# _quarto.yml

project:
  type: website
  output-dir: docs

execute:
  eval: false # Explicitly disable all code execution for the project
  freeze: true

website:
  title: "Bioconductor Slack Export"
  navbar:
    title: false
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "General"
        menu:
          - text: "General"
            href: general.qmd
          - text: "Random"
            href: random.qmd
          - text: "Introductions"
            href: introductions.qmd
          - text: "Jobs"
            href: jobs.qmd
          - text: "Papers & Preprints"
            href: papersandpreprints.qmd
          - text: "Welcome Material"
            href: FCF05URJ0P021Welcome_material.qmd

      - text: "Development"
        menu:
          - text: "Developers Forum"
            href: developers-forum.qmd
          - text: "Bioc Git"
            href: bioc_git.qmd
          - text: "Bioc Builds"
            href: bioc-builds.qmd
          - text: "Package Submissions"
            href: package_submissions.qmd
          - text: "R7 Object System"
            href: r7.qmd
          - text: "GitHub Actions"
            href: github-actions.qmd
          - text: "WASM"
            href: wasm.qmd
          - text: "CPP"
            href: cpp.qmd
          - text: "GPUs"
            href: gpus.qmd
          - text: "Cloud WG"
            href: cloud-working-group.qmd
          - text: "Cloud GitHub Actions Subgroup"
            href: cloud-github-actions-subgroup.qmd
          - text: "Containers"
            href: containers.qmd
          - text: "Singularity"
            href: singularity.qmd
          - text: "ARM Linux"
            href: arm-linux.qmd
          - text: "BiocCheck-a-thon"
            href: bioccheck-a-thon.qmd
          - text: "BiocVerse"
            href: biocverse.qmd
          - text: "Bioc2u"
            href: bioc2u.qmd
          - text: "GitDevTest"
            href: gitdevtest.qmd
          - text: "New Packages (Archived?)"
            href: new_packages.qmd
          - text: "Null Ranges"
            href: nullranges.qmd
          - text: "OMA Developers"
            href: oma-developers.qmd
          - text: "Other Distros"
            href: other-distros.qmd
          - text: "Package Submission (Old?)"
            href: package-submission.qmd
          - text: "Palm Tree"
            href: palmtree.qmd
          - text: "RCWL"
            href: rcwl.qmd
          - text: "RHDF5 Client"
            href: rhdf5client.qmd
          - text: "RowDataFix"
            href: rowdatafix.qmd

      - text: "Conferences & Events"
        menu:
          - text: "BioC Workshops"
            href: biocworkshops.qmd
          - text: "BioC 2018"
            href: bioc2018.qmd
          - text: "BioC 2018 Workshops"
            href: bioc2018-workshops.qmd
          - text: "BioC 2019"
            href: bioc2019.qmd
          - text: "BioC 2020"
            href: bioc2020.qmd
          - text: "BioC 2020 Annotation Wksh"
            href: bioc2020-bioconductor-100_introduction-to-bioconductor-annotation-resources.qmd
          - text: "BioC 2020 BoF 10sr"
            href: bioc2020-bof-10sr.qmd
          - text: "BioC 2020 Workshops"
            href: bioc2020-workshops.qmd
          - text: "BioC 2021"
            href: bioc2021.qmd
          - text: "BioC 2021 Microbiome Wksh"
            href: microbiome_experiment_bioc2021.qmd
          - text: "BioC 2022"
            href: bioc2022.qmd
          - text: "BioC 2024"
            href: bioc2024.qmd
          - text: "BioC Conf Everyone"
            href: bioc-conference-everyone.qmd
          - text: "BioC Conf Non-Competing"
            href: bioc-conference-noncompeting.qmd
          - text: "BioC Conf Sponsorship"
            href: bioc-conference-sponsorship.qmd
          - text: "BioC Conf Web"
            href: bioc-conference-web.qmd
          - text: "BioCAsia"
            href: biocasia.qmd
          - text: "BioCAsia 2020"
            href: biocasia2020.qmd
          - text: "BioCAsia 2021"
            href: biocasia2021.qmd
          - text: "BioCAsia 2022"
            href: biocasia2022.qmd
          - text: "BioCAsia 2023"
            href: biocasia2023.qmd
          - text: "Calendar Events"
            href: calendar-events.qmd
          - text: "CSAMA 2023"
            href: csama2023.qmd
          - text: "EuroBioC 2019"
            href: eurobioc2019.qmd
          - text: "EuroBioC 2020"
            href: eurobioc2020.qmd
          - text: "EuroBioC 2020 Chairs"
            href: eurobioc2020-chairs.qmd
          - text: "EuroBioC 2020 iSEE Transcripts"
            href: eurobioc2020-isee-transcripts.qmd
          - text: "EuroBioC Everyone"
            href: eurobioc-conference-everyone.qmd
          - text: "Events"
            href: events.qmd
          - text: "Hacktoberfest"
            href: hacktoberfest.qmd
          - text: "IBT2025 KushCentreGroup1"
            href: ibt2025-kushcentregroup1.qmd
          - text: "ISMB OSCA"
            href: ismb-osca.qmd
          - text: "Meetups"
            href: meetups.qmd

      - text: "Community & Outreach"
        menu:
          - text: "Accessible Vis"
            href: accessible-vis.qmd
          - text: "Beginners & Schools"
            href: beginners_and_schools.qmd
          - text: "Bioc Africa"
            href: bioc_africa.qmd
          - text: "Carpentries"
            href: carpentries.qmd
          - text: "Community Advisory Board"
            href: community-advisory-board.qmd
          - text: "Developers Mentorship"
            href: developers-mentorship.qmd
          - text: "DiverseBioc"
            href: diversebioc.qmd
          - text: "Education & Training"
            href: education-and-training.qmd
          - text: "Humble Brag"
            href: humble-brag.qmd
          - text: "Mentorship Program Microstasis"
            href: mentorship_program_microstasis.qmd
          - text: "Outreachy"
            href: outreachy.qmd
          - text: "Queer Bioc"
            href: queer-bioc.qmd
          - text: "R-Ladies"
            href: r-ladies.qmd
          - text: "Social Media"
            href: social-media.qmd
          - text: "Support Site"
            href: support-site.qmd
          - text: "Technical Advisory Board"
            href: tech-advisory-board.qmd

      - text: "Projects & Topics"
        menu:
          - text: "Alpha Missense"
            href: alpha-missense.qmd
          - text: "Annotation Roadmap"
            href: annotation-roadmap.qmd
          - text: "Anvil"
            href: anvil.qmd
          - text: "ArtifactDB"
            href: artifactdb.qmd
          - text: "Big Data Rep"
            href: bigdata-rep.qmd
          - text: "BioC Books"
            href: biocbooks.qmd
          - text: "BioC Challenges"
            href: biocchallenges.qmd
          - text: "BioC Classes"
            href: biocclasses.qmd
          - text: "BioC Connect"
            href: bioc-connect.qmd
          - text: "BioC Hubs"
            href: biochubs.qmd
          - text: "BioC Python"
            href: biocpython.qmd
          - text: "BioC Website"
            href: biocwebsite.qmd
          - text: "BugSigDB"
            href: bugsigdb.qmd
          - text: "Cancer Data"
            href: cancerdata.qmd
          - text: "Cancer Related"
            href: cancer-related.qmd
          - text: "cBioPortal Data R"
            href: cbioportal-data-r.qmd
          - text: "Channel Requests"
            href: channel-requests.qmd
          - text: "Clinical"
            href: clinical.qmd
          - text: "Cool Vis"
            href: cool-vis.qmd
          - text: "Cyto Spec Book"
            href: cyto-spec-book.qmd
          - text: "Database"
            href: database.qmd
          - text: "Delayed Array"
            href: delayed_array.qmd
          - text: "Doc Translation"
            href: documentation-translation.qmd
          - text: "EasyLift"
            href: easylift.qmd
          - text: "EasyPlot"
            href: easyplot.qmd
          - text: "EDAM Collaboration"
            href: edam-collaboration.qmd
          - text: "Elixir"
            href: elixir.qmd
          - text: "Funding"
            href: funding.qmd
          - text: "GenAI Bioc"
            href: genai-bioc.qmd
          - text: "GSEABase"
            href: gseabase.qmd
          - text: "GWAS Data"
            href: gwas-data.qmd
          - text: "Hash Multi Species"
            href: hash-multi-species.qmd
          - text: "HCA Clustering"
            href: hca_clustering.qmd
          - text: "HCA Data Insights"
            href: hca-data-insights.qmd
          - text: "HCA RFA"
            href: hca_rfa.qmd
          - text: "Histopathology Image Analysis"
            href: histopathology-image-analysis.qmd
          - text: "HuBMAPr"
            href: hubmapr.qmd
          - text: "Image Analysis"
            href: image-analysis.qmd
          - text: "Industry"
            href: industry.qmd
          - text: "iSEE"
            href: isee.qmd
          - text: "LLMs for Bioc"
            href: llms-for-bioc.qmd
          - text: "Long Read Study Group"
            href: long-read-study-group.qmd
          - text: "Longread"
            href: longread.qmd
          - text: "Machine Learning"
            href: machine-learning.qmd
          - text: "MAE Discussion"
            href: mae-discussion.qmd
          - text: "MAE Updates"
            href: mae-updates.qmd
          - text: "Mass Spectrometry"
            href: mass-spectrometry.qmd
          - text: "Metabolomics"
            href: metabolomics.qmd
          - text: "MiaVerse"
            href: miaverse.qmd
          - text: "MiaVerse Admins"
            href: miaverse-admins.qmd
          - text: "Microbiome/Metagenome"
            href: microbiome_metagenome.qmd
          - text: "Microsoft Azure Collaboration"
            href: microsoft-azure-collaboration.qmd
          - text: "MolEvolvR"
            href: molevolvr.qmd
          - text: "Multiomics"
            href: multiomics.qmd
          - text: "OmicIdx"
            href: omicidx.qmd
          - text: "OSCA Book"
            href: osca-book.qmd
          - text: "OSCA Book Club"
            href: osca-book-club.qmd
          - text: "Pangenome"
            href: pangenome.qmd
          - text: "Pharmacogenomics"
            href: pharmacogenomics.qmd
          - text: "Proteomics"
            href: proteomics.qmd
          - text: "Ragged Experiment"
            href: raggedexperiment.qmd
          - text: "Reproducibility"
            href: reproducibility.qmd
          - text: "Salmon2Bioc"
            href: salmon2bioc.qmd
          - text: "Scalability"
            href: scalability.qmd
          - text: "SC Batch Correction"
            href: sc-batch-correction.qmd
          - text: "SC Repertoires"
            href: sc-repertoires.qmd
          - text: "SC Signature"
            href: sc-signature.qmd
          - text: "SC Velocity"
            href: sc-velocity.qmd
          - text: "Shiny"
            href: shiny.qmd
          - text: "Single Cell Experiment"
            href: singlecellexperiment.qmd
          - text: "Single Cell Queries"
            href: singlecell-queries.qmd
          - text: "Spatial"
            href: spatial.qmd
          - text: "Spatial Data Devel"
            href: spatialdata-devel.qmd
          - text: "Spatial Experiment"
            href: spatialexperiment.qmd
          - text: "Spatial Experiment Devel"
            href: spatialexperiment-devel.qmd
          - text: "Spatial Interoperability"
            href: spatial-interoperability.qmd
          - text: "Sweave2Rmd"
            href: sweave2rmd.qmd
          - text: "Terra"
            href: terra.qmd
          - text: "TeSS Integration"
            href: tess-integration.qmd
          - text: "Tidiness in Bioc"
            href: tidiness_in_bioc.qmd
          - text: "Translation FR"
            href: translation-fr.qmd
          - text: "Tree-like SE"
            href: tree-like-se.qmd
          - text: "Voyager"
            href: voyager.qmd
          - text: "Workflows"
            href: workflows.qmd
          - text: "Zarr"
            href: zarr.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    css: styles.css
    # Add this engine setting for HTML output
    engine: markdown # Ensure qmd files are treated as plain markdown
