---
title: "#beginners_and_schools"
---

## 2021-05-07

**Aedin Culhane** (16:00:02):
> @Aedin Culhane has joined the channel

**Aedin Culhane** (16:00:02):
> set the channel description: This channel is a place to provide and discuss resources for teaching R and Bioconductor to high school, for undergraduate summer projects, or beginner resources to help welcome non-statistical/computational collaborators to R and Bioconductor

**Aedin Culhane** (16:00:34):
> The is a nice video of an 8th graders experience with R. I think the integration of google sheets and R might be a nice mini project for high school or summer students, who just want to learn how to make a few plots in R[https://www.rstudio.com/resources/rstudioconf-2020/a-high-school-student-s-journey-to-bring-r-into-the-classroom/](https://www.rstudio.com/resources/rstudioconf-2020/a-high-school-student-s-journey-to-bring-r-into-the-classroom/)
  - Attachment (rstudio.com): [A high school student’s journey to bring R into the classroom](https://www.rstudio.com/resources/rstudioconf-2020/a-high-school-student-s-journey-to-bring-r-into-the-classroom/)
> My 8th grade capstone project introduced me to R. The project was a data visualization about breakfast tacos. I used R and other web based tools.


## 2021-05-11

**Megha Lal** (16:43:44):
> @Megha Lal has joined the channel


## 2021-05-23

**Jonas Schulte-Schrepping** (08:09:30):
> @Jonas Schulte-Schrepping has joined the channel


## 2021-06-04

**Flavio Lombardo** (05:50:38):
> @Flavio Lombardo has joined the channel


## 2021-06-05

**KP** (17:21:00):
> @KP has joined the channel


## 2021-07-19

**Leo Lahti** (16:51:21):
> @Leo Lahti has joined the channel


## 2021-07-23

**Batool Almarzouq** (15:51:17):
> @Batool Almarzouq has joined the channel


## 2021-07-26

**Frank** (20:17:20):
> @Frank has joined the channel


## 2021-09-06

**Eddie** (08:21:47):
> @Eddie has joined the channel

**Eddie** (08:35:37):
> @Eddie has left the channel


## 2021-09-27

**Mikey C** (09:49:12):
> @Mikey C has joined the channel


## 2021-11-08

**Paula Nieto García** (03:18:40):
> @Paula Nieto García has joined the channel

**Marc Elosua** (06:25:29):
> @Marc Elosua has joined the channel


## 2022-01-28

**Oliver Voogd** (00:44:04):
> @Oliver Voogd has joined the channel

**Megha Lal** (11:11:46):
> @Megha Lal has left the channel


## 2022-02-23

**Paulina Paiz** (10:46:26):
> @Paulina Paiz has joined the channel


## 2022-02-25

**Joshua Sodicoff** (16:19:50):
> @Joshua Sodicoff has joined the channel


## 2022-03-30

**Mercedes Guerrero-Murillo** (06:46:11):
> @Mercedes Guerrero-Murillo has joined the channel


## 2022-04-12

**Vivian Chu** (13:58:40):
> @Vivian Chu has joined the channel


## 2022-04-23

**Arda Keles** (15:55:15):
> @Arda Keles has joined the channel


## 2022-05-17

**Alan Aw** (20:48:34):
> @Alan Aw has joined the channel


## 2022-06-17

**George Odette** (17:23:50):
> @George Odette has joined the channel


## 2022-07-22

**Gary Sieling** (14:44:59):
> @Gary Sieling has joined the channel


## 2022-07-28

**Krithika Bhuvanesh** (13:50:05):
> @Krithika Bhuvanesh has joined the channel


## 2022-10-10

**Mercilena Benjamin** (13:54:49):
> @Mercilena Benjamin has joined the channel


## 2022-11-08

**Nicolas** (20:37:59):
> @Nicolas has joined the channel

**Nicolas** (20:44:09):
> @Nicolas has left the channel


## 2022-11-23

**ashish tp53** (01:07:53):
> @ashish tp53 has joined the channel


## 2022-12-12

**Zainab Ashimiyu-Abdusalam** (04:47:47):
> @Zainab Ashimiyu-Abdusalam has joined the channel

**Carlos José Ferreira da Silva** (18:54:48):
> @Carlos José Ferreira da Silva has joined the channel


## 2022-12-20

**Krithika Bhuvanesh** (13:25:16):
> @Krithika Bhuvanesh has left the channel


## 2023-01-18

**José Basílio** (13:08:53):
> @José Basílio has joined the channel


## 2023-01-21

**Hien** (16:01:19):
> @Hien has joined the channel


## 2023-01-31

**Rebecca Butler** (15:06:57):
> @Rebecca Butler has joined the channel


## 2023-02-22

**Sue McClatchy** (19:32:35):
> @Sue McClatchy has joined the channel


## 2023-04-17

**Leo Lahti** (15:23:35):
> ***Multi-omic data analysis with R/Bioconductor: Oulu Summer School, June 19-21, 2023 (Mon-Wed)*** For program & schedule, travel tips, registration, and other details, see the
> course homepage[https://microbiome.github.io/course_2023_oulu](https://microbiome.github.io/course_2023_oulu)


## 2023-05-06

**Sarah Parker** (14:03:50):
> @Sarah Parker has joined the channel


## 2023-05-15

**Michael Lynch** (07:55:58):
> @Michael Lynch has joined the channel


## 2023-05-19

**Umar Ahmad** (23:35:43):
> @Umar Ahmad has joined the channel


## 2023-06-13

**Leo Lahti** (08:28:15):
> Any tips on good data containers for metabolome data? (or is SummarizedExperiment the way to go?)


## 2023-07-04

**Shruti Shah** (06:17:46):
> @Shruti Shah has joined the channel


## 2023-08-02

**Beth Cimini** (08:20:03):
> @Beth Cimini has joined the channel


## 2023-08-04

**irem Kahveci** (17:38:47):
> @irem Kahveci has joined the channel


## 2023-08-10

**mahamtariq58** (07:14:09):
> @mahamtariq58 has joined the channel


## 2023-08-20

**Federica Gazzelloni** (10:37:49):
> @Federica Gazzelloni has joined the channel


## 2023-08-28

**Abdullah Al Nahid** (15:06:29):
> @Abdullah Al Nahid has joined the channel


## 2023-09-04

**Anna Lewkowicz** (16:50:20):
> @Anna Lewkowicz has joined the channel


## 2023-09-15

**Leo Lahti** (04:53:08):
> @Leo Lahti has joined the channel


## 2024-01-24

**Manuel Barrios Izás** (11:31:07):
> @Manuel Barrios Izás has joined the channel


## 2024-03-09

**Cherishma Subhasa** (20:18:37):
> @Cherishma Subhasa has joined the channel


## 2024-05-05

**Ifra** (05:08:01):
> @Ifra has joined the channel


## 2024-07-28

**Precious Orakwe** (07:39:32):
> @Precious Orakwe has joined the channel

**Precious Orakwe** (07:40:04):
> Hello, good day everyone, I'm happy to be here


## 2024-08-12

**Enrique Mondragon** (11:18:11):
> @Enrique Mondragon has joined the channel


## 2024-10-18

**Oluwaseyi Ashaka** (16:55:39):
> @Oluwaseyi Ashaka has joined the channel


## 2024-10-23

**Hong Qin** (17:45:49):
> @Hong Qin has joined the channel


## 2024-11-07

**Malvika Kharbanda** (22:09:26):
> @Malvika Kharbanda has joined the channel


## 2024-11-23

**Rachel Wise** (01:04:49):
> @Rachel Wise has joined the channel


## 2024-12-29

**Andrew Su** (12:19:15):
> @Andrew Su has joined the channel


## 2025-01-09

**Ammar Sabir Cheema** (11:28:46):
> @Ammar Sabir Cheema has joined the channel


## 2025-01-25

**Rahman Nurudeen** (10:26:55):
> @Rahman Nurudeen has joined the channel


## 2025-02-20

**Mikaila Chetty** (02:33:00):
> @Mikaila Chetty has joined the channel


## 2025-03-17

**Sunil Nahata** (09:25:46):
> @Sunil Nahata has joined the channel


## 2025-03-18

**Andres Wokaty** (14:26:11):
> @Andres Wokaty has joined the channel

**Nicolo** (14:58:25):
> @Nicolo has joined the channel


## 2025-03-19

**Sivaranjani Balachander** (02:37:26):
> @Sivaranjani Balachander has joined the channel


## 2025-03-28

**Khadija Juma** (07:27:00):
> @Khadija Juma has joined the channel


## 2025-04-23

**Silvia González** (08:37:35):
> @Silvia González has joined the channel
