---
title: "#bioc-conference-sponsorship"
---

## 2019-12-12

**Aedin Culhane** (15:05:03):
> @Aedin Culhane has joined the channel

**Aedin Culhane** (15:05:03):
> set the channel description: bioconductor conference sponsorship

**Simina Boca** (15:05:27):
> @Simina Boca has joined the channel

**Qian Liu** (15:05:27):
> @Qian Liu has joined the channel

**Qian Liu** (15:05:45):
> :+1:

**Nitesh Turaga** (15:07:41):
> @Nitesh Turaga has joined the channel

**Aedin Culhane** (15:19:18):
> Meeting minutes[https://docs.google.com/document/d/1Ce_6lCh14YSDuvo1mSpffYDLRWVjcPpQxfZ5Yc0a0QU/edit#](https://docs.google.com/document/d/1Ce_6lCh14YSDuvo1mSpffYDLRWVjcPpQxfZ5Yc0a0QU/edit#)

**Qian Liu** (15:34:00):
> Hi@Aedin Culhane, I have checked 5 companies.`CZI`and`Illumina`has no previous sponsorship.`F1000`has previously sponsored but I already have contacts there about this issue, so I would like to reach out. For the`Rstudio`and`Rconsortium`who has previously sponsored, if anyone who already contacted last year or wants to take them this year, I am happy to uncheck from my list.

**Martin Morgan** (16:37:31):
> @Martin Morgan has joined the channel

**Levi Waldron** (16:44:04):
> @Levi Waldron has joined the channel

**Erica Feick** (16:44:23):
> @Erica Feick has joined the channel


## 2019-12-13

**Matt Brauer** (02:40:16):
> @Matt Brauer has joined the channel

**Fred Boehm** (11:25:28):
> @Fred Boehm has joined the channel

**Aedin Culhane** (11:26:10):
> Thanks@Qian Liu. Thanks for putting your name beside companies in the sheet.

**Sean Davis** (11:28:59):
> @Sean Davis has joined the channel

**Rafael Irizarry** (11:28:59):
> @Rafael Irizarry has joined the channel

**Simone Bell** (11:28:59):
> @Simone Bell has joined the channel

**Fred Boehm** (11:37:47):
> @Aedin CulhaneI found a couple examples for wordings of diversity scholarships. Is there a document where I should share them?

**Aedin Culhane** (12:39:10) (in thread):
> Thanks@Fred Boehm. Maybe add it into the minutes doc so everything is together. Or create a new doc and link it within the minutes doc


## 2019-12-16

**Fred Boehm** (09:39:05) (in thread):
> Sounds good. I've now added (to the meeting notes) a hyperlink to a new google doc for diversity scholarship language examples:[https://docs.google.com/document/d/1lKw8Tzr_7KpFi-2COSaH6Ddy-n10GCuklYEbRBwN0Lw/edit?usp=sharing](https://docs.google.com/document/d/1lKw8Tzr_7KpFi-2COSaH6Ddy-n10GCuklYEbRBwN0Lw/edit?usp=sharing)


## 2020-01-07

**Qian Liu** (00:25:32):
> Hi@Aedin Culhaneand other organizing members, based on the last sponsorship meeting, I have created the following google doc for a possible job fair if interested. Would be happy to hear any comments about the plausibility.[https://docs.google.com/document/d/1m2tjXw6zLSplSwoSYRQYiVjjvYftFC88MgluSSkk9YQ/edit?usp=sharing](https://docs.google.com/document/d/1m2tjXw6zLSplSwoSYRQYiVjjvYftFC88MgluSSkk9YQ/edit?usp=sharing)


## 2020-01-08

**Martin Morgan** (22:34:55) (in thread):
> I like the idea of a job fair of some sort; not just for external purposes but also for the project as a whole and for post-docs / etc in individual research labs. Maybe a short 'talk' on careers in bioinformatics...? (It could help the project to actually think about career paths for people who join the Bioconductor core team, for instance, in addition to the career paths for less academic opportunities like working in a core facility or in pharma)


## 2020-01-21

**Qian Liu** (17:08:36) (in thread):
> Sorry I wasn't following this conversion closely. I think having a "talk" about careers would be a really nice touch. For a general bioinformatics community and Bioconductor developers / users. Wasn't sure about which invited speaker would be interested, or maybe a small panel discussion, or anyone from the#jobschannel?


## 2020-01-30

**Aedin Culhane** (12:17:03):
> Please can others send out letters

**Simina Boca** (14:33:19):
> Yes! Shall I just go ahead and email some and list my name?


## 2020-02-04

**Aedin Culhane** (12:55:44):
> Three levels of sponsorship are available are:
> ●***Platinum $10,000 USD ***o  Poster session or awards will be named after these donors.
> o  Highest recognition, using your logo, in the promotional material.
> o  Two invitations to attend the speaker dinner.
> o  Up to 8 free registrations.
> o  A thank-you tweet including your preferred Twitter handle.
> o  A table during the poster session and social hours.
> ●***Gold: $5,000 USD***o  Top recognition, using your logo, in the promotional material.
> o  Up to 5 free registrations.
> o  A thank-you tweet including your preferred Twitter handle.
> o  A table during the poster session and social hours.
> ●***Silver: $1,000 USD***o  Sponsor names will be listed in the promotional material. 
> o  Academic discount on 2 registrations.
> o  A thank-you tweet including your preferred Twitter handle


## 2020-02-07

**Simina Boca** (14:54:40):
> Contacted a few people but no one's agreed on sponsorship yet:disappointed:


## 2020-02-13

**Noor Pratap Singh** (00:20:06):
> @Noor Pratap Singh has joined the channel


## 2020-02-14

**Aedin Culhane** (08:55:12):
> Thanks, may send a reminder in a week or two

**Aedin Culhane** (10:24:59):
> Biogen are sponsoring us.  Bluebird are interested


## 2020-02-16

**Qian Liu** (09:11:38):
> F1000 is sponsoring!

**Qian Liu** (09:12:10):
> R consortium and rstudio are interested.

**Levi Waldron** (17:18:31):
> Sounds like a happy Valentine’s day!


## 2020-03-06

**Qian Liu** (21:38:48):
> I can't find any contact email / phone for CZI. I have tried to send message on LinkedIn to their director of operations, but got no response, and couldn't follow up with another message for not being connected. I wonder if anyone in the Bioc community could possibly know someone from CZI and reach out directly, that would be great!


## 2020-03-10

**Aedin Culhane** (01:17:49):
> @Martin Morganwho is the contact at CZI for sponsorship?


## 2020-03-11

**Martin Morgan** (03:44:21):
> I don't have any insight into how or if CZI sponsors conferrences, sorry...

**Martin Morgan** (03:48:04):
> The R Consortium will not reach a decision about coordinated funding for all Bioc conferences while the consequences of COVID-19 are not clear. They did however urge individual conferences to apply for support through the[RUGS program](https://www.r-consortium.org/projects/r-user-group-support-program), so I've done that for BioC2020@Qian Liuwill you do the same for BioC Asia?
  - Attachment (R Consortium): [R User Group Support Program - R Consortium](https://www.r-consortium.org/projects/r-user-group-support-program)
> The User Group Program Welcome to RUGS 2020, the R Consortium’s R User Group and Small Conference Support Program for 2020. We at the R Consortium believe that nothing is...


## 2020-03-12

**Qian Liu** (06:34:19):
> Thanks@Martin Morganfor the info. I'll do that for BiocAsia in a little bit.


## 2020-03-24

**Nitesh Turaga** (09:05:38):
> @Nitesh Turaga has left the channel


## 2020-06-06

**Olagunju Abdulrahman** (19:56:58):
> @Olagunju Abdulrahman has joined the channel


## 2020-07-08

**Qian Liu** (10:40:36):
> Hi@Martin Morgandid you get an response from the R Consortium grant application?


## 2020-07-24

**Levi Waldron** (04:26:34):
> set the channel topic: For sponsorship-related discussions during planning of BioC2020. For general conference discussion during the conference use #bioc2020 and for workshop-specific discussion use #bioc2020-workshops.

**Sean Davis** (14:35:51):
> Just an FYI, I added the ISB-CGC folks as a sponsor. They are picking up the tab for the workshop runtimes.


## 2020-07-25

**Levi Waldron** (03:38:15):
> That’s awesome, Sean.


## 2020-08-01

**Chiaowen Joyce Hsiao** (15:31:16):
> @Chiaowen Joyce Hsiao has joined the channel


## 2020-09-09

**frederick boehm** (12:29:39):
> @frederick boehm has joined the channel


## 2020-10-22

**Amarinder Singh Thind** (08:29:09):
> @Amarinder Singh Thind has joined the channel


## 2020-10-29

**Pinki Dey** (01:38:33):
> @Pinki Dey has joined the channel


## 2020-12-02

**Konstantinos Geles (Constantinos Yeles)** (05:42:11):
> @Konstantinos Geles (Constantinos Yeles) has joined the channel


## 2021-01-15

**Aedin Culhane** (17:11:31):
> Bioc20201[sponsorship organization document](https://docs.google.com/document/d/1Ce_6lCh14YSDuvo1mSpffYDLRWVjcPpQxfZ5Yc0a0QU/edit)which has links to sheet and letter

**Aedin Culhane** (17:20:39):
> set the channel topic: For sponsorship-related discussions during planning of BioC2020. For general conference discussion during the conference use #bioc2020 and for workshop-specific discussion use #bioc2020-workshops.

**Aedin Culhane** (17:21:26):
> set the channel description: For sponsorship-related discussions during planning of BioC2021 For general conference discussion during the conference use #bioc2021


## 2021-01-21

**Chiaowen Joyce Hsiao** (08:15:46):
> Dear conference organizers - I am reaching out on behalf of Moderna for Bioc2021 sponsorship. We greatly appreciate contributions from the Bioconductor community over the years, and our Statistics group is eager to participate in the 2021 conference. Please let me know how we should proceed from here. Thank you!

**Aedin Culhane** (12:30:57) (in thread):
> Thanks for reaching out.  I would be delighted to help you. I am on the sponsorship committee and can send you information about sponsorship packages.

**Chiaowen Joyce Hsiao** (19:18:37) (in thread):
> Thank you Aedin! My email is[chsiao@modernatx.com](mailto:chsiao@modernatx.com). Look forward to hearing from you.


## 2021-01-22

**Annajiat Alim Rasel** (15:43:10):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-08

**Aedin Culhane** (17:45:42):
> @Levi Waldron@Martin Morganjust a wee reminder to send out sponsorship invites ;-))

**Aedin Culhane** (17:46:13) (in thread):
> Thanks, sorry for the delay but I got the letter to you today.

**Aedin Culhane** (17:47:03):
> @Marc RJ Carlsoninviting you in case there are local seattle companies that we should invite to sponsor Bioc2021

**Marc RJ Carlson** (17:47:06):
> @Marc RJ Carlson has joined the channel


## 2021-02-09

**Mikhail Dozmorov** (20:23:52):
> @Mikhail Dozmorov has joined the channel


## 2021-02-10

**Aedin Culhane** (19:42:06):
> BastBit Global have confirmed Gold level sponsorship of Bioc2021:fast_parrot::tada::heart:

**Aedin Culhane** (19:50:44):
> Moderna have confirmed Platinum level sponsorship:fast_parrot::fast_parrot::fast_parrot:of Bioc2021:heart::heart::fast_parrot:


## 2021-02-11

**Simina Boca** (17:52:52):
> Yay!!!


## 2021-02-22

**Aedin Culhane** (17:15:55):
> Volunteers to submit Novartis and Abbvie sponsorship forms??@Levi Waldron

**Aedin Culhane** (17:16:01):
> Abbvie is[https://www.abbvie.com/responsibility/abbvie-grants/how-to-apply-for-grant.html](https://www.abbvie.com/responsibility/abbvie-grants/how-to-apply-for-grant.html)


## 2021-02-23

**Levi Waldron** (04:39:30) (in thread):
> I submitted Novartis!


## 2021-04-20

**Aedin Culhane** (11:54:06):
> Genentech have confirmed Gold Level Sponsorship of Bioc2021:fast_parrot::heart::tada:


## 2021-05-04

**Aedin Culhane** (09:48:21):
> Maze Therapeutics have confirmed Gold Level Sponsorship at Bioc2021:fast_parrot::heart::heart::tada:


## 2021-05-06

**Aedin Culhane** (07:29:40):
> F1000 have confirmed silver sponsorship at Bio2021:heart::fast_parrot:

**Mikhail Dozmorov** (08:05:02):
> Maze and F1000 are on the website. Can we ask if Maze has a different logo, as a horizontal rectangle, to match others?


## 2021-05-11

**Aedin Culhane** (16:09:50):
> Takeda are confirmed as a Gold level Sponsor of Bioc2021:heart::fast_parrot::heart::tada:

**Megha Lal** (16:43:50):
> @Megha Lal has joined the channel


## 2021-05-17

**Simone Bell** (10:52:41):
> Tercen Dublin has confirmed Silver level sponsorship at BioC2021:boom::tada::star:

**Sean Davis** (11:15:09):
> It might be worth formally extending an offer to all sponsors to meet after the conference. Some sponsors may want to get more involved in the project and may have additional resources (or collaboration) to bring to the table.

**Mikhail Dozmorov** (20:40:04) (in thread):
> Just to make sure I add the correct info to the website - this is the company[https://www.tercen.com/](https://www.tercen.com/)?
  - Attachment (Tercen): [Next Generation Data Analytics Platform](https://www.tercen.com/)
> Tercen is a rapid and flexible, drag and drop data analytics platform that requires no coding knowledge. It easily allows users to share, integrate, compare and build upon large data sets in a simple and user friendly environment, all online and in the cloud.


## 2021-05-18

**Simone Bell** (04:08:34) (in thread):
> Yes, this is correct. Many thanks.

**Simone Bell** (04:08:36):
> Great point, thank you! We shall be happy to discuss this more in detail with the committee.

**Aedin Culhane** (11:42:38) (in thread):
> :fast_parrot::heart:

**Mikhail Dozmorov** (20:03:16):
> First draft of the Sponsors page is up. Any suggestions what to improve?[https://bioc2021.bioconductor.org/sponsors/](https://bioc2021.bioconductor.org/sponsors/)
  - Attachment (bioc2021.bioconductor.org): [Sponsors](https://bioc2021.bioconductor.org/sponsors/)
> Sponsors


## 2021-05-19

**Simone Bell** (15:27:30):
> Hey Mikhail, the page looks great to me. Thanks a lot! I would perhaps make the Maze and F1000 logos slightly smaller, so that they have the same height as the other 3 gold ones, if possible.

**Simone Bell** (15:27:37):
> :star-struck:

**Mikhail Dozmorov** (16:26:11) (in thread):
> Proportions are always tricky. Now, they are the same height, plus Maze horizontal logo looks better.


## 2021-05-20

**Aedin Culhane** (01:51:34):
> R consortium RUGS are a silver sponsor:fast_parrot::heart:


## 2021-05-27

**Aedin Culhane** (05:51:14):
> Thanks to Microsoft for gold sponsorship:fast_parrot:
  - File (JPEG): [Image from iOS](https://community-bioc.slack.com/files/U34P8RS3B/F0234GTMWER/image_from_ios.jpg)

**Aedin Culhane** (05:54:31) (in thread):
> Good idea but meet with whom? The cab and tab? Speakers? Also how can that bear be done by zoom ?Have a Birds of a feather or panel discussion.

**Sean Davis** (10:46:16) (in thread):
> One or two people from the organizing committee who represent the Bioconductor project meet with each sponsor (or limit to highest-level sponsors) individually.


## 2021-06-17

**Aedin Culhane** (10:27:48):
> :fast_parrot::fast_parrot::fast_parrot::heart::heartpulse::fast_parrot::fast_parrot::fast_parrot:Thanks to Nanostring for platinum sponsorship


## 2021-06-24

**Aedin Culhane** (09:34:15):
> Thanks to Novartis for gold sponsorship:heart::fast_parrot::fast_parrot::heart:

**Sean Davis** (10:23:17):
> @Aedin Culhaneis on a:fast_parrot:kick. Appropriate use, of course!


## 2021-07-20

**Aedin Culhane** (18:19:52):
> Thanks so much to Bluebird Bio for gold sponsorship:heart::fast_parrot::fast_parrot::heart:

**Aedin Culhane** (18:21:04):
> Thanks to StickerMule and CRC Press for in kind donations.  CRC Press have donated books, and StickerMule have provided in kind credit for stickers… Yeah:fiesta_parrot:

**Aedin Culhane** (18:21:54):
> Thanks to Bristol-Myers Squibb for silver conference sponsorship:fiesta_parrot::heart:


## 2021-12-14

**Megha Lal** (08:24:19):
> @Megha Lal has left the channel


## 2022-02-23

**Paulina Paiz** (10:44:55):
> @Paulina Paiz has joined the channel


## 2022-03-03

**Mahmoud Ahmed** (02:40:50):
> @Mahmoud Ahmed has joined the channel

**Daniela Cassol** (02:40:50):
> @Daniela Cassol has joined the channel

**Krithika Bhuvanesh** (02:40:51):
> @Krithika Bhuvanesh has joined the channel

**Jenny Drnevich** (02:40:51):
> @Jenny Drnevich has joined the channel

**Simone Bell** (02:42:52):
> Moderna Therapeutics has confirmed platinum sponsorship for Bioc2022!!:tada::star:

**Jenny Drnevich** (11:00:37):
> @Simone Bellyou've inspired me to start sending out sponsorship requests! I've done two full requests (Nanostring and Maze) and made two informal contacts (10X Genomics and F1000) to ask who I should  send the request to.

**Simone Bell** (11:38:01):
> Oh wow. Thanks a lot, Jenny!!


## 2022-03-04

**Jenny Drnevich** (16:28:33):
> 10X Genomics is a hard pass. I'm a bit surprised but maybe they view us as a competitor to their Computational Biology team? Here is their email and my reply:
> 
> Hi Jess,
> 
> Thank you for letting me know. I believe we have all the keynote speakers filled. All other talk/presentations will be by submission. If anyone from your Computational Biology team would like to submit a talk, the deadline is March 9th.[https://bioc2022.bioconductor.org/submissions/](https://bioc2022.bioconductor.org/submissions/)All the best,
> Jenny***From:***Jessica Dines <[jessica.dines@10xgenomics.com](mailto:jessica.dines@10xgenomics.com)>***Sent:***Friday, March 4, 2022 3:19 PM***To:***Drnevich, Jenny <[drnevich@illinois.edu](mailto:drnevich@illinois.edu)>***Cc:***Heather Eckart <[heather.eckart@10xgenomics.com](mailto:heather.eckart@10xgenomics.com)>; Melissa Leone <[melissa.leone@10xgenomics.com](mailto:melissa.leone@10xgenomics.com)>; Kara Pivarski <[kara.pivarski@10xgenomics.com](mailto:kara.pivarski@10xgenomics.com)>***Subject:***Re: Contact at 10X in charge of Conference sponsorships?
> 
> Hi Jenny,
> 
> I hope all is well. Heather and I touched base on the Bioconducor opportunity. While we cannot sponsor the event this year, please keep us informed about where the conference will be located and whether you are seeking speakers. It's possible that someone from the 10x Genomics Computational Biology team could contribute by way of a presentation, if desired.
> 
> Thank you for thinking of us,
> Jess Dines
  - Attachment (bioc2022.bioconductor.org): [Submissions](https://bioc2022.bioconductor.org/submissions/)
> Submissions


## 2022-03-05

**Simone Bell** (11:01:13):
> @Jenny DrnevichThanks a lot! At least we tried. Hopefully they will enjoy the conference in the summer and potentially sponsor the event next year.

**Martin Morgan** (11:17:45):
> @Martin Morgan has left the channel


## 2022-03-07

**Krithika Bhuvanesh** (19:06:55):
> I got an update from Astra Zeneca. They are having a meeting about sponsorship on March 10, so we will know soon


## 2022-03-08

**Simone Bell** (10:36:17):
> Thanks for the update, Krithika! This is good news. See you in a while.


## 2022-03-16

**Krithika Bhuvanesh** (10:09:42):
> Hi everyone. Just heard from Astra zeneca. It’s unfortunately it’s a no for this year:disappointed:. It seems like they prioritize conferences that employees are going to. So next year if an AZ employee is submitting an abstract for BioC, then the chances will be higher. Simina says she will try to do that for next year.

**Krithika Bhuvanesh** (10:12:47):
> I haven’t heard anything back from my Seven Bridges contact. They have participated (submitted abstracts) in previous BioC conferences it seems. Is anyone able to look into attendee information from previous years conferences to see who it was from this company that participated ? I can try reaching out to them as well


## 2022-03-29

**Jenny Drnevich** (12:49:13):
> Maze agreed to Gold sponsorship! Matt Brauer asked about what the next steps were. I was not exactly sure other than I saw an invoice was sent to them last year. His email and my reply went to[sponsorship@bioconductor.org](mailto:sponsorship@bioconductor.org)so if anyone getting those has more to add, please do so.

**Krithika Bhuvanesh** (16:00:12):
> More good news ! Seven Bridges has agreed to Gold sponsorship ! They are asking about next steps. I don’t know what the next steps are either. What can I say ?

**Jenny Drnevich** (16:11:09) (in thread):
> If you want to reply back today, I would just say something along the lines that I did about we can send an invoice. Also copy[sponsorship@bioconductor.org](mailto:sponsorship@bioconductor.org)(you get these, correct?) so that it gets through to the people that have handled this in previous years. They're all probably off work by now so it will have to wait until tomorrow.

**Krithika Bhuvanesh** (16:12:59) (in thread):
> Yes Simone Bell is copied in my email with Seven Bridges, so I will inquire about invoice, and see if Simone will follow up on that tomorrow

**Krithika Bhuvanesh** (16:13:21) (in thread):
> Is there any information that I need to say about talks and workshops and such ?

**Jenny Drnevich** (16:14:32) (in thread):
> I would wait on that for Gold memberships to see how many regular applications we get. It wasn't in the original sponsorship descriptions.

**Krithika Bhuvanesh** (16:15:26) (in thread):
> okay sounds good.


## 2022-03-30

**Simone Bell** (07:07:06):
> Thanks a lot, Krithika and Jenny:tada:I’m sending you an e-mail at[sponsorship@bioconductor.org](mailto:sponsorship@bioconductor.org)

**Konstantinos Geles (Constantinos Yeles)** (14:30:32):
> @Konstantinos Geles (Constantinos Yeles) has left the channel


## 2022-04-04

**Aedin Culhane** (22:04:35) (in thread):
> @Erica Feickand Matt know each other as Matt has sponsored bioc a couple of years.


## 2022-04-17

**Annajiat Alim Rasel** (01:42:46):
> @Annajiat Alim Rasel has left the channel


## 2022-04-21

**Jenny Drnevich** (22:50:51):
> NanoString has confirmed Platinum sponsorship! Dave has asked me to work with Kevin Sheehy on the details. I see we sent them an invoice last year. Is this what we will do again? Or what else should I say/ask?


## 2022-04-25

**Aedin Culhane** (19:16:00) (in thread):
> Yipppppeeeeee


## 2023-01-18

**José Basílio** (13:09:01):
> @José Basílio has joined the channel


## 2023-01-27

**Aedin Culhane** (12:31:27):
> Hi Everyone.  We will soon be opening up sponsorship opportunities for[Bioc2023 (Boston, 2-4 Aug)](https://bioc2023.bioconductor.org/)We are reviewing the sponsorship packages. We are excited to plan Bioc2023,  it’ll be great to meet in person, and we intend to keep the virtual participation too because its so important for equity and inclusivity for our community globally, many of whom can’t attend because of cost, caregiving, travel or visas issues.  Please email[sponsorship@bioconductor.org](mailto:sponsorship@bioconductor.org)if you have feedback (good, bad and ugly) on our previous sponsorship package (onhttps://bioc2022.bioconductor.org/sponsors/).  What do sponsors want in 2023 in person and virtual hybrid meeting, whats important in post-pandemic meetings, what are conference sponsor expectations.


## 2023-02-07

**Maria Doyle** (12:09:40):
> @Maria Doyle has joined the channel


## 2023-02-16

**Erica Feick** (08:52:09):
> @Erica Feick has joined the channel


## 2023-02-20

**Rui Fu** (06:23:23):
> @Rui Fu has joined the channel


## 2023-02-22

**Junxia Lin** (00:04:53):
> @Junxia Lin has joined the channel


## 2023-02-28

**Krithika Bhuvanesh** (16:53:09):
> @Krithika Bhuvanesh has joined the channel


## 2023-05-09

**Krithika Bhuvanesh** (18:28:54):
> Did you guys get email from[ivo.kwee@bigomics.ch](mailto:ivo.kwee@bigomics.ch)regarding their interest in sponsoring ?

**Krithika Bhuvanesh** (18:29:05):
> “We would be interested in becoming a silver sponsor for your coming Bioconductor 2023 conference. Would there still be a possibility to present ourselves, or to give a short talk or organize a workshop as a sponsor?”


## 2023-05-10

**Maria Doyle** (06:20:46) (in thread):
> I’ve forwarded into org channel


## 2023-09-14

**Levi Waldron** (03:31:44) (in thread):
> A little behind here:smile:but what eventually happened with bigomics.ch?

**Maria Doyle** (04:04:14) (in thread):
> They ended up sponsoring EuroBioC for silver, they’d also sponsored them at that level last year.

**Levi Waldron** (04:11:13) (in thread):
> Great!:thumbsup::muscle:


## 2023-09-20

**Jaykishan** (05:29:36):
> @Jaykishan has joined the channel


## 2023-11-21

**Renuka Potbhare** (07:03:46):
> @Renuka Potbhare has joined the channel


## 2024-05-05

**Ifra** (09:37:53):
> @Ifra has joined the channel


## 2025-03-28

**Khadija Juma** (07:26:45):
> @Khadija Juma has joined the channel
