---
title: "#bioc2024"
---

## 2024-03-22

**Erica Feick** (15:41:48):
> @Erica Feick has joined the channel

**Maria Doyle** (15:41:57):
> @Maria Doyle has joined the channel

**Jenny Drnevich** (15:50:47):
> @Jenny Drnevich has joined the channel

**Samuel Gamboa** (16:08:16):
> @Samuel Gamboa has joined the channel

**Charlotte Soneson** (16:25:44):
> @Charlotte Soneson has joined the channel

**Michael Lynch** (16:26:59):
> @Michael Lynch has joined the channel

**Hervé Pagès** (16:37:31):
> @Hervé Pagès has joined the channel

**Marcel Ramos Pérez** (16:50:34):
> @Marcel Ramos Pérez has joined the channel

**Janani Ravi** (17:35:02):
> @Janani Ravi has joined the channel

**Himel Mallick** (18:57:51):
> @Himel Mallick has joined the channel

**Leopoldo Valiente** (21:02:28):
> @Leopoldo Valiente has joined the channel

**Mikhail Dozmorov** (21:39:04):
> @Mikhail Dozmorov has joined the channel

**Martin Morgan** (21:46:50):
> @Martin Morgan has joined the channel


## 2024-03-23

**irem Kahveci** (04:28:10):
> @irem Kahveci has joined the channel

**Assa** (04:42:30):
> @Assa has joined the channel

**Aananditaa** (08:59:55):
> @Aananditaa has joined the channel


## 2024-03-24

**Raihanat Adewuyi** (00:45:19):
> @Raihanat Adewuyi has joined the channel

**Charlotte Hutchings** (11:16:21):
> @Charlotte Hutchings has joined the channel

**Stephanie Hicks** (20:49:47):
> @Stephanie Hicks has joined the channel


## 2024-03-25

**Hamdi Furkan Kepenek** (00:45:41):
> @Hamdi Furkan Kepenek has joined the channel

**Philippine Louail** (03:59:47):
> @Philippine Louail has joined the channel

**Jacques SERIZAY** (05:01:44):
> @Jacques SERIZAY has joined the channel

**Ilaria Billato** (06:42:36):
> @Ilaria Billato has joined the channel

**Andres Wokaty** (09:22:33):
> @Andres Wokaty has joined the channel

**Sehyun Oh** (12:20:10):
> @Sehyun Oh has joined the channel

**Louise Morlot** (13:17:41):
> @Louise Morlot has joined the channel

**Nitesh Turaga** (15:31:18):
> @Nitesh Turaga has joined the channel

**Ahmad Al Ajami** (16:38:08):
> @Ahmad Al Ajami has joined the channel

**Frederick Tan** (17:34:49):
> @Frederick Tan has joined the channel

**Farhan Ameen** (20:07:45):
> @Farhan Ameen has joined the channel

**Nitya Singhal** (23:17:40):
> @Nitya Singhal has joined the channel


## 2024-03-26

**Ryan C. Thompson** (11:42:30):
> @Ryan C. Thompson has joined the channel

**Eve Gardner** (13:05:37):
> @Eve Gardner has joined the channel

**Erica Feick** (15:00:28):
> Hello everyone, We have changed the name of the #bioc2023 channel to#bioc-conference-everyoneso we have one channel for all things related to the North American conference. Plus, you don't have to join a new channel each year! So we will be removing this channel shortly, so be sure to join the new channel to get all your BioC2024 info!

**Hervé Pagès** (17:18:36):
> @Hervé Pagès has left the channel


## 2024-03-27

**Assa** (02:42:50):
> @Assa has left the channel

**David Rach** (12:31:48):
> @David Rach has joined the channel

**Nitya Singhal** (15:38:23):
> @Nitya Singhal has left the channel


## 2024-03-28

**Wes W** (10:42:04):
> @Wes W has joined the channel

**Erica Feick** (13:11:55):
> archived the channel
