---
title: "#bioc-conference-web"
format: gfm
---


## 2019-10-10

*09:13:27 - @Lorena Pantano has joined the channel*
**Lorena Pantano** (09:13:28):
> set the channel description: coordinate the efforts for the web page for the bioc conference

*09:14:42 - @Helena L. Crowell has joined the channel*
*09:14:42 - @Lori Shepherd has joined the channel*
*09:14:42 - @Martin Morgan has joined the channel*
*09:16:23 - @Levi Waldron has joined the channel*
*09:16:23 - @Aedin Culhane has joined the channel*
**Helena L. Crowell** (09:30:28):
> Thanks for getting us started, Lorena!! Happy to help any time- just wondering 2 things regarding the “mode of operation”:slightly_smiling_face:1) Do we need to be added as collaborators on[https://github.com/Bioconductor/BioC2019](https://github.com/Bioconductor/BioC2019)2) Once edits are made (e.g., in a separate branch) & checked, by ourselves do you typically like a pull request to be made, double-checked, and approved by you?

**Martin Morgan** (09:44:50) (in thread):
> Actually[https://github.com/Bioconductor/BioC2020](https://github.com/Bioconductor/BioC2020)which is configured but otherwise empty, with Lorena as admin...

*10:04:17 - @Qian Liu has joined the channel*
**Lorena Pantano** (10:10:31):
> I was thinking in adding people as collaboratos and all of you will be able to create branches, and then master will be blocked and only PR are allowed to update the barnch. If there is other ideas, happy to discuss.

**Lorena Pantano** (10:11:05):
> Probably only some people will be able to merge.

*13:25:16 - @Fred Boehm has joined the channel*
*13:34:58 - @venu has joined the channel*
*13:48:36 - @Sean Davis has joined the channel*
*14:02:15 - @Zhezhen Wang has joined the channel*
*14:07:36 - @Mikhail Dozmorov has joined the channel*
**Mikhail Dozmorov** (14:12:15):
> Thanks all for helping with sign in - joined now.

*19:03:16 - @Simina Boca has joined the channel*
**Simina Boca** (19:06:57):
> When is it not going to be "too early" to start spamming people with "save the date?":joy:


## 2019-10-11

**Helena L. Crowell** (03:17:54):
> I already told people on the hallway weeks ago:see_no_evil::see_no_evil:

*07:44:15 - @Charlotte Soneson has joined the channel*
**Lorena Pantano** (09:27:42):
> set the channel topic: [https://github.com/Bioconductor/BioC2019](https://github.com/Bioconductor/BioC2019)

**Lorena Pantano** (09:28:38):
> I will try to get the page populated today. For people who are new to jekyll you could try to fork the last year repository and localy get running the page:[https://github.com/Bioconductor/BioC2019](https://github.com/Bioconductor/BioC2019). This is what you will need to do to change the content and check all is good.

**Lorena Pantano** (09:28:56):
> set the channel topic: [https://github.com/Bioconductor/BioC2020](https://github.com/Bioconductor/BioC2020)


## 2019-10-16

**Lorena Pantano** (17:28:15):
> <!channel>, this is set up now:[https://github.com/Bioconductor/BioC2020](https://github.com/Bioconductor/BioC2020). I created some issues that can be done now. If you want to do any of them, just comment in the issue, I will add you as contributor. Then you would be able to***push changes to another branch***and***make the PR***to master, that it'll be reviewed.

**Mikhail Dozmorov** (21:13:57):
> Installing jekyll was an adventure, but it finally works running a test site. Does anybody successfully run BioC2020 and BioC2019 sites after cloning? I am getting a hard-to-google error:***ERROR bad Request-Line `\x16\x03\x01\x02\x00\...***Any suggestions if this is my local error, or something is fundamentally wrong?

**Martin Morgan** (22:13:57):
> [https://stackoverflow.com/a/47057601/547331](https://stackoverflow.com/a/47057601/547331)(from google bad request line jekyll:wink:) says you're trying to use https but should be using http?
  - Attachment (Stack Overflow): [Jekyll bad uri bad request line](https://stackoverflow.com/a/47057601/547331)
    > For some reason I started getting this error and I'm not sure why. I haven't been doing anything differently, it just started doing this. Does anyone know why this would be happening? Bryans-MacBo...


## 2019-10-17

**Mikhail Dozmorov** (13:57:49):
> Didn’t google well enough:slightly_smiling_face:Thank you, it works now


## 2019-10-18

**Martin Morgan** (08:17:09):
> @Lorena Pantanowas wondering about the 'need' for netlify? I guess the current site uses github pages which is just a click of a setting to get published as static web site; did you have a vision for additional features that netlify enables? I guess I'm concerned about maintainability in the face of the proverbial bus, re-use across years / conferences, and also the bait-and-switch that 'get started for free' implies

**Lorena Pantano** (08:38:55):
> netfly only to test the page, for PR and so, it will create a temporal page that is deleted on merging. So easy to check. Nothing to do for the final host.

**Lorena Pantano** (08:39:10):
> github still being the hosting of the pages

**Lorena Pantano** (09:06:30):
> is that ok?

**Lorena Pantano** (09:06:50):
> it is like a travis testing plugin for the page

**Martin Morgan** (09:13:34):
> yep that's fine thanks for clarifying

**Lorena Pantano** (13:08:00):
> thank you@Mikhail Dozmorov, this is done. Can you do another one to add you to the organizers ([https://github.com/Bioconductor/BioC2020/blob/master/docs/organizers.md](https://github.com/Bioconductor/BioC2020/blob/master/docs/organizers.md))? maybe@Helena L. Crowell,@Charlotte Soneson,@Simina Bocaas well? I can merge all the PR that you do, so don't worry about doing it at the same time. You can do it without checking, now the automatic build will make a temporal page to show how it looks like during the PR and I can fix it if there are issues.

**Mikhail Dozmorov** (13:39:15):
> Absolutely, will start addressing the “add all organizers #4” issue.


## 2019-10-19

**Mikhail Dozmorov** (16:03:01):
> <!channel>Please, check the table of organizers,[https://docs.google.com/spreadsheets/d/1JR7_PSy8cfEAz11uVTIITwD_fcGMjyouCcETnFbYiOc/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1JR7_PSy8cfEAz11uVTIITwD_fcGMjyouCcETnFbYiOc/edit?usp=sharing). Currently, sorted alphabetically. The online version will look like on the snapshot. Please, check your committee assignment, add your affiliations, and upload your photos into the “Organizers_Bioc2020_photos” subfolder in the Bioc2020 folder. The soft deadline is October 26, updates afterward are possible. Please, help to inform others outside of this channel, let’s discuss anything that needs improvement.
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/FPMJLTG5D/image.png)

**Levi Waldron** (16:13:17) (in thread):
> Maybe put a request too on the Google group? Will be nice having an organized list of organizers on the website.

**Mikhail Dozmorov** (17:22:14):
> Good point, done.


## 2019-10-21

**Aedin Culhane** (13:59:46):
> <!channel>please add your affiliation to the google sheet that@Mikhail Dozmorovcreated


## 2019-10-22

**Helena L. Crowell** (07:33:55):
> Hey@Lorena Pantano- just letting you know I finally(!) got all things running & would be most happy to help with/cover the next issue/task!

**Lorena Pantano** (13:01:46) (in thread):
> I added you to the repo as collaborator, let me know if you don't get the invitation.

**venu** (15:00:41):
> just to make sure we are all on same page, the website is still under initial set up, right?

**Lorena Pantano** (17:20:04):
> yes, why? although the idea is to have something soon up, I think


## 2019-10-24

**Martin Morgan** (15:17:59) (in thread):
> @Erica Feickprobably has some 'canned' material for[https://github.com/Bioconductor/BioC2020/issues/5](https://github.com/Bioconductor/BioC2020/issues/5)(Erica might not be paying attention to slack / this channel; I can provide contact info if you direct message me...)


## 2019-11-04

**Zhezhen Wang** (12:21:41):
> @Lorena PantanoI am happy to help with the next issue or any current ones ~


## 2019-11-05

**Lorena Pantano** (09:09:51) (in thread):
> @Helena L. Crowellcan you contact@Erica Feickby email to see if she can help with this?

*10:07:41 - @Erica Feick has joined the channel*
**Aedin Culhane** (14:16:12):
> Hi Lorena, In 2018, we put the conference posters on the website ([http://bioc2018.bioconductor.org/poster/Bioc2018_Poster.pdf](http://bioc2018.bioconductor.org/poster/Bioc2018_Poster.pdf)) But we forgot to do this last year.  Can we put a bookmark or reminder someplace to do it this year

**Aedin Culhane** (14:16:49):
> Its easier to email colleagues  a URL to a poster than attach to an email


## 2019-11-06

**Lori Shepherd** (11:40:49):
> FWIW -  I looked in the[bioc2020.bioconductor.org](http://bioc2020.bioconductor.org)not displaying -  From what I found, our AWS settings and the github pages that@Lorena Pantanoset up look correct -   There was an incident reported yesterday that affected the building of gitpages (See:[https://www.githubstatus.com/](https://www.githubstatus.com/)and the slew of reports on the gitpages community board:[https://github.community/t5/GitHub-Pages/bd-p/pages](https://github.community/t5/GitHub-Pages/bd-p/pages))  -   It seems to have cleared but the first posts last entry seems to indicate they needed a new push/update event to trigger a new build ([https://github.community/t5/GitHub-Pages/GitHub-Pages-Not-Deploying/m-p/37164/highlight/true#M2320](https://github.community/t5/GitHub-Pages/GitHub-Pages-Not-Deploying/m-p/37164/highlight/true#M2320))   -   Hopefully this will result in the website being built
  - Attachment: [GitHub Pages](https://github.community/t5/GitHub-Pages/bd-p/pages)
    > Discussion and questions about GitHub Pages—websites for you and your projects hosted right on your GitHub repository.
  - Attachment: [Re: GitHub Pages Not Deploying](https://github.community/t5/GitHub-Pages/GitHub-Pages-Not-Deploying/m-p/37164/highlight/true#M2320)
    > Now that the servers have recovered, I checked to see if my github pages site was built. It wasn't so I had to make a very small change within the guthub source editor and committed straight to master. This restarted the build and now my site has been updated.

**Lorena Pantano** (14:00:37):
> ok, let me do a push now, thanks

**Lori Shepherd** (15:21:22):
> Looks like successful as now the link is live -[https://bioc2020.bioconductor.org/](https://bioc2020.bioconductor.org/)
  - Attachment (bioc2020.bioconductor.org): [BioC 2019](https://bioc2020.bioconductor.org/)
    > Where Software and Biology Connect. June 24 - 27, New York City, USA.

**Simina Boca** (15:25:58):
> Yay! Just make sure to change the title to BioC 2020:wink:

**Lorena Pantano** (17:16:27):
> that is a very good point, but the theme to travel to the past was interesting ... hehe

**Lorena Pantano** (17:17:17):
> should we add a link to last year conference? if somebody wants to make the change a open a PR, feel free to do it, maybe in the home page or the menu


## 2019-11-07

**Mikhail Dozmorov** (16:13:42):
> @Lorena PantanoPlease, review the PR adding the past conferences. Lots of interesting material and history there:slightly_smiling_face:

**Lorena Pantano** (16:21:03):
> thanks!

**Martin Morgan** (17:47:08) (in thread):
> really nice that you did the leg work to dig all that information up!


## 2019-11-19

**Fred Boehm** (10:53:45):
> Hi,<!channel>- would you remind me of the December monthly meeting date and time? I've been unable to participate in the first two meetings. Is there a url that I need to join the meeting?

**Lorena Pantano** (13:14:23):
> I have it for Dec, 3rd at 9am EST

**Fred Boehm** (17:08:47):
> Thank you,@Lorena Pantano! I haven't been able to participate in past meetings. What teleconferencing service are we using? Do I need a url or code to join the meeting?

**Lorena Pantano** (17:32:27):
> Planning folder link ([https://drive.google.com/drive/u/0/folders/1CRN6u1m4a_xkgYhOwK2IKgsHzqD5cXto](https://drive.google.com/drive/u/0/folders/1CRN6u1m4a_xkgYhOwK2IKgsHzqD5cXto))   - organizing document link ([https://docs.google.com/document/d/1c93a4lLdrOSuwdHbr4q1Pbb9ZsWlQ_pFQmTYTaKeIHE/edit](https://docs.google.com/document/d/1c93a4lLdrOSuwdHbr4q1Pbb9ZsWlQ_pFQmTYTaKeIHE/edit))
> 
> To join the meeting on a computer or mobile phone:[https://bluejeans.com/260305868?src=calendarLink](https://bluejeans.com/260305868?src=calendarLink)Phone Dial-in[+1.408.740.7256](tel:+14087407256)(US (San Jose))[+1.408.317.9253](tel:+14083179253)(US (Primary, San Jose))
> Global Numbers:[https://www.bluejeans.com/premium-numbers](https://www.bluejeans.com/premium-numbers)Meeting ID: 260 305 868
> 
> Room System
> 199.48.152.152 or bjn.vc
> 
> Meeting ID: 260 305 868
> 
> Want to test your video connection?[https://bluejeans.com/111](https://bluejeans.com/111)


## 2019-11-21

**Fred Boehm** (09:04:11):
> Thank you,@Lorena Pantano!


## 2019-11-23

**Mikhail Dozmorov** (09:43:15):
> A quick reminder - please, add your photos[https://drive.google.com/drive/folders/1IQ56pnkMfwOfCkUwsKGX90Lzr7NPqPJD](https://drive.google.com/drive/folders/1IQ56pnkMfwOfCkUwsKGX90Lzr7NPqPJD)and affiliations[https://docs.google.com/spreadsheets/d/1JR7_PSy8cfEAz11uVTIITwD_fcGMjyouCcETnFbYiOc/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1JR7_PSy8cfEAz11uVTIITwD_fcGMjyouCcETnFbYiOc/edit?usp=sharing)before Monday, November 25, so we will have the organizing committee web page[http://bioc2020.bioconductor.org/organizers](http://bioc2020.bioconductor.org/organizers)maximally complete.
  - Attachment (bioc2020.bioconductor.org): [BioC 2020](http://bioc2020.bioconductor.org/organizers)
    > Where Software and Biology Connect. June 24 - 27, New York City, USA.


## 2019-12-03

**Lorena Pantano** (10:13:34):
> <!channel>, if somebody wants to do this one:[https://github.com/Bioconductor/BioC2020/issues/19](https://github.com/Bioconductor/BioC2020/issues/19)

**Zhezhen Wang** (10:14:18):
> I will do it

**Levi Waldron** (10:27:16):
> One more, update the key dates:[https://github.com/Bioconductor/BioC2020/issues/20](https://github.com/Bioconductor/BioC2020/issues/20)

**Zhezhen Wang** (10:28:12) (in thread):
> Sorry just see this, do I still have a chance to add in my photo?

**Mikhail Dozmorov** (10:30:36) (in thread):
> Yes.


## 2019-12-04

**Lorena Pantano** (16:41:03):
> <!channel>some other issues here if you have time to update:[https://github.com/Bioconductor/BioC2020/issues/23](https://github.com/Bioconductor/BioC2020/issues/23)

**Lorena Pantano** (16:41:51):
> [https://github.com/Bioconductor/BioC2020/issues/19](https://github.com/Bioconductor/BioC2020/issues/19)

**Lorena Pantano** (16:48:40):
> 23 is pretty urgent, so if it is not done for tonight I'll do it

**Mikhail Dozmorov** (16:50:55):
> I’m planning to get to it tonight, will fix 23 first.

**Lorena Pantano** (16:51:34):
> :slightly_smiling_face:


## 2019-12-06

**Lorena Pantano** (15:43:48):
> @Helena L. Crowellor any other, willing to update speakers:[https://github.com/Bioconductor/BioC2020/issues/25#issuecomment-562724041](https://github.com/Bioconductor/BioC2020/issues/25#issuecomment-562724041)

**Helena L. Crowell** (15:50:33):
> Hey sorry about the lack for activity- I’m traveling in AUS at the moment w/o much wifi... should get better from Monday onwards. Happy to do it then if it’s still open!


## 2019-12-09

**Aedin Culhane** (10:24:05):
> Hi. Can we update the sponsorship info. Do I need to submit a pull request or can someone point me to the mechanism to get an update. The new info was presented (and is in minutes) in the last conf call.

**Zhezhen Wang** (10:56:40) (in thread):
> So sorry something unexpected happened last week and didn’t have a chance to work on  the things

**Helena L. Crowell** (15:20:52):
> If you’d like to send me the info on Slack/via mail I’d be happy to do it along with other update above! 
> *I guess the current mechanism is to submit a GitHub issue with the relevant info that should be added.


## 2019-12-11

**Mikhail Dozmorov** (07:50:38):
> If still relevant, I’ll look at updating the sponsorship info this weekend. Traveling this week, can’t access the docs.

**Aedin Culhane** (15:41:18):
> Details of the sponsorship is in[https://docs.google.com/document/d/1yAjRJmFJ22F8CB3DYhj7WwywHh0ZovA1ZEDok-0AJ6A/edit](https://docs.google.com/document/d/1yAjRJmFJ22F8CB3DYhj7WwywHh0ZovA1ZEDok-0AJ6A/edit)

**Aedin Culhane** (15:41:37):
> ***Your sponsorship will help increase diversity and representation at Bioconductor 2020***by:
> * Funding travel scholarships for students and postdoctoral fellows
> * Providing caregiver awards to assist in childcare or eldercare costs (new in 2020)
> * Offering student diversity scholarships to increase participation of underrepresented minorities (new in 2020)
> * Keeping registration costs affordable for academic participants
> Three levels of sponsorship are available ([https://bioc2020.bioconductor.org/sponsor](https://bioc2020.bioconductor.org/sponsor)).***Sponsors of all levels***may present a poster highlighting the scientific interests of their organization in the poster sessions.***Platinum  $10,000 USD. ***
> * ***Poster session will be named after these donors. ***
> * ***Highest recognition, using your logo, in the online and print promotional and scheduling material. ***
> * ***Two invitations to attend the speaker dinner.***
> * ***Up to 8 free registrations.***
> * ***A thank-you tweet including your preferred Twitter handle. ***
> * ***A table during the poster session and social hours.***
> ***Gold: $5,000 USD: ***
> * ***Top recognition, using your logo, in the online and print conference promotional and scheduling material. ***
> * ***Up to 5 free registrations. ***
> * ***A thank-you tweet including your preferred Twitter handle. ***
> * ***A table during the poster session and social hours.***
> ***Silver: $1,000 USD***
> * Sponsor names will be listed in the online and print promotional and scheduling material.
> * Academic discount on 2 registrations.
> * A thank-you tweet including your preferred Twitter handle

**Aedin Culhane** (15:42:24):
> I'll also put in a pull request

**Aedin Culhane** (15:45:02):
> Sorry, I was in a rush, and I just put the lines into an issue. Should I edit the ,md file and submit that instead?

**Aedin Culhane** (15:46:04):
> Sorry, I just noticed you already updated it, can you add in the top few lines on what the sponsorship will be used for?

**Aedin Culhane** (15:49:41):
> The schedule, of 3 keynote speakers one after each other is tough. How can the schedule be adjusted.. Should 8:30 -10am Speaker 1 (35 min), contributed talks  (20 min each),  Speaker 2  (35 min) contributed talks (20 min each), Speaker 3  +2 contributed talks  would be a nicer schedule?

**Helena L. Crowell** (17:03:43):
> I just made a PR to update the sponsorship info!


## 2019-12-12

*04:08:25 - @Emma Jablonski has joined the channel*
*04:08:50 - @Emma Jablonski has left the channel*

## 2019-12-20

*07:16:53 - @Robert Ivánek has joined the channel*

## 2020-01-23

**Lori Shepherd** (10:47:15):
> Just a note -  it seems the registration and call for submission pages need updating ASAP  since both appear to be open but there is no information on the pages


## 2020-01-24

**Lorena Pantano** (07:56:56):
> <!channel>anybody can deal with this:[https://github.com/Bioconductor/BioC2020/issues/42](https://github.com/Bioconductor/BioC2020/issues/42), If not I will do it tonigh


## 2020-01-25

**Mikhail Dozmorov** (10:20:34):
> <!channel>Links to the registration forms should be live after the latest pull request is approved. The remaining registration link can also be added, and we can announce registration/call for abstracts/workshops on Monday, January 27. Are there some standard forms/flyers/ways to call for Bioc2020 registration, who can help with announcements on social media channels?

**Lori Shepherd** (11:10:37):
> I can help with social media, support site and main bioconductor website unless someone else was going to.  Just let me know and when they are live


## 2020-01-26

**Levi Waldron** (08:32:50):
> @Lori Shepherdregistration and the call for abstracts are open on the website now. Would you make an official announcement?


## 2020-01-27

**Lori Shepherd** (08:50:47) (in thread):
> done


## 2020-02-05

*02:16:35 - @Robert Ivánek has left the channel*

## 2020-02-16

**Levi Waldron** (13:22:58):
> Just finished reviewing submissions to eRUM2020 using a nifty Shiny app by@Federico Marini-[https://github.com/federicomarini/assessr](https://github.com/federicomarini/assessr). It was a big improvement over what we’ve used in the past… Would anyone on the web team be willing to set it up for reviewing BioC2020 submissions?


## 2020-02-24

**Lorena Pantano** (11:11:06):
> mm, I can try to take a look. Where would be hosted?


## 2020-02-25

**Levi Waldron** (15:07:54) (in thread):
> Easiest would be either[shinyapps.io](http://shinyapps.io)or asking Federico to host it for us :)


## 2020-03-05

**Mikhail Dozmorov** (13:15:15):
> assertr is indeed nice, but there's some work. We need Excel files with workshops and talks/posters (can be one file), with reviewers assigned. And, we need Google forms for evaluation. More details on it with examples are at[https://github.com/mdozmorov/assessr](https://github.com/mdozmorov/assessr). The actual app will approximately look like[https://mdozmorov.shinyapps.io/assessr/](https://mdozmorov.shinyapps.io/assessr/)

**Mikhail Dozmorov** (13:15:49):
> @Lorena Pantano, if you could add me to the Bioconductor organization, I'll maintain the assertr repository on[https://github.com/Bioconductor](https://github.com/Bioconductor)account. Not sure if it is connected to[shinyapps.io](http://shinyapps.io), or we may want to host it elsewhere?

**Lorena Pantano** (13:17:58):
> great! I don’t have permissions for that, maybe@Lori Shepherdor@Martin Morgan, they can fork it there maybe?

**Lori Shepherd** (16:01:04):
> @Mikhail Dozmorov-  I can help set this up -  Instead of adding to the organization I should be able to grant permissions to the specific repository created -  It sounded like you wanted a forked version to be in Bioconductor?   Is this the repository that should be forked?[https://github.com/mdozmorov/assessr](https://github.com/mdozmorov/assessr)?

**Mikhail Dozmorov** (17:03:30):
> @Lori Shepherd, yes it would be good to develop this repo under the official Bioconductor GitHub account. That's the correct repository to be forked, and adding me allows for direct development. Another consideration is that the Bioconductor account should be connected with[https://www.shinyapps.io/](https://www.shinyapps.io/)to deploy this app - instructions there are simple.
  - Attachment (shinyapps.io): [shinyapps.io](https://www.shinyapps.io/)
    > [shinyapps.io](http://shinyapps.io)


## 2020-03-06

**Levi Waldron** (16:54:22):
> Would love to use this if you can get it up quickly!@Federico MariniFYI

*17:03:38 - @Federico Marini has joined the channel*
**Federico Marini** (17:03:54):
> Sorry, I somehow missed the first mention:disappointed:

**Federico Marini** (17:04:49):
> Is there a general GSheet for the submissions I can sneak peek into - in terms of columns provided

**Federico Marini** (17:04:51):
> ?

**Mikhail Dozmorov** (20:26:42):
> We don't have GSheet(s) yet.@Matthew McCall, can you provide an Excel file with workshops/posters/talks? I or anyone volunteering can make evaluation GSheets and adjust columns in assertr

*20:26:52 - @Matthew McCall has joined the channel*
**Matthew McCall** (21:07:11):
> @Mikhail Dozmorovit's in the bioc2020 folder on google drive

**Matthew McCall** (21:08:03):
> I added columns for reviewer assignments, just numbered 1,2,3,... for now.

**Matthew McCall** (21:12:01):
> Let me know what other info you need. The list of reviewers and their email addresses are in the organizing doc. If you're planning to do the reviewer assignments, it'd be good to check that no one is asked to review their own submission.

**Mikhail Dozmorov** (21:25:19):
> I'll make the Bioconductor version of assertr compatible with the "Bioc2020 talks and posters review" file. And, make a Google form for assessment submission. Please, assign the reviewers.


## 2020-03-07

**Federico Marini** (02:36:45):
> Looks like you’re good on track!

**Federico Marini** (02:37:02):
> All you need yet seems to be the GForm for inputting the reviews

**Federico Marini** (02:37:50):
> And use that link in the hard coded function to generate the pre-filled links

**Federico Marini** (02:38:01):
> that’d save a lot of time

**Federico Marini** (02:43:07):
> Once the GForm is done, we did the whole aggregation (well, “’f course”) in R

**Federico Marini** (02:43:23):
> and just sent out the acceptance/rejections with`mailR`loops

**Federico Marini** (02:43:42):
> Happy to give some pointers on these if needed, just make sure to tag me:slightly_smiling_face:

**Mikhail Dozmorov** (10:23:26):
> @Federico MariniQuick question, turned out to be difficult to google. Playing with Chrome developer tools wasn't productive either. How to pass information to a specific element in Google Form? The current assertr code uses extended URL like "/viewform?usp=pp_url&entry.840333480=", but how to get this entry id?

**Federico Marini** (11:28:41):
> that is taken from the dump of the submissions

**Federico Marini** (11:28:57):
> guessing you’d assign one

**Federico Marini** (11:29:07):
> otherwise it would be an incremental id

**Federico Marini** (11:29:17):
> we had that coming from sessionize and we took that

**Federico Marini** (11:29:30):
> in case we want to re-enter that system

**Matthew McCall** (14:21:32):
> @Mikhail DozmorovWhat’s the best way for me to assign reviewers? Can I send you a list of Reviewer <int> : <name> <email> ?

**Matthew McCall** (14:22:45):
> Or is there a way for me to assign reviewers within assertr? I’m traveling this week, so apologies if my response time is a bit slow.

**Mikhail Dozmorov** (14:42:10):
> @Matthew McCall, please, add the reviewers directly to the Google Sheet. assertr will either read directly from it (wip), or use a saved Excel version (current). The app is functional with the current submissions, linked to the evaluation form, (free shinyapps account does not allow organizations). As soon as we have reviewers assigned, it will be ready for all of us to use.

**Matthew McCall** (14:49:40):
> So for example I'd replace "Reviewer 1" with someone's full name? Or google id? Or email?

**Mikhail Dozmorov** (14:50:51):
> Yes, name. All unique names will appear in assertr, and everyone can see what has been assigned to whom

**Matthew McCall** (14:51:49):
> Got it thanks. I'll work on assigning reviewers this evening once I'm in front of a computer (on my phone now).

**Matthew McCall** (19:45:57):
> If I understand your tests correctly, I need to paste in the names of each reviewer where I previously had “Please Review These”. I did the first two (Lori and Qian). Can you check that this is working correctly? Thanks!

**Mikhail Dozmorov** (22:24:19):
> It works as expected. Yes, now the app shows both names in the drop-down menu. Selecting either will show posters assigned to the corresponding name (currently 20 the same posters).


## 2020-03-08

**Levi Waldron** (04:01:37) (in thread):
> BTW I just turned link sharing “off” so you have to be signed in and have the document shared with you, which seems more appropriate for the submissions.

**Levi Waldron** (04:04:13) (in thread):
> You can turn link sharing back on, but then probably shouldn’t post the link in public places...

**Levi Waldron** (04:24:15):
> Thanks Mikhail, this is so great! It’ll make reviewing much easier and better formalized.

**Matthew McCall** (08:07:51):
> Yes, thank you@Mikhail Dozmorov! I’ve assigned all of the reviewers (I tried to not have anyone review something from their own group but I’m sure I’ll hear from someone if I missed one). Please let me know when the app is ready to be sent out, and I’ll email all of the reviewers.

**Federico Marini** (08:10:47):
> Depending on whether you want to show the info of the presenter, keep in mind to remove or not the respective column from the db:wink:

**Federico Marini** (08:11:50):
> (and: you likely want the link to be accessed upon a password? don’t know what your policy is regarding sharing info of submitters to sponsors and third parties?)

**Mikhail Dozmorov** (08:49:00):
> Now, all reviewers are showing correctly.

**Mikhail Dozmorov** (08:50:01):
> Security is an open question. Currently, the app is public for anyone who knows the link. So is the evaluation form. I don't know Shiny that well to implement passwords.@Federico Marini, how did you dealt with this? Any implementations of passwords on Shiny and Google Forms?

**Levi Waldron** (08:58:53):
> As I understand, the ratings will still be password protected in any case. It's probably ok to use public URLs for the form and shiny app if we just don't post the links publicly (can use the conference committee mailing list to post, since this channel is also public).

**Levi Waldron** (09:01:31):
> BTW the app looks GREAT

**Mikhail Dozmorov** (09:38:40):
> It should be OK to use the app as is. Regarding the evaluation form, it has been set to ask for an e-mail and will send confirmation after each evaluation to the evaluator. Any unsolicited submissions will be obvious. Let's transition the evaluation conversations to the committee mailing list.

**Federico Marini** (10:18:16):
> > how did you dealt with this?
> The guys at vanlog (data science company, coorganizing the event**en masse**) have their server with shinyproxy setup

**Federico Marini** (10:18:28):
> there they have a simple password login

**Federico Marini** (10:20:07):
> My thought was also to reveal info of the submitters to (potentially) personal data collectors. I know it sounds exaggerated, but we had to define the whole things according to the GDPR

**Federico Marini** (10:23:14):
> A hacky alternative: a conditional panel displaying the stuff correctly if one widget field has the correct value as in the password you would expect?


## 2020-03-31

**Lori Shepherd** (09:57:09):
> Hello -- I think this is the right channel for the website committee (@Lorena Pantano) -- I just wanted to give you a heads up -- In past years suggestions for BOF sessions were opened as open issues on the conference github issues so the community would have access to discussion and could up vote sessions they felt were interesting -- We are going to open this up again to make suggestions for birds-of-a-feather (BOF) , short hack-a-thon projects (HAK) , or short how-to / FAQ (FAQ) -- we are encouraging spontaneous sessions as well but want to narrow down a few pre-set ones to insert into the program  --  I have drafted  an announcement that the program committee heads are editing and plan to announce some time this week -- I wanted to give the website committee a heads up as this will mean there will start to be open issues that should not be closed and not directly relevant to updating the website content material.

**Lorena Pantano** (09:58:08):
> thank you!


## 2020-04-29

*14:06:43 - @Nitesh Turaga has joined the channel*

## 2020-06-04

**Levi Waldron** (13:45:59):
> Website group (@Lorena Pantano?) - would you update[https://bioc2020.bioconductor.org/scholarships.html](https://bioc2020.bioconductor.org/scholarships.html)? To 1) get rid of the outdated dates here, 2) refer to registration scholarships, 3) not require a talk/poster/workshop, but say that it will be considered if entered, and 4) add a deadline (did we decide on one yet?). The canonical site for dates is[https://bioc2020.bioconductor.org/call-for-abstracts](https://bioc2020.bioconductor.org/call-for-abstracts)
  - Attachment (bioc2020.bioconductor.org): [BioC 2020](https://bioc2020.bioconductor.org/scholarships.html)
    > Where Software and Biology Connect. July 29 - 31, Boston, USA.
  - Attachment (bioc2020.bioconductor.org): [BioC 2020](https://bioc2020.bioconductor.org/call-for-abstracts)
    > Where Software and Biology Connect. July 29 - 31, Boston, USA.


## 2020-06-05

**Mikhail Dozmorov** (09:49:45):
> First draft of the workshop page. Workshop titles are linked to the pkgdown websites, GitHub links link to the raw repos. The other version additionally includes links to Docker images, but it seems too much. Any suggestions? If it looks good, I'll complete and make a pull request
  - File (PNG): [workshop2.png](https://community-bioc.slack.com/files/U34P8RS3B/F014X57QYD8/workshop2.png)
  - File (PNG): [workshop1.png](https://community-bioc.slack.com/files/U34P8RS3B/F0159PK6BU1/workshop1.png)

**Martin Morgan** (11:23:30) (in thread):
> seems like this should be 'user friendly' so at most the link to the docker image (where they can then go for github source). Also it would be great If_WeAgreed.On_some_conventionR!ForNaming:wink:

**Mikhail Dozmorov** (12:18:24):
> Cleaner version, with all the naming imperfections hidden:slightly_smiling_face:
  - File (PNG): [workshop3.png](https://community-bioc.slack.com/files/U34P8RS3B/F014XH4TT0A/workshop3.png)

**Lorena Pantano** (17:41:30) (in thread):
> I create this PR:[https://github.com/Bioconductor/BioC2020/pull/73](https://github.com/Bioconductor/BioC2020/pull/73)


## 2020-06-06

**Levi Waldron** (01:04:23) (in thread):
> Thanks@Lorena Pantano! I made a minor suggestion but approved the PR (“are encouraged to present a talk, poster, organize a “watch party”, or generally to participate actively in the conference. To apply for a scholarship, complete”) since the scholarship is only $50, I think we can lower the requirements for applying to it.

**Levi Waldron** (01:14:37) (in thread):
> Nice@Mikhail Dozmorov! How about another column for build status badges, such as the one visible at[https://github.com/waldronlab/MultiAssayWorkshop](https://github.com/waldronlab/MultiAssayWorkshop), after all the workshops have switched over to the new template? That would help in tracking which workshops are successfully built. Once the pkgdown sites are all built, I think that site might replace both the GitHub and Docker columns. What do you think@Sean Davis?

**Sean Davis** (08:46:01) (in thread):
> The build status won’t matter for the workshops. Even a workshop that is not building will still work if the docker image and website have been created.

**Mikhail Dozmorov** (08:55:27) (in thread):
> I was under impression the build status IS an indicator of successful pkgdown site and Docker image creation. If the build status is "failing", how can we know other than manually checking that a workshop has all the components?

**Levi Waldron** (10:25:08) (in thread):
> I think if the build passes once, the built docker container and pkgdown site will not be replaced except by another successful build. But the docker container could lag GitHub commits, and in an extreme case correspond only to the initial workshop setup.

**Sean Davis** (11:24:36) (in thread):
> That was what I had in mind,@Levi Waldron.

**Sean Davis** (11:27:00) (in thread):
> We will want to have the workshop page reflect the availability of a docker image and a working url.

**Mikhail Dozmorov** (13:04:54) (in thread):
> The #74 pull request adds all workshops, they'll look like this screenshot. We can always add/remove columns. The title is linked to the pkgdown site, but if it is not ready, GitHub repo is available
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F015BF42H4Z/image.png)

**Sean Davis** (13:13:32) (in thread):
> I’d remove the build status stuff for now.

**Sean Davis** (13:14:07) (in thread):
> I don’t think we want people to avoid a working workshop just because the current commit isn’t building.

**Mikhail Dozmorov** (13:14:29) (in thread):
> Good point, will fix

**Sean Davis** (13:14:38) (in thread):
> @Mikhail DozmorovThanks so much for taking this on!!!!

**Levi Waldron** (13:15:06) (in thread):
> How about keeping it for now while we'll be chasing down authors to get things working?

**Mikhail Dozmorov** (13:15:36) (in thread):
> I'll comment them out, so they can be easily restored

**Levi Waldron** (13:16:12) (in thread):
> Seems useful having a central point of checking the status of all workshops, but doesn't have to be there.

**Levi Waldron** (13:18:31) (in thread):
> Although maybe that's really no longer necessary now that we don't have a mega-image... Yeah, thank you Mikhail!!!!

**Mikhail Dozmorov** (13:19:52) (in thread):
> We'll have the page with badges, but it won't be listed. The listed page, for now, will have badges hidden and won's scary users from failing to build workshops

**Mikhail Dozmorov** (15:38:29) (in thread):
> The result[https://bioc2020.bioconductor.org/workshops](https://bioc2020.bioconductor.org/workshops), and the same page with badges (unlisted)[https://bioc2020.bioconductor.org/workshops_full](https://bioc2020.bioconductor.org/workshops_full). Thanks,@Lorena Pantano, for quick merge
  - Attachment (bioc2020.bioconductor.org): [BioC 2020](https://bioc2020.bioconductor.org/workshops)
    > Where Software and Biology Connect. July 29 - 31, Boston, USA.
  - Attachment (bioc2020.bioconductor.org): [BioC 2020](https://bioc2020.bioconductor.org/workshops_full)
    > Where Software and Biology Connect. July 29 - 31, Boston, USA.


## 2020-06-07

**Sean Davis** (10:03:19) (in thread):
> Looking good,@Mikhail Dozmorov. Can we remove workshops that are not built yet and add a note that  there are “more to come” or something like that? I tried to set things up so that the process could be automated:
> 1. Collect list of github repos for workshops.
> 2. Check URL and Docker image locations from DESCRIPTION file. If either is a 404, then workshop is not ready.
> 3. The tag on the docker image is the git SHA that was used to build the image, so tagging the website with the SHA for the docker image ensures that the workshops can remain stable after the workshop.
> 4. All workshops can immediately be transitioned to “Available workshops” on the main[Bioconductor.org](http://Bioconductor.org)site and listed.
> 5. For the[Bioconductor.org](http://Bioconductor.org)version, the list of github repos can grow indefinitely. Routine checks, identical to #2 above guarantee that workshops that “go away” get removed.
> tagging@Lori Shepherdand@Nitesh Turagajust so some core team members know what I have in mind.

**Sean Davis** (10:05:20) (in thread):
> We might want to add some functionality around this stuff to BiocPkgTools or another location to complete the checks, automate creation of a “data.frame” of details for workshop github repos and supporting materials that can then be used to create web pages easily for future workshops, both bioc-related and not.

**Sean Davis** (10:05:54) (in thread):
> The same code could then be used for the[bioconductor.org](http://bioconductor.org)location.

**Mikhail Dozmorov** (10:24:22) (in thread):
> It'll be great to automate such checks. For now, this is just a markdown table. I'll appreciate if someone can look at it, I have a massive teaching commitment for the coming week. Tonight I'll send another e-mail to workshop participants to speed up the development and have less 404 links


## 2020-06-23

**Federico Marini** (08:39:14):
> Hey there:slightly_smiling_face:I noticed that the links to the workshops seem to be broken

**Federico Marini** (08:39:15):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F015WC7E1JN/image.png)

**Federico Marini** (08:39:30):
> see lower left corner while I was hovering one

**Federico Marini** (08:39:44):
> (at least, some)

**Mikhail Dozmorov** (09:30:57):
> May it be the browser? It looks good in Chrome

**Federico Marini** (11:37:08):
> hm, not really

**Federico Marini** (11:37:17):
> [Public Data Resources in Bioconductor](http://bioc2020.bioconductor.org/NA)also links there

**Sean Davis** (11:46:42):
> @Mikhail Dozmorovand@Federico Marini, the workshop website links are broken for a couple of likely reasons.
> 1. URL is not included in the DESCRIPTION file (this results in an`NA`link).
> 2. The URL in the DESCRIPTION file does not lead to a working website.
> For docker links:
> 1. DockerImage is not in the DESCRIPTION file.
> 2. DockerImage tag is incorrect OR includes uppercase letters; only lowercase letters are allowed for dockerhub.
> 3. Docker image has never been built.

**Federico Marini** (11:48:04):
> ok, makes sense!

**Federico Marini** (11:48:17):
> thanks@Sean Davis!

**Mikhail Dozmorov** (12:13:33):
> @Federico Marini, I misunderstood the problem. Yes, some workshops currently are not being built properly. A good time to remind the workshop building instructions by@Sean Davis,[https://github.com/seandavi/BuildABiocWorkshop2020](https://github.com/seandavi/BuildABiocWorkshop2020)

**Lorena Pantano** (17:24:20):
> Should we update the logo?


## 2020-06-24

**Levi Waldron** (05:38:18) (in thread):
> Looks like@Mikhail Dozmorovhas done it in PR[https://github.com/Bioconductor/BioC2020/pull/96](https://github.com/Bioconductor/BioC2020/pull/96)(I think one of you two should merge it, not me)

**Levi Waldron** (06:06:43) (in thread):
> I am working on that now:smile:It’s because I haven’t updated the DESCRIPTION file according to the directions in[https://github.com/seandavi/BuildABiocWorkshop2020](https://github.com/seandavi/BuildABiocWorkshop2020)

**Mikhail Dozmorov** (07:14:06) (in thread):
> Yes, that PR implements the new logo. I still cannot push directly to the main branch, hence pull requests.

**Levi Waldron** (07:17:56) (in thread):
> I can confirm you have write access, so I’ not sure why you can’t push directly

**Levi Waldron** (07:20:10) (in thread):
> I just upped you to admin for the BioC2020 repo, so you can also manage access of others.

**Lorena Pantano** (13:07:35) (in thread):
> great

**Mikhail Dozmorov** (13:18:27) (in thread):
> Thank you@Levi Waldron,@Lorena Pantano,@Lori Shepherd- it works and makes updates much easier. Switching to ssh protocol was the main issue

**Lorena Pantano** (13:18:51) (in thread):
> awesome, you are the best!


## 2020-07-20

*13:14:20 - @Rydham Goyal has joined the channel*

## 2020-07-21

**Aedin Culhane** (12:48:10):
> [https://bcc2020.github.io/](https://bcc2020.github.io/)have a fancy looking github pages ….  Maybe future bioc conferences could borrow ideas from their style. They use  Zeppelin.[http://gdg-x.github.io/zeppelin/](http://gdg-x.github.io/zeppelin/)which seems to be designed specifically for conferences[https://github.com/gdg-x/zeppelin](https://github.com/gdg-x/zeppelin)
  - Attachment (bcc2020.github.io): [BCC2020](https://bcc2020.github.io/)
    > BCC2020 brings together the Galaxy Community Conference and Bioinformatics Open Source Conference to meet jointly online.
  - Attachment (gdg-x.github.io): [GDG DevFest Season 2014](http://gdg-x.github.io/zeppelin/)
    > GDG DevFest is a set of events all around the world

*12:49:44 - @Carl McIntosh has joined the channel*

## 2020-07-22

**Aedin Culhane** (18:43:04):
> Hi I created a pull request to add the names of speakers to the schedule[https://github.com/Bioconductor/BioC2020/pull/119](https://github.com/Bioconductor/BioC2020/pull/119)


## 2020-07-24

**Levi Waldron** (04:20:58):
> Note, this channel is to “coordinate the efforts for the web page for the bioc conference” - the general conference channel is#bioc2020.

**Levi Waldron** (04:23:57):
> set the channel description: coordinate the efforts for the web page for the bioc conference. For general conference-related discussion, use #bioc2020 and for workshop-related discussion use #bioc2020-workshops.

**Levi Waldron** (04:24:27):
> set the channel topic: Development of the website [bioc2020.bioconductor.org](http://bioc2020.bioconductor.org), see [https://github.com/Bioconductor/BioC2020](https://github.com/Bioconductor/BioC2020)


## 2020-07-27

*09:11:33 - @Vivek Das has joined the channel*

## 2020-07-28

**Federico Marini** (15:53:35):
> Dunno if this is the best place to report, but here it goes:

**Federico Marini** (15:53:45):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F017UN74HNH/image.png)

**Federico Marini** (15:54:08):
> not reporting any violation, but: the tinyurl in the bottom seems broken

**Federico Marini** (15:57:40):
> (a***c***is missing)

**Levi Waldron** (16:58:49) (in thread):
> Argh thanks@Federico Marini!


## 2020-07-29

*08:42:34 - @Marc RJ Carlson has joined the channel*

## 2020-07-31

*16:15:20 - @Dr Awala Fortune O. has joined the channel*

## 2020-10-06

*11:21:44 - @Kayla Interdonato has joined the channel*

## 2020-10-25

*06:52:52 - @Leo Lahti has joined the channel*

## 2020-12-02

*05:42:14 - @Konstantinos Geles (Constantinos Yeles) has joined the channel*

## 2021-01-22

*15:41:32 - @Annajiat Alim Rasel has joined the channel*

## 2021-05-11

*16:43:53 - @Megha Lal has joined the channel*

## 2021-05-18

**Levi Waldron** (04:46:35):
> @Mikhail DozmorovI noticed that the "[All short talk abstracts](https://bioc2021.bioconductor.org/short-talks)" link from[https://bioc2021.bioconductor.org/schedule/](https://bioc2021.bioconductor.org/schedule/)is broken
  - Attachment (bioc2021.bioconductor.org): [Schedule](https://bioc2021.bioconductor.org/schedule/)
    > Schedule

**Levi Waldron** (04:47:22) (in thread):
> I see this is fixed now!

**Mikhail Dozmorov** (07:51:00) (in thread):
> Overlooked to commit them. Fixed now, and the Tercen logo is up.

**Sean Davis** (08:24:19):
> I just poked around the[https://bioc2021.bioconductor.org/](https://bioc2021.bioconductor.org/)website. WOW! I say again, WOW!
> 
> Lots of folks involved, but kudos to@Mikhail Dozmorovfor the incredible work of art and science!


## 2021-08-05

*05:47:45 - @Ambarish S. Ghatpande has joined the channel*
*05:48:58 - @Ambarish S. Ghatpande has left the channel*

## 2022-01-13

**Levi Waldron** (08:31:57):
> @Mikhail Dozmorov@Lori ShepherdI noticed that[https://bioc2022.bioconductor.org/](https://bioc2022.bioconductor.org/)is down

**Lori Shepherd** (08:44:35):
> did we create the[bioconductor.org](http://bioconductor.org)endpoint yet for bioc2022?  I don't have any records currently that would redirect it and I don't see any requests to create it --@Mikhail Dozmorovis there a netlify it should point to?

**Mikhail Dozmorov** (08:54:35):
> [https://bioc2022.netlify.app/](https://bioc2022.netlify.app/)is the existing URL. It was on my todo to ask,@Lori Shepherd, can you, please, help?

**Lori Shepherd** (08:58:16):
> yep.  I'll set it up now

**Lori Shepherd** (09:01:13):
> Okay. it was created.  I think it can normally take up to day to resolve but it should be all set


## 2022-01-14

**Levi Waldron** (10:28:08):
> set the channel topic: Development of the website [bioc2022.bioconductor.org](http://bioc2022.bioconductor.org), see [https://github.com/Bioconductor/BioC2022](https://github.com/Bioconductor/BioC2022)

**Levi Waldron** (10:29:35):
> set the channel description: coordinate the efforts for the web page for the bioc conference. Also see: #bioc2022 <#G01KMRQP3C7|bioc-conference-organization> #biocworkshops


## 2022-01-18

**Levi Waldron** (09:15:35) (in thread):
> Still not seeing it:[https://bioc2022.bioconductor.org/](https://bioc2022.bioconductor.org/)

**Levi Waldron** (09:15:42):
> Still no[https://bioc2022.bioconductor.org/](https://bioc2022.bioconductor.org/)

**Lori Shepherd** (09:17:41) (in thread):
> I dont know what additional settings if anything needs to be done for netify -- I set up the endpoint the same as I always do

**Levi Waldron** (09:18:14) (in thread):
> Do you still need to do something@Mikhail Dozmorov?

**Mikhail Dozmorov** (09:41:13) (in thread):
> It was a Netlify setting indeed.[http://bioc2022.bioconductor.org/](http://bioc2022.bioconductor.org/)is live now.

**Mikhail Dozmorov** (09:42:45) (in thread):
> There are some things to fix (logo, wording) - we can discuss during the call. I’ll fix the wording.

**Martin Morgan** (12:00:31) (in thread):
> ‘works for me’ (though it talks about registration for EuroBioC2020, which is a bit confusing…)


## 2022-01-22

**Lori Shepherd** (17:56:52):
> So -- I was getting ready to twitter announce abstracts open but i don't see a link on the website -- still just coming soon?  I'll wait until at least monday to tweet if someone can put in the PR and update the site so it has the active link please

**Mikhail Dozmorov** (18:14:56):
> It’s there now, I forgot adding it. Tested, submission works.


## 2022-01-28

*11:11:54 - @Megha Lal has left the channel*

## 2022-03-04

**Leo Lahti** (16:08:40):
> DL for abstract submissions to Bioc conference is in a few days from now (next Wednesday, March 9). I could not find information from the Bioc conference website, if virtual participation will be an option. The location also seems unknown, the website states "[The venue is currently being decided](https://bioc2022.bioconductor.org/)". With no information of the actual location, and/or remote option, I find it challenging to decide if it will be feasible for us to submit an abstract from Finland[https://bioc2022.bioconductor.org/](https://bioc2022.bioconductor.org/)- - also not sure who to contact as the "Organizers" subpage says "Organizers - Coming soon"


## 2022-04-14

**Lori Shepherd** (08:16:24):
> The bioc2022 site appears to be down@Mikhail Dozmorov. When I try to load the page I'm getting
> ```
> Secure Connection Failed
> 
> An error occurred during a connection to bioc2022.bioconductor.org. PR_END_OF_FILE_ERROR
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.
> ```

**Mikhail Dozmorov** (08:19:44):
> It may be isolated outages. I’m able to open it in “incognito” windows, although have to reload and sometimes it is garbled. Will be checking.


## 2022-06-09

**Leo Lahti** (01:55:54):
> The European BIoconductor meeting 2022 submission form does not list "Birds-of-a-feather" as a possible submission type, although the submission instructions at the meeting homepage do list this as one of the possible submission type.


## 2022-07-29

**Aedin Culhane** (16:03:10):
> RLadies Birds of a Feather is now 1:15-1:45.  Developers birds of a feather at Bioc2022 which start after RLadies


## 2023-01-18

*13:09:03 - @José Basílio has joined the channel*

## 2023-05-30

*08:44:09 - @Chiachun Chiu has joined the channel*

## 2023-08-04

*10:05:04 - @Nick Owen has joined the channel*

## 2023-11-21

*05:40:25 - @Konstantinos Geles (Constantinos Yeles) has left the channel*

## 2024-03-10

*16:30:48 - @Ikeh Darlington Ikeh has joined the channel*

## 2024-05-14

**Lori Shepherd** (09:44:00):
> archived the channel
