---
title: "#bioc2021"
---

## 2020-12-01

**Sean Davis** (11:20:56):
> @Sean Davis has joined the channel

**Sean Davis** (11:20:56):
> set the channel description: Discussion of bioc2021

**Charlotte Soneson** (11:22:40):
> @Charlotte Soneson has joined the channel

**Kayla Interdonato** (11:22:51):
> @Kayla Interdonato has joined the channel

**Simina Boca** (11:23:07):
> @Simina Boca has joined the channel

**Mikhail Dozmorov** (11:23:35):
> @Mikhail Dozmorov has joined the channel

**Sean Davis** (11:24:22):
> @Lori Shepherdcan you create a[bioc2021.bioconductor.org](http://bioc2021.bioconductor.org)DNS entry and point it to[https://bioc2021.netlify.app/](https://bioc2021.netlify.app/)
  - Attachment (bioc2021.netlify.app): [BioC2021](https://bioc2021.netlify.app/)
> Site template made by devcows using hugo

**Lori Shepherd** (11:24:27):
> @Lori Shepherd has joined the channel

**Lori Shepherd** (11:24:57):
> yes I can look into this

**Marc RJ Carlson** (11:25:30):
> @Marc RJ Carlson has joined the channel

**Sean Davis** (11:26:31):
> Thanks,@Lori Shepherd.@Mikhail Dozmorov, does this work for you?

**Sean Davis** (11:27:29):
> This leaves the bioc2021-test site as a playground for you.

**Mikhail Dozmorov** (11:28:33):
> bioc2021-test and[bioc2021.bioconductor.org](http://bioc2021.bioconductor.org)will be synchronized

**Sean Davis** (11:29:17):
> So, you’d rather have the DNS entry[bioc2021.bioconductor.org](http://bioc2021.bioconductor.org)point to[https://bioc2021-test.netlify.app](https://bioc2021-test.netlify.app)?
  - Attachment (bioc2021-test.netlify.app): [BioC2021](https://bioc2021-test.netlify.app)
> Site template made by devcows using hugo

**Lori Shepherd** (11:34:27):
> that doesnt seem right?   I would have assumed[https://bioc2021-test.netlify.app](https://bioc2021-test.netlify.app)and[https://bioc2021.netlify.app/](https://bioc2021.netlify.app/)are different no?  in which case we wouldn't want the test one linked to the subdomain

**Mikhail Dozmorov** (11:35:43):
> I have to investigate. It may be a redirect with[bioc2021.bioconductor.org](http://bioc2021.bioconductor.org)being the single domain.

**Aedin Culhane** (12:01:17):
> @Aedin Culhane has joined the channel

**Erica Feick** (12:05:41):
> @Erica Feick has joined the channel

**Levi Waldron** (12:05:56):
> @Levi Waldron has joined the channel

**Aedin Culhane** (12:07:14):
> Let add a discussion of  developer/community  challenges or other team type events that might work in a virtual format next month???

**Glenn Morton** (12:22:16):
> @Glenn Morton has joined the channel

**Tim Triche** (12:25:07):
> @Tim Triche has joined the channel

**Sean Davis** (13:36:00):
> @Mikhail Dozmorov, I’d suggest creating a new[https://bioc2021.netlify.app](https://bioc2021.netlify.app)and then point the DNS entry to that site. That leaves the possibility of adding content to the test site first.
> Just make two deployment scripts, one that deploys to bioc2021 and one that deploys to bioc2021-test.
  - Attachment (bioc2021.netlify.app): [BioC2021](https://bioc2021.netlify.app)
> Site template made by devcows using hugo

**Krutika** (13:36:05):
> @Krutika has joined the channel

**Sean Davis** (13:36:58):
> I see you’ve already created the second prod site,@Mikhail Dozmorov. Nice!

**Mikhail Dozmorov** (13:39:07):
> @Sean Davis, I’ll reconcile them later on. The one with the ‘-test’ suffix is the latest

**Sean Davis** (13:40:10):
> And the site looks fantastic!

**Sean Davis** (13:43:00):
> FYI, here is a new Hugo trick I recently learned. I automated page creation for a bunch of abstracts directly from the Google Forms spreadsheet using a Hugo archetype.[https://github.com/seandavi/genetics_branch_retreat_site](https://github.com/seandavi/genetics_branch_retreat_site). Here is the result:[https://seandavi.github.io/genetics_branch_retreat_site/](https://seandavi.github.io/genetics_branch_retreat_site/)

**Kevin Rue-Albrecht** (13:48:48):
> @Kevin Rue-Albrecht has joined the channel

**Andrew McDavid** (14:28:40):
> @Andrew McDavid has joined the channel

**Mikhail Dozmorov** (18:52:42) (in thread):
> Very interesting. Will try to adapt for the BioC2021 site.

**Mahmoud Ahmed** (20:45:16):
> @Mahmoud Ahmed has joined the channel


## 2020-12-02

**Konstantinos Geles (Constantinos Yeles)** (05:42:19):
> @Konstantinos Geles (Constantinos Yeles) has joined the channel

**Lori Shepherd** (09:51:59) (in thread):
> So I've done what I normally do linking the sub-domain as a CNAME and trying to forward to netify but it doesn't seem to like it.  We might have to do some troubleshooting.

**Aedin Culhane** (16:44:02):
> @Levi Waldron@Qian LiuAny dates/times for a sponsorship committee meeting?

**Qian Liu** (16:44:08):
> @Qian Liu has joined the channel


## 2020-12-03

**Levi Waldron** (18:44:28) (in thread):
> Maybe we can start with Slack if you could prep the GDrive folder and list of targets? Easiest way to schedule a meeting for me is[calendly.com/lwaldron](http://calendly.com/lwaldron).


## 2020-12-09

**Hena Ramay** (14:42:23):
> @Hena Ramay has joined the channel

**Sean Davis** (20:26:51):
> Updated “Orchestra” workshop site is here:[http://app.orchestra.cancerdatasci.org/](http://app.orchestra.cancerdatasci.org/). Login with github, google, or create an account. 47 workshops are pre-loaded.


## 2020-12-10

**Levi Waldron** (05:00:27):
> Sweet! Any future plans to allow user-billed persistent storage, so they can keep files there longer-term? Any other user benefits to login?


## 2020-12-12

**Huipeng Li** (00:41:20):
> @Huipeng Li has joined the channel


## 2020-12-15

**Francesc Català** (05:40:45):
> @Francesc Català has joined the channel

**Francesc Català** (05:40:59):
> @Francesc Català has left the channel

**Francesc Català** (05:41:02):
> @Francesc Català has joined the channel


## 2020-12-16

**Francesc Català** (11:41:03):
> @Francesc Català has left the channel


## 2020-12-17

**Kelly Street** (11:06:00):
> @Kelly Street has joined the channel

**Manojkumar Selvaraju** (11:11:20):
> @Manojkumar Selvaraju has joined the channel


## 2020-12-20

**Leo Lahti** (04:34:50):
> @Leo Lahti has joined the channel


## 2020-12-22

**Aedin Culhane** (15:43:39):
> Hi is[http://bioc2021.bioconductor.org/](http://bioc2021.bioconductor.org/)live yet.  Will there is pages[http://bioc2021.bioconductor.org/sponsor](http://bioc2021.bioconductor.org/sponsor)and[http://bioc2021.bioconductor.org/organizers](http://bioc2021.bioconductor.org/organizers)

**Mikhail Dozmorov** (17:13:56) (in thread):
> Not yet. Catching up on year’s end deadlines, revisiting the BioC2021 website is on top of my todo, before the next committee meeting.


## 2020-12-23

**Levi Waldron** (06:51:23) (in thread):
> @Lori Shepherdcould you create the redirect to mikhail's site? That would let us start making sponsorship requests even if the site isn't complete.

**Lori Shepherd** (06:55:27) (in thread):
> I asked sean and mikhail for help in an above thread: I've done what I normally do linking the sub-domain as a CNAME and trying to forward to netify but it doesn't seem to like it.  We might have to do some troubleshooting together

**Mikhail Dozmorov** (13:30:41) (in thread):
> We use Netlify to build the website. It has its own ways for domain redirect. Looks like the redirect works,[http://bioc2021.bioconductor.org/](http://bioc2021.bioconductor.org/)is live. Netlify has an option for DNS tweaking, I’m not sure we need it.
  - Attachment (bioc2021.bioconductor.org): [BioC2021](http://bioc2021.bioconductor.org/)
> Site template made by devcows using hugo

**Levi Waldron** (14:19:43) (in thread):
> Awesome!!!

**Mikhail Dozmorov** (15:17:21) (in thread):
> All pages are functional, and the sponsors/organizers links are there. Please, open issues at[https://github.com/Bioconductor/BioC2021/issues](https://github.com/Bioconductor/BioC2021/issues)to add content.@Aedin Culhane


## 2021-01-01

**Soumya Banerjee** (09:40:00):
> @Soumya Banerjee has joined the channel


## 2021-01-04

**Jenny Drnevich** (14:05:20):
> @Jenny Drnevich has joined the channel


## 2021-01-12

**Hugo Tavares** (04:02:48):
> @Hugo Tavares has joined the channel


## 2021-01-13

**Kevin Rue-Albrecht** (08:20:22):
> Is there a channel for bioc2021 organisers?

**Tim Triche** (09:20:08):
> I got triple-booked yesterday thanks to someone deleting a department meeting and not adding it back until 5 minutes beforehand:confused:

**Tim Triche** (09:20:17):
> so it would be ideal to catch up

**Lori Shepherd** (09:27:24) (in thread):
> not strictly.  some of the subcommittees use other channels -- like bioc-conference-noncompeting ,  bioc-conference-web , etc .

**Kevin Rue-Albrecht** (10:04:19) (in thread):
> thanks! i just wanted to minimize noise when I had queries between calls of the organising committee


## 2021-01-21

**JiefeiWang** (09:06:44):
> @JiefeiWang has joined the channel

**Aedin Culhane** (15:50:06):
> Rstudio conf is going on today. Its free and almost 12,000 people registered. Two things struck me about the organization

**Aedin Culhane** (15:50:20):
> 1. timezone.  They are repeating keynotes 12 hours apart

**Aedin Culhane** (15:51:18):
> 2. Video quality.  Speakers were sent a light rig and microphone and asked to video with their phones.  Seemingly phones provide better recordings that webcam

**Aedin Culhane** (15:51:44):
> I could ask curtis who organized the meeting to join us for a meeting if you wish


## 2021-01-22

**Kozo Nishida** (00:28:33):
> @Kozo Nishida has joined the channel

**Jonathan Speh** (05:15:45):
> @Jonathan Speh has joined the channel

**Kevin Rue-Albrecht** (14:04:50):
> [https://twitter.com/KevinRUE67/status/1352693670458372096?s=20](https://twitter.com/KevinRUE67/status/1352693670458372096?s=20)
  - Attachment (twitter): [Attachment](https://twitter.com/KevinRUE67/status/1352693670458372096?s=20)
> Do you want to present a talk, poster, or workshop at the [@Bioconductor](https://twitter.com/Bioconductor) #BioC2021 virtual #conference (4-6 Aug 2021)? Abstract submission is now open until March 9! Check out our great lineup of invited speakers and all the other details at [https://bioc2021.bioconductor.org/](https://bioc2021.bioconductor.org/) #rstats

**Annajiat Alim Rasel** (15:41:47):
> @Annajiat Alim Rasel has joined the channel


## 2021-01-24

**Frederick Tan** (14:56:13):
> @Frederick Tan has joined the channel


## 2021-01-26

**Aedin Culhane** (11:08:40):
> Do we have a call today?

**Kevin Rue-Albrecht** (11:10:45):
> my understanding is that no, it's a leftover of the two choices that@Levi Waldroncreated an invitation for

**Aedin Culhane** (11:11:01):
> I tried the zoom and google meet links.. but I was the only one… lonely I left:wink:

**Lori Shepherd** (11:11:03):
> I was on and no one came on so I left

**Kevin Rue-Albrecht** (11:11:19):
> the meeting was two weeks ago, and then every month

**Lori Shepherd** (11:11:33):
> Can@Levi Waldronremove the calendar invite then?

**Kevin Rue-Albrecht** (11:12:02):
> I hope i didn't mix up people, i think it was him

**Aedin Culhane** (11:12:05):
> Ok.. Thats:wink:

**Levi Waldron** (11:12:20):
> I have no idea where that invite is, it’s not on my calendar!

**Levi Waldron** (11:12:52):
> I wish I could make it disappear from everyone’s calendar…

**Kevin Rue-Albrecht** (11:14:43):
> looks like it's from your gmail, in case it helps at all
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F01KX8BVA4B/image.png)


## 2021-01-27

**Tim Triche** (09:28:02):
> I need to shove my Tuesday 11am out of the way if this is going to be the usual time

**Tim Triche** (11:00:30):
> thanks to@Erica Feickfor the spreadsheet, that is super handy.

**Erica Feick** (11:26:54):
> thanks@Tim Trichehopefully this will provide clarity on who is doing what as we move forward. I’ve reached out to hopin and airmeet for initial consultation; I can talk them them about setting up a demo and mutually agreeable time.


## 2021-02-08

**Matt Brauer** (15:24:53):
> @Matt Brauer has joined the channel


## 2021-02-12

**Janani Ravi** (15:51:50):
> @Janani Ravi has joined the channel


## 2021-02-17

**abdullah hanta** (16:05:22):
> @abdullah hanta has joined the channel


## 2021-02-24

**Kyle Alford** (11:40:09):
> @Kyle Alford has joined the channel

**Aedin Culhane** (14:27:55):
> ***Announcement:***Submit an abstract for a talk, digital poster, or Birds-of-a-feather session, or a syllabus for a software demo or long workshop at BioC2021 on Aug 4-6! The conference will most likely again be virtual this year.[https://bioc2021.bioconductor.org/submissions/](https://bioc2021.bioconductor.org/submissions/)
  - Attachment (bioc2021.bioconductor.org): [Submissions](https://bioc2021.bioconductor.org/submissions/)
> Submissions

**Jenny Drnevich** (22:21:54):
> @Andrew McDavidand I sent out email invitations to 143 new package authors to submit an abstract for BioC2021 and I have already got 4 positive responses. One also asked "I’m guessing this is planned as an online event given circumstances? It’s probably quite obvious, but it’d be nice to have it clearly stated on the conference page."@Mikhail Dozmorovmaybe now that Fred Hutch can't host this year, the website should be updated to say it will be a virtual conference?


## 2021-02-25

**Jonathan Goeke** (00:56:51):
> @Jonathan Goeke has joined the channel

**Jonathan Goeke** (01:23:09):
> thanks for organising Bioc 2021, I look forward to the event! Is anything known about registration fees (in particular for students)? sorry if I missed that information

**Levi Waldron** (07:24:14) (in thread):
> Agreed

**Levi Waldron** (07:28:37) (in thread):
> This would also be good to get up on the web page@Mikhail Dozmorov- we've discussed a sliding scale from $10 for students to $50 for funded researchers, with an easy request form for free admission, so cost shouldn't be a barrier.

**Levi Waldron** (07:29:57) (in thread):
> And, thanks for doing this!

**Mikhail Dozmorov** (07:43:25) (in thread):
> Added the “virtual” wording to the front page. I’ll create a registration page and run it by all before posting

**margherita mutarelli** (09:51:49):
> @margherita mutarelli has joined the channel


## 2021-02-26

**Jonathan Goeke** (10:43:41) (in thread):
> Thanks! That's very student friendly!!


## 2021-02-27

**Mikhail Dozmorov** (17:14:36) (in thread):
> Basic registration information is now available,[https://bioc2021.bioconductor.org/registration/](https://bioc2021.bioconductor.org/registration/)
  - Attachment (bioc2021.bioconductor.org): [Registration](https://bioc2021.bioconductor.org/registration/)
> Registration


## 2021-03-02

**Nitesh Turaga** (15:45:04):
> @Nitesh Turaga has joined the channel

**Nitesh Turaga** (15:45:16):
> How long is the Short-talk for Bioc2021 ?


## 2021-03-03

**Kevin Rue-Albrecht** (05:19:59):
> good point, I was going to redirect you to[https://bioc2021.bioconductor.org/submissions/](https://bioc2021.bioconductor.org/submissions/)but I realise that short talks don't have any indication of time.
> I suppose that we were waiting to see how many submissions we have, to pick a duration anywhere between 10 and 15 min (more than that doesn't really sound 'short' anymore)
  - Attachment (bioc2021.bioconductor.org): [Submissions](https://bioc2021.bioconductor.org/submissions/)
> Submissions

**Kevin Rue-Albrecht** (05:22:00):
> I'd suggest either:
> * 10 (talk) + 2 (Q&A), which would fit 5 talks in an hour
> * 15 (talk) + 5 (Q&A) which would fit 3 talks in an hour

**Kevin Rue-Albrecht** (05:23:17):
> The latter being easier to keep track of on a clock ('00, '20, '40), compared to ('00, '12, '24, '36, '48).

**Aedin Culhane** (11:59:23):
> Hi , its often easier to put Q&A in a panel, 4 x10 min or 5x8 min talks followed by 15 minute Q&A

**Nitesh Turaga** (12:00:30):
> I see! That is helpful information. Thanks.


## 2021-03-05

**Jim Hunter** (05:00:50):
> @Jim Hunter has joined the channel


## 2021-03-08

**Daniela Cassol** (11:47:00):
> @Daniela Cassol has joined the channel


## 2021-03-09

**Levi Waldron** (12:07:09):
> Submission deadline is extended to March 16 - submit! More specifically, submit a talk, digital poster, Birds-of-a-feather session, or a syllabus for a software demo or long workshop at BioC2021 on Aug 4-6! We can confirm that the conference will be virtual.[https://bioc2021.bioconductor.org/submissions/](https://bioc2021.bioconductor.org/submissions/).
  - Attachment (bioc2021.bioconductor.org): [Submissions](https://bioc2021.bioconductor.org/submissions/)
> Submissions

**Haichao Wang** (15:33:40):
> @Haichao Wang has joined the channel


## 2021-03-12

**Julia Romanowska** (14:50:52):
> @Julia Romanowska has joined the channel


## 2021-03-16

**Jenny Drnevich** (11:59:12):
> I am using@Sean Davis’s excellent[https://seandavi.github.io/BuildABiocWorkshop/](https://seandavi.github.io/BuildABiocWorkshop/)template for my Bioc2021 workshop submission. I've gotten through just about everything successfully except I cannot figure out how to get the changes to appear on the[github.io](http://github.io)page. Googling lead me to[https://lea.verou.me/2011/10/easily-keep-gh-pages-in-sync-with-master/](https://lea.verou.me/2011/10/easily-keep-gh-pages-in-sync-with-master/), which I tried but failed because it said`both modified:   pkgdown.yml`even though the master has`_pkgdown.yml`and gh-pages has`pkgdown.yml`, which I guess are considered the same file. Looking at some of the comments on that page, I probably do not want to do`get rebase master`because the master and gh-pages do not contain all the same files. Do I just need to`git checkout master`for particular files? Which all files? Thanks in advance!
  - Attachment (seandavi.github.io): [BuildABiocWorkshop](https://seandavi.github.io/BuildABiocWorkshop/)
> This package serves as a template for using github actions to prepare a Bioconductor Workshop package for use. In particular, a pkgdown website and docker image are generated based on workflow settings.

**Charlotte Soneson** (12:32:24) (in thread):
> I think the issue may be that GitHub Actions is not activated in the repo - the GitHub Actions workflow runs`pkgdown`and deploys the documentation so you won’t have to keep things in sync with the`master`branch manually.

**Jenny Drnevich** (13:29:25) (in thread):
> OK, I found out how to do that. "Actions" tab on the repo. Looks like`.github/workflows/basic_checks.yaml`is now running after I did a push.

**Sean Davis** (15:41:22) (in thread):
> Just to add, the gh-pages branch will almost never resemble the master branch. The gh-pages branch containns the actual website, not the code to create it. After running pkgdown, the gh-pages branch will contain the output.

**Jenny Drnevich** (15:43:29) (in thread):
> Thanks,@Sean DavisI did just open an issue on your package template about how to properly format the DOCKER_USERNAME in secrets. That is the only part that is failing for me now, but at least I have the pkgdown web page for the workshop submission!


## 2021-03-20

**watanabe_st** (01:56:29):
> @watanabe_st has joined the channel

**Mikhail Dozmorov** (11:57:52):
> BioC2021 website needs help,[see this issue](https://github.com/Bioconductor/BioC2021/issues/14). If anyone has a good knowledge of Hugo themes and CSS and can advice how to make speaker panels wider, please, comment or make a PR.
  - Attachment: [#14 Make speaker panels wider](https://github.com/Bioconductor/BioC2021/issues/14)
> Speaker panels for the 3x2 layout look narrow. I couldn't immediately find CSS formatting that would make speaker panels wider. Will continue looking, in a meantime - help wanted.


## 2021-03-22

**Sean Davis** (23:46:43) (in thread):
> Done.[https://github.com/Bioconductor/BioC2021/pull/15](https://github.com/Bioconductor/BioC2021/pull/15)
  - Attachment: [#15 Fix speaker page to be a little more visually appealing](https://github.com/Bioconductor/BioC2021/pull/15)
> fixes [#14](https://github.com/Bioconductor/BioC2021/issues/14)


## 2021-03-23

**Mikhail Dozmorov** (08:09:36) (in thread):
> Great, thank you. In retrospect, it is obvious that class="row ..." would be better than making the panels wider, horizontal layout is easier to read.

**Lambda Moses** (23:04:16):
> @Lambda Moses has joined the channel


## 2021-03-31

**Lisa Cao** (12:49:40):
> @Lisa Cao has joined the channel


## 2021-04-08

**Thomas Naake** (10:13:22):
> @Thomas Naake has joined the channel


## 2021-04-16

**Haichao Wang** (16:26:11):
> hi, have the decisions on the submissions been sent to authors?


## 2021-04-17

**Levi Waldron** (23:48:06) (in thread):
> Hi Haichao, I don’t believe so but they will be within the next few days. Sorry for the delay!


## 2021-04-18

**Haichao Wang** (06:40:19) (in thread):
> Hi Levi, thanks for the message, don’t worry! I was worrying whether the notification email was filtered out by security setting of my institution


## 2021-04-19

**Levi Waldron** (17:52:28) (in thread):
> They are now sent!


## 2021-04-20

**Haichao Wang** (07:59:41) (in thread):
> well noted! thanks


## 2021-04-25

**Leo Lahti** (11:14:19):
> Hi! The (positive) decision on Bioc2021 talk in[openreview.net](http://openreview.net)says "Please confirm your attendance and let us know if you have any scheduling restrictions" but I do not find information on how the attendance should be confirmed. Is the registration enough, and in which address the scheduling restrictions could/should be sent?


## 2021-04-26

**Keith Connolly** (12:09:36):
> @Keith Connolly has joined the channel


## 2021-04-28

**Mateusz Staniak** (18:16:37):
> @Mateusz Staniak has joined the channel


## 2021-04-29

**Jovan Tanevski** (04:30:07):
> @Jovan Tanevski has joined the channel


## 2021-05-03

**Wes W** (12:27:19):
> @Wes W has joined the channel

**Wes W** (12:28:04):
> will BioC 2021 stickers be mailed to people? I have a new laptop after my old one died and its looking naked


## 2021-05-04

**Erica Feick** (07:51:16) (in thread):
> yes, we plan to mail them out to people after the conference!


## 2021-05-11

**Megha Lal** (16:43:57):
> @Megha Lal has joined the channel


## 2021-05-12

**Federico Marini** (03:19:01):
> @Federico Marini has joined the channel

**Annekathrin Ludt** (05:04:59):
> @Annekathrin Ludt has joined the channel

**Kevin Blighe** (22:31:18):
> @Kevin Blighe has joined the channel


## 2021-05-13

**Leo Lahti** (04:52:43):
> I have a similar situation. The acceptance note said that the talk should be "confirmed" but there was no information how. I tried to ask here (above) and by sending email to the address that was mentioned in the acceptance note. But I have not received any replies.@Aedin Culhanedo you have any information about the accepted talks?

**Mikhail Dozmorov** (07:55:23):
> Now, all talks should be visible at[https://bioc2021.bioconductor.org/shorts/](https://bioc2021.bioconductor.org/shorts/).@Kevin Blighe,@Leo Lahti, yours are listed. Previously, this page showed 10 talks on one page, hence the confusion.

**Leo Lahti** (08:00:04):
> Great, thanks!

**Tim Triche** (10:48:11):
> remarkable selection of talks, congratulations to all

**Aedin Culhane** (12:02:54):
> @Mikhail DozmorovOn[https://bioc2021.bioconductor.org/shorts/](https://bioc2021.bioconductor.org/shorts/)is there a way to reduce to one track or see which talks are in which track?

**Aedin Culhane** (12:03:28):
> Also should the twitter feed on the front page show the tag #Bioc2021 or just @Bioconductor

**Mikhail Dozmorov** (12:05:25) (in thread):
> I believe, we don’t have short talks split by tracks yet,@Charlotte Soneson? But in principle it is possible.

**Mikhail Dozmorov** (12:07:32):
> Displaying tweets with the #Bioc2021 tag would be ideal, but I couldn’t find the way of doing that. If anyone has suggestions, please, let know. For now, I suggest the @Bioconductor account retweets most relevant tweets.

**Charlotte Soneson** (12:09:04) (in thread):
> Yes, the track assignment is in the google sheet (the “slot” column).

**Mikhail Dozmorov** (21:16:27) (in thread):
> Now we have pages with all abstracts and track-specific abstracts. Headers for the listing pages have underscores, looking into it.


## 2021-05-18

**Marc RJ Carlson** (12:22:02):
> Hey guys,  Since its the 20th anniversary, I popped into the wayback machine to see what the Bioconductor site looked like all the way back in 2002 (as far back as the wayback machine had archived).  Check it out:[https://web.archive.org/web/20020327093500/http://www.bioconductor.org/](https://web.archive.org/web/20020327093500/http://www.bioconductor.org/)

**Marc RJ Carlson** (12:22:24):
> There are other timepoints you can look at as well, this was just the oldest...

**Marc RJ Carlson** (12:23:21):
> But it occurs to me that if you wanted to do something commemorative (stickers or backgrounds etc.), that this is a good way to get inspirational images.


## 2021-05-19

**Jenny Drnevich** (16:19:03):
> I looked back through my own files to see the earliest R stuff I could find, and came across this gem from the Westmead Millennium Institute.
  - File (PDF): [biologistguide to bioconductor.pdf](https://community-bioc.slack.com/files/U34P8RS3B/F022MEE5DJ8/biologistguide_to_bioconductor.pdf)


## 2021-05-20

**Federico Marini** (03:05:29):
> On a similar line for the anniversary spirit: Is there any plan to give the releases a name? I recall we were proposing naming schemes, and I was a strong proponent of coffee types:coffee::coffee:

**Federico Marini** (03:06:18):
> (asking this as I just saw that also RStudio started giving their releases a name ->[https://twitter.com/kevin_ushey/status/1395054942088400905?s=20](https://twitter.com/kevin_ushey/status/1395054942088400905?s=20))
  - Attachment (twitter): [Attachment](https://twitter.com/kevin_ushey/status/1395054942088400905?s=20)
> PSA: If you're an RStudio user planning to upgrade to R 4.1.0, you may want to install the preview release of RStudio ([https://www.rstudio.com/products/rstudio/download/preview/](https://www.rstudio.com/products/rstudio/download/preview/)) -- otherwise, you may see RStudio crash when you try to use ggplot2. :grimacing: #rstats

**Federico Marini** (03:07:21):
> looks like they went flowers:slightly_smiling_face:

**Kevin Rue-Albrecht** (07:57:23):
> Just a thought - I can't remember what other themes were suggested - how about musical genres and/or artists? That could match well  the "conductor" part of BioC.
> e.g.`ragtime tchaikovsky`:smile:

**Kevin Rue-Albrecht** (08:01:43):
> That said, it also prompts me to wonder what the added value is for naming releases. I haven't had to refer much to named releases in recent times, and I find numbered releases more intuitive to track anyway. What would be the use case for using named releases in Bioconductor? Would`BiocManager::install()`be taught how to map names to numbered releases? Personally I'd still use the number then, as it would most likely be faster to type and track over time

**Federico Marini** (08:48:48):
> > the added value is for naming releases
> I’d say merely fun.
> On the same line one names servers with wine names:smile:(my previous boss had PCs named with latin names of fishes - 1st declination for laptops, 2nd declination for servers)

**Federico Marini** (10:18:27):
> Composers are actually quite a good idea, damn:grimacing:


## 2021-05-25

**Aedin Culhane** (11:12:01) (in thread):
  - File (PNG): [Screen Shot 2021-05-25 at 11.09.35 AM.png](https://community-bioc.slack.com/files/U34P8RS3B/F022ZLV6CLT/screen_shot_2021-05-25_at_11.09.35_am.png)

**Aedin Culhane** (11:18:43):
> Classical, Jazz, Blue or  rock …..  Handle or Hendrix ! Beethoven or Otis Blackwell.

**Aedin Culhane** (12:05:50):
> First post on Bioc mailing list

**Aedin Culhane** (12:07:04):
  - File (PNG): [Screen Shot 2021-05-25 at 12.06.43 PM.png](https://community-bioc.slack.com/files/U34P8RS3B/F022T0F0STG/screen_shot_2021-05-25_at_12.06.43_pm.png)


## 2021-05-26

**Tim Triche** (10:23:59):
> wow@Vince Careyreally has been here right from the beginning:sunglasses:


## 2021-05-28

**Lori Shepherd** (14:33:18):
> Deadline for nominating someone for a Bioc2021 award is this weekend! May 31st.   See more information at[http://bioconductor.org/about/awards/](http://bioconductor.org/about/awards/).   The nomination form can be found at[https://forms.gle/d9PyAjAw62yVKxjL8](https://forms.gle/d9PyAjAw62yVKxjL8)
  - Attachment (Google Docs): [Bioconductor Awards 2021](https://forms.gle/d9PyAjAw62yVKxjL8)
> Nomination form for the Bioconductor Awards (see [https://bioconductor.org/about/awards/](https://bioconductor.org/about/awards/) for more details). Please fill out all the fields in the following sections. In the Nominator section, please provide your own contact information in case we need to contact you with any question. In the Nominee section, please indicate how the nominee provides outstanding contributions for each of the selected nomination criteria. Four awards will be given using the selected criteria as justification.


## 2021-06-23

**Stephen Mosher** (16:30:25):
> @Stephen Mosher has joined the channel


## 2021-06-29

**Simone Montalbano** (07:25:02):
> @Simone Montalbano has joined the channel


## 2021-07-04

**Mirko Brüggemann** (09:02:44):
> @Mirko Brüggemann has joined the channel


## 2021-07-09

**Erica Feick** (13:34:10):
> Scholarship and caregiver award applications are still open for BioC2021!
> If you are currently experiencing financial hardship or reduced funding, please apply for a[BioC2021 Scholarship](https://docs.google.com/forms/d/e/1FAIpQLSeOE8FfcewYccR37o5dtC_tUjTCE5cKbyVMC_68uMuC3CgQbA/viewform?usp=pp_url)for a waiver on the registration fee.
> Bioconductor is offering a limited number of awards to cover caregiving expenses for BioC2021 attendees. If you need assistance with childcare or eldercare during the course of the conference, please[apply here](https://forms.gle/8sUSgNwKFDFEZii58).
  - Attachment (Google Docs): [BioC2021 Caregiver Award Application](https://forms.gle/8sUSgNwKFDFEZii58)
> Awards of up to $300 per family are available to Bioconductor attendees who will be incurring additional expenses for childcare or other caregiving responsibilities (such as elder care) during the meeting. APPLICATION DEADLINE IS JULY 1, 2021. Notifications will be made by July 8th.


## 2021-07-12

**Harpo MAxx** (11:52:19):
> @Harpo MAxx has joined the channel

**Harpo MAxx** (11:58:19):
> Hello everybody. I'm new to BioC,  I submitted a poster and I would like to know if  are the posters being presented live during the poster session? or I need to submit a video of the presentation? Or perhaps the poster will be just published on the conference website? As you can see, I have several questions:man-facepalming:. Any help you can provide me will be great.

**Kevin Rue-Albrecht** (13:12:35):
> Unless someone corrects me, each poster will be assigned to a virtual table, where the presenter is expected to remain for the duration of the session, so that participants can join and ask questions.
> I can't think that the platform allows to play videos on demand at tables (i.e., a participant would join a table, and click a button that launches a recorded poster presentation). Could be a nice request to the platform, now that I think of it.

**Harpo MAxx** (16:26:22) (in thread):
> Thanks for your answer Kevin!.. So basically it's similar to a "tradittional" poster session.:raised_hands:

**Peter Hickey** (18:32:29):
> @Peter Hickey has joined the channel

**Stephanie Hicks** (19:11:34):
> @Stephanie Hicks has joined the channel

**Lukas Weber** (20:07:04):
> @Lukas Weber has joined the channel

**Sridhar N** (21:33:42):
> @Sridhar N has joined the channel

**Alexandra Garnham** (21:36:35):
> @Alexandra Garnham has joined the channel


## 2021-07-13

**Davide Risso** (01:25:05):
> @Davide Risso has joined the channel

**Almut** (01:46:19):
> @Almut has joined the channel

**Nils Eling** (04:17:45):
> @Nils Eling has joined the channel

**Stephany Orjuela** (04:20:44):
> @Stephany Orjuela has joined the channel

**Mireia Ramos-Rodríguez** (05:30:26):
> @Mireia Ramos-Rodríguez has joined the channel

**Chris Vanderaa** (06:06:25):
> @Chris Vanderaa has joined the channel

**Kevin Rue-Albrecht** (07:03:51) (in thread):
> yes, as close as possible, each table has a limited number of 'seats' on this platform, not unlike the limited amount of space around each poster.

**Erica Feick** (07:08:31) (in thread):
> Kevin is correct, you can share your screen to show your poster with table attendees but there is no video on demand option. We will be sending more detailed information to poster presenters soon.

**Ilaria Billato** (08:38:36):
> @Ilaria Billato has joined the channel

**mirna** (09:09:28):
> @mirna has joined the channel

**Jianhai Zhang** (21:00:28):
> @Jianhai Zhang has joined the channel


## 2021-07-14

**Roye Rozov** (03:16:07):
> @Roye Rozov has joined the channel

**Kevin Rue-Albrecht** (10:52:21):
> [https://twitter.com/KevinRUE67/status/1415323243934851080?s=20](https://twitter.com/KevinRUE67/status/1415323243934851080?s=20)
  - Attachment (twitter): [Attachment](https://twitter.com/KevinRUE67/status/1415323243934851080?s=20)
> The [@Bioconductor](https://twitter.com/Bioconductor) project is celebrating 20 years in 2021!
> Everyone is invited to contributed to a carousel of #xaringan slides to share memories and highlights of the project over the years!
> The slides will be featured during the BioC2021 conference 
> -> [https://github.com/kevinrue/Bioconductor20YearsSlides](https://github.com/kevinrue/Bioconductor20YearsSlides)


## 2021-07-16

**Tim Howes** (15:40:23):
> @Tim Howes has joined the channel


## 2021-07-17

**Pedro Baldoni** (20:17:52):
> @Pedro Baldoni has joined the channel


## 2021-07-18

**mariadermit** (01:32:25):
> @mariadermit has joined the channel

**Spencer Nystrom** (11:00:34):
> @Spencer Nystrom has joined the channel


## 2021-07-20

**Maya Reed McDaniel** (12:52:38):
> @Maya Reed McDaniel has joined the channel


## 2021-07-23

**Batool Almarzouq** (15:51:42):
> @Batool Almarzouq has joined the channel


## 2021-07-27

**philip terry** (15:33:32):
> @philip terry has joined the channel


## 2021-07-28

**Erick Cuevas** (23:54:49):
> @Erick Cuevas has joined the channel


## 2021-07-29

**Gurpreet Kaur** (01:02:11):
> @Gurpreet Kaur has joined the channel

**Dania Machlab** (04:08:19):
> @Dania Machlab has joined the channel

**Theresa Alexander** (11:22:09):
> @Theresa Alexander has joined the channel


## 2021-07-30

**Tom Sinden** (04:18:53):
> @Tom Sinden has joined the channel

**CristinaChe** (09:55:08):
> @CristinaChe has joined the channel


## 2021-08-01

**Leonardo Collado Torres** (18:33:51):
> @Leonardo Collado Torres has joined the channel

**Leonardo Collado Torres** (18:34:06):
> question from Twitter[https://twitter.com/rmflight/status/1421937792502931469](https://twitter.com/rmflight/status/1421937792502931469)
  - Attachment (twitter): [Attachment](https://twitter.com/rmflight/status/1421937792502931469)
> Ok, looking through the [@Bioconductor](https://twitter.com/Bioconductor) #bioc2021 schedule, there doesn't seem to be any real breaks built into the schedule of things??
> 
> [https://bioc2021.bioconductor.org/schedule/](https://bioc2021.bioconductor.org/schedule/)
> 
> Am I reading this right??
> 
> [@AedinCulhane](https://twitter.com/AedinCulhane) ??

**Robert M Flight** (20:31:54):
> @Robert M Flight has joined the channel


## 2021-08-02

**Charlotte Soneson** (01:26:21):
> [https://twitter.com/CSoneson/status/1422066072929308675](https://twitter.com/CSoneson/status/1422066072929308675)
  - Attachment (twitter): [Attachment](https://twitter.com/CSoneson/status/1422066072929308675)
> [@rmflight](https://twitter.com/rmflight) [@AedinCulhane](https://twitter.com/AedinCulhane) [@LeviWaldron1](https://twitter.com/LeviWaldron1) There are two longer (1-1.5h) ‘Networking breaks’ each day (2:30pm, 7pm Eastern time), during which no other program points are scheduled. And as [@AedinCulhane](https://twitter.com/AedinCulhane) mentioned, the sessions will be recorded and should be available to rewatch also in the platform.

**Nitesh Turaga** (08:58:10):
> There isn’t a birds of a feather or anything during the conference is there ?

**Erica Feick** (08:59:24):
> Yes, at 2pm PDT on Thursday August 5th.

**Nitesh Turaga** (09:00:06):
> I see, these are the ‘Networking’ sessions ?

**Nitesh Turaga** (09:00:19):
> Thanks@Erica Feick

**Erica Feick** (09:02:11):
> The networking sessions are breaks in the speaking schedule to allow people to join in the lounge and chat with other attendees. The August 5th at 2pm session features AnnotationHub2.0. We will also be accepting abstracts for lightning talks - watch for an announcement the first morning of the conference!

**Charlotte Soneson** (09:03:46):
> Also in your attendee email from last week there is a link to a form to “request a table” (in the lounge) (if you would like to organize a discussion session about something).

**Matt Paul** (10:35:29):
> @Matt Paul has joined the channel


## 2021-08-03

**Mike Smith** (08:58:48):
> @Mike Smith has joined the channel

**Johannes Rainer** (09:44:08):
> @Johannes Rainer has joined the channel

**Nick Owen** (14:53:07):
> @Nick Owen has joined the channel

**Astrid Deschenes** (21:00:26):
> @Astrid Deschenes has joined the channel


## 2021-08-04

**Michael Stadler** (05:35:20):
> @Michael Stadler has joined the channel

**Jeroen Gilis** (07:40:54):
> @Jeroen Gilis has joined the channel

**Shila Ghazanfar** (08:17:23):
> @Shila Ghazanfar has joined the channel

**Paula Beati** (08:21:58):
> @Paula Beati has joined the channel

**Dario Righelli** (08:22:31):
> @Dario Righelli has joined the channel

**Anke Busch** (08:22:45):
> @Anke Busch has joined the channel

**Laurent Gatto** (08:22:50):
> @Laurent Gatto has joined the channel

**Assa** (08:23:30):
> @Assa has joined the channel

**Aaron Wolen** (08:23:35):
> @Aaron Wolen has joined the channel

**Matteo Calgaro** (08:24:34):
> @Matteo Calgaro has joined the channel

**John Lee** (08:25:03):
> @John Lee has joined the channel

**Wes W** (08:25:47):
> morning:smiley:

**Nicole Kramer** (08:26:19):
> @Nicole Kramer has joined the channel

**Mike Sportiello** (08:27:14):
> @Mike Sportiello has joined the channel

**Julia Philipp** (08:27:26):
> @Julia Philipp has joined the channel

**Caroline Schreiber** (08:27:41):
> @Caroline Schreiber has joined the channel

**Oscar Lapuente Santana** (08:28:19):
> @Oscar Lapuente Santana has joined the channel

**Chase Clark** (08:28:46):
> @Chase Clark has joined the channel

**shristi shrestha** (08:28:56):
> @shristi shrestha has joined the channel

**Eric Davis** (08:29:02):
> @Eric Davis has joined the channel

**Vy Nguyen** (08:29:22):
> @Vy Nguyen has joined the channel

**Prateek Arora** (08:32:31):
> @Prateek Arora has joined the channel

**Matt Ritchie** (08:33:32):
> @Matt Ritchie has joined the channel

**Marianna Foos** (08:33:50):
> @Marianna Foos has joined the channel

**Jirawat I.** (08:33:57):
> @Jirawat I. has joined the channel

**Demitra Ellina** (08:34:08):
> @Demitra Ellina has joined the channel

**Marcel Ramos Pérez** (08:35:57):
> @Marcel Ramos Pérez has joined the channel

**Nitesh Turaga** (08:58:18):
> Good morning!

**Robin Lu** (09:15:13):
> @Robin Lu has joined the channel

**Tulasi Marrapu** (09:53:00):
> @Tulasi Marrapu has joined the channel

**Levi Waldron** (09:56:12):
> Morning everyone!

**Assa** (09:56:50):
> How long will the talks be available online (the watch replay)? or is it they also possible to download them to watch later?

**ChiaSin** (09:59:50):
> @ChiaSin has joined the channel

**Matt Paul** (10:00:43) (in thread):
> Seems like you can already rewatch the intro lecture which was just an hour ago.

**Assa** (10:03:00) (in thread):
> yes, you can already watch a few of them. But how long would this be possible?

**Erica Feick** (10:03:04) (in thread):
> The videos will be available at least through the weekend, perhaps longer. Eventually, all the talks will be uploaded to our YouTube Channel.

**Hosna Baniadam** (10:38:27):
> @Hosna Baniadam has joined the channel

**TimNieuwenhuis** (12:14:42):
> @TimNieuwenhuis has joined the channel

**Rene Welch** (12:16:36):
> @Rene Welch has joined the channel

**C. Mirzayi (please do not tag this account)** (12:51:50):
> @C. Mirzayi (please do not tag this account) has joined the channel

**Valerio Licursi** (14:09:04):
> @Valerio Licursi has joined the channel

**Sehyun Oh** (14:16:57):
> @Sehyun Oh has joined the channel

**Faris Naji** (14:20:42):
> @Faris Naji has joined the channel

**Faris Naji** (14:20:59):
> Hi all

**Nitesh Turaga** (14:23:49):
> Anyone try the ‘Start Networking’ button on Airmeet yet?

**Simina Boca** (14:28:47):
> I tried it and it timed me out

**Simina Boca** (14:31:02):
> I had some issues with updating my profile as well. We can ask Airmeet folks in the lounge, but I haven't gotten around to it yet.

**Nitesh Turaga** (14:31:20):
> Apparently we cannot update profile if we are given a link.

**Mikhail Dozmorov** (14:31:23):
> Same. I believe, it is based on interests added to the profile. But those interests are heavily industry-oriented, so hard to find the right ones.

**Simina Boca** (14:32:08):
> I wanted to add my Twitter handle and some sentences in the Intro, which also didn't work.

**Mikhail Dozmorov** (14:33:35):
> It may be best to ask Airmeet. My profile saves updates.

**Lakni Weerakoon** (15:22:38):
> @Lakni Weerakoon has joined the channel

**Maddy Griswold** (16:31:02):
> @Maddy Griswold has joined the channel

**Robert M Flight** (20:33:12):
> For everyone whose profile doesn't update: I think it depends on how you have previously accessed Airmeet and how you access it now. If this is your first time using Airmeet, and it's only via the ticket you purchased (i.e. you don't have an***account***with them), then I think you can only nominally update your profile. Pictures, introduction, interests, twitter, etc are all out the window.

**Robert M Flight** (20:33:39):
> When I talked to the help person, they indicated it was due to being at a ticketed event.

**Robert M Flight** (20:34:33):
> I did raise this on Twitter, and hopefully they will either change things, or at least put a big***warning***that says that those things can't be modified for ticket holders only who don't have an Airmeet account, or non-host persons maybe?

**Jenny Drnevich** (20:39:14):
> When will the videos be available to non-Airmeet participants, i.e., publicly on YouTube?

**Erica Feick** (20:53:04) (in thread):
> last year it took us about 3-4 weeks to get them up on YouTube - but it was rolling so we were adding new videos each week.

**Nitesh Turaga** (22:08:28):
> I will summarize my talk here for people who missed it because of time zone issues (or TL;DR)
> 1. Use Biconductor docker images`bioconductor/bioconductor_docker:[devel, RELEASE_3_13]`
> 2. Install Bioconductor packages lightning fast with a single function`AnVIL::install(<package_name>)`


## 2021-08-05

**Nick Owen** (05:18:27):
> Is there a way when recording the presentations Airmeet can maximize the presentation window, right now the videos take up such a small area of view that its hard to see on a laptop? Thanks

**Ambarish S. Ghatpande** (05:49:50):
> @Ambarish S. Ghatpande has joined the channel

**Kevin Rue-Albrecht** (07:31:56) (in thread):
> I hope I understand this correctly: it is possible to put the stream full screen. When you hover the top right corner of the stream, the full screen icon shows up

**Nick Owen** (08:18:43) (in thread):
> HI Kevin, thanks for replying. I know you can maximize the recording, but the actual recording doesn't have the presenters view maximized, its currently a window in the view, taking up less than half the space, which makes viewing workshops/slides difficult. When i watch them live its fine as I maximize that presenter view. The recordings don't show the chat anyway so not maximizing the presentation view would be great if possible.  Have put snapshot of maximized recording. Thanks!
  - File (JPEG): [IMG_20210805_131503_resized_20210805_011519498.jpg](https://community-bioc.slack.com/files/U34P8RS3B/F02A74JQ4E9/img_20210805_131503_resized_20210805_011519498.jpg)

**Kevin Rue-Albrecht** (08:24:24) (in thread):
> ah right thats unfortunate indeed

**Valerio Licursi** (08:24:36) (in thread):
> A workaround can be the Picture-in-picture mode that you can use clicking on this button over the video:
  - File (PNG): [button.png](https://community-bioc.slack.com/files/U34P8RS3B/F02ANQQLRGR/button.png)

**Nick Owen** (08:27:29) (in thread):
> @Valerio Licursiis that available on recorded videos, i dont see it , just a maximize and pause

**Nick Owen** (08:27:48) (in thread):
> dont get me wrong, having recorded presentations is brilliant and helpful, was just a thought:smile:

**Valerio Licursi** (08:30:01) (in thread):
> I see it also in the recordings… I’m using the last version of Firefox on mac

**Kevin Rue-Albrecht** (08:31:49) (in thread):
> We do welcome feedback that we pass on to the Airmeet platform. They are quite reactive and often implement new functionality within a couple of weeks when they accept (won't apply to this conference, unfortunately).

**Valerio Licursi** (08:32:06) (in thread):
> try to leave for a couple of seconds the mouse pointer over the video and the button should appear

**Nick Owen** (08:37:09) (in thread):
> Thanks, was using Edge on Win10, now using Firefox and that comes up, although still same video stream which makes sense, but atleast I have  a better way to watch it, thanks both!

**Valerio Licursi** (08:38:31) (in thread):
> :+1:

**Nick Owen** (08:50:05):
> *the minute you realize the sessions go on till 3am BST, when you thought it was midnight. So much good stuff!

**Andrew McDavid** (09:05:48) (in thread):
> I agree, the amount of letterboxing on the presenter's screen is definitely suboptimal.  It may depend on the aspect ratio of the materials being shared. sometimes it's quite substantial and interferes with legibility.

**Aedin Culhane** (09:15:27):
> Good morning .. day 2

**Kevin Rue-Albrecht** (09:18:24):
> you mean people actually went to sleep?:stuck_out_tongue::coffee::woozy_face::exploding_head:

**Robert M Flight** (09:33:48):
> Re: profile non-updating: This has apparently been fixed! You should be able to update your profile now with a pic, introduction, twitter handle, website, etc!
> 
> Interests are still the same, unfortunately. This seems to be hard coded in the Airmeet application. There isn't even an option to change them for a specific conference.:disappointed:

**Erica Feick** (09:35:22) (in thread):
> Thank you for the update Robert! The custom interests feature was not added in time for our conference (literally added last week). But I'm glad the other options are accessible now!

**Jenny Drnevich** (09:38:24):
> When does the Airmeet platform end? I am not sure I will be able to make the last workshops on Friday evening and I'd like to watch them later. But if Airmeet ends immediately after the conference, then I will have to wait a couple weeks for them to come out on YouTube? This doubly applies to all European attendees.

**Erica Feick** (09:41:36):
> Right now the conference will be open through the weekend, possibly longer. Working on a more concrete answer for you....

**Kevin Rue-Albrecht** (10:15:38) (in thread):
> Just to confirm that this point has been added to the list of items that we'll pass on to Airmeet. Hopefully the recordings will be better for future conferences!

**Rasha Shraim** (11:42:20):
> @Rasha Shraim has joined the channel

**Andres Wokaty** (11:46:13):
> @Andres Wokaty has joined the channel

**Sonali** (12:08:25):
> @Sonali has joined the channel

**Sonali** (12:16:43):
> @Lori Shepherd@Aedin Culhane- is there a slack channel for TAB which we can join ?

**Nitesh Turaga** (12:17:02):
> #tech-advisory-board

**Sonali** (13:12:38):
> Thanks@Nitesh Turaga

**Nitesh Turaga** (14:02:31):
> I’m available for Git related questions in the lounge now. If anyone is facing any issues. It’s table 9. I’m there for 1 hour.

**Nitesh Turaga** (14:09:59):
> Git and Bioconductor - Ask me anything.


## 2021-08-06

**Levi Waldron** (16:05:41):
> Sorry to drop out mid-sentence from the “New to BioC” table@Aedin Culhane@Nitesh Turaga@Federico Marini! I was a co-host so being at the talk now wasn’t optional I learned:smile:

**Federico Marini** (16:06:37):
> no prob Levi:slightly_smiling_face:I guessed there was the auto-magnet still operative just like in EuroBioc2020:smile:

**Levi Waldron** (16:08:06):
> Send my regrets!

**Federico Marini** (16:33:34):
> Will do/catch up in the next networking:slightly_smiling_face:

**Felix M** (19:29:41):
> @Felix M has joined the channel


## 2021-08-10

**Woo** (08:17:42):
> @Woo has joined the channel


## 2021-08-17

**Chris Fields** (12:15:25):
> @Chris Fields has joined the channel


## 2021-09-13

**Amy Guillaumet** (15:19:02):
> @Amy Guillaumet has joined the channel


## 2021-09-16

**Henry Miller** (18:35:29):
> @Henry Miller has joined the channel


## 2021-11-05

**Kozo Nishida** (04:14:32):
> Hi all. Did BioC2021 have a post-conference survey?
> If so, could you share the list of questions with me?
> I would like to refer to it in the BioC Asia 2021 survey.

**Stephanie Hicks** (20:34:24):
> @Stephanie Hicks has left the channel


## 2021-11-08

**Paula Nieto García** (03:25:31):
> @Paula Nieto García has joined the channel

**Erica Feick** (10:51:12) (in thread):
> Just shared a google doc with you with the questions from the post-conference survey.

**Kozo Nishida** (17:22:13) (in thread):
> @Erica FeickThank you for the information. I will use it as a reference.


## 2021-11-09

**Stephen Mosher** (08:28:36):
> @Stephen Mosher has left the channel


## 2021-11-11

**Shilpa Garg** (09:27:57):
> @Shilpa Garg has joined the channel


## 2021-11-29

**Vince Carey** (12:13:05):
> @Vince Carey has joined the channel

**Vince Carey** (12:14:01):
> I am looking at the bioc2021 web site and I see poster abstracts but no links to posters themselves.  Is that intended?

**Charlotte Soneson** (12:16:57):
> The landing page ([https://bioc2021.bioconductor.org/](https://bioc2021.bioconductor.org/)) has a link to[https://f1000research.com/gateways/bioconductor/bioc?selectedDomain=posters](https://f1000research.com/gateways/bioconductor/bioc?selectedDomain=posters)(“See all posters here”). But you’re right that there doesn’t seem to be a link on the schedule page.
  - Attachment (f1000research.com): [Posters from gateway Bioconductor - F1000Research](https://f1000research.com/gateways/bioconductor/bioc?selectedDomain=posters)
> Read the latest peer reviewed Bioconductor articles and more on F1000Research


## 2022-01-18

**Kelly Street** (10:20:00):
> @Kelly Street has left the channel


## 2022-01-19

**Stephany Orjuela** (10:10:36):
> @Stephany Orjuela has left the channel


## 2022-01-28

**Megha Lal** (11:11:56):
> @Megha Lal has left the channel


## 2022-02-23

**Paulina Paiz** (10:45:00):
> @Paulina Paiz has joined the channel


## 2022-03-08

**Marcel Ramos Pérez** (15:10:46):
> @Marcel Ramos Pérez has left the channel


## 2022-03-18

**Andres Wokaty** (09:59:48):
> @Andres Wokaty has left the channel


## 2022-03-29

**Tim Triche** (13:17:34):
> @Tim Triche has left the channel


## 2022-04-07

**Simone Montalbano** (08:44:46):
> @Simone Montalbano has left the channel


## 2022-06-13

**Alexandra Garnham** (20:39:33):
> @Alexandra Garnham has left the channel


## 2022-07-27

**Levi Waldron** (12:28:12):
> archived the channel
