---
title: "#bioc2020-bof-10sr"
format: gfm
---


## 2020-07-29

*04:21:30 - @Federico Marini has joined the channel*
*04:21:43 - @Charlotte Soneson has joined the channel*
*04:21:43 - @Davide Risso has joined the channel*
**Federico Marini** (04:22:40):
> Welcome everyone! This channel is tightly linked to the BoF proposed in here:[https://github.com/Bioconductor/BioC2020/issues/105](https://github.com/Bioconductor/BioC2020/issues/105)

**Federico Marini** (04:23:42):
> For having an overview here, I’ll repost the description:
> ---***Ten simple rules for thriving in bioinformatics research******Input/topic:***In the spirit of an open discussion, we would like to gather experiences and suggestions about how it is possible**as bioinformaticians/computational biologists**to develop software as well our own career in the Life Sciences, with a specific focus in the fields of academia, consulting, and research service.
> How can we for example improve the opportunities for recognition of our work (e.g. by being able to publish workflows and software), and encourage evaluation based on additional metrics than the “traditional” papers and citations. Or, touching another possible pain point, how can we acquire funding being mostly in the software/method development?
> We started a brainstorming session in one of the open Thematic Lounge sessions during e-Rum2020 and wanted to continue the discussion in a more targeted group.
> Ideally, this could develop into a “response” to the “Ten simple rules for providing effective bioinformatics research support”, recently posted on Plos Computational Biology[https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007531](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007531)- there the focus was on how to build up efficient ways to provide research support, while we would like to put a spotlight on the research aspects.***Output:***While the conversation will be kept in a very open format to enable the participation for attendees coming from diverse backgrounds and academic levels, we would like to document and structure the output of this BoF pretty much as a “Ten Simple Rules” collaborative manuscript.

*13:02:05 - @Nick Owen has joined the channel*

## 2020-07-30

*11:51:55 - @Keegan Korthauer has joined the channel*
*11:52:30 - @Dario Righelli has joined the channel*
**Federico Marini** (11:55:43):
> Link to the presentation leading in the BoF:[https://federicomarini.github.io/bioc2020bof/](https://federicomarini.github.io/bioc2020bof/)

*12:09:33 - @Riyue Sunny Bao has joined the channel*
*12:10:05 - @Nur-Taz Rahman has joined the channel*
*12:10:10 - @Adrija Kalvisa has joined the channel*
*12:11:03 - @Spencer Nystrom has joined the channel*
*12:11:16 - @Jeroen Gilis has joined the channel*
*12:11:18 - @Mirko Signorelli has joined the channel*
*12:11:35 - @Leopoldo Valiente has joined the channel*
*12:11:37 - @Simina Boca has joined the channel*
*12:11:39 - @Kelly Eckenrode has joined the channel*
*12:11:44 - @Stephany Orjuela has joined the channel*
*12:11:46 - @Constantin Ahlmann-Eltze has joined the channel*
*12:11:51 - @James Ashmore has joined the channel*
*12:11:51 - @Petra Palenikova has joined the channel*
*12:11:55 - @Sara Stankiewicz has joined the channel*
*12:12:14 - @Daniela Cassol has joined the channel*
*12:12:54 - @Regina Umarova has joined the channel*
*12:13:15 - @Dan Bunis has joined the channel*
*12:15:48 - @Erick Cuevas has joined the channel*
*12:31:05 - @Matthew McCall has joined the channel*
**Riyue Sunny Bao** (12:38:34):
> hiiii folks I was inspired by the discussion from #BoF regarding the recog of bioinformatician career in academia vs industry:star-struck:If you have time to check out the poll[https://twitter.com/RiyueSunnyBao/status/1288875156849528834](https://twitter.com/RiyueSunnyBao/status/1288875156849528834)
  - Attachment (twitter): [Attachment](https://twitter.com/RiyueSunnyBao/status/1288875156849528834)
    > As #bioinformatician, do you feel your #contribution is #recognized in your current work environment? 
    > 
    > Inspired by comments from #BioC2020 #BoF session and very curious on how the poll looks like! 
    > 
    > [@AcademicChatter](https://twitter.com/AcademicChatter) #AcademicChatter #AcademicTweeter #research #careeradvice

*12:41:16 - @Aditi Verma has joined the channel*
*12:42:03 - @Dania Machlab has joined the channel*
*12:42:12 - @CristinaChe has joined the channel*
*12:42:27 - @Devika Agarwal has joined the channel*
*12:43:06 - @Hendrick Gao-Min Lim has joined the channel*
*12:43:51 - @Lucy has joined the channel*
*12:45:19 - @Ayush Raman has joined the channel*
*12:52:05 - @Isha Goel has joined the channel*
*12:54:33 - @Sara Keeble has joined the channel*
*12:55:06 - @Andreas Gschwind has joined the channel*
*12:56:39 - @Ray Su has joined the channel*
*12:57:03 - @Vivek Das has joined the channel*
*12:57:07 - @Shila Ghazanfar has joined the channel*
**Ayush Raman** (12:57:12):
> Thanks@Federico Mariniand everyone for amazing discussion..

*12:57:17 - @Leonardo Collado Torres has joined the channel*
**Lucy** (12:57:38):
> Great session

*12:57:40 - @Jenny Drnevich has joined the channel*
*12:57:51 - @Tiago C. Silva has joined the channel*
*12:57:55 - @Vandhana has joined the channel*
**Erick Cuevas** (12:58:06):
> Excellent session

**Vivek Das** (12:58:15):
> Enjoyed the discussion. Thanks for organizing@Federico Marini@Charlotte Soneson&@Davide Risso

*12:58:29 - @Brice Sarver has joined the channel*
*12:58:40 - @Paula Beati has joined the channel*
**Simina Boca** (12:59:02):
> Yes, this was super fun!

**Davide Risso** (12:59:47):
> thanks you all for participating in the discussion! Let's keep it going here on slack!

**Brice Sarver** (13:00:41):
> Hi everyone - Brice here from the industry discussion earlier!

**Sara Keeble** (13:01:19):
> Hi all, thanks for the discussion! I had submitted the statement regarding bioinformatics in industry and would be happy to chat about the differences between industry and academia also

**Davide Risso** (13:03:10):
> yes, I think we should definitely have one "rule" that explores the different career paths (industry, academia, service, ...)

**Shila Ghazanfar** (13:04:44):
> I liked@Keegan Korthauer’s latest point, indeed bioinformatics research *******can******* be done without collaboration, but can be much stronger with collaboration. The biggest time & energy sinks can also stem from poor collaborations, so a ‘rule’ is to try to identify in which situations where there can be mutual benefits, or is worthwhile to pursue without collab

*13:05:06 - @Antonio Colaprico has joined the channel*
**Riyue Sunny Bao** (13:05:21):
> loved the session!!

**Riyue Sunny Bao** (13:06:16) (in thread):
> Hi Sara!! is the statement public? would love to hear more from you!

*13:06:16 - @Aedin Culhane has joined the channel*
**Aedin Culhane** (13:06:27):
> Nicely organized session

**Kelly Eckenrode** (13:07:37):
> Thank you so much for this workshop. As a novice, it was nice to listen in.

**Riyue Sunny Bao** (13:10:16):
> I'd love to hear more from everyone regarding the #career path of bioinformaticians in #academia! I am building a case to ask my institution to change the job category and build a new career structure for our bioinformaticians. if you are happy about your role, what makes you feel most recognized - e.g. 1st author papers, chances to lead projects, participant in grants? would you prefer job role as staff scientists or research faculty?

**Sara Keeble** (13:11:14) (in thread):
> Hi Riyue! I'm not sure if they put all the questions up from the discussion somewhere, but I had just said in my experience that bioinformatics scientists are respected more in industry than academia and have better opportunities. I made the transition a couple of years ago so it's something I've thought about a lot.

**Vivek Das** (13:11:35):
> As long as we don’t look moving to industry as failure, things will improve. Career decisions can be due to many factors and interests. Collaborations is very important but so are our own capabilities and limits identification. Finding a mentor can help who can guide, provide a mentee to take the flight and risks, teach them not to be afraid of failures and take stand if collaboration gets toxic. Jenny raised great points and so as Aedin. I always try to see how we can balance between Demand & supply vs Innovation but that also means the person needs some sort of independence and support.

*13:12:03 - @Anabella has joined the channel*
**Riyue Sunny Bao** (13:12:49) (in thread):
> yes definitely!! I have been interested in this for long time and back in my previous employer we fought mouth to teeth to restructure the career path for bioinformaticians in order to make a more sustainable environment for our scientists, that took 2 years and only 60% of our suggestions were implemented by HR. We eventually almost all left. I am trying to make the same changes in my current institution.

*13:14:33 - @Sidharth Sen has joined the channel*
**Riyue Sunny Bao** (13:16:59) (in thread):
> Thanks Sara! Yes I also have friends as bioinformaticians in industry, and when I was expressing my frustration to them, they were like you should come here and you would never feel undervalued!:sweat_smile:I am in academia building my lab now and still trying to fight the stereotype, but joining industry is definitely a possibility for me in the future!

**Keegan Korthauer** (13:17:28) (in thread):
> Many great points about selecting collaborators in the session. I agree with your rule suggestion. Would be good to brainstorm specific points for*how *to identify which might be mutually beneficial to collab and which to pursue without (and the related point - what are key factors to look for in a mutually beneficial collab)

**Riyue Sunny Bao** (13:17:48) (in thread):
> what do you like most about the industry - is it stable funding, no one fighting for the authorship, folks tend to share the rewards instead of winner taking it all?

**Riyue Sunny Bao** (13:20:05):
> Would anybody be interested in putting together a thread or a blog post integrating everybody's inputs about academia vs industry? I have students asking me the same question when I was on panel discussions for career development previously and this would be definitely very beneficial for them.

**Vivek Das** (13:20:45):
> Should we try to put it as academia and industry rather than making it sound as a comparison? It’s a request. Thanks:blush:

**Riyue Sunny Bao** (13:21:32):
> Very good point@Vivek Das!!! sorry what I meant was more like a general discussion rather than comparison:joy:

**Vivek Das** (13:22:11):
> I am happy to share my experience who has worked also worked in IT service industry before PhD and now working over 2.5 yrs as an industry postdoc. Happy to share my personal experience and opinion if that helps.

**Riyue Sunny Bao** (13:23:19):
> that is amazing!! maybe we could start putting it together on google doc? maybe we could ask for folks to chip in same time:flushed:we would need to make it anonymous though

**Sara Keeble** (13:23:33) (in thread):
> I understand where you're coming from for sure, good luck! I saw your comment about your plan to better your institution's bioinformatics career tracks, and I think that's fantastic. That's really what it comes down to for me - many universities don't offer appealing career growth or compensation for bioinformatics scientists, and refuse to compete with companies in that regard by telling students they are failures for leaving academia. What I personally like the most about the nature of work in industry is actually the opportunity to work with teams of bioinformaticians rather than doing everything on my own. The stable funding, career growth potential, and compensation made it a clear choice for me at the end of the day.

*13:24:20 - @Selvi G has joined the channel*
**Brice Sarver** (13:24:22):
> I think you should carefully consider what an academic bioinformatician/data scientist/computational biologist/[insert similar title here] would mean. The endpoint is critical. In academia, it's either professor or bioinformatics core director (plus others). In industry it's everything from postdoc, junior scientist, senior scientist, team lead, assistant director, director, VP, SVP, CSO - all with different roles depending on how much of the business you want to be involved with

**Brice Sarver** (13:25:01):
> Very hard to include in a single conversation, as a scientist can easily move to operations and become more a managerial role as opposed to hands-on

**Vivek Das** (13:25:09):
> Agree with@Brice Sarverthis is something we should keep in mind.

**Brice Sarver** (13:25:10):
> In academia, it's much more linear

**Riyue Sunny Bao** (13:26:44) (in thread):
> Yes I have been in academia as bioinformatician for 8 years and I echo everything you said! lack of career path is a big issue, compensation is another! and the stereotype against bioinformaticians as we are only doing "support" - which is completely biased and wrong. Thanks so much for sharing your experience in industry! would you be interested in joining if we put together a shared doc about the acedamia and industrial environment for bioinformaticians?

**Brice Sarver** (13:27:15):
> I can definitely weigh-in, just like@Vivek Das, so let me know how you'd like to see the discussion oriented. I've had friends and colleagues progress through academic appointments of all flavors, though my personal experience is more limited there

**Vivek Das** (13:27:22):
> There are opportunities and options, it’s on the community how to create them both in academia and in industry. Although I do know industry do have dedicated positions allotted.

**Riyue Sunny Bao** (13:29:22):
> One thing I heard from my friends in industry was that usually your role is well defined, e.g. variant calling. Then there may be limitation for a person to expand their skills and gain experience from other areas. What's your thought@Brice Sarver@Vivek Das?

**Brice Sarver** (13:30:24):
> I'd disagree. I am working on a bunch of different projects with a number of different teams, and I'm leading some of them. I get the freedom to choose how I want to proceed given current needs, keeping in mind general goals and objectives

**Vivek Das** (13:30:36):
> It depends on the group and on the department. Be it on R&D side or product side. My experience says it’s also how organization structure is.

**Brice Sarver** (13:30:41):
> You may be a point-person for a particular project and have deliverables there, but it's not narrow in my experience

**Vivek Das** (13:31:00):
> If you ask me, I work on multiple projects that’s because I get the independence

**Vivek Das** (13:31:29):
> And also our department is open and disruptive. We like to challenge and get challenged. Don’t mind failures but fast fail.

**Vivek Das** (13:31:46):
> This has been the exciting part for me in past 2.5 yrs

**Riyue Sunny Bao** (13:31:50):
> thanks! definitely sounds it could be company culture dependent:flushed:

**Brice Sarver** (13:33:01):
> Definitely company-dependent, for sure. But i've worked in diagnostic genetic testing, liquid biopsy/biotech, and pharma and (contrary to what my friends in academia suggested), the culture has generally been pretty good with fantastic work-life balance

**Vivek Das** (13:33:52):
> I know that there is a difference between Product side vs R&D. I have only worked in IT service and R&D in the industry so cant say much on the product side.

*13:34:07 - @Nitesh Turaga has joined the channel*
**Vivek Das** (13:34:40):
> There is a lot of process driven rigorous science happening in the industry. It’s just a matter of outreach.:blush:

**Vivek Das** (13:34:59):
> @Brice Sarverhas more experience than me here.

**Vivek Das** (13:35:56):
> Again, all my takes are based on my experience. But if this helps I am happy to chat with folks who are interested to know more.

*13:36:14 - @Christian Brueffer has joined the channel*
**Riyue Sunny Bao** (13:37:51):
> the good news might be that more and more universities have strong connections with industries and pharmas, and they have their own spin off start up companies. I have my good hope that such bias will be gone in the next 5 years ..........
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596129095038100)
    > As long as we don’t look moving to industry as failure, things will improve. Career decisions can be due to many factors and interests. Collaborations is very important but so are our own capabilities and limits identification. Finding a mentor can help who can guide, provide a mentee to take the flight and risks, teach them not to be afraid of failures and take stand if collaboration gets toxic. Jenny raised great points and so as Aedin. I always try to see how we can balance between Demand & supply vs Innovation but that also means the person needs some sort of independence and support.

**Antonio Colaprico** (13:38:07):
> Hi all, thank you for this really interesting workshop and it is was great hear from@Davide Risso

**Brice Sarver** (13:39:31):
> I agree@Riyue Sunny Bao, but the tricky part about this is that you'll have people who have only ever worked in academia or are professors trying to provide career advice to soon-to-be graduates or postdocs, and there's a big mismatch between perceptions and reality

**Vivek Das** (13:39:41):
> I am hoping for the same@Riyue Sunny Bao. We need more folks to speak up and make the outreach to bring out better Industry-academia alliance that can be strong to encourage students about varied options.:smiley:

**Sara Keeble** (13:40:58) (in thread):
> I completely agree! No problem, sure I'd be happy to contribute

**Riyue Sunny Bao** (13:42:21):
> @Brice Sarver@Vivek Dasyes I really believe there is a lack of knowledge from academia students on how an industrial work environment***really***looks like those days .... and I have seen cases there professors discouraged industrial internship!! I mean we are in 2020:sweat_smile:

**Vivek Das** (13:42:57):
> I am hoping in my lifetime this will change and improve.:blush:

**Riyue Sunny Bao** (13:43:03):
> same here !!

**Riyue Sunny Bao** (13:44:08):
> building`Industry-academia alliance`is definitely the key:slightly_smiling_face:and also relevant to funding. Given it is almost impossible to get sustained funding from NIH, many researchers are now funded by industries and no-profit foundations , which are also good choices

**Vivek Das** (13:45:04):
> Well it’s all about generalization. I shouldn’t be generalizing academia so someone else with no experience of industry should also not be generalizing industry.:wink:

**Riyue Sunny Bao** (13:45:10):
> for students who come to me, I usually suggest them to look for internship in industry , then decide where they want to go

**Brice Sarver** (13:47:00):
> I'm excited by the prospect of more 'industry postdocs,' and professors need to not be scared about letting a student complete a summer internship. I've seen several folks rotate through during their summers during their PhDs, and I think it really gives some good experience and perspective

**Brice Sarver** (13:47:50):
> In my original field of training (evolutionary genomics), zero folks complete internships (and are generally expected to still work over the summer or do field work then)

**Brice Sarver** (13:48:04):
> I guess I shouldn't say zero:slightly_smiling_face:- zero that I know of

**Riyue Sunny Bao** (13:49:39):
> I almost applied for a CPT year:joy:

**Riyue Sunny Bao** (13:49:58):
> (industrial intern for F-1 students)

**Riyue Sunny Bao** (13:50:20):
> that was 15 years ago and there was push back for students to do interns at companies

**Riyue Sunny Bao** (13:50:33):
> most likely you should do a lab intern

**Riyue Sunny Bao** (13:50:34):
> :thinking_face:

**Riyue Sunny Bao** (13:51:14):
> I think in general we should educate students that there are more ways to be successful if not staying in academia.

**Federico Marini** (13:58:33):
> Hi there<!channel>- just exploiting the break after the lightning to thank you***all ***for the so many and compelling points you raised!
> Let’s keep the discussion flowing in here, I’ll make sure we do not lose any bit of the comments you provided:wink:

**Simina Boca** (14:03:15):
> We should note that it's not as simple as academia vs. industry, there are also positions are med schools that are more focused on service, multiple types of govt positions (with more or less research - some are actually tenure-track), non-profit, consulting

**Simina Boca** (14:03:27):
> Industry is also not just pharma

**Simina Boca** (14:04:09):
> I've only been in academia so not familiar with all of this directly, but it would be helpful for folks in the field to learn about

**Simina Boca** (14:05:00):
> Perhaps we need a diagram:joy:

**Brice Sarver** (14:05:08):
> For sure@Simina Boca- I've worked in government for the USDA, did an academic postdoc, worked in genetic testing for several years, and I'm now in pharma - I can comment on my time in any of these

**Vivek Das** (14:05:48):
> That’s the key@Simina Boca. Industry isn’t just pharma. It’s also small biotech, startups, Bioinformatics product or Genomics products company.

**Vivek Das** (14:06:00):
> They also have varied departments.

**Simina Boca** (14:06:11):
> Yeah

**Vivek Das** (14:06:27):
> All consumables used in research mostly come from industry . Isn’t it? At least in Omics based ones?

**Simina Boca** (14:06:32):
> In terms of what@Matthew McCallsaid about "not calling yourself a bioinformatician" - there are also multiple job titles

**Riyue Sunny Bao** (14:09:44):
> I think we can introduce ourselves as bioinformatician just like a med doc introduces as oncologist? no?:flushed:

**Vivek Das** (14:09:49):
> Just to drop another info, look at technology companies now & how much they are developing infrastructure for Bioinformatics analysis plus their research in high dimensional data and applied ML/DL. I don’t think I need to name the big 4. They also do data science related stuffs that may or may not overlap with Bioinformatics.

**Riyue Sunny Bao** (14:10:23):
> yup super important point!!
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596132589099300)
    > Just to drop another info, look at technology companies now & how much they are developing infrastructure for Bioinformatics analysis plus their research in high dimensional data and applied ML/DL. I don’t think I need to name the big 4. They also do data science related stuffs that may or may not overlap with Bioinformatics.

**Brice Sarver** (14:10:43):
> I'll say that title matters in one important arena - what the non-technical recruiter or first-pass screener sees when they get your resume or CV

**Riyue Sunny Bao** (14:11:05):
> @Vivek Das@Brice Sarverwe almost felt we could write a paper about this? career paths of bioinformaticians in different sectors?

**Brice Sarver** (14:11:11):
> In mine, I have various mentions of computational genomics, bioinformatician, and data scientist, even though this group will understand that there's a lot of overlap

**Matthew McCall** (14:11:18) (in thread):
> It was mostly a joke, but I do think it can make for an easier career, at least historically.

**Riyue Sunny Bao** (14:11:21):
> also cc@Simina Boca

**Vivek Das** (14:12:10):
> Title is important when one is applying for industry positions for initial automated screening. I agree with@Brice Sarver. But there are ways to also make better CV and/or Motivation letter for the recruiter or automated screening to pick up a CV.:blush:

**Brice Sarver** (14:12:37):
> @Vivek Dasdefinitely. letter is really important. just something to consider in the era of LinkedIn

**Federico Marini** (14:13:17):
> hopping onto this: I’d definitely recommend to***curate your public profiles ***(github, scholar, twitter if you use it, …)

**Riyue Sunny Bao** (14:13:52):
> I have seen a joke e.g. statisticians should put data scientists as job title to sound more sexy even thou statistians are way more qualified for ds analysis

**Aedin Culhane** (14:14:32):
> More qualified that who?

**Riyue Sunny Bao** (14:15:02):
> perhaps a better way to say this is lots of ds work are statistics

**Aedin Culhane** (14:15:08):
> Degrees in DS are really recent, so most people in DS came from stats/math/CS etc

**Riyue Sunny Bao** (14:15:36):
> I agree

*14:15:40 - @Rene Welch has joined the channel*
**Vivek Das** (14:15:49):
> Yes, totally agree with@Aedin Culhane.

**Stephany Orjuela** (14:15:59):
> @Brice Sarveryou mentioned you changed between the three different sectors, was this a conscious decision? Do you think you have benefited from changing between the sectors rather than staying in one? (Sorry of this is more of a personal ques)

**Aedin Culhane** (14:16:04):
> Many of the comments raised in the sessions could easily have been said 5-10 years ago too
> Watson (2013)[A guide for the lonely bioinformatician](http://www.opiniomics.org/a-guide-for-the-lonely-bioinformatician/)**** ****[http://www.opiniomics.org/a-guide-for-the-lonely-bioinformatician/](http://www.opiniomics.org/a-guide-for-the-lonely-bioinformatician/)Corpas et al., (2012)***How Not to Be a Bioinformatician ***[https://scfbm.biomedcentral.com/articles/10.1186/1751-0473-7-3](https://scfbm.biomedcentral.com/articles/10.1186/1751-0473-7-3)
  - Attachment (Opiniomics): [A guide for the lonely bioinformatician](http://www.opiniomics.org/a-guide-for-the-lonely-bioinformatician/)
    > This may be a uniquely UK centric blog post but I suspect not.  Let me start with a brief story.  Sat with a coffee in our canteen a few weeks ago, I overheard a conversation between a few PIs abou…
  - Attachment (Source Code for Biology and Medicine): [How Not to Be a Bioinformatician](https://scfbm.biomedcentral.com/articles/10.1186/1751-0473-7-3)
    > Although published material exists about the skills required for a successful bioinformatics career, strangely enough no work to date has addressed the matter of how to excel at not being a bioinformatician. A set of basic guidelines and a code of conduct is hereby presented to re-address that imbalance for fellow-practitioners whose aim is to not to succeed in their chosen bioinformatics field. By scrupulously following these guidelines one can be sure to regress at a highly satisfactory rate.

**Riyue Sunny Bao** (14:16:35):
> it is a bit sad that 5 years had passed and those issues still persist

**Riyue Sunny Bao** (14:17:08):
> from my experience, I have not seen a proper career structure for bioinformaticians

**Riyue Sunny Bao** (14:17:23):
> while in industry it is set very well

**Aedin Culhane** (14:18:22) (in thread):
> Actually the ODSC CEO Sheamus Mcgovern has a really good talk (I posted on twitter) on this recently..  He said how almost all industries screen CVs using automated systems and how “words” matter…

**Aedin Culhane** (14:18:45) (in thread):
> Agree…..

**Vivek Das** (14:19:15):
> But I see there are some new data science initiatives from NIH and other organizations across EU for data science, CS, methods, etc in Biology. Then CZI Science initiatives. I think these initiatives are for the good. Only time will tell but I take them as positive direction for funds and new positions.

**Simina Boca** (14:19:47):
> I think a lot of people in academia value it

**Simina Boca** (14:19:57):
> But clearly not enough to have more hard-money positions, for example

**Simina Boca** (14:20:31):
> So it sometimes feels a little hollow

**Riyue Sunny Bao** (14:20:31):
> I really like the CZi initiatives to fund sustainable bioinformatics software

**Riyue Sunny Bao** (14:20:37):
> they are doing a good job there

**Aedin Culhane** (14:20:39):
> So how can this article advance the field so these issues are not the same issues in 10 years again. So the question is you can change a culture? Is the culture changing? how?
> * Many degrees in bioinformatics/comp bio are available but fewer bioinformatics departments exist in academic, or medical schools, mostly bioinformatics faculty are dispersed in clinical/biological and math/stat/epidemiology/CS dept. I have never work in a “bioinformatics” department in academic or an academic hospital, I have worked in Biochemistry, Neuroscience, Computer Science, Biostatistics, and Data Science departments.  Is the lack of an departmental “home” limiting career development?   Does Bioinformatics just rename itself.. so its has a home?

**Aedin Culhane** (14:21:13):
> What “Rules” can help advance career recognition and development?
> * Can bioinformatics faculty or those in senior positions in academic or institutes create within/between dept/institute “centers” of bioinformatics that span departments are created to foster inter-group collaborations in bioinformatics
> * Communication is fundamental to support
> * Senior and junior faculty, staff responsibility to mentor and support junior faculty, postdocs and students
> * Provide access to seminar/webinar/conferences for learning/training
> * Provide slack or email lists that enable bioinformatics that are lonely in labs
> * Finally hierarchically structure in research may introduce intellectual bias. Typically older disciplines have “card-carrying” intellectual bias… eg card carrying immunologist/statistician/mathematician, ’ologies v ’omits  etc etc

**Riyue Sunny Bao** (14:21:30):
> I have seen bioinformatics faculties embedded in CS, health informatics, biomedical informatics, engineering, and biostatistics

**Riyue Sunny Bao** (14:21:35):
> but rarely a bioinformatics department alone

**Riyue Sunny Bao** (14:21:40):
> 'I am not sure the reason:thinking_face:

**Brice Sarver** (14:22:02):
> @Stephany OrjuelaI'd say it aligns with what I wanted to do. At the start of my postdoc, I started looking seriously into all options, and I was really impressed by what I was hearing about industry. Much of it was completely opposite of what I had been told by professors. I asked around more, eventually joined a company as opposed to a tenure-track position, and I've been consistently impressed with the quality of the science, structure, and fast pace. I find government to be some sort of hybrid between the two - things move more slowly than industry, but without the non-scientific time-consuming requirements of academia. Also pay/benefits: industry >>> government > academia

**Riyue Sunny Bao** (14:22:15):
> Another big issue might be that funding agency tend to fund bioinformatics as part of a big grant

**Riyue Sunny Bao** (14:22:15):
> rather than its own grant

**Riyue Sunny Bao** (14:23:15):
> I have seen "Centers" being created for computational medicine, though  the director is not bioinformatician

**Aedin Culhane** (14:25:04):
> Yes@Susan Holmesand I had a discussion of this. Computational genomics is seen as a subset of lab work, not as an independent field.  The ITCR is good but it funds software tools, not necessarily computational research and science

**Riyue Sunny Bao** (14:25:12):
> I wonder, is that because funding agency values more about "generating" the data, rather than "methodology" to analyez the data?

**Aedin Culhane** (14:25:44):
> The CZI is supporting computational research.

**Simina Boca** (14:25:58):
> In terms of publications, which was another question that was posed

**Aedin Culhane** (14:26:18):
> Honestly I think the lack of an academic home is a big problem,, the field is seen as ancillary

**Riyue Sunny Bao** (14:26:28):
> yes, they support software development which is essential
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596133544131900)
    > The CZI is supporting computational research.

**Vivek Das** (14:26:55) (in thread):
> This is an important point.

**Aedin Culhane** (14:26:57):
> In terms of 10 simple rules… they the rules might be to foster “being seen” to build career structure

**Simina Boca** (14:27:05):
> I posted this a while ago: comments I got on an NIH review[https://twitter.com/siminaboca/status/1285220800686108676/photo/1](https://twitter.com/siminaboca/status/1285220800686108676/photo/1)
  - Attachment (twitter): [Attachment](https://twitter.com/siminaboca/status/1285220800686108676/photo/1)
    > [@loyalgoff](https://twitter.com/loyalgoff) I'm having a super hard time with the "Investigator" section as well. Not even sure what I'm supposed to do with something like this. It seems very hard to win unless you fit the exact mold the reviewers have in mind. [https://pbs.twimg.com/media/EdYFEIXXgAAWVDw.png](https://pbs.twimg.com/media/EdYFEIXXgAAWVDw.png)

**Simina Boca** (14:27:33):
> Basically even if things are papers if they're not the kind of papers in the kind of journals the people evaluating you are used to seeing...

**Simina Boca** (14:27:36):
> It can be a hard sell

**Aedin Culhane** (14:28:00):
> Actually if you look at the most cited papers ever, many are computational tools so impact of comp bio is high…

**Riyue Sunny Bao** (14:28:01):
> yes!  this might also tie to@Simina Bocacomment about publications
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596133617135000)
    > In terms of 10 simple rules… they the rules might be to foster “being seen” to build career structure

**Riyue Sunny Bao** (14:28:57):
> would this be improved if we can have more bioinformatics/computational bio people on the study sections?
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596133653136000)
    > Basically even if things are papers if they're not the kind of papers in the kind of journals the people evaluating you are used to seeing...

**Vivek Das** (14:28:59):
> TCGA papers.

**Aedin Culhane** (14:29:08):
> 10 simple rules to enhance communcaition/collaboration between bioinf faculty/research/students that are dispersed throughout the academic dept/medical schools/labs

**Vivek Das** (14:29:08):
> Consortium ones mostly.

**Riyue Sunny Bao** (14:29:18):
> exactly!!!!
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596133680136800)
    > Actually if you look at the most cited papers ever, many are computational tools so impact of comp bio is high…

**Vivek Das** (14:29:42):
> I totally agree with@Aedin Culhane. It has to be diverse.

**Vivek Das** (14:30:42):
> More of a guideline document for future students and students in the field to make educated career choices. Doesn’t have to be narrow.

**Aedin Culhane** (14:31:12):
> Within any hospital/Univ there are a lot of bioinformatics folks, but they are dispersed.  So its how to build infrastructure and rules to help them leverage that community to help each other , to mentor, amplify each other and develop career structure and “rules” to build each other up

*14:31:33 - @Charlie George has joined the channel*
**Aedin Culhane** (14:31:55):
> Bioc is a great example.. the slack community, engagment of people globally etc

**Riyue Sunny Bao** (14:32:13):
> in our institution we have been trying to get folks to join our slack channel, might be a start ....

**Aedin Culhane** (14:32:38):
> People need to get something from it .. help

**Shila Ghazanfar** (14:35:36):
> Something that’s changed in the last 5-10 years technology-wise@Aedin Culhaneis the increased ability to build interactive data tools - empowering you as a analyst/researcher as well as collaborators to interrogate data more effectively. I definitely think the most effective apps/dashboards you create are the ones you use yourself:smile:iSEE is a prime example of this!
> 
> A “rule” for more thriving bioinformatics research, especially in an embedded lab environment, is to promote statistical and data literacy for all in the lab. this is great for the more biology-person to get more familiar with the data, build an appreciation for what the analyses entail, and for the bioinformatics researcher to delve into intriguing analytical questions + methodological avenues

**Riyue Sunny Bao** (14:39:33):
> To build such a community, several ways we can do it, e.g. through training, workshops, online seminars, classes, and journal clubs. The challenge I saw from the past was that organizers volunteer their time and commitment for those events, but they were not accounted for academia development, there are strict rules of which to be counted, e.g. classes need to have a class ID assigned from school where students can take credits. Also teaching a workshop is listed towards academia contribution, but not as much as papers, grants, and invited talks. In the long time, those events eventually died off. At least that was my experience.

**Aedin Culhane** (14:40:02):
> True, but we can’t expect biology folks to learn bioinformatics or just like no one would expect them to learn statistics.

**Charlotte Soneson** (14:40:14):
> @Shila GhazanfarI agree with this. Also tools like Galaxy can be very useful for allowing more people to perform (some parts of) data analysis and exploration.

**Riyue Sunny Bao** (14:40:33):
> that is a very important point:thinking_face:
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596134402156200)
    > True, but we can’t expect biology folks to learn bioinformatics or just like no one would expect them to learn statistics.

**Vivek Das** (14:40:57):
> It’s about appreciation for each other’s skills and contribution. Science for me is a team work.

**Riyue Sunny Bao** (14:41:03):
> Yerp

**Shila Ghazanfar** (14:41:07):
> A couple potential dangers though: bioinformatics researcher could end up being placed into a ‘teacher’ role for others - this should be actively avoided ( prefer pointing to resources:white_check_mark:).
> 
> and second danger is if some analysis requires a lot more nuance than within capabilities of someone less experienced, this is a danger but i think so long as there is appreciation for how nontrivial bioinformatics research is, then it would be good:thumbsup:

**Vivek Das** (14:41:13):
> Current state is beyond just wet biology.

**Simina Boca** (14:41:37) (in thread):
> It's also hard b/c technically a lot of this is "volunteer work" while trying to get grants/papers etc out to actually get paid.

**Simina Boca** (14:42:28) (in thread):
> I know there are educational and training grants, so of course it depends/YMMV. I do find that the lack of "hard money" positions in bioinformatics may make these things harder.

**Aedin Culhane** (14:42:29):
> Saying biologists should all learn bioinformatics feeds into the ancillary myth. Whilst you might expect a biology to do a t-test, you don’t expect them to do a linear model.  Equally biologists should know basic bioinformatics but can all learn unix/R/python do WGS alignment and analysis

**Riyue Sunny Bao** (14:43:10):
> that was what I have seen as well
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596134548163200?thread_ts=1596134373155500&cid=C017GBE6SCX)
    > I know there are educational and training grants, so of course it depends/YMMV. I do find that the lack of "hard money" positions in bioinformatics may make these things harder.

**Vivek Das** (14:43:44):
> As long as a wet Biology doesn’t see Bioinformatics/statistical computing/data science/data analysis as pushing buttons, it helps. On a similar note quantitative biology (Bioinformatics/DS/DA/Stats/CS, etc) folks should not expect wet biologists to be data generation folks. It’s all about synergy that makes up great and innovative science.

**Aedin Culhane** (14:44:39):
> Good point.. hard money is vital and not available without an academic home…

**Riyue Sunny Bao** (14:44:59):
> In a collaboration where everybody respects each other's expertise and learn from each other (but not replacing) would be the best

**Aedin Culhane** (14:45:22):
> The current trend I’ve seen is expecting all bioinformatics folks to have their own wet lab

**Riyue Sunny Bao** (14:45:45):
> I have seen that too especially for big labs

**Vivek Das** (14:45:55) (in thread):
> This is unfortunate .

**Riyue Sunny Bao** (14:45:55):
> they hire 1 bioinformatician to support every project ...

**Riyue Sunny Bao** (14:46:13):
> and bioinformatician ends up doing a lot of fragmental work and not leading her/his own project, that is dangerous for career

**Vivek Das** (14:46:51) (in thread):
> Not all collaborators. Some still come in the end thinking it’s push button science. Few cases are there.:rolling_on_the_floor_laughing::grimacing:

**Riyue Sunny Bao** (14:47:08):
> agreed:grimacing:

**Aedin Culhane** (14:48:01):
> So the question is how have these since Mick Watson wrote his blog in early microarray days…  today genomics data is way way more complicated both in scale and in terms of multi’ omic integration and computational and biological complexity

**Aedin Culhane** (14:48:06):
> Listening to shirley

**Riyue Sunny Bao** (14:48:21):
> yeah on the channel too

**Aedin Culhane** (14:48:33):
> her talks is integration complex biology, computational too and advancing science

**Vivek Das** (14:48:40):
> I have learned to set expectations of turnaround from apriori that things will take time and get delayed when there is a lot of EDA involved.

**Aedin Culhane** (14:49:03):
> But she has great collaborations with wet lab science (esp myles brown lab) which was essential for her group development

**Riyue Sunny Bao** (14:49:19):
> I think her lab has both dry and web lab components, and she has fostered a long term relationship with oncologsits to share samples with her

**Riyue Sunny Bao** (14:49:23):
> for lots of translational research

**Riyue Sunny Bao** (14:49:37):
> her lab is a really encouraging successful case

**Riyue Sunny Bao** (14:50:34):
> I have been trying the rule of estimating x days then move the unit up
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596134920177600)
    > I have learned to set expectations of turnaround from apriori that things will take time and get delayed when there is a lot of EDA involved.

**Nur-Taz Rahman** (14:53:24) (in thread):
> This is crucial for managing time and stress, specially when involved in multiple projects

**Vivek Das** (14:55:16):
> It’s not easy. Not all projects I would say. It entirely depends on goals, projects, departments, roles, etc. for me this is important given the kind of work I do plus I am also involved with multiple curiosity driven research gigs outside of my job. They are some collaborations I do for fun and knowledge with collaborations around the world without funds and compensation. But yes, I get a name in the paper. Can’t lose on that if I contribute.:wink:

**Riyue Sunny Bao** (14:56:48) (in thread):
> in the meantime you have to fight the stereotype of "bioinformatics == pushing buttons" ....

**Vivek Das** (14:57:39):
> But through those I am also mentoring and training students in developing countries. But I try to keep it as much transparent as I can for them to realize there are pros and cons to everything. For me, I try to see if I can make them passionate and curious but they should not feel obligated to do science.

**Nur-Taz Rahman** (14:58:09) (in thread):
> oh yeah, you just hit "enter" and everything happens . . .:stuck_out_tongue_closed_eyes:

**Vivek Das** (14:58:41) (in thread):
> @Riyue Sunny Baofolks who are familiar with me, know that already. In reference “pushing buttons”:grimacing::wink:

**Riyue Sunny Bao** (14:59:23) (in thread):
> one thing I never understood was that why nobody thoughts "biostatistics == push buttons":thinking_face:

**Shila Ghazanfar** (14:59:28):
> i think increased data and statistical literacy in general is a good thing. whether this fits into a category of a “must” or a “would be nice” for all in a lab (esp wet-lab biologist) is a different question, and will vary from lab-to-lab. I would argue that in the presence of colleagues/collaborators who have higher level of data and statistical literacy, a bioinformatics researcher would benefit, compared to not. To be more specific, im talking about e.g. generating a volcano plot from a csv file, subsetting a table using various rules (things i have performed in the past), which are more in the ‘data literacy’ component

**Riyue Sunny Bao** (14:59:47) (in thread):
> is it because biostatistics is a discipline of longer history?

**Nur-Taz Rahman** (15:00:19) (in thread):
> Very good question . . . and probably . . . ?

**Vivek Das** (15:01:26):
> I agree@Shila Ghazanfar, literacy is important specially if someone is interested or hell bent on quicker results. It helps to clarify expectations.

**Aedin Culhane** (15:04:37) (in thread):
> Biostatistics are seen, they are required in NIH grants. A statistical section is required in every grant. Researchers have to respect biostats folks. They then expect a %FTE on every grant.  I have reviewed grants that will generate tons of data and they include zero FTE for a bioinformatics person

**Aedin Culhane** (15:05:24) (in thread):
> But when I bring this up in the grant review, frequently someone (a clinician almost always)  will point to the biostatistics person who did the power test and say they have stats support

**Riyue Sunny Bao** (15:06:12) (in thread):
> Yes, I bring this up every time too when I spot that

**Aedin Culhane** (15:06:14) (in thread):
> Folks dont’ realize the tools to perform integrate Hi-C and RNAseq data may not be the same as those to analyze a clinical trial. Bioinfo folks are not seen

**Riyue Sunny Bao** (15:06:55) (in thread):
> how can we make changes happen?:thinking_face:

**Vivek Das** (15:07:51) (in thread):
> This will take time. I hope this changes. I am hopeful. But need more voices plus support from clinician or medical community. It’s all about FTE.

**Riyue Sunny Bao** (15:07:56) (in thread):
> NCI now requires every big grant to have support from a bioinformatics core, however I have yet to see if that increases the visibility of bioinformaticians

**Riyue Sunny Bao** (15:08:31) (in thread):
> Let's say, I have seen more clinicians who want to learn bioinformatics than the ones who are willing to fund bioinformaticians to do their work

**Riyue Sunny Bao** (15:09:03) (in thread):
> but I have not met with any clinicians who say they want to learn biostatistics

**Aedin Culhane** (15:09:33) (in thread):
> I think bioinfo folks need to be “seen”.  I attended a AACR conference two years ago in Newport entitled “ARTIFICIAL INTELLIGENCE, BIG DATA, AND PREDICTION IN CANCER” in 2018.. almost all the presenters were clinicans

**Aedin Culhane** (15:09:42) (in thread):
> Most had no clue about the algorithms

**Aedin Culhane** (15:09:53) (in thread):
> One actually mentioned “pressing buttons”

**Vivek Das** (15:09:54) (in thread):
> This can be good or even bad. One cannot learn overnight. If it’s for data literacy@Shila Ghazanfarmentioned, that’s understandable but if it’s for FTE, then I am afraid that’s not a great collaborator.

**Riyue Sunny Bao** (15:10:54) (in thread):
> @Aedin Culhaneto be honest, I frow everytime when I see a clinician presenting machine learning work who clearly has no clue how the analysis was done'

**Aedin Culhane** (15:11:08) (in thread):
> When a person asked about a ML tool, the person got the answer “oh it was just a standard one, I expect another one would work too”. They didn’t even know they had run a GAN

**Riyue Sunny Bao** (15:11:25) (in thread):
> did they even mention a bioinformatics person did that?

**Vivek Das** (15:11:27) (in thread):
> Bioinformatics folks need to be in applied side of conferences. Yes I totally agree@Aedin Culhane. I have been in some and tried to voice up. But it’s not always easy. But yes, I have also received positive feedbacks based on things I presented there.

**Aedin Culhane** (15:11:46) (in thread):
> No person of the bioinfo folks in a lot of cases.. it was seen as a service

**Aedin Culhane** (15:12:08) (in thread):
> Just like doing a power test

**Riyue Sunny Bao** (15:12:37) (in thread):
> that was horrible!

**Aedin Culhane** (15:12:43) (in thread):
> Myself and a few of other other comp folks there were incredibly frustrated. We learned nothing

**Riyue Sunny Bao** (15:12:47) (in thread):
> @Vivek Das

**Riyue Sunny Bao** (15:13:14) (in thread):
> on your point yes bioinformatics folks need to present more but usually those "applied" studies would not invite us to present

**Vivek Das** (15:13:19) (in thread):
> I have mention this earlier. Service is great but there is a lot of science. It’s just not services. It’s applied science.

**Riyue Sunny Bao** (15:13:25) (in thread):
> biologists or clinicaisn are the 1st author of the paper

**Riyue Sunny Bao** (15:13:33) (in thread):
> they are invited to present

**Aedin Culhane** (15:13:54) (in thread):
> (see the stats folks are cleaver they never provided Biologists tools to do their own power tests.. they say only a trained person can do it.. you need to rely on us and respect us)

**Riyue Sunny Bao** (15:14:10) (in thread):
> I think we might have to do the same

**Vivek Das** (15:14:49) (in thread):
> @Riyue Sunny Bao. I know it is not easy. It also depends that a Bioinformatics person needs support from someone up the hierarchy or at least present a case why that person is needed to be in that conference.

**Riyue Sunny Bao** (15:15:47) (in thread):
> @Vivek Das

**Riyue Sunny Bao** (15:15:50) (in thread):
> very good point

**Sidharth Sen** (15:16:10):
> I would also like to add in my 2cents here - I am bioinfo phd candidate, working in a bioinfo lab. We do a lot of "service" projects, but always add an element of innovation/method learning, etc - by proposing the use of some new method or analysis which we want to explore.

**Vivek Das** (15:16:40) (in thread):
> Bioinformatics tool creation is great but folks who created it should not be marginalized. Service is great but that service is data science or data analysis that entails loads of EDA. This narrative needs to be changed. Hopefully with time it will with more open source tools and knowledge that biology now is totally interdisciplinary.

**Riyue Sunny Bao** (15:16:50) (in thread):
> @Aedin CulhaneI have been  there too. I even had one person who came to me and told me they never used their analysis and removed me from the paper

**Riyue Sunny Bao** (15:17:14) (in thread):
> meanwhile I had the email from their graduate student saying how much my analysis helped them to pick the target for experiment

**Riyue Sunny Bao** (15:17:28) (in thread):
> did not fight that battle tho

**Aedin Culhane** (15:18:25) (in thread):
> Hey then you have the NEJM editorial about data parasite, where they were asking to be authors in every paper in which the data are used. That like us asking to be an author on every paper where our packages are used

**Vivek Das** (15:19:21) (in thread):
> Sorry to hear that@Riyue Sunny Bao. I understand some battles are worth not fighting.

**Riyue Sunny Bao** (15:19:50) (in thread):
> is the paper still out there or it was radacted?

**Riyue Sunny Bao** (15:20:45) (in thread):
> I was wrong.  the paper is still there

**Sidharth Sen** (15:20:51):
> This way we keep an air of innovation added onto the service side and usually those add on extra analysis gives us first author papers

**Aedin Culhane** (15:21:12) (in thread):
> I think we have all had collaboration in which our contribution was not recognized, I always point out.. where how would you feel if I walked into the lab and expected you to run 100 PCR assays immediately… that the same as .. oh just redo this figure to include xyz

**Aedin Culhane** (15:22:10) (in thread):
> But lets get back to the “Rules”,… how can we make lemonade out of lemons

**Riyue Sunny Bao** (15:22:27) (in thread):
> yup, I never had a good solution for that, it is like you are the middle author but you have to do all the work that 1st author is supposed to do

**Riyue Sunny Bao** (15:23:17) (in thread):
> I really feel there has to be change from the root, from NIH and institution. Otherwise nothing would change.

**Aedin Culhane** (15:23:38) (in thread):
> I have definitely had 1st author arguments, have you a senior faculty to back you up… That where a network of bioinf folks in a Univ can help.. like a union its a supportive tool

**Riyue Sunny Bao** (15:23:42) (in thread):
> NIH needs to fund bioinformatics as a seperate thing not as part of U grant. Allow bioinformaticians as the lead on data grants and not MDs.

**Aedin Culhane** (15:24:41) (in thread):
> Agree,  MDs have a ton of power in all clinical facilities. Most successful bioinfo folks have a powerful MD working with them

**Aedin Culhane** (15:25:03) (in thread):
> But with medical schools, bio PhDs  have the same problem.. MDs rule

**Riyue Sunny Bao** (15:25:24) (in thread):
> I am in Department of Med with PhD agree. tell me about it:sweat_smile:

**Riyue Sunny Bao** (15:26:36) (in thread):
> back to the rules ... as change needs to happen in NIH and at institution, perhaps the 1st step is to get bioinformatics folks into leadership positions?

**Riyue Sunny Bao** (15:26:38) (in thread):
> :thinking_face:

**Riyue Sunny Bao** (15:27:09) (in thread):
> everything always roots back to funding.

**Aedin Culhane** (15:30:06) (in thread):
> Funding and journals

**Aedin Culhane** (15:30:32) (in thread):
> I think EU might be a bit better than US on funding compbio

**Aedin Culhane** (15:30:38) (in thread):
> NIH is more old school

**Riyue Sunny Bao** (15:32:53) (in thread):
> for EU, I also heard from junior investigators that it is very hard to get credits, as they have such funding structure as one "king" controls all the funds and is senior author on every papers

**Riyue Sunny Bao** (15:32:59) (in thread):
> I have never been there so those are just words

**Vivek Das** (15:33:08) (in thread):
> The responses here are in a sub thread. I would request all to be in the main channel so that it helps everyone to be a part of discussion and eventually a guideline document.:blush:

**Riyue Sunny Bao** (15:33:14) (in thread):
> that was one of the reasons why EU investigators came to the US to develop their own lab

**Riyue Sunny Bao** (15:33:35) (in thread):
> ohh how do we make it a main channel:joy:

**Erick Cuevas** (15:37:09):
> As a "novice" bioinformatician, I would say that the rules that I have seen in those people who have the skills that I would like to have are:
> -Math skills, so learn solid math.
> -Know the biological / experimental bases to have the expertise to analyze results
> -Summarize results in a stylish way, make smart charts
> -Generate interactions with experts on all possible topics
> -Never stop learning

**Vivek Das** (15:40:32):
> Great points@Erick Cuevas

**Simina Boca** (15:53:32):
> I think being willing to read up on the specific scientific topic and to write is also super important

**Simina Boca** (15:53:53):
> Roger Peng would always say that whoever writes the first draft has a lot of power

**Simina Boca** (15:54:01):
> Much harder to change stuff after that first draft

**Simina Boca** (15:54:28):
> We have to be involved with that, not say "my part is done, leave me alone"

**Simina Boca** (15:54:45):
> (No one here but I know Biostat/bioinfo people who do that)

**Federico Marini** (15:56:42) (in thread):
> With quality = impact factor or what?

**Matthew McCall** (16:02:29):
> Great points@Simina Boca. Write the first draft of the paper, put your name on the author line, and ask others to add their names as they edit. 9/10 you’ll still be 1st author once all the names are added.

**Simina Boca** (16:03:32):
> And it makes us look less like "button-pushers"

**Simina Boca** (16:03:47) (in thread):
> :shrug:I assume so?

**Vivek Das** (16:04:55):
> Yes, great points@Simina Boca. For core this isn’t always possible . But I guess there is a way to make core agreements where services and/or authorship is well clarified.

**Federico Marini** (16:04:56) (in thread):
> as sad as it is, huh.

**Federico Marini** (16:05:23) (in thread):
> the 2 comments are so colliding against each other

**Matthew McCall** (16:05:36):
> The consulting contract we use in my dept spells out terms for authorship.

**Vivek Das** (16:05:39):
> I have read about folks not being in paper, despite contributing more than required service. This is a slippery slope.

**Matthew McCall** (16:06:03):
> I do think it’s important to distinguish between consulting and collaboration, though.

**Vivek Das** (16:06:06):
> Key is to have a good contract in place.

**Federico Marini** (16:06:13) (in thread):
> Come on: you covered them all***but in low IF?***

**Vivek Das** (16:06:19):
> Agree@Matthew McCall

**Vivek Das** (16:06:52):
> But even on consulting, expectations need to be clarified well.

**Simina Boca** (16:07:18) (in thread):
> I mean clearly they didn't like the grant. But like, if you're not excited about the idea, don't come up with random pointless criticism.

**Federico Marini** (16:32:41) (in thread):
> I fear we could go on and on… but you’re just 100% right

**Davide Risso** (16:33:07):
> The comment by@Aedin Culhaneon the lack of bioinformatics depts really resonated with me. I do believe that it hurts our careers. In Italy for instance most bioinformaticians are in biology depts and get evaluated by tenure committees that might think only last author in glam journals is tenure worthy... similar with us in stats depts where the expectations are 2 author papers in stats journals

**Riyue Sunny Bao** (16:33:49):
> I think it stems from very root issues about where the funds come from

**Riyue Sunny Bao** (16:34:19):
> I have no doubt there are a lot of talents that can be developed into a bioinformatics department

**Davide Risso** (16:34:24):
> If you’re lucky the committee is made of people that know the field and that helps you but there are no guarantees...

**Riyue Sunny Bao** (16:34:59):
> but the decision makers are usually not bioinformaticians and do not understand that bioinformatics is a discipline

**Riyue Sunny Bao** (16:35:05):
> same as the issue with committee members

**Riyue Sunny Bao** (16:36:16):
> it might take a generation to shift the culture

**Vivek Das** (16:39:20):
> @Davide RissoI am totally familiar with this. I did my PhD from Italy. I can totally see that. It’s pretty tough and vary across countries, universities and departments.

**Vivek Das** (16:41:50):
> That’s why it’s important to have folks in the system who understands the scope of Bioinformatics or Genomics well and that it needs to co-exist with experimental projects. Biology is beyond just running experiments now given data modality and dimension is so high. Lot relies on infrastructure, methods, analysis, etc. So equal weightage is needed while committee evaluation.

**Sidharth Sen** (16:41:53):
> on that note -  how many of you usually are consulted before starting a project? - as in when writing a grant application or proposing a new project?

**Vivek Das** (16:42:36):
> I do get consulted but not for all projects.

**Sidharth Sen** (16:44:00):
> @Vivek Daskind of strange - all the projects I am working on - has my PhD advisor as a co-PI and dedicated bioinfo sections in the grant proposals

**Vivek Das** (16:44:23):
> Collaborations is not always at inception. So I am not always involved in design. In some I am in some I am not. But not all projects were poorly designed where I have been involved. Some definitely were that my results showed them. I didn’t get a publication on those. But that’s fine.:rolling_on_the_floor_laughing:

**Vivek Das** (16:45:46):
> @Sidharth Sen, I am not working for a PI. I am in the industry where I am involved in multiple consortium. Collaborations doesn’t start with me. I joined some once Data was generated and some i imitated. It’s not always like that.

**Vivek Das** (16:46:45):
> Also can you clarify what you find strange here? In drug discovery projects things might be different since we have clinical folks involved.

**Sidharth Sen** (16:49:36):
> ah - I don't do drug discovery stuff - mostly omics data integration and that too mostly on plant data. Essentially gene expression and all allied annotation stuff - mostly preliminary exploration and biomarker discovery.

**Vivek Das** (16:49:36):
> I wanted to clarify something. Any sequencing related project involves me as a grant member. If that was the query specially if it started after I joined as I am the POC

**Vivek Das** (16:50:01):
> And I do write those grants as well.

**Sidharth Sen** (16:50:11):
> so maybe that also makes a difference? the sort of people we are all associated with?

**Vivek Das** (16:50:30):
> Either as a co-lead , single lead or within a team.

**Vivek Das** (16:50:37):
> Varies between projects.

**Vivek Das** (16:50:49):
> Definitely. It makes a difference

**Vivek Das** (16:51:25):
> It’s about the group we work with and how much they are aware of Bioinformatics. But we also need to educate them. We can’t expect everyone to know it all.

**Sidharth Sen** (16:51:27):
> I personally work with a lot of maize and plant data - my colleagues and all have a healthy appreciation for bioinfo people and tend to consult them a lot - even as to far as making changes during a project guided by the results we generate...

**Vivek Das** (16:51:56):
> That’s great@Sidharth Senbut it’s not universal.

**Sidharth Sen** (16:52:43):
> I agree - the sentiment shared by everyone here seems to be the norm. My experience seems to be on the fringe

**Vivek Das** (16:54:26):
> It’s great to have all who are having great experience. We need every experience. I guess the scenario will be important once you graduate. I guess these opinions will help you with decision making and be conscious when you are out in job market for post doc or beyond.

**Riyue Sunny Bao** (16:54:48):
> this would take some time to improve the awareness, but after a while they mostly consult me first during sample collection phase or earlier (grant phase)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596141713262700)
    > on that note -  how many of you usually are consulted before starting a project? - as in when writing a grant application or proposing a new project?

**Riyue Sunny Bao** (16:56:29):
> I run a core and also have a joint lab with my collabrator

**Riyue Sunny Bao** (16:56:39):
> so the business is bit different

**Vivek Das** (16:56:41):
> Also@Sidharth Sen, the fun, challenge & pain starts sometime in late graduate school when program ending nears and mostly when one is in the new job market as ECR.

**Riyue Sunny Bao** (16:57:11):
> one thing I always wonder, how does the covid situation has affected bioinformatics job market?:thinking_face:

**Vivek Das** (16:57:19):
> But that doesn’t mean the entire field is problematic.

**Riyue Sunny Bao** (16:57:20):
> I can see if affects experimental jobs

**Vivek Das** (16:57:29):
> It’s about being aware.

**Riyue Sunny Bao** (16:57:37):
> but how about bioinformatics jobs? assuming remote working is allowed.

**Vivek Das** (16:58:21) (in thread):
> I am involved in an opinion article. Let’s see when it sees the light to answer this. That’s another discussion:rolling_on_the_floor_laughing:

**Sidharth Sen** (16:58:41):
> @Riyue Sunny Baoas someone who is looking at jobs now - the market seems the same - same amount of new jobs being posted online as a year back or so

**Riyue Sunny Bao** (16:58:43):
> agreed improving the awareness is important. most PIs are pretty open to include bioinformaticians as authors sometimes they just did not think about it, but if you bring it up they will.
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596142649290100)
    > It’s about being aware.

**Vivek Das** (16:59:00):
> I would always advice to network the hell out of any conference. It helps a lot for future positions.

**Vivek Das** (16:59:51):
> Novo Nordisk jobs are posted in job boards. Just saying .:wink:

**Riyue Sunny Bao** (17:01:15):
> I would encourage this as well. also helps to have someone to introduce you to their circles.
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1596142740293700)
    > I would always advice to network the hell out of any conference. It helps a lot for future positions.

**Vivek Das** (17:01:20):
> But, I haven’t seen a huge drop in Bioinformatics industry positions. Can’t say much of academic one.

**Aedin Culhane** (17:41:30):
> Anyone want to hang out/chat.  Pop into[https://meet.bioconductor.org/yEoLukjsyI](https://meet.bioconductor.org/yEoLukjsyI)
  - Attachment (meet.bioconductor.org): [Jitsi Meet](https://meet.bioconductor.org/yEoLukjsyI)
    > Join a WebRTC video conference powered by the Jitsi Videobridge

**Riyue Sunny Bao** (22:30:00) (in thread):
> Thanks Sara!! I will keep you in the loop.


## 2020-07-31

**Federico Marini** (03:31:34) (in thread):
> I missed some part of that as I was on the way back home - maybe we can try to involve her in this effort as well@Aedin Culhane?

*04:20:26 - @Francesca Finotello has joined the channel*
**USLACKBOT** (07:07:45):
> ***GeneLab***has joined this channel by invitation from***community-bioc***.

*07:07:45 - @UTRUSRTGR has joined the channel*
**USLACKBOT** (08:33:05):
> @Federico Mariniremoved***GeneLab***from this channel.

*09:18:18 - @Kevin Rue-Albrecht has joined the channel*
*09:30:34 - @Anke Busch has joined the channel*
**Jenny Drnevich** (09:57:29):
> I missed all the good discussions yesterday. Re: Authorship. I work for a core and even though we get paid for the analysis our terms state that they should at least acknowledge us and if we make substantial contributions, we should be included as authors. If they want me to write the methods and then respond to reviewer comments, I'd better be an author!

**Jenny Drnevich** (10:01:12):
> And we have had both cases: an analyst has done most of the work but was not included in the final author list, and someone sending me a manuscript out of the blue with my name on it saying "we just got accepted to journal XXX"

*10:07:15 - @Pedro Madrigal has joined the channel*
**Vivek Das** (10:32:34):
> Seems like a great contract agreement in place@Jenny Drnevich. Sorry for the times where the group didn’t make it to the paper. But still it seems that the agreement somewhat safeguards intellectual contributions. Indeed this needs to be translated in more core facility.

**Jenny Drnevich** (10:36:20):
> Yes,@Vivek DasWe wrote ours after an informal survey of other cores' contract terms. That was ~6 years ago so it would be interesting to see how many have them now. It is easier for a core - I imagine it is much harder for an individual bioinformatician.

**Pedro Madrigal** (10:36:33):
> I am joining late, but here are my two cents after few years in academia (engineering background, PhD in dry lab, 2 post-doc in wet-labs): I understand 'thriving' as successful career progression. Of course this has a different meaning for different people. But let's consider for a while the traditional academic path (PhD -> Postdoc/s -> PI). To win fellowships, grants, and TT assist./assoc. prof positions one INEVITABLY needs compelling first author papers (preferably in flashy journals). Bioinformatics postdocs working on multiple collaborative projects are at a disadvantage when compared to wet-lab postdocs spending full efforts pursuing a project (aka: Donald's project in Kate's lab). There is a handicap there - no one will give acknowledge authorship (if deserved) unless the computational phd/postdoc  or his/her PI start the conversation (a group leader in Cambridge recently admitted that “credit goes to the data generator"). This is even worse for Core facility members that might work in completely different topics (looks bad for grant/fellowship reviewers as you look 'unfocused’). Highly-skilled technicians/helpers will not get tenure. If you add in top of that, that postdoc salaries in academia are not great when compared to industry, where computational skills are most wanted, then you have come to the perfect storm, which some PIs just translate into the sentence "It is so difficult to find a good bioinformatician!”, instead of actually doing something to retain talent.

**Davide Risso** (10:39:18) (in thread):
> Can I say that the second example bothers me as much (ok maybe not as much) as the first one? If I’m an author I need to be involved since first submission. Emailing a co-author after the paper is accepted is NOT ok.

**Jenny Drnevich** (10:41:27):
> Yes,@Davide Risso! It has happened to me maybe 3 times. Each time I was temped to complain to the journal but as I didn't disagree with the papers I just left it alone. Free pub with no extra work on my part.

**Jenny Drnevich** (10:42:08):
> (obviously they were not journals that required each author to sign off on it)

**Davide Risso** (10:42:45):
> This in my experience happens a lot with MDs.. I think in their mind they just think there’s no need to bother you, but still

**Jenny Drnevich** (10:43:11):
> I did tell each PI that I need to see drafts of manuscripts before submission in the future.

**Davide Risso** (10:44:38):
> At least they told you at the acceptance stage. I know of an example of someone finding out from google scholar that they published a paper...:joy:/:sob:

**Pedro Madrigal** (10:46:24):
> You have also a slightly different version: after few years you get the draft, which MUST be submitted Imminently so you can only propose cosmetic changes. Some data analyses are flawed. What do you do?

**Vivek Das** (10:47:08):
> I like the expression@Davide Risso. It can be amazing or lead to sadness as well given the content of the paper and problem addressed in it.:grimacing:

**Vivek Das** (10:48:33):
> Thats why I mentioned, can lead to sadness@Pedro Madrigal:man-shrugging:

**Vivek Das** (10:48:43):
> It’s kinda slippery slope.

**Jenny Drnevich** (10:48:57):
> @Pedro Madrigaldemand changes. I've had been in a similar situation and I've just laid out how as I reviewer I would fault A, B and C. Of course, that led to me having to do quite a bit of re-analysis/writing in a short period of time

**Vivek Das** (10:50:34):
> @Jenny Drnevichdid this re-analysis/writing happen after publication or during the process? I mean if accepted and published already, and then one of the co-author finds out the issue in analysis, what is the best possible way then?

**Jenny Drnevich** (10:51:37):
> Things we do not charge for at my core: experimental design help, grant proposals, time writing an authored manuscript. Luckily we are supplemented by our University so we can spend time on these.

**Jenny Drnevich** (10:56:12):
> @Vivek DasI have not been in that situation where invalid analyses got published! If it was extremely serious, then I would talk with the PI about issuing a retraction/revision. If that went nowhere, then you would be in the sad position of possibly bringing it up with your institution's ethical review board and/or contacting the journal. Anybody been involved with anything like this?

**Matthew McCall** (11:01:25):
> @Jenny DrnevichI've asked to have my name taken off a paper because I wasn't comfortable with the analyses and the senior author refused to allow me to attempt to reproduce the results (I was just providing statistical guidance / supervision of a bioinformatian in the PI's lab).

**Jenny Drnevich** (11:08:23):
> @Matthew McCallWow! I wasn't an author on a paper but I have been asked to evaluate the appropriateness of an analysis before publication a couple of time. Me: "The analyses are flawed". Them: <***crickets>***Not sure what ever happened to them...

**Matthew McCall** (11:10:23):
> Those are sometimes the most worrying. I've had a few of those where I've raised an issue (typically completely confounded study design) and they just dropped me from the project and went ahead with publishing it.

**Riyue Sunny Bao** (11:20:52) (in thread):
> yup when submitting there is usually a check box on journal page e.g.`all authors have read and approved the manuscript`...

**Riyue Sunny Bao** (11:25:33):
> @Pedro Madrigalin that case I usually request removing my name from the paper. I have a reputation to guard and a paper does not worth costing my reputation.

**Pedro Madrigal** (11:40:46):
> @Riyue Sunny BaoThis is exactly what I did. No need to say, big PI did not like it...

**Charlie George** (11:47:57):
> When I think of the best bioinformatics/computational PIs/Stars they are fantastic at communicating really complex ideas in a 'down to earth' and accessible way - Caroline Uhler was an excellent example today (as are many of the bioconductor community). So my advice would be practise  talking to people outside your field about what you do and how best to explain it, whether that's teaching, lab meetings or just coffee conversations.

**Matthew McCall** (11:53:16):
> Thanks@Charlie Georgefor bringing us back to the main topic. As much fun as it can be to trade war stories, it's good to remember that many (most?) collaborators are a joy to work with and definitely spark new ideas and methods development.

**Matthew McCall** (11:53:51):
> Being able to communicate is key to getting the most out of any collaboration.

*16:10:28 - @Joselyn Chávez has joined the channel*
*16:10:41 - @Leo Lahti has joined the channel*
*16:11:01 - @Sonali has joined the channel*
*16:11:23 - @Lori Shepherd has joined the channel*
*16:12:48 - @Dr Awala Fortune O. has joined the channel*
*16:17:04 - @Kayla Interdonato has joined the channel*
*16:25:06 - @Matthew Carlucci has joined the channel*
*19:13:53 - @Tanya Grancharova has joined the channel*

## 2020-08-03

*02:06:15 - @bogdan tanasa has joined the channel*
*04:08:40 - @Sunil Nahata has joined the channel*

## 2020-08-04

*14:31:21 - @rohitsatyam102 has joined the channel*

## 2020-08-05

*03:19:33 - @Hans-Rudolf Hotz has joined the channel*
*19:04:56 - @Lambda Moses has joined the channel*

## 2020-08-07

**Charlie George** (04:38:06):
> [https://www.cell.com/trends/genetics/fulltext/S0168-9525(20)30161-X](https://www.cell.com/trends/genetics/fulltext/S0168-9525(20)30161-X)- some interesting comments from Chris about the importance the first conversations with biologists and how many fail. maybe one of the 10 simple rules could cover not getting too disheartened when things don't work out and expect many conversations not to.  Advice on how to help these initial conversations go well and get the relationship off on the right foot from the start  (even if its a quick goodbye) would be great. e.g. know what time you have to commit etc, what you want (opportunity to develop methods, is this a learning experience for you or a dataset you are comfortable with), where you draw the line between service and research and what you expect from a collaboration (authorship positions, who owns the research)

**Aedin Culhane** (11:08:41) (in thread):
> I have also asked for me name to be removed from papers, in one case it was sufficient for them to listen to my concerns, In the second it wasn’t so I removed my name

**Aedin Culhane** (11:12:53):
> Who is this aimed at?  Students/Postdocs/junior PI/Core facility staff or isolated bioinformatics students/postdocs attached to wet lab.  Do we even know who self-identifies in bioinformatics and where they are in an institute/univ/hopsital?


## 2020-08-22

**Pedro Madrigal** (05:38:30):
> is this idea stopped? the GitHub page shows no changes[https://github.com/drisso/ThrivingInBioinformatics](https://github.com/drisso/ThrivingInBioinformatics)

**Federico Marini** (08:13:21):
> Hi Pedro, no, the idea is still active. After some vacation I have been collecting the material and ideas, and will be happy to give some more momentum in here as well:wink:


## 2020-09-07

*20:58:43 - @Tyrone Chen has joined the channel*

## 2020-09-14

**Vivek Das** (19:33:57):
> @Federico Marinilet me know, when you think it’s time to kick start and if it’s possible for me to contribute.Also the stickers arrived. Yayy.:smiley:Thanks


## 2020-09-15

**Federico Marini** (01:55:03) (in thread):
> Sure. Sorry, got swamped in many other things planned in these weeks.
> As you can imagine, this 10sr is something I wanted to do and not I had to:smile:

**Federico Marini** (01:55:09) (in thread):
> Glad the stickers arrived!!


## 2020-10-01

**Aedin Culhane** (10:13:48):
> I have more stickers to send out. So if you didn’t get yours yet (or forgot to fill up the form…) do it soon

**Nur-Taz Rahman** (10:37:41):
> I filled out the form, but I never got my stickers . . . QQ

**Jenny Drnevich** (11:26:45):
> @Aedin CulhaneSo if we haven't gotten our stickers yet we should fill out the form again? If so, please send the link again! Thanks.


## 2020-10-08

**rohitsatyam102** (18:11:48):
> i got an email that i will get them soon but haven't received them yet

**Joselyn Chávez** (21:01:20):
> I can’t find the form to request my sticker, could someone please share it with me??


## 2020-10-09

**Dario Righelli** (03:47:14) (in thread):
> Hi Fede, I'm in too, when the it'll be the right time! ;)

**rohitsatyam102** (16:51:30):
> [https://docs.google.com/forms/d/e/1FAIpQLSdZp1vxJGP61XgKPc8P8XwXbZ9Kv-yFyJ1YWZ4Y-R7-5hiTsg/viewform](https://docs.google.com/forms/d/e/1FAIpQLSdZp1vxJGP61XgKPc8P8XwXbZ9Kv-yFyJ1YWZ4Y-R7-5hiTsg/viewform)

**rohitsatyam102** (16:51:42):
> here@Joselyn Chávez

**Joselyn Chávez** (16:52:47):
> Thanks@rohitsatyam102!!


## 2020-10-15

**Nur-Taz Rahman** (11:13:11):
> Got my hex sticker! Thank-you!!!!


## 2020-10-19

*23:29:38 - @Chris Chiu has joined the channel*

## 2020-10-26

*14:03:02 - @Jeffrey O'Brien has joined the channel*

## 2020-11-26

*06:52:02 - @Markus Schroeder has joined the channel*

## 2020-12-02

*05:42:16 - @Konstantinos Geles (Constantinos Yeles) has joined the channel*

## 2020-12-12

*00:41:31 - @Huipeng Li has joined the channel*

## 2020-12-18

**Federico Marini** (10:10:02):
> Hey there<!channel>!
> In an hour we’ll revamp our efforts for the 10-simple-rules BoF  we initiated at Bioc2020.
> Feel free to join in the EuroBioc2020 venue on Airmeet, all material can be reached via[https://federicomarini.github.io/eurobioc2020bof/](https://federicomarini.github.io/eurobioc2020bof/)

**Federico Marini** (10:11:49):
> This time we’ll build on your extensive input we had in the last session, so it would be
> * “more targeted”
> * more operational
> I’d be super happy if we can converge to the 10 “magic boxes” that will steer the direction of the manuscript we’d like to compose

**Federico Marini** (10:12:15):
> That said: looking forward to seeing you there!

**Dario Righelli** (10:16:57):
> could it be useful to setup a manubot? (do you have it already?)

**Davide Risso** (10:20:52):
> we have one already:[https://github.com/drisso/ThrivingInBioinformatics](https://github.com/drisso/ThrivingInBioinformatics):slightly_smiling_face:

**Hans-Rudolf Hotz** (10:33:35):
> I am sorry I wont be able to join today, but I am looking forward to help/contribute at a later stage

**Federico Marini** (10:44:19):
> No problem - I guess this channel is the best way to have a persistent platform to communicate, so I will encourage most of actions to take place here - also easier to coordinate!

*11:16:33 - @Thomas Naake has joined the channel*
*11:16:47 - @Nils Kurzawa has joined the channel*
*11:17:09 - @Friederike Dündar has joined the channel*
*11:18:57 - @Michael Stadler has joined the channel*
*11:43:26 - @Luke Zappia has joined the channel*
*12:08:43 - @Laurent Gatto has joined the channel*
*12:08:48 - @Marion Shadbolt has joined the channel*
*12:11:55 - @Olly Crook has joined the channel*
*12:20:12 - @Milan Malfait has joined the channel*
*12:25:03 - @Chris Vanderaa has joined the channel*
*12:25:35 - @Anne-Maud Ferreira has joined the channel*
*12:31:05 - @António Domingues has joined the channel*
*12:53:28 - @Shirin Moossavi has joined the channel*
*13:24:15 - @Alan O'C has joined the channel*
*13:31:06 - @Manojkumar Selvaraju has joined the channel*
**Friederike Dündar** (15:44:22):
> Thanks for the great session today! My connection was super flaky towards the end and I didn't hear what the next planned steps are -- do you mind posting them here@Federico Marini

**Friederike Dündar** (15:58:36):
> I would enjoy another brainstorming session (there's got to be an online mind-map/brainstorming platform, too) just focused on specific rules/specific questions (e.g. clarify what we mean by "thriving in bioinformatics -- thriving itself is rather general (be happy with what you do) and we also discussed several rather general topics, too (e.g. toxic research environment etc.). The challenge is to identify the aspects that are specific to bioinformatics (e.g. a generally fantastic research environment in a given lab may still be suboptimal for a bioinformatician).

**Shirin Moossavi** (17:13:10):
> Hi all, I am not a biostatistician/bioinformatician by training, but I have loved statistics throughout my career and especially the last couple of years that I have been heavily focused on microbiome research. Here are what I tell my mentees regarding how to learn coding:
> • Focus on HOW to learn and not WHAT to learn
> • Learn and implement good coding practice and coding efficiency
> • Learning to code is a trial-and-error process; learn to enjoy this process
> • Strive to become independent, this means that you need to rely on yourself while you seek guidance and direction
> • Start with breaking down your questions into analysis plan
> • Data exploration is key, you need to discover and decipher the story hidden in the data
> • You need to understand that there are alternatives and other options either in statistical approach or coding efficiency. You need to learn to make decisions appropriate to your study.
> • Always consider WHY when analyzing and interpreting the results

**Federico Marini** (17:32:13) (in thread):
> Sure!
> I’d like to have today’s thoughts sink in a little over this holidays, and then reprise this in a call that we can coordinate from here

**Federico Marini** (17:33:17) (in thread):
> That is definitely quite useful also IMHO  - some “rule candidates” did not seem so well spot on, so might need to address these in a more structured way

**Federico Marini** (17:33:51) (in thread):
> I’ll be on holiday from today onwards, but I’ll do my best to annotate the inputs you all provided

**Federico Marini** (17:35:23):
> Hi@Shirin Moossavi, thank you for the excellent points!
> If you see they fit into the proposed “rule candidates”, feel free to add them in the presentation, otherwise I’ll do one very general swiping round with all previous feedback we had throughout this channel as well!


## 2020-12-19

*16:37:25 - @Soumya Banerjee has joined the channel*
**Soumya Banerjee** (16:39:32):
> Hi everyone excellent session yesterday. Just to add to the points discussed yesterday, I would like to add 1) seek out a mentor who has been in a similar situation and is an early career researcher  2) proactively mentor PhD students and early career researchers

**Soumya Banerjee** (16:41:33):
> Also would like to mention that there are other career options coming up. Like UKRI has a Research Software Engineer (RSE) fellowship opportunity now. As@Laurent Gattomentioned that maybe RSE needs a new name


## 2020-12-22

**Soumya Banerjee** (08:05:23):
> Not to take the discussion in a different direction. I just read this article[https://www.nature.com/articles/d41586-020-03235-y](https://www.nature.com/articles/d41586-020-03235-y)
  - Attachment (Nature): [Postdocs under pressure: ‘Can I even do this any more?’](https://www.nature.com/articles/d41586-020-03235-y)
    > Long hours and a lack of job security, combined with workplace bullying and discrimination, are forcing many to consider leaving science, finds Nature’s inaugural survey of postdoctoral researchers.

**Soumya Banerjee** (08:05:47):
> Maybe useful to cite in the manuscript

**Soumya Banerjee** (08:06:13):
> This has the results of a survey of postdocs in Europe and the Americas


## 2020-12-28

**Dario Righelli** (05:29:06):
> @Federico MariniIf I want to add some suggestions to the existing rules, do I use the[gDoc](https://docs.google.com/document/d/1ybYpu4XO_WdGhUYYkmxabBjpkyMoGQWCWdB-PhsIoMk/edit)from your slides?


## 2020-12-29

**Federico Marini** (14:07:11):
> Exactly@Dario Righelli!


## 2021-01-07

**Friederike Dündar** (09:54:08):
> Are there plans to reconvene at some not-so-distant point in the future to discuss the paper?

**Federico Marini** (10:47:39):
> Hi Friederike!
> Yes, I just came back into academic business after the work-offline weeks over Christmas, so I’ll take a chance to collect all the ideas and sort them out

**Federico Marini** (10:48:22):
> But I agree that should be not too distant. I’d aim for doing a first catchup in January already.


## 2021-01-08

**Soumya Banerjee** (03:58:34):
> Thanks a lot. I was just about to message everyone that it would be meet once while the ideas are still fresh in our heads. Talk to all of you soon!


## 2021-01-09

**Riyue Sunny Bao** (23:37:50):
> HI everyone! Just found out I might be late to the conversation:sweat_smile:trained as bioinformatician and saw many of my friends struggled through their career (including myself) each of us eventually figured the right path but it took some time. Here are some take home thoughts from my (and my friends) experience. Many of these you might have already discussed so I just wanted to share here

**Riyue Sunny Bao** (23:37:54):
> ```
> - Environment. Pick the right environment you want to be in: a bioinformatics lab, a bioinformatics core, a departmental funded role, or a position shared by several PIs. It determines your success in early career stage, including expectations, duties, and resouces. A guidance to pick such environment: check if the PI(s) put bioinformaticians as first, co-first, or last authors on their papers. If never, then it is a red flag. 
> - Roles. The career path of a bioinformatics postdoc and a staff scientist can be very different (not always, but have to be careful when picking out labs). If you want to have your own lab, then priorities is to have 1st author papers and PI role grants, lock those K and R00 grants in your early career stage. If you want to stay in academia but not having your own lab or go to industry, then working on many different projects, mastering versitle skill sets and equip yourself with real-world hands experience is more important. 
> - Authorship. Set up expectations for authorship at the beginning of a project. I have seen too many times bioinformaticians do the analysis, make the figures, write the manuscript, write rebuttal letter, and somebody else is installed as first author. There is always this thing that without my analysis there is no paper, and without their data there is no analysis. Therefore whoever generate the data gotta be the first author. That is wrong. I would ask the PI(s) this frankly and bold at the beginning of a project: how do you envision the authorship? 
> - Reseach identity. At some point, you'd have to decide whether you want to be someone who writes code to build models and make discoveries on new targets for patients, someone who develops new algorithms/tools to resolve a complicated computational problem, or someone who builds large-scale bioinformatics infrastructure for many people to use. I know people who masters all three, but relatively rare. They also come with different positions when you go further in your career. 
> - Growth. Many universities do not have a career path for bioinformaticians. HR does not know what bioinformatics do, and the job description they have on record does not reflect the complexity of the work we do as scientists at all. They think we just simply do coding everyday and print numbers. To fix this situation, hiring manager usually has to talk through the process with HR, and it is a long process. 
> 
> And a few more .... 
> - Never be the free labor. In contrast to common presumption that bioinformatics work is free because no mice or reagent cost, it is not. 
> - Pull out toxic collaborations when you can. Even you know it'd be Nature paper, the trauma does not worth it. If you worry about burning bridges, ask help from senior advisers or your PI, to resolve this conflict for you.
> ```

**Riyue Sunny Bao** (23:44:01):
> hoping that was helpful!


## 2021-01-10

**Soumya Banerjee** (05:48:45):
> great points@Riyue Sunny Bao! I like your Research Identity points


## 2021-01-11

**rohitsatyam102** (03:37:35):
> I am happy someone finally jotted it down pointwise. However, when it comes to genomics, you gotta work for free in the starting to learn and get a hands on (at least in India; Sad though!!). Everyone does not have powerful machines to practice. I worked for a really bigshot in telomere biology in India for free for two months because he didn't trust my analysis in the starting ( I had a BTech Degree in Biotechnology not in Bioinformatics and no prior experience (on paper experience) though I knew a bit of the coding; also no-on-paper experience=no job) and it seemed to be fine in the starting because I was at-least getting access to HPC where I could run those state of the art aligners and workflows that failed on my laptop.  Besides, you gotta be a free labor sometimes when you require papers to showcase your capabilities. When applying abroad for internships/admissions to professors you are asked for evidences because no-one takes you seriously when you say you know WGS/CHIPSeq/RNASeq because even though you did know the analysis, your ex-boss denied to give you authorship (for xyz reason) and since you signed the NOC, you cant even use the data/plots you made to show that you know. And even when you share your codes as a testimony, you are told that your scripts seems to copied (Good lord!! everyone is following the same vignette for a given package, how do I remove plagiarism in codes). So@Riyue Sunny Baomaybe not being a free labor seems to be a leisure that established bioinformatician might enjoy, but for those who are in process of making, isn't it inevitable? I would love to learn how else can one exhibit his capabilities because even after single-handedly conceiving 4 mini projects, executing them all alone and writing the 4  first-author articles during my Bachelors didn't help me and I was repeatedly demanded of more evidence to prove my scientific acumen and capabilities!!


## 2021-01-12

**Riyue Sunny Bao** (13:20:57):
> hi Rohit!! You brought up a very important point. Research environment is very different in different countries ... the experience here we gather at US might not be applicable for bioinformaticians from other countries like in India or China!! I think it'd be useful to discuss this

**Riyue Sunny Bao** (13:25:11):
> In terms of free labor, that refers to time unaccounted for without any return. Authorships would be one way to compensate such effort. Denying authorships where you had intellectual contribution is unethical (though I have seen it happened to me too).

**Riyue Sunny Bao** (13:53:22):
> I do not see an easy solution to resolve this. One solution is to have senior people to advocate on behalf of you, though that is not always possible. My hope is that, as we bring more awareness to this problem, and as more fresh blood grows into leadership positions, we will change the culture over time.


## 2021-01-22

*15:41:44 - @Annajiat Alim Rasel has joined the channel*

## 2021-01-27

**Federico Marini** (05:52:48):
> Dearest BOF-participants, I want to excuse myself for not following up on this in the planned timeline I proposed. Got swamped by an unexpected quarantine case in the family (no harm, just chaos all around) that had to slow down and delay a couple of things.
> But no worry, the plan is pretty much still up:wink:Thank you for your understanding!:pray:


## 2021-01-29

**Soumya Banerjee** (02:52:14):
> No problem@Federico Marini!  talk to all of you soon


## 2021-02-08

**Aedin Culhane** (17:51:36):
> no problems, we are all wafting between chaos and calm, mostly the former ;-))


## 2021-02-12

*15:51:45 - @Janani Ravi has joined the channel*

## 2021-02-25

**Soumya Banerjee** (05:12:42):
> Dear All hope everyone is well. I was wondering if it would be worth having a virtual meet some time next month to talk about the great points that we discussed and give some more shape to the outline? Thanks a lot again and looking forward to talking with all of you!

**Federico Marini** (16:30:43):
> Agreed!
> Trying to pencil in a date/week: my 3rd week of March is full with swiss-cheese-teaching, shall we take the 4th week (CW 12)?


## 2021-02-26

**Soumya Banerjee** (03:17:52):
> 4th week of March sounds good to me! Does it work for everyone else? Sorry@Federico Mariniwhat is CW12 ?

**Federico Marini** (04:07:47) (in thread):
> calendar week 12

**Friederike Dündar** (06:16:46) (in thread):
> you've been in Germany too long, Federico:slightly_smiling_face:


## 2021-03-05

**Federico Marini** (02:53:13) (in thread):
> Still there and probably soon in the process of Germanizing myself with the extra nationality:flag-it::flag-de:


## 2021-03-10

**Soumya Banerjee** (15:29:56):
> should we decide on a date for the 4th week of March ?

**Federico Marini** (15:43:39):
> Yep!
> For me Wednesday 24 would be very good. A time slot that starts at 18:00 (6pm CET) could be also welcoming for other time zones in the US, like the Developers’ Forum does. Would this work for you all? Feel free to react with:thumbsup:and:thumbsdown:


## 2021-03-11

**Soumya Banerjee** (09:24:54):
> Is that 18:00 or 6 PM CET (central european time)?

*09:29:45 - @Chris Vanderaa has left the channel*
**Federico Marini** (09:35:15) (in thread):
> Yes, sorry for the ambiguity- 6 pm CET. I’ll update the previous message


## 2021-03-15

**Soumya Banerjee** (13:59:01):
> Do people prefer Zoom or Google hangout for these meetings?


## 2021-03-22

**Soumya Banerjee** (13:07:29):
> do we want to use Zoom or Google hangout for this meeting?@Federico Marinidoes anyone have a preference?

**Federico Marini** (15:24:59):
> Sorry for missing the Q last week - I cannot offer a non-free Zoom, so following the example of other working groups in here I set up a room in Jitsi:[https://meet.jit.si/BioconductorBOF10SimpleRules](https://meet.jit.si/BioconductorBOF10SimpleRules)
  - Attachment (meet.jit.si): [Jitsi Meet](https://meet.jit.si/BioconductorBOF10SimpleRules)
    > Join a WebRTC video conference powered by the Jitsi Videobridge


## 2021-03-23

**Hans-Rudolf Hotz** (12:06:33) (in thread):
> I am sorry, I have to give it a miss again tomorrow - though, I am still hoping there will be a chance to contribute for me at one point...

**Jenny Drnevich** (13:58:57):
> Hi all! I am on the BioC2021 Organizing Committee and at our meeting today the idea came up that in coordination with a jobs board, we could have a 1 hr BoF session discussing career paths in Academia vs. Industry vs. Core facilities targeted at grad students and post-docs to  help guide them in their career choices. This overlaps quite a lot with what you are doing now, and you may have already put in for another BoF this year.
> 
> Would it be alright if I crashed the first few minutes of the meeting tomorrow to discuss this other BoF idea and see who might be interested in being on the panel? I will be on there as a core bioinformatician. Thanks in advance!


## 2021-03-24

**Kevin Rue-Albrecht** (05:43:41):
> The other thing I was thinking about, in the lead up to the call today, is that we should encourage a diverse representation among the authors and contributors (e.g. interviewees), so that the meaning of "thriving" is covered in as many aspects as possible. For instance, it would be interesting to have insights into what ECR anticipate as goals to thrive, and compare/contrast to what more experienced group leaders (and other "stable" roles) view in retrospect as contributing to their path to thriving.

**Kevin Rue-Albrecht** (05:45:58):
> To preserve anonymity of contributors, we could always have a Google Docs or Google Form where people could drop discussion points and personal experiences anonymously, while providing a few pieces of information (e.g. current career stage)

**Soumya Banerjee** (06:19:01):
> Looking forward to this. I may be a few minutes late. Apologies in advance

**Charlotte Soneson** (13:06:49):
> Just a note that the call is happening now:point_down:[https://community-bioc.slack.com/archives/C017GBE6SCX/p1616441099002900](https://community-bioc.slack.com/archives/C017GBE6SCX/p1616441099002900)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1616441099002900)
    > Sorry for missing the Q last week - I cannot offer a non-free Zoom, so following the example of other working groups in here I set up a room in Jitsi: [https://meet.jit.si/BioconductorBOF10SimpleRules](https://meet.jit.si/BioconductorBOF10SimpleRules)

**Kevin Rue-Albrecht** (13:10:02) (in thread):
> I'm stuck in a call that ran over:confused:

**Aedin Culhane** (17:42:28) (in thread):
> Hi Kevin.  I like this idea.  Thriving for one person is suffocation for another  and its often dependent on career stage.  One interesting approach might be to focus on under-represented groups and ask each what they need.  I was recently talking to someone from MENA region (Middle east/north Africia) and basic resources and training are a big problem there, especially for women. Bioinformatics is not provided in most HBCUs.   etc


## 2021-03-25

**Soumya Banerjee** (05:29:10):
> great speaking to all of you yesterday! I am very excited about this.

**Soumya Banerjee** (05:29:42):
> Just a suggestion: should we draft a small 1 page summary and send pre-submission enquiries to editors/journals?@Federico Marini

**Soumya Banerjee** (05:30:09):
> we can contact Plos Comp Bio and also cell press patterns[https://www.cell.com/patterns/home](https://www.cell.com/patterns/home)

**Federico Marini** (05:30:49):
> I got in touch yesterday with the editorial team of PlosCompBiol to see how we should submit that - they specify one option which is not there in the submission system:shrug:

**Federico Marini** (05:31:28):
> Hopefully they will get back soon enough - and yes, a short 3 para-letter would be the best

**Friederike Dündar** (08:54:47):
> Hi, sorry I couldn't make it, apart from 6am I don't think there's a worse time for me for a meeting than 6pm:slightly_smiling_face:Anyway -- could you highlight the main conclusions that were reached? What's the main document for drafting the text?

**Dario Righelli** (09:21:34):
> Hi guys, sorry I couldn’t make it either. I was updated a little bit about it from Davide and we were discussing about having an infographic showing the multiple existing bioinformatics figures that will be described in the paper.
> A sort of dendrogram…
> If it’s something that can fit here, I offer myself do it, but I’d need some help to figure out about all the bioinfo figures and their relations. ^^

**António Domingues** (10:03:00):
> Same here. Attending a course at the moment, so no time at all:disappointed:

**Federico Marini** (15:58:45):
> Here’s the operative summary of yesterday’s call
> * the slide deck ideas have been combined into the draft available in[https://docs.google.com/document/d/18mZlk4Hy2hNtvymvejXS3wQaa2rj-f0mrjz7ZhJ0rCs/edit](https://docs.google.com/document/d/18mZlk4Hy2hNtvymvejXS3wQaa2rj-f0mrjz7ZhJ0rCs/edit)
> * we’re now with a couple of situations where rules could be merged/expanded, so that we get to the set of 10
> * before going in for the final rounds in manubot, we thought to just use this GDoc to sketch out the text content
> * leaving each rule’s point unchanged, we can write in the space between the tags ->
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F01T5PQEB6C/image.png)

**Federico Marini** (16:04:20):
> * we will need/use an introduction, and the ideas on presenting some “personas”/profiles is very well grounded
> * an important point to clarify: are we missing something?
> * PlosCompBiol seems to not accept anymore presubmission inquiries, even if their website currently has such a page -:shrug:
> I would like to thank a lot all the ones who could make it, but also everyone who contributed with a thought or a simple line so far. I hope we’ll be able to voice all the points of view and points you raised so far.
> 
> Next to do:
> * if you want to throw in some more comments, please do so (at best in suggesting mode)
> * if you feel you want to add some stub of text, use the space between the <content> tags


## 2021-04-03

**Soumya Banerjee** (03:55:22):
> should we talk sometime in early May to iterate a bit more on the draft?@Federico Marini


## 2021-04-06

**Federico Marini** (12:51:31):
> Yes, early may sounds reasonable to me, I’ll check in the calendar and we can make it poll-wise in here to find the best date.
> Noted as todo item as currently I cannot access my outlook:confused:


## 2021-05-05

**Riyue Sunny Bao** (12:14:12):
> Hello everyone! I added some thoughts to Rule #1, 2, 7, and 5 (as shown in order in the google doc draft). Also added  comments to the subsection of "find one's niche".  You can find the new contents  between `<content>` and `</content>` in the gdoc. Hoping that helps!

**Riyue Sunny Bao** (12:14:40):
> Ran out of steam when it comes to Rule 8:rolling_on_the_floor_laughing:but will add more later!

**Riyue Sunny Bao** (13:48:24):
> I also wanted to clarify that the content added in between`content`tags are not official write up languages for the paper .... mostly are suggestions and thoughts for now. Thanks!


## 2021-05-06

**Riyue Sunny Bao** (15:43:55):
> Added new content and comments to Rule 9-12. Done!

**Riyue Sunny Bao** (15:43:59):
> Hoping that was helpful!


## 2021-05-11

*16:43:56 - @Megha Lal has joined the channel*

## 2021-05-12

**Soumya Banerjee** (04:46:02):
> hello everyone@Federico Mariniwould all of you like to meet sometime in June to discuss the manuscript?


## 2021-05-13

**Federico Marini** (07:27:37):
> Yes! Thank you@Soumya Banerjee:wink:Shall we keep Thursday but do 17:00-18:00 (probably slightly more family-friendly)? - EDIT to clarify: 17:00-18:00 CEST, thanks@Janani RaviRe: date, on June 17 there’s already the Developers Forum. I can do both, 10th (:one:) and 24th (:two:). You can react to this message with that emoji(s) that would work for you!


## 2021-05-18

*09:25:22 - @Aditi Kulkarni has joined the channel*

## 2021-05-28

*00:46:34 - @Joselyn Chávez has left the channel*

## 2021-06-06

**Pedro Madrigal** (07:08:01):
> Hi all, I am just curious how is this "***Ten Simple Rules for Thriving in Bioinformatics Research" ***community effort going?


## 2021-06-07

**Soumya Banerjee** (15:16:05):
> @Federico Mariniand everyone should we decide on a date and time for the next call? Should we do June 17th 1700 CEST?

**Federico Marini** (15:16:48):
> June 17 might be not ideal - the developers forum would be right after that, and did not want to block a too long slot, in case one wants to attend both

**Federico Marini** (15:17:34):
> I just got notified something came up for the earlier slot, so I would need to opt for the one on June 24.


## 2021-06-08

**Soumya Banerjee** (13:01:26):
> thanks@Federico Marinican you please suggest a time for June 24th?

**Federico Marini** (13:02:22):
> 17:00-18:00 CEST, as in the poll - I’d try to stick to that as many gave some sign of availability


## 2021-06-24

**Federico Marini** (09:03:31):
> eHi - Here’s a reminder for our meeting later today (17:00-18:00 CEST)
> Hello to all the fellow birds of a feather:hatching_chick::duck::eagle:Meeting will be held over jitsi:[https://meet.jit.si/BioconductorBOF10SimpleRules](https://meet.jit.si/BioconductorBOF10SimpleRules)Looking forward to catching up with you there if you can make it!
  - Attachment (meet.jit.si): [Jitsi Meet](https://meet.jit.si/BioconductorBOF10SimpleRules)
    > Join a WebRTC video conference powered by the Jitsi Videobridge

**Janani Ravi** (12:10:22):
> ```
> [https://msu.zoom.us/j/93987577734](https://msu.zoom.us/j/93987577734)Meeting ID: 939 8757 7734
> Passcode: bioc_bof
> ```
> - There is no waiting room enabled
> - Participants can join anytime
> [So, hopefully you don’t need me to start the meeting.]
> 
> Next couple of meetings/writing sprints:
> * July 14, 1–4p UTC
> * Aug 19, 1–4p UTC

**Riyue Sunny Bao** (16:48:27):
> would love to join but have to miss it this time unfortunately (having a date with BFFs :D) but will be there next time!! Have fun everyone:hugging_face:


## 2021-07-07

**Shila Ghazanfar** (09:30:19) (in thread):
> just catching up on slack and realised i completely missed this:flushed:so sorry, putting the two next dates into my calendar now!


## 2021-07-09

**Federico Marini** (07:35:52) (in thread):
> No prob@Shila Ghazanfar- we’ll have some writing sprint sessions, as in@Janani Ravi’s post above. You are more than invited to join (also for a shorter time window, late comer, early goer, whatever suits you)


## 2021-07-12

**Jenny Drnevich** (12:47:55):
> At Bioc2021, we are having a Career Panel BoF (Thurs 5 Aug at 2 pm Pacific time / 11 pm CEST). discussing career paths in Academia vs. Industry vs. Core facilities targeted at grad students and post-docs to help guide them in their career choices. I am looking for volunteers to sit on the panel from the various career paths to give a brief overview of their area and answer questions. It would be great if someone involved with the 10 Simple Rules could be on the panel, likely as an Academic person. Anyone interested and able to be at the time slot?


## 2021-07-14

**Davide Risso** (08:31:23):
> Hi<!here>I'm sorry for the late notice, but I won't be able to join the writing session today. I'm happy to do a second pass in the next few days if you update here your progress.

**Davide Risso** (08:32:36):
> @Jenny Drnevichthe time is not ideal for me, but if nobody else from this channel volunteers, I'm happy to sit on the panel.

**Friederike Dündar** (08:59:26) (in thread):
> If you need someone from a Bioinfo core, I could offer myself

**Federico Marini** (09:08:28):
> :writing_hand:A link to the main document for the fellow writers:[https://docs.google.com/document/d/18mZlk4Hy2hNtvymvejXS3wQaa2rj-f0mrjz7ZhJ0rCs/edit?usp=sharing](https://docs.google.com/document/d/18mZlk4Hy2hNtvymvejXS3wQaa2rj-f0mrjz7ZhJ0rCs/edit?usp=sharing):writing_hand:

**Federico Marini** (09:12:32):
> [https://community-bioc.slack.com/archives/C017GBE6SCX/p1624551022010600](https://community-bioc.slack.com/archives/C017GBE6SCX/p1624551022010600)-> for these that want to join via video
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1624551022010600)
    > ```[https://msu.zoom.us/j/93987577734](https://msu.zoom.us/j/93987577734)
    > Meeting ID: 939 8757 7734
    > Passcode: bioc_bof```
    > - There is no waiting room enabled
    > - Participants can join anytime
    > [So, hopefully you don’t need me to start the meeting.]
    > 
    > Next couple of meetings/writing sprints:
    > • July 14, 1–4p UTC
    > • Aug 19, 1–4p UTC

**Jenny Drnevich** (10:10:57) (in thread):
> @Friederike Dündarthat would be great! I will also be on the panel as a core person. Once we get the volunteers, we will see if the areas want to put together 2-3 slides or just everyone introduces themselves and give a bit of background

**Jenny Drnevich** (10:15:33) (in thread):
> Thanks, Davide! I know the time isn't the best for European folks. I will pencil you in but try to recruit others.

**Federico Marini** (12:05:47):
> A huge THANK YOU to the participants of this writing sprint!
> It looks like it was a quite productive afternoon:sunglasses:

**Federico Marini** (12:06:52):
> For these of you who could not make it: no worry, you can pick any time in a second or third pass in the upcoming days.

**Federico Marini** (12:08:51):
> The next sprint is going to be on August 18, 1-4p UTC (the message above said 19th, but I recall we were aiming for keeping the weekday same)
> Link:
> ```
> [https://msu.zoom.us/j/93987577734](https://msu.zoom.us/j/93987577734)Meeting ID: 939 8757 7734
> Passcode: bioc_bof
> ```
> Happy:writing_hand:to everyone:slightly_smiling_face:

**Friederike Dündar** (14:02:40) (in thread):
> Well, if you've got the Core side covered, I don't have to be there:smile:I'm at CEST so if my perspective is already present, I'll take a raincheck. But you can keep me as a backup:wink:

**Friederike Dündar** (14:53:27):
> Can you comment on "edit" mode vs. "suggestions/comments"? I seem to have missed the memo on writing everything as a suggestion rather than a direct edit:grimacing:

**Federico Marini** (14:55:24):
> No worries - I figured out it was easier to find out what we have been writing on “while live” if keeping the suggesting mode.
> Since I know what rule you’ve been working on, no harm done at all:wink:

**Federico Marini** (14:55:45):
> the edits will be consolidated in internal rounds ideally before the next writing sprint

**Friederike Dündar** (15:06:47):
> gotcha

**Jenny Drnevich** (17:01:21) (in thread):
> I was hoping to get 2 people per area so there is diversity. I can reach out some other core people in the US to see if they can do it. That is pretty late for you.


## 2021-07-15

**Friederike Dündar** (05:32:09) (in thread):
> It is.@Kevin Blighe@Jared Andrews@Bob Policastromight have interesting perspectives, too

*05:32:21 - @Kevin Blighe has joined the channel*
*05:32:22 - @Jared Andrews has joined the channel*
*05:32:22 - @Bob Policastro has joined the channel*
**Jared Andrews** (07:26:07) (in thread):
> Happy to be involved if wanted. St. Jude is rather unique, but research hospitals as a whole are an interesting avenue that I expect many trainees tend to overlook.

**Kevin Blighe** (07:32:04) (in thread):
> I'd be interested but slightly worried about timing, as I'm due to start a new job as Chief Science Officer on July 30. I have worked in the clinical setting in the UK, and also maintained a career in bioinformatics in both private industry (via my own company and elsewhere) and academia (rising to Visiting Professor Level).

**Jenny Drnevich** (10:21:05) (in thread):
> @Jared Andrewsthat would be great to get someone from a research hospital as another core type (I'm university core).@Kevin Blighesounds like you span all 3 areas, which will point out that these definitely blend into each other. I can put you on as a maybe and you can see how your schedule is that week.

**Jared Andrews** (10:23:18) (in thread):
> Ah, to clarify, I am not in a core, but a bioinformatics staff position.

**Bob Policastro** (11:14:33) (in thread):
> I've been in industry a whole month, so I consider myself an expert on the topic:slightly_smiling_face:

**Kevin Blighe** (11:25:20) (in thread):
> Hi Jenny, yes, I was actually the first full-time bioinformatician in the UK NHS, based at Sheffield Children's Hospital. Was tough, going in straight from PhD. Later worked in an Italian hospital but more in research. Various short postdoc roles in UK & USA, own company started in London in 2015, and working on site in Brazil and USA, but mostly remote. Also contribute on a panel to Euro Commission. I guess that you could pencil me in preliminarily.

**Jenny Drnevich** (11:41:13) (in thread):
> Jared, I was vaguely separating job types into three main categories - the traditional Academic (primarily do your own biological research and/or bioinformatics development) vs. Industry (do whatever the company wants you to do) and then the catch all for the rest of us who do bioinformatics for lots of different people/groups instead of primarily for ourselves. Is there a group you feel you fit into best? I can see a research hospital being a hybrid of Academic and Industry...

**Jared Andrews** (11:42:32) (in thread):
> It is very much a hybrid between the two (which was a big part of the draw for me).

**Jared Andrews** (11:44:03) (in thread):
> The research being done is academic, but the funding structure (especially here) is quite different, and the work environment is likely more akin to that of industry than most academic institutions.

**Friederike Dündar** (11:48:07) (in thread):
> and do you mostly work on projects others have cooked up or projects you've developed yourself?

**Jared Andrews** (11:53:32) (in thread):
> It's kind of a mix between typical analysis work that I get plug n' played on ("Here's data, here's our question - analyze it") and tool/pipeline/process development that I have more control over. More "soft" responsibilities include data stewardship/organization, training others, and generally functioning as a resource people can go to with questions. Priorities shift pretty rapidly, and task switching is still something I'm learning to effectively manage.
> 
> The analysis work is my main function, but if I say "I can build X and it will make this task easier/faster/better, etc", I generally get the greenlight to go ahead with it. Especially anything that empowers people to dig through/visualize/interpret their own data.

**Friederike Dündar** (12:22:30) (in thread):
> definitely sounds like a Core Facility function:slightly_smiling_face:

**Jenny Drnevich** (12:22:48) (in thread):
> Jared, this would be perfect for the panel!

**Jared Andrews** (12:26:15) (in thread):
> @Friederike Dündar:shrug:I need to stop offering to do stuff probably. In reality, most of my work is for only a single lab/collaborations with said lab, so a bit different than a core facility, but definitely similar in needing to be flexible and working on wildly different projects all the time.

**Jared Andrews** (12:26:44) (in thread):
> I'm happy to be involved if wanted, though I'm far from "experienced".

**Kevin Blighe** (12:28:44) (in thread):
> If you have passed through BSc, Masters, PhD, and now work at arguably the most reputable hospital in the US / World, that's something to aspire to for many


## 2021-07-16

*12:43:39 - @Lori Shepherd has left the channel*

## 2021-07-19

**Riyue Sunny Bao** (16:44:49) (in thread):
> Happy to be involved but it seems you have got candidates for the core bioinfo:+1:I also recommend my friend Dr. Kyler Hernandez ([https://scholar.google.com/citations?user=u3xwhCUAAAAJ&hl=en](https://scholar.google.com/citations?user=u3xwhCUAAAAJ&hl=en)) he is the bioinformatics co-lead on the NCI GDC project and might offer some perspective from being a bioinfo scientist and managerial role in large-scale international projects (and within an institution e.g. U of Chicago)


## 2021-07-30

*11:12:07 - @Krutika has joined the channel*

## 2021-08-03

**Jenny Drnevich** (00:26:54) (in thread):
> @Davide RissoI do have two other "Academic" - type people for the Career Panel so if you are not able to make it due to the time, we will be OK although I would love to have you on there. It doesn't look like the 10 simple rules draft is at pre-pub bioRxiv stage yet so I would not link to it, but it might be good for you to mention the group if you are able to join.

**Davide Risso** (05:15:13) (in thread):
> Happy to be there and I will mention the 10 simple rules draft! Thanks!!


## 2021-08-05

*17:54:26 - @Wes W has joined the channel*
*17:54:29 - @Krutik Patel has joined the channel*
*17:55:37 - @mirna has joined the channel*

## 2021-08-18

**Friederike Dündar** (04:40:04):
> Just highlighting that there's another writing sprint tomorrow:slightly_smiling_face:
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1624551022010600)
    > ```[https://msu.zoom.us/j/93987577734](https://msu.zoom.us/j/93987577734)
    > Meeting ID: 939 8757 7734
    > Passcode: bioc_bof```
    > - There is no waiting room enabled
    > - Participants can join anytime
    > [So, hopefully you don’t need me to start the meeting.]
    > 
    > Next couple of meetings/writing sprints:
    > • July 14, 1–4p UTC
    > • Aug 19, 1–4p UTC

**Friederike Dündar** (04:42:46):
> that's 3-6pm CET (Berlin) or 9am-noon EST (New York)

**Hans-Rudolf Hotz** (04:45:34):
> it is today, isn't-t?[https://community-bioc.slack.com/archives/C017GBE6SCX/p1626278931024700](https://community-bioc.slack.com/archives/C017GBE6SCX/p1626278931024700)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1626278931024700)
    > The next sprint is going to be on August 18, 1-4p UTC (the message above said 19th, but I recall we were aiming for keeping the weekday same)
    > Link:
    > ```[https://msu.zoom.us/j/93987577734](https://msu.zoom.us/j/93987577734)
    > Meeting ID: 939 8757 7734
    > Passcode: bioc_bof```
    > Happy :writing_hand:   to everyone :slightly_smiling_face:

**Friederike Dündar** (04:59:09):
> lol, well, what a timely reminder then:smile:

**Friederike Dündar** (04:59:34):
> thanks for catching it

**Friederike Dündar** (05:00:00):
> although I never changed it in my calendar, so I'll probably be writing on my own tomorrow:slightly_smiling_face:

**Federico Marini** (08:58:15):
> I might also “have to” join tomorrow, as I have serious issues with the wifi these days

**Federico Marini** (08:58:59):
> I’ll ping myself in via audio in 2 min, though:wink:

*09:06:11 - @Alan O'C has left the channel*
**Janani Ravi** (17:37:26):
> hello all, in addition to a few content edits, I have started to add ‘practical tips’ to each section. It’s far from complete + it is helping me realize potential overlap between sections. If you think this is a good section to have at the end of each rule, maybe during your next iteration, you can start jotting down some thoughts there too? That will also help FM/others during the rearrangement and cleanup phase by identifying potential overlaps. It was fun writing together. Hope to see you soon!:wave:


## 2021-08-20

**Kevin Rue-Albrecht** (08:19:57):
> That's a really nice idea!

**Federico Marini** (11:07:22):
> Great idea@Janani Ravi! But yes, let’s fill this up. I think it is a great support for the text-stitchers


## 2021-09-11

**Pedro Madrigal** (13:59:07):
> Hi! Still time to contribute? It looks like the GitHub repo is empty??[https://github.com/drisso/ThrivingInBioinformatics](https://github.com/drisso/ThrivingInBioinformatics)

**Pedro Madrigal** (14:02:48):
> oops! I found the link to the google doc above!

**Pedro Madrigal** (19:55:04):
> I have left my edits/comments in the google doc. Apologies for not joining the Writing Sprints in July and August, it's been a while since I didn't check this<!channel>!


## 2021-09-15

**Federico Marini** (09:43:54):
> Hi@Pedro Madrigal- yes, still open to contributions, I have seen you found the right location!
> The repo will be probably a later stage.

**Federico Marini** (10:09:19):
> A piece of info for the entire<!channel>- I am a little swamped for a project review in a larger collaborative effort, so I could not speed up the preps from my side with proper editing of all your contributions.
> For this reason, I would suggest to skip this month, and reschedule for***October 14, 15:00 CET ***(3-6pm CET (Berlin) or 9am-noon EST (New York))
> 
> Link and modality would stay the same, see link in[https://community-bioc.slack.com/archives/C017GBE6SCX/p1626278931024700](https://community-bioc.slack.com/archives/C017GBE6SCX/p1626278931024700)If you want to keep some text components coming, please do so (at best probably in Suggesting mode).
> I will make sure that we pick up the pace for the upcoming meeting!
> 
> Feel free to react to this message so that I can keep track of who is actively involved:wink:
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C017GBE6SCX/p1626278931024700)
    > The next sprint is going to be on August 18, 1-4p UTC (the message above said 19th, but I recall we were aiming for keeping the weekday same)
    > Link:
    > ```[https://msu.zoom.us/j/93987577734](https://msu.zoom.us/j/93987577734)
    > Meeting ID: 939 8757 7734
    > Passcode: bioc_bof```
    > Happy :writing_hand:   to everyone :slightly_smiling_face:

*11:25:51 - @Stephany Orjuela has left the channel*
*16:32:31 - @Lucy has left the channel*
*23:02:34 - @Keegan Korthauer has left the channel*

## 2021-09-16

**Soumya Banerjee** (15:34:32):
> Hello everyone and@Federico MariniI have added some text/edits to the document. This is looking good!

*18:34:56 - @Henry Miller has joined the channel*

## 2021-09-25

*07:20:15 - @Haichao Wang has joined the channel*

## 2021-10-08

**Soumya Banerjee** (05:54:48):
> @Federico Mariniand others: I have added some more text to the google document. I will try my best to attend the Oct 14th meeting. I have another meeting during that time. Apologies in advance from me if I cannot attend it. All the best!

**Pedro Madrigal** (14:26:35):
> this was published yesterday[https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3001419](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3001419)
  - Attachment (journals.plos.org): [A field guide to cultivating computational biology](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3001419)
    > Do you want to attract computational biologists to your project or to your department? Despite the major contributions of computational biology, those attempting to bridge the interdisciplinary gap often languish in career advancement, publication, and grant review. Here, sixteen computational biologists around the globe present "A field guide to cultivating computational biology," focusing on solutions.


## 2021-10-09

**Janani Ravi** (10:52:06):
> I~~~may or ~~~may not be able to attend the Oct 14 writing session due to a grant deadline, but I will post my suggestions/edits soon after!*Happy writing, *everyone!


## 2021-10-11

**Soumya Banerjee** (15:12:11) (in thread):
> this is a great find@Pedro Madrigalwe should cite this paper


## 2021-10-14

**Pedro Madrigal** (03:26:49):
> hi! unfortunately I am unable to make it today but happy to add more contributions during the weekend - just let me know.

**Federico Marini** (08:51:48) (in thread):
> That was out as a preprint recently, I think there’s a new lead author

**Shila Ghazanfar** (11:08:20):
> hi i just went onto the zoom and noone’s there? did it finish early ? happy to edit particular sections that need some work, maybe those who joined a bit earlier could mention what needs work?

**Charlotte Soneson** (11:11:22):
> @Shila GhazanfarI can join the Zoom and bring you up to speed:slightly_smiling_face:

**Shila Ghazanfar** (11:11:57) (in thread):
> that’d be amazing, thanks Charlotte! joining now:slightly_smiling_face:

**Shila Ghazanfar** (12:37:04):
> i’ve attempted a re-write of Rule 1 - with focus on conciseness (ie max 500 words as a reasonable goal). I’ve removed the specific examples but happy for someone to inject some anecdotes where they see fit:slightly_smiling_face:


## 2021-10-15

**Federico Marini** (04:07:23) (in thread):
> I think you missed me by two minutes:stuck_out_tongue:needed to pick up the car w winter tires:car:


## 2021-11-08

*03:25:41 - @Paula Nieto García has joined the channel*

## 2021-11-10

**Janani Ravi** (09:36:34):
> @Federico Marini& others: are we not writing today? I have it on my calendar for some reason.:thinking_face:

**Hans-Rudolf Hotz** (10:44:43) (in thread):
> I am not aware of any group writing session today...

**Soumya Banerjee** (11:47:17):
> @Federico Mariniand others, are we planning to have a zoom call sometime next month to discuss the paper? Sorry if I missed any discussion about this

**Federico Marini** (11:49:06):
> None of you missed anything, it is just some chaotic situations on my side, apologies for that. I hope to get some recharged batteries some time soon:hugging_face:


## 2021-11-11

*09:27:55 - @Shilpa Garg has joined the channel*

## 2021-12-08

**Janani Ravi** (10:06:58) (in thread):
> Just to confirm — no writing group/co-write session today either, right? I still have a recurring event for some reason. I can make it for an hour or so.:thinking_face:


## 2021-12-11

**Riyue Sunny Bao** (23:35:17):
> hi! sorry for missing the writing sprints, Fall was intense! hoping to help with more writings over the next 2 weeks:hugging_face:

**Riyue Sunny Bao** (23:35:36):
> wishing everybody a wonderful holiday and a much deserved winter break!!


## 2021-12-14

**Pedro Madrigal** (07:10:09):
> Hi all!!  what's the current status of these 10 rules? is there any plan/meeting schedule for 2022?

*08:22:56 - @Megha Lal has left the channel*
*15:35:40 - @Spencer Nystrom has left the channel*

## 2021-12-16

**Federico Marini** (04:26:31):
> A word from my side - I know the channel has been lagging, and that is very much on me.
> Had some personal reasons to not being so present, and I am very sorry about that with you all.
> On top of the whole, just went through a 3-week quarantine phase post whole-fam-covid-infection…
> So, please give me some time to get back on track, and we will gain momentum again:slightly_smiling_face:I will keep you all posted, and take this occasion to wish you all some relaxing around-christmas days:slightly_smiling_face:

*05:11:22 - @Laurent Gatto has left the channel*

## 2022-01-05

*08:25:11 - @Dania Machlab has left the channel*

## 2022-01-18

**Janani Ravi** (22:17:03):
> Wish you all a very happy new year!@Federico Marinihope you are feeling much better now. Take your time. We are all recovering from work/breaks -- so, all good!:smiley:


## 2022-02-20

**Soumya Banerjee** (05:58:29):
> @Federico MariniI hope you and your family are well and have recovered. Apologies for my long silence on this channel. Hope all of you are fine as well


## 2022-04-01

*13:56:36 - @Nitesh Turaga has left the channel*

## 2022-06-23

**Soumya Banerjee** (07:32:28):
> Dear All@Federico Marinisincerest apologies for the repeat message. I was wondering if it would be worth meeting once virtually to discuss this paper. I think it is very close to being submitted and just needs a little push. I am quite excited by it!@Federico Marini@Charlotte Soneson@Kevin Rue-Albrecht@Janani Ravi


## 2022-09-27

*13:26:53 - @Maria Doyle has joined the channel*

## 2022-10-22

**Soumya Banerjee** (12:16:36):
> Dear All@Federico Marinisincerest apologies for the repeat message. I was wondering if it would
>  be worth meeting once virtually to discuss this paper. I think it is
> very close to being submitted and just needs a little push. I am quite
> excited by it!@Federico Marini@Charlotte Soneson@Kevin Rue-Albrecht@Janani Ravi

**Janani Ravi** (12:22:40) (in thread):
> I can look into again over the next few weeks.Should we setup co-write times again, maybe with a poll? That was likely the only time we(at least I) got any writing done.:sweat_smile:


## 2022-10-24

**Federico Marini** (05:12:28):
> My sincere apologies for the silence on this side,@Janani Raviand@Soumya Banerjee, but also to everyone else involved till now.
> I have been (too?) absorbed by a couple of other commitments and duties, and indirectly left this “on ice”.
> I am chopping down some other urgent things, and will resume this one properly, I think till the end of the year we can have something “ready to be read” fully:slightly_smiling_face:


## 2022-11-02

**Riyue Sunny Bao** (20:50:38):
> is the manuscript still using the google doc link here ?[https://docs.google.com/document/d/18mZlk4Hy2hNtvymvejXS3wQaa2rj-f0mrjz7ZhJ0rCs/edit](https://docs.google.com/document/d/18mZlk4Hy2hNtvymvejXS3wQaa2rj-f0mrjz7ZhJ0rCs/edit)

**Riyue Sunny Bao** (20:51:12):
> does it matter who wrote which parts in this draft? I practically do not remember which parts I wrote or contributed:rolling_on_the_floor_laughing:maybe it does not matter as editing is going on!


## 2022-11-03

**Soumya Banerjee** (13:03:34) (in thread):
> no problem at all! Let us organize a virtual meeting to discuss this and let us push it out. Looking forward to this!

**Soumya Banerjee** (13:06:46) (in thread):
> Thanks@Janani Ravi! it would be great to set up a co-writing time! That is a great idea! Can you please set something up?

**Soumya Banerjee** (13:07:26) (in thread):
> yes@Riyue Sunny Baothat is the manuscript


## 2022-12-01

*05:15:59 - @Chris Chiu has left the channel*

## 2023-01-12

*23:20:50 - @Ray Su has left the channel*

## 2023-01-24

**Soumya Banerjee** (03:30:34):
> happy new year all!@Federico Marini@Kevin Rue-Albrecht@Janani Raviand others shall we meet virtually in the next few months and discuss this manuscript?

**Janani Ravi** (10:13:33) (in thread):
> Happynew year—sure!


## 2023-03-09

**Janani Ravi** (17:18:37) (in thread):
> This came up again today in a different meeting with@Kevin Rue-Albrecht— maybe we can restart this/next month?[https://www.when2meet.com/?19135105-nezdv](https://www.when2meet.com/?19135105-nezdv)(timezone: MST, EST-2)


## 2023-03-31

**Soumya Banerjee** (05:18:33) (in thread):
> Thanks@Janani Ravi@Kevin Rue-Albrecht@Federico Mariniwould love to restart this!


## 2023-04-01

**Janani Ravi** (15:30:55) (in thread):
> Sounds good.Around apr 15?


## 2023-04-02

**Soumya Banerjee** (05:04:40) (in thread):
> April 15th works for me!@Kevin Rue-Albrecht@Federico Mariniand others does that work for you?


## 2023-04-03

**Kevin Rue-Albrecht** (04:20:37) (in thread):
> I see that's a Saturday. I can't promise anything on weekends these days

**Janani Ravi** (09:46:45) (in thread):
> I meant after mid-April.Hadn’tchecked the calendar.Let’s try the following week then! Weekend would be difficult.


## 2023-04-05

**Soumya Banerjee** (04:14:54) (in thread):
> @Janani Ravisounds good! let me know a time.@Kevin Rue-Albrecht@Federico Marini


## 2023-04-21

**Soumya Banerjee** (05:49:06) (in thread):
> @Janani Ravishall we try another time next week?

**Janani Ravi** (09:29:21) (in thread):
> Sorry, Soumya! It’s been an unexpectedly crazy month. Maybe next Tuesday—if not, let’s try early May?


## 2023-04-26

*03:08:48 - @Jeroen Gilis has left the channel*

## 2023-05-22

**Soumya Banerjee** (06:39:46) (in thread):
> Dear@Janani Ravino problem at all.let us know some times that work


## 2023-11-09

**Janani Ravi** (18:21:32) (in thread):
> Does anyone here have the bandwidth to quickly check how the landscape (published/preprints) has changed on this topic since we paused? Then we can make a decision as to whether or not to continue.:thinking_face:


## 2023-11-21

*05:46:09 - @Konstantinos Geles (Constantinos Yeles) has left the channel*

## 2024-02-18

**Riyue Sunny Bao** (19:04:27) (in thread):
> I wonder if it would be useful to clean it up and deposits as preprint . there are a lot of good content there in the current draft.


## 2024-05-14

**Lori Shepherd** (10:48:43):
> archived the channel
