---
title: "#bioc_africa"
---

## 2020-10-20

**Sean Davis** (08:01:35):
> @Sean Davis has joined the channel

**Sean Davis** (08:01:36):
> set the channel description: Bioconductor in and related to Africa

**Aedin Culhane** (08:02:01):
> @Aedin Culhane has joined the channel

**Lori Shepherd** (08:04:11):
> @Lori Shepherd has joined the channel

**Sean Davis** (08:04:30):
> One of the premier communities in Africa supporting genomic research on the continent:[https://h3africa.org/](https://h3africa.org/)
  - Attachment (H3Africa): [H3Africa | Human Heredity & Health in Africa | Human Genomic Research](https://h3africa.org/)
> H3Africa empowers African researchers in genomic sciences. It generates unique data that can be used to improve African and indeed global health!

**Sean Davis** (08:05:03):
> [https://www.sciencedirect.com/science/article/pii/S0168952514001966](https://www.sciencedirect.com/science/article/pii/S0168952514001966)
  - Attachment (sciencedirect.com): [The H3Africa policy framework: negotiating fairness in genomics](https://www.sciencedirect.com/science/article/pii/S0168952514001966)
> Human Heredity and Health in Africa (H3Africa) research seeks to promote fair collaboration between scientists in Africa and those from elsewhere. Her…

**Sean Davis** (08:10:35):
> You can invite folks not already in Bioc Slack by sending them this link:[https://bioc-community.herokuapp.com/](https://bioc-community.herokuapp.com/)

**Kevin Blighe** (08:10:45):
> @Kevin Blighe has joined the channel

**rohitsatyam102** (08:22:40):
> @rohitsatyam102 has joined the channel

**Ruth Schmidt** (08:27:44):
> @Ruth Schmidt has joined the channel

**Norbert Tavares** (09:41:31):
> @Norbert Tavares has joined the channel

**Vince Carey** (10:56:29):
> @Vince Carey has joined the channel

**Chris Fields** (11:49:15):
> @Chris Fields has joined the channel

**Nitesh Turaga** (12:08:32):
> @Nitesh Turaga has joined the channel


## 2020-10-22

**Chris Fields** (10:06:00):
> @Sean Davisthere is also the bioinformatics support infrastructure for H3Africa:[https://www.h3abionet.org](https://www.h3abionet.org)
  - Attachment (H3ABioNet - Pan African Bioinformatics Network for the Human Heredity and Health in Africa): [Home](https://www.h3abionet.org)
> H3aBioNet website

**Matt Ritchie** (17:11:31):
> @Matt Ritchie has joined the channel

**Yagoub Ali Ibrahim Adam** (17:11:55):
> @Yagoub Ali Ibrahim Adam has joined the channel


## 2020-10-23

**Falola Dare** (10:18:16):
> @Falola Dare has joined the channel

**chaimae samtal** (14:05:09):
> @chaimae samtal has joined the channel


## 2020-10-25

**Ben Story** (10:52:31):
> @Ben Story has joined the channel


## 2020-11-19

**Kevin Blighe** (08:29:06):
> @Kevin Blighe has joined the channel


## 2020-12-02

**Aedin Culhane** (16:45:58):
> Looking for speakesr for H3ABioNet Webinar series[https://docs.google.com/document/d/1xHTPhWtq6rDxxgeqSxAIR1Il4OS4cGRu5fJRA7YkNI4/edit](https://docs.google.com/document/d/1xHTPhWtq6rDxxgeqSxAIR1Il4OS4cGRu5fJRA7YkNI4/edit)


## 2020-12-05

**Mahmoud Ahmed** (23:49:57):
> @Mahmoud Ahmed has joined the channel


## 2020-12-06

**Davide Risso** (09:29:00):
> @Davide Risso has joined the channel

**Davide Risso** (09:31:24):
> Sorry I just found out about this channel... I wanted to mention that registration to EuroBioc2020 is free and open until tomorrow and it works well for Africa in terms of time zones... anyone interested can register at[eurobioc2020.bioconductor.org](http://eurobioc2020.bioconductor.org)


## 2020-12-12

**Hena Ramay** (23:46:55):
> @Hena Ramay has joined the channel


## 2020-12-14

**Katharina Imkeller** (10:14:04):
> @Katharina Imkeller has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:41:49):
> @Annajiat Alim Rasel has joined the channel


## 2021-04-28

**Sean Davis** (14:36:56):
> The workshop website is up and running:[http://app.orchestra.cancerdatasci.org/](http://app.orchestra.cancerdatasci.org/)


## 2021-05-11

**Megha Lal** (16:43:58):
> @Megha Lal has joined the channel


## 2021-07-23

**Batool Almarzouq** (15:51:45):
> @Batool Almarzouq has joined the channel


## 2022-01-28

**Megha Lal** (11:11:49):
> @Megha Lal has left the channel


## 2022-05-05

**Daniel Adediran** (15:53:44):
> @Daniel Adediran has joined the channel


## 2022-05-06

**Anelda Van der Walt** (11:02:49):
> @Anelda Van der Walt has joined the channel

**Anelda Van der Walt** (11:05:33):
> Hi everyone, Anelda from South Africa here. Thanks@Aedin Culhanefor the invitation. I'm not so much a user/contributor of BioConductor at the moment, although I have used various BioConductor packages in my life as bioinformatician. At the moment I'm involved in supporting various communities of practice in South Africa and more broadly on the African continent and there might be some overlap between this channel's interest and the work we're doing.

**Anelda Van der Walt** (11:08:31):
> One of the things that specifically might be of interest is the work we're doing with RSSE Africa (research software and systems engineers). We're re-launching this community of practice with a series of webinars and community meetups.
> 
> Our first event takes place on 11 May 2022 @ 15:00 CAT. Registration and more information available at[https://qkt.io/rsse-africa-2022](https://qkt.io/rsse-africa-2022)I'm also attaching flyers with info about the upcoming event and another one that provides more details about RSSE and the global RSE movement. Please feel free to advertise to others in your communities. Thanks!!
  - Attachment (quicket.co.za): [Book tickets for RSSE Africa Community Meetups 2022](https://qkt.io/rsse-africa-2022)
  - File (PDF): [RSSE Information Leaflet - Updated May 2022.pdf](https://community-bioc.slack.com/files/U34P8RS3B/F03F3RD1H32/rsse_information_leaflet_-_updated_may_2022.pdf)
  - File (PDF): [RSSEAfrica-11May2022.pdf](https://community-bioc.slack.com/files/U34P8RS3B/F03EGDMUHN0/rsseafrica-11may2022.pdf)


## 2022-06-17

**George Odette** (17:24:08):
> @George Odette has joined the channel


## 2022-07-29

**Alex Mahmoud** (16:54:45):
> @Alex Mahmoud has joined the channel


## 2023-02-06

**Deborah** (06:17:35):
> @Deborah has joined the channel


## 2023-05-17

**Hassan Kehinde Ajulo** (12:15:38):
> @Hassan Kehinde Ajulo has joined the channel


## 2023-05-19

**Umar Ahmad** (23:36:50):
> @Umar Ahmad has joined the channel


## 2023-06-21

**Maria Doyle** (11:25:13):
> @Maria Doyle has joined the channel


## 2023-08-05

**David Rach** (17:19:55):
> @David Rach has joined the channel


## 2023-10-02

**myles** (12:28:10):
> @myles has joined the channel


## 2024-03-05

**Amaka Joyce** (11:57:47):
> @Amaka Joyce has joined the channel


## 2024-04-09

**Amal Boukteb** (11:06:58):
> @Amal Boukteb has joined the channel


## 2024-08-21

**Angelique Trusler** (08:08:57):
> @Angelique Trusler has joined the channel

**Angelique Trusler** (08:09:00):
> [Cross posting]***The Fellowship***The[Capacity Accelerator Network (CAN) initiative](https://www.data4sdgs.org/initiatives/capacity-accelerator-network)develops data science talent for climate and health impact across Africa. The CAN Fellowship provides emerging data science professionals with the skills needed to address challenges at the intersection of climate and health and make a positive impact on lives across the continent.
> During the program, participants collaborate with host institutions and mentors on projects to share their data skills, encourage innovative solutions, and build a network of data professionals committed to sustainable development. The fellowship includes practical project work, media training, and opportunities for fellows to present their work at local, regional, and international events.[https://www.data4sdgs.org/about-can-data-science-fellowship](https://www.data4sdgs.org/about-can-data-science-fellowship)

**Said Salehe** (10:59:47):
> @Said Salehe has joined the channel


## 2024-08-23

**Rema Gesaka** (03:48:48):
> @Rema Gesaka has joined the channel

**Rema Gesaka** (03:49:23):
> :wave:Hello, team!


## 2024-09-08

**Sounkou Mahamane Toure** (11:26:48):
> @Sounkou Mahamane Toure has joined the channel


## 2024-10-11

**Maria Doyle** (05:24:01):
> Hey everyone!:wave:Just wanted to share some exciting news from CZI - there’s a new***African Bioinformatics Institute***being set up with support from Wellcome and CZI. They’re holding an online info session on***October 31st***, and I’ve signed up. Here’s the link to register if you’re interested:[https://wellcome.org/news/were-establishing-new-institute-advance-genomics-africa](https://wellcome.org/news/were-establishing-new-institute-advance-genomics-africa)
  - Attachment (Wellcome): [New Wellcome-funded African Bioinformatics Institute to advance genomics in Africa | News | Wellcome](https://wellcome.org/news/were-establishing-new-institute-advance-genomics-africa)
> With funding from Wellcome and the Chan Zuckerberg Institute, the ABI aims to support and develop sustainable genomics and wider bioinformatics research in Africa.

**Tobi Ogunbowale** (11:55:29):
> @Tobi Ogunbowale has joined the channel


## 2024-11-14

**Hedia Tnani** (03:44:32):
> @Hedia Tnani has joined the channel


## 2024-11-17

**Gen B** (14:54:04):
> @Gen B has joined the channel


## 2024-11-21

**Nesrine Gharbi** (04:11:14):
> @Nesrine Gharbi has joined the channel


## 2024-12-10

**Aleru Divine** (05:51:37):
> @Aleru Divine has joined the channel


## 2024-12-28

**Michael Hungbo** (07:28:23):
> @Michael Hungbo has joined the channel


## 2025-01-28

**Maria Doyle** (09:22:35):
> :earth_africa:***Bioconductor Course, Kenya 2025***:mortar_board:We’re excited to announce our first in-person Bioconductor course in Kenya, taking place***March 24–28, 2025***, in Nairobi! This free, week-long course is tailored for bioinformatics beginners and builds on our global Carpentry program.
> Participants will gain hands-on experience in R, Bioconductor, and RNA-seq workflows while supporting the growth of the Bioconductor community in Africa.:arrow_right:[ Apply now](https://forms.gle/7ofqnEy6jD95dPV66):information_source:[ More details](https://training.bioconductor.org/workshops/2025-03-Nairobi/index.html)We’ve also shared this announcement on[LinkedIn](https://www.linkedin.com/posts/bioconductor_bioconductor-bioinformatics-carpentries-activity-7289970491144962049-EHwz),[Mastodon](https://genomic.social/@bioconductor/113906027963249763)and[BlueSky](https://bsky.app/profile/bioconductor.bsky.social/post/3lgsi2rmf322k). Feel free to check them out and share if you'd like to help highlight this opportunity!:star2:


## 2025-02-19

**Idowu Festus** (04:48:45):
> @Idowu Festus has joined the channel


## 2025-02-20

**Mikaila Chetty** (02:33:09):
> @Mikaila Chetty has joined the channel


## 2025-03-03

**Mildred Anashie** (11:47:35):
> @Mildred Anashie has joined the channel


## 2025-03-25

**Maria Doyle** (03:42:55):
> [https://www.linkedin.com/feed/update/urn:li:activity:7310197726544060416](https://www.linkedin.com/feed/update/urn:li:activity:7310197726544060416)
  - Attachment (linkedin.com): [#bioconductor #bioinformatics #rprogramming #datascience #carpentries… | Bioconductor](https://www.linkedin.com/feed/update/urn:li:activity:7310197726544060416)
> :mortar_board::earth_africa: Bioconductor Kenya Course Kickoff! :tada:
> 
> We&#39;re excited to announce that our first Bioconductor course in Africa started yesterday in Nairobi! Day 1 was filled with learning and collaboration. Rachel Zozo, International Institute of Tropical Agriculture (IITA) Kenya Country Representative, gave the opening remarks, and Laurent Gatto from de Duve Institute, and Michael Landi from IITA taught the Bioconductor Carpentry Introduction to R and Bioconductor lesson.
> 
> Later this week, sessions will be led by Fabricio Almeida-Silva from VIB, Laurah Ondari from IITA, and zedias Chikwambi from AIBST. The course organisation was led by Trushar Shah from IITA and Maria Doyle from University of Limerick, through a grant secured by Aedin Culhane and Maria Doyle. Thanks to other organisers who helped make this happen, Charlotte Soneson from Friedrich Miescher Institute for Biomedical Research and Umar Ahmad from Africa CDC.
> 
> Thanks to Chan Zuckerberg Initiative and UL Global for their funding.
> 
> #Bioconductor #Bioinformatics #RProgramming #DataScience #Carpentries #CZIScience #LearningTogether #Africa


## 2025-03-28

**Laurent Gatto** (07:23:45):
> @Laurent Gatto has joined the channel

**Trushar** (07:24:13):
> @Trushar has joined the channel

**Khadija Juma** (07:26:25):
> @Khadija Juma has joined the channel


## 2025-03-31

**Fabricio Almeida-Silva** (08:37:48):
> @Fabricio Almeida-Silva has joined the channel

**Sophia Mogere** (15:38:40):
> @Sophia Mogere has joined the channel
