---
title: "#biocasia2023"
format: gfm
---


## 2023-04-19

*07:05:12 - @Dario Strbenac has joined the channel*
*07:05:23 - @Ellis Patrick has joined the channel*
*07:05:24 - @Maria Doyle has joined the channel*
**Ellis Patrick** (07:13:42):
> Thanks again for meeting tonight@Maria Doyle:slightly_smiling_face:

**Maria Doyle** (07:44:56):
> Was great to meet you all today, looking forward to BiocAsia2023:earth_asia::relaxed:


## 2023-04-21

*10:07:08 - @Yuanhua Huang has joined the channel*

## 2023-04-24

*13:16:15 - @Joshua Ho has joined the channel*

## 2023-05-08

*21:22:31 - @Peter Hickey has joined the channel*

## 2023-06-06

*20:22:51 - @Melody Jin has joined the channel*

## 2023-07-05

*19:30:05 - @Jean Yang has joined the channel*

## 2023-07-19

**Dario Strbenac** (01:30:00):
> Teamup calendar updated with placeholders.


## 2023-08-14

*13:03:05 - @Erica Feick has joined the channel*
**Erica Feick** (13:05:09):
> Hello BioCAsia organizers! I've been following up with Hopin on our BioC2023 experience (which was very positive). Of course they are asking us to renew our subscription for next year, but wanted to see if there was interest from this group to use Hopin for BioCAsia 2023? I believe Zoom was used for last year or if you plan to go full in-person that's great! Just please let me know your thoughts on it. Thanks

**Peter Hickey** (18:23:17):
> Yep, last year we just used a Zoom account I had through my university affiliation.
> BioC Asia 2022 was a satellite event of another bioinformatics event and there was some integrated platform thing (not Hopin) from them that we were offered but it was a nightmare, which is why we reverted to a simple Zoom link and recording.
> I'll let this year's organisers (@Dario Strbenacand@Ellis Patrick) tell you plans for this year.
> Thanks for getting in touch!


## 2023-08-22

**Erica Feick** (15:15:30):
> @Dario Strbenac@Ellis Patrickany thoughts on what you would like to use for BioC Asia 2023? We have until Monday 8/28 to let Hopin know if we are renewing for the year.


## 2023-08-23

*22:05:25 - @Xueyi Dong has joined the channel*

## 2023-09-03

**Dario Strbenac** (20:00:01):
> Would it be a good idea to have a selection in the registration form to specify whether the applicant is submitting an abstract for the Hong Kong Bioinformatics Symposium or the Bioconductor Asia Symposium?

**Xueyi Dong** (22:21:00):
> Hi@Yuanhua Huangand@Joshua Ho, several people have told me they are interested in giving a workshop on BioC Asia 2023. Can you please confirm is abstract submission for workshops available?


## 2023-09-04

**Yuanhua Huang** (01:12:34) (in thread):
> thanks Dario. For now, they are mixed together; only research vs R workshop. we may consider putting R related research together, after collecting all abstracts.

**Yuanhua Huang** (01:13:39) (in thread):
> Great. Yes, the abstract form is also for R related research or R pkg demonstration

**Yuanhua Huang** (01:14:15) (in thread):
> or you meant people interested in hosting a workshop for R. We also have room for that too. Do they have specific topic?

**Xueyi Dong** (02:44:07) (in thread):
> I think they are more interested in hosting a workshop. Can I know how many slots are available?

**Xueyi Dong** (02:47:21) (in thread):
> Their topics would be use some specific Bioconductor packages for analysis, which should fit the BioC Asia conference well.

**Xueyi Dong** (02:48:54) (in thread):
> If that’s possible, would you be willing to add the workshop option to the abstract submission page?

**Yuanhua Huang** (05:25:02) (in thread):
> Thanks Xueyi. Sure,I’lladd some info about the workshop proposal. Probably simply just email us.

**Yuanhua Huang** (05:38:44) (in thread):
> updated on the webpage


## 2023-09-07

**Ellis Patrick** (17:58:48):
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C35G93GJH/p1693496640080559?thread_ts=1693496640.080559&cid=C35G93GJH)
    > :mega: BioCAsia2023 abstract submission now open !


## 2023-10-05

*10:11:39 - @Vince Carey has joined the channel*

## 2023-10-15

*20:45:01 - @Y-h. Taguchi has joined the channel*
**Yuanhua Huang** (20:46:07):
> ***Joint Bioc Asia - HK Bioinfo Symposium 2023***will start from 9am HK Time (15min to go). All welcome!
> 
> Topic: Bioc Asia - HK Bioinfo Symposium 2023
> Time: Oct 16, 2023 08:45 AM Hong Kong SAR
> 
> Join Zoom Meeting[https://hku.zoom.us/j/91657475464?pwd=cEZ1YVY4VjIvRUFvNE14WTVmdnVYQT09](https://hku.zoom.us/j/91657475464?pwd=cEZ1YVY4VjIvRUFvNE14WTVmdnVYQT09)Meeting ID: 916 5747 5464
> Password: 135854


## 2023-10-16

**Maria Doyle** (06:16:43) (in thread):
> Thanks for sharing the Zoom link! For those looking for the schedule for the symposium, you can find it here:[https://biocasia2023.bioconductor.org/](https://biocasia2023.bioconductor.org/)


## 2023-10-17

**USLACKBOT** (03:08:18):
> ***biopackathon***has joined this channel by invitation from***community-bioc***.


## 2024-01-13

**USLACKBOT** (05:24:46):
> ***biopackathon***has removed themselves from this channel.


## 2024-02-22

**USLACKBOT** (00:00:00):
> Some older messages are unavailable. Due to the retention policies of an organization in this channel, all their messages and files from before this date have been deleted.


## 2024-05-14

**Lori Shepherd** (10:19:26):
> archived the channel
