---
title: "#biocasia2022"
---

## 2022-11-27

**Peter Hickey** (19:01:49):
> @Peter Hickey has joined the channel

**Peter Hickey** (19:01:49):
> set the channel description: Discussions during and about BioC Asia 2022

**Kozo Nishida** (20:56:43):
> @Kozo Nishida has joined the channel


## 2022-11-28

**Ray Su** (09:44:33):
> @Ray Su has joined the channel


## 2022-11-29

**Alexandra Garnham** (15:37:18):
> @Alexandra Garnham has joined the channel

**Pedro Baldoni** (16:24:15):
> @Pedro Baldoni has joined the channel

**Peter Hickey** (17:17:27):
> ***BioC Asia (Dec 1-2)***Zoom webinar link:[https://unimelb.zoom.us/j/89757924129?pwd=dktkeHl3TnlxeEo2aXArMHJ6SVROQT09](https://unimelb.zoom.us/j/89757924129?pwd=dktkeHl3TnlxeEo2aXArMHJ6SVROQT09)(passcode: 931607)
> The Zoom webinar will be active from about 12:55pm each day (Melbourne, Australia time; AEDT) but you will be able to join the waiting room prior to that.
> 
> Please don't share the link outside the Slack.
> Video recordings will be posted to YouTube following the event

**Jonathan Carroll** (19:00:36):
> @Jonathan Carroll has joined the channel

**Shixiang Wang** (19:11:14):
> @Shixiang Wang has joined the channel

**Kozo Nishida** (22:46:07):
> Hi all,
> I have widened the time display range on[https://biocasia2022.bioconductor.org/schedule/](https://biocasia2022.bioconductor.org/schedule/).
> (Because it was not set to display the full range of the schedule in areas with time differences.)
> Please let me know if you can't check the schedule well.
  - Attachment (biocasia2022.bioconductor.org): [Schedule](https://biocasia2022.bioconductor.org/schedule/)
> Schedule


## 2022-11-30

**Peter Hickey** (16:32:23):
> ***In-person presenters***Please upload your presentation (PowerPoint, Keynote, or PDF) to[https://bit.ly/biocasia2022](https://bit.ly/biocasia2022)or transfer to the presentation computer via USB before the start of your session

**Lori Shepherd** (18:13:25):
> @Lori Shepherd has joined the channel

**Peter Hickey** (18:29:31):
> @Ellis Patrick@Givanna Putri@Shani AmarasingheI’m looking for a volunteer who could swap to present today (ideally at 2:15 PM) - let me know if you’re able to please!

**Ellis Patrick** (18:29:37):
> @Ellis Patrick has joined the channel

**Givanna Putri** (18:29:37):
> @Givanna Putri has joined the channel

**Shani Amarasinghe** (18:29:37):
> @Shani Amarasinghe has joined the channel

**Ellis Patrick** (18:34:17) (in thread):
> Sorry Pete, there is a chance that I'm still making my slides....

**Peter Hickey** (18:36:25) (in thread):
> Haha that's okay, I have a back up plan but if someone is able to swap it might be simpler

**Givanna Putri** (20:06:17) (in thread):
> Sorry Pete, I’m still editing my slides (haven’t even done a practice talk yet), but if push come shove, I’ll fill in

**Shani Amarasinghe** (20:08:21) (in thread):
> I can, but I don’t think I can make it in person though l, ifthat’sok.

**Shani Amarasinghe** (20:11:15) (in thread):
> Was planning to attend virtually today and come in person tomorrow.

**Peter Hickey** (20:30:35) (in thread):
> That's okay. We'll leave it as is and I'll just switch some talks for today around

**Peter Hickey** (20:47:22):
> @Yue Caoand@Dario StrbenacA small change in the program means you'll each be presenting 15 minutes earlier than originally scheduled

**Yue Cao** (20:47:25):
> @Yue Cao has joined the channel

**Dario Strbenac** (20:47:26):
> @Dario Strbenac has joined the channel

**Dario Strbenac** (21:00:39):
> Someone else is using the meeting room.
  - File (PNG): [Blocker](https://community-bioc.slack.com/files/U34P8RS3B/F04CT6SM7PZ/image.png)

**Peter Hickey** (21:00:56):
> Can anyone attending virtually please confirm they can see slides

**Jovana Maksimovic** (21:07:03):
> @Jovana Maksimovic has joined the channel

**Anna Quaglieri (she/her)** (21:09:09):
> @Anna Quaglieri (she/her) has joined the channel

**Chris Chiu** (21:09:18):
> @Chris Chiu has joined the channel

**Paul Harrison** (21:09:21):
> @Paul Harrison has joined the channel

**Alice Johnstone** (21:09:25):
> @Alice Johnstone has joined the channel

**Michael Milton** (21:09:46):
> @Michael Milton has joined the channel

**Dario Strbenac** (21:10:10):
> No. Medical Biology is using the meeting room, blocking Bioconductor Symposium from starting. Does anyone know when Biology's meeting ends?

**Xueyi Dong** (21:10:43):
> @Xueyi Dong has joined the channel

**Jean-Philippe Fortin** (21:10:56):
> @Jean-Philippe Fortin has joined the channel

**Jovana Maksimovic** (21:11:10):
> Everything has been working perfectly on my end. No problem joining and have been able hear@Peter Hickeyand see all the slides.

**Jonathan Carroll** (21:12:15):
> All good here, joined via the link in the pinned message

**Matt Ritchie** (21:17:00):
> @Matt Ritchie has joined the channel

**Peter Hickey** (21:26:26):
> [https://www.jkanche.com/kana/](https://www.jkanche.com/kana/)for those who want to try out the app Aaron is presenting

**Peter Hickey** (21:51:40):
> Don't forget to post any questions here

**Peter Hickey** (21:52:57):
> @Dario StrbenacI don't think we'll try doing Q&A through zoom, sorry

**Dario Strbenac** (21:55:05):
> :unamused:Very impressive software engineering. How is Kana being used within Roche?

**Michael Milton** (21:58:33):
> If your workflow is already written in R without existing C++, how might you integrate it into this WASM framework? Have you looked into webR?

**Peter Hickey** (22:05:34) (in thread):
> Tagging@Aaron Lun

**Melody Jin** (22:09:17):
> @Melody Jin has joined the channel

**Calandra Grima** (22:15:26):
> @Calandra Grima has joined the channel

**Dario Strbenac** (22:30:04):
> Would you have gotten the same results without doublet removal? The proportion of doublet cells looked small.

**Ruqian Lyu** (22:33:53):
> @Ruqian Lyu has joined the channel

**Chao WANG** (22:40:50):
> @Chao WANG has joined the channel

**Andres Wokaty** (23:07:38):
> @Andres Wokaty has joined the channel

**Kozo Nishida** (23:19:23):
> [https://docs.google.com/presentation/d/1Wgs6y2ZMmbYGFk3WhEQ7Vc3NbvQxXjRFuyimidM1JxA/edit?usp=sharing](https://docs.google.com/presentation/d/1Wgs6y2ZMmbYGFk3WhEQ7Vc3NbvQxXjRFuyimidM1JxA/edit?usp=sharing)is the link to my slides.
> If you are interested in the community working groups, please click the links in the slides.
  - File (Google Slides): [BioCAsia2022 - 5mins](https://community-bioc.slack.com/files/U34P8RS3B/F04CRKYJF9D/biocasia2022_-_5mins)

**Matt Ritchie** (23:37:37):
> Can people online hear OK?

**Jovana Maksimovic** (23:38:39):
> Yes, it’s all good@Matt Ritchie

**koki** (23:50:12):
> @koki has joined the channel


## 2022-12-01

**Alex Wong** (00:02:36):
> @Alex Wong has joined the channel

**Jovana Maksimovic** (00:38:57):
> Thanks for a great session everyone:tada:

**Peter Hickey** (21:02:28):
> Sound and video okay at home?

**Lori Shepherd** (21:02:43):
> good to me

**Peter Hickey** (21:33:33):
> Minor thing: references to Spring, Summer, etc. don't immediately translate to us in the southern hemisphere :)

**Dario Strbenac** (22:30:19):
> How would your method perform in class-imbalanced data sets, such as skin cancer, which is predominantly a male cancer?

**Belinda Phipson** (22:37:18):
> @Belinda Phipson has joined the channel

**jmsimon** (22:38:11):
> @jmsimon has joined the channel

**Aaron Lun** (22:38:33):
> @Aaron Lun has joined the channel

**Mark Ziemann** (22:38:41):
> @Mark Ziemann has joined the channel

**Aaron Lun** (22:39:07) (in thread):
> oops, went to the wrong channel

**Belinda Phipson** (22:39:23) (in thread):
> We tested the method on datasets with only 1 sex and it works well! We actually uncovered an interesting "bug" by testing on single sex datasets (to do with scaling features)

**chunman zuo** (22:41:59):
> @chunman zuo has joined the channel

**Shila Ghazanfar** (22:44:18):
> @Shila Ghazanfar has joined the channel

**Dario Strbenac** (22:45:38):
> Given that there are already so many large single cell atlases publicly available, why would we want to build another one from bulk RNA sequencing data? What is the benefit of it?

**Aaron Lun** (22:46:01) (in thread):
> yes, i have looked at webR (and also pyodide). Basically they provide the ease of execution, but I suspect this will come at the cost of runtime performance and increased bundle size compared to a direct-to-wasm approach. Interesting to see how much adoption this gets; web developers seem to be obsessed with reducing resource usage, so I would speculate that most applications would end up implementing the critical parts direct in Wasm, but maybe webR would be useful for prototyping.

**Michael Milton** (22:48:03) (in thread):
> No doubt it will result in worse performance, but if it’s a fairly lightweight analysis I can see it being much easier to use pure R than needing to rewrite everything into C++

**jmsimon** (22:48:07) (in thread):
> Plenty of experimental conditions, developmental timepoints, manipulations, treatments, etc that haven't yet been profiled at the single-cell level but may have been assayed by bulk

**jmsimon** (22:57:10) (in thread):
> i should add- thats at least my personal experience. i almost never can find a truly matching single-cell reference to use:joy:

**Aaron Lun** (23:05:49) (in thread):
> to be honest, i would guess that, for a lightweight analysis, most devs would just rewrite it in JS and move on, rather than learn R (and introduce a chunky dependency on R in their app).

**Michael Milton** (23:10:31) (in thread):
> I have found that if your analysis involves some fairly simple linear algebra, stats etc, it is often very difficult to implement in JS and there probably isn’t a library that does so. In this case I tend to use Shiny just because of the convenience of using R, but I prefer the end product of a client-side application that webR might offer.

**Peter Hickey** (23:37:37):
> Is audio working for everyone?

**Dario Strbenac** (23:39:10):
> Fixed now.

**Peter Hickey** (23:39:46):
> Sorry about that, I didn't quite set up everything properly after the break

**Dario Strbenac** (23:45:16):
> In the comparison to CellRanger, what are the reasons that some counts are exactly zero in one software but positive in another?

**Peter Hickey** (23:51:25) (in thread):
> @Shani Amarasinghe

**Shani Amarasinghe** (23:54:28) (in thread):
> Hi Darlo, good observation!That is because the cells that are identified by one approach is not identified by the other. So we have made the count number 0 for those to make sure we can include them in the matrix for correlation.Does that answer your question.

**Dario Strbenac** (23:55:22) (in thread):
> Yes, thanks.


## 2022-12-02

**Aaron Lun** (00:01:19) (in thread):
> it's certainly another option. we'll have to see how much uptake it'll get, w.r.t. convenience of initial development versus dependency/maintenance burden.

**George Howitt** (00:07:45):
> @George Howitt has joined the channel

**Aaron Lun** (00:11:05):
> i just realized that hashedDrops was one of my functions. Forgot i wrote it.
> 
> If there is any interest, i'm happy to contribute hashedDrops to a "BioC demultiplexing package", pretty much like how I gave away scran's doublet-finding tools to***scDblFinder***. This hypothetical package could then be a one-stop-shop for BioC HTO demultiplexing, possibly also used in the book.
> 
> Maybe the speakers who gave demultiplexing talks might be interested:@George Howitt, jianan doesn't seem to be on slack.

**Amelia Dunstone** (00:12:42):
> @Amelia Dunstone has joined the channel

**Peter Hickey** (00:13:25) (in thread):
> I did discuss with the author of demuxmix to contribute to the hto demultiplexing section of osca

**Peter Hickey** (00:15:12) (in thread):
> That section could be expanded on with some of@George Howitt's findings

**George Howitt** (00:15:15) (in thread):
> There's a package called cellhashR that has wrappers for several demultiplexing tools, including hashedDrops, however it doesn't allow to change any of the default options for several tools. Something similar in bioconductor would be great

**Aaron Lun** (00:16:58) (in thread):
> one could imagine a similar interface as bluster where a generic dispatches on a single parameter class that chooses different hashing methods with its own parameters. Then workflows can jsut call the generic and switch between methods (and parametrizations of those methods) by just changing the`PARAM=`object.

**Aaron Lun** (00:18:33) (in thread):
> anyway, if someone is sufficiently motivated to create such a package, I'm looking forward to giving away this function to a better home.

**Aaron Lun** (00:20:24) (in thread):
> probably also some scope for improvement to`hashedDrops`, judging by the talks. Guess that the various cut-offs shouldn't be chosen so half-assedly.

**Dario Strbenac** (00:25:11) (in thread):
> Is there any R package for SNP-based demultiplexing (e.g. all samples have matched exome sequencing)?

**George Howitt** (00:28:42) (in thread):
> We've been using vireo[https://bioinformaticshome.com/tools/rna-seq/descriptions/Vireo.html#gsc.tab=0](https://bioinformaticshome.com/tools/rna-seq/descriptions/Vireo.html#gsc.tab=0)
  - Attachment (bioinformaticshome.com): [Vireo](https://bioinformaticshome.com/tools/rna-seq/descriptions/Vireo.html#gsc.tab=0)
> Description, details, publications, contact, and download information for Vireo

**George Howitt** (00:29:18) (in thread):
> demuxafy also includes a few others[https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/index.html](https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/index.html)

**Peter Hickey** (00:31:02) (in thread):
> @Dario Strbenacwe use vireoSNP (python) for this task with post-processing in R

**Peter Hickey** (00:32:02) (in thread):
> @Aaron Lunre hashedDrops, I think both@George Howittand I found that lowering logFC cutoff usually helped

**Aaron Lun** (00:56:42) (in thread):
> i don't even remember a parameter of that name.

**Peter Hickey** (00:57:22) (in thread):
> `confident.min`

**Aaron Lun** (00:57:32) (in thread):
> there seems to be a bunch of MAD-based outlier detection here; i bet doing the outlier detection per label would proboably give better results

**jmsimon** (00:59:45):
> i can't seem to find a link to Göknur's shiny app. anyone have it handy?

**Lachlan Dryburgh** (01:23:13):
> @Lachlan Dryburgh has joined the channel

**Hsiao-Chi Liao** (01:46:59):
> @Hsiao-Chi Liao has joined the channel

**Aaron Lun** (03:19:49) (in thread):
> fwiw, i just did some measurements using the webR demo at[https://webr.gwstagg.co.uk/](https://webr.gwstagg.co.uk/).
> 
> the bundle is a bit over 28 MB, not including any non-base packages. not great, and very tedious on hotel wifi, but some caching should limit the pain to first-time use.
> 
> performance may be an issue, though. Some basic tests for R 4.2.0 on my laptop, vs R 4.1.3 on the demo via Chrome:
> ```
> library(Matrix)
> X <- rsparsematrix(1000, 1000, 0.01)
> system.time(Z <- qr(X))
> ## 0.335 on laptop, 4.026 on Chrome
> 
> g <- gl(5, 4)
> system.time({
>     for (i in seq_len(1000)) {
>         y <- rnbinom(20, mu=10, size=10)
>         fit <- glm(y ~ g)
>     }
> })
> ## 0.799 on laptop, 4.304 on Chrome
> 
> X <- matrix(runif(500000), ncol=100)
> system.time(Z <- dist(X))
> ## 2.220 on laptop, 8.574 on Chrome
> ```
> So, several-fold slower in this session, but it's very erratic; sometimes it's only 2-fold slower, not sure why. The webR repo indicates it was compiled to minimize size, not for speed, so perhaps this could be easily improved by fiddling with the build.

**Michael Milton** (06:27:10) (in thread):
> Hmm that’s not great. I wonder how it compares to pyiodide

**Aaron Lun** (07:30:31) (in thread):
> was curious so went and tested it out. Python 3.6.9 on my machine vs[https://pyodide.org/en/stable/console.html](https://pyodide.org/en/stable/console.html)
> ```
> # Turn off all multithreading by setting
> # export MKL_NUM_THREADS=1
> # export NUMEXPR_NUM_THREADS=1
> # export OMP_NUM_THREADS=1
> 
> import numpy
> import time
> x = numpy.random.rand(5000, 100)
> y = numpy.random.rand(100, 5000)
> start = time.time()
> z = numpy.matmul(x, y)
> end = time.time()
> print(end - start)
> ```
> 0.5 seconds locally, 3.2 seconds on the console. So, not much better than webR's perf gap.

**Vince Carey** (08:50:32):
> @Vince Carey has joined the channel


## 2022-12-03

**Aaron Lun** (07:42:58):
> @Peter Hickeydid you want a copy of the presentation?

**Aaron Lun** (07:43:02):
> slides i mean

**Aaron Lun** (07:43:20):
> oh wait, i guess you already have it.


## 2022-12-04

**Peter Hickey** (19:06:38) (in thread):
> yeah that would be good

**Connie Li Wai Suen** (20:51:41):
> @Connie Li Wai Suen has joined the channel


## 2022-12-05

**Lizhong Chen** (17:50:31):
> @Lizhong Chen has joined the channel


## 2022-12-06

**Aaron Lun** (08:16:05) (in thread):
> done

**Peter Hickey** (16:47:25) (in thread):
> Thanks


## 2023-01-12

**Ray Su** (23:21:23):
> @Ray Su has left the channel


## 2023-01-20

**Yikun Jiang** (03:13:49):
> @Yikun Jiang has joined the channel


## 2023-02-06

**Aaron Lun** (01:39:25) (in thread):
> were there any videos of this? i can't remember if it was recorded or not

**Aaron Lun** (01:39:54) (in thread):
> some folks were asking about it and i was hoping to avoid having to give another company seminar


## 2023-02-28

**Peter Hickey** (17:32:12):
> BioC Asia 2022 presentations are now available for viewing on YouTube:[https://www.youtube.com/playlist?list=PLdl4u5ZRDMQRjQRyAlm4KpRbs1AD1ZODk](https://www.youtube.com/playlist?list=PLdl4u5ZRDMQRjQRyAlm4KpRbs1AD1ZODk)
  - Attachment (YouTube): [BiocAsia2022](https://www.youtube.com/playlist?list=PLdl4u5ZRDMQRjQRyAlm4KpRbs1AD1ZODk)
> Share your videos with friends, family, and the world

**Luyi Tian** (21:58:29):
> @Luyi Tian has joined the channel


## 2023-04-19

**Pedro Baldoni** (23:46:04):
> @Pedro Baldoni has left the channel


## 2023-04-27

**Ellis Patrick** (19:21:08):
> Hi<!here>, for those not in the know, we are currently organising BiocAsia to be held in Hong Kong this year. I'm posting here to gauge interest in being involved in the organisation of 1) the conference this year in some capacity (eg program committee) or 2) in BiocAsia conference organisation in the future.

**Simple Poll** (19:21:11):
> @Simple Poll has joined the channel

**Unknown User** (19:21:14):
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: context]


## 2023-04-28

**Vince Carey** (14:13:01):
> What is the date of the next BiocAsia


## 2023-05-03

**Ellis Patrick** (21:12:24) (in thread):
> The plan is the week of  16 - 20 October. Still locking down the exact days


## 2023-05-17

**Augustine** (11:43:15):
> @Augustine has joined the channel


## 2023-05-18

**Oluwafemi Oyedele** (05:54:11):
> @Oluwafemi Oyedele has joined the channel


## 2024-05-14

**Lori Shepherd** (09:44:50):
> archived the channel
