---
title: "#biocasia2021"
format: gfm
---


## 2021-03-16

*18:44:58 - @Peter Hickey has joined the channel*
**Peter Hickey** (18:44:58):
> set the channel description: Organising BioC Asia 2021

*18:46:07 - @Kozo Nishida has joined the channel*
*18:46:08 - @koki has joined the channel*
**Peter Hickey** (18:46:49):
> Hi all, are there any updates on planning for BioC Asia 2021?

**Peter Hickey** (18:47:01):
> would you prefer such discussion here or at[https://github.com/biopackathon/BiocAsia2021/discussions](https://github.com/biopackathon/BiocAsia2021/discussions)?

*18:47:14 - @Matt Ritchie has joined the channel*
**Kozo Nishida** (23:34:33) (in thread):
> @Peter HickeySorry, I don't have the update.
> Now I'm trying to assign the committee role to someone.
> (See[https://github.com/biopackathon/BiocAsia2021/discussions/12#discussioncomment-491878](https://github.com/biopackathon/BiocAsia2021/discussions/12#discussioncomment-491878))
> Currently, I'm considering whether there is a suitable person for the following three roles.
> 1. Program: Competitive component
> 2. Program: non-competitive component
> 3. Code of Conduct

**Peter Hickey** (23:36:46):
> are there any rough dates you have in mind?

**Kozo Nishida** (23:38:02):
> I'm sorry, I forgot to inform you of the schedule. The schedule has already been decided. From November 1st to 4th.

**Peter Hickey** (23:41:59):
> thanks!

**Peter Hickey** (23:43:10):
> The reason I ask is that BioC Asia is a sub-committee of the Australian Bioinformatics and Computational Biology Society (ABACBS). They help manage our finances and some other admin. I'm the representative for BioC Asia to ABACBS and so need to give occasional updates on BioC Asia's current plans.

**Kozo Nishida** (23:47:15) (in thread):
> Thank you for the information. I didn't know that. So@kokiand I have looked for Japanese sponsors.

**Peter Hickey** (23:48:30) (in thread):
> it's a great idea to look for local sponsors. i think we can help with previous/existing sponsorship. perhaps the organising committee should have a video call soon to discuss this and other general matters

**Kozo Nishida** (23:55:34) (in thread):
> ok. I will schedule the video call. Is there any date and time that is convenient for you?

**Kozo Nishida** (23:56:24) (in thread):
> please let me know if anyone else should be invited to the video call.

**Peter Hickey** (23:58:25) (in thread):
> I think the people involved in[https://github.com/biopackathon/BiocAsia2021](https://github.com/biopackathon/BiocAsia2021). unsure if@Matt Ritchieis interested/available? i'm a bit booked up this week and next, but after that we should be able to find a time (i'd prefer Tues, Wed, or Fri but have some flexibility)


## 2021-03-17

**Matt Ritchie** (00:05:57) (in thread):
> We can help with sponsorship@Kozo Nishida- sorry for not communicating this earlier!

**Kozo Nishida** (00:23:12) (in thread):
> @Peter HickeyOK. i'm also booked up this week and next. I will schedule a video call early next month (Tues, Wed, or Fri).@Matt Ritchiethank you for your help. By the way, Is it possible to see what and how much budget (==sponsorships?) was spent on past BioC?
> Japanese sponsors need information on how we use the budget.

**Peter Hickey** (00:43:54) (in thread):
> yes, i think we have that info for at least some of the previous years. the difference will be that these were in-person meetings and i'm doubtful in-person meetings will be happening this year

**Kozo Nishida** (00:49:54) (in thread):
> @kokiand I are currently assuming virtual meetings rather than in-person.

**Matt Ritchie** (01:40:37):
> Last year our expenses were minimal as it was an online event (i.e. we have funds left over) and we get another lot of sponsorship this year. The amount would probably be ~$1M Yen if that helps - not sure if that stretches very far. We could also potentially request some funding in the planned CZI EOSS proposal to support this event if more sponsorship would be helpful.

**Matt Ritchie** (01:42:27):
> Virtual is a good approach, as it will be possible to reach a larger audience, and saves people time and money in terms of travel (although it would be nice to visit Japan:jp:!)


## 2021-03-18

**Kozo Nishida** (01:52:30) (in thread):
> @Matt RitchieThank you for all the information.@kokiand I will hold BioCAsia2021 online and it will be the minimal case.
> We thought we had to get Japanese sponsors for BioCAsia2021 (because Japan is the organizer and we didn't know that we might be able to get the support you introduced).
> It may be better to change the way we think about Japanese sponsors.
> Because most Japanese sponsors do not allow the budget leave-over.
> We will withhold trying to get (Japanese) sponsors.
> We will just focus on clarifying what we need money for.

**Kozo Nishida** (01:56:07) (in thread):
> Yes, we will hold BioCAsia2021 virtually (like BioCAsia2020).


## 2021-03-20

*01:56:39 - @watanabe_st has joined the channel*

## 2021-03-23

*11:36:30 - @Mahmoud Ahmed has joined the channel*
*19:40:48 - @Xueyi Dong has joined the channel*

## 2021-04-01

**Kozo Nishida** (11:56:39):
> @Matt Ritchie@Peter Hickey@Mahmoud Ahmed@Xueyi Dong@Tom KellyI would like to hold a video meeting in April (for BioCAsia2021 organizing committee).
> Could you please check your convenient datetime in the doodle[https://doodle.com/poll/5687ns22rrstevdp](https://doodle.com/poll/5687ns22rrstevdp)(I haven't created the agenda yet, sorry)
  - Attachment (doodle.com): [Doodle: BiocAsia 2021 organizing committee](https://doodle.com/poll/5687ns22rrstevdp)
    > I will send you the Google Meet URL later


## 2021-04-15

*06:05:48 - @Harshita Ojha bs17b012 has joined the channel*

## 2021-04-22

*12:18:42 - @Satoshi Kume has joined the channel*

## 2021-05-11

*16:44:05 - @Megha Lal has joined the channel*

## 2021-05-13

*15:27:19 - @Aedin Culhane has joined the channel*

## 2021-06-25

*04:01:11 - @Heather Turner has joined the channel*
**Heather Turner** (04:02:54):
> From@Janani Ravi:******To anyone interested in attending useR! 2021 + building a strong AsiaR community******Hello,
> Hope you are doing well and are safe.
> 
> Please join our AsiaR incubator discussion at useR! 2021. The goal of this incubator is to discuss strategies for building a diverse and vibrant R community within Asia, connecting various useRs/developeRs, and down the line, hosting an AsiaR conference within the next couple of years.
> 
> Do invite people from your R community to join the incubator discussion and register for useR! Asian R-users can avail themselves of reduced registration fees. Also, if they do not have institutional support, we encourage them to apply for waivers. So, please spread the word, and write to us with questions, if any.
> 
> Here are some topics that we could address during our discussion.
> * Shared struggles of the local communities.
> * Motivation for creating/joining these communities.
> * Long-term goals for the AsiaR global community.
> * Current lack of online social platforms for the R community in Asia.
> * The focus is on Python instead of R, though R is a great language for data analysis. Academia/industries are much more invested in learning Python than R, starting with how students are educated.
> * Need for financial assistance -- what are resources we can tap into?
> Few invited participants from across Asia
> * Binod Jung Bogati from Nepal
> * Noman Khalid from Pakistan
> * Meenakshi Kushwaha from Taiwan
> * Joel Nitta from Japan
> * Young Suk-Lee, Woo June Jung, & Eun-Kyung Lee from South Korea
> * Aarthi Ravikrishnan from Singapore
> * Emi Tanaka | originally from Japan but now in Australia
> * Matthias Bannert | will help us connect with the R community in China, but based in Switzerland
> ***Moderators***
> * @Adithi R. Upadhya from Bangalore, India
> * @Janani Ravi| originally from India but now in the US
> ***SESSION DETAILS***Topic: Strategies to build a strong AsiaR community
> Time: 08 July 2021 3:40—4:40am UTC
> 
> useR! 2021 conference schedule:[https://user2021.r-project.org/program/schedule/](https://user2021.r-project.org/program/schedule/)Code of Conduct:[https://user2021.r-project.org/participation/coc/](https://user2021.r-project.org/participation/coc/)***Conference details***useR! 2021: July 05–09, 2021
> Website:[https://user2021.r-project.org/](https://user2021.r-project.org/)(incl. registration)
> FAQ:[https://user2021.r-project.org/participation/faq/](https://user2021.r-project.org/participation/faq/)Looking forward to building a wonderful AsiaR community with you all!

*08:37:16 - @Janani Ravi has joined the channel*

## 2021-06-26

*08:25:59 - @Tom Kelly has joined the channel*

## 2021-07-07

**Aedin Culhane** (01:49:51) (in thread):
> @Kozo Nishida@Matt Ritchieare you going to this session.

**Kozo Nishida** (03:16:57) (in thread):
> @Aedin CulhaneYes. I will introduce BioCAsia 2021. However, it seems that the introduction of the Bioconductor Community Advisory Board (CAB) is more suitable for this session than the introduction of BioCAsia.

**Matt Ritchie** (05:41:41) (in thread):
> Thanks@Kozo Nishida! I am also planning to attend - will be great to meet others who are keen to promote R in our region

**Kozo Nishida** (09:18:53) (in thread):
> @Matt RitchieFYI, the agenda of the session seems to be[https://docs.google.com/document/d/18CVgSmxODv7R9uRKntSS-EklOemUHSlQmQbb_VfejDQ/edit](https://docs.google.com/document/d/18CVgSmxODv7R9uRKntSS-EklOemUHSlQmQbb_VfejDQ/edit)[https://twitter.com/janani137/status/1412621919392874499](https://twitter.com/janani137/status/1412621919392874499)
  - Attachment (twitter): [Attachment](https://twitter.com/janani137/status/1412621919392874499)
    > :point_down:Join our #incubator_asiaR [@_useRconf](https://twitter.com/_useRconf) to discuss strategies to build a strong & sustainable AsiaR community! #useR2021
    > :date:Jul 8, 3.30 UTC
    > 
    > ~ [@AdithiUpadhya](https://twitter.com/AdithiUpadhya) [@janani137](https://twitter.com/janani137) 
    > w/ featured useRs from India, Nepal, S.Korea, Japan, Taiwan, Pakistan, S'pore & more! 
    > 
    > [https://docs.google.com/document/d/18CVgSmxODv7R9uRKntSS-EklOemUHSlQmQbb_VfejDQ/](https://docs.google.com/document/d/18CVgSmxODv7R9uRKntSS-EklOemUHSlQmQbb_VfejDQ/) [https://twitter.com/_useRconf/status/1409229005694410756](https://twitter.com/_useRconf/status/1409229005694410756) [https://pbs.twimg.com/media/E5qkJDPWUAAQgpc.jpg](https://pbs.twimg.com/media/E5qkJDPWUAAQgpc.jpg)
  - Attachment (twitter): [Attachment](https://twitter.com/_useRconf/status/1409229005694410756)
    > :hatching_chick: useR! 2021 Incubator
    > Strategies to build a strong AsiaR community
    > 
    > Join us to discuss ideas to build a strong, diverse, and vibrant AsiaR community!
    > 
    > #AsiaR #RStats
    > :date: Thu, July 8, 2021
    > :clock1: 3:30–4:30 am UTC
    > Join the Lounge — #incubator_asiaR
    > 
    > :link: [https://teamup.com/event/show/id/71FcJWv6T9qFVmJnRAxFmLBErJCtve](https://teamup.com/event/show/id/71FcJWv6T9qFVmJnRAxFmLBErJCtve) [https://pbs.twimg.com/media/E46WDWXXMAIxCIu.jpg](https://pbs.twimg.com/media/E46WDWXXMAIxCIu.jpg)
  - File (Google Docs): [Strategies to build a strong AsiaR community - discussion](https://community-bioc.slack.com/files/U34P8RS3B/F02787K3XK7/strategies_to_build_a_strong_asiar_community_-_discussion)

**Janani Ravi** (09:31:59) (in thread):
> Great! We will set aside couple of min for you to do that.:muscle:

**Kozo Nishida** (23:11:01) (in thread):
> @Janani RaviThanks. I said I would introduce BioCAsia, but it seems that the introduction of the[Bioconductor Community Advisory Board](http://bioconductor.org/about/community-advisory-board/)(CAB) would be more suitable for the topic of this session.
> I think the governance of this committee and the way of meetings will be helpful for the management of the AsiaR community.

**Janani Ravi** (23:15:10) (in thread):
> Yes, I have added a slide for you.

**Janani Ravi** (23:15:27) (in thread):
> Please join our #incubator_asiar channel on slack.

**Kozo Nishida** (23:20:03) (in thread):
> I'm sorry, I forgot to check "useR! 2021 - The Lounge" Slack. I'm in #incubator_asiar now. Thank you for the information.


## 2021-07-08

**Janani Ravi** (09:46:12) (in thread):
> Let's connect soon. It was great having you and@Matt Ritchiejoin us yesterday!:raised_hands:

**Janani Ravi** (09:46:48) (in thread):
> [janani@msu.edu](mailto:janani@msu.edu)|[jravilab.github.io](http://jravilab.github.io)| @janani137


## 2021-07-16

*10:43:53 - @Nitesh Turaga has joined the channel*
**Nitesh Turaga** (10:51:01):
> Hi, I would like to listen in on the Asia R / BIoc community and discussions. Allow me to introduce myself. I’m Nitesh, i’m a Scientist at Dana Farber/Harvard in the Data science department. I’ve been a core team member of Bioconductor for a while now. I work on cloud applications, scalability methods among other things Bioconductor related.
> 
> Although, i’m based in the US, my roots are from India.  So, i’m hoping to listen to some discussions to learn more.

**Kozo Nishida** (11:21:48):
> Hi,@Nitesh TuragaWe are looking for an invited speaker for the very cloud. Until now, I was thinking of asking Martin, but I would like to replace it with you.
> Instead, do you want to join the organizing committee?

**Nitesh Turaga** (11:23:04):
> I’m happy to accept and give a talk.

**Kozo Nishida** (11:24:18):
> understood. Let me add you to the one of the invited candidates who will provide a talk about the "cloud".

**Nitesh Turaga** (11:24:54):
> I wanted to listen in on the discussions mostly@Kozo Nishida.  I’m very new at organizing conferences, but would like to listen and see how it goes?

**Kozo Nishida** (11:27:11):
> @Nitesh TuragaI will invite you to the private channel for BioCAsia2021 organizing committee.

**Janani Ravi** (18:03:40):
> When is the conference scheduled for, Kozo?

**Kozo Nishida** (23:35:19) (in thread):
> The conference is scheduled for November 1st(1pm~5pm), 2nd(1pm~5pm), 3rd(1pm~5pm) and 4th(1pm~5pm)***Japan time***.


## 2021-07-23

*15:51:54 - @Batool Almarzouq has joined the channel*

## 2021-08-04

*08:34:09 - @Jirawat I. has joined the channel*

## 2021-08-10

*08:17:34 - @Woo has joined the channel*

## 2021-09-06

**Kozo Nishida** (23:12:53):
> <!channel>[https://twitter.com/kozo2/status/1435073250866851846](https://twitter.com/kozo2/status/1435073250866851846)
  - Attachment (twitter): [Attachment](https://twitter.com/kozo2/status/1435073250866851846)
    > We launched the dedicated website for BioC Asia 2021.
    > [https://biocasia2021.bioconductor.org](https://biocasia2021.bioconductor.org)
    > I would appreciate it if you could join us.


## 2021-09-08

**Aedin Culhane** (10:45:42):
> Great


## 2021-09-09

*18:28:41 - @Pedro Baldoni has joined the channel*

## 2021-10-28

*02:53:38 - @itTan has joined the channel*

## 2021-11-01

*02:27:25 - @Chris Chiu has joined the channel*

## 2022-01-28

*11:12:13 - @Megha Lal has left the channel*

## 2022-02-10

**Janani Ravi** (18:48:43):
> Cross-posting from#biocasia
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CH9QQUAE5/p1644536869571959)
    > <!channel> :tada: AsiaR is now on Twitter ([@AsiaR_comm](https://twitter.com/AsiaR_comm) | follow us) & we posted our first official tweet announcing our first exciting meetup! :confetti_ball:
    > > **How to build inclusive communities**
    > > featuring the amazing @Yanina Bellini Saibene @Heather Turner @Iman Al-Hasani!
    > > 
    > > :calendar: Come join us on Feb 19, 2022, 11a UTC | [local time](https://bit.ly/asiar_feb2022)
    > > 
    > > RSVP: [https://forms.gle/YdpiRqRroiTFN6GV6](https://forms.gle/YdpiRqRroiTFN6GV6)
    > :repeat: Please RT: [https://twitter.com/AsiaR_comm/status/1491916831522639876](https://twitter.com/AsiaR_comm/status/1491916831522639876)
    > 
    > Want to host the next event or the one after that?
    > Please sign up here: [https://bit.ly/asiar_host_2022](https://bit.ly/asiar_host_2022)
    > 
    > Most importantly, bring your fellow AsiaR useRs to Slack and help us build & grow this inclusive community! :raised_hands::skin-tone-3:
    > *See you all next week!* :wave::skin-tone-3: 
    > 
    > *[Qs? Please DM me @Janani Ravi]*


## 2022-04-01

*13:56:53 - @Nitesh Turaga has left the channel*

## 2022-12-01

*05:15:19 - @Chris Chiu has left the channel*

## 2023-07-11

*20:28:23 - @Pedro Baldoni has left the channel*

## 2024-05-14

**Lori Shepherd** (10:19:05):
> archived the channel
