---
title: "#bioc-connect"
format: gfm
---


## 2022-10-13

*06:52:02 - @Maria Doyle has joined the channel*
**Maria Doyle** (06:52:02):
> set the channel description: To identify ways to help Bioc people, groups, funders find connections between each other in an automated way e.g. using IAM, ORCID etc Benefits are to make it easier to network, identify opportunities for shared resources/challenges/funding etc

*06:54:29 - @Vince Carey has joined the channel*
*06:54:29 - @Lori Shepherd has joined the channel*
*06:54:29 - @Alex Mahmoud has joined the channel*
*06:54:29 - @Kasper D. Hansen has joined the channel*
*06:54:29 - @Nicole Ortogero has joined the channel*
*06:54:29 - @Aedin Culhane has joined the channel*
**Maria Doyle** (06:55:59):
> Initial working group for this being set up (as discussed in joint CAB TAB meeting yesterday). Members so far are@Vince Carey,@Lori Shepherd,@Alex Mahmoud,@Kasper D. Hansen,@Nicole Ortogero,@Aedin Culhaneand myself
> Proposing monthly meeting
> 4th Thursday of the month please vote for 9am ET:green_heart:or 12pm ET:yellow_heart:

**Maria Doyle** (06:56:43):
> set the channel description: To identify ways to help Bioc people, groups, funders find connections between each other in an automated way e.g. using IAM, ORCID etc Benefits are to make it easier to network, identify shared resources/challenges/funding etc

**Maria Doyle** (07:13:11):
> set the channel description: To identify automated ways to help Bioc people, groups, funders find connections between each other e.g. using IAM, ORCID etc. Benefits are to make it easier to network, identify shared resources/challenges/funding etc


## 2022-10-23

**Aedin Culhane** (15:16:56):
> We are trying to think of ways so developers get recognition for packages they develop that can be picked up for jobs/connections /funders etc.


## 2022-10-25

*11:57:01 - @Kozo Nishida has joined the channel*

## 2023-04-28

*16:05:25 - @Vince Carey has left the channel*

## 2023-05-17

*12:14:51 - @Hassan Kehinde Ajulo has joined the channel*

## 2024-05-14

**Lori Shepherd** (09:45:07):
> archived the channel
