---
title: "#biocchallenges"
---

## 2020-12-18

**Kevin Rue-Albrecht** (13:28:05):
> @Kevin Rue-Albrecht has joined the channel

**Kevin Rue-Albrecht** (13:28:05):
> set the channel description: General coordination of BiocChallenges

**FelixErnst** (13:29:32):
> @FelixErnst has joined the channel

**Charlotte Soneson** (13:29:40):
> @Charlotte Soneson has joined the channel

**FelixErnst** (13:29:51):
> thanks for setting uo the template

**FelixErnst** (13:30:05):
> cloned and deployed:slightly_smiling_face:

**Kevin Rue-Albrecht** (13:30:24):
> My pleasure!
> > cloned and deployed
> hahaha:laughing:

**FelixErnst** (14:31:37):
> The topics are hardcoded right now. Do you have an idea how they could be extended? Maybe import all biocViews terms as acceptable?

**Kevin Rue-Albrecht** (14:35:56):
> they're hard-coded insofar as it's a character vector in the BiocChallenges package, so adding topics is just a PR away:slightly_smiling_face:

**FelixErnst** (14:38:42):
> challenge accepted!

**FelixErnst** (14:38:49):
> :slightly_smiling_face:

**Dario Righelli** (14:43:21):
> @Dario Righelli has joined the channel

**Dario Righelli** (14:51:04):
> Hi guys, I was wondering about the Bioc Classes, that are increasing in number and sometimes they bring with them a few dependencies that can require time demanding installations.
> A good example is the`upsetSamples`function into the`MultiAssayExperiment`package which requires the`upsetR`package (and with it other graphical dependencies).
> A few years ago I wrote an upset plot function for the`GenomicRangesList`class (never released), so I thought that we can try to collect them into a unified external package, let’s say`BiocPlots`or something similar.
> Just to be able to lighten up the classes and at the same time collecting the same dependencies in a unified package.
> Do you think this could be a candidate for the BiocChallenges?

**Dario Righelli** (14:54:33):
> I know that in the end a similar package would depend on a few Bioc Classes, but most of them inherits from the same ancestor…


## 2020-12-21

**FelixErnst** (06:46:14) (in thread):
> I added the PR. I am not sure, why the GHA doesn't complete though.

**Kevin Rue-Albrecht** (14:27:36) (in thread):
> did you enable github action on your fork?

**Kevin Rue-Albrecht** (14:28:07) (in thread):
> I tweaked the PR anyway, so gha is running on a branch of the main repo


## 2021-01-22

**Annajiat Alim Rasel** (15:41:58):
> @Annajiat Alim Rasel has joined the channel


## 2021-03-03

**Aedin Culhane** (00:27:07):
> @Aedin Culhane has joined the channel


## 2021-03-30

**Sudarshan** (04:26:16):
> @Sudarshan has joined the channel


## 2021-05-01

**Arjun Krishnan** (21:39:34):
> @Arjun Krishnan has joined the channel


## 2021-05-11

**Megha Lal** (16:44:06):
> @Megha Lal has joined the channel


## 2021-07-19

**Leo Lahti** (17:00:20):
> @Leo Lahti has joined the channel


## 2021-11-26

**Francesc Català** (06:44:41):
> @Francesc Català has joined the channel


## 2022-01-28

**Megha Lal** (11:12:15):
> @Megha Lal has left the channel


## 2023-09-20

**Jaykishan** (05:29:46):
> @Jaykishan has joined the channel


## 2024-05-14

**Lori Shepherd** (10:18:05):
> archived the channel
