---
title: "#biocverse"
format: gfm
---

## 2018-07-25

**Davide Risso** (16:49:19):
> @Davide Risso has joined the channel

**Davide Risso** (16:49:19):
> set the channel description: Create a resource to visualize the Bioconductor ecosystem

**Stephanie Hicks** (16:49:56):
> @Stephanie Hicks has joined the channel

**Shian Su** (16:49:56):
> @Shian Su has joined the channel

**Nitesh Turaga** (16:49:56):
> @Nitesh Turaga has joined the channel

**Michael Love** (16:52:04):
> @Michael Love has joined the channel

**Charlotte Soneson** (16:54:01):
> @Charlotte Soneson has joined the channel

**Shian Su** (17:34:49):
> Can we get that sketch of our grand vision posted up?

**Daniel Giguere** (17:35:08):
> @Daniel Giguere has joined the channel

**Dario Righelli** (18:41:54):
> @Dario Righelli has joined the channel

**Diya Das** (23:55:16):
> @Diya Das has joined the channel


## 2018-07-26

**Shian Su** (09:15:20):
  - File (MATLAB): [Prototype](https://community-bioc.slack.com/files/U34P8RS3B/FBXA832SX/prototype.m)

**Shian Su** (09:16:22):
> Create a quick prototype of visualising dependencies in a network diagram. Personally don’t like the ball of mess it creates, but wanted to show that grabbing the package data with BiocPkgTools is really straight-forward.

**Lori Shepherd** (14:38:11):
> @Lori Shepherd has joined the channel

**Shian Su** (16:26:04):
> [https://github.com/seandavi/BiocPkgTools](https://github.com/seandavi/BiocPkgTools)for Sean’s great package to easily access the data
  - Attachment (GitHub): [seandavi/BiocPkgTools](https://github.com/seandavi/BiocPkgTools)
> BiocPkgTools - Access Bioconductor repository and project metadata from within R


## 2018-07-27

**Stephanie Hicks** (09:24:04):
> thanks@Shian Su! I ran your code but looked for the “RNASeq” biocview instead of visualization. really cool!
  - File (HTML): [network.html](https://community-bioc.slack.com/files/U34P8RS3B/FBY2LUL4B/network.html)

**Stephanie Hicks** (09:24:15):
> Should we start a github repo?

**Stephanie Hicks** (09:26:19):
> we can create github issue or roadmap of the types of networks that might be useful.

**Stephanie Hicks** (10:16:57):
> @Stephanie Hicks pinned a message to this channel.

**Stephanie Hicks** (10:22:56):
> I started a github repo:[https://github.com/stephaniehicks/biocverse](https://github.com/stephaniehicks/biocverse)let me know if you want push access!
  - Attachment (GitHub): [stephaniehicks/biocverse](https://github.com/stephaniehicks/biocverse)
> biocverse - project to create an interactive data viz of the biocoductor ecosystem

**Stuart Lee** (10:48:01):
> @Stuart Lee has joined the channel

**Michael Steinbaugh** (11:03:01):
> @Michael Steinbaugh has joined the channel

**Davide Risso** (11:11:21):
  - File (PNG): [Screen Shot 2018-07-27 at 9.36.44 AM.png](https://community-bioc.slack.com/files/U34P8RS3B/FBY1UAT5J/screen_shot_2018-07-27_at_9.36.44_am.png)

**Davide Risso** (11:12:26):
> this is the SingleCell biocView

**Davide Risso** (11:14:04):
> Note how important packages are missing, e.g., monocle… this is because biocViews are manually entered by the individual developers

**Davide Risso** (11:14:14):
> so perhaps NLP of the DESCRIPTION would be better


## 2018-08-14

**Aedin Culhane** (12:26:11):
> @Aedin Culhane has joined the channel


## 2018-10-30

**Rob Amezquita** (13:17:10):
> @Rob Amezquita has joined the channel


## 2018-11-27

**Stephanie Hicks** (20:07:45):
> hey, does anyone have a d3 object that we created from bioc in toronto of the network illustrating all the packages that use`SingleCellExperiment`?

**Stephanie Hicks** (20:09:22):
> I tried to run our code here ([https://github.com/stephaniehicks/biocverse](https://github.com/stephaniehicks/biocverse)) but see that some for of the function names in`BiocPkgTools`must have changed. I can also figure out what to fix, but thought I’d ask first
  - Attachment (GitHub): [stephaniehicks/biocverse](https://github.com/stephaniehicks/biocverse)
> project to create an interactive data viz of the biocoductor ecosystem - stephaniehicks/biocverse

**Shian Su** (20:58:36):
> I think I’ve fixed up the code in my pull request.


## 2018-11-28

**Stephanie Hicks** (15:50:37):
> thank you@Shian Su!


## 2018-12-06

**Kevin Rue-Albrecht** (17:03:10):
> @Kevin Rue-Albrecht has joined the channel


## 2018-12-21

**Laurent Gatto** (12:03:35):
> @Laurent Gatto has joined the channel


## 2019-02-25

**Rob Amezquita** (17:06:51):
> @Rob Amezquita has left the channel


## 2019-04-15

**Jon Bråte** (12:26:52):
> @Jon Bråte has joined the channel


## 2019-07-08

**Laurent Gatto** (16:57:55):
> As far as I remember, this is the first time I come across a paper like this[https://www.pnas.org/content/early/2019/07/02/1819409116](https://www.pnas.org/content/early/2019/07/02/1819409116)Does anyone know of additional references?
  - Attachment (PNAS): [Evaluating the prevalence and quality of conference codes of conduct](https://www.pnas.org/content/early/2019/07/02/1819409116)
> Academic conferences encourage collaboration and ignite ideas but can have negative impacts that disproportionately affect historically marginalized groups. Conference codes of conduct can help protect against abuses and foster diversity, but less than one fourth of the biology conferences we studied from the United States and Canada had them. Of these, few codes addressed or denounced identity-based discrimination and sexual misconduct that fuels attrition of scientists from historically marginalized groups. Most codes did not provide clear or impartial reporting mechanisms. Only two thirds listed consequences for violations. We provide recommendations for codes of conduct at biology conferences to improve equity in more platforms of science. Efforts to increase inclusion in science face multiple barriers, including cultural and social behaviors in settings such as academic conferences. Conferences are beneficial, but the culture can promote inequities and power differentials that harm historically underrepresented groups. Science suffers when conference culture propagates exclusion and discrimination that leads to attrition of scientists. Codes of conduct represent a tool to shift conference culture to better support diverse scientists and clearly detail unacceptable behaviors. We examined the prevalence and content of codes of conduct at biology conferences in the United States and Canada. We highlight how codes of conduct address issues of sexual misconduct and identity-based discrimination. Surprisingly, only 24% of the 195 surveyed conferences had codes. Of the conferences with codes, 43% did not mention sexual misconduct and 17% did not mention identity-based discrimination. Further, 26% of these conferences failed to include a way to report violations of the code and 35% lacked consequences for misconduct. We found that larger and national conferences are more likely to have codes than smaller ( P = 0.04) and international or regional ( P = 0.03) conferences. Conferences that lack codes risk creating and perpetuating negative environments that make underrepresented groups feel unwelcome, or worse, actively cause harm. We recommend that conferences have codes that are easily accessible, explicitly address identity-based discrimination and sexual misconduct, provide channels for anonymous impartial reporting, and contain clear consequences. These efforts will improve inclusivity and reduce the loss of scientists who have been historically marginalized.

**Kevin Rue-Albrecht** (17:12:13):
> Not exactly on the topic of “code of conduct”, but in the “provide recommendations” theme, I was remotely involved in this one:[https://www.embopress.org/cgi/doi/10.1038/embor.2013.147](https://www.embopress.org/cgi/doi/10.1038/embor.2013.147)If anything, taking a second to think about all this again does make me aware that a code of conduct is generally not the first thing on the mind of students (or anyone, really) organizing conferences/symposiums/… It’s very easy to focus on scientific content, etc, and only become aware of “conduct” when unfortunate things do happen


## 2019-07-12

**Jannik Buhr** (07:47:49):
> @Jannik Buhr has joined the channel


## 2019-10-29

**Kevin Rue-Albrecht** (17:33:49):
> @Kevin Rue-Albrecht has left the channel


## 2019-12-04

**Jonathan Carroll** (17:38:19):
> @Jonathan Carroll has joined the channel


## 2019-12-10

**Camille BONAMY** (11:56:47):
> @Camille BONAMY has joined the channel


## 2020-01-07

**Nitesh Turaga** (09:19:01):
> @Nitesh Turaga has left the channel


## 2020-03-12

**Stephanie Hicks** (16:00:52):
> @Stephanie Hicks has left the channel


## 2020-06-13

**Shian Su** (05:38:32):
> @Shian Su has left the channel


## 2020-06-17

**Marco Chiapello** (08:37:38):
> @Marco Chiapello has joined the channel


## 2020-07-30

**Rene Welch** (12:57:35):
> @Rene Welch has joined the channel


## 2020-07-31

**Dr Awala Fortune O.** (16:21:49):
> @Dr Awala Fortune O. has joined the channel


## 2020-12-02

**Konstantinos Geles (Constantinos Yeles)** (05:42:30):
> @Konstantinos Geles (Constantinos Yeles) has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:42:04):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-12

**Janani Ravi** (15:52:11):
> @Janani Ravi has joined the channel


## 2021-03-05

**Jim Hunter** (05:01:07):
> @Jim Hunter has joined the channel


## 2021-03-20

**watanabe_st** (01:56:50):
> @watanabe_st has joined the channel


## 2021-03-23

**Lambda Moses** (23:04:33):
> @Lambda Moses has joined the channel


## 2021-06-07

**Stuart Lee** (00:45:28):
> @Stuart Lee has left the channel


## 2021-07-19

**Leo Lahti** (17:00:30):
> @Leo Lahti has joined the channel


## 2021-08-06

**ChiaSin** (20:00:17):
> @ChiaSin has joined the channel


## 2021-08-15

**KP** (01:40:23):
> @KP has joined the channel


## 2021-09-29

**Kozo Nishida** (13:54:29):
> @Kozo Nishida has joined the channel


## 2022-09-17

**Kartik** (11:34:57):
> @Kartik has joined the channel


## 2023-11-21

**Konstantinos Geles (Constantinos Yeles)** (05:40:36):
> @Konstantinos Geles (Constantinos Yeles) has left the channel


## 2024-05-14

**Lori Shepherd** (10:36:11):
> archived the channel
