---
title: "#bioc2018-workshops"
format: gfm
---


## 2018-05-08

*11:14:38 - @Martin Morgan has joined the channel*
*11:14:38 - @Vince Carey has joined the channel*
*11:14:39 - @Levi Waldron has joined the channel*
*11:14:39 - @Sean Davis has joined the channel*
*11:14:39 - @Aedin Culhane has joined the channel*
*11:14:39 - @Rafael Irizarry has joined the channel*
**Martin Morgan** (11:16:27):
> set the channel description: Coordinate development and use of workshops for the Bioconductor annual conference

**Martin Morgan** (11:56:59):
> <!channel>our general plan is to have a centralized repository formatted as a 'book', with each accepted workshop a 'chapter'. We anticipate managing resources via ExperimentHub or similar. More as this develops...

**Martin Morgan** (11:57:09):
> Be sure to submit your proposals[http://bioc2018.bioconductor.org/call-for-abstracts](http://bioc2018.bioconductor.org/call-for-abstracts); applications close May 17.
  - Attachment (BioC 2018): [BioC 2018: Where Software and Biology Connect](http://bioc2018.bioconductor.org/call-for-abstracts)
    > Where Software and Biology Connect. July 25 - 27, Toronto, Canada.

*12:14:01 - @Marcel Ramos Pérez has joined the channel*
*12:17:38 - @Nitesh Turaga has joined the channel*

## 2018-05-09

*20:58:51 - @Stephanie Hicks has joined the channel*

## 2018-05-10

*14:39:34 - @Davide Risso has joined the channel*
**Davide Risso** (14:42:19):
> <!channel>We are about to submit a workshop proposal led by myself and two students. We were wondering: are the travel fellowships available also to students presenting a workshop or do they have to present a talk/poster to be considered for the fellowship?

**Davide Risso** (14:42:55):
> Currently the application for the fellowship is linked to the talk / poster submission

**Martin Morgan** (16:58:27):
> Yep we'll extend scholarships to workshop presenters. Just working out the technical details now...

**Davide Risso** (16:59:19):
> Thanks Martin!

**Martin Morgan** (17:04:45):
> (I mean the opportunity to apply for scholarships...)

**Davide Risso** (18:08:26):
> I thought you were giving away free scholarships on slack!:wink:

**Martin Morgan** (19:35:13):
> The workshop submission form should be updated to include a 'would you like to be considered for a scholarship...' field.


## 2018-05-11

*14:12:02 - @Peter Hickey has joined the channel*
**Peter Hickey** (14:17:36):
> I’d like to propose a DelayedArray workshop, led by myself. I emailed Hervé who has indicated his willingness to help. 
> I’m thinking of it being a developer-focused workshop, so I’m unsure whether to submit as a workshop (which are only running during the main conference?) or as a Birds of a Feather / Special Interest Groups for developer day
> Any guidance would be welcome!

**Levi Waldron** (14:50:48):
> Are you thinking of developer-oriented or user-oriented?

**Levi Waldron** (14:55:23):
> Another consideration, workshops are structured, and laid out in a syllabus, whereas BOF may or may not be structured, and could have any kind of structure.

**Peter Hickey** (15:54:08):
> developer-oriented. at this stage, my impression is that this is of greater interest/relevance to package developers. In an ideal world the user would rarely need to know they were dealing with an object that uses**DelayedArray**or ordinary arrays

**Vince Carey** (16:06:34):
> Should the topic be a little more general?  Storage-Agnostic Design?  IMHO we want a) to maximize use of standard rich containers like GRanges and (Ranged)SummarizedExperiment, b) ensure that there are no obstacles to using an alternate back end for any data container, and c) simplify effective use of alternate back ends when appropriate.  With Hervé and others, you've made great progress with c); b) seems pretty-well established?  Can progress and good presentation on b and c help us to get more uptake of a?

**Peter Hickey** (17:00:01):
> I see the interest in that topic, Vince. To me, I can see that working for a SIG session. 
> I was really thinking of running a how-to workshop for working with DelayedArray.
> I see the two as complementary


## 2018-05-14

**Martin Morgan** (12:31:16):
> The intention is to publish the workshops as a github book. Once workshops are accepted, you'll be asked to become a collaborator on[https://github.com/Bioconductor/BiocWorkshops](https://github.com/Bioconductor/BiocWorkshops); the process for workshop contributors is described in the 'index.Rmd' file. The workshops will be processed as a github book, currently available at[https://bioconductor.github.io/BiocWorkshops](https://bioconductor.github.io/BiocWorkshops). I'm not particularly versed in bookdown or the github publication process, so if there are productive comments / contributions I'm happy to listen. In particular it would be great to style chapters using BiocStyle, and to have a robust travis-based system for building chapters automatically after they are updated.


## 2018-05-31

*13:53:51 - @Lori Shepherd has joined the channel*

## 2018-06-04

*14:08:51 - @Michael Love has joined the channel*

## 2018-06-05

*19:47:40 - @Diya Das has joined the channel*

## 2018-06-06

*13:00:41 - @Kelly Street has joined the channel*

## 2018-06-07

*15:08:40 - @Charlotte Soneson has joined the channel*

## 2018-06-26

*16:41:51 - @Ju Yeong Kim has joined the channel*

## 2018-07-10

*08:03:34 - @Petr Smirnov has joined the channel*

## 2018-07-16

**Nitesh Turaga** (11:50:16):
> @Marcel Ramos PérezCan you take a look at the BiocWorkshops repo and see why it’s not building? The Travis job gets terminated, and I don’t think any of the latest changes have actually gone through.

**Marcel Ramos Pérez** (11:50:47):
> These are manual builds. I'm building the book now. I will push the output files soon.

**Nitesh Turaga** (11:51:10):
> Aaah, ok. So what is travis doing exactly?

**Marcel Ramos Pérez** (11:51:20) (in thread):
> This has to do with the 1 hour time limit for travis builds. We can't really build on travis.

**Marcel Ramos Pérez** (11:56:07):
> I've disabled the travis builds


## 2018-07-19

**Nitesh Turaga** (10:10:13):
> Will the workshops be built again before the conference or since yesterday was the deadline (18th) it has officially ended?

**Martin Morgan** (10:12:50):
> Does the AMI have a clone of the git repository, so any data used, e.g., BiocWorkshops/100_Morgan_RBiocForAll/ALL-phenoData.csv will be available to the participants

**Sean Davis** (10:13:18):
> It will have a clone of the repo, yes.

**Sean Davis** (10:43:29):
> For those who have access to AWS, the images will be available here:[https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;search=Bioconductor_Conference_2018;sort=desc:creationDate](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;search=Bioconductor_Conference_2018;sort=desc:creationDate)

**Sean Davis** (10:44:13):
> Generally, choose the newest one and use an instance with at least 30GB of RAM.

**Sean Davis** (10:46:55):
> Finally, be sure to configure the security groups to include http:

**Sean Davis** (10:47:02):
> @Sean Davisuploaded a file:[image.png](https://community-bioc.slack.com/files/U35HGTXNY/FBUG5LPN3/image.png)
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/FBUG5LPN3/image.png)

**Marcel Ramos Pérez** (10:54:50) (in thread):
> Is this different from using the`ALL`package?

**Marcel Ramos Pérez** (10:55:41) (in thread):
> NVM I see you're running data import examples

**Sean Davis** (11:01:19):
> And if you DO start an instance, be sure to turn it off when you are done!

*14:16:20 - @Brendan Innes has joined the channel*
**Sean Davis** (16:10:59):
> Just rendered the entire workshop book--500+ pages as an iBook!

**Levi Waldron** (16:11:10):
> whoa!

**Martin Morgan** (16:56:16):
> that's a lot of learning!

**Peter Hickey** (17:52:19) (in thread):
> Also wondering about this


## 2018-07-20

*04:46:41 - @Dario Righelli has joined the channel*

## 2018-07-23

**Nitesh Turaga** (10:27:56):
> Just a heads up, the workshop book references section is not rendering properly. It’s all going under the section`16.8`.

**Sean Davis** (10:29:26):
> Yeah, we have tried a couple of variations to fix that. No go as of yet. Apologies to the authors.

**Martin Morgan** (13:28:34):
> If I try and link to any chapter via http, e.g.,[http://bioconductor.github.io/BiocWorkshops/effectively-using-the-delayedarray-framework-to-support-the-analysis-of-large-datasets.html](http://bioconductor.github.io/BiocWorkshops/effectively-using-the-delayedarray-framework-to-support-the-analysis-of-large-datasets.html)I get redirected to https:// and need to security exception
  - Attachment (bioconductor.github.io): [The Bioconductor 2018 Workshop Compilation](http://bioconductor.github.io/BiocWorkshops/effectively-using-the-delayedarray-framework-to-support-the-analysis-of-large-datasets.html)
    > This book contains all the workshops presented at the Bioconductor 2018 Conference

**Sean Davis** (13:37:11):
> Does anyone else see the security exception issue? http and https work fine for me on Mac (Chrome and Safari).

**Nitesh Turaga** (13:37:37):
> I don’t see the security exception issue, but it does redirect to HTTPS.

**Sean Davis** (13:37:53):
> Same behavior for me.

**Martin Morgan** (13:44:46):
> OK thanks I'll take the blame...

**Sean Davis** (13:48:40):
> Check to see if you have up-to-date trusted certificates. I think on Ubuntu is it`update-ca-certificates`, but this is from memory.


## 2018-07-25

*09:06:09 - @Kasper D. Hansen has joined the channel*
*09:27:35 - @Shian Su has joined the channel*
*09:27:51 - @Stuart Lee has joined the channel*

## 2018-07-26

*11:15:18 - @Andrea Mcewan has joined the channel*
*12:56:48 - @Matthew Oldach has joined the channel*

## 2018-08-02

*09:31:19 - @Chiaowen Joyce Hsiao has joined the channel*

## 2018-11-10

**Levi Waldron** (08:26:27):
> archived the channel
