---
title: "#biocasia"
format: gfm
---

## 2019-04-02

**Stevie Pederson** (01:08:31):
> @Stevie Pederson has joined the channel

**Peter Hickey** (01:08:31):
> @Peter Hickey has joined the channel

**Stevie Pederson** (01:08:32):
> set the channel description: Chat about & plan the event

**saskia** (02:11:07):
> @saskia has joined the channel

**saskia** (02:11:23):
> :wave:

**saskia** (04:52:41):
> i think the easiest might be to go with precision medicine

**saskia** (04:52:46):
> cause that could be anything

**Dario Strbenac** (07:04:54):
> @Dario Strbenac has joined the channel

**Stevie Pederson** (23:38:34):
> Yeah, it's a tough call. I'm thinking that if we do the developer day Thursday then we can clash with whatever.


## 2019-04-03

**saskia** (20:37:30):
> anyway we probably need to respond, right?@Peter Hickey

**Peter Hickey** (21:28:10):
> sorry, yeah we do

**Peter Hickey** (21:28:13):
> i've been stupid busy

**Peter Hickey** (21:28:57):
> my random thoughts

**Peter Hickey** (21:29:12):
> i don't think mass spec will work. yes, there's stuff in bioc but none of us (I think) have any expertise

**Peter Hickey** (21:29:52):
> precision medicine - well i don't really know what they mean. ... but, as you say@saskia, that could be good cause we can make it whatever we want it to mean

**Peter Hickey** (21:34:10):
> if either of you have time this week to write that more coherently to send on our behalf to Jean, it'd be much appreciated. otherwise i will try to do on the weekend

**Peter Hickey** (21:35:06):
> and yeah,@Stevie Pederson, i'm also happy to clash with whatever on thursday to get a developer-focused day happening.
> we should find out what other (inter)national speakers they're inviting and see who might be good to invite along (e.g., John Marioni)

**saskia** (21:40:24):
> I am happy to write the email

**Peter Hickey** (22:21:17):
> legend, thanks for that sas


## 2019-04-04

**Stevie Pederson** (09:08:27):
> Great work@saskia. Thought I had a reasonable week but then it went nuts. Thanks for taking the lead on that one


## 2019-04-18

**Yoon, Tae-Hyun** (02:29:36):
> @Yoon, Tae-Hyun has joined the channel


## 2019-05-02

**Dario Strbenac** (20:00:13):
> What are the next tasks to do?


## 2019-05-06

**Peter Hickey** (23:48:50):
> Hi Dario, I'll set up some tasks during the week (I got back today from 3 weeks leave)


## 2019-05-24

**Dario Strbenac** (04:00:07):
> Jean will also book a room for Thursday in the guise of a stream of BioInfoSummer, so there's not much to do about room bookings.


## 2019-05-26

**Peter Hickey** (03:05:52):
> Great, thanks Dario!


## 2019-10-09

**Helena L. Crowell** (08:57:04):
> @Helena L. Crowell has joined the channel


## 2019-11-29

**koki** (15:41:33):
> @koki has joined the channel


## 2019-12-04

**Jonathan Carroll** (17:37:53):
> @Jonathan Carroll has joined the channel

**Stuart Lee** (18:34:15):
> @Stuart Lee has joined the channel


## 2019-12-17

**Jean Yang** (02:39:31):
> @Jean Yang has joined the channel


## 2020-05-15

**Giuseppe D'Agostino** (05:13:02):
> @Giuseppe D'Agostino has joined the channel


## 2020-06-11

**Kozo Nishida** (03:12:19):
> @Kozo Nishida has joined the channel


## 2020-07-31

**Isha Goel** (12:47:00):
> @Isha Goel has joined the channel

**Dr Awala Fortune O.** (16:16:13):
> @Dr Awala Fortune O. has joined the channel


## 2020-08-12

**Maria Doyle** (23:36:17):
> @Maria Doyle has joined the channel


## 2020-10-02

**Paul Harrison** (03:22:58):
> @Paul Harrison has joined the channel

**Paul Harrison** (03:23:39):
> @Paul Harrison has left the channel


## 2020-10-16

**bogdan tanasa** (02:57:18):
> @bogdan tanasa has joined the channel


## 2020-11-05

**Aedin Culhane** (11:55:02):
> @Aedin Culhane has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:41:54):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-12

**Janani Ravi** (15:52:01):
> @Janani Ravi has joined the channel


## 2021-05-11

**Megha Lal** (16:44:02):
> @Megha Lal has joined the channel


## 2021-07-16

**Nitesh Turaga** (10:43:50):
> @Nitesh Turaga has joined the channel


## 2021-07-23

**Batool Almarzouq** (15:51:50):
> @Batool Almarzouq has joined the channel


## 2022-01-28

**Megha Lal** (11:11:59):
> @Megha Lal has left the channel


## 2022-02-10

**Janani Ravi** (18:47:49):
> <!channel>:tada:AsiaR is now on Twitter ([@AsiaR_comm](https://twitter.com/AsiaR_comm)| follow us) & we posted our first official tweet announcing our first exciting meetup!:confetti_ball:
> > ***How to build inclusive communities***featuring the amazing @Yanina Bellini Saibene@Heather Turner@Iman Al-Hasani!:calendar:Come join us on Feb 19, 2022, 11a UTC |[local time](https://bit.ly/asiar_feb2022)RSVP:[https://forms.gle/YdpiRqRroiTFN6GV6](https://forms.gle/YdpiRqRroiTFN6GV6)
> :repeat:Please RT:[https://twitter.com/AsiaR_comm/status/1491916831522639876](https://twitter.com/AsiaR_comm/status/1491916831522639876)Want to host the next event or the one after that?
> Please sign up here:[https://bit.ly/asiar_host_2022](https://bit.ly/asiar_host_2022)Most importantly, bring your fellow AsiaR useRs to Slack and help us build & grow this inclusive community!:raised_hands:*See you all next week! *:wave:* **[Qs? Please DM me *@Janani Ravi**]**

**Heather Turner** (18:47:57):
> @Heather Turner has joined the channel


## 2022-02-15

**Dario Strbenac** (00:00:00):
> Is the symposium still looking for volunteers for the organising committee for this year's event?

**Peter Hickey** (00:04:20):
> very much so

**Dario Strbenac** (00:20:19):
> How may I participate again this year?

**Peter Hickey** (00:26:23):
> there's been no planning meetings since last year's conference and I don't know of any expressions of interest to host.
> are you interested in hosting in Sydney or just in general organisation?

**Dario Strbenac** (00:45:16):
> Just a general organisation once the hosting institution is selected.

**Kozo Nishida** (05:00:44):
> Hi@Dario Strbenac.
> Do you mean`the symposium`== BioCAsia2022 ?
> (Let me check it just in case.)

**Dario Strbenac** (05:05:02):
> I do.

**Kozo Nishida** (05:20:25):
> Thank you for the information.
> Thank you again for your interest in volunteering.
> I will check how you can join the BioCAsia2022 organising committee.

**Kozo Nishida** (05:23:07):
> @Dario StrbenacI also understand that you are interested in joining the committee after the hosting organization has been selected.
> (Thanks for asking that,@Peter Hickey)


## 2022-02-28

**Peter Hickey** (17:42:27):
> Is anyone interested in hosting BioC Asia in 2022, particularly those outside of Australia?
> This could be a hybrid meeting with an in-person component or fully virtual.
> 
> An alternative is that we have been approached by the Australian Bioinformatics and Computational Biology Society (ABACBS) about again having BioC Asia as a satellite event for the annual ABABCS conference (to be held in November, 2022).
> This would likely be a hybrid meeting.


## 2022-03-01

**Kozo Nishida** (02:11:02):
> @Dario StrbenacSorry for my late reply.
> The BioCAsia2022 hosting organization has not yet been decided, but you can get involved in the organizing committee.
> The work of the organizing committee includes the following.
> Let me know if you are interested in any of these.
> * ***Schedule and host organization decisions***
> * ***local or virtual platform organizing***
> 
> * website (see also[https://bioc2022.bioconductor.org/](https://bioc2022.bioconductor.org/))
> * registration
> * sponsorship
> * contact with invited speakers
> * community activities (BOF program)
> * competitive decisions (talks, workshops)
> * workshops technical aspects
> * code of conduct
> * scholarships
> * stickers
> * post-conference materials organization

**Kozo Nishida** (02:13:39):
> Of course, if the first "Schedule and host organization decisions" have not been decided, it may not be clear which one to take charge of.
> We will push forward it as Peter messaged it.

**Kozo Nishida** (02:15:50):
> @Dario StrbenacIf you are interested in deciding on a host organization, please help "***Schedule and host organization decisions***".
> If you are interested in inviting keynote speakers instead, please help "contact with invited speakers".

**Kozo Nishida** (02:18:16) (in thread):
> Thanks for the message.
> I also ask the AsiaR community about it.

**Kozo Nishida** (02:38:37):
> In the future, AsiaR will continue to hold meet-ups on various themes.
> (In it,) I'm considering introducing BioC Asia and calling for this year's host organization.[https://docs.google.com/spreadsheets/d/1EFKoFceB9EwPpeD93giFRyGLbZ92I5CCZPcWMc0aSpk/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1EFKoFceB9EwPpeD93giFRyGLbZ92I5CCZPcWMc0aSpk/edit?usp=sharing)I'm going to create (and share) the introductory slides for calling host organization(/institution).
  - File (Google Sheets): [AsiaR_meetup_volunteers](https://community-bioc.slack.com/files/U34P8RS3B/F0354NWKAJG/asiar_meetup_volunteers)


## 2022-03-02

**Peter Hickey** (00:12:26):
> it’s a good idea to speak with AsiaR. Can you please let me know when you will present. I will probably need to respond to the ABACBS president soon about what our plans our but it’s fine to tell him that we’re still thinking about where to host this year’s meeting


## 2022-03-04

**Kozo Nishida** (02:30:54) (in thread):
> > Can you please let me know when you will present.
> Yes, I will do it as early as this month and as late as April.
> > I will probably need to respond to the ABACBS president soon about what our plans our but it’s fine to tell him that we’re still thinking about where to host this year’s meeting
> Thank you for the information.
> I keep in mind that we need to work with ABACBS again this year.
> (I will also let people know about it.)
> I'm sorry but please respond to the president that we haven't made a plan yet.


## 2022-03-07

**Peter Hickey** (18:00:10):
> no problem

**Peter Hickey** (21:17:59):
> Today I joined the monthly ABACBS executive meeting.
> The annual ABACBS conference is planned to be held in November at Monash University in Victoria, Australia (Monash’s main campus is ~1 hour outside Victoria’s capital city of Melbourne).
> The proposal from ABACBS is to have BioC Asia as one of a small number (1-5) of satellite events to the ABACBS conference (likely after the main meeting).
> We have run BioC Asia in conjunction with ABACBS on a few occasions.

**Peter Hickey** (21:18:35):
> At Monash, there will be technical capacity for running this as a hybrid meeting which would allow those who can’t be in-person to participate online

**Peter Hickey** (21:22:54):
> I indicated to ABACBS that we have not yet decided about how, where, and when to run Bioc Asia 2022.
> I also mentioned that Kozo is discussing seeking interest from the AsiaR community.
> However, I told ABACBS that what they suggest sounds like a good proposal and I think right now it is probably our most likely choice.

**Peter Hickey** (21:23:12):
> I told them that we would give them a definitive answer by next month’s meeting, so I will organise a call for a couple of week’s time for us to discuss. Please indicate here if you are interested in joining this call


## 2022-03-12

**Janani Ravi** (12:47:18):
> @Peter Hickey@Kozo Nishidawhat would be needed/what would it entail to host either a ‘full’ BioCAsia or a satellite spin-off from ABACBS this Nov 2022? I ask this to find out what we need in terms of infrastructure, sponsorships, personnel, invited speakers, call for abstracts, etc. Please let us know and we will take it back to AsiaR folks. thank you!


## 2022-03-16

**Peter Hickey** (02:28:23):
> <!channel>If you are interested in being involved in organising BioC Asia 2022, we’ll have an initial planning meeting next week on Zoom.
> I’d like to keep this < 30 mins.
> Please vote for your preferred time:[https://doodle.com/meeting/participate/id/Ddw6p8zb](https://doodle.com/meeting/participate/id/Ddw6p8zb)I’ll send out an invitation at the end of the week
  - Attachment (doodle.com): [Doodle](https://doodle.com/meeting/participate/id/Ddw6p8zb)
> Doodle is the simplest way to schedule meetings with clients, colleagues, or friends. Find the best time for one-to-ones and team meetings with our user-friendly calendar tool. Get started today!

**Peter Hickey** (02:29:39) (in thread):
> Hi Janani, hopefully you’ll be able to join our initial meeting next week (see below). I plan to explain how past meetings have been run and discuss options for this year, which will cover these topics

**Janani Ravi** (13:25:23) (in thread):
> I’ve shared this with AsiaR folks, Peter.

**Peter Hickey** (18:20:46) (in thread):
> thanks!


## 2022-03-18

**Peter Hickey** (18:55:52):
> Thanks to those who responded and apologies to for whom the time doesn’t suit. We’ll post a summary/minutes back to the channel

**Peter Hickey** (18:55:54):
> ***Zoom meeting on Mar 22, 2022 10:00 AM Australia/Melbourne***Join from PC, Mac, iOS or Android:[https://unimelb.zoom.us/j/84021526185?pwd=VXRpMStjZFI1TW42b3V1M1o3SEY5Zz09](https://unimelb.zoom.us/j/84021526185?pwd=VXRpMStjZFI1TW42b3V1M1o3SEY5Zz09)Password: 596853
> 
> Need to dial-in instead? Enter the meeting ID: 840 2152 6185 via
> Australia:[+61 3 7018 2005](tel:+61370182005)or[+61 2 8015 6011](tel:+61280156011)Hong Kong:[+852 5808 6088](tel:+85258086088)or[+852 5803 3730](tel:+85258033730)US:[+1 669 900 6833](tel:+16699006833)or[+1 646 876 9923](tel:+16468769923)Additional international numbers:[https://unimelb.zoom.us/u/kdRsNDLvI6](https://unimelb.zoom.us/u/kdRsNDLvI6)Or join from a H.323/SIP room system:
> Dial:[84021526185@global.zoomcrc.com](mailto:84021526185@global.zoomcrc.com)| or SIP:[84021526185@zmau.us](mailto:84021526185@zmau.us)| or 103.122.166.55
> with meeting ID: 84021526185 and password: 596853


## 2022-03-23

**Kozo Nishida** (04:37:25):
> @Peter Hickey@Janani RaviI'm sorry, I've been busy lately and couldn't reply to you.
> I will check your document(s) from now on.

**Peter Hickey** (18:37:00) (in thread):
> No problem Kozo


## 2022-03-26

**Jayaram Kancherla** (21:17:14):
> @Jayaram Kancherla has joined the channel


## 2022-03-29

**Mahmoud Ahmed** (10:25:17):
> @Mahmoud Ahmed has joined the channel

**Mahmoud Ahmed** (10:36:19):
> I saw the call for volunteers for organizing the conference this year on another channel. Sorry I missed the first meeting. Is there a date set for the next meeting, or something I can help with meanwhile?

**Peter Hickey** (17:39:27) (in thread):
> Thanks, Mahmoud. I’ll DM you a link to a working document.


## 2022-04-01

**Jayaram Kancherla** (00:45:54) (in thread):
> @Peter HickeyI also missed the first meeting but I’m happy to help

**Peter Hickey** (00:52:24) (in thread):
> Thanks, Jayaram. I've emailed you a link to the working document (using the email address in your bioc slack profile)


## 2022-05-02

**Peter Hickey** (20:22:32):
> [https://twitter.com/AsiaR_comm/status/1521281303043186688](https://twitter.com/AsiaR_comm/status/1521281303043186688)@Kozo NishidaSorry I can't join this event on the weekend
  - Attachment (twitter): [Attachment](https://twitter.com/AsiaR_comm/status/1521281303043186688)
> :loudspeaker:Join our next #AsiaR meetup on
> 'Introduction to BioC Asia and how to use {targets} for effective workflows in R'
> 
> Speakers #JapanR
> [@kozo2](https://twitter.com/kozo2) & [@joel_nitta](https://twitter.com/joel_nitta)
> 
> Material [https://github.com/AsiaR-community/2022-bioCasia_targets](https://github.com/AsiaR-community/2022-bioCasia_targets)
> 
> May 7 '22 | 8a UTC | [https://bit.ly/asiar_may2022](https://bit.ly/asiar_may2022)
> RSVP: [https://forms.gle/jkw4dfQj6hdtAuhi9](https://forms.gle/jkw4dfQj6hdtAuhi9)
> #rstats #rladies [https://pbs.twimg.com/media/FRyrbGHVkAA0MDe.jpg](https://pbs.twimg.com/media/FRyrbGHVkAA0MDe.jpg)

**Kozo Nishida** (22:14:09) (in thread):
> I’m sorry too.
> Sorry for the delay in contacting you and Janani.
> I have stopped discussing the BioC Asia 2022 host organization.
> I understand that you (@Peter Hickey) are considering hosting it in ABACBS and@Janani Raviwants to do it in some way related with AsiaR.
> Is my understanding of this correct?

**Janani Ravi** (22:18:14) (in thread):
> I haven’t had a chance to follow-up on this yet!

**Kozo Nishida** (22:18:36) (in thread):
> If the above is correct, I haven't yet come up with the best way to adjust it.
> I also don't know if it's okay to call on host organizations other than ABACBS in my AsiaR presentation above.
> Anyway, I will create the BioC Asia introduction slide ASAP and share it with everyone in this workspace.
> (And I will ask for your opinions.)

**Peter Hickey** (22:19:31) (in thread):
> We had a meeting a couple of weekes ago and decided to run BioC Asia 2022 as a hybrid event as part of ABACBS in November.
> I'm meeting with the ABACBS organisers this week to make further plans to ensure it'll be a successful hybrid event

**Kozo Nishida** (22:23:08) (in thread):
> Thank you Peter. I think it's good for me and the Japanese people.
> Because Japan is still very strict to re-enter the country due to  pandemic.

**Janani Ravi** (22:23:56) (in thread):
> It would make sense to invite AsiaR folks from different countries to partake but since we are coming out of the pandemic, it’s increasingly difficult to rally support & get people to make any kind of time or $$ commitment. We may need to ease into it for 2023!

**Peter Hickey** (22:36:42) (in thread):
> We will hopefully have some funding available to support in-person attendance, but we also know that international travel may still essentially be impossible for people from many countries.
> Promoting the event to the wider AsiaR network and giving people from that network an opportunity to present is high on my list of aims for this meeting.
> We will be seeking ideas to ensure that online attendees don't feel like 'second class citizens' (bad choice of words, I know) to those in-person attendees.


## 2022-05-03

**Janani Ravi** (13:51:44):
> Not sure if there’s a better channel to announce events!
> -------------------
> We are excited to announce our next AsiaR meetup!
> Please join us this Saturday & help spread the word.***Introduction to BioC Asia and how to use {targets} for effective workflows in R******Companion repo***:[https://github.com/AsiaR-community/2022-bioCasia_targets](https://github.com/AsiaR-community/2022-bioCasia_targets):speech_balloon:* On Twitter*?[Please RT](https://twitter.com/AsiaR_comm/status/1521281303043186688).***Featured speakers***-@Kozo Nishida|[https://github.com/kozo2](https://github.com/kozo2)- Joel Nitta |[https://www.joelnitta.com](https://www.joelnitta.com)|[https://github.com/joelnitta](https://github.com/joelnitta)***Event details***May 7, 2022 | 8a UTC / 5p JST | Check your local time:[https://bit.ly/asiar_may2022](https://bit.ly/asiar_may2022):star2:**** How to participate**:star2:1. Fill out the Google Form:[https://forms.gle/jkw4dfQj6hdtAuhi9](https://forms.gle/jkw4dfQj6hdtAuhi9)2. A zoom link will be sent to your email by***May 6, 2022***. Please join via Zoom.:loudspeaker:***** Want to host an event in the future?***********Ple******ase sign up here:[https://bit.ly/asiar_host_2022](https://bit.ly/asiar_host_2022)--------------------***About the Event******Part I: *********Introduction to **********`BioC Asia`******Are you interested in biology and R? R has a package repository for biology called Bioconductor. Bioconductor holds annual conferences in Asia (BioC Asia), Europe (EuroBioC), and the United States (BioC).**Kozo Nishida**will introduce you to what ‘BioC Asia’ looks like in ~10–15 minutes.***Part II: *********How to use {************`targets`************} for effective workflows in R******Have you ever returned to an analysis in R and can’t remember which scripts you need to run and in what order to make things work? Do you want to speed up your analyses with parallelization? Do you want to ensure other people can run your code? The {targets} R package ([https://docs.ropensci.org/targets/](https://docs.ropensci.org/targets/)) can help! {targets} is increasingly becoming the de-facto standard in R for reproducible workflows but can be intimidating for new users to get started.**Joel Nitta**will conduct a short (~1 hr) interactive workshop to introduce participants to the {targets} package for managing workflows in R. Joel has published several analyses (papers) using {targets} and now uses it on a near-daily basis ([https://github.com/joelnitta](https://github.com/joelnitta)). The workshop materials are also available in Japanese ([https://togotv.dbcls.jp/20220331.html](https://togotv.dbcls.jp/20220331.html)).**Prerequisites**: Basic familiarity with R. If you plan to follow along during live coding, please install R, RStudio, and {targets}.
> --------------------


## 2022-05-16

**Batool Almarzouq** (19:22:22):
> @Batool Almarzouq has left the channel

**Batool Almarzouq** (19:22:25):
> @Batool Almarzouq has joined the channel


## 2022-06-08

**Kozo Nishida** (04:26:05):
> @Dario StrbenacSorry for contacting you late. ABACBS will be the hosting institution for this year's BioC Asia.
> And now you can join the organizing committee.
> I made a draft list of the roles.
> If you have a role that you are interested in, please sign up this Slack post.
  - File (Canvas): [BioCAsia2022 organizing committee](https://community-bioc.slack.com/docs/T35G93A5T/F03JR7FHVQB)

**Kozo Nishida** (04:29:45) (in thread):
> If anyone is interested in becoming the BioC Asia 2022 organizing committee, feel free to sign up the Slack post.

**Kozo Nishida** (04:33:21):
> The "website" and "registration" are expected to be almost the same as last year's BioC Asia (See also[https://bioc2022.bioconductor.org/](https://bioc2022.bioconductor.org/)and[https://biocasia2021.bioconductor.org/](https://biocasia2021.bioconductor.org/)).
> So I and@Peter Hickey, who are the same persons as last year, are assigned in the post.
> But if anyone wants to take on these roles, feel free to sign up those fields.
  - Attachment (biocasia2021.bioconductor.org): [BioC Asia 2021](https://biocasia2021.bioconductor.org/)
> Site template made by devcows using hugo

**Kozo Nishida** (04:41:49) (in thread):
> @Dario StrbenacSorry for the delay in replying to you from this message.


## 2022-07-14

**Xueyi Dong** (10:59:35):
> @Xueyi Dong has joined the channel


## 2022-07-29

**Alex Mahmoud** (16:54:47):
> @Alex Mahmoud has joined the channel


## 2022-11-14

**Stevie Pederson** (23:58:55):
> Hi<!channel>. I thought I might get organised & print off some stickers for my packages this year. Is there a recommended hex sticker printer  other BiocAsia people have used?


## 2022-11-15

**Peter Hickey** (00:07:06):
> In Melbourne, we've used[https://classic-colour.com.au/](https://classic-colour.com.au/)for some BioC Asia stuff back in 2019.@Matt Ritchiemight have a more up-to-date recommendation

**Matt Ritchie** (00:07:21):
> @Matt Ritchie has joined the channel

**Peter Hickey** (00:11:51):
> which reminds me to get stickers printed for this year!

**Stevie Pederson** (01:20:38):
> Thanks Peter. I'll given them a try.

**Kozo Nishida** (02:14:48):
> By the way, this year's BioCAsia sticker by Kathleen Zeglinski is[https://github.com/Bioconductor/BiocStickers/tree/master/events/BiocAsia2022](https://github.com/Bioconductor/BiocStickers/tree/master/events/BiocAsia2022).
> (I think that the svg file can create a more beautiful print.)


## 2022-11-16

**Matt Ritchie** (18:53:30) (in thread):
> I went to the same place to get some other stickers printed recently (they’ve moved to East Brunswick though, which is still pretty close by)


## 2023-02-28

**Luyi Tian** (21:59:08):
> @Luyi Tian has joined the channel


## 2023-05-18

**Oluwafemi Oyedele** (05:54:39):
> @Oluwafemi Oyedele has joined the channel


## 2023-08-08

**Ellis Patrick** (16:41:22):
> @Ellis Patrick has joined the channel


## 2023-09-04

**Kozo Nishida** (13:10:09):
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C024SNHU8A3/p1693847396304119)
> For those of you in the Asian time zone and in non-English-speaking regions,
> I'm considering holding a (Carpentries) community session to translate [https://github.com/carpentries-incubator/bioc-intro](https://github.com/carpentries-incubator/bioc-intro)  into your native languages starting at 13:00 Japan time on the Sep 13th.
> Is anyone interested?
> I would like to know how many people are interested and whether it might be necessary to reschedule


## 2023-09-07

**Ellis Patrick** (17:58:28):
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C35G93GJH/p1693496640080559?thread_ts=1693496640.080559&cid=C35G93GJH)
> :mega: BioCAsia2023 abstract submission now open !


## 2023-09-09

**Kozo Nishida** (05:00:18):
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C024SNHU8A3/p1694249987376869?thread_ts=1693847396.304119&cid=C024SNHU8A3)
> > For those of you in the Asian time zone and in non-English-speaking regions,
> > I'm considering holding a (Carpentries) community session to translate [https://github.com/carpentries-incubator/bioc-intro](https://github.com/carpentries-incubator/bioc-intro)  into your native languages starting at 13:00 Japan time on the Sep 13th.
> > Is anyone interested?
> I have decided to postpone this event. (I'm sorry :pray:)
> 
> However, the system to support translation (Crowdin+DeepL+GitHub) is almost fully set up,
> • [https://bioconductor.crowdin.com/bioc-intro](https://bioconductor.crowdin.com/bioc-intro)
> • [https://github.com/bioconductor-translations/bioc-intro-translation/blob/main/crowdin.yml](https://github.com/bioconductor-translations/bioc-intro-translation/blob/main/crowdin.yml)
> • [https://github.com/bioconductor-translations/bioc-intro-translation/tree/l10n_main](https://github.com/bioconductor-translations/bioc-intro-translation/tree/l10n_main)
> and all that's left is to automate the building website (from the translated text).
> 
> If anyone is interested in or wants to try out this translation system, please feel free to reach out to me.


## 2024-04-03

**Kozo Nishida** (11:44:56):
> Hi all,
> Does anyone know who will host BioCAsia2024?
> (If it hasn't been decided yet, ) I would like to ask[https://www.apbjc.asia/](https://www.apbjc.asia/)if they would consider co-hosting BioCAsia2024 with us.
  - Attachment (apbjc.asia): [1st Asia & Paciﬁc Bioinformatics Joint Conference ～JSBi, GIW, InCoB, APBC, and ISCB-Asia～ (APBJC 2024)](https://www.apbjc.asia/)
> Dates: 22Tue -25Fri October 2024　Venue: Okinawa, JAPAN　Conference Chairs: Wataru Iwasaki (The University of Tokyo), Kiyoko F. Aoki-Kinoshita (Soka University)


## 2024-04-09

**Dario Strbenac** (01:00:01):
> It will be co-hosted with A.B.A.CB.S. in Sydney, Australia. It would be great to see it in Japan soon, though.

**Stevie Pederson** (03:00:31) (in thread):
> Oh thanks Dario. That's really good to know. Are you the convenor, or is Ellis heading it up again?

**Dario Strbenac** (03:00:52) (in thread):
> Ellis.

**Stevie Pederson** (03:01:55) (in thread):
> He's gonna be busy then:joy:

**Kozo Nishida** (04:57:20) (in thread):
> Thank you for the information, Dario.:pray:


## 2024-05-03

**stefano mangiola** (05:04:36):
> @stefano mangiola has joined the channel


## 2024-05-14

**Ellis Patrick** (01:04:32) (in thread):
> Are you volunteering@Stevie Pederson?

**Ellis Patrick** (01:05:24) (in thread):
> Arguably, apbjc might be a great option to provide BioC visability

**Ellis Patrick** (01:07:41) (in thread):
> We can run some bioconductor workshops + developer meet-up at ABACBS without it being the official biocasia2024

**Stevie Pederson** (01:40:37) (in thread):
> Hmm. Timeline might be a bit tight for a Japan Bioc24. I probably wouldn't have the travel budget to go to Japan but it would be great to see if it's viable. Any thoughts@Kozo Nishida?
> 
> The CAB has been intermittently discussing the idea of workshops at conferences too so running some with ABACBS is definitely worth exploring if the conference goes to Japan.
> 
> Happy to join the organising group too if you're recruiting...


## 2024-05-19

**Ellis Patrick** (17:23:46) (in thread):
> @stefano mangiolatagging you here:slightly_smiling_face:

**stefano mangiola** (18:10:36) (in thread):
> I could definitely help with the organisation of Bioc workshop session.


## 2024-05-23

**stefano mangiola** (23:12:39) (in thread):
> @Stevie Pedersondo you want to have a short chat about all this?


## 2024-05-24

**Stevie Pederson** (02:37:47) (in thread):
> Sounds good. Next week sometime?

**stefano mangiola** (02:56:13) (in thread):
> Tue 2PM?

**Stevie Pederson** (03:03:09) (in thread):
> Yep! Abbots & Kinney across the road?


## 2024-06-03

**Stevie Pederson** (22:42:40):
> Hi<!channel>. The BiocAsia conference organising group is currently being put together. We'd absolutely love for anyone who's keen to help to be involved. The 2024 event is likely to be held in Sydney, this November. Please contact@stefano mangiola@Ellis Patrickor@Stevie Pedersonif you're keen to help out.


## 2024-06-04

**Tuomas Borman** (01:29:06):
> @Tuomas Borman has joined the channel

**stefano mangiola** (03:19:33):
> tagging@Jiya Chaudharywho is an intern at Bioconductor and expressed interest in contributing to the organisation of BiocAsia

**Jiya Chaudhary** (03:19:46):
> @Jiya Chaudhary has joined the channel

**Peace Sandy** (06:41:50):
> @Peace Sandy has joined the channel

**irem Kahveci** (07:58:22):
> @irem Kahveci has joined the channel


## 2024-06-06

**Jiya Chaudhary** (02:15:31):
> Hello all, excited to be a part of BiocAsia :))


## 2024-06-09

**Saejeong Park** (10:23:36):
> @Saejeong Park has joined the channel


## 2024-06-13

**Shinji Tokunaga** (01:48:38):
> @Shinji Tokunaga has joined the channel


## 2024-06-16

**Kozo Nishida** (04:40:58) (in thread):
> Sorry for the late reply.
> It does not look like I can organize a Bioconductor workshop [instead of BioCAsia] at apbjc.
> (I have been quite busy recently and have not been able to reply to this community...)
> Instead of the above,
> I would like to submit a talk abstract [about#education-and-training]to[https://www.apbjc.asia/call-for-submission.html](https://www.apbjc.asia/call-for-submission.html).
> Bioconductor plans to make the Carpentries-style teaching materials available in multiple languages and to provide education in local languages.


## 2024-07-08

**Maria Doyle** (16:54:34):
> Hi everyone,
> 
> I wanted to share an opportunity to participate in the Australian Outpost of the ELIXIR BioHackathon, happening this November 4-8. This international event brings together bioinformatics professionals to enhance the interoperability, accessibility, and reusability of bioinformatics tools.
> 
> Australian BioCommons wants to support people in Australia who can’t attend the BioHackathon in person in Barcelona to still contribute meaningfully, including to our project on increasing the findability of Bioconductor packages and improving EDAM ontology. Our project is one of the identified projects for the Australian Outpost.
> 
> Even if you’re not based in Australia, you might know someone who could be interested. Additionally, remote participation from outside Australia is also possible. Note this event coincides with the ABACBS conference dates (November 5-6) and associated satellite events.
> 
> If you’re interested or know someone who might be, please let me know! More info about the call for participation:[BioHackathon Europe Call 2024](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biocommons.org.au%2Fnews%2Fbiohack-call2024&data=05%7C02%7CMaria.Doyle%40ul.ie%7C9243b7fb051a411e62c408dc9cb0180c%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638557527339032332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=rIZzk9ylEScnvTODRWKFDauU63e8egZBYtOwEIrtLvA%3D&reserved=0). The deadline is***August 9th***.
> 
> Happy to answer any questions or provide more details.
  - Attachment (Australian BioCommons): [Join the Australian Outpost of BioHackathon Europe 2024! — Australian BioCommons](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biocommons.org.au%2Fnews%2Fbiohack-call2024&amp;data=05%7C02%7CMaria.Doyle%40ul.ie%7C9243b7fb051a411e62c408dc9cb0180c%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638557527339032332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&amp;sdata=rIZzk9ylEScnvTODRWKFDauU63e8egZBYtOwEIrtLvA%3D&amp;reserved=0)
> Are you interested in joining this year’s BioHackathon Europe, but can’t face the long haul flights? You should join the Australian Outpost team who will gather to work locally, while checking in regularly with our international colleagues.


## 2024-07-24

**Kozo Nishida** (03:31:14) (in thread):
> I am interested in participating in it remotely.
> What actions, if any, should I take to do it?


## 2024-07-25

**Maria Doyle** (16:44:41) (in thread):
> Great Kozo, you can register to attend the BioHackathon virtually through this page[https://biohackathon-europe.org/registration/](https://biohackathon-europe.org/registration/)


## 2024-07-29

**Kozo Nishida** (04:37:04) (in thread):
> Thanks Maria, I registered through that page.


## 2024-08-22

**Maria Doyle** (04:50:52):
> :mega:***BioCAsia 2024 Abstract Deadline - August 26th***Hi everyone, Just a quick heads-up that the abstract submission deadline for BioCAsia 2024 is approaching soon. If you’re planning to present your research at the conference in Sydney, Australia:flag-au:, on November 7-8, make sure to submit your abstract by***this Monday, August 26th, at 11:59 PM (AEST)***.
> 
> You can submit your abstract here:[BioCAsia 2024 Submission Page](https://biocasia2024.bioconductor.org/submissions/).
> 
> Looking forward to seeing your contributions!


## 2024-08-27

**Maria Doyle** (08:06:25):
> :mega:𝗥𝗲𝗴𝗶𝘀𝘁𝗿𝗮𝘁𝗶𝗼𝗻 𝗳𝗼𝗿 𝗕𝗶𝗼𝗖𝗔𝘀𝗶𝗮 𝟮𝟬𝟮𝟰 𝗶𝘀 𝗻𝗼𝘄 𝗼𝗽𝗲𝗻!
> 
> Join a key event connecting the bioinformatics community.:point_right:Register here:[https://buff.ly/4cEmcIj](https://buff.ly/4cEmcIj)**Note: BioCAsia registration is available separately if you’re not attending ABACBS. If attending ABACBS, select ‘ABACBS Full’ or ‘ABACBS Student’ to add BioCAsia during the process.**Feel free to share the[LinkedIn](https://www.linkedin.com/posts/bioconductor_biocasia2024-bioinformatics-rstats-activity-7234168024713342976-jiIO)or[Mastodon](https://genomic.social/@bioconductor/113033872307553730)posts.


## 2024-08-28

**Maria Doyle** (07:08:38) (in thread):
> :money_with_wings:Just a heads-up! The “Conference Access Award” is available to help cover your BioCAsia registration fee. If you’re presenting or participating and need support, consider applying here:[https://biocasia2024.bioconductor.org/submissions/](https://biocasia2024.bioconductor.org/submissions/)


## 2024-09-11

**Alex Qin** (19:48:42):
> @Alex Qin has joined the channel


## 2024-11-06

**Davide Risso** (02:20:12):
> @Davide Risso has joined the channel

**Ellis Patrick** (21:38:07):
> If anyone wants to zoom in you can join by this link[https://uni-sydney.zoom.us/j/87583095352](https://uni-sydney.zoom.us/j/87583095352)

**Ellis Patrick** (21:38:15):
> <!here>

**Kozo Nishida** (21:41:15) (in thread):
> Hi Ellis,
> that Zoom link requires a University of Sydney sign-in, so it seems that the general public won't be able to join.

**Ellis Patrick** (21:48:45) (in thread):
> Are you sure it requires a sign in? You should just need to input the same email that you are using to sign into zoom.

**Kozo Nishida** (21:54:32) (in thread):
> Is that the email that is used to register for BioCAsia? If so, I don't think I registered.

**Ellis Patrick** (21:55:02) (in thread):
> No, the email of your zoom account.

**Michael Nakai** (21:58:05):
> @Michael Nakai has joined the channel

**Kozo Nishida** (21:59:30) (in thread):
> Ah, sorry, I hadn't signed in to my Zoom account yet.
> Therefore, I was not able to proceed to the step where I input the email.
> Now I can access BioCAsia Zoom without any problems. Apologies for the trouble.

**Shila Ghazanfar** (22:08:01):
> @Shila Ghazanfar has joined the channel

**Sam El-Kamand** (22:08:27):
> @Sam El-Kamand has joined the channel

**Pratibha Panwar** (22:09:06):
> @Pratibha Panwar has joined the channel


## 2024-11-08

**Kozo Nishida** (08:24:57):
> This is the Google Slides I used in my BioCAsia talk today.[https://docs.google.com/presentation/d/1Fi7tuhGHh1xkl3zOs4Hf4vL6kSXj7A702R5UdVmTxHQ/edit?usp=sharing](https://docs.google.com/presentation/d/1Fi7tuhGHh1xkl3zOs4Hf4vL6kSXj7A702R5UdVmTxHQ/edit?usp=sharing)
  - File (Google Slides): [Carpentries to promote Bioconductor (BioCAsia2024)](https://community-bioc.slack.com/files/U34P8RS3B/F08027XHMMG/carpentries_to_promote_bioconductor__biocasia2024_)


## 2024-11-10

**Connie Li Wai Suen** (18:13:58):
> @Connie Li Wai Suen has joined the channel

**Connie Li Wai Suen** (18:16:03):
> @Connie Li Wai Suen has left the channel


## 2025-03-17

**stefano mangiola** (02:19:35):
> ***Hello Everyone,***This morning, we had a great chat with@Stevie Pedersonabout the exciting future of the***BiocAsia community***. We discussed the importance of having an organised effort to boost community engagement and thought giving it an official name would help highlight its significance:***BiocAsia Engagement Initiative***As a first practical goal (with a 1-month timeline), we suggest identifying 1–2 enthusiastic**** “Engagement Champions”****from each major region in Asia-Pacific, such as:
> 	•	Japan
> 	•	China
> 	•	India
> 	•	Singapore
> 	•	South-east Asia
> 	•	New Zealand
> 	•	Hong Kong
> 	•	Australia (though we’re already quite active!)
> 	•**(Feel free to propose more!)**These Engagement Champions would help drive community engagement with clear responsibilities we can define together. Some initial ideas include:
> 	•	Gathering participation and outreach across local institutions
> 	•	Defining requirements for digital platforms
> 	•	Identifying potential sponsors for the BiocAsia conference
> 
> Once we collectively agree on these roles, we can begin identifying community members interested in taking on this meaningful, long-term commitment.
> 
> We’d love your thoughts on this! Please share your feedback and any additional suggestions you may have.

**stefano mangiola** (18:38:39) (in thread):
> Tagging@Vince Careyfor knowledge and feedback


## 2025-04-08

**Lijia Yu** (09:13:55):
> @Lijia Yu has joined the channel
