---
title: "#calendar-events"
format: gfm
---

## 2022-02-12

**Kozo Nishida** (16:22:10):
> @Kozo Nishida has joined the channel

**Kozo Nishida** (16:22:11):
> set the channel description: This channel collects bioc-related events info around the world and shares it on Google calendar.

**Lori Shepherd** (16:22:27):
> @Lori Shepherd has joined the channel

**Kozo Nishida** (16:23:38):
> set the channel description: This channel collects bioc-related event information around the world and shares it on Google calendar.


## 2022-02-23

**Paulina Paiz** (10:45:11):
> @Paulina Paiz has joined the channel


## 2022-05-16

**Batool Almarzouq** (19:22:19):
> @Batool Almarzouq has joined the channel


## 2022-06-01

**Mikie Phan** (09:59:04):
> @Mikie Phan has joined the channel


## 2022-07-14

**Madelyn Carlson** (12:03:53):
> @Madelyn Carlson has joined the channel


## 2022-07-22

**Gary Sieling** (14:48:22):
> @Gary Sieling has joined the channel


## 2022-07-31

**Arda Keles** (04:11:35):
> @Arda Keles has joined the channel


## 2022-08-31

**Kozo Nishida** (14:17:41):
> [https://twitter.com/Bioconductor/status/1565015905918021632](https://twitter.com/Bioconductor/status/1565015905918021632)
  - Attachment (twitter): [Attachment](https://twitter.com/Bioconductor/status/1565015905918021632)
> "Bioconductor Teaching Week 2022
> 06 - 08 September 2022 — virtual"
> has been added to the Bioconductor Event calendar.
> [http://bioconductor.org/help/events/](http://bioconductor.org/help/events/)
> See below for more information.
> [https://support.bioconductor.org/p/9146055/](https://support.bioconductor.org/p/9146055/)


## 2022-12-12

**Lexi Bounds** (17:57:46):
> @Lexi Bounds has joined the channel


## 2023-01-18

**José Basílio** (13:09:23):
> @José Basílio has joined the channel


## 2023-01-31

**Rebecca Butler** (15:07:26):
> @Rebecca Butler has joined the channel


## 2023-02-28

**Krithika Bhuvanesh** (16:53:23):
> @Krithika Bhuvanesh has joined the channel


## 2023-06-19

**Pierre-Paul Axisa** (05:09:54):
> @Pierre-Paul Axisa has joined the channel


## 2023-08-01

**Nikhil Mane** (09:12:38):
> @Nikhil Mane has joined the channel


## 2023-08-04

**Trisha Timpug** (09:35:01):
> @Trisha Timpug has joined the channel


## 2023-09-04

**Anna Lewkowicz** (16:50:42):
> @Anna Lewkowicz has joined the channel


## 2024-03-11

**Melysssa Minto** (10:09:11):
> @Melysssa Minto has joined the channel


## 2024-05-14

**Lori Shepherd** (10:24:49):
> archived the channel
