---
title: "#cancer-related"
---

## 2022-05-10

**Sean Davis** (14:48:04):
> @Sean Davis has joined the channel

**Sean Davis** (14:48:04):
> set the channel description: Discuss cancer-related data, resources, tools, algorithms, and opportunities

**Sean Davis** (14:48:18):
> [https://events.cancer.gov/hdrp/machinelearning](https://events.cancer.gov/hdrp/machinelearning)
  - Attachment (events.cancer.gov): [Machine Learning and Health Outcomes in Cancer Care Delivery Research (Overview) | Events Registration](https://events.cancer.gov/hdrp/machinelearning)
> Overview The National Cancer Institute is conducting a Machine Learning and Health Outcomes in Cancer Care Delivery Research virtual workshop from May 16-17, 2022 focused on research in machine learning, cancer care delivery, and health outcomes. The goals are to identify scientific gaps, barriers, and opportunities in this emerging area of cancer-focused healthcare research.

**Umar Ahmad** (17:58:51):
> @Umar Ahmad has joined the channel


## 2022-05-11

**Daniel Adediran** (12:04:58):
> @Daniel Adediran has joined the channel


## 2022-07-28

**Krithika Bhuvanesh** (13:52:02):
> @Krithika Bhuvanesh has joined the channel


## 2022-10-10

**Mercilena Benjamin** (13:55:30):
> @Mercilena Benjamin has joined the channel


## 2022-12-20

**Krithika Bhuvanesh** (13:24:34):
> @Krithika Bhuvanesh has left the channel


## 2023-01-18

**José Basílio** (13:09:24):
> @José Basílio has joined the channel


## 2023-01-21

**Hien** (16:01:50):
> @Hien has joined the channel


## 2023-01-31

**Ahmad Al Ajami** (08:18:35):
> @Ahmad Al Ajami has joined the channel


## 2023-02-09

**Wes W** (22:03:17):
> @Wes W has joined the channel


## 2023-03-01

**jeremymchacón** (12:11:54):
> @jeremymchacón has joined the channel


## 2023-03-31

**Ilaria Billato** (08:56:19):
> @Ilaria Billato has joined the channel


## 2023-05-31

**Alyssa Obermayer** (14:14:19):
> @Alyssa Obermayer has joined the channel


## 2023-06-07

**Alyssa Obermayer** (18:28:39):
> @Alyssa Obermayer has joined the channel


## 2023-06-09

**Aedin Culhane** (17:25:07):
> @Aedin Culhane has joined the channel


## 2023-06-19

**Pierre-Paul Axisa** (05:09:50):
> @Pierre-Paul Axisa has joined the channel


## 2023-08-04

**Trisha Timpug** (09:35:00):
> @Trisha Timpug has joined the channel


## 2023-09-15

**Leo Lahti** (04:53:55):
> @Leo Lahti has joined the channel

**Leo Lahti** (04:53:57):
> @Leo Lahti has left the channel


## 2023-11-11

**António Domingues** (16:35:54):
> @António Domingues has joined the channel


## 2024-05-18

**Aedin Culhane** (10:52:01):
> Is there a list of cancer related resources in Bioconductor.Is this a review article this group could consider


## 2024-06-27

**Wes W** (09:56:52):
> as a cancer reseacher i'd be down to put something together like this


## 2024-07-11

**Sathish Kumar** (06:04:38):
> @Sathish Kumar has joined the channel


## 2024-10-21

**Zahraa W Alsafwani** (19:02:18):
> @Zahraa W Alsafwani has joined the channel


## 2024-11-18

**Lucio Queiroz** (14:52:54):
> @Lucio Queiroz has joined the channel


## 2024-12-05

**Aedin Culhane** (06:35:58):
> We are delighted to invite you to the All Island Forum on Cancer Data on January 14th and would be delighted if you could share our announcement with colleagues and partners.
> 
> On January 14th***eHealth-Hub for Cancer ***will host an***All Island Forum on Cancer Data***at the***University of Limerick***. Registration is free. Register on eventbrite[here](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.eventbrite.com%2Fe%2Fthe-all-island-forum-on-cancer-data-tickets-1080248796229%3Faff%3Doddtdtcreator&data=05%7C02%7CAedin.Culhane%40ul.ie%7C5f0893a17a724149ea3b08dd1476d8f5%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638689223511206638%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=lN%2FHZxm0FdBVzTa2tOlcB%2B%2FJ9wO1pdbPpZvj4B12I0o%3D&reserved=0). Please submit[Abstracts](https://app.oxfordabstracts.com/stages/77261/submitter)before December 18th.
> 
> This conference will bring together international and all-island clinical, academic and industry leaders to discuss how to connect, access and analyse clinical and genomics cancer data across institutes and hospitals.
> 
> Confirmed speakers include;***Gianpiero Cavalleri,***Professor of Human Genetics, RCSI***Geoff Hall***, Professor of Digital Health, Leeds University***Paul Nagy***, Assoc Professor at Bloomberg School of Public Health, Director Informatics and Data Science, Johns Hopkins University***Xose Fernandez***, Head Digital Oncology Network for Europe, IQVIA***Lesley Anderson***, Professor in Health Data Science, University of Aberdeen***Martin Curley***, Professor of Innovation, Maynooth University and Digital Health Leader***Angela Clayton-Lea***, Chief Operations Officer at Cancer Trials Ireland***Giles Ducorroy,***Head Global Real World Evidence Services at Novartis
> 
> Forum themes include
> •Case studies of successful federated cancer research
> •Real-World Evidence in Cancer Research
> •Data Innovation for All-Island Clinical Trials
> •Leveraging electronic health records for cancer insights
> •Cancer Genomics and Precision Medicine
> •Data driven cancer policy
> 
> Registration for the forum is free, please[Register](https://www.eventbrite.com/e/the-all-island-forum-on-cancer-data-tickets-1080248796229#:~:text=The%20All%20Island%20Forum%20on%20Cancer%20Data%20is%20hosted%20by,advance%20research%20and%20benefit%20patients.). on eventbrite
> Please submit[Abstracts](https://app.oxfordabstracts.com/stages/77261/submitter)before December 18th.
  - Attachment (Eventbrite): [The All Island Forum on Cancer Data](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.eventbrite.com%2Fe%2Fthe-all-island-forum-on-cancer-data-tickets-1080248796229%3Faff%3Doddtdtcreator&amp;data=05%7C02%7CAedin.Culhane%40ul.ie%7C5f0893a17a724149ea3b08dd1476d8f5%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638689223511206638%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&amp;sdata=lN%2FHZxm0FdBVzTa2tOlcB%2B%2FJ9wO1pdbPpZvj4B12I0o%3D&amp;reserved=0)
> Hosted by the eHealth-Hub for Cancer, University of Limerick and Queens University Belfast.
  - Attachment (Eventbrite): [The All Island Forum on Cancer Data](https://www.eventbrite.com/e/the-all-island-forum-on-cancer-data-tickets-1080248796229#:~:text=The%20All%20Island%20Forum%20on%20Cancer%20Data%20is%20hosted%20by,advance%20research%20and%20benefit%20patients.)
> Hosted by the eHealth-Hub for Cancer, University of Limerick and Queens University Belfast.

**Zahraa W Alsafwani** (16:40:38) (in thread):
> Is there an option to attend virtually?


## 2024-12-11

**joe mcconnell** (17:42:32):
> @joe mcconnell has joined the channel


## 2025-01-18

**Wanling Kratzman** (09:08:22):
> @Wanling Kratzman has joined the channel


## 2025-03-25

**Lama Salem** (09:19:47):
> @Lama Salem has joined the channel

**Lama Salem** (09:20:46):
> @Lama Salem has left the channel
