---
title: "#channel-requests"
format: gfm
---


## 2024-05-10

*13:48:09 - @Lori Shepherd has joined the channel*
**Lori Shepherd** (13:49:22):
> set the channel description: Channel creation is limited to workspace owners and administrators.  Please make a request to start a new channel here with a description/reasoning for its creation.

*13:50:28 - @Maria Doyle has joined the channel*
*13:50:40 - @Marcel Ramos Pérez has joined the channel*
*13:50:48 - @Vince Carey has joined the channel*
*13:51:05 - @Levi Waldron has joined the channel*
*13:51:11 - @Sean Davis has joined the channel*

## 2024-05-14

*12:49:51 - @Charlotte Soneson has joined the channel*

## 2024-05-15

*02:16:08 - @Malte Thodberg has joined the channel*
**Maria Doyle** (09:42:25):
> Hi everyone,
> At the most recent CAB meeting, we proposed creating a new channel called #upcoming-conferences for sharing information about attending events. However, I’m considering a simpler name like #events, which people can use for both advertising events and letting others know if they’re attending, in case they want to meet up with other Bioconductor community members.
> I’ve asked the CAB for their feedback on this name change. In the meantime, I’d love to hear your thoughts as well. I’ll wait 24 hours for feedback before proceeding with creating #events if there are no objections.


## 2024-05-27

*21:18:32 - @Aedin Culhane has joined the channel*
**Aedin Culhane** (21:19:34):
> Should we have a channel on AI research and tools for bioconductior.  #AI


## 2024-05-28

**Vince Carey** (06:09:32):
> yes, please go ahead


## 2024-05-31

*15:55:03 - @irem Kahveci has joined the channel*
*17:50:08 - @Hervé Pagès has joined the channel*
**Hervé Pagès** (17:54:33):
> I'd like to create a new**private**channel for a few selected members, including@Erdal Cosgun, to discuss topics related to our build machines on the Azure cloud. Since we might exchange sensitive information, we need the channel to be private. I don't seem to have the permission to create a new channel. Can someone on this channel help me? Thanks


## 2024-06-04

**Hervé Pagès** (12:08:39):
> @Vince Careycreated the new channel (<#C07618TBKQD>). Thanks everyone.


## 2024-06-10

*13:44:00 - @Alik Huseynov has joined the channel*

## 2024-06-16

**Aedin Culhane** (10:22:18) (in thread):
> Didn’t because there is a#machine-learningchannel.  Should that  be AI and ML.


## 2024-06-17

**Vince Carey** (07:11:39) (in thread):
> sounds good to me


## 2024-06-24

*01:32:29 - @Stevie Pederson has joined the channel*
**Stevie Pederson** (01:35:31):
> Hi. I'd like to create a new private channel called biocasia-conf-committee. Will I be able to add people later or should I list them here?

**Lori Shepherd** (09:09:21) (in thread):
> you'll be able to add later --  would it be okay to do "biocasia-conference-organization"  to keep it consistent with the other two (eurobioc-conference-organization and bioc-conference-organization)

**Stevie Pederson** (09:10:14) (in thread):
> For sure! That sounds good to me. Thanks Lori

**Lori Shepherd** (09:12:14) (in thread):
> created.  let me know if you cannot add members yourself

**Stevie Pederson** (09:14:35) (in thread):
> Fabulous. All seems to have worked rather nicely. Thanks again


## 2024-07-26

*10:44:48 - @Alex Mahmoud has joined the channel*
**Alex Mahmoud** (10:45:13):
> Requesting #singularity public channel to discuss singularity developments/containers

**Maria Doyle** (10:46:23) (in thread):
> I’ll create

**Maria Doyle** (10:47:32) (in thread):
> created now here#singularity


## 2024-08-08

*04:23:45 - @Vilhelm Suksi has joined the channel*
**Vilhelm Suksi** (04:26:13):
> Hi! I'd like to have a private channel created for the notame package to facilitate collaboration. #notame for example. We're planning to submit it for the next Bioconductor release. Thanks!

**Lori Shepherd** (09:47:49):
> We like to avoid having specialized channels for packages.  Is it possible to use an existing channel that the package focuses on for open collaboration? for instance we have channels for mass-spectrometry, metabolomics, proteomics, singlecell-queries ? if it is entirely necessary, we would encourage an open not private channel for collaboration.


## 2024-08-09

**Vilhelm Suksi** (01:12:47) (in thread):
> We'll settle for another solution. Thanks!


## 2024-10-29

**Alex Mahmoud** (13:10:36):
> Could I please get a new #gitdevtest channel to communicate with volunteer dev testers for the new github source? I was starting with a DM, but figured a channel would be better as the group grows

**Marcel Ramos Pérez** (13:11:21):
> Done


## 2025-01-02

*00:53:10 - @George Kitundu has joined the channel*

## 2025-03-20

*10:03:26 - @Kehinde Kilanko has joined the channel*