---
title: "#clinical"
---

## 2020-09-01

**Sean Davis** (13:04:39):
> @Sean Davis has joined the channel

**Sean Davis** (13:04:39):
> set the channel description: Discuss clinical applications and standards

**Vince Carey** (13:05:52):
> @Vince Carey has joined the channel

**Levi Waldron** (13:05:52):
> @Levi Waldron has joined the channel

**Leonardo Collado Torres** (13:05:52):
> @Leonardo Collado Torres has joined the channel

**Benjamin Haibe-Kains** (13:05:52):
> @Benjamin Haibe-Kains has joined the channel

**Aedin Culhane** (13:05:52):
> @Aedin Culhane has joined the channel

**Sean Davis** (13:05:58):
> [https://github.com/FirelyTeam/RonFHIR](https://github.com/FirelyTeam/RonFHIR)

**Sean Davis** (13:06:29):
> Just wanted to seed a place to discuss clinical and clinical-touching applications.


## 2020-10-21

**Kevin Blighe** (13:34:37):
> @Kevin Blighe has joined the channel


## 2020-10-23

**Rebecca Howard** (08:17:38):
> @Rebecca Howard has joined the channel

**ImranF** (11:42:35):
> @ImranF has joined the channel


## 2020-11-16

**Robert Castelo** (05:17:42):
> @Robert Castelo has joined the channel


## 2020-11-19

**Kevin Blighe** (08:29:24):
> @Kevin Blighe has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:42:15):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-23

**Wynn Cheung** (10:32:26):
> @Wynn Cheung has joined the channel

**Wynn Cheung** (10:32:27):
> @Wynn Cheung has left the channel


## 2021-02-24

**Kyle Alford** (11:40:21):
> @Kyle Alford has joined the channel


## 2021-03-20

**watanabe_st** (01:57:02):
> @watanabe_st has joined the channel


## 2021-05-23

**Jonas Schulte-Schrepping** (08:10:01):
> @Jonas Schulte-Schrepping has joined the channel


## 2021-05-28

**Izaskun Mallona** (10:15:29):
> @Izaskun Mallona has joined the channel


## 2021-08-05

**Ambarish S. Ghatpande** (05:37:34):
> @Ambarish S. Ghatpande has joined the channel


## 2021-08-15

**KP** (01:40:44):
> @KP has joined the channel


## 2021-11-08

**Paula Nieto García** (03:26:17):
> @Paula Nieto García has joined the channel


## 2021-12-07

**Jenny Smith** (15:20:31):
> @Jenny Smith has joined the channel


## 2022-04-12

**Vivian Chu** (13:59:09):
> @Vivian Chu has joined the channel


## 2022-05-10

**Sean Davis** (14:48:40):
> [https://events.cancer.gov/hdrp/machinelearning](https://events.cancer.gov/hdrp/machinelearning)
  - Attachment (events.cancer.gov): [Machine Learning and Health Outcomes in Cancer Care Delivery Research (Overview) | Events Registration](https://events.cancer.gov/hdrp/machinelearning)
> Overview The National Cancer Institute is conducting a Machine Learning and Health Outcomes in Cancer Care Delivery Research virtual workshop from May 16-17, 2022 focused on research in machine learning, cancer care delivery, and health outcomes. The goals are to identify scientific gaps, barriers, and opportunities in this emerging area of cancer-focused healthcare research.

**Umar Ahmad** (17:58:55):
> @Umar Ahmad has joined the channel


## 2022-07-22

**Gary Sieling** (14:48:15):
> @Gary Sieling has joined the channel


## 2022-07-28

**Krithika Bhuvanesh** (13:52:05):
> @Krithika Bhuvanesh has joined the channel


## 2022-08-26

**Connor Higgins** (21:04:30):
> @Connor Higgins has joined the channel


## 2022-10-04

**Aedin Culhane** (20:12:03):
> @Sean Davis[https://esciencelab.org.uk/projects/eosc4cancer/](https://esciencelab.org.uk/projects/eosc4cancer/)
  - Attachment (esciencelab.org.uk): [EOSC4Cancer](https://esciencelab.org.uk/projects/eosc4cancer/)
> Funded by call HORIZON-INFRA-2021-EOSC-01-06 101058427, EOSC4Cancer will provide a federated infrastructure for the exploitation of cancer data for the EU Ca...

**Aedin Culhane** (20:17:05):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F044YSJDMB8/image.png)

**Aedin Culhane** (20:17:48):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F0455FDT38A/image.png)

**Aedin Culhane** (20:20:09):
  - File (PNG): [Screenshot 2022-10-05 at 01.19.18.png](https://community-bioc.slack.com/files/U34P8RS3B/F0455FKQ80J/screenshot_2022-10-05_at_01.19.18.png)

**Aedin Culhane** (20:20:22):
> [https://pharmaverse.org](https://pharmaverse.org)
  - Attachment (pharmaverse.org): [pharmaverse](https://pharmaverse.org)
> This is meta description

**Aedin Culhane** (20:22:45):
> [http://openpharma.github.io](http://openpharma.github.io)


## 2022-10-06

**Alan Aw** (19:27:39):
> @Alan Aw has joined the channel

**kipper fletez-brant** (19:27:54):
> @kipper fletez-brant has joined the channel

**Amarinder Singh Thind** (19:40:35):
> @Amarinder Singh Thind has joined the channel

**Samuel Gamboa** (20:45:32):
> @Samuel Gamboa has joined the channel

**Spencer Nystrom** (20:47:45):
> @Spencer Nystrom has joined the channel

**Ana Beatriz Villaseñor Altamirano** (21:02:34):
> @Ana Beatriz Villaseñor Altamirano has joined the channel

**Jonathan Carroll** (21:36:55):
> @Jonathan Carroll has joined the channel

**Indrik Wijaya** (22:03:43):
> @Indrik Wijaya has joined the channel

**Marouen Ben Guebila** (23:46:01):
> @Marouen Ben Guebila has joined the channel


## 2022-10-07

**Alan Murphy** (01:25:55):
> @Alan Murphy has joined the channel

**Lluís Revilla** (02:50:14):
> @Lluís Revilla has joined the channel

**Stephany Orjuela** (03:26:36):
> @Stephany Orjuela has joined the channel

**Alvaro Sanchez** (11:22:23):
> @Alvaro Sanchez has joined the channel

**Vince Carey** (17:36:20):
> Here's a very rudimentary exploration of FHIR:[https://vjcitn.github.io/BiocFHIR](https://vjcitn.github.io/BiocFHIR)
  - Attachment (vjcitn.github.io): [Illustration of FHIR ingestion and transformation using R](https://vjcitn.github.io/BiocFHIR)
> FHIR R4 bundles in JSON format are derived from [https://synthea.mitre.org/downloads](https://synthea.mitre.org/downloads). Transformation inspired by a kaggle notebook published by Dr Alexander Scarlat, [https://www.kaggle.com/code/drscarlat/fhir-starter-parse-healthcare-bundles-into-tables](https://www.kaggle.com/code/drscarlat/fhir-starter-parse-healthcare-bundles-into-tables).

**Vince Carey** (17:38:05):
> Any FHIR experts should not hold back -- this is technically extremely limited.  But I would like it to be a basis for introducing better interrogation and integration technologies in the context of the synthea data and any other public collections.


## 2022-10-08

**Taku Iwaki** (17:47:26):
> @Taku Iwaki has joined the channel


## 2022-10-09

**Adam Stevens** (17:19:13):
> @Adam Stevens has joined the channel


## 2022-10-10

**Mercilena Benjamin** (13:55:35):
> @Mercilena Benjamin has joined the channel


## 2022-10-17

**Spencer Nystrom** (10:20:39):
> Not necessarily a Bioc question, but maybe someone here knows. Are DAIDS criteria defined/vendored in a json or other schema somewhere? All I can dig up are the NIAID PDFs with the criteria in plain text....

**Vince Carey** (11:55:19):
> criteria for AIDS or AIDS-related syndromes?  i used to work on HIV clinical trials and know some people at NIAID but what exactly do you need?  what are the pdf links?

**Spencer Nystrom** (16:53:01):
> Ah, sorry. DAIDS grading is criteria for evaluating severity grades of adverse events.[https://rsc.niaid.nih.gov/clinical-research-sites/daids-adverse-event-grading-tables](https://rsc.niaid.nih.gov/clinical-research-sites/daids-adverse-event-grading-tables)For example in this pdf it describes lab value ranges that correspond to different clinical severity levels.[https://rsc.niaid.nih.gov/sites/default/files/daidsgradingcorrectedv21.pdf](https://rsc.niaid.nih.gov/sites/default/files/daidsgradingcorrectedv21.pdf)I was hoping to find a csv file or something that had these criteria to do automated data classifications.


## 2022-10-18

**Vince Carey** (22:21:38):
> @Spencer Nystromthe answer appears to be negative.  I tried to register at the regulatory support center
> but their registration page is messed up for non-NIH users.  If you would like to pursue this further let's discuss in DM.


## 2022-10-19

**Spencer Nystrom** (06:46:09):
> Thanks for giving it a shot, Vince! Really appreciate it.


## 2022-10-24

**Filip Stachura** (10:44:10):
> @Filip Stachura has joined the channel


## 2022-11-17

**Konstantinos Geles (Constantinos Yeles)** (17:26:57):
> @Konstantinos Geles (Constantinos Yeles) has joined the channel


## 2023-01-18

**José Basílio** (13:09:28):
> @José Basílio has joined the channel


## 2023-01-31

**Rebecca Butler** (15:07:38):
> @Rebecca Butler has joined the channel


## 2023-02-28

**Ramin** (15:31:11):
> @Ramin has joined the channel


## 2023-03-15

**Amarinder Singh Thind** (01:45:36):
> @Amarinder Singh Thind has left the channel


## 2023-04-28

**Vince Carey** (16:05:08):
> @Vince Carey has left the channel


## 2023-05-18

**Oluwafemi Oyedele** (05:54:51):
> @Oluwafemi Oyedele has joined the channel


## 2023-06-19

**Pierre-Paul Axisa** (05:09:58):
> @Pierre-Paul Axisa has joined the channel


## 2023-08-04

**Trisha Timpug** (09:35:04):
> @Trisha Timpug has joined the channel


## 2023-08-08

**Aedin Culhane** (14:31:11):
> Whats the best way to work with  clinVar  and hgvsg in R/Bioconductor?


## 2024-03-26

**Sara m.morsy** (16:07:52):
> @Sara m.morsy has joined the channel


## 2024-08-21

**Laura Symul** (08:56:41):
> @Laura Symul has joined the channel


## 2024-09-05

**Mauro Masiero** (03:09:55):
> @Mauro Masiero has joined the channel


## 2024-09-24

**Jasmine Baker** (22:48:06):
> @Jasmine Baker has joined the channel


## 2024-10-23

**Sounkou Mahamane Toure** (11:48:30):
> @Sounkou Mahamane Toure has joined the channel


## 2024-12-05

**Zahraa W Alsafwani** (16:50:56):
> @Zahraa W Alsafwani has joined the channel


## 2025-01-09

**Ammar Sabir Cheema** (11:35:42):
> @Ammar Sabir Cheema has joined the channel


## 2025-03-18

**Nicolo** (14:58:39):
> @Nicolo has joined the channel


## 2025-04-15

**Aedin Culhane** (14:21:54):
> The Italian Biostatistics Group (IBIG) organised a series of 4 webinars focusing on R packages useful for the design and analysis of clinical trials, presented by prominent pharma industry experts:
> 
> - 21 May: Frank Bretz (Novartis) and Dong Xi (Gilead), gMCP: Graph Based Multiple Comparison Procedures.
> 
> - 19 June: Marcel Wolbers and Isaac Gravestock (Roche), rbmi: Reference Based Multiple Imputation.
> 
> - 24 September: Bodo Kirsch (PSI Visualisation Special Interest Group lead), subscreen: Systematic Screening of Study Data for Subgroup Effects.
> 
> - 13 November: Gernot Wassmer and Friedrich Pahlke (RPACT GbR), rpact: Confirmatory Adaptive Clinical Trial Design and Analysis.
> 
> For subscription and further details:[https://simef.it/index.php?option=com_eventbooking&view=event&id=716&catid=7&Itemid=386&lang=it](https://simef.it/index.php?option=com_eventbooking&view=event&id=716&catid=7&Itemid=386&lang=it)
  - Attachment (Società Italiana di Medicina Farmaceutica): [Webinar series on using R software packages](https://simef.it/index.php?option=com_eventbooking&amp;view=event&amp;id=716&amp;catid=7&amp;Itemid=386&amp;lang=it)
> Webinar series on using R software packages

**Aedin Culhane** (14:22:05):
> Sorry just realized they are charging for these
