---
title: "#covid19"
format: gfm
---


## 2020-03-20

*07:47:59 - @Vince Carey has joined the channel*
**Vince Carey** (07:48:00):
> set the channel description: Discuss software/data related to COVID-19

*07:48:09 - @Sean Davis has joined the channel*
*07:49:35 - @Levi Waldron has joined the channel*
**Levi Waldron** (09:23:10):
> I’ve wondered if I could contribute something to the public health response to COVID-19, or whether I would just be duplicating efforts by people more involved than me in infectious disease epidemiology. For example, the Italy dataset that seems to be in use ([https://github.com/pcm-dpc/COVID-19](https://github.com/pcm-dpc/COVID-19)) could be enriched by adding the dates of public health interventions and age structure per region / province. But do we have a line on what analyses are really in need right now?

**Levi Waldron** (09:23:27):
> And whether something like that has been done already?

**Sean Davis** (12:31:44):
> [https://twitter.com/seandavis12/status/1241028865679646726](https://twitter.com/seandavis12/status/1241028865679646726)
  - Attachment (twitter): [Attachment](https://twitter.com/seandavis12/status/1241028865679646726)
    > Looking for #DataScience projects involving #COVID19, this #AwesomeList on [@github](https://twitter.com/github) from [@soroushchehresa](https://twitter.com/soroushchehresa) contains a nice set of data resources.
    > 
    > [https://github.com/soroushchehresa/awesome-coronavirus](https://github.com/soroushchehresa/awesome-coronavirus)
    > 
    > #Coronavirus #SARSCoV2 #github
    > 
    > cc [@Bioconductor](https://twitter.com/Bioconductor) [@NIH](https://twitter.com/NIH) [@CDCgov](https://twitter.com/CDCgov) [@US_FDA](https://twitter.com/US_FDA) [https://pbs.twimg.com/media/ETkD8_7WkAAd1wR.jpg](https://pbs.twimg.com/media/ETkD8_7WkAAd1wR.jpg)

**Sean Davis** (12:33:13):
> @Vince Carey, do you want to “announce” the#covid19channel on#general? People may not find it otherwise. Alternatively, we can keep it quiet for the time being.


## 2020-03-22

**Vince Carey** (11:28:46):
> 1. Kaggle called CORD-19:[https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge). Tasks, what is of interest to extract:[https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/tasks](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/tasks)2. Oak Ridge National Lab effort:[https://chemrxiv.org/articles/Repurposing_Therapeutics_for_the_Wuhan_Coronavirus_nCov-2019_Supercomputer-Based_Docking_to_the_Viral_S_Protein_and_Human_ACE2_Interface/11871402/3](https://chemrxiv.org/articles/Repurposing_Therapeutics_for_the_Wuhan_Coronavirus_nCov-2019_Supercomputer-Based_Docking_to_the_Viral_S_Protein_and_Human_ACE2_Interface/11871402/3)3. OHDSI effort:[https://forums.ohdsi.org/t/ohdsi-virtual-study-a-thon-to-support-covid-19-response-to-take-place-26-29mar2020-collaborators-wanted/9810](https://forums.ohdsi.org/t/ohdsi-virtual-study-a-thon-to-support-covid-19-response-to-take-place-26-29mar2020-collaborators-wanted/9810)
  - Attachment (kaggle.com): [COVID-19 Open Research Dataset Challenge (CORD-19)](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge)
    > An AI challenge with AI2, CZI, MSR, Georgetown, NIH & The White House
  - Attachment (kaggle.com): [COVID-19 Open Research Dataset Challenge (CORD-19)](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/tasks)
    > An AI challenge with AI2, CZI, MSR, Georgetown, NIH & The White House
  - Attachment (figshare): [Repurposing Therapeutics for COVID-19: Supercomputer-Based Docking to the SARS-CoV-2 Viral Spike Protein and Viral Spike Protein-Human ACE2 Interface](https://chemrxiv.org/articles/Repurposing_Therapeutics_for_the_Wuhan_Coronavirus_nCov-2019_Supercomputer-Based_Docking_to_the_Viral_S_Protein_and_Human_ACE2_Interface/11871402/3)
    > The novel Wuhan coronavirus (SARS-CoV-2) has been sequenced, and the virus shares substantial similarity with SARS-CoV. Here, using a computational model of the spike protein (S-protein) of SARS-CoV-2 interacting with the human ACE2 receptor, we make use of the world's most powerful supercomputer, SUMMIT, to enact an ensemble docking virtual high-throughput screening campaign and identify small-molecules which bind to either the isolated Viral S-protein at its host receptor region or to the S protein-human ACE2 interface. We hypothesize the identified small-molecules may be repurposed to limit viral recognition of host cells and/or disrupt host-virus interactions. A ranked list of compounds is given that can be tested experimentally.
  - Attachment (OHDSI Forums): [OHDSI virtual study-a-thon to support COVID-19 response, to take place 26-29Mar2020...Collaborators wanted!](https://forums.ohdsi.org/t/ohdsi-virtual-study-a-thon-to-support-covid-19-response-to-take-place-26-29mar2020-collaborators-wanted/9810)
    > Team: In light of the current uncertainty around COVID-19, we have decided to cancel the in-person OHDSI EU Symposium, which was scheduled to take place 27-29Marc2020 in Oxford, UK. An announcement about this is available here. In lieu of this large meeting event, we have decided to coordinate a virtual OHDSI study-a-thon to take place over the same period that will be focused on generating real-world evidence that can inform the current COVID-19 pandemic response. We expect there are many ...

*16:39:22 - @Aedin Culhane has joined the channel*
**Aedin Culhane** (16:39:52):
> This looks useful[https://github.com/wikipathways/cord-19](https://github.com/wikipathways/cord-19)

**Aedin Culhane** (16:56:10):
> Is there a db of scRNAseq related to covid?

**Aedin Culhane** (17:11:05):
> There is a called for RFA in Boston

**Aedin Culhane** (17:11:48):
> Dear HMS and HSDM Faculty:
>  
> The outbreak of COVID-19 can be considered the single most threatening pandemic to arise in the last century, and we have taken action accordingly to safeguard our community. However, as a leading medical school with clinical and research faculty throughout a large hospital ecosystem, we also have the ability to actively combat the outbreak by executing critical and timely research relevant to the pandemic.
>  
> Many of you are aware of a workshop that took place on March 2, which gathered 80 members of the greater Boston biomedical research community to determine how to collectively respond to the COVID-19 outbreak. That community has solidified into the Greater Boston Consortium on Pathogen Readiness (GBCPR), led by Faculty Co-Directors Arlene Sharpe and Bruce Walker. The consortium has received its initial funding from Harvard University based on generous support from the China Evergrande Group in partnership with the Guangzhou Institute of Respiratory Health in Guangzhou, China.
>  
> Through this email I am announcing a Request for Proposals for the Evergrande COVID-19 Response Fund Awards, administered by the GBCPR. We are compressing the typical RFP schedule, with***two-page proposals due March 24, 2020,***and funding beginning as soon as possible in April 2020. Awards will be made in the $50,000 to $500,000 range, which includes total costs per project cumulatively across all budget years. Areas of research include epidemiology, pathogenesis, diagnostics, therapeutics, vaccines and clinical management related to COVID-19.
>  
> Tenure-track faculty members at the level of assistant, associate, or full professor at Harvard University (HMS, FAS, HCSPH, HSDM, SEAS), MIT, Boston University School of Medicine, Tufts University School of Medicine, University of Massachusetts Medical School and hospitals and research institutes affiliated with these four medical schools are eligible to apply as lead PIs. Senior scientists from biotechnology and pharmaceutical companies are eligible as co-PIs.   
>  
> Proposals should be submitted by email to[gbcpr@hms.harvard.edu](mailto:gbcpr@hms.harvard.edu). More information can be found on the consortium[website](http://links.mkt3779.com/ctt?kn=3&ms=MjMwMTkzMTIS1&r=MTg1OTAxOTc3NDkwS0&b=0&j=MTcwMTA3NDYyNwS2&mt=1&rt=0).
>  
> We encourage all researchers who work on these topics to apply, particularly those whose research is directly applicable to address the current urgent needs of the COVID-19 outbreak.
>  
> If you are wondering why we are announcing this RFP at the same time as we are curtailing much of our in-person laboratory activities, the answer is simple: Our laboratories are being shut down for one set of public health reasons (i.e., the safety of our lab personnel and reducing the spread of the disease in our community), while COVID-19 research is being ramped up for a different set of public health reasons (i.e., to achieve short- and long-term control of the viral illness at the individual patient level and control of this pandemic and future pandemics at the population level). Both sets of activities serve our mission to alleviate suffering and improve health and well-being for all.
>  
> Please feel free to forward this RFP to eligible colleagues throughout the Commonwealth, as we expand our community of researchers to combat the pandemic.
> 
> Sincerely,
>  
> George Q. Daley
> Dean of the Faculty of Medicine
> Harvard University
  - Attachment (gbcpr.hms.harvard.edu): [Greater Boston Consortium on Pathogen Readiness](http://links.mkt3779.com/ctt?kn=3&amp;ms=MjMwMTkzMTIS1&amp;r=MTg1OTAxOTc3NDkwS0&amp;b=0&amp;j=MTcwMTA3NDYyNwS2&amp;mt=1&amp;rt=0)
    > Greater Boston Consortium on Pathogen Readiness

**Aedin Culhane** (17:12:10):
> Deadline is Tuesday 5pm EST. No grants sign off needed.

**Aedin Culhane** (17:13:34):
> I am talking lab colleagues about a possible proposal. I am trying to gather info on state of the field and is moving v fast

**Sean Davis** (20:28:07):
> @Vince Carey, I’ll take a stab at adding to your 2pp tomorrow.

**Sean Davis** (20:29:37):
> Do you all know the approximate resources?

**Sean Davis** (20:30:19):
> Ah. Found it.


## 2020-03-23

**Sean Davis** (10:12:48):
> COVID-19 dataset from JHU augmented with country metadata. Useful for joining to financial and other data resources.
  - File (Excel Spreadsheet): [covid_19_data.xlsx](https://community-bioc.slack.com/files/U34P8RS3B/F0106GM8WKC/covid_19_data.xlsx)

**Aedin Culhane** (14:48:27):
> 2pm tomorrow??????

*15:43:45 - @Lauren Hsu has joined the channel*
**Sean Davis** (16:09:33):
> 2 pager (2pp),@Aedin Culhane. Using@Vince Careyterminology.:slightly_smiling_face:

**Aedin Culhane** (16:27:52):
> [https://www.ebi.ac.uk/ena/pathogens/covid-19](https://www.ebi.ac.uk/ena/pathogens/covid-19)


## 2020-03-24

**Sean Davis** (16:27:35):
> [https://covid19challenge.mit.edu/](https://covid19challenge.mit.edu/)

**Sean Davis** (16:27:43):
> <!channel>, any interest in participating?

**Aedin Culhane** (19:25:15):
> Have you seen OHDSI hackathon[https://forums.ohdsi.org/t/ohdsi-cov19-community-update-24march2020-logistics-for-ohdsi-covid19-study-a-thon/10092](https://forums.ohdsi.org/t/ohdsi-cov19-community-update-24march2020-logistics-for-ohdsi-covid19-study-a-thon/10092)
  - Attachment (OHDSI Forums): [[OHDSI Cov19] Community Update 24March2020: Logistics for OHDSI COVID19 Study-a-thon](https://forums.ohdsi.org/t/ohdsi-cov19-community-update-24march2020-logistics-for-ohdsi-covid19-study-a-thon/10092)
    > Team: T minus 2 days until the kick-off of the OHDSI COVID-19 study-a-thon. This update provides you details of the logistics for those who registered about how you can participate in the activities. Thanks to the ~300 individuals in ~30 countries who have signed up to join this journey with us. We will be using Microsoft Teams as our collaboration platform for the OHDSI COVID-19 study-a-thon. Thanks to Peter and ErasmusMC for ‘hosting’ this event on their account. Either today or tomorrow...


## 2020-03-25

**Aedin Culhane** (01:30:09):
> Sean have you looked at mark handleys tracking[http://nrg.cs.ucl.ac.uk/mjh/covid19/](http://nrg.cs.ucl.ac.uk/mjh/covid19/)

**Sean Davis** (12:15:43):
> Yes. Looks fantastic. I particularly like the contest that he provides.


## 2020-03-26

*13:24:24 - @Steve Lianoglou has joined the channel*

## 2020-03-30

**Sean Davis** (12:50:28):
> [https://seandavi.github.io/sars2pack/](https://seandavi.github.io/sars2pack/)
  - Attachment (seandavi.github.io): [sars2pack](https://seandavi.github.io/sars2pack/)
    > The sars2pack package includes COVID-19 data resources, analysis tools, and workflows in R.

**Sean Davis** (12:50:46):
> [https://github.com/seandavi/sars2pack](https://github.com/seandavi/sars2pack)

**Sean Davis** (12:52:05):
> @Vince Careykicked this off.<!channel>, we’d be happy to have some contributors of Rmarkdown vignettes or additional data resources. The datasets are highly amenable to dplyr, ggplot2, and other exploratory data analysis tasks.

**Sean Davis** (12:54:16):
> For folks with students who would be interested in contributing, perhaps consider inviting them here. There are about 10 more datasets that I’d like to add via relatively straightforward acccessor/caching mechanisms.

*14:12:04 - @Kevin Blighe has joined the channel*
*14:26:04 - @Tiago C. Silva has joined the channel*
*14:58:22 - @Jared Andrews has joined the channel*
**Sean Davis** (15:54:13):
> @Kevin BligheWell, the sars2pack work is our little work-in-progress contribution. That said, I think the problem is large enough for additional projects, discussions, contributions, and collaborations.

**Sean Davis** (15:55:11):
> Let’s keep discussion open here; Bioconductor has a lot to bring to the table.

*16:06:35 - @Kevin Rue-Albrecht has joined the channel*

## 2020-03-31

*11:37:52 - @Paula Beati has joined the channel*
*13:58:36 - @Jenny Drnevich has joined the channel*

## 2020-04-05

**Sean Davis** (15:31:15):
> [https://seandavi.github.io/COVID19Book/](https://seandavi.github.io/COVID19Book/)
  - Attachment (seandavi.github.io): [Understanding the COVID-19 pandemic](https://seandavi.github.io/COVID19Book/)
    > Understanding the COVID-19 pandemic

**Sean Davis** (15:31:42):
> Work-in-progress. Anyone is welcome to contribute.

**Sean Davis** (15:32:09):
> [https://github.com/seandavi/COVID19Book](https://github.com/seandavi/COVID19Book)

**Kevin Rue-Albrecht** (16:46:41):
> For the interactive maps section, I've got[https://kevinrue.github.io/COVID-19-website/csse_covid_19_map_latest.html](https://kevinrue.github.io/COVID-19-website/csse_covid_19_map_latest.html)

**Sean Davis** (22:02:07):
> That is a sweet site,@Kevin Rue-Albrecht! I hope you don’t mind if I steal some of your plots as examplars (with attribution, of course).


## 2020-04-06

**Kevin Rue-Albrecht** (02:52:29):
> No worries. At the moment, it's probably more efficient that you take from me, with a quick reference / link.
>  I've looked at the covid book and the JHU part of`sars2pack`, and I've got a few ideas, but I can't promise when exactly I can contribute back. It'll be bite-size contributions here and there. I'll let you know when it happens.

*13:52:27 - @Anna Lorenc has joined the channel*

## 2020-04-07

**Aedin Culhane** (00:05:36):
> First papers from OHDSI studies will be submitted tomorrow. exicting. Galaxy has a hackathon on covid19 next week[https://covid19.galaxyproject.org/](https://covid19.galaxyproject.org/)
  - Attachment (covid19.galaxyproject.org): [COVID-19 analysis on usegalaxy.★](https://covid19.galaxyproject.org/)
    > This repo serves as a companion to our study describing the analysis of early COVID-19 data: No more business as usual: agile and effective responses to emerging pathogen threats require open data and open analytics. [usegalaxy.org](http://usegalaxy.org), [usegalaxy.eu](http://usegalaxy.eu), [usegalaxy.org.au](http://usegalaxy.org.au), [usegalaxy.be](http://usegalaxy.be) and [hyphy.org](http://hyphy.org) development teams, Anton Nekrutenko, Sergei L Kosakovsky Pond. bioRxiv 2020.02.21.959973; doi: [https://doi.org/10.1101/2020.02.21.959973](https://doi.org/10.1101/2020.02.21.959973)

**Aedin Culhane** (00:09:31):
> Bioc  could consider a hackathon possible to develop frameworks to support covid19. Need to consider how we'd get papers from it (people need sugar to participate) Possible things that could be added to Bioc to support COVID19 research 1)  build curated scRNAseq of lung, kidney, blood and publish on ACE2 expression and related pathways  - aka build  immune annotation 2) support phylogenetics and  viral/bacterial genomes  3) support for EHR records, connections to OHDSI (both on R), support for OMOP[https://www.ohdsi.org/data-standardization/the-common-data-model/](https://www.ohdsi.org/data-standardization/the-common-data-model/)

**Kevin Rue-Albrecht** (02:25:46):
> Interesting point in the news about reporting (and thus using) actual dates of events:
> > Many hospitals will not report deaths that happened over the weekend until the middle of the following week.
> Over the weekend, NHS England released new figures broken down by the actual date of death.
> [https://www.bbc.co.uk/news/health-52167016](https://www.bbc.co.uk/news/health-52167016)
  - Attachment (BBC News): [Warning over daily coronavirus death figures](https://www.bbc.co.uk/news/health-52167016)
    > Spikes or dips may in part reflect bottlenecks in the reporting system, rather than real changes in the trend.


## 2020-04-09

**Sean Davis** (07:33:29):
> [https://www.nytimes.com/2020/04/08/science/new-york-coronavirus-cases-europe-genomes.html](https://www.nytimes.com/2020/04/08/science/new-york-coronavirus-cases-europe-genomes.html)
  - Attachment (The New York Times): [Most New York Coronavirus Cases Came From Europe, Genomes Show](https://www.nytimes.com/2020/04/08/science/new-york-coronavirus-cases-europe-genomes.html)
    > Travelers seeded multiple cases starting as early as mid-February, genomes show.

**Sean Davis** (11:23:12) (in thread):
> Yep. That would make a really cool analysis for someone here to try to replicate, though I won’t be the one to do so.

*17:52:03 - @Federico Marini has joined the channel*
**Federico Marini** (17:53:14) (in thread):
> I’m just picturing the results combined with all the goodies contained in the newest version of the`mapdeck`package. A relief for the eyes would that be:slightly_smiling_face:


## 2020-04-11

**Aedin Culhane** (18:03:17):
> Last minute I know, but its only a short google form with 500 words, deadline is Sunday. Fast Grants are $10k to $500k and decisions are made in under 48 hours[https://fastgrants.org/?fbclid=IwAR0qyUFfme14qr0P3FlIEuh6jZhcRIYTEavfxXcviMdw_WadpbS6h5dUOpk](https://fastgrants.org/?fbclid=IwAR0qyUFfme14qr0P3FlIEuh6jZhcRIYTEavfxXcviMdw_WadpbS6h5dUOpk)
  - Attachment (fastgrants.org): [Fast Grants](https://fastgrants.org/?fbclid=IwAR0qyUFfme14qr0P3FlIEuh6jZhcRIYTEavfxXcviMdw_WadpbS6h5dUOpk)
    > Funding for scientists at academic institutions working on COVID-19 related projects.

**Aedin Culhane** (18:04:43):
> Could Bioconductor build out tools that would facilitate COVID-19 research and could be described in 500 words??


## 2020-04-12

*06:45:58 - @FelixErnst has joined the channel*
**Vince Carey** (16:43:13):
> Is it a hard deadline?  My reading is that they will review the bolus submitted Sunday within a fixed period.  But one could submit subsequently.


## 2020-04-18

**Kevin Rue-Albrecht** (15:10:25):
> A use of`sars2pack::jhu_data()`:[https://github.com/kevinrue/COVID-19-website/blob/master/csse_covid_19_time_series_cumulative_cases_week.Rmd](https://github.com/kevinrue/COVID-19-website/blob/master/csse_covid_19_time_series_cumulative_cases_week.Rmd)
> ```
> ```{r setup, include=FALSE}
> knitr::opts_chunk$set(echo = FALSE)
> library(sars2pack)
> ```
> 
> ```{r}
> csse_table <- jhu_data()
> ```
> ```
> Resulting page here:[https://kevinrue.github.io/COVID-19-website/csse_covid_19_time_series_cumulative_cases_week.html](https://kevinrue.github.io/COVID-19-website/csse_covid_19_time_series_cumulative_cases_week.html)


## 2020-04-20

*01:31:41 - @Mohamed Gunady has joined the channel*

## 2020-04-22

**Aedin Culhane** (11:44:16):
> Dear ITCR Investigators,
> 
> This may be of interest to some of you:
> 
> 
> The National Library of Medicine (NLM) at the National Institutes of Health is hosting a free webinar for researchers to learn how to share, discover, and cite COVID-19 data and code in generalist repositories on April 24 from 2:00-3:45 p.m. ET.
> The biomedical research community’s understanding of the novel coronavirus and the associated coronavirus disease (COVID-19) is rapidly evolving. Open science and the timely sharing of research data have played a critical role in advancing our understanding of COVID-19 and accelerating the pace of discovery. Researchers will have an opportunity to hear from multiple generalist repositories about the ways each repository is supporting discoverability and reusability of COVID-19 data and associated code. The NLM will also provide an overview of available COVID-19 literature.
> The webinar will be available via NIH VideoCast:[http://ow.ly/Ec5750zkz22](http://ow.ly/Ec5750zkz22)and instructions on submitting questions will be made available closer to the webinar. Interested participants are encouraged to bookmark this page for the latest updates and follow #NIHdata on Twitter. The webinar will be recorded and available a week after the live event.
> See the agenda:[http://ow.ly/IL3R50zkyZg](http://ow.ly/IL3R50zkyZg)Individuals with disabilities who need sign language interpreting and/or other reasonable accommodations to participate in this event should contact Tara Mowery at[tara.mowery@nih.gov](mailto:tara.mowery@nih.gov)and/or the Federal Relay at 1-800-877-8339. Requests should be made five days in advance.
> Questions - Please contact Dr. Lisa Federer -[lisa.federer@nih.gov](mailto:lisa.federer@nih.gov), 301-827-4399
> 
> 
> ########################################################################
  - Attachment (videocast.nih.gov): [NIH VideoCast - NIH Webinar on Sharing, Discovering, and Citing COVID-19 Data and Code](http://ow.ly/Ec5750zkz22)
    > NIH Webinar on Sharing, Discovering, and Citing COVID-19 Data and Code


## 2020-04-23

**Sean Davis** (11:45:21):
> I added the Apple Mobility dataset which provides city and country-level daily index of auto, pedestrian, and public transport activity at one-day resolution. It is kind of addictive to play with IMHO.[https://seandavi.github.io/sars2pack/reference/apple_mobility_data.html](https://seandavi.github.io/sars2pack/reference/apple_mobility_data.html)
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F012E8122SF/image.png)

**Sean Davis** (11:45:31):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F012E81F075/image.png)


## 2020-04-24

**Sean Davis** (15:46:08):
> [https://www.biorxiv.org/content/10.1101/2020.04.19.049254v2](https://www.biorxiv.org/content/10.1101/2020.04.19.049254v2)


## 2020-04-27

**Aedin Culhane** (11:18:57):
> Love the heatmap of the mobility data. Do people in most cities do more walking at the weekend and less on Mondays???


## 2020-04-30

**Sean Davis** (13:05:14):
> [https://www.nsf.gov/pubs/2020/nsf20052/nsf20052.jsp](https://www.nsf.gov/pubs/2020/nsf20052/nsf20052.jsp)

**Sean Davis** (13:05:25):
> funding opportunity


## 2020-05-01

*05:25:04 - @Charlotte Rich-Griffin has joined the channel*
**Sean Davis** (20:20:24):
> Some non-map-based geospatial visualizations from recent contributors to sars2pack:[https://seandavi.github.io/sars2pack/articles/more_visualization.html](https://seandavi.github.io/sars2pack/articles/more_visualization.html)
  - Attachment (seandavi.github.io): [Visualizing geographic COVID-19 trends without maps](https://seandavi.github.io/sars2pack/articles/more_visualization.html)
    > sars2pack


## 2020-05-04

**Sean Davis** (17:42:51):
> 62 genomes available via nextstrain_case_data() from sars2pack and then this:
> ```
> > library(genbankr)
> > gba = GBAccession("MT007544")
> > gba
> GenBank Accession Number(s):  MT007544
> > gbk = readGenBank(gba)
> Loading required namespace: rentrez
> Annotations don't have 'locus_tag' label, using 'gene' as gene_id column
> Annotations don't have 'locus_tag' label, using 'gene' as gene_id column
> No exons read from genbank file. Assuming sections of CDS are full exons
> No transcript features (mRNA) found, using spans of CDSs
> > gbk
> GenBank Annotations
> Severe acute respiratory syndrome coronavirus 2 isolate Australia/VIC01/2020, complete genome.
> Accession: MT007544
> 1 Sequence(s) with total length length: 29893
> 10 genes
> 10 transcripts
> 11 exons/cds elements
> 0 variations
> 2 other features
> 
> > getSeq(gbk)
>   A DNAStringSet instance of length 1
>     width seq                                                                                                                                                                                           names
> [1] 29893 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTGTGTGGCT...TAAAATTAATTTTAGTAGTGCTATCCCCATGTGATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA Severe acute resp...
> ```


## 2020-05-05

*09:55:58 - @Devika Agarwal has joined the channel*

## 2020-05-06

**Sean Davis** (10:08:54):
> Immune cell profiling of COVID-19 patients in the recovery stage by single-cell sequencing[https://www.nature.com/articles/s41421-020-0168-9](https://www.nature.com/articles/s41421-020-0168-9)
  - Attachment (Cell Discovery): [Immune cell profiling of COVID-19 patients in the recovery stage by si](https://www.nature.com/articles/s41421-020-0168-9)
    > Immune cell profiling of COVID-19 patients in the recovery stage by single-cell sequencing


## 2020-05-23

**Sean Davis** (10:47:24):
> [https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/2020-05-21-COVID19-Report-23.pdf](https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/2020-05-21-COVID19-Report-23.pdf)


## 2020-06-06

*19:57:12 - @Olagunju Abdulrahman has joined the channel*

## 2020-06-07

*06:27:28 - @Tanzeel Tagalsir has joined the channel*

## 2020-06-22

**USLACKBOT** (09:11:34):
> This message was deleted.


## 2020-06-28

**Vince Carey** (06:59:10) (in thread):
> Thanks for posting this.  I'll place a toe into potentially dangerous water.  The scope of questioning is nice but excludes any concern with effects on political engagement.  Because public health scientists have been directly muzzled (in the USA at least), it is clearly important that processes begin to reduce political control over government scientists.  Steps need to be taken to reduce the chances that anti-science individuals are in positions to control public health policy.  But lack of time and perception of likely intimidation probably conspire to reduce scientists' willingness to engage in political action.  Would survey questions along these lines only be relevant in the context of the USA, or would they be of interest more broadly?


## 2020-07-03

**Sean Davis** (12:49:51):
> [https://clades.nextstrain.org/](https://clades.nextstrain.org/)
  - Attachment (Nextclade): [Nextclade](https://clades.nextstrain.org/)
    > Clade assignment, mutation calling, and quality control right inside your browser


## 2020-07-29

*17:37:17 - @Riyue Sunny Bao has joined the channel*

## 2020-07-31

*16:23:59 - @Dr Awala Fortune O. has joined the channel*

## 2020-08-31

**Sean Davis** (09:15:39):
> [https://www.biorxiv.org/content/10.1101/2020.08.30.273235v1](https://www.biorxiv.org/content/10.1101/2020.08.30.273235v1)

**Sean Davis** (09:16:15):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F019ZC3R11S/image.png)


## 2020-09-16

*11:02:26 - @Mike Morgan has joined the channel*

## 2020-11-04

*11:58:56 - @Krutika has joined the channel*

## 2020-12-12

*00:40:32 - @Huipeng Li has joined the channel*

## 2021-01-22

*15:43:31 - @Annajiat Alim Rasel has joined the channel*

## 2021-03-05

*05:01:19 - @Jim Hunter has joined the channel*

## 2021-03-20

*01:57:15 - @watanabe_st has joined the channel*

## 2021-03-23

*23:04:44 - @Lambda Moses has joined the channel*

## 2021-05-11

*16:44:43 - @Megha Lal has joined the channel*

## 2021-05-23

*08:10:08 - @Jonas Schulte-Schrepping has joined the channel*

## 2021-06-08

*08:49:19 - @Lorenzo Bonaguro has joined the channel*

## 2021-11-08

*03:26:31 - @Paula Nieto García has joined the channel*

## 2022-01-28

*11:12:19 - @Megha Lal has left the channel*

## 2022-07-22

*14:48:11 - @Gary Sieling has joined the channel*

## 2022-07-28

*13:50:25 - @Krithika Bhuvanesh has joined the channel*

## 2022-07-29

*15:41:44 - @Ryan C. Thompson has joined the channel*

## 2023-01-18

*13:09:38 - @José Basílio has joined the channel*

## 2023-08-03

*15:57:20 - @Ritika Giri has joined the channel*

## 2024-02-05

*17:37:25 - @Manuel Barrios Izás has joined the channel*

## 2024-05-14

**Lori Shepherd** (10:43:16):
> archived the channel
