---
title: "#database"
---

## 2020-11-04

**Kevin Rue-Albrecht** (05:57:37):
> @Kevin Rue-Albrecht has joined the channel

**Kevin Rue-Albrecht** (05:57:38):
> set the channel description: Working with databases in R

**Kevin Rue-Albrecht** (05:58:42):
> In case anyone works with SQLite databases, I'm happy to get feedback about[https://github.com/kevinrue/sqlighter](https://github.com/kevinrue/sqlighter)It's by no mean groundbreaking, as it says on the tin:
> > Convenient wrapper functions around the RSQLite package


## 2020-12-12

**Huipeng Li** (00:40:23):
> @Huipeng Li has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:43:35):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-17

**abdullah hanta** (16:06:11):
> @abdullah hanta has joined the channel


## 2021-03-20

**watanabe_st** (01:57:19):
> @watanabe_st has joined the channel


## 2021-05-11

**Megha Lal** (16:44:46):
> @Megha Lal has joined the channel


## 2021-06-04

**Izaskun Mallona** (08:56:25):
> @Izaskun Mallona has joined the channel


## 2021-07-23

**Batool Almarzouq** (15:52:40):
> @Batool Almarzouq has joined the channel


## 2021-11-08

**Paula Nieto García** (03:26:37):
> @Paula Nieto García has joined the channel


## 2021-12-07

**Jenny Smith** (15:20:46):
> @Jenny Smith has joined the channel


## 2022-01-28

**Megha Lal** (11:12:26):
> @Megha Lal has left the channel


## 2022-07-28

**Krithika Bhuvanesh** (13:52:17):
> @Krithika Bhuvanesh has joined the channel


## 2022-07-31

**Arda Keles** (04:14:33):
> @Arda Keles has joined the channel


## 2022-12-12

**Lexi Bounds** (17:58:04):
> @Lexi Bounds has joined the channel


## 2023-01-18

**José Basílio** (13:09:33):
> @José Basílio has joined the channel


## 2023-01-21

**Hien** (16:02:01):
> @Hien has joined the channel

**Hien** (16:17:25):
> @Hien has left the channel


## 2023-03-31

**Aedin Culhane** (08:34:09):
> @Aedin Culhane has joined the channel


## 2023-05-03

**Rebecca Butler** (16:15:35):
> @Rebecca Butler has joined the channel


## 2024-02-05

**Manuel Barrios Izás** (17:27:20):
> @Manuel Barrios Izás has joined the channel


## 2024-03-26

**Sara m.morsy** (16:08:39):
> @Sara m.morsy has joined the channel


## 2024-05-14

**Lori Shepherd** (10:23:37):
> archived the channel
