---
title: "#developers-mentorship"
---

## 2021-08-05

**Aedin Culhane** (16:22:51):
> @Aedin Culhane has joined the channel

**Aedin Culhane** (16:22:51):
> set the channel description: Bioconductor mentorship program to assist new developers and would-be developers to develop a new package.

**Kevin Rue-Albrecht** (16:23:21):
> @Kevin Rue-Albrecht has joined the channel

**Mike Smith** (16:23:21):
> @Mike Smith has joined the channel

**Shila Ghazanfar** (16:23:21):
> @Shila Ghazanfar has joined the channel

**Shila Ghazanfar** (18:48:32):
> thanks for making this slack channel Aedin:slightly_smiling_face:a couple of thoughts that i had during the ‘meet the tab’ session:
> 
> Developer support:
> - May be worth sending out a survey to understand needs of potential and existing developers
> - Ask developers about if/how they maintain their packages?
> - Do they know how to get help?
> - Would they like a mentor?
> - Trouble with package building, vignettes, Github?
> - “Ask the experts” special sessions (Bioc workshop/networking)


## 2021-08-06

**Aedin Culhane** (14:46:52):
> @Kevin Rue-Albrecht@Mike SmithCan we post links to everything here

**Kevin Rue-Albrecht** (14:47:36):
> great idea! we can pin them too

**Aedin Culhane** (14:47:54):
> Guidelines for Developers and Reviewers:[http://contributions.bioconductor.org/](http://contributions.bioconductor.org/)

**Aedin Culhane** (14:48:10):
> @Kevin Rue-AlbrechtI don’t think we have added a slide about the EoI in the CAB Slides

**Kevin Rue-Albrecht** (14:49:03):
> Resource:
> * [Bioconductor Package Guidelines for Developers and Reviewers](http://contributions.bioconductor.org/)
> * [Expression of Interest (for new Mentors)](https://forms.gle/cq7jkXXsuo2ChMpLA)
> * [Developer github book](https://kevinrue.github.io/bioc-mentorship-docs/)

**Aedin Culhane** (14:49:05):
> * ***Expression of Interest in Developer Mentorship Program (for new Mentors)***.[https://forms.gle/cq7jkXXsuo2ChMpLA](https://forms.gle/cq7jkXXsuo2ChMpLA)
> * Developer github book:[https://kevinrue.github.io/bioc-mentorship-docs/index.html](https://kevinrue.github.io/bioc-mentorship-docs/index.html)
  - Attachment (Google Docs): [Bioconductor Developer Mentorship Program - Expression of Interest](https://forms.gle/cq7jkXXsuo2ChMpLA)
> Please indicate your interest to learn more and potentially become a mentor in the Bioconductor Developer Mentorship program. The Bioconductor Developer Mentorship Program will form a part of the Bioconductor “welcome mat” that the Bioconductor Community Advisory Board are developing. It will be a group-mentorship/buddy program for would-be, new, or hesitant developers or for developers who wish to refresh their skills. The goal of the program is to welcome and onboard new developers, develop educational material to assist new developers, improve the quality of packages submitted to Bioconductor, and strengthen community and interactions between Bioconductor developers. Mentors should have at least 1 package either in the release or accepted in the development branch of Bioconductor. Each program cycle would run for 6 months (or the development cycle of Bioconductor package release). For more information about the program see the Bioconductor Website [link].. or Google doc [[https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing](https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing)]

**Kevin Rue-Albrecht** (15:02:05):
> woops, that's true, I'll have a look where it could fit
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C029XJX3A4F/p1628275690004200)
> @Kevin Rue-Albrecht I don’t think we have added a slide about the EoI in the CAB Slides

**Aedin Culhane** (15:02:11):
> Short link to form[https://bit.ly/BiocDevel](https://bit.ly/BiocDevel)

**Aedin Culhane** (15:02:18):
> I added it into slides

**Kevin Rue-Albrecht** (15:02:39) (in thread):
> argh ok - sorry I was multitasking dinner xD

**Daniela Cassol** (17:16:59):
> @Daniela Cassol has joined the channel

**Lori Shepherd** (17:17:09):
> @Lori Shepherd has joined the channel

**Marcel Ramos Pérez** (17:38:01):
> @Marcel Ramos Pérez has joined the channel

**Davide Risso** (17:44:07):
> @Davide Risso has joined the channel

**Laurent Gatto** (22:41:18):
> @Laurent Gatto has joined the channel


## 2021-08-07

**Charlotte Soneson** (08:27:02):
> @Charlotte Soneson has joined the channel


## 2021-08-15

**Lluís Revilla** (10:35:47):
> @Lluís Revilla has joined the channel


## 2021-08-18

**Aedin Culhane** (09:41:45):
> If you have developed a Bioconductor Package and learned the challenges along the way If you have tips and tricks for would-be developers. Please consider joining the new Bioconductor Mentorship program to help new would be  developers get from R scripts to Bioconductor package. Expression of interest form at[https://forms.gle/fya5JEArTT5kNEGr9](https://forms.gle/fya5JEArTT5kNEGr9)
  - Attachment (Google Docs): [Bioconductor Developer Mentorship Program - Expression of Interest](https://forms.gle/fya5JEArTT5kNEGr9)
> Please indicate your interest to learn more and potentially become a mentor in the Bioconductor Developer Mentorship program. The Bioconductor Developer Mentorship Program will form a part of the Bioconductor “welcome mat” that the Bioconductor Community Advisory Board are developing. It will be a group-mentorship/buddy program for would-be, new, or hesitant developers or for developers who wish to refresh their skills. The goal of the program is to welcome and onboard new developers, develop educational material to assist new developers, improve the quality of packages submitted to Bioconductor, and strengthen community and interactions between Bioconductor developers. Mentors should have at least 1 package either in the release or accepted in the development branch of Bioconductor. Each program cycle would run for 6 months (or the development cycle of Bioconductor package release). For more information about the program see the Bioconductor Website [link].. or Google doc [[https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing](https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing)]


## 2021-09-06

**Eddie** (08:22:39):
> @Eddie has joined the channel


## 2021-09-29

**Kozo Nishida** (13:54:46):
> @Kozo Nishida has joined the channel


## 2021-11-03

**Aedin Culhane** (08:47:02):
> Inviting@Davide Risso@Nitesh Mani@Federico Marini@Kelly Street@Alan O'C@Dario Strbenac

**Alan O'C** (08:47:17):
> @Alan O'C has joined the channel

**Kelly Street** (12:00:47):
> @Kelly Street has joined the channel

**Federico Marini** (17:32:25):
> @Federico Marini has joined the channel

**Federico Marini** (17:32:36):
> Hello there:slightly_smiling_face:


## 2021-11-06

**Federico Marini** (09:33:52):
> Thinking out loud: what is the status of this initiative? Something public, “something we can tweet about”?
> I am imagining maybe some of the followers might be animated to get in touch and apply as mentee

**Kevin Rue-Albrecht** (11:52:28):
> Thanks for pointing that out. It's definitely public (since the call for mentors was already public).
> I'll do you one better. I'd encourage everyone to put the word out around them, especially in the lead up to the call for mentees, so that we cast the net wide and reach mentees who may not be already the most familiar with the Bioconductor project

**Kevin Rue-Albrecht** (11:53:03):
> Your message is also a good to reminder to get the google form for mentee applications in shape ASAP:sweat_smile:


## 2021-11-09

**Julia Philipp** (15:08:39):
> @Julia Philipp has joined the channel


## 2021-11-24

**Sowmya Parthiban** (13:46:46):
> @Sowmya Parthiban has joined the channel

**Sowmya Parthiban** (13:48:12):
> Hi, the link to the mentee form seems to be broken. It redirects me to the same page. Hope this is the right place to bring it up at.

**Kevin Rue-Albrecht** (13:58:28) (in thread):
> Absolutely, let me check that. I don't use[bit.ly](http://bit.ly)very much. It seemed the best way to give out a short link that people could type quickly:grimacing:

**Kevin Rue-Albrecht** (13:59:56) (in thread):
> The link still works for me. What do you mean it redirects you to the same page? The link is on Twitter, and it should redirect you to a Google Form

**Kevin Rue-Albrecht** (14:00:35) (in thread):
> we are talking about[bit.ly/3cDwwUs](http://bit.ly/3cDwwUs)right?

**Sowmya Parthiban** (14:17:45) (in thread):
> Oh, sorry I didn't clarify where. I meant here[https://bioconductor.org/developers/new-developer-program/](https://bioconductor.org/developers/new-developer-program/)under the 'Join as a Mentee' section.

**Sowmya Parthiban** (14:18:07) (in thread):
> it doesn't take me to the form when I click on the link.

**Kevin Rue-Albrecht** (14:20:17) (in thread):
> Ah right. That would make sense as that particular link was not updated since we published the form. I’m not sure why that was made a self link, possibly a leftover or copy pasting contents into this page. Thanks for reporting the issue, I’ll update the link shortly

**Kevin Rue-Albrecht** (14:20:39) (in thread):
> In the meantime please use the link that I posted above

**Kevin Rue-Albrecht** (14:24:04) (in thread):
> unnecessary side note: apparently the self link was not an accidental copy-paste, but rather the fallback behaviour of the website in the absence of a URL in the link:sweat_smile:


## 2021-12-02

**Aedin Culhane** (11:27:59):
> [https://twitter.com/KevinRUE67/status/1462838583245651970?s=20](https://twitter.com/KevinRUE67/status/1462838583245651970?s=20)
  - Attachment (twitter): [Attachment](https://twitter.com/KevinRUE67/status/1462838583245651970?s=20)
> The [@Bioconductor](https://twitter.com/Bioconductor) Mentorship programme is now open for applications as mentee! New package developers are encouraged to apply at [https://bit.ly/3cDwwUs](https://bit.ly/3cDwwUs)
> More information at [https://bioconductor.org/developers/new-developer-program/](https://bioconductor.org/developers/new-developer-program/)
> Come turn some of your scripts into a Bioconductor package! [https://pbs.twimg.com/media/FE0KIRYWYAAFfEB.jpg](https://pbs.twimg.com/media/FE0KIRYWYAAFfEB.jpg)

**Aedin Culhane** (11:28:22):
> Apply at[https://docs.google.com/forms/d/e/1FAIpQLSf_xEOQU6Ye78qF0o0tcUhmMHWui-QVX8R-53KQE8c13qQMqA/viewform](https://docs.google.com/forms/d/e/1FAIpQLSf_xEOQU6Ye78qF0o0tcUhmMHWui-QVX8R-53KQE8c13qQMqA/viewform)


## 2022-01-07

**Vince Carey** (06:34:25):
> @Vince Carey has joined the channel

**Vince Carey** (06:34:50):
> I recommended the mentoring program to a new package submitter but the form says the program is closed.  True?

**Vince Carey** (06:35:01):
> @Aedin Culhane^^

**Aedin Culhane** (07:51:35):
> Yes for this cycle@Kevin Rue-Albrecht@Mike Smith


## 2022-01-09

**Kevin Rue-Albrecht** (11:04:27):
> @Vince CareyWe'll have a meeting shortly to decide how to deal with applications on a rolling basis.
> To avoid having to create a new form for each cycle of application, I've been thinking about adding a field to the form with a dropdown for the cycle of mentorship (e.g. April 2022, October 2022, ...), with that field offering only one choice at any one time, and that choice being updated every time we close one cycle of application and simultaneously open the next one.

**Kevin Rue-Albrecht** (11:06:11) (in thread):
> That way, all the applications of all the cycles of mentorship would end up in the same Google Sheet (for better or for worse), and reviewers could always filter the sheet for a release of interest

**Kevin Rue-Albrecht** (11:06:55) (in thread):
> I don't know exactly what would happen if other fields of the form were changed. Perhaps we'd still have to occasionally create a new pair of form and sheet to collect answers

**Vince Carey** (13:19:37) (in thread):
> Thanks Kevin!


## 2022-01-20

**Kevin Rue-Albrecht** (04:52:18) (in thread):
> Hi@Vince CareyThings are going a bit more slowly than anticipated. While we get things going for the pilot round of applications, I've made this new form to collect applications for future rounds of mentorships.[https://forms.gle/K2LguxW7MWkY3js38](https://forms.gle/K2LguxW7MWkY3js38)
  - Attachment (Google Docs): [Bioconductor Mentorship Program - Application form for mentees](https://forms.gle/K2LguxW7MWkY3js38)
> Please indicate your interest to become a mentee in the Bioconductor Developer Mentorship program. The Bioconductor Developer Mentorship Program is a Bioconductor Community Advisory Board (CAB) initiative. It is a group-mentorship/buddy program for would-be, new, or hesitant developers or for developers who wish to refresh their skills which will help you get from R scripts to a fully fledged Bioconductor package. Applicant mentees should have a GitHub account and at least R scripts in a public code repository (e.g., GitHub , Gitlab). The R code should demonstrate functionality and the applicant is applying to the mentorship program to package it into an R/Bioconductor package. The mentees should have ownership or explicit permission to use the code. The goal of the program is to welcome and onboard new developers, develop educational material to assist new developers, improve the quality of packages submitted to Bioconductor, and strengthen community and interactions between Bioconductor developers. Each mentorship program cycle will run for one development cycle of Bioconductor package release (approximately 6 months), with the aim to submit a candidate package to the 'Bioconductor/Contributions' GitHub repository ([https://github.com/Bioconductor/Contributions](https://github.com/Bioconductor/Contributions)), with sufficient advance for review ahead of the following release deadline. Mentors are not expected to be co-authors of the resulting package or any associated publication. As such, they also are not expected to contribute to the package in the form of code or documentation. Rather, they can be expected to provide expert advice on best practices and resources for the development and improvement of package functionality and coding practices. Any other agreement should be discussed between mentor, mentee, and supervisor/line manager, if applicable. For more information about the program, see the Bioconductor website ([https://bioconductor.org/](https://bioconductor.org/)) or the Bioconductor 'New Developer Mentorship and Assistance' statement ([https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing](https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing)).

**Vince Carey** (07:34:05) (in thread):
> Thanks for the update Kevin.  I like the thoroughness of the approach.


## 2022-02-03

**Kevin Rue-Albrecht** (10:47:25) (in thread):
> I forgot to merge the PR to the bioconductor website, the new link is now live on the mentorship page:[https://bioconductor.org/developers/new-developer-program/](https://bioconductor.org/developers/new-developer-program/)


## 2022-02-11

**Noriaki Sato** (20:38:00):
> @Noriaki Sato has joined the channel


## 2022-02-24

**Himel Mallick** (11:02:12):
> @Himel Mallick has joined the channel


## 2022-02-25

**Theresa Alexander** (12:32:40):
> @Theresa Alexander has joined the channel

**Nitesh Turaga** (16:35:41):
> @Nitesh Turaga has joined the channel


## 2022-02-28

**Mike Smith** (07:06:39):
> set the channel description: Bioconductor mentorship program to assist new developers and would-be developers to develop a new package. Feel free to talk both the mentorship program itself and to discuss package development.

**Gali Bai** (13:27:22):
> @Gali Bai has joined the channel


## 2022-03-01

**Ramon Massoni-Badosa** (03:32:20):
> @Ramon Massoni-Badosa has joined the channel

**Alexandru-Ioan Voda** (03:32:39):
> @Alexandru-Ioan Voda has joined the channel

**Arshi Arora** (03:33:24):
> @Arshi Arora has joined the channel

**Mike Smith** (03:47:54):
> I'd like to welcome@Ramon Massoni-Badosa@Gali Bai@Alexandru-Ioan Voda@Theresa Alexander@Arshi Arora@Himel Mallickand Pedro Sanchez to Bioconductor slack and this channel.  You're our first cohort of mentees in the Bioconductor Package Developer Mentorship Program and we're really excited to see your progress!
> 
> For some of you the first introduction meetings are starting this week and hopefully you'll have some fruitful discussions with your primary mentors.  However if you have questions or ideas you want to raise between meetings, or you just want to say "Hi" to your fellow package developers feel free to use this channel.  You'll get an answer from any of our current  set of mentors (@Nitesh Turaga@Davide Risso@Kelly Street@Dario Strbenac@Federico Mariniand@Alan O'C) or anyone else in the Bioc community.
> 
> Welcome again and happy coding!

**Dario Strbenac** (03:48:00):
> @Dario Strbenac has joined the channel

**Ramon Massoni-Badosa** (04:24:08):
> Hi all! I'm Ramon Massoni-Badosa, a 4th year PhD student at Holger Heyn's lab. In my research, I use the unprecedented discriminative power of single-cell technologies to reclassify immune cell types, and to study intratumoral heterogeneity and clonal evolution in chronic lymphocytic leukemia (CLL). In the context of the Human Cell Atlas (HCA), we are creating a taxonomy of cell types and states in human tonsils, a model secondary lymphoid organ (SLO). We developed SLOcatoR, a package that provides programmatic access to the tonsil dataset, and allows the user to annotate unseen single-cell transcriptomes and accessibility profiles from SLO. However, it's my first package ever and it can be improved greatly ^^’ That’s why I’m super grateful to all of you for creating this initiative. I'm looking forward to improving my R coding skills, and hopefully this will be the first package of many more to come:slightly_smiling_face:


## 2022-03-02

**Himel Mallick** (09:54:08):
> Hi everyone - so nice to meet you all - I'm Himel Mallick, an Associate Principal Scientist at Merck. I am working on developing methods for omics data science for a while now with special emphasis on microbiome, single-cell, and multi-omics data. We have recently developed an R package for the purpose of conducting differential analysis for multi-platform genomics and digital pathology data. The package has basic functionality in place but it's not a full-fledged package as of yet which is what I am excited to do as part of this program. In addition to networking with the broader Bioconductor community, I'm looking forward to learning the best practices and  putting some of this learning into practice down the line.


## 2022-04-11

**Shani Amarasinghe** (05:49:35):
> @Shani Amarasinghe has joined the channel

**Shani Amarasinghe** (05:55:21):
> Hi all, I'm working for Matt Ritchie at WEHI. We are currently improving our existing sc preprocessing tool ScPipe. I have a question regarding that for which I hope to get some expert advice from the forum. Sorry of this is not the channel I should be posting it to though…We have a bunch of large annotation files (below image to give a snippet) from some which are needed for the upgraded preprocessing pipeline in ScPipe to produce meaningful results. But adding them onto the package would make it too bulky.Can the experts in the house maybe suggest locations where these might be readily accessible or if not what is the norm to make such large files available for R packages? We looked at`ExperimentHub`but it doesn't seem to allow us to upload our own data sets to it (?) We also tried compressing but still they are closer to 1MB each.We can produce a small subsample of annotations. But the purpose here is, if the user specifies for example say "hg38", to load the relevant annotation files and do all the matching in the background without user having to upload the files or worry about their syntaxes.Many thanks in advance.

**Shani Amarasinghe** (05:56:06):
  - File (JPEG): [Image from iOS](https://community-bioc.slack.com/files/U34P8RS3B/F03AYL2NKBM/image_from_ios.jpg)

**Lori Shepherd** (07:03:51) (in thread):
> The AnnotationHub and ExpeirmentHub will allow you to upload your own data sets -- they need to be hosted on a public, trusted server (institutional, aws, data lakes, zenodo) and not something like github and then the hub interface just becomes the pointer to your data.  The hubs will download the files locally however so something like "without user having to upload the files" isn't necessarily possible.


## 2022-04-12

**Shani Amarasinghe** (00:10:47) (in thread):
> Thanks for your feedback@Lori Shepherdand for clearing the doubts I ad about ExperimetnHub. I think we might opt out to show a small sample for the data and point user to a source where they can download the annotations to use if needed.


## 2022-05-16

**Pedro Sanchez** (07:02:11):
> @Pedro Sanchez has joined the channel

**Pedro Sanchez** (07:42:59):
> Hi everyone! I completely missed this channel months ago when I joined as a mentee of the 1st Bioconductor Package Developer Mentorship Program. Happy to say hello to you all although a bit late:zany_face:I currently work in Alejo Rodríguez-Fraticelli’s lab at IRB Barcelona. Here we do bunch of stuff about Hematopoietic Stem Cells mainly studying their heterogeneity during development and disease by mainly using single-cell omics technologies and lineage tracing.
> However, what I have been and am doing as a mentee is to improve the***microSTASIS***R package I developed almost a year ago in my previous lab. It comes to fill the gap of the compositional data analysis applied to microbiome data lacking metrics for evaluating temporal stability of the communities. Not only I am restructuring it to change it from CRAN to Bioconductor but improving it in terms of some theoretical aspects of the main algorithm, allowing its interoperability with TreeSummarizedExperiment object, creating wrappers for users analysing multiple paired times, changing the future ecosystem for BiocParallel and merging some previous split functions.
> Have a nice week!


## 2022-06-17

**George Odette** (17:26:07):
> @George Odette has joined the channel


## 2022-07-29

**Aedin Culhane** (15:59:16):
> Developers forum birds of a feather at Bioc2022 in 45 mins

**Wes W** (17:04:20):
> @Wes W has joined the channel

**Samuel Gamboa** (17:08:17):
> @Samuel Gamboa has joined the channel

**Margaret Turner** (20:16:39):
> @Margaret Turner has joined the channel

**Kristyna Kupkova** (23:58:35):
> @Kristyna Kupkova has joined the channel


## 2022-08-09

**Jared Andrews** (11:49:29):
> @Jared Andrews has joined the channel

**Jared Andrews** (11:50:49):
> Is there any info as to when this process opens to new mentees?


## 2022-08-10

**Kevin Rue-Albrecht** (08:25:01):
> @Jared AndrewsIt is open:
> * [https://bioconductor.org/developers/new-developer-program/](https://bioconductor.org/developers/new-developer-program/)
> * Form ->[https://forms.gle/8yykWfpVT9xyKd9b8](https://forms.gle/8yykWfpVT9xyKd9b8)
> * I just checked and we currently have 5 mentee applicants who have been patiently waiting for some months now. We are limited by the number and availability of volunteer mentors at the moment. We plan to discuss re-opening applications for mentors
  - Attachment (Google Docs): [Bioconductor Mentorship Program - Application form for mentees](https://forms.gle/8yykWfpVT9xyKd9b8)
> Please indicate your interest to become a mentee in the Bioconductor Developer Mentorship program. The Bioconductor Developer Mentorship Program is a Bioconductor Community Advisory Board (CAB) initiative. It is a group-mentorship/buddy program for would-be, new, or hesitant developers or for developers who wish to refresh their skills which will help you get from R scripts to a fully fledged Bioconductor package. Applicant mentees should have a GitHub account and at least R scripts in a public code repository (e.g., GitHub , Gitlab). The R code should demonstrate functionality and the applicant is applying to the mentorship program to package it into an R/Bioconductor package. The mentees should have ownership or explicit permission to use the code. The goal of the program is to welcome and onboard new developers, develop educational material to assist new developers, improve the quality of packages submitted to Bioconductor, and strengthen community and interactions between Bioconductor developers. Each mentorship program cycle will run for one development cycle of Bioconductor package release (approximately 6 months), with the aim to submit a candidate package to the 'Bioconductor/Contributions' GitHub repository ([https://github.com/Bioconductor/Contributions](https://github.com/Bioconductor/Contributions)), with sufficient advance for review ahead of the following release deadline. Mentors are not expected to be co-authors of the resulting package or any associated publication. As such, they also are not expected to contribute to the package in the form of code or documentation. Rather, they can be expected to provide expert advice on best practices and resources for the development and improvement of package functionality and coding practices. Any other agreement should be discussed between mentor, mentee, and supervisor/line manager, if applicable. For more information about the program, see the Bioconductor website ([https://bioconductor.org/](https://bioconductor.org/)) or the Bioconductor 'New Developer Mentorship and Assistance' statement ([https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing](https://docs.google.com/document/d/1Q-Hxmy0ZcKzKSbB-dtg02gJRlZ0Vi6WNOTF-W3bwjmY/edit?usp=sharing)).

**Jared Andrews** (08:33:49):
> I suppose I will apply and do my best. Was hoping someone familiar with shiny would warn me of common pitfalls before I submit.

**Kevin Rue-Albrecht** (08:36:50) (in thread):
> what kind of pitfalls? iSEE made us flirt with a lot of them:wink:

**Jared Andrews** (10:36:03) (in thread):
> Some semblance of testing, any build issues you ran into, any shiny-specific things to be aware of that are likely to get you dinged during the review process, etc.
> 
> The package is here:[https://github.com/j-andrews7/CRISPRball](https://github.com/j-andrews7/CRISPRball)It still needs some polish but is functionally complete for the most part. I guess I should really just take a look at how iSEE and@Federico Marini's stuff handled all of this.

**Jared Andrews** (10:36:49) (in thread):
> I am hoping to get it into the October release, so we'll see how it goes.

**Kevin Rue-Albrecht** (10:48:20) (in thread):
> Yeah.. so, first, testing is a bit of a wild west and depends a lot on how the app itself is written.
> iSEE is again a bit special there, as we're making the shiny app literally write and assemble some R code depending on user inputs, meaning that we can unit test that the expected code is generated for a specific set of inputs.
> 
> You'll also see a lot of`nocov start / nocov end`around observers (e.g.`observeEvent`) because that code isn't run until an app instance is actually running and a user physically interacts with it. I have a feeling that I once read those events can be simulated too, but haven't looked into it since. A google search now reports this poor soul talking to themselves:[https://community.rstudio.com/t/how-do-i-test-an-observeevent-that-updates-an-input-how-do-i-test-a-module-using-shinytest/100537](https://community.rstudio.com/t/how-do-i-test-an-observeevent-that-updates-an-input-how-do-i-test-a-module-using-shinytest/100537)Finally (well.. I could go on forever), you can also get some inspiration from the`test/testthat/setup*`scripts that we use to simulate app states, e.g.[https://github.com/iSEE/iSEE/blob/master/tests/testthat/setup_mimic_live_app.R](https://github.com/iSEE/iSEE/blob/master/tests/testthat/setup_mimic_live_app.R)I'll have a look at your code for a bit now, but before I even start, my best advice is to break down your app as much as you can in regular R functions that you can test like any other package. We haven't gone far into actual shiny testing.
  - Attachment (RStudio Community): [How do I test an observeEvent that updates an input? / How do I test a module using shinytest?](https://community.rstudio.com/t/how-do-i-test-an-observeevent-that-updates-an-input-how-do-i-test-a-module-using-shinytest/100537)
> I have a shiny module that I want to test (see code below) that is part of an app that I have packaged as an R package. The reactive value timeunit_rv holds a state in the app using the module. It can be set by several controls, and as I update one, I want the other controls to be updated too. I would like to write two tests, one for each of the two observeEvents: Test that if I update input$tunit, then timeunit_rv is updated. Test that if I update timeunit_rv, then input$tunit is updated. I...

**Jared Andrews** (10:52:15) (in thread):
> Thanks for the advice. Most of the app is broken up, and given the main focus is on viz/interactivity, there seems to be a lot from iSEE that applies for just testing plot output.
> 
> I do have a few observeEvents that do things on click, but pretty tough to test those.
> 
> I appreciate you taking a look if you have the time. I'll try to add some example input data later today.

**Kevin Rue-Albrecht** (10:56:49) (in thread):
> I'm not going to chase down Fede's package reviews, but my latest  iSEEhex went pretty smoothly here:[https://github.com/Bioconductor/Contributions/issues/2686](https://github.com/Bioconductor/Contributions/issues/2686)It's a minimal extension, so perhaps not so representative of a brand new submission, but it's also a very small package that can give you a sense of what I focus on

**Kevin Rue-Albrecht** (11:09:13) (in thread):
> One positive review from me on your repo already is that you're returning the app to the user. That's good as they have then the chance to invoke`shiny::runApp()`themselves with their own preferred options.
> 
> That said, I see that the man page does not provide a runnable example (wrap it in`if interactive()`). You should add it.
> 
> I see that your README demonstrates a simple call to`CRISPRball()`. Again, I would recommend
> ```
> app <- CRISPRball(...)
> shiny::runApp(app, ...)
> ```
> to illustrate that users can control the parameters of the running app

**Jared Andrews** (11:11:11) (in thread):
> Excellent, easy changes. Yes, pretty much all the functions still need examples, and some are not yet exported (and appropriately documented) that will be.

**Kevin Rue-Albrecht** (11:16:50) (in thread):
> Then, your`CRISPRball()`function is basically 2300 lines long. While it's not wrong to pack it all in one place (I think shiny tutorials about tiny apps do that), you want to consider refactoring bits of UI and server into internal functions that are then called from within the main`CRISPRball()`ball function.
> Our main`iSEE()`function is still ~300 lines long , even after refactoring ~10k lines of code across the whole package.
> However, now we can navigate the codebase by thematically named files that contain bits of app that focus on certain aspects.

**Kevin Rue-Albrecht** (11:20:26) (in thread):
> On a separate perfectionist note, we have also documented our internal functions in iSEE. You'll see that we've given then`@rdname`prefixed with`INTERNAL_*`and that we've added that pattern to our`.gitignore`so that those pages only show up on our developers computers, not in the main documentation.
> Internal documentation proved useful more than once given the shear size of iSEE and the need for coordination between four remote developers (including our own future selves).

**Jared Andrews** (11:31:44) (in thread):
> Yeah, I like how you've handled documenting the internal functions, that's a clever solution.

**Jared Andrews** (11:37:44) (in thread):
> I do want to break the main app up, I'll have to consider how best to do that.


## 2022-08-11

**Kevin Rue-Albrecht** (04:03:41) (in thread):
> All I can advise is to not break up for the sake of it, but to groups things thematically. For instance, none of the observers are defined in the main`iSEE()`function. Instead,`iSEE()`calls the internal`.initialize_server()`which in turns calls various internal functions to initialise the observers (given some persistent and reactive objects that observers will depend on).
> 
> With all that said, I doubt that the BioC review will go to that level of detail. Shiny apps are notoriously painful to review as static code. The important bit for the review is that that app works as seamlessly as possible for users. I'm only emphasising points that will make long-term maintenance easier for yourself

**Kevin Rue-Albrecht** (04:04:45) (in thread):
> I was about to point you to[http://contributions.bioconductor.org/shiny.html?q=shiny#shiny%7C](http://contributions.bioconductor.org/shiny.html?q=shiny#shiny%7C)But I realise that this is mostly a placeholder for guidelines that have not been written yet:slightly_smiling_face:

**Kevin Rue-Albrecht** (04:06:34) (in thread):
> Also, about test, I literally  saw that just this morning[https://www.rstudio.com/blog/four-announcements-from-rstudio-conf-2022/#test-shiny-applications-with-shinytest2](https://www.rstudio.com/blog/four-announcements-from-rstudio-conf-2022/#test-shiny-applications-with-shinytest2)I can't advise from experience. But it might be worth a look
  - Attachment (rstudio.com): [Four announcements from rstudio::conf(2022)](https://www.rstudio.com/blog/four-announcements-from-rstudio-conf-2022/#test-shiny-applications-with-shinytest2)
> rstudio::conf was an eventful four days! This post details some of the bigger announcements from RStudio.

**Shila Ghazanfar** (04:36:54):
> thanks for this thread@Jared Andrewsand@Kevin Rue-Albrecht, i read with a lot of interest! I’m in general interested in how many packages across Bioconductor are including shiny app loaders as part of the package and what (if any) special considerations needed for such packages. I created a#shinychannel with this in mind way back but no activity as yet, this channel could be a place to discuss such topics? just a thought:slightly_smiling_face:pinging@Federico Marinitoo :)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C029XJX3A4F/p1660134829013599?thread_ts=1660134829013599&cid=C029XJX3A4F)
> I suppose I will apply and do my best. Was hoping someone familiar with shiny would warn me of common pitfalls before I submit.

**Kevin Rue-Albrecht** (04:43:14) (in thread):
> Thanks for that!
> I'll be short on volunteering time from September til December (teaching) and I'm also mindful of not talking over the Core Team but I wouldn't mind populating a bit the page[http://contributions.bioconductor.org/shiny.html](http://contributions.bioconductor.org/shiny.html)with my experience (largely iSEE centric).
> That said, even though iSEE is full of examples for shiny in Bioconductor, we'll need to find a way to make the page package-agnostic like the others, in a way that one package does not set the standards for all future ones
  - Attachment (contributions.bioconductor.org): [Chapter 17 Shiny apps | Bioconductor Packages: Development, Maintenance, and Peer Review](http://contributions.bioconductor.org/shiny.html)
> Shiny apps are allowable. Please have all relevant code in the main R/ directory of the package. The bulk of the package code should not be implemented within the Shiny app directly.

**Shila Ghazanfar** (04:45:40) (in thread):
> indeed, thanks so much for this Kevin. i think it makes a lot of sense to populate with a wider array of packages that use shiny in some way — looking at biocViews and searching for “shiny”[https://bioconductor.org/packages/release/BiocViews.html#___Software](https://bioconductor.org/packages/release/BiocViews.html#___Software)brings up 17 packages, so it’s certainly not an anomaly!

**Kevin Rue-Albrecht** (04:48:17) (in thread):
> which makes me think, there should be an`Interactive`BiocViews under`Visualization`
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F03SU6GGFF1/image.png)

**Shila Ghazanfar** (04:48:44) (in thread):
> I’m also curious about the variety of hosted shiny apps out there that make use of bioc and/or highly relevant to users, and can be compiled as a showcase

**Kevin Rue-Albrecht** (04:48:54) (in thread):
> or perhaps`InteractiveVisualization`to avoid any confusion across  all biocviews

**Kevin Rue-Albrecht** (04:49:36) (in thread):
> you're aware of Fede's list right?[https://github.com/federicomarini/awesome-expression-browser](https://github.com/federicomarini/awesome-expression-browser)

**Shila Ghazanfar** (04:50:10) (in thread):
> ahhh.. i am now:smile:thanks for linking!!

**Shila Ghazanfar** (04:50:22) (in thread):
> +1 for`InteractiveVizualisation`

**Kevin Rue-Albrecht** (04:52:11) (in thread):
> It's not all shiny nor bioc, it's a general list of browsers out there, useful to keep track of all the awesome functionality out there. Not one browser has it all, so it's good to know the breadth of tools that offer different functionality

**Vince Carey** (07:05:35) (in thread):
> The awesome-expression-browser resource is daunting.  Are there any prospects of comparing tools in terms of their efficiency in fostering discovery?  Identifying shared components that should be reused and fortified?

**Vince Carey** (07:34:31) (in thread):
> I had a quick look at CRISPRball... are the example data available?  Should we have a class to manage such data?

**Kevin Rue-Albrecht** (09:15:25) (in thread):
> I haven't heard anything recently about prospects for using that list.
> The only recent  benchmark that I can remember is[https://academic.oup.com/nargab/article/2/3/lqaa052/5877814](https://academic.oup.com/nargab/article/2/3/lqaa052/5877814)Although a discussion of the preprint with the authors highlighted the challenge of fairness when comparing programs differing in functionality and default settings (by default iSEE displays all possible panels in a sort of showcase mode which makes it look much slower than a production app configured to display a curated set of panels).
> The idea of identifying and curating good defaults for every program in the awesome-expression-browser resource is daunting itself

**Kevin Rue-Albrecht** (09:16:40) (in thread):
> I also installed the package myself before realising that the example files in the README are not available (or documented as such)

**Jacob Steele** (11:26:00):
> @Jacob Steele has joined the channel

**Jared Andrews** (18:23:31) (in thread):
> I have updated the README and added example data.

**Jared Andrews** (18:29:45) (in thread):
> Features of particular note are the interactivity, full plot customization/re-sizing, gene(set) highlighting, and movable point annotations on click for the "Gene" plots.
> 
> Still a few other things to add/fix beyond general code cleanup and proper docs.

**Shila Ghazanfar** (19:29:59) (in thread):
> maybe it’s useful to think of the different functionalities that are possible with these browsers, off the top of my head things like 1. allows upload of own data, 2. allows download of selected data, 3. static or dynamic plots, 4. performs any hypothesis (e.g. DE) testing on-the-fly, etc…


## 2022-08-12

**Kevin Rue-Albrecht** (04:17:44) (in thread):
> I just tested your example. One point of confusion for me was that, even though the data are provided in the`CRISPRball()`call, the app opens on the data upload page with a bunch of empy file upload fields which made me frantically look further into the README where I should look for those files.
> It's only when I courageously decided to ignore those file upload fields and navigate to the other tabs that I realised the data were indeed processed and available to view in those other tabs.
> I'd suggest that when data are provided to the`CRISPRball()`function, the app either:
> * Hides the Data Upload tab altogether
> * Keep the Data Upload tab but replaces the 'Count Files' and 'Summary Files' boxes by one box that simply displays a message 'Data successfully supplied in function call' (or equivalent)
> * One of the above + immediately switch the view to the QC tab (i.e., the first tab after Data Upload)

**Kevin Rue-Albrecht** (04:19:00) (in thread):
> I hope I'm not sounding too harsh. The app itself works well and In congratulate you on your work so far. I'm just advising from a user experience perspective.

**Kevin Rue-Albrecht** (04:24:12) (in thread):
> (low priority unless it's something you expect users to do often) In the 'Gene Summary Tables', consider whether the 'Copy' button copies [1] all the rows currently visible (i.e., the page of the table currently displayed; seems to be current behaviour), [2] all the rows in the whole table (i.e., across all pages visible and invisible), [3] all the rows that pass any filter (filters on the individual columns and global filter), or [4] the row(s) currently selected.
> All of which are valid choices in their own way, though I don't find the current behaviour particularly logical nor useful. I would lean toward the latter two options, or even better giving users a dropdown of choice among any of the options described above.

**Jared Andrews** (08:04:52) (in thread):
> No, I wholeheartedly welcome these comments, they are not harsh at all. It's suffering from lack of end user use currently and anyone trying it out is a huge boon. I really do appreciate you taking the time to do so.

**Jared Andrews** (11:16:55) (in thread):
> For the table buttons, 3 is intended to be the current behavior, which I**thought**was functional. Will have to take a closer look.

**Kevin Rue-Albrecht** (11:30:52) (in thread):
> Let me know. When I clicked it, the message kept saying 10 rows which was the number shown by page, even though I hadn't filtered anything. Im pretty sure there were more than one page

**Jared Andrews** (11:35:07) (in thread):
> Yeah, I forgot to pass`server = FALSE`to the`renderDT`call, which I had done for the sgRNA tables. Thanks for the catch.


## 2022-08-13

**Kevin Rue-Albrecht** (08:51:17) (in thread):
> You're tempting me to create a repo (maybe a Shiny app:laughing:but more likely a markdown website) where we could set up a template of criteria, and contributors could submit an entry for each tool they review. A github action could collate those entries into a comparative (interactive) table.

**Kevin Rue-Albrecht** (08:53:14) (in thread):
> That said, I'm already investing a ton of time that I don't have into iSEE derivatives (right now,[https://github.com/kevinrue/iSEEhub](https://github.com/kevinrue/iSEEhub)) and I've got teaching duties coming up in September, so I can't promise much resources before Xmas.


## 2022-08-15

**Federico Marini** (10:03:54) (in thread):
> > The awesome-expression-browser resource is daunting. Are there any prospects of comparing tools in terms of their efficiency in fostering discovery? Identifying shared components that should be reused and fortified?
> Indeed daunting, and a little scary considering how much dev time went into a lot of reinvented wheels

**Federico Marini** (10:04:33):
> And yes, I would like to do this kind of exercise of collecting and analyzing what features are in

**Federico Marini** (10:05:26):
> There is a similar work by Vlad Kiselev, more focused on single cell data, but might be a starter

**Federico Marini** (10:05:26):
> [https://academic.oup.com/nargab/article/2/3/lqaa052/5877814](https://academic.oup.com/nargab/article/2/3/lqaa052/5877814)

**Federico Marini** (10:06:02):
> (has some narrower choice of tools)


## 2022-09-21

**Vince Carey** (08:58:19):
> I wonder if it is possible to soften the message of[https://docs.google.com/forms/d/e/1FAIpQLScAtq8x6lPIuzoscRTpHQHNao5AgUDRnx5Ctw_KxV9jadTT_A/closedform](https://docs.google.com/forms/d/e/1FAIpQLScAtq8x6lPIuzoscRTpHQHNao5AgUDRnx5Ctw_KxV9jadTT_A/closedform)... could text be added to indicate that future openings should be available at [approximate date], perhaps also give a link to the heroku app for accessing this channel?@Aedin Culhane

**Kevin Rue-Albrecht** (11:53:52) (in thread):
> I agree, but from what I can see that's an automated Google message, when the form is marked as not accepting new responses, not sure if there is an alternative

**Vince Carey** (20:53:15) (in thread):
> it might need to go in the title   which could be revised when active again?


## 2022-09-23

**Aedin Culhane** (03:19:43) (in thread):
> I agree. Indeed we should have a rolling call /waitlist or regular cycles. We must organize a meeting and decide

**Aedin Culhane** (06:18:22) (in thread):
> Fixed.[https://docs.google.com/forms/d/e/1FAIpQLScAtq8x6lPIuzoscRTpHQHNao5AgUDRnx5Ctw_KxV9jadTT_A/closedform](https://docs.google.com/forms/d/e/1FAIpQLScAtq8x6lPIuzoscRTpHQHNao5AgUDRnx5Ctw_KxV9jadTT_A/closedform)

**Aedin Culhane** (06:18:45) (in thread):
> It now says ‘We are delighted that you are interested in becoming a Bioconductor Mentor to novice developers. We are currently running the 1st cycle of the Bioconductor Mentorship program, and will soon make a call for new mentors. Please check for updates on the program in the Bioconductor slack ([community-bioc.slack.com](http://community-bioc.slack.com)) in the channel#developers-mentorship’

**Aedin Culhane** (06:20:16):
> Just a reminder on the release schedule for Bioconductor 3.16

**Aedin Culhane** (06:20:17):
> ***Friday October 7***
> * ***Deadline for new package submissions.***
> Monday October 10
> * Announce deprecated packages for Bioc 3.16. They’ll be removed from Bioc 3.17. See[End of Life](http://contributions.bioconductor.org/package-end-of-life-policy.html)for details.
> Wednesday October 12
> * No API changes to Bioc 3.16.
> Monday October 17
> * Stop building Bioc 3.15, current release. Commits to this branch will be disabled.
> Wednesday October 19
> * Contributed annotation packages posted to devel annotation data repository.
> * Bioconductor 3.16 release candidate. Package maintainers should limit changes to “show-stopper” bugs and documentation improvements.
> Monday October 24
> * Start building Bioc 3.17.
> ***Wednesday October 26***
> * ***Deadline to add new packages to the Bioc 3.16 manifest. Package submitted to tracker must have completed the review processes and been accepted to be added to the manifest***
> ***Friday October 28***
> * ***Deadline for packages passing ‘’R CMD build’’ and ‘’R CMD check’’ without errors or warnings. This includes software, data experiment and workflow packages. Some warnings will be accepted, clarification on the bioc-devel mailing list.***
> Monday October 31
> * Last day to commit changes to the Bioc 3.16 branch. NEWS files must be updated before the builds start at 1:30 pm EST or they will not be included in the release announcement.
> * The branch will be frozen prior to creating the release branch on Tuesday, November 1. Committing last minute changes could break your package in both release and devel! Be sure to run ‘R CMD build’ and ‘R CMD check’ locally before committing any changes.
> Tuesday November 1
> * Creation of the Bioc 3.16 release branch. Development can resume on trunk, but changes there will not be part of the release.
> Wednesday November 2
> * Bioconductor Release 3.16.

**Aedin Culhane** (06:34:12):
> <!channel>We are thinking of holding a celebration of work from the developer mentorship program where each mentee will have the opportunity to present their package.  What windows of time works for everyone? Please respond with your timezone.  For common timezones, emojis are  EST (:us:), CEST (:flag-eu:) , GMT/BST (:gb:)

**Federico Marini** (07:58:18) (in thread):
> I have Ramon:flag-eu:(progress good) , and Himel & Gali (both:flag-us::flag-us:) - more on the on hold side of it

**Shila Ghazanfar** (11:13:02) (in thread):
> I absolutely love this!!!


## 2022-09-25

**Maria Doyle** (20:53:13):
> @Maria Doyle has joined the channel


## 2022-09-26

**Aedin Culhane** (17:45:13) (in thread):
> Any more time zones?@Kelly Streetis in PST. So it looks like 11am  EST might be a good time? (8am PST, 5pm CEST if my time zone math is correct). Now just need to work out a date  in October that works for most.


## 2023-01-10

**Atuhurira Kirabo Kakopo** (10:52:08):
> @Atuhurira Kirabo Kakopo has joined the channel


## 2023-01-21

**Hien** (16:02:07):
> @Hien has joined the channel


## 2023-03-01

**jeremymchacón** (12:12:10):
> @jeremymchacón has joined the channel


## 2023-05-18

**Sarvesh Nikumbh** (03:39:29):
> @Sarvesh Nikumbh has joined the channel


## 2023-06-07

**Alyssa Obermayer** (18:29:17):
> @Alyssa Obermayer has joined the channel


## 2023-08-03

**Ritika Giri** (15:57:36):
> @Ritika Giri has joined the channel


## 2023-10-15

**Karthik Desingu** (23:55:27):
> @Karthik Desingu has joined the channel


## 2023-10-24

**Louis Le Nézet** (09:51:27):
> @Louis Le Nézet has joined the channel

**Louis Le Nézet** (09:55:17):
> Hi,
> I would like to know if there are plans for a new series of mentoring programs in the future.
> I would be really interested:slightly_smiling_face:Thanks


## 2023-11-24

**Kevin Rue-Albrecht** (04:10:36) (in thread):
> Therearen’tany dates set, but there in is ongoing effort to get funding and support this in a more sustainable way.


## 2024-02-12

**Aedin Culhane** (03:37:29) (in thread):
> Are you interested as mentor or mentee ?

**Louis Le Nézet** (04:54:19) (in thread):
> I would be interested as a mentee.


## 2024-02-14

**Patrizia Piotti** (13:00:51):
> @Patrizia Piotti has joined the channel


## 2024-03-13

**Kelly Street** (19:44:46) (in thread):
> Just wanted to check in and see if there was any update on this? I’d be happy to serve as a mentor again!


## 2024-03-14

**Kevin Rue-Albrecht** (01:01:58) (in thread):
> the CZI grant decision should come in sometime this month (March 2024)


## 2024-03-15

**Peace Sandy** (09:00:25):
> @Peace Sandy has joined the channel


## 2024-03-26

**Maria Doyle** (07:40:22) (in thread):
> Hi Kelly,
> Just wanted to add your willingness to mentor again is very appreciated.
> We’ll update on the grant decision here.

**Kelly Street** (13:51:08) (in thread):
> Thanks! And sounds good, fingers crossed!


## 2024-03-27

**Jovana Maksimovic** (00:39:40):
> @Jovana Maksimovic has joined the channel


## 2024-07-11

**Sathish Kumar** (06:06:41):
> @Sathish Kumar has joined the channel


## 2024-07-29

**JP Flores** (17:10:02):
> @JP Flores has joined the channel


## 2024-10-02

**Eva Hamrud** (19:06:14):
> @Eva Hamrud has joined the channel


## 2024-12-28

**Michael Hungbo** (07:30:15):
> @Michael Hungbo has joined the channel


## 2025-01-09

**Ammar Sabir Cheema** (11:37:28):
> @Ammar Sabir Cheema has joined the channel


## 2025-02-13

**Anushka Paharia** (15:12:53):
> @Anushka Paharia has joined the channel


## 2025-02-19

**Idowu Festus** (04:49:23):
> @Idowu Festus has joined the channel


## 2025-03-18

**Nicolo** (14:58:54):
> @Nicolo has joined the channel
