---
title: "#diversebioc"
---

## 2019-06-28

**Aedin Culhane** (15:59:04):
> @Aedin Culhane has joined the channel

**Aedin Culhane** (15:59:05):
> set the channel description: Discussion forum for diversity in Bioconductor

**Martin Morgan** (15:59:05):
> @Martin Morgan has joined the channel

**Vince Carey** (15:59:05):
> @Vince Carey has joined the channel

**Levi Waldron** (15:59:05):
> @Levi Waldron has joined the channel

**Laurent Gatto** (15:59:05):
> @Laurent Gatto has joined the channel

**Aedin Culhane** (16:00:18):
> set the channel description: DiverseBioc : Discussion of diversity in Bioconductor

**Aedin Culhane** (16:02:35):
> A few people asked how many female/minority developer are in Bioc. Could we do a survey of developers/maintainers. I would be eager to know how many developers/package maintainers are located in Boston, so I could invite speakers for our local meetup

**Laurent Gatto** (16:20:18):
> If I remember well, a diversity R group assessed gender ration among package developers using names to infer gender, which wasn't well received due to the implicit implication of name and gender.
> Perhaps an anonymous questionnaire on the support site and social media would work.

**Martin Morgan** (17:06:31):
> Thanks@Aedin Culhanefor creating this channel; it would be great to identify ways to quantify the current situation, and more importantly to remedy the inequities that surely exist. The Maintainer first names are easily obtained via`BiocPkgTools::biocPkgList("3.9")[,"Maintainer"]`and might be a starting point;`gender::gender()`assigns binary and also continuous gender, and reports the number of unassigned individuals; certainly one could be more sophisticated...


## 2019-06-29

**Sean Davis** (21:10:38):
> @Sean Davis has joined the channel

**Davide Risso** (23:06:40):
> @Davide Risso has joined the channel

**Simina Boca** (23:07:08):
> @Simina Boca has joined the channel

**Levi Waldron** (23:13:00):
> I wanted to respond to the issue of gender imbalance of speakers during the Robert Gentleman symposium that@Rob Amezquitaraised on Twitter ([https://twitter.com/robamezquita/status/1145052861526695941](https://twitter.com/robamezquita/status/1145052861526695941)). I’m hesitant to reply on Twitter because I found it especially difficult to reply without the multi-thread you get in initial composing, and because Twitter does not remove anonymous trolls like the one who has been insulting and name-calling#bioc2019participants ([https://twitter.com/SPollack15/with_replies](https://twitter.com/SPollack15/with_replies)), instead only removing their individual tweets that called people four-letter words.
  - Attachment (twitter): [Attachment](https://twitter.com/robamezquita/status/1145052861526695941)
> After seeing amazing role models of courage from [@CrowellHL](https://twitter.com/CrowellHL) and [@cmirzayi](https://twitter.com/cmirzayi) speaking out, I want to also say a few words about something that bothered me - to put it lightly - about #BioC2019
  - Attachment (twitter.com): [Login on Twitter](https://twitter.com/SPollack15/with_replies)
> Welcome back to Twitter. Sign in now to check your notifications, join the conversation and catch up on Tweets from the people you follow.

**Rob Amezquita** (23:13:11):
> @Rob Amezquita has joined the channel

**Levi Waldron** (23:13:36):
> set the channel topic: Discussion of diversity and inclusiveness of the Bioconductor community.

**Levi Waldron** (23:16:38):
> I can speak to the Robert Gentleman symposium, summarizing the discussion I gave at the start of the session on evolution of the R/Bioconductor communities.@Rob Amezquita, I’m not sure if you heard that introduction and still had the same concern, or missed it, so I’ll summarize, also for others who weren’t there.

**Levi Waldron** (23:22:58):
> Organizers (not the same organizing committee as BioC2019) noticed and were concerned by the gender imbalance of the speakers, all chosen for having worked with RG during early development of R/Bioconductor. We discussed two remedies:
> 
>     1) invite more women speakers, although they would have had no such connection to the symposium’s theme, and risk making them feel token or being seen so by audience members. That seemed problematic and anti-productive towards the larger goal of promoting women scientists.
>     2) address the problem head-on, with an open discussion of how gender imbalance of that day’s speakers arose from imbalances existing in the earlier days or R/Bioconductor, how Bioconductor is now working to increase the diversity of its community, and discuss current barriers to women advancing in our field.
> 
> I hope you’ll agree that option 2 was the more progressive and productive option for the goal of increasing diversity in our field and the Bioconductor community specifically. Happy to discuss further though.

**Zachary Brehm** (23:32:39):
> @Zachary Brehm has joined the channel

**Lorena Pantano** (23:34:54):
> @Lorena Pantano has joined the channel


## 2019-06-30

**Lukas Weber** (00:06:32):
> @Lukas Weber has joined the channel

**Charlotte Soneson** (01:30:53):
> @Charlotte Soneson has joined the channel

**James Taylor** (01:54:46):
> @James Taylor has joined the channel

**Joselyn Chávez** (02:17:50):
> @Joselyn Chávez has joined the channel

**Matt Brauer** (03:37:00):
> @Matt Brauer has joined the channel

**Kevin Rue-Albrecht** (04:54:05):
> @Kevin Rue-Albrecht has joined the channel

**Charlotte Soneson** (05:07:59):
> [https://community-bioc.slack.com/archives/CL21357E2/p1561755991011300](https://community-bioc.slack.com/archives/CL21357E2/p1561755991011300)FWIW, I tried this approach some time ago, and I found it quite difficult to get reliable results in an automated way, especially without additional information (for example, many names are typically male in some countries and typically female in other). The`gender`and`genderizeR`packages implement several “methods” (underlying data sets), but there didn’t seem to be enough geographic diversity in any of them, and there were lots of names that were not assigned (including, of course, all the maintainers only providing initials), or that I could identify as misassigned by manual inspection. As an example though, these are the results I would get with two of the methods that seemed to do “best” (numbers represent unique maintainers, not packages):
> ```{genderize}
> kantrowitz female male <NA>
>     either     16   69    0
>     female    111    8    0
>     male        1  456    0
>     <NA>      113  223  167
> ```
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CL21357E2/p1561755991011300)
> Thanks @Aedin Culhane for creating this channel; it would be great to identify ways to quantify the current situation, and more importantly to remedy the inequities that surely exist. The Maintainer first names are easily obtained via `BiocPkgTools::biocPkgList("3.9")[,"Maintainer"]`  and might be a starting point; `gender::gender()` assigns binary and also continuous gender, and reports the number of unassigned individuals; certainly one could be more sophisticated...

**Kayla Interdonato** (05:43:12):
> @Kayla Interdonato has joined the channel

**Stephanie Hicks** (06:19:31):
> @Stephanie Hicks has joined the channel

**Martin Morgan** (06:29:35) (in thread):
> Offering this more as tips-and-tricks for parsing Bioc package metadata than pretending to know what I'm doing statistically. Keeping caveats in mind, it might be interesting to look at historical versus recent submissions, like Figure 2 of[http://bioconductor.org/about/annual-reports/AnnRep2019.pdf](http://bioconductor.org/about/annual-reports/AnnRep2019.pdf)does for biocViews terms. The basic strategy was to use`BiocPkgTools::biocPkgList()`to get two releases, and ask about the increment of packages between them. A public gist of my full code is at[https://gist.github.com/mtmorgan/464028015c4944b45832f9c0d1d26b6a](https://gist.github.com/mtmorgan/464028015c4944b45832f9c0d1d26b6a)

**Charlotte Soneson** (07:03:54) (in thread):
> Is there a way to get to the “In Bioconductor since” information programmatically?

**Martin Morgan** (07:14:52) (in thread):
> @Lori Shepherdwill know; I know a file is generated with that information (I think from`git clone `[git@git.bioconductor.org](mailto:git@git.bioconductor.org)`:admin/manifest`(I think that's a public repository...) but I'm not sure if it is on the public server. I used the setdiff() between manifests of each release as an indication of age.

**Lori Shepherd** (07:15:01):
> @Lori Shepherd has joined the channel

**Abbas Rizvi** (08:31:50):
> @Abbas Rizvi has joined the channel

**Charlotte Soneson** (09:03:13) (in thread):
> With all the caveats above (and probably more, I wouldn’t trust the precise numbers), this is what it looks like since version 2.1, using different databases to assign gender to names (Maint = fraction of female maintainers, Pkg = fraction of packages maintained by female maintainers). Gist here:[https://gist.github.com/csoneson/56bf3331df6f1f451f5b4dc410aa1e66](https://gist.github.com/csoneson/56bf3331df6f1f451f5b4dc410aa1e66)
  - File (PNG): [Screen Shot 2019-06-30 at 15.02.16.png](https://community-bioc.slack.com/files/U34P8RS3B/FL2CZHQ31/screen_shot_2019-06-30_at_15.02.16.png)

**Martin Morgan** (09:33:05) (in thread):
> These are the genders of the maintainers of all packages in the release, rather than of packages added in the release? So current releases are influenced by historical fractions? If helpful, the dates of the releases are available at[http://bioconductor.org/about/release-announcements/](http://bioconductor.org/about/release-announcements/)
> ```
> url = "[http://bioconductor.org/about/release-announcements/](http://bioconductor.org/about/release-announcements/)"
> res = httr::GET(url)
> html = httr::content(res)
> release = xml2::xml_find_all(html, "//table[2]//td[1]//text()") %>% as.character()
> date = xml2::xml_find_all(html, "//table[2]//td[2]//text()") %>% as.character()
> ```

**Martin Morgan** (09:42:16) (in thread):
> 2.12 was released in April, 2013; it's interesting perhaps to note the apparent rate of increase of the number of new packages added to the project sometime between 2010 and 2015 (from slide 6 of my dday update,[https://docs.google.com/presentation/d/1S_e9g5OfpJK51TxiUWTKbqomutCsUJ2qgmio_g_qN-E/edit?usp=sharing](https://docs.google.com/presentation/d/1S_e9g5OfpJK51TxiUWTKbqomutCsUJ2qgmio_g_qN-E/edit?usp=sharing)). I don't think this corresponds to any infrastructure changes on our part, e.g., the support site, transition to using git, using public reviews, updated web site, etc. Rise of MOOCS? Rise of tidyverse / good documentation on package building in general (it seems a bit early for that?). Rise of the 'data scientist' ?

**Stuart Lee** (10:08:43):
> @Stuart Lee has joined the channel

**Daniela Cassol** (10:12:09):
> @Daniela Cassol has joined the channel

**Charlotte Soneson** (10:27:25) (in thread):
> Yes, figure above is all packages in a given release. Only considering new packages (with version = 1.0.x) gives left panel here:
  - File (PNG): [Screen Shot 2019-06-30 at 16.23.47.png](https://community-bioc.slack.com/files/U34P8RS3B/FKU7N35TK/screen_shot_2019-06-30_at_16.23.47.png)

**Nitesh Turaga** (10:37:14):
> @Nitesh Turaga has joined the channel

**Sridhar N** (10:39:43):
> @Sridhar N has joined the channel

**Nitesh Turaga** (10:47:27):
> @Charlotte SonesonYou can access the manifest. It is a public repo,`git clone `[https://git.bioconductor.org/admin/manifest](https://git.bioconductor.org/admin/manifest)

**Charlotte Soneson** (10:48:57):
> @Nitesh TuragaThanks!

**Nitesh Turaga** (10:58:34) (in thread):
> It might help if the community reports the user. This is extreme.

**Marcel Ramos Pérez** (11:07:45):
> @Marcel Ramos Pérez has joined the channel

**Laurent Gatto** (11:35:11) (in thread):
> Several of us have already.

**Abbas Rizvi** (13:04:44):
> @Abbas Rizvi has left the channel

**Sean Davis** (14:22:47) (in thread):
> Given the potentially larger geographical diversity in CRAN, it might be difficult to make a quantitative comparison using the name-based approach. But I do wonder what such a comparison might show, even qualitatively.

**Stephanie Hicks** (14:39:38):
> Thank you@Aedin Culhanefor creating this channel. One thing that i’m interested in discussing is what are some barriers that people have felt when joining the bioc community (or open source software communities in general) and what would be some ways of overcoming those barriers?

**Aedin Culhane** (14:43:10):
> I think the first thing we need is to ensure everyone knows about slack and can join. Of all of the recent forums I feel slack is a great way that everyone can contribute.

**Michael Love** (14:49:03):
> @Michael Love has joined the channel

**Aedin Culhane** (14:52:02):
> Secondly I agree beginners documentation is important.  People need to be able to find it (on the website.. so that needs to be better) We held two meetups on marking a R and BioC package. The aim was to make a bookdown and distribute these but we got busy.@Kylie Bemis@BJ Stubbs. Perhaps Bioc should apply for the recent CZI call to 1) update/replace website 2) create beginner documentation and training courses. 3) ??? data Carpentry.

**Aedin Culhane** (14:58:23):
> This year there was an open call to be part of the conference committee. Should that could be formalized. With an election of members open to all?

**Aedin Culhane** (16:17:30):
> What do others see in other communities. What ideas should Bioc borrow/adpot?

**Charlotte Soneson** (16:55:58) (in thread):
> Same approach on CRAN gives
> ```
> fracFemalePkgSSA          0.1436993
> fracFemaleMaintSSA        0.1724629
> fracFemalePkgKantrowitz   0.1109601
> fracFemaleMaintKantrowitz 0.1460302
> fracFemalePkgGenderize    0.1462206
> fracFemaleMaintGenderize  0.1788013
> ```

**Levi Waldron** (22:45:05) (in thread):
> There was no election - anyone who expressed interest was then a part of the conference committee.


## 2019-07-01

**FeiZhao** (01:29:06):
> @FeiZhao has joined the channel

**Lluís Revilla** (03:39:54):
> @Lluís Revilla has joined the channel

**Laurent Gatto** (03:43:27):
> I think that rOpenSci and RStudio might be organisation that do particularly well in terms of inclusion and diversity - we could possibly get in touch with them for idea to adopt?

**Charlotte Soneson** (09:02:29) (in thread):
> I also recently started composing a little guide to writing Bioconductor packages since a couple of people in the institute where I work wanted to get into it. It is a bit immature and needs more work, but I’m happy to share what I have if anyone is interested/want to combine efforts.

**Leonardo Collado Torres** (10:42:11):
> @Leonardo Collado Torres has joined the channel

**Domenick Braccia** (10:44:15):
> @Domenick Braccia has joined the channel

**Rob Amezquita** (13:35:50) (in thread):
> absolutely Levi, I think it was the best of a not ideal situation, I'm sorry for not recognizing the effort therein to make the best of what it was, recognizing it out loud was the right way to go

**Rob Amezquita** (13:37:22) (in thread):
> Absolutely would be happy to be part of this effort as well to contribute to editing/reading/testing!

**Andrew McDavid** (14:08:29):
> @Andrew McDavid has joined the channel

**Marko Zecevic** (14:54:22):
> @Marko Zecevic has joined the channel

**Sean Davis** (16:29:51) (in thread):
> Thanks,@Charlotte Soneson. That does feel like a difference to me, but of course the goal isn’t really to “be better than CRAN”.

**Aedin Culhane** (20:53:01):
> Good idea Laurent

**Aedin Culhane** (21:00:41) (in thread):
> Rob on twitter, I was very concerned at the serious comments/allegations about your experience of the  Bioconductor conference. Please do submit an form to the CoC  if you want these investigated and followed up on.  Unfortunately, the CoC can't follow up tweets.[https://twitter.com/robamezquita/status/1145052861526695941](https://twitter.com/robamezquita/status/1145052861526695941)
  - Attachment (twitter): [Attachment](https://twitter.com/robamezquita/status/1145052861526695941)
> After seeing amazing role models of courage from [@CrowellHL](https://twitter.com/CrowellHL) and [@cmirzayi](https://twitter.com/cmirzayi) speaking out, I want to also say a few words about something that bothered me - to put it lightly - about #BioC2019

**Aedin Culhane** (21:02:31) (in thread):
> @Charlotte Sonesonthe making Bioc package guides were pretty significant (as they were presented at the meetup).  I'll put you in contact with authors@Kylie Bemisand@BJ Stubbsto join forces perhaps.

**Kylie Bemis** (21:02:35):
> @Kylie Bemis has joined the channel

**BJ Stubbs** (21:02:35):
> @BJ Stubbs has joined the channel

**Aedin Culhane** (21:05:20) (in thread):
> So the question is whether everyone who wanted to be part of the Bioc2019, saw the announcement and whether the committee should be selected to be more diverse.[http://bioc2019.bioconductor.org/organizers](http://bioc2019.bioconductor.org/organizers)
  - Attachment (BioC 2019): [BioC 2019: Where Software and Biology Connect](http://bioc2019.bioconductor.org/organizers)
> Where Software and Biology Connect. June 24 - 27, New York City, USA.

**Aedin Culhane** (21:05:57) (in thread):
  - File (PNG): [Screen Shot 2019-07-01 at 9.05.31 PM.png](https://community-bioc.slack.com/files/U34P8RS3B/FL20SLPLM/screen_shot_2019-07-01_at_9.05.31_pm.png)

**Aedin Culhane** (21:07:54) (in thread):
> Invited speakers were 50:50 male  female for the main conference, should that be extended to devel day, contributed talks, workshops. etc  The community that attends the meeting is not 50:50, martin shares statistics on attendees on twitter

**Aedin Culhane** (21:09:11) (in thread):
> What barriers have you identified?

**Aedin Culhane** (21:12:37) (in thread):
> Rob did you see my talk on diversity and gender in R/Biostats, academic and tech.  It included a sectioning on engaging women in hackathons (from Ben Busby and Allissa Dillman). I am happy to share my slides with you


## 2019-07-02

**Lorena Pantano** (09:51:04):
> After some years running a meetup in boston for woman in bioinformatics I learnt some reasons why many women don’t go to ‘developers days’ like events. Many of them say that their work is not that good /important and they feel people will criticize (not nicely) their work. They are afraid is not a supportive environment.  So I see two main targets to help, a) one is to make sure minorities like women, knows that their work is good and enough, and. b) to tell them that is a good environment where they can feel safe. If you meet a woman during the year who works in a R package, encourage her to go to the event.

**Nitesh Turaga** (09:58:00):
> @Lorena PantanoGreat point! Do you think the name "developer day"  makes it less approachable? The Galaxy project (from what I recall) changed the name from "developer day" to "Training day" or "Collaboration Fest". I can see why the name "developer day" can be daunting to folks. It might be useful to reach out to them and ask them if they see more balance post name change (if it did happen).

**Kevin Rue-Albrecht** (10:12:04):
> I’m in favour of possibly renaming the day. Good start@Nitesh Turaga. I just find “training” at the other extreme of the spectrum, possibly obscuring the part where developers can just give a short flashtalk rather actually train anyone.
> How about “Community day”?
> From my user/developer perspective after attending 2 editions, this day is a chance for developers to showcase their work (flashtalks, workshops) and users to approach developers (BoF, workshops).

**Lorena Pantano** (10:45:26):
> @Nitesh Turaga, actually that could be a great point.@Kevin Rue-Albrechtis a good point, something like Community day or Collaboration day/fest seems good options to me.

**TomCarroll** (11:10:03):
> @TomCarroll has joined the channel

**Hervé Pagès** (14:23:04):
> @Hervé Pagès has joined the channel

**Rob Amezquita** (14:43:30) (in thread):
> @Aedin Culhaneyes I did, I really enjoyed your talk! I actually did get to participate in a hackathon led by Ben Busby (I don't think I met Allissa) and was similarly impressed with how they've modernized hackathon culture compared to when I participated several years back

**Ana Beatriz Villaseñor Altamirano** (15:07:18):
> @Ana Beatriz Villaseñor Altamirano has joined the channel

**Ana Beatriz Villaseñor Altamirano** (15:29:05) (in thread):
> Data Carpentry (or -like) workshops for beginners would be a great idea, I think there are a couple of instructors in BioC. And Carpentry has been working in translating the material (to Spanish) so more beginners can use it.

**Ana Beatriz Villaseñor Altamirano** (15:34:20) (in thread):
> Official videos on youtube? (no more than 20 minutes), also a blog with maybe a small comment/opinion/explanation from different BioC members every week/month?

**Stephanie Hicks** (20:14:51) (in thread):
> I like how Galaxy’s conference name shifted to the name**UseGalaxy**

**Marcel Ramos Pérez** (20:21:20) (in thread):
> There's also the useR conference.. I'd support the suggestions: useBioC / useBioconductor as well

**Nitesh Turaga** (20:24:31) (in thread):
> I don't think Galaxy conference name changed. It's always been "Galaxy Community Conference". Their twitter tag has always been #usegalaxy, because their main server's website is also[usegalaxy.com](http://usegalaxy.com). I could be wrong though. The website still looks the same from last time I checked.

**Nitesh Turaga** (20:29:08):
> There was some acceptance to the idea of a potential name change to "developer" day.  If we come up with a name which better reflects the low entry barrier to the event, we could suggest something. But@Kevin Rue-Albrechtis correct, that there should be some level of clarity in that, these events on the "developer" day will have welcome a diverse group who are old/new/beginner/just wanted to test waters/advanced bioc-developers.

**Nitesh Turaga** (20:32:44) (in thread):
> But were the suggestions, useBioc, or useBioconductor for renaming developer day?

**Marcel Ramos Pérez** (20:40:25) (in thread):
> I thought I saw one of these suggestions in the feed at some point. Yes, they're for renaming developer day or potentially even the conference. Perhaps we should have a poll of some sort?

**Nitesh Turaga** (20:41:47) (in thread):
> +1 for the poll.

**Stephanie Hicks** (21:07:21) (in thread):
> i had suggested it on the main channel, but then deleted the comment because I realized the idea was not be to rename the entire bioc conference, just developer day. and wasn’t sure if UseBioc / UseBioconductor was meant for just developer day or the entire thing

**Stephanie Hicks** (21:09:29) (in thread):
> ooooh i now remember where I got the idea that the entire galaxy conference was renamed to**UseGalaxy**: I saw this tweet the other day[https://twitter.com/jxtx/status/1145964742625955841?s=20](https://twitter.com/jxtx/status/1145964742625955841?s=20)
  - Attachment (twitter): [Attachment](https://twitter.com/jxtx/status/1145964742625955841?s=20)
> For those who think we can't count, the first #useGalaxy conference was at [@cshlmeetings](https://twitter.com/cshlmeetings) in 2010. Called the Galaxy Developer Conference at the time, but we retroactively rebranded it. [https://pbs.twimg.com/media/D-dIm-_WwAA_hSa.jpg](https://pbs.twimg.com/media/D-dIm-_WwAA_hSa.jpg)

**Nitesh Turaga** (21:10:31) (in thread):
> I see:grin:

**Nitesh Turaga** (21:11:50) (in thread):
> "Community day" is a pretty good idea.

**Stephanie Hicks** (21:24:12) (in thread):
> One big barrier that I have felt is a lack of concise, clear, cohesive newcomer support. e.g. the set of challenges to overcome that newcomers to bioc face to make their first contribution (from something as small as a pull request to fix a bug to a full fledge bioc package). The period of time between when a new person decides they want to contribute and when their first code is contributed in my mind is critical. If newcomers face too many barriers or the project doesn’t make a good first impression, the newcomer might give up and wait a long time before trying again. There is for sure a lot of**wonderful**material developed by many bioc leaders, but it can sometimes require quite a bit of sifting through from a newcomer’s perspective (vs having a landing page specific to newcomers which could then link out to all the great material already developed)

**Stephanie Hicks** (21:25:08) (in thread):
> similar to the idea of teaching students base r graphics vs ggplot2. someone who is new to R tends to do really well when you can get them to create a beautiful data viz as fast and as simple as possible, with just a few lines of code. Afterwards, they tend to be more willing to dig into the details of**why**or**how**the code works (or even modify / play around with the code to create a second plot). I think one goal of ours should be to try and minimize the amount of time it takes between a newcomer deciding they want to contribute and their first contribution (even if it’s super small).

**Stephanie Hicks** (21:26:28) (in thread):
> it is!

**Stephanie Hicks** (21:34:56):
> And I don’t think there is just one solution to the above. Many things could help. Better documentation / less information overload, maybe a tutorial on how to make contributions ranging from big to small (but highlighting examples of the small tasks that can get someone started), better understanding of overall project architecture, better/different website, etc


## 2019-07-03

**Aedin Culhane** (01:07:36) (in thread):
> [https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/)
  - Attachment (Chan Zuckerberg Initiative): [Essential Open Source Software for Science](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/)
> The Chan Zuckerberg Initiative is inviting applications for one-year open source software projects that are essential to biomedical research. This RFA is the first of a series. CZI will invite applications during three distinct cycles, with rounds beginning June 18, 2019; mid-December 2019; and mid-June 2020.

**Stephanie Hicks** (06:27:19) (in thread):
> @Aedin Culhanewould you/others be interested in helping to write?:grin:I’m happy to help write a grant, but I think we (BioC) need to first agree whether this is a barrier that others have felt? I acknowledge this is just my perspective. Also, you mentioned at the conference and on Slack you have a lot of new material that you have been working on for newcomers?

**Kevin Rue-Albrecht** (06:35:14) (in thread):
> Incidentally, I made a relevant point in the#gseabasechannel ([https://community-bioc.slack.com/archives/CEK3JDXFV/p1562143141107500](https://community-bioc.slack.com/archives/CEK3JDXFV/p1562143141107500)).
> Contributing and maintaining (good) packages is a massive commitment of time and brainpower that is often not supported in time or funding in research groups that are focused on biological/medical research and high-throughput publications.
> From personal experience, I have invested a LOT of personal time to learn Bioc-best-practice of package development including reading some core packages, sometimes creating friction with my group leader due to distraction from the research work that I am expected/paid to do. I have both the satisfaction of having contributed code that I am proud of, but also fear some level of negative impact on future recommendations [because “this isn’t what we do”].
> Maybe it’s just me picking research positions that are not aligned [close enough] with my passion for software development, but aside from being a Bioc core member or close collaborator, I’d argue that I find it hard to find groups that have the time, funding, and freedom to cross the bridge from users to community-trusted developers.
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CEK3JDXFV/p1562143141107500)
> @Aedin Culhane Thanks a ton for the feedback at the conference. I’ve added a couple of points to what Lluis already wrote (thanks!)
> There was certainly a lot of feedback and suggestions for each package/developer to do further testing before claiming to replace `GSEBase`.
> 
> From my (`unisets`) perspective, I already addressed a couple of downstream use cases (what motivated `unisets` in the first place) with the `hancock` package (see BoF slides linked in the Google docs).
> That said, the development and support of such an important package requires time and effort that is not supported by my current (postdoc researcher) position (until September 2020). As I understand it, Lluis is in a similar position at the moment. As such, Kayla has the edge of having dedicated time and support on her side.
> 
> I was probably too shy to ask at the conference, but I do wonder how non-core developers like me or Lluis can hope to obtain dedicated time and support to explore and develop such candidate core packages. As much as I would love to spend my days working on gene set representations and downstream analyses, for the next couple of months, my (paid for) priorities have to be on finishing up overdue analyses and writing an article.
> 
> One thing that I experienced with `iSEE` is that having a small group of developers thinking alike can significantly speed up the process, where one picks up where the other one is stuck or tired. This is more difficult in our  “gene set” case where the 3 of us have split very early on into mutually exclusive implementations (tidyverse/S4/hybrid).

**Kevin Rue-Albrecht** (06:59:25) (in thread):
> Put briefly, I guess what I’m trying to say here is that to me the most immediate barrier to join (and remain active in) the community is either:
> - a**strong**will to do so (at the risk of stepping on some feet along the way)
> - or the chance to spend time in a group that is already closely involved in Bioc, with expertise and dedicated time

**Martin Morgan** (07:57:03) (in thread):
> FWIW I'd be up for**supporting**such an effort, e.g., with letter of support and promise of high profile on the Bioc web site / etc. I'm also eager to**contribute**but not in a way that the endeavor would depend on me, because that would just end in  [:tears:] (why do they never have the emoji I want?)

**Stephanie Hicks** (09:18:27) (in thread):
> @Martin MorganI think you are looking for:sob:…..:wink:

**Sean Davis** (10:49:55):
> I have recently started teaching “how to create an R package” to students who are new to R and Bioconductor. I find that one of the largest barriers to contribution to R is the lack of understanding of what an R package is, how an R package can be useful in daily work, and how simple it is to share work via an R package and social coding platforms like GitHub. I am also starting to focus on the “sharing” aspects of R packages, not just the software. Sharing data via data packages is often more attractive to folks new to R than is sharing “code”, particularly since many students are not confident enough to share code, but are excited to share data with collaborators, etc.

**Sean Davis** (10:52:33):
> All that said, adult learners are, as@Stephanie Hickspoints out, are driven by productivity and confidence, not necessarily by knowledge. For newcomers, focusing less on knowledge transfer and, instead, establishing environments that helps newcomers build confidence (through success and productivity) is valuable.

**Sean Davis** (10:55:17):
> I’ll see if I can find some literature and materials on adult learning and share here. Perhaps others can do the same. We made an attempt last year to have the workshops adopt a more pedagogical approach by establishing learning goals, objectives, and prereqs. We should continue to advance the best practices for adult learning so that our existing efforts as well as new ones are most effective.

**Kelly Street** (15:33:13):
> @Kelly Street has joined the channel

**Robert Castelo** (17:15:21):
> @Robert Castelo has joined the channel


## 2019-07-04

**James Taylor** (05:28:31) (in thread):
> The renaming was s/Developer/Community/ in an effort to make the conference inclusive of users, trainers, etc not just developers.

**James Taylor** (05:29:53) (in thread):
> And it has worked somewhat, but it is still hard to get users here. We personally reached out to a LOT of people who had published interesting papers using Galaxy this year and had a lot of really good Biology talks where the underlying analysis was all done in Galaxy. But required scanning a lot of papers and making a lot of invites.

**James Taylor** (05:30:13) (in thread):
> And I totally see how my tweet was confusing!

**Vince Carey** (07:37:28):
> Some concepts about training that I have not fully processed but found intriguing are at[https://cacm.acm.org/blogs/blog-cacm/232557-direct-instruction-is-better-than-discovery-but-what-should-we-be-directly-instructing/fulltext](https://cacm.acm.org/blogs/blog-cacm/232557-direct-instruction-is-better-than-discovery-but-what-should-we-be-directly-instructing/fulltext)
  - Attachment (cacm.acm.org): [Direct Instruction is Better than Discovery, but What Should We be Directly Instructing?](https://cacm.acm.org/blogs/blog-cacm/232557-direct-instruction-is-better-than-discovery-but-what-should-we-be-directly-instructing/fulltext)
> We should teach students directly, not expect them to discover for themselves. What should we be teaching directly?

**Vince Carey** (08:21:39):
> Since there are concepts of conference redesign/renaming on this
> channel I will raise these points here, but maybe we should have a
> bioc2020 channel to get going on planning next conference.
> 
> 1) I think the 3-day format with one optional day has worked well and
> may continue to work well for at least the next few years
> 
> 2) I am all in favor of "Collaboration day" as one of the days
> 
> 3) I am not in favor of dropping "Developer day" and I propose some repositioning below.
> 
> 4) Proposal for redesign of conference schedule.
> 
> Day 1: Conference day.  Keynotes on cutting edge comp bio and genomics, followed by elementary and intermediate workshops that are few in number, large in class size, and emphasize teamwork.   We might think about "flipped classroom" approach to our core workshops, where there is a well-produced video that people watch together, interrupt with questions, and
> then tackle problems in small groups.  [Does flipped classroom still get used?  It
> got a fair amount of press a few years ago.  The wikipedia entry seems useful.  Would
> it be helpful in such short term encounters?]
> 
> Day 2: Collaboration day.  Early meeting giving overview of objectives of day 2.
> Various workshops and meetings throughout the day.  Schedule "reporting back"
> from groups formed in workshops -- one objective of each workshop is preparing
> a report for delivery to the whole conference.  [This reporting concept is speculative.]
> 
> Day 3: Developer day.  Optional.  Focus on decisionmaking in software/data structure
> design, new assay types and associated problems of ingestion, QC, summarization,
> new concepts in R and computational services relevant to state-of-the-art comp bio.

**Martin Morgan** (08:53:01) (in thread):
> [:thanks:]!

**Sean Davis** (09:08:02):
> +1 for a bioc2020 channel.


## 2019-07-06

**Vince Carey** (10:26:02):
> [https://www.cell.com/ajhg/fulltext/S0002-9297(19)30229-0](https://www.cell.com/ajhg/fulltext/S0002-9297(19)30229-0)

**Vince Carey** (10:27:06):
> ```
> We then examine the effects of specific interventions and show that wide public discussion of the relative under-participation of women in question-and-answer sessions alters question-asking behavior. We suggest that engaging the community in such projects promotes visibility of diversity issues at academic meetings and allows for efficient data collection that can be used to further explore and understand differences in conference participation.
> ```


## 2019-07-08

**Stephanie Hicks** (22:37:46):
> @Vince Carey@Sean Davis#bioc2020has been created


## 2019-07-12

**Stephanie Hicks** (19:31:57) (in thread):
> @Martin MorganJust following up on your earlier message. You mentioned you would be supportive of such effort with a letter of support. Do you have recommendations on the best way to organize the people in interested in such a project? e.g. new channel? or just a message on#general?

**Martin Morgan** (23:16:41) (in thread):
> @Stephanie HicksI'd create a new channel...


## 2019-07-15

**Heather Turner** (15:14:54):
> @Heather Turner has joined the channel

**Matt Ritchie** (20:27:36):
> @Matt Ritchie has joined the channel


## 2019-07-16

**Charlotte Soneson** (04:49:59) (in thread):
> A couple of thoughts related to@Stephanie Hicks’s points above:
> • could it help to have a dedicated “new developer”/“getting started with development” slack channel (there’s probably a better name), for informal discussions and sharing of ideas - less formal than the devel mailing list, and perhaps easier to bring up questions like “How do I get started with X?“, and also to help other (new) developers, even if you may not have the full solution.
> • for involving more people/community day - I think at useR they had the “tidyverse dev-day”, where attendees were tackling open issues in the tidyverse packages ([https://github.com/tidyverse/dev-day-2019](https://github.com/tidyverse/dev-day-2019)), with helpers present. Could be useful also for improving documentation, adding examples, etc.


## 2019-07-23

**Aedin Culhane** (10:46:10):
> @Laurent GattoThanks for pointing out the PNAS article on Code of Conduct[https://www.pnas.org/content/early/2019/07/02/1819409116](https://www.pnas.org/content/early/2019/07/02/1819409116)
  - Attachment (PNAS): [Evaluating the prevalence and quality of conference codes of conduct](https://www.pnas.org/content/early/2019/07/02/1819409116)
> Academic conferences encourage collaboration and ignite ideas but can have negative impacts that disproportionately affect historically marginalized groups. Conference codes of conduct can help protect against abuses and foster diversity, but less than one fourth of the biology conferences we studied from the United States and Canada had them. Of these, few codes addressed or denounced identity-based discrimination and sexual misconduct that fuels attrition of scientists from historically marginalized groups. Most codes did not provide clear or impartial reporting mechanisms. Only two thirds listed consequences for violations. We provide recommendations for codes of conduct at biology conferences to improve equity in more platforms of science. Efforts to increase inclusion in science face multiple barriers, including cultural and social behaviors in settings such as academic conferences. Conferences are beneficial, but the culture can promote inequities and power differentials that harm historically underrepresented groups. Science suffers when conference culture propagates exclusion and discrimination that leads to attrition of scientists. Codes of conduct represent a tool to shift conference culture to better support diverse scientists and clearly detail unacceptable behaviors. We examined the prevalence and content of codes of conduct at biology conferences in the United States and Canada. We highlight how codes of conduct address issues of sexual misconduct and identity-based discrimination. Surprisingly, only 24% of the 195 surveyed conferences had codes. Of the conferences with codes, 43% did not mention sexual misconduct and 17% did not mention identity-based discrimination. Further, 26% of these conferences failed to include a way to report violations of the code and 35% lacked consequences for misconduct. We found that larger and national conferences are more likely to have codes than smaller ( P = 0.04) and international or regional ( P = 0.03) conferences. Conferences that lack codes risk creating and perpetuating negative environments that make underrepresented groups feel unwelcome, or worse, actively cause harm. We recommend that conferences have codes that are easily accessible, explicitly address identity-based discrimination and sexual misconduct, provide channels for anonymous impartial reporting, and contain clear consequences. These efforts will improve inclusivity and reduce the loss of scientists who have been historically marginalized.

**Aedin Culhane** (10:47:04):
  - File (JPEG): [CoC_large.jpg](https://community-bioc.slack.com/files/U34P8RS3B/FLR41CX63/coc_large.jpg)


## 2019-07-25

**Aedin Culhane** (12:58:57):
> [https://www.nature.com/articles/d41586-019-02253-9](https://www.nature.com/articles/d41586-019-02253-9)
  - Attachment (nature.com): [How to organize a conference that’s open to everyone](https://www.nature.com/articles/d41586-019-02253-9)
> Thinking about the needs of all participants is key to a successful event.


## 2019-08-08

**Vince Carey** (21:09:01):
> [https://nexus.od.nih.gov/all/2019/07/22/achieving-gender-equity-at-conferences/](https://nexus.od.nih.gov/all/2019/07/22/achieving-gender-equity-at-conferences/)
  - Attachment (NIH Extramural Nexus): [Achieving Gender Equity at Conferences](https://nexus.od.nih.gov/all/2019/07/22/achieving-gender-equity-at-conferences/)
> Inviting women to speak at conferences matters for many reasons – it’s a matter of fairness; it gives eminently qualified women a level playing field; it is just the right thing to do. In essence, …


## 2019-10-01

**Stephanie Hicks** (12:30:38):
> I would like to toss out the idea that Bioc applies for this grant ([https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/)) in the mid-December round. The idea being that Bioc has been previously funded twice by the CZI for methodological and software development around scRNA-seq data. But the essential oss application would be to fund new modes of community support / engagement. This could entail e.g.
> 
> - expanding (or building?) more websites like[https://osca.bioconductor.org](https://osca.bioconductor.org)or significantly expanding documentation for large-scale analyses in bioc
> - funding an Bioc “unconference” to interface in person between biologists and bioc developers (this is a different goal than the current bioc conference)
> - expanding support for new data modalities that Bioc is currently not a major player in (e.g. spatial transcriptomics). here we would engage other communities and develop infrastructure to leverage their software and integrate into bioc
  - Attachment (Chan Zuckerberg Initiative): [Essential Open Source Software for Science](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/)
> The Chan Zuckerberg Initiative is inviting applications for one-year open source software projects that are essential to biomedical research. This RFA is the first of a series. CZI will invite applications during three distinct cycles, with rounds beginning June 18, 2019; mid-December 2019; and mid-June 2020.
  - Attachment (osca.bioconductor.org): [Orchestrating Single-Cell Analysis with Bioconductor](https://osca.bioconductor.org)
> Online companion to ‘Orchestrating Single-Cell Analysis with Bioconductor’ manuscript by the Bioconductor team.

**Stephanie Hicks** (12:30:59):
> would love to get feedback from anyone interested in working on this together

**Simina Boca** (14:19:47):
> I'm interested!

**Simina Boca** (14:20:19):
> I applied for this grant for the August 1 deadline for another project but I don't think there's any restriction in applying again and I think you give some great ideas

**Simina Boca** (14:20:59):
> They specifically explain that open-source software goes beyond the code and includes all these additional community-building aspects

**Simina Boca** (14:21:03):
> Also it's a very short application

**Vince Carey** (16:57:47):
> @Stephanie HicksThese are very interesting thoughts and if some support from the bioc foundation could help please let me know.  Travel support for a couple of developers to attend a small meeting with some spatial transcriptomics practitioners in your area?


## 2019-10-04

**Lauren Hsu** (09:13:43):
> @Lauren Hsu has joined the channel

**Aedin Culhane** (16:10:37):
> Hi Stephanie. Great idea.  There was discussions to get this together in August, but it didn't come together.


## 2019-10-14

**Sean Davis** (10:28:03):
> Another example of a thoughtful code-of-conduct.[https://github.com/AlexsLemonade/RNA-Seq-Exercises/blob/master/code-of-conduct.md](https://github.com/AlexsLemonade/RNA-Seq-Exercises/blob/master/code-of-conduct.md)


## 2019-10-21

**Aedin Culhane** (14:07:53):
> Thanks Sean.@Levi Waldronis leading the CoC


## 2019-11-04

**Izaskun Mallona** (08:20:42):
> @Izaskun Mallona has joined the channel


## 2019-11-07

**Shraddha Pai** (12:37:37):
> @Shraddha Pai has joined the channel

**Qian Liu** (12:38:26):
> @Qian Liu has joined the channel


## 2019-11-12

**Stephanie Hicks** (21:13:59):
> hi#diversebioc— I’m looking to move forward with one of the CZI proposal ideas that I tossed out last month ([https://community-bioc.slack.com/archives/CL21357E2/p1569947438001100](https://community-bioc.slack.com/archives/CL21357E2/p1569947438001100)). I see there were 9:thumbsup:from people who are interested in at least one of these ideas. Could we revive that conversation? I’m going to open up a poll on Slack to help us figure if there are groups of people who want to work on different project proposals. From there, we can decide how to move forward with the december deadline?
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CL21357E2/p1569947438001100)
> I would like to toss out the idea that Bioc applies for this grant ([https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/)) in the mid-December round. The idea being that Bioc has been previously funded twice by the CZI for methodological and software development around scRNA-seq data. But the essential oss application would be to fund new modes of community support / engagement. This could entail e.g.
> 
> - expanding (or building?) more websites like [https://osca.bioconductor.org](https://osca.bioconductor.org) or significantly expanding documentation for large-scale analyses in bioc
> - funding an Bioc “unconference” to interface in person between biologists and bioc developers (this is a different goal than the current bioc conference)
> - expanding support for new data modalities that Bioc is currently not a major player in (e.g. spatial transcriptomics). here we would engage other communities and develop infrastructure to leverage their software and integrate into bioc

**Unknown User** (21:20:13):
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: context]

**Stephanie Hicks** (21:20:32):
> alternatively, if you could leave suggestions here of other ideas, that would be helpful in getting the ball rolling


## 2019-11-13

**Hervé Pagès** (11:32:29):
> @Stephanie HicksMaybe you'll get more exposure by having the poll in a different channel?

**Kevin Blighe** (12:13:44):
> @Kevin Blighe has joined the channel

**Keegan Korthauer** (12:30:45):
> @Keegan Korthauer has joined the channel

**Koen Van den Berge** (12:32:07):
> @Koen Van den Berge has joined the channel

**Alan O'C** (12:32:55):
> @Alan O'C has joined the channel

**Kasper D. Hansen** (12:35:07):
> @Kasper D. Hansen has joined the channel

**Mikhail Dozmorov** (14:49:52):
> @Mikhail Dozmorov has joined the channel


## 2019-11-14

**Mike Smith** (07:59:37):
> @Mike Smith has joined the channel

**Aedin Culhane** (14:38:04):
> Hi Stephanine. I think the Bioconductor Website needs major work. It was identified in the Bioc survey as a weak point. That survey maybe useful as preliminary data to back up the CZI grant strategy[https://docs.google.com/forms/d/e/1FAIpQLSdPPVtPO4zWOJB0DmeU44UWdolJipPh83qrGR8YscagQ7veSA/viewform?usp=send_form](https://docs.google.com/forms/d/e/1FAIpQLSdPPVtPO4zWOJB0DmeU44UWdolJipPh83qrGR8YscagQ7veSA/viewform?usp=send_form).

**Kasper D. Hansen** (15:17:37):
> They just put out a list of awardees from last cycle

**Hervé Pagès** (15:25:41):
> @Aedin CulhaneI'm surprised the survey is still open. Do you have the link to the results? (I think I've seen them somewhere but can't remember where.)

**Aedin Culhane** (15:43:58):
> Yes survey is still open

**Aedin Culhane** (15:48:40):
> Its had 109 responses when I saw data.

**Aedin Culhane** (15:49:39):
> However for the purposes of this grant, it might be easier to create just a resources for Bioc, and it doesn't have to include an overhaul of the main site.

**Aedin Culhane** (15:50:43):
> In the survey Barriers to contributing: S4 is mentioned a few times. especially from people coming from R-> Bioc who may have "grown-up" in tidyverse land.

**Aedin Culhane** (15:52:50):
> I think another useful guide (that CZI might like) is how to develop packages for they can be integrated into non-Bioc frameworks (eg python, GUIs, Galaxy etc)

**Aedin Culhane** (16:15:44):
> Medium blog from CZI on who was funded in first round[https://medium.com/@cziscience/the-invisible-foundations-of-biomedicine-4ab7f8d4f5dd](https://medium.com/@cziscience/the-invisible-foundations-of-biomedicine-4ab7f8d4f5dd)
  - Attachment (Medium): [The Invisible Foundations of Biomedicine](https://medium.com/@cziscience/the-invisible-foundations-of-biomedicine-4ab7f8d4f5dd)
> Supporting 42 Essential Open Source Software Projects that Drive Science

**Aedin Culhane** (16:18:58):
> The list of proposals funded is[https://chanzuckerberg.com/eoss/proposals/](https://chanzuckerberg.com/eoss/proposals/)
  - Attachment (Chan Zuckerberg Initiative): [CZI – Essential Open Source Software for Science](https://chanzuckerberg.com/eoss/proposals/)
> CZI’s Essential Open Source Software for Science program supports software maintenance, growth, development, and community engagement for open source tools critical to science.

**Hervé Pagès** (16:19:41) (in thread):
> Interesting, thanks! I agree that Bioconductor website needs some work. Do you know when the results of the survey will be made publicly available? (Strangely I have a vague recollection of having seen them somewhere but my memory is clearly playing tricks on me:face_with_head_bandage:)

**Aedin Culhane** (16:20:41):
> R/Bioc packages people include MSstats/Cardinal (Olga Vitek), Limma/edgeR/Glimma (Gordon Smyth), Seurat (Rahul Satija), Bioc Build System (Vince Carey)

**Hervé Pagès** (16:28:04):
> also funded the Bioconda folks who redistribute Bioconductor packages

**Aedin Culhane** (16:51:07):
> well spotted

**Stephanie Hicks** (22:35:26):
> yeah, I was a reviewer for this last round (listed at the bottom of the medium post). Did not review any bioc grants & no conflict of interests. But I really do believe that we should submit one this next round.

**Stephanie Hicks** (22:35:58):
> @Aedin CulhaneI like your ideas! I’ll go through the survey results tomorrow and circle back tomorrow


## 2019-11-15

**Stephanie Hicks** (08:24:20) (in thread):
> congratulations Olga@Gordon SmythRahul@Vince Carey!!

**Aedin Culhane** (11:13:25):
> Delighted you got an insight into the review progress.  I think the survey data might be good prelim (especially if its public at the time of submission).  Bioc for sc data needs to be accessible to as diverse a community as possible.  So we need entry level documentation on basic bioc (S4 classes), and documentation for devel to can leverage the method to extend (using git, developing package, working with other CZI teams to make methods portable), and both need training/education materials and web site.  I think Martin mention working with carpentries. So could propose to develop carpentry course for beginner and devel scData in Bioc. Thats a pretty concrete goal.

**Aedin Culhane** (11:14:31):
> I love the idea of a meeting. I think doing a webinar or two for beginners unfamiliar with bioc to "advertize" bioc resources to non R folks and mention how it can be called from python

**Aedin Culhane** (11:15:10):
> These could be recorded and posted on Youtube to expand the impact of these

**Aedin Culhane** (11:16:58):
> But how much is the grant and how long is it for. The goals need to be tractable and writing documentation takes time (as you know!).  We could video/record the meeting talks as material

**Aedin Culhane** (11:18:21):
> I have done a pretty poor job of posting the meetup talks online. I am not sure how to do this. We have recorded a few of them, but should do them all.  Also can we post to the bioc channel.  It would be good to make that simple.

**Frederick Tan** (12:46:48):
> @Frederick Tan has joined the channel

**Mike Smith** (13:13:14):
> The idea of a data carpentry module that focuses on Bioconductor classes sounds like an awesome idea to me.

**Stephanie Hicks** (13:14:20):
> talking with@Kasper D. Hansentoday, he mentioned he’s building a intro guide for S4 classes in Bioc which is great!


## 2019-11-18

**Jayaram Kancherla** (09:08:29):
> @Jayaram Kancherla has joined the channel


## 2019-12-01

**FelixErnst** (14:19:50):
> @FelixErnst has joined the channel


## 2019-12-07

**Juan Ojeda-Garcia** (18:44:59):
> @Juan Ojeda-Garcia has joined the channel


## 2019-12-09

**Aedin Culhane** (10:18:46):
> New definition of diversity by the NIH[https://nexus.od.nih.gov/all/2019/11/26/expanding-nihs-definition-of-socio-economic-disadvantaged-to-be-more-inclusive-and-diversify-the-workforce/](https://nexus.od.nih.gov/all/2019/11/26/expanding-nihs-definition-of-socio-economic-disadvantaged-to-be-more-inclusive-and-diversify-the-workforce/)Aedin
  - Attachment (NIH Extramural Nexus): [Expanding NIH’s Definition of  Socio-Economic Disadvantaged to be More Inclusive  and Diversify the Workforce](https://nexus.od.nih.gov/all/2019/11/26/expanding-nihs-definition-of-socio-economic-disadvantaged-to-be-more-inclusive-and-diversify-the-workforce/)
> NIH has considered a different approach to defining scientists from disadvantaged backgrounds. We reviewed a wide variety of criteria, looking for those that are relatively easy to self-evaluate an…

**Sean Davis** (10:54:17) (in thread):
> And the (US-centric) criteria themselves, copied from the Guidance Document:

**Sean Davis** (10:54:20) (in thread):
> Now, through this Guide Notice which supersedes current diversity language in existing funding opportunities, we will consider scientists to have come from a disadvantaged background if they meet at least two of the following criteria.
> 1. Were or currently are homeless, as defined by the McKinney-Vento Homeless Assistance Act
> 2. Were or currently are in the foster care system, as defined by the Administration for Children and Families;
> 3. Were eligible for the Federal Free and Reduced Lunch Program for two or more years;
> 4. Have/had no parents or legal guardians who completed a bachelor’s degree (see the U.S. Department of Education);
> 5. Were or currently are eligible for Federal Pell grants (;
> 6. Received support from the Special Supplemental Nutrition Program for Women, Infants and Children as a parent or child;
> 7. Grew up in one of the following areas: a) a U.S. rural area, as designated by the Health Resources and Services Administration Rural Health Grants Eligibility Analyzer, or b) a Centers for Medicare and Medicaid Services-designated Low-Income and Health Professional Shortage Areas  (qualifying zip codes are included in the file). Only one of the two possibilities in #7 can be used as a criterion for the disadvantaged background


## 2019-12-15

**Mikhail Dozmorov** (11:10:39):
> Interesting resources on organizing inclusive scientific meetings,[https://immunox.ucsf.edu/future-immunology](https://immunox.ucsf.edu/future-immunology). Their inclusive meeting guide seems very useful[https://static1.squarespace.com/static/582cce42bebafbfc47a82b04/t/5ca0fe7d9b747a3d7dc7a71f/1554054781756/Formatted+Inclusive+Meeting+Guide-v5.pdf](https://static1.squarespace.com/static/582cce42bebafbfc47a82b04/t/5ca0fe7d9b747a3d7dc7a71f/1554054781756/Formatted+Inclusive+Meeting+Guide-v5.pdf)


## 2020-01-29

**Matt Ritchie** (19:23:57):
> Thanks again to everyone who replied to the Bioconductor community survey. Some analysis of the results kindly provided by@Stuart Leecan be found at[https://sa-lee.github.io/BiocSurvey/articles/report.html](https://sa-lee.github.io/BiocSurvey/articles/report.html)or via the R package at[https://github.com/sa-lee/BiocSurvey](https://github.com/sa-lee/BiocSurvey)(which includes anonymised raw response data). We hope others find the results interesting!


## 2020-01-30

**Sean Davis** (11:56:47):
> Thanks,@Matt Ritchieand@Stuart Lee(and others that may have contributed anonymously) for the work! We should consider setting aside some time at the conference to discuss this (if it isn’t already there).

**Stuart Lee** (17:03:14):
> Thanks@Sean Davis,  also to anyone who is interested, this analysis was done very quickly over an afternoon so I’m sure there’s more you could look at, feel free to fork and roll your own!


## 2020-02-05

**Aedin Culhane** (13:08:15):
> > ***From: ***Microsoft Research Grants <[msrgrant@microsoft.com](mailto:msrgrant@microsoft.com)>***Date: ***Tuesday, February 4, 2020 at 3:13 PM***To: ***Microsoft Research Grants <[msrgrant@microsoft.com](mailto:msrgrant@microsoft.com)>***Subject: ***Accepting Proposals - 2020 Microsoft Research Dissertation Grant 
> > 
> > We are currently accepting proposals for the Microsoft Research Dissertation Grant through***March 30, 2020***. You can read more about the grant and find instructions to submit a proposal at[http://aka.ms/Dissertation-Grant](http://aka.ms/Dissertation-Grant). 
> >  
> > We encourage you to share this announcement within your communities either directly with your student and faculty contacts, via topically relevant email lists, or on social media: Twitter, Facebook, Instagram, and LinkedIn.
> >  
> > Broadening participation in computing is a core part of Microsoft's values; accordingly, we are excited to continue the Microsoft Research Dissertation Grant that aims to recognize and support diverse doctoral students as they complete their dissertation research in computing-related fields.
> >  
> > This grant is open to doctoral students in their fourth year or beyond at universities in the United States, Canada and Mexico, who are underrepresented in the field of computing. This includes those who self-identify as a woman, African American, Black, Hispanic, Latinx, American Indian, Alaska Native, Native Hawaiian, Pacific Islander, and/or person with a disability. The program allows students to submit a proposal of up to $25,000 to support their dissertation research; grant recipients can also participate in a two-day career workshop at one of Microsoft Research’s labs this autumn.
> >   
> > For questions, please contact[msrgrant@microsoft.com](mailto:msrgrant@microsoft.com).
> >  
> > Sincerely,
> >  
> > Meredith Ringel Morris
> > Sr. Principal Research Manager & MSR Dissertation Grant Chair**Unsubscribe / Se désabonner | Privacy Statement / Déclaration de confidentialité****Microsoft Corporation****One Microsoft Way****Redmond, WA 98052**
  - Attachment (Microsoft Research): [Dissertation Grant - Microsoft Research](http://aka.ms/Dissertation-Grant)
> The Microsoft Research Dissertation Grant is for under-represented PhD students at universities in US/Canada doing dissertation work related to computing.


## 2020-02-09

**Matt Ritchie** (17:35:15):
> The newly created Bioconductor Community Advisory Board might be of interest to members of this channel - draft terms of reference are available at[https://tinyurl.com/yx7e53d3](https://tinyurl.com/yx7e53d3).
> 
> The Community Advisory Board is seeking its first members. Our goal is to have broad representation in terms of gender, ethnicity, geographical location, career stage, experience levels etc.
> 
> If you're interested in contributing to community building in any number of ways (conference and meet-up organisation / promoting Bioconductor more broadly via social media / improving the on-ramps for new users etc.) then please consider nominating.
> 
> Applications can be made by completing the form at[https://forms.gle/q6xzBGpEcJKVK7GC9](https://forms.gle/q6xzBGpEcJKVK7GC9). The closing date for applications is Friday 28th February 2020.
> 
> Please direct any questions you have about the Community Advisory Board to either myself or@Aedin Culhane.
> 
> We look forward to receiving your nomination!
  - Attachment (Google Docs): [CAB Governance](https://tinyurl.com/yx7e53d3)
> Bioconductor Community Advisory Board Governance Version 0.0.2 January 2020 Purpose The Bioconductor mission is to promote the statistical analysis and comprehension of current and emerging high-throughput biological assays. The Community Advisory Board's purpose is to support this mission by E...
  - Attachment (Google Docs): [Nomination Form: Bioconductor Community Advisory Board](https://forms.gle/q6xzBGpEcJKVK7GC9)
> Bioconductor's mission is to promote the statistical analysis and comprehension of current and emerging high-throughput biological assays. The newly established Community Advisory Board aims to support this mission by: - empowering user and developer communities by coordinating training and outreach activities. - enabling productive and respectful participation by Bioconductor users and developers at all levels of experience. Draft terms of reference for the Community Advisory Board are available at [https://tinyurl.com/yx7e53d3](https://tinyurl.com/yx7e53d3). Nominations are sought from enthusiastic individuals interested in serving on the Community Advisory Board. To reflect the diverse background of members of the Bioconductor community, we are seeking broad representation in terms of gender, ethnicity, geographical location, career stage, experience level etc. To nominate, yourself or someone else (please check that they are happy to be nominated first!) complete the form below. Nominations will close on 28th February 2020 and members will be selected by a vote of current members of Bioconductor's Technical Advisory Board. Membership will be confirmed by early March 2020. If you have further questions, please contact Matt Ritchie (<mailto:mritchie@wehi.edu.au|mritchie@wehi.edu.au>) or Aedin Culhane ( <mailto:aedin@jimmy.harvard.edu|aedin@jimmy.harvard.edu>). Thank you for your nomination!


## 2020-02-11

**Theresa Alexander** (15:36:56):
> @Theresa Alexander has joined the channel


## 2020-02-17

**Heather Turner** (03:31:53):
> [https://twitter.com/smallperks/status/1229207579127111681?s=19](https://twitter.com/smallperks/status/1229207579127111681?s=19)
  - Attachment (twitter): [Attachment](https://twitter.com/smallperks/status/1229207579127111681?s=19)
> :wave::skin-tone-6:Want to continue to grow the diversity and inclusion efforts within the Rstats community? There is ongoing discussion in the R community around reach, support, and inclusivity of racial minority users of R, ie URM in the US: [https://qz.com/1661487/hadley-wickham-on-the-future-of-r-python-and-the-tidyverse/](https://qz.com/1661487/hadley-wickham-on-the-future-of-r-python-and-the-tidyverse/) (1/4)

**Heather Turner** (03:32:14):
> :point_up_2:Information about a new community for racial/ethnic minority groups. Focus is on the US, but if you are part of a minority group in your country, I think you are welcome to join.


## 2020-02-25

**Hena Ramay** (12:49:56):
> @Hena Ramay has joined the channel


## 2020-02-26

**Vince Carey** (11:31:05):
> of potential interest[https://chaoss.community/](https://chaoss.community/)... includes diversity as a measure of "health" of an open source project


## 2020-02-29

**Leonardo Collado Torres** (18:07:31):
> This was a special day for us at CDSB@Alejandro Reyes@Joselyn ChávezCarmina and Emiliano:[https://support.bioconductor.org/p/128691/](https://support.bioconductor.org/p/128691/)^^

**Alejandro Reyes** (18:07:36):
> @Alejandro Reyes has joined the channel

**Leonardo Collado Torres** (20:15:53) (in thread):
> gracias:smiley:


## 2020-03-03

**Leonardo Collado Torres** (10:40:40) (in thread):
> Hi. No, I work in the US as well as Alejandro. But we both try to go for the in person 1 week course we organize in the summer in Mexico, and we’ve been helping Joselyn, Carmina and Emiliano remotely


## 2020-03-09

**Levi Waldron** (19:14:38):
> The Code of Conduct committee response to the violation reported at BioC2019 has been posted:[https://bioc2019.bioconductor.org/code_of_conduct](https://bioc2019.bioconductor.org/code_of_conduct)
  - Attachment (BioC 2019): [BioC2019 Code of Conduct violation response](https://bioc2019.bioconductor.org/code_of_conduct)
> Where Software and Biology Connect. June 24 - 27, New York City, USA.


## 2020-03-10

**Sean Davis** (00:15:44):
> Thanks for all the hard work and thoughtful response,@Levi Waldron,@Aedin Culhaneand@Laurent Gatto.

**Matt Ritchie** (05:09:01) (in thread):
> and@Stephanie Hicks

**Kevin Rue-Albrecht** (05:31:19) (in thread):
> Minor typo I believe
> > and this response been our work on forming , and formed procedures for decision-making in such instances
> As Sean said, great thoughtful response

**Levi Waldron** (05:38:22) (in thread):
> Argh, thanks@Kevin Rue-Albrecht, that sentence actually wasn’t supposed to be there, the same content being sufficiently covered in the first paragraph. Fixed now.

**Stephanie Hicks** (11:04:45) (in thread):
> thanks@Sean Davis@Matt Ritchie.@Levi Waldrondid almost all the work, but I was happy to provide my feedback / suggestions

**Sean Davis** (18:48:01) (in thread):
> Sorry,@Stephanie Hicks!

**Stephanie Hicks** (18:52:28) (in thread):
> Haha np!


## 2020-06-02

**Hervé Pagès** (00:02:03):
> @Hervé Pagès has left the channel


## 2020-06-06

**Olagunju Abdulrahman** (19:57:18):
> @Olagunju Abdulrahman has joined the channel


## 2020-06-11

**Dan Bunis** (15:36:30):
> @Dan Bunis has joined the channel


## 2020-06-12

**Dan Bunis** (12:59:31):
> Although pride parades are cancelled, and social focus is largely shifted elsewhere* this year, it is still pride month.
> 
> I’m wondering if anyone else in the group has any thoughts on this newer iteration of the general pride flag. Particularly, as a white cis gay male myself, I’d like to hear others’ thoughts on this flag iteration.
> 
> Rather than giving my own words as to why I personally support this flag, I’d like to share its creator’s:
> > Their artist statement:
> > I am so excited that my art is getting some traction. I created this in 2019 as a way to spread the message that we need to center Trans people, People of color, and specifically Trans People of Color in the queer community as a whole. There are no lines separating us as we are one big community that blends together and needs intersectional support. I am very excited about the T-shirts, Hoodies, Tanktops and now Flags that we have to spread this art and this message. As a Brown Queer Disabled Transman. This has helped me feel more supported in the community as a whole. anyways here is my art if you want to spread the word! I am a Portlander and would love the support of my local community with this message.
> (full credit text in link in the thread. Please do not share without it.)
> 
> I’m specifically considering making a square version of the flag into an emoji, and then adding it as my status icon for the rest of the June. I would love to see an open discussion on this, and it would also be wonderful to see how diverse of a community we have here, but DMs (confidentiality assured) are also welcome!
> 
> *rightfully so. #blacklivesmatter, and the LGBT community must proclaim and actively support that because #blacktranslivesmatter, and because of so many other reasons too!
  - File (JPEG): [Queer Trans POC Community PRIDE flag.jpg](https://community-bioc.slack.com/files/U34P8RS3B/F015BK5D0HH/queer_trans_poc_community_pride_flag.jpg)

**Dan Bunis** (13:04:44) (in thread):
> DO NOT SHARE WITHOUT THIS CREDIT: Design byScout TheBootblack. Purchase links and artist statement below:
> Stickers:[https://mitabear-designs.myshopify.com/collections/stickers-lgbtqa/products/queer-trans-poc-community-flag-sticker-3-x-5](https://mitabear-designs.myshopify.com/collections/stickers-lgbtqa/products/queer-trans-poc-community-flag-sticker-3-x-5)Flag:[https://mitabear-designs.myshopify.com/collections/pride-flags/products/queer-trans-poc-community-flag-3-x-5-preorder](https://mitabear-designs.myshopify.com/collections/pride-flags/products/queer-trans-poc-community-flag-3-x-5-preorder)Shirts:[https://www.customink.com/fundraising/centerqtpoc](https://www.customink.com/fundraising/centerqtpoc)Their artist statement:
> I am so excited that my art is getting some traction. I created this in 2019 as a way to spread the message that we need to center Trans people, People of color, and specifically Trans People of Color in the queer community as a whole. There are no lines separating us as we are one big community that blends together and needs intersectional support. I am very excited about the T-shirts, Hoodies, Tanktops and now Flags that we have to spread this art and this message. As a Brown Queer Disabled Transman. This has helped me feel more supported in the community as a whole. anyways here is my art if you want to spread the word! I am a Portlander and would love the support of my local community with this message.
  - Attachment (MitaBear Designs): [QUEER TRANS POC COMMUNITY FLAG STICKER 3](https://mitabear-designs.myshopify.com/collections/stickers-lgbtqa/products/queer-trans-poc-community-flag-sticker-3-x-5)
> Working in COLAB with Scout Hudson I am Proud to bring you the Official QUEER TRANS POC FLAG STICKER  a portion of profit from every one will go into this fund [https://www.customink.com/fundraising/centerqtpoc?share=1141591154015266&fbclid=IwAR2ycIAIYHYLQ9oIcQn7tTWuPj02JmSNNvIxlJ0V4Ui56sXvO7w24pITwz0](https://www.customink.com/fundraising/centerqtpoc?share=1141591154015266&fbclid=IwAR2ycIAIYHYLQ9oIcQn7tTWuPj02JmSNNvIxlJ0V4Ui56sXvO7w24pITwz0) It is
  - Attachment (MitaBear Designs): [QUEER TRANS POC Community flag 3' x 5' - PREORDER](https://mitabear-designs.myshopify.com/collections/pride-flags/products/queer-trans-poc-community-flag-3-x-5-preorder)
> Working in COLAB with Scout Hudson I am Proud to bring you the Official QUEER TRANS POC FLAG  $5 From every will go into this fund [https://www.customink.com/fundraising/centerqtpoc?share=1141591154015266&fbclid=IwAR2ycIAIYHYLQ9oIcQn7tTWuPj02JmSNNvIxlJ0V4Ui56sXvO7w24pITwz0](https://www.customink.com/fundraising/centerqtpoc?share=1141591154015266&fbclid=IwAR2ycIAIYHYLQ9oIcQn7tTWuPj02JmSNNvIxlJ0V4Ui56sXvO7w24pITwz0) It is time that we center Trans Peo
  - Attachment (customink.com): [Support Center Trans People of Color in Queer Community!!](https://www.customink.com/fundraising/centerqtpoc)
> Buy this great shirt to support Center Trans People of Color in Queer Community!. Hurry, sale ends Monday, June 29.

**hcorrada** (14:00:02):
> @hcorrada has joined the channel


## 2020-06-14

**Peter Hickey** (06:18:18):
> @Peter Hickey has joined the channel


## 2020-06-15

**Constantin Ahlmann-Eltze** (04:14:43):
> @Constantin Ahlmann-Eltze has joined the channel


## 2020-06-16

**Liz Ing-Simmons** (09:27:10):
> @Liz Ing-Simmons has joined the channel

**Laurent Gatto** (12:49:16):
> Hello - I just wanted to point out here that we have a new diversity-affirming section in the BiocStickers repo ([https://github.com/Bioconductor/BiocStickers/blob/master/README.md](https://github.com/Bioconductor/BiocStickers/blob/master/README.md)) featuring rainbow and trans versions of our Bioconductor sticker. Credits to@Aaron Lunand@Dan Bunis. Thank you!


## 2020-06-18

**saskia** (22:42:15):
> @saskia has joined the channel

**Aedin Culhane** (23:03:19):
> @Dan BunisI wonder if you could make a bioc sticker of this flag for Bioc


## 2020-06-19

**Laurent Gatto** (03:38:11) (in thread):
> Anyone could order stickers on stickermule (for example). But may be the#community-advisory-boardcould coordinate this.
> 
> Otherwise, I am happy to order 100 or so and dispatch them further.

**Heather Turner** (04:15:50):
> This conference might be a bit tech-focused for people here, but there are still many great talks on community, diversity and contributing to open source:[https://juneteenthconf.com/](https://juneteenthconf.com/)
  - Attachment (juneteenthconf.com): [JuneteenthConf - June 19th and 20th 2020](https://juneteenthconf.com/)
> Juneteenth Conference is a free virtual tech conference made for and featuring Black people in technology. The conference celebrates Black Excellence and promotes community for Black people who are severely underrepresented in the tech industry. We welcome anyone and everyone aligned with this goal to come and listen to the conversation.

**Huipeng Li** (13:28:05):
> @Huipeng Li has joined the channel


## 2020-06-23

**Henrik Bengtsson** (15:53:28):
> @Henrik Bengtsson has joined the channel


## 2020-06-27

**Dan Bunis** (14:42:06) (in thread):
> I've made a version now, but I will not share it until I secure permission from the original artist.


## 2020-06-29

**Aedin Culhane** (22:58:51):
> Good point.


## 2020-07-04

**Umar Ahmad** (08:21:18):
> @Umar Ahmad has joined the channel


## 2020-07-09

**Giuliano Netto Flores Cruz** (14:32:57):
> @Giuliano Netto Flores Cruz has joined the channel


## 2020-07-14

**Kelly Eckenrode** (14:18:19):
> @Kelly Eckenrode has joined the channel


## 2020-07-25

**Dr Awala Fortune O.** (16:29:36):
> @Dr Awala Fortune O. has joined the channel


## 2020-07-27

**Aedin Culhane** (12:57:32):
> @Atul Deshpandeand@Dan Bunisdiscussion on creating figures that work for color blind individuals.  The google doc is at[https://docs.google.com/document/d/1qCYv4vfBeKMTNMf1m6TgRvo9dyfmbR7qx772dHiuX5M/edit#heading=h.8l5xrpwd5sqd](https://docs.google.com/document/d/1qCYv4vfBeKMTNMf1m6TgRvo9dyfmbR7qx772dHiuX5M/edit#heading=h.8l5xrpwd5sqd)

**Mike Smith** (13:25:03):
> It was an interesting discussion, and I'd definitely be interested in any follow up discussion on what we might be able to incorporate into Bioconductor.

**Leonardo Collado Torres** (13:30:16):
> I'll try to watch the video later, I was on the containers session. Thx for the info!

**Atul Deshpande** (13:33:07):
> @Atul Deshpande has joined the channel

**Dan Bunis** (14:32:22):
> Sounds like there’s a lot of interest in some sort of ‘practical’ followup to the discussion from earlier. Atul and I would love to have another session later in the conference where anyone interested could gather to discuss some concrete plans.  He and I just discussed a few ideas that we have, and here’s the sort of structure we think might work best for the session.
> 
> Session structure:
> 1. A few slides giving overview of a few ideas that might “easily” achievable ideas,
> 2. Some joint brainstorming: What of these ideas are most achievable? What can we actually do?
> 3. Breakout sessions, perhaps one for each idea, to see if we can create some concrete implementation plans
> Potentially achievable goals we’ve come up with so far:
> * A check of accessibility compliance in BiocCheck
> * Default colors - how to make accessible palettes more commonly the default
> * A color version of “ggrepel” where colors that are too similar are made more distant
> * automated generation of Alt Text - perhaps a basic text description which might encourage people to fill these in
> * new visualization possibilities (augmenting with non-color) — example Atul’s
> * A set of resources / guidelines that could be posted somewhere in the Bioconductor website
> Totally open to suggestions for both structure and individual ideas! If you’d like to suggest anything, you can do that either here or in the googledoc shared above.  I’ve copied these examples in towards the bottom of the doc.

**Dan Bunis** (14:33:47):
> I’m not sure who to talk to about literally setting up the session (?) but perhaps some time Wednesday or later

**Atul Deshpande** (14:35:10):
> I can help with setting up the session.


## 2020-07-28

**Dan Bunis** (12:34:22) (in thread):
> New session is added for***Thursday at 4pm***

**Mike Smith** (13:01:14) (in thread):
> I don't think I'll be able to attend at that time, but if the session is recorded I'll happily watch on Friday morning.

**Jenny Drnevich** (13:03:54):
> @Jenny Drnevich has joined the channel

**Dan Bunis** (13:08:47) (in thread):
> Unfortunate! But we will definitely record the session. Feel free to message me or@Atul Deshpandeafter with any additional thoughts or ideas or if you’d like to help with any implementation.

**Ray Su** (13:51:46):
> @Ray Su has joined the channel


## 2020-07-29

**Aedin Culhane** (11:25:49):
> great Thurs at 4pm.. Is it added to the agenda?

**Dan Bunis** (11:30:12):
> yup,[https://bioc2020.pathable.co/meetings/virtual/yraZDS49Yhkds4dHa](https://bioc2020.pathable.co/meetings/virtual/yraZDS49Yhkds4dHa)
  - Attachment (bioc2020.pathable.co): [BioC 2020](https://bioc2020.pathable.co/meetings/virtual/yraZDS49Yhkds4dHa)
> BioC 2020

**Riyue Sunny Bao** (17:39:15):
> @Riyue Sunny Bao has joined the channel

**Brianna Barry** (21:31:37):
> @Brianna Barry has joined the channel


## 2020-07-30

**Dan Bunis** (17:04:00):
> Thanks for another great discussion in on improving accessibility of visualizations at the followup BOF session just now!  To help push our ideas along and continue discussions further, I’ve just created a#accessible-vischannel.


## 2020-08-15

**Sean Davis** (13:07:28):
> ***Folks in GCB (***[https://www.folksingcb.com/](https://www.folksingcb.com/)) is a**self-nomination list**for individuals from groups that are underrepresented in genomics, computational biology, and bioinformatics.
> (e.g., women, racial or ethnic minorities, members of the LGBTQ+ community, veterans, among others; please see[Self-Nomination Form](https://www.folksingcb.com/signup)for more information).
  - Attachment (folksingcb.com): [Folks in GCB](https://www.folksingcb.com/)
> 


## 2020-10-20

**Sean Davis** (08:09:40):
> There is a new channel,#bioc_africa, for engaging on Bioconductor usage, development, and community in Africa. You can invite folks not already in Bioc Slack by sending them this link:[https://bioc-community.herokuapp.com/](https://bioc-community.herokuapp.com/)


## 2020-11-16

**Carmen Abaurre** (06:13:42):
> @Carmen Abaurre has joined the channel


## 2020-12-12

**Huipeng Li** (00:40:18):
> @Huipeng Li has joined the channel


## 2021-01-22

**Kozo Nishida** (00:28:57):
> @Kozo Nishida has joined the channel

**Annajiat Alim Rasel** (15:43:40):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-12

**Janani Ravi** (15:52:30):
> @Janani Ravi has joined the channel


## 2021-03-23

**Lambda Moses** (23:04:52):
> @Lambda Moses has joined the channel


## 2021-03-31

**Lisa Cao** (12:52:18):
> @Lisa Cao has joined the channel


## 2021-04-05

**Maya Reed McDaniel** (11:23:39):
> @Maya Reed McDaniel has joined the channel


## 2021-05-11

**Megha Lal** (16:44:51):
> @Megha Lal has joined the channel


## 2021-06-30

**Vince Carey** (12:19:00):
> There is software submitted utilizing the "ENCODE blacklist".[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/)is very clear that this term is problematic.
  - Attachment (PubMed Central (PMC)): [“Blacklists” and “whitelists”: a salutary warning concerning the prevalence of racist language in discussions of predatory publishing](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/)
> This commentary addresses the widespread use of racist language in discussions concerning predatory publishing. Examples include terminology such as blacklists, whitelists, and black sheep. The use of such terms does not merely reflect a racist culture, ...


## 2021-07-01

**Ben Story** (05:41:26):
> @Ben Story has joined the channel


## 2021-07-16

**Aedin Culhane** (15:50:03) (in thread):
> Where was this software submitted to? I hope not to Bioconductor. We should have clear guidelines in the code of conduct or package submission guidelines that software should not use offensive terms.@Lori Shepherd@saskia


## 2021-08-06

**ChiaSin** (20:00:51):
> @ChiaSin has joined the channel


## 2021-08-18

**Laurent Gatto** (10:36:01) (in thread):
> @Aedin Culhane- indeed, and we have discussed this briefly and have it on the next meeting's schedule too.


## 2021-08-19

**Ava Hoffman (she/her)** (11:33:20):
> @Ava Hoffman (she/her) has joined the channel


## 2021-08-25

**Sean Davis** (10:24:42):
> [http://lifescienceeditors.org/](http://lifescienceeditors.org/)

**Sean Davis** (10:25:20):
> JEDI AWARDS
> Our Justice, Equity, Diversity and Inclusion (JEDI) awards provide free scientific or language edits of a scientific manuscript or grant proposal from one of our volunteers (a[ former journal editor,](https://www.lifescienceeditors.com/about-the-editors/)current journal editor, technical writer, or researcher). In 2021, we plan to give 55 JEDI awards (equivalent to >$35,000) to students, postdocs and principal investigators (tenure-track/early career researchers within 7 years of starting their position, excluding any career breaks or extensions) who have a completed draft of a manuscript or grant proposal ready for editing. Manuscript-submission applicants must be first or corresponding author.
> We aim to give JEDI awards monthly to ~five scientists who face disproportionately high and unfair obstacles to career progression in academic science, including but not limited to women, people from historically underrepresented races or ethnic groups, people from low socioeconomic backgrounds, people with disabilities, primary caregivers (of any dependent), people who identify as LGBTQ+, and people in a low or lower middle income country.******To apply******please send an email to[jedi.award@lifescienceeditors.com](mailto:jedi.award@lifescienceeditors.com)(subject: JEDI Award) with one PDF document that includes:
> 1. Your C.V., highlighting current/previous positions, publications, current/previous funding.
> 2. A short paragraph describing your situation and how you think a JEDI award would help you.
> 3. A short summary (<30 lines) of your paper or grant proposal and the deadline.
> 4. Which of the obstacles above you face (please mention all that apply and/or other).
> ******This information will be kept strictly confidential.************The deadline is the 10th of every month******. JEDI awardees will represent diverse backgrounds and will have a submission-ready paper or grant proposal that advances knowledge in any area of experimental biology. JEDI awardees will be announced on or around the 15th of every month. If your submission was not chosen, you can reapply for any subsequent deadline. JEDI awardees are selected by LSEF volunteers, including LSEF co-founders Dr. Angela Andersen and Dr. Helen Pickersgill.*Banner photo: Dr. Marta Shahbazi, *[Cambridge](https://www2.mrc-lmb.cam.ac.uk/group-leaders/n-to-s/marta-shahbazi/)* (left), Dr. Magdalena Zernicka-Goetz, LSEF Board Member, *[Cambridge](http://zernickagoetzlab.pdn.cam.ac.uk/)* and *[Caltech](https://zernickagoetzlab.caltech.edu/)* (right). The LSEF Board of Directors also includes *[Dr. Angela Andersen](https://www.lifescienceeditors.com/about-the-editors/angela-andersen/)*, *[Dr. Helen Pickersgill](https://www.lifescienceeditors.com/about-the-editors/helen-pickersgill/)**,**[ Dr. Valentina Greco](http://www.grecolab.org/)*, *[Dr. Giovanna Guerrero-Medina](https://medicine.yale.edu/profile/giovanna_guerrero-medina/)*, *[Dr. Mandë Holford](https://holfordlab.com/)*, *[Dr. Sabbi Lall ](https://www.lifescienceeditors.com/about-the-editors/sabbi-lall-ph-d/)*and *[Dr. Alana Welm](https://uofuhealth.utah.edu/huntsman/labs/welm-labs/)**.**


## 2021-09-06

**Eddie** (08:22:41):
> @Eddie has joined the channel

**Eddie** (08:27:06):
> @Eddie has left the channel


## 2021-09-08

**Aedin Culhane** (10:47:58) (in thread):
> Great imitative. I’ll share with the  cab members too


## 2021-09-16

**Henry Miller** (18:35:05):
> @Henry Miller has joined the channel


## 2021-09-27

**Mikey C** (09:49:13):
> @Mikey C has joined the channel


## 2021-11-08

**Paula Nieto García** (03:26:46):
> @Paula Nieto García has joined the channel


## 2021-12-07

**Jenny Smith** (15:20:57):
> @Jenny Smith has joined the channel


## 2021-12-14

**Megha Lal** (08:24:59):
> @Megha Lal has left the channel


## 2022-03-15

**Heather Turner** (04:38:39):
> DiveRSE Keynote - Mary Ann Leung: "Normalizing inclusion by embracing difference"
> 
> DiveRSE is a series of talks and related activities including discussion and panel sessions designed to support and raise awareness of Equity, Diversity and Inclusion (EDI) challenges and successes within the research software community.
> 
> The series runs from March 2022 and is linked to the “Vive la différence - research software engineers” workshop being hosted at the Lorentz Centre in The Netherlands in April 2022.
> 
> We’re delighted to welcome Mary Ann Leung, Ph.D., Founder and President of the Sustainable Horizons Institute, as our inaugural speaker in the DiveRSE talk series.
> 
> This session explores what it takes to achieve DEI, also known as equity, diversity, inclusion (EDI) and justice, equity, diversity, inclusion (JEDI) and how reframing DEI within RSE could increase innovation and developer productivity. We will also consider how cultivating respect and embracing difference could help to normalize inclusion.
> 
> Following the talk, there will be a chance to join a faciliated discussion in breakout rooms providing an excellent opportunity to chat with Research Software Engineers and researchers from around the world.
> 
> This talk is being co-hosted with and supported by the Society of Research Software Engineering.
> 
> More information about the event can be found at[https://diverse-rse.github.io/events/2022-03-22](https://diverse-rse.github.io/events/2022-03-22).
> 
> When: Mar 22, 2022 04:00 PM UTC (London time) / 9 AM PDT (California time)
> 
> Please register for this event at[https://us06web.zoom.us/meeting/register/tZwvd-CprD4jH9Kt5smG4nGbp-YHoahn44Hm](https://us06web.zoom.us/meeting/register/tZwvd-CprD4jH9Kt5smG4nGbp-YHoahn44Hm)


## 2022-04-01

**Nitesh Turaga** (13:56:17):
> @Nitesh Turaga has left the channel


## 2022-05-03

**Heather Turner** (04:34:23):
> I'll be speaking about “EDI (Equality, Diversity & Inclusion) in the R Community” as part of the DiveRSE series, tomorrow! The talk will be followed by open discussion.
> 
> Time: Wednesday 4th May 2022 - 15:00-16:00 UTC
> Free registration:[https://us06web.zoom.us/meeting/register/tZUsduuorjItHtRqDKkgy-wqQv1hgnI2NbUZ](https://us06web.zoom.us/meeting/register/tZUsduuorjItHtRqDKkgy-wqQv1hgnI2NbUZ)More info:[https://diverse-rse.github.io/events/2022-05-04](https://diverse-rse.github.io/events/2022-05-04)
  - Attachment (diverse-rse.github.io): [DiveRSE - Supporting EDI within the RSE community](https://diverse-rse.github.io/events/2022-05-04)
> The home of a series of talks and related activities for promoting awareness of and supporting EDI within the Research Software Engineering community.


## 2022-07-01

**Aedin Culhane** (14:52:40):
> @Kozo Nishidadid you post your event to the chat ?  Kozo is organizing a really exciting event on July 9th, a translate-a-thon… so we can make Bioconductor more friendly for those for whom English is not their first language.  If you want to make Bioconductor more multi-lingual and inclusive… Kozo has the info

**Kozo Nishida** (18:26:30) (in thread):
> I haven't posted the event to the chat yet.[https://www.meetup.com/boston-r-bioconductor-for-genomics/events/286908674/](https://www.meetup.com/boston-r-bioconductor-for-genomics/events/286908674/)is the event page!
> If there's anything you are unclear on, please let me know!
  - Attachment (Meetup): [Bioconductor translation virtual sprint , Sat, Jul 9, 2022, 10:00 AM   | Meetup](https://www.meetup.com/boston-r-bioconductor-for-genomics/events/286908674/)
> Sat, Jul 9, 10:00 AM EDT: ## Details Hello! Hola! Bonjour! 你好! こんにちは! We want to open up Bioconductor to the whole world and we’d love your help to achieve [our goal]([https://chanzuckerberg.com/eo](https://chanzuckerberg.com/eo)


## 2022-07-15

**Ashley Robbins** (15:23:56):
> @Ashley Robbins has joined the channel


## 2022-07-20

**Alex Mahmoud** (13:05:28):
> @Alex Mahmoud has joined the channel


## 2022-07-21

**Andres Wokaty** (12:27:10):
> @Andres Wokaty has joined the channel

**Nitesh Turaga** (15:53:44):
> @Nitesh Turaga has joined the channel


## 2022-07-28

**Krithika Bhuvanesh** (13:50:31):
> @Krithika Bhuvanesh has joined the channel


## 2022-07-29

**Jill Lundell** (16:38:09):
> @Jill Lundell has joined the channel

**Samuel Gamboa** (17:07:35):
> @Samuel Gamboa has joined the channel


## 2022-11-09

**Selin Jessa** (22:03:40):
> @Selin Jessa has joined the channel


## 2022-11-15

**Pariksheet Nanda** (11:09:19):
> @Pariksheet Nanda has joined the channel


## 2022-12-20

**Krithika Bhuvanesh** (13:24:59):
> @Krithika Bhuvanesh has left the channel


## 2023-03-01

**jeremymchacón** (12:12:20):
> @jeremymchacón has joined the channel


## 2023-03-08

**Laurent Gatto** (03:50:37):
> Today, I read this article "[The retention problem: Women are going into tech but are also being driven out](https://theconversation.com/the-retention-problem-women-are-going-into-tech-but-are-also-being-driven-out-200625)", that specifically mentions open source projects. Among the suggestions they have to have more welcoming project, several have been put in place by Bioconductor. There is also mention of spaces that are mainly but not exclusively for women and cite Fedora Women or Debian Women. I know that several people in the project are also involved in or interact with R-ladies. But I was wondering of a Bioconductor equivalent to the above would be welcome?
  - Attachment (The Conversation): [The retention problem: Women are going into tech but are also being driven out](https://theconversation.com/the-retention-problem-women-are-going-into-tech-but-are-also-being-driven-out-200625)
> Women are severely underrepresented in tech. Strength in numbers – communities for women and women mentoring women – can counter tech’s sexist culture and help retain women in the field.

**Frederick Tan** (08:39:52) (in thread):
> Perhaps this thread?
> * [https://community-bioc.slack.com/archives/C03R9H3A86A/p1677778303961459](https://community-bioc.slack.com/archives/C03R9H3A86A/p1677778303961459)


## 2023-05-18

**Oluwafemi Oyedele** (05:54:00):
> @Oluwafemi Oyedele has joined the channel


## 2023-05-25

**Jacob Krol** (17:16:33):
> @Jacob Krol has joined the channel


## 2023-06-07

**Kayla Jackson** (13:52:21):
> @Kayla Jackson has joined the channel


## 2023-07-05

**Sonali Kumari** (16:18:30):
> @Sonali Kumari has joined the channel


## 2023-08-25

**Andrés Arredondo Cruz** (17:29:54):
> @Andrés Arredondo Cruz has joined the channel


## 2024-02-14

**Vince Carey** (07:34:01):
> see[https://community-bioc.slack.com/archives/C34NC134G/p1707850277449119](https://community-bioc.slack.com/archives/C34NC134G/p1707850277449119)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C34NC134G/p1707850277449119)
> Hello all, I have two announcements from [BWCB](http://blackwomencompbio.org):
> 
> • On February 28th, 2024 we are hosting a public townhall centering community-building around exploring opportunities for allyship in the computational biology community. We will begin by sharing some insights from our survey results capturing the experiences of various communities within the computational biology field. Many of you here participated in that survey, and we appreciate your input! We welcome you to join us for a conversation that will create space to engage critically together on what we're learning. 
>     ◦ RSVP here: [https://www.blackwomencompbio.org/event-details/townhall-on-opportunities-for-allyship-in-computational-biology](https://www.blackwomencompbio.org/event-details/townhall-on-opportunities-for-allyship-in-computational-biology)
> • We have just released applications for our 2024 [grant programs](https://www.blackwomencompbio.org/grants). If you work with colleagues or trainees who could benefit from becoming a member applying, I appreciate you sharing this with them. Applications close on March 1, 2024.


## 2024-03-11

**Melysssa Minto** (10:13:47):
> @Melysssa Minto has joined the channel


## 2024-04-26

**Kevin Rue-Albrecht** (09:57:49):
> Thrilled to announce the addition of Lithuanian in the translations of the code of conduct:party_parrot:[https://bioconductor.github.io/bioc_coc_multilingual/](https://bioconductor.github.io/bioc_coc_multilingual/)


## 2024-05-15

**Sunil Nahata** (08:31:44):
> @Sunil Nahata has joined the channel


## 2024-05-16

**Melysssa Minto** (10:07:33):
> Hello, posting an invitation to our #BlackInCompBio social happening this Friday!
> 
> Don't miss out on this fantastic opportunity to meet and connect with fellow members of the broader #BlackInCompBio community.
> Register for either session below.****#BlackInCompBio Virtual Social - Friday, May 17th, 2024**
> * [Session A](https://www.blackwomencompbio.org/event-details/blackincompbio-social-session-a-2024-05-17-09-00-1)9 am ET / 2 pm BST/ 4 pm EAT
> * [Session B](https://www.blackwomencompbio.org/event-details/blackincompbio-social-session-b-2024-05-17-17-00-1)5 pm ET / 2 pm PT / 10 pm BST
> ***Our next event***will be an in-person Women in CompBio social & fireside chat happening concurrently with the Festival of Genomics and Biodata in Boston/Cambridge. It will be co-hosted by Boston-area Women in Bioinformatics. Registration will open soon but to let me know if you're interested in the link for it.
  - Attachment (BlackWomenCompBio): [#BlackInCompBio Social  | Session A | BlackWomenCompBio](https://www.blackwomencompbio.org/event-details/blackincompbio-social-session-a-2024-05-17-09-00-1)
> Join us for a vibrant virtual gathering celebrating #BlackInCompBio! Connect with like-minded individuals, share insights, and forge new collaborations across academia, government and industry. Two sessions ensure everyone has a chance to join
> :clock6:click "Select Different Date" to switch to session B
  - Attachment (BlackWomenCompBio): [#BlackInCompBio Social | Session B | BlackWomenCompBio](https://www.blackwomencompbio.org/event-details/blackincompbio-social-session-b-2024-05-17-17-00-1)
> Join us for a vibrant virtual gathering celebrating #BlackInCompBio! Connect with like-minded individuals, share insights, and forge new collaborations across academia, government and industry. Two sessions ensure everyone has a chance to join.
> :clock6:click "Select Different Date" to switch to session A


## 2024-05-18

**Maria Doyle** (04:22:10):
> @Maria Doyle has joined the channel


## 2024-07-04

**Sounkou Mahamane Toure** (15:28:30):
> @Sounkou Mahamane Toure has joined the channel


## 2024-07-23

**Shaurita** (17:38:48):
> @Shaurita has joined the channel


## 2024-08-14

**Jayaram Kancherla** (13:34:02):
> @Jayaram Kancherla has left the channel


## 2024-08-19

**Rema Gesaka** (09:41:44):
> @Rema Gesaka has joined the channel


## 2024-11-13

**Aedin Culhane** (11:41:20):
> CZI Diversity Leadership Awards (LOI 5th Dec)[https://chanzuckerberg.com/rfa/science-diversity-leadership-award/](https://chanzuckerberg.com/rfa/science-diversity-leadership-award/)
  - Attachment (Chan Zuckerberg Initiative): [Science Diversity Leadership Award](https://chanzuckerberg.com/rfa/science-diversity-leadership-award/)


## 2024-11-21

**Leonardo Collado Torres** (14:29:41):
> Thanks for sharing!


## 2025-01-15

**Claire Rioualen** (05:04:56):
> @Claire Rioualen has joined the channel


## 2025-01-21

**Stevie Pederson** (07:46:07):
> @Stevie Pederson has joined the channel


## 2025-02-06

**Liz Hare** (11:58:13):
> @Liz Hare has joined the channel


## 2025-02-13

**JP Flores** (13:54:23):
> @JP Flores has joined the channel


## 2025-03-21

**Kevin Rue-Albrecht** (12:55:36):
> Hi everyone!
> I came across this call for interviewees from underrepresented groups writing software, code or scripts for research purposes.[https://www.software.ac.uk/news/participants-sought-inclusive-rse-study?mc_cid=50737ae853&mc_eid=5fc831271b](https://www.software.ac.uk/news/participants-sought-inclusive-rse-study?mc_cid=50737ae853&mc_eid=5fc831271b)Best,
  - Attachment (software.ac.uk): [Participants sought for inclusive RSE study | Software Sustainability Institute](https://www.software.ac.uk/news/participants-sought-inclusive-rse-study?mc_cid=50737ae853&amp;mc_eid=5fc831271b)
> Have you ever written software, code or scripts for research purposes?

**Chioma Onyido** (13:01:16):
> @Chioma Onyido has joined the channel

**Eseoghene Cynthia Princewill-Ukot** (14:26:43):
> @Eseoghene Cynthia Princewill-Ukot has joined the channel
