---
title: "#elixir"
format: gfm
---

## 2023-01-12

**Aedin Culhane** (12:00:57):
> @Aedin Culhane has joined the channel

**Leo Lahti** (12:01:14):
> @Leo Lahti has joined the channel

**Davide Risso** (12:01:14):
> @Davide Risso has joined the channel

**Maria Doyle** (12:01:14):
> @Maria Doyle has joined the channel

**Aedin Culhane** (12:02:22):
> **ELIXIR ALL Hands Meeting Dublin 5-8th June  2023****Link to s**[ubmit abstract](https://app.oxfordabstracts.com/stages/5171/submissions/new?behalf=false&fromDashboard=false&preview=false)*Information about meeting and *[abstract review criteria](https://elixir-europe.org/events/elixir-all-hands-2023)
  - Attachment (ELIXIR): [ELIXIR All Hands 2023](https://elixir-europe.org/events/elixir-all-hands-2023)
> The ELIXIR All Hands 2023 will be held in the Dublin Convention Centre, Ireland. The 9th ELIXIR All Hands meeting will take place 5-8 June 2023 in Ireland. The meeting brings together members of the

**Aedin Culhane** (12:02:42):
> * There are 4 themes to the meeting this year**’’Science - Enabling scientists to access and analyse life science data”**
> * **’’Technology - Delivering services to support federated data management and analytics”**
> * *“Nodes - Equipping national Nodes for successful long-term operations” *
> * **“People - Developing people and capacity to benefit science and society”**

**Aedin Culhane** (12:03:04):
> We could submit under science or people

**Simone Bell** (12:04:10):
> @Simone Bell has joined the channel

**Federico Marini** (12:04:10):
> @Federico Marini has joined the channel

**Vince Carey** (12:04:54):
> @Vince Carey has joined the channel

**Levi Waldron** (12:04:54):
> @Levi Waldron has joined the channel

**Charlotte Soneson** (12:04:54):
> @Charlotte Soneson has joined the channel

**Aedin Culhane** (12:07:16):
> Session/workshops are 90 mins long and  the submission deadline is***Monday 23 January, 2023.  For submission, we need a title, abstract (400 words) and a list of presenters of which 2 need to attend in person.  ***Leo, Maria and I can most likely attend in person, so we have sufficient to submit an abstract for a session.  We just need to define the abstract and session

**Aedin Culhane** (12:13:27):
> There are currently 239 training materials from Bioconductor on the[ELIXIR training platform](https://tess.elixir-europe.org/content_providers)
  - Attachment (tess.elixir-europe.org): [TeSS (Training eSupport System)](https://tess.elixir-europe.org/content_providers)

**Aedin Culhane** (12:15:27):
> with 0 upcoming events and 1 past event (which was a Bioc2020 conference workshop?)

**Aedin Culhane** (12:20:16):
> [Slides](https://docs.google.com/presentation/d/10hMdBFX2x3pTc95HyEzG6xg0V0nKBtd0batf5M8SJYg/edit#slide=id.g1277deaf704_0_0)presented at last year’s meeting about the ELIXIR training portal[and its abstract/title/presenters](https://docs.google.com/document/d/1vlHODVnN9RFTp2fr2NCcLV4ujb8Js3EH6NqXHfP_F9E/edit#)

**Aedin Culhane** (12:29:40):
> I think we should think about leverages some of the ELIXIR resources for our global training platform …
> 
> I  like their dashboard…[https://training-metrics-dev.elixir-europe.org/dashboard](https://training-metrics-dev.elixir-europe.org/dashboard)Courses are registered via a simple web app (I recently did an ELIXIR training courses.. its was just a standard training course but it was registered with ELIXIR.. the form took 2 min to fill in). The course info is represented via their bioschema ([https://bioschemas.org](https://bioschemas.org)) and is available to the API which present course info/dashboard etc.
> 
> They also have course metrics and surveys…
  - Attachment (bioschemas.org): [Bioschemas - Bioschemas](https://bioschemas.org)
> Bioschemas relies and extends from [schema.org](http://schema.org) and aims to reuse existing standards and reach consensus among a wide number of life sciences organizations and communities.

**Aedin Culhane** (12:29:54):
> [https://training-metrics-dev.elixir-europe.org/dashboard](https://training-metrics-dev.elixir-europe.org/dashboard)

**Martin Grigorov** (13:06:00):
> @Martin Grigorov has joined the channel

**Lluís Revilla** (13:06:09):
> @Lluís Revilla has joined the channel

**Frederick Tan** (13:13:23):
> @Frederick Tan has joined the channel

**Leo Lahti** (14:41:01) (in thread):
> I like both.

**Leo Lahti** (14:42:18):
> Great. I have not been in events making general Bioc outreach. Would be nice to know if this is more familiar to some of you, and if there is some earlier material/experiences that can be utilized.

**Leo Lahti** (14:42:48):
> Or if you have a vision.

**Federica Gazzelloni** (17:04:57):
> @Federica Gazzelloni has joined the channel

**Maria Doyle** (17:38:18):
> Not a concrete vision for the workshop just some thoughts,
> 
> Elixir are finalising their scientific programme for 2024-2028 this year[https://elixir-europe.org/about-us/what-we-do/2024-28-programme](https://elixir-europe.org/about-us/what-we-do/2024-28-programme)They have an interest in collaborations with international organisations of value to their members (Bioc is not listed on that page, could ite be)[https://elixir-europe.org/events/consultation-event-international-engagement](https://elixir-europe.org/events/consultation-event-international-engagement)There is an ELIXIR Galaxy community[https://elixir-europe.org/communities/](https://elixir-europe.org/communities/)[https://galaxyproject.org/news/2022-06-21-elixirah22/](https://galaxyproject.org/news/2022-06-21-elixirah22/)But no ELIXIR Bioconductor community, should there be?
> 
> Wondering if the workshop should have 2 parts 1- highlight what Bioconductor is doing that overlaps with Elixir interests and 2- have time (30 min) for discussion/breakout session like the workshop Aedin linked to here[https://docs.google.com/document/d/1vlHODVnN9RFTp2fr2NCcLV4ujb8Js3EH6NqXHfP_F9E/edit#](https://docs.google.com/document/d/1vlHODVnN9RFTp2fr2NCcLV4ujb8Js3EH6NqXHfP_F9E/edit#)? e.g. "Engagement between Bioconductor and ELIXIR"? to get input on how Bioc could most usefully mutually engage with ELIXIR. Also may help get Bioconductor on the radar for their scientific programme for 2024-2028 which could help with growing and strengthening Bioc community.
> 
> Potential overlapping areas of interest we could perhaps discuss in workshop from viewing[Elixir 2021 report](https://elixir-europe.org/news/2021-annual-report)(might be wrong and/or more I missed)
> Platforms[https://elixir-europe.org/platforms](https://elixir-europe.org/platforms)Tools - benchmarking tools & workflows, EDAM, biotools
> 	Training - workshops, materials, events, TESS,
> Communities -[https://elixir-europe.org/communities](https://elixir-europe.org/communities)Single Cell Omics, Proteomics
  - Attachment (ELIXIR): [ELIXIR Programme for 2024-2028 | Consultation event on international engagement](https://elixir-europe.org/events/consultation-event-international-engagement)
> Objectives This 2 hour online event aims to provide ELIXIR Nodes with an opportunity to influence international engagement as part of the upcoming ELIXIR Programme for 2024-2028. The event’s outputs
  - Attachment (galaxyproject.org): [Galaxy taking part @ Elixir All Hands 2022](https://galaxyproject.org/news/2022-06-21-elixirah22/)
> During 6-9th of June, members of the European Galaxy team travelled to Amsterdam to join the ELIXIR All Hands meeting 2022 where we joined other colleagues from ELIXIR-DE.

**Mae Woods** (19:04:02):
> @Mae Woods has joined the channel


## 2023-01-13

**Leo Lahti** (02:19:24):
> Sounds good to me at least.

**Charlotte Soneson** (02:35:56) (in thread):
> Regarding a potential Bioconductor ELIXIR Community - if we decide to give this a try, I think it would make sense to talk to the Galaxy team again to get their experience (we have touched upon it on a couple of occasions already). It takes a decent amount of time to get a new community set up (for the recent single-cell community I'd say it took about 2.5 years from the first concrete document was initialised to the approval - I'm not sure if this is representative, but in any case the application has to go through a bunch of different stages).

**Hans-Rudolf Hotz** (03:30:13):
> @Hans-Rudolf Hotz has joined the channel

**Christian Panse** (03:58:18):
> @Christian Panse has joined the channel

**Gavin Rhys Lloyd** (07:32:06):
> @Gavin Rhys Lloyd has joined the channel

**Deena Gendoo** (08:32:07):
> @Deena Gendoo has joined the channel

**Jayaram Kancherla** (16:36:28):
> @Jayaram Kancherla has joined the channel

**Vince Carey** (19:18:35):
> @Wolfgang Huber^^

**Wolfgang Huber** (19:18:40):
> @Wolfgang Huber has joined the channel


## 2023-01-17

**Roy Storey** (16:05:19):
> @Roy Storey has joined the channel


## 2023-01-18

**José Basílio** (13:09:46):
> @José Basílio has joined the channel


## 2023-01-20

**Aedin Culhane** (17:41:45):
> I updated the[google doc](https://docs.google.com/document/d/1LvIicx3bduY3SEZkhR66DIbOx_pf_l_uy7Gdre3WyWY/edit#)..  welcome your suggestions and contributions. The submission deadline is***Monday 23 January, 2023.  For submission, we need a title, abstract (400 words) and a list of presenters of which 2 need to attend in person.  ***Please add your name if you are a member of ELIXIR and wish to contribute.


## 2023-01-21

**Mark Robinson** (10:07:47):
> @Mark Robinson has joined the channel


## 2023-01-22

**Kozo Nishida** (03:37:39):
> @Kozo Nishida has joined the channel

**Maria Doyle** (16:02:12):
> Following on from Aedin's message above, we plan to submit the abstract in the[google doc](https://docs.google.com/document/d/1LvIicx3bduY3SEZkhR66DIbOx_pf_l_uy7Gdre3WyWY/edit#)~12pm GMT tomorrow Monday 23rd Jan, if anyone wants to add more comments please do before then:pray:


## 2023-01-23

**Almut** (02:28:35):
> @Almut has joined the channel

**Aedin Culhane** (07:39:17):
> <!channel>We are submitting the abstract in the[google doc](https://docs.google.com/document/d/1LvIicx3bduY3SEZkhR66DIbOx_pf_l_uy7Gdre3WyWY/edit#)shortly.  Please review and add final comment

**Maria Doyle** (09:34:40):
> Ok submitted, says will be notified on outcome Feb 10th. Thanks all!


## 2023-01-27

**Helge Hecht** (08:23:01):
> @Helge Hecht has joined the channel

**Sean Davis** (15:30:14):
> @Sean Davis has joined the channel


## 2023-01-31

**Aedin Culhane** (07:01:37):
> EU folks… has anyone experience in microcredential courses?


## 2023-02-06

**Maria Doyle** (10:37:40):
> Good news, workshop has been accepted:tada:
> > I am pleased to inform you that your workshop submission (Opportunities for Bioconductor and ELIXIR communities to co-develop training infrastructures) has been accepted for the ELIXIR All Hands Meeting 2023.
> > 
> > Guidelines for further preparation are attached and will shortly be posted on the conference website. As a workshop lead you and your named co-lead have been pre-registered for the event. Other speakers will need to register through the normal links, registration will open at the end of February. 
> > 
> > We look forward to seeing you in Dublin Convention Centre in June.


## 2023-02-10

**Daniel Adediran** (19:44:13):
> @Daniel Adediran has joined the channel

**Laurent Gatto** (20:07:18):
> @Laurent Gatto has joined the channel


## 2023-02-11

**rohitsatyam102** (07:54:04):
> @rohitsatyam102 has joined the channel


## 2023-02-12

**Umar Ahmad** (06:46:03):
> @Umar Ahmad has joined the channel


## 2023-02-17

**Frederick Tan** (10:22:00):
> Perhaps relevant?  Hybrid ELIXIR Single-Cell Omics Community workshop in Geneva on March 21/22 for data analysis trainers[https://bit.ly/SCOtrainerWorkshop2023](https://bit.ly/SCOtrainerWorkshop2023)


## 2023-02-20

**Aedin Culhane** (12:19:52):
> @Charlotte SonesonWhat is the overlap between GOBLET and ELIXIR?


## 2023-02-21

**Charlotte Soneson** (02:48:33) (in thread):
> Not sure I have the full picture/answer here, but they're collaborating on training, see e.g.[https://elixir-europe.org/system/files/goblet-elixir_partnership-final.pdf](https://elixir-europe.org/system/files/goblet-elixir_partnership-final.pdf)


## 2023-02-27

**Aedin Culhane** (05:42:03):
> FYI.  See calls for proposals for Elixir biohackathon (30 Oct-3 Nov),[Hacking projects (](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbiohackathon-europe.org%2Fprojects.html&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055038114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cd3MVDTQPqPl%2FO65DuA9H2kXDdi5UXRLa80Wx3vPmm0%3D&reserved=0)[biohackathon-europe.org](http://biohackathon-europe.org)[)](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbiohackathon-europe.org%2Fprojects.html&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055038114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cd3MVDTQPqPl%2FO65DuA9H2kXDdi5UXRLa80Wx3vPmm0%3D&reserved=0)A hackathon is not necessarily coding, I think it can sometimes be e.g. developing protocols and standards, etc relevant to coding
> 
> 
> SCOPE
> BioHackathon activities are driven by practical sessions where people gather, discuss, and implement ideas and projects during intensive and productive coding sessions. The topics will be aligned to challenges proposed by[ELIXIR Platforms](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Felixir-europe.org%2Fplatforms&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055038114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BfzHIG%2FyhaCmzeGtnWZgCYx8Yo%2BKelEsSTG3ZSz7eLU%3D&reserved=0),[ELIXIR Communities](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Felixir-europe.org%2Fcommunities&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055038114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=35rz3cPH8eofFKPErMbCnYhIHT6N0nLZ9%2FZR1kJFLME%3D&reserved=0), and/or[Focus Groups](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Felixir-europe.org%2Ffocus-groups&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055194287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wHrp2AGw4ZnaJjFdsGDi%2FGDd2pw7oyBPiyZVmNPG2bU%3D&reserved=0), and a set of common challenges proposed by the sister[BioHackathon](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.biohackathon.org%2F&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055194287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qSD1Lgs64w1lSiYvPvr%2F8gVmwjEXC42kcZogj2wLZok%3D&reserved=0)organised in Japan.
> GOALS
> · Advance the development of an open source infrastructure for data integration to accelerate scientific innovation. We will focus on technology implementations such as FAIR, identifiers, metadata standards, ontologies and metadata catalogues that support the operations across[ELIXIR Platforms](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.elixir-europe.org%2Fplatforms&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055194287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NBLQL%2FHQGYtoxpCxfe%2BKyGizqUnyXZptszJ6ZrgmrcM%3D&reserved=0),[Communities](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.elixir-europe.org%2Fcommunities&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055194287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TE3W8I6kWa5nyzCKUUYNqFZD92lwv9S4UgVuSyVeYfU%3D&reserved=0)and[Focus Groups](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Felixir-europe.org%2Ffocus-groups&data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055194287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wHrp2AGw4ZnaJjFdsGDi%2FGDd2pw7oyBPiyZVmNPG2bU%3D&reserved=0).
> · Engage technical people in the bioinformatics community inside and outside ELIXIR to work together on topics of common interest aligned to ELIXIR activities
> · Strengthen the interactions with ELIXIR Platforms, Communities and Focus Groups to establish and reinforce collaborations through hands-on programming activities.
  - Attachment (biohackathon-europe.org): [Hacking projects](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbiohackathon-europe.org%2Fprojects.html&amp;data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055038114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=cd3MVDTQPqPl%2FO65DuA9H2kXDdi5UXRLa80Wx3vPmm0%3D&amp;reserved=0)
> Barcelona 30 October - 3 November 2023
  - Attachment (biohackathon.org): [> BioHackathon](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.biohackathon.org%2F&amp;data=05%7C01%7Caedin.culhane%40ul.ie%7Caa59c71da0604963405c08db18abb9e1%7C0084b9243ab4411692519939f695e54c%7C0%7C0%7C638130898055194287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=qSD1Lgs64w1lSiYvPvr%2F8gVmwjEXC42kcZogj2wLZok%3D&amp;reserved=0)


## 2023-03-03

**Maria Doyle** (09:05:02):
> <!channel>our Elixir All Hands workshop "Opportunities for Bioconductor and ELIXIR communities to co-develop training infrastructure"  will be***Tuesday June 6th 11-12.30pm GMT.***If you're interested to take part in[the agenda](https://docs.google.com/document/d/13cwMip37eQMIc75pztdXun-zTzYYREQmo_HXqV-rm94/)please let me know as we'll start populating it in the next week or so.

**Jayaram Kancherla** (09:56:43):
> @Jayaram Kancherla has left the channel


## 2023-04-03

**Manuel Barrios Izás** (02:07:46):
> @Manuel Barrios Izás has joined the channel


## 2023-04-05

**Martin Grigorov** (02:52:31):
> @Martin Grigorov has left the channel


## 2023-04-06

**Marcel Ramos Pérez** (16:11:34):
> @Marcel Ramos Pérez has joined the channel


## 2023-04-12

**Nils Hoffmann** (11:18:59):
> @Nils Hoffmann has joined the channel


## 2023-05-03

**Maria Doyle** (13:21:35):
> <!channel>if you would like to contribute (either in-person in Dublin or remotely) to the Elixir All Hands workshop “Opportunities for Bioconductor and ELIXIR communities to co-develop training infrastructure” on June 6th 11-12.30pm GMT please let me know.


## 2023-05-11

**Monica Valecha** (12:44:54):
> @Monica Valecha has joined the channel


## 2023-06-01

**Alex Mahmoud** (14:43:17):
> @Alex Mahmoud has joined the channel

**irem Kahveci** (17:48:01):
> @irem Kahveci has joined the channel


## 2023-06-06

**Gil Poiares-Oliveira** (06:13:29):
> @Gil Poiares-Oliveira has joined the channel

**Lisanna Paladin** (06:24:25):
> @Lisanna Paladin has joined the channel

**USLACKBOT** (11:15:58):
> ***ELIXIR***has joined this channel by invitation from***community-bioc***.

**U01PW0NJL7M** (11:15:58):
> @U01PW0NJL7M has joined the channel

**U023FUYM75F** (11:22:09):
> @U023FUYM75F has joined the channel

**U02433X2S76** (11:22:17):
> @U02433X2S76 has joined the channel

**U023G6CU3QV** (11:22:25):
> @U023G6CU3QV has joined the channel

**U023JDZ6Q4S** (11:22:31):
> @U023JDZ6Q4S has joined the channel

**U01DFST06UX** (11:23:25):
> @U01DFST06UX has joined the channel

**U023ZUCS4UR** (11:23:34):
> @U023ZUCS4UR has joined the channel


## 2023-06-07

**Aedin Culhane** (09:11:56):
> ELIXIR single cell ’omics community have a co-lead position open if any is interested

**Aedin Culhane** (09:13:25):
> If anyone wants to assist Maria in plans to update connectivity between Tess and Bioconductor by building support for Bioschema, let Maria know[https://tess.elixir-europe.org/content_providers/bioconductor](https://tess.elixir-europe.org/content_providers/bioconductor)
  - Attachment (tess.elixir-europe.org): [Bioconductor](https://tess.elixir-europe.org/content_providers/bioconductor)
> Open development software project, based on the R programming language,
>  providing tools for the analysis of high-throughput genomic data. The project aims to enable
>  interdisciplinary research, collaboration and rapid development of scientific software.

**Aedin Culhane** (09:13:45):
> [https://tess.elixir-europe.org/materials/getting-started-with-bioschemas](https://tess.elixir-europe.org/materials/getting-started-with-bioschemas)

**U023JDZ6Q4S** (09:20:06):
> there is some discussion in<#C0262CVJSC9>on this topic too:slightly_smiling_face:[https://elixir-europe.slack.com/archives/C0262CVJSC9/p1686061370798999](https://elixir-europe.slack.com/archives/C0262CVJSC9/p1686061370798999)
  - Attachment: [Attachment](https://elixir-europe.slack.com/archives/C0262CVJSC9/p1686061370798999)
> We should get in contact with Maria Doyle to discuss about Bioschemas scraping of Bioconductor training material. It looks like a very nice opportunity to work together!


## 2023-06-08

**U02433X2S76** (07:30:12):
> <@U04T1MQNFN1>looks like you have a busy future ahead of you. Obviously we need a bit of time to develop these initial ideas and plans but it would be really good if at some point just after summer we could dedicate some time to Bioconductor and Elixir collaborating in one of the regular Training Platform meetings.

**U04T1MQNFN1** (09:37:46):
> That would be great


## 2023-06-09

**Aedin Culhane** (17:16:43):
> Biohackathon projects for Barcelona.[https://biohackathon-europe.org/projects.html](https://biohackathon-europe.org/projects.html)
  - Attachment (biohackathon-europe.org): [Hacking projects](https://biohackathon-europe.org/projects.html)
> Barcelona 30 October - 3 November 2023


## 2023-06-13

**Maria Doyle** (13:15:44):
> Bioconductor website survey is now LIVE and posted about in Bioconductor Slack and Elixir Slack#generalchannels.
> * [https://community-bioc.slack.com/archives/C35G93GJH/p1686661875820929](https://community-bioc.slack.com/archives/C35G93GJH/p1686661875820929)
> * [https://elixir-europe.slack.com/archives/C01DPT2E2DU/p1686674062828269](https://elixir-europe.slack.com/archives/C01DPT2E2DU/p1686674062828269)
> Posting survey link here as<@U02433X2S76>, thanks for your previous feedback, this is the official survey link if you want to share with your users[https://t.maze.co/169169456](https://t.maze.co/169169456)

**U02433X2S76** (13:38:23):
> Thanks. I'll share it about.


## 2023-08-10

**U059439UP70** (08:57:34):
> Microbiome data science with R/Bioconductor course in****:****University of Bergen  October 9-12, 2023:[https://norbis.w.uib.no/microbiome-data-science-with-r-bioconductor/](https://norbis.w.uib.no/microbiome-data-science-with-r-bioconductor/)


## 2023-09-11

**U059AN3RK98** (12:09:21):
> Nice slides set on ELIXIR TESS history[https://docs.google.com/presentation/d/1Qt9eD_NRPItBa0WpkyA2ejdPKrsPZlnb/edit#slide=id.p5](https://docs.google.com/presentation/d/1Qt9eD_NRPItBa0WpkyA2ejdPKrsPZlnb/edit#slide=id.p5)

**U059AN3RK98** (12:10:45):
> <!channel>Hope to see you EuroBioc next week in Brussels … Should be have a BOFI..

**U059AN3RK98** (12:11:20):
> deadline for submission is Sept 20[https://eurobioc2023.bioconductor.org/submissions/](https://eurobioc2023.bioconductor.org/submissions/)
  - Attachment (eurobioc2023.bioconductor.org): [Submissions](https://eurobioc2023.bioconductor.org/submissions/)
> Submissions

**Leo Lahti** (12:43:09):
> I can only be in Gent on Wed-Thu, so Fri BoF I will miss.


## 2023-09-12

**Aedin Culhane** (04:28:33):
> The ELIXIR-Germany BioHackathon projects were just announced and we are back again this year with SpaceHack 2.0! This time we focus on establishing systematic benchmarking for spatial cluster/domain identification in spatial transcriptomics data. Please spread the word to your groups and networks – those interested can register via this link:[https://www.denbi.de/helpdesk?option=com_rsform&view=rsform&formId=7](https://www.denbi.de/helpdesk?option=com_rsform&view=rsform&formId=7).
  - Attachment (denbi.de): [HelpDesk](https://www.denbi.de/helpdesk?option=com_rsform&amp;view=rsform&amp;formId=7)
> The 'German Network for Bioinformatics Infrastructure – de.NBI' is a national, academic and non-profit infrastructure supported by the Federal Ministry of Education and Research providing bioinformatics services to users in life sciences research and biomedicine in Germany and Europe. The partners organize training events, courses and summer schools on tools, standards and compute services provided by de.NBI to assist researchers to more effectively exploit their data.


## 2023-10-09

**U059AN3RK98** (09:52:46):
> @Dario Righellihas questions about the Space Biohackathon[https://cloud.denbi.de/about/testimonials/denbi-biohackathon-spacehack-project/](https://cloud.denbi.de/about/testimonials/denbi-biohackathon-spacehack-project/). Connecting you<@U027T75LNSC>

**Dario Righelli** (10:12:08) (in thread):
> Thanks@Aedin Culhane, I was interested to have a few more details on how the hackathon is organised and/or if there are already some defined aims for it.
> Thanks!

**U059AN3RK98** (12:39:43):
> For Bioconductor folks..[https://elixir-europe.org/events/elixir-single-cell-omics-community-f2fhybrid-meeting-0](https://elixir-europe.org/events/elixir-single-cell-omics-community-f2fhybrid-meeting-0)
  - Attachment (ELIXIR): [ELIXIR Single Cell Omics Community F2F/hybrid meeting](https://elixir-europe.org/events/elixir-single-cell-omics-community-f2fhybrid-meeting-0)
> This year, we are combining the annual community gathering with the FAIR Data Management Workshop. The annual meeting is scheduled for October 18th and will be hosted at the EMBL-EBI Campus in


## 2023-10-12

**U027T75LNSC** (07:01:43) (in thread):
> Oops - I missed this.
> Thanks for reaching out! The hackathon itself is organised by de.NBI (the German Network for Bioinformatics, a.k.a ELIXIR-Germany) as part of the[German BioHackathon](https://www.denbi.de/de-nbi-events/1547-biohackathon-germany-2). They deal with all the organisation aspects (food, location, registration, ...). I deal with organizing and running the project covering the topics, providing centralized cloud compute, and day-to-day entertainment/motivation.
> We have another iteration to take place this year in December:[https://spatialhackathon.github.io/](https://spatialhackathon.github.io/)If you are interested in the administrative/technical organisation of the hackathon then you want to contact de.NBI ([contact@denbi.de](mailto:contact@denbi.de)), otherwise we can chat further about the SpaceHack v1/v2 projects:slightly_smiling_face:


## 2023-12-30

**Aedin Culhane** (09:32:25):
  - Attachment (datascience.cancer.gov): [Sharing Cancer Research Software? NIH Wants to Hear from You! | CBIIT](https://datascience.cancer.gov/news-events/news/sharing-cancer-research-software-nih-wants-hear-you)
> Are you working with source codes, algorithms, workflows, and other software in your cancer research? NIH wants to hear from you! Respond today to help NIH develop new best-practice guidelines.


## 2024-02-04

**Leo Lahti** (09:15:42):
> European Conference on Computational Biology (ECCB) 2024 will take place in Turku, Finland on Sep 16-20:
> CfP:[https://eccb2024.fi/calls](https://eccb2024.fi/calls)There is a special "ELIXIR Communities Track".  As this is my home town & I am in the local org. committee, I will be present in any case. Hence I was thinking whether The ELIXIR Bioconductor Community should consider something here. Is anyone else planning to join? The DL for workshops and tutorials is Feb 15, proceedings March 14, highlight talks and posters Apr 23.


## 2024-02-09

**Levi Waldron** (09:23:28):
> @Levi Waldron has left the channel


## 2024-03-26

**U031FT693FD** (13:26:18):
> Hi everyone, is there anyone who have experience with developing R bioconductor package?

**Vince Carey** (13:36:46):
> <@U031FT693FD>Consider visiting#developers-mentorshipand#developers-forum

**U031FT693FD** (13:47:11):
> I do not have access@Vince Carey, both are private
  - File (PNG): [image.png](https://elixir-europe.slack.com/files/U34P8RS3B/F06REQCHG03/image.png)

**Maria Doyle** (13:51:52):
> <@U031FT693FD>actually#developers-mentorshipand#developers-forumare public channels within the Bioconductor Slack workspace. This channel where you’ve posted your question is a shared channel between Bioconductor and Elixir workspaces. To access the channels Vince mentioned, you’ll need to join the Bioconductor Slack through this link:[https://slack.bioconductor.org/](https://slack.bioconductor.org/). Once you’re in, you should hopefully get the help and guidance you’re looking for regarding R Bioconductor package development. Hope to see you there!

**U031FT693FD** (13:56:44):
> Ah, I thought it is in ELIXIR ... Thanks for pointing this out :)


## 2024-05-18

**Aedin Culhane** (11:02:45) (in thread):
> I was thinking of going but not confirmed


## 2024-06-02

**Aedin Culhane** (14:44:47):
> :mega:EuroBioC2024 Registration is Open!:tada:We are excited to share that registration for EuroBioC2024 is open! Join us for the European Bioconductor conference in beautiful Oxford, UK, from September 4-6.  Secure your spot and take advantage of discounted accommodation by registering now!:point_right:[https://eurobioc2024.bioconductor.org/registration/](https://eurobioc2024.bioconductor.org/registration/)Help spread the word!:pray:
> * [https://www.linkedin.com/feed/update/urn:li:activity:7202223655781580800](https://www.linkedin.com/feed/update/urn:li:activity:7202223655781580800)
> * [https://genomic.social/@bioconductor/112534743328078110](https://genomic.social/@bioconductor/112534743328078110)
  - Attachment (eurobioc2024.bioconductor.org): [Registration](https://eurobioc2024.bioconductor.org/registration/)
> Registration
  - Attachment (linkedin.com): [Bioconductor on LinkedIn: #eurobioc2024 #bioinformatics #rstats #bioconductorcommunity](https://www.linkedin.com/feed/update/urn:li:activity:7202223655781580800)
> :mega: Registration for EuroBioC2024 is open! :tada:
> 
> Join us for the European Bioconductor conference in beautiful Oxford, UK, from September 4-6. This event focuses…
  - Attachment (genomic.social): [Bioconductor (@bioconductor@genomic.social)](https://genomic.social/@bioconductor/112534743328078110)
> Attached: 1 image
> 
> :mega: Registration for EuroBioC2024 is open! :tada:
> 
> Join us for the European Bioconductor conference in beautiful Oxford, UK, from September 4-6. This event focuses on cutting-edge bioinformatics and data analysis using R and Bioconductor. :computer::dna: Secure your spot and take advantage of discounted accommodation by registering now! 
> 
> :point_right: Register here: [https://buff.ly/4aHLu7m](https://buff.ly/4aHLu7m) 
> 
> #EuroBioC2024 #Bioinformatics #RStats #BioconductorCommunity


## 2024-06-27

**U059AN3RK98** (07:07:22):
> For anyone at Galaxy,<@U04T1MQNFN1>will be speaking today.
  - File (PNG): [image.png](https://elixir-europe.slack.com/files/U34P8RS3B/F079LLCRM0X/image.png)
  - File (PNG): [image.png](https://elixir-europe.slack.com/files/U34P8RS3B/F07A3MLMBAQ/image.png)

**U059AN3RK98** (07:15:39):
  - Attachment: [Attachment](https://elixir-europe.slack.com/archives/C024G2NUZNU/p1688112333130529)
> @U05EV1P8L2X has joined the channel


## 2024-09-15

**Aedin Culhane** (14:02:08):
> [https://elixir-europe.org/sites/default/files/documents/Final-Memorandum-of-Agreement-between-ELIXIR-NIH_ODSS.pdf](https://elixir-europe.org/sites/default/files/documents/Final-Memorandum-of-Agreement-between-ELIXIR-NIH_ODSS.pdf)


## 2024-09-20

**Aedin Culhane** (09:16:26):
> Hi, Should we write a  blog post for[https://blog.bioconductor.org/](https://blog.bioconductor.org/)announcing the MoU and listing the ELIXIR/NIH projects in which Bioconductor is involved.
  - Attachment (blog.bioconductor.org): [Bioconductor community blog](https://blog.bioconductor.org/)
> A blog for the Bioconductor community!


## 2024-12-10

**U073FHNT4MB** (04:51:00):
> Hi there! Just randomly discovered the existence of this channel:sweat_smile:

**Maria Doyle** (12:32:07):
> :wave:hi Claire, glad you found it:relaxed:
