---
title: "#eurobioc2020-chairs"
format: gfm
---

## 2020-12-11

**Davide Risso** (04:25:18):
> @Davide Risso has joined the channel

**Davide Risso** (04:25:18):
> set the channel description: Channel to discuss among chairs during EuroBioc2020

**Charlotte Soneson** (08:10:14):
> @Charlotte Soneson has joined the channel

**Levi Waldron** (08:13:50):
> @Levi Waldron has joined the channel

**Gabriele Sales** (08:13:50):
> @Gabriele Sales has joined the channel

**chiara romualdi** (08:13:50):
> @chiara romualdi has joined the channel

**Wolfgang Huber** (08:13:50):
> @Wolfgang Huber has joined the channel

**Simone Bell** (08:13:51):
> @Simone Bell has joined the channel

**Federico Marini** (08:13:51):
> @Federico Marini has joined the channel

**Kevin Rue-Albrecht** (08:13:51):
> @Kevin Rue-Albrecht has joined the channel

**Laurent Gatto** (08:13:51):
> @Laurent Gatto has joined the channel

**Andrea Rau** (08:19:32):
> @Andrea Rau has joined the channel

**Friederike Dündar** (08:19:33):
> @Friederike Dündar has joined the channel

**Susan Holmes** (08:19:33):
> @Susan Holmes has joined the channel

**Michael Love** (08:19:33):
> @Michael Love has joined the channel

**Chris Vanderaa** (08:19:33):
> @Chris Vanderaa has joined the channel

**Mike Smith** (08:19:33):
> @Mike Smith has joined the channel

**Michael Stadler** (08:19:34):
> @Michael Stadler has joined the channel

**Aedin Culhane** (08:19:34):
> @Aedin Culhane has joined the channel

**Koen Van den Berge** (08:19:34):
> @Koen Van den Berge has joined the channel

**Britta Velten** (08:19:34):
> @Britta Velten has joined the channel

**Michael Love** (08:19:44):
> :wave:

**Federico Marini** (08:35:41):
> Hi there everyone:slightly_smiling_face:

**Mike Smith** (08:41:24):
> Just a quick question about chairing the workshop sessions.  The instructions say:
> > It is important that we only use the questions feature on the platform. Please do not use the chat and do not let people from the audience join the chat. Ignore the raise hands feature.
> Is this also the plan for the workshops?  It feels like we might want to be more interactive in those.

**Kevin Rue-Albrecht** (08:49:02):
> oh yeah - (long) workshops definitely should be more interactive (not only text-based questions). I'd say that in those cases it'll be more up to the speaker to declare how they prefer to manage the session. The raised hand feature would clearly be helpful in long interactive workshops, to invite participants on screen and perhaps share their solution/bug on an exercise. Instead, talks and 'demonstration-only workshops' should use the Questions feature, so that the chair only has one place to monitor and manage questions.

**Katharina Imkeller** (09:31:27):
> @Katharina Imkeller has joined the channel

**Simone Bell** (09:49:57):
> Welcome Katharina!

**Katharina Imkeller** (09:56:16):
> Coucou everyone:slightly_smiling_face:I think I understood most of the instructions, but I am not sure how I will be able to chair 2 consecutive sessions. If I moderate the questions from session 1 I should already help setting up session 2 in the backstage. There are 5 min breaks, but is this enough? Maybe we somehow coordinate this between chair 1 and 2.

**Friederike Dündar** (10:18:33):
> Hola! What's the role of chair 2? Making sure to take over in case chair 1 happens to be incapacitated?

**Gabriele Sales** (10:24:14):
> Hi@Friederike Dündar. That, and giving Chair 1 some help with questions from the audience.

**Friederike Dündar** (10:25:02):
> Moral support/answering or in regard to the technological hurdles?

**Davide Risso** (10:25:16):
> Note that Chair 2 will be added as “speaker” in the platform because there is only one official “host” slot per session

**Davide Risso** (10:26:01) (in thread):
> The questions will be asked by the audience using a within-platform version of slido

**Davide Risso** (10:27:05) (in thread):
> so while Chair 1 is in charge of relaying the question to the speakers, Chair 2 can keep an additional eye for unanswered questions

**Friederike Dündar** (10:27:27) (in thread):
> sounds good

**Katharina Imkeller** (10:27:28):
> Can we swap the chair 1/ chair 2 assignments in cases where chair 1 would have to moderate several consecutive sessions (problem as stated above).

**Davide Risso** (10:27:37) (in thread):
> and perhaps check the chat for questions asked there instead of in the questions box

**Simone Bell** (10:35:45):
> sure, you could discuss with your chair 2 directly, or even better, refuse to chair consecutive sessions where it gets too tight for you in terms of time.

**Simone Bell** (10:36:32):
> If someone feels like making suggestions to the Google Doc with instructions, please do in "suggesting" mode. Thanks!

**Katharina Imkeller** (10:39:29) (in thread):
> @Gabriele Saleswould you like to chair long talk 5 on Thursday? I was supposed to do that, but I was not aware of the problem with switching sessions.

**Gabriele Sales** (10:45:38) (in thread):
> Yes, no problem.


## 2020-12-12

**Huipeng Li** (00:40:10):
> @Huipeng Li has joined the channel

**Susan Holmes** (02:26:27):
> :wave:

**Huipeng Li** (04:40:19):
> @Huipeng Li has left the channel


## 2020-12-13

**Davide Risso** (04:17:55):
> Hi@Charlotte Sonesonand@Katharina Imkellerdid you check in with the speakers in your tomorrow’s sessions? Should we expect any recorded videos or are they all giving a live talk? Just so that I know if I have to upload any videos into the platform tomorrow...

**Charlotte Soneson** (04:18:45):
> I have not heard back from everyone - so far, no pre-recorded talks

**Kevin Rue-Albrecht** (05:30:52):
> Sanity check: my talk for BiocChallenges is pre recorded but I’ve already uploaded it myself as a test. All good?

**Katharina Imkeller** (07:30:49):
> I have so far only heard back from 3/5 of the speaker for tomorrow. No pre-recorded talks so far.

**Federico Agostinis** (16:09:05):
> @Federico Agostinis has joined the channel


## 2020-12-14

**Laurent Gatto** (07:56:19):
> Are the backup chairs needed backstage?

**Charlotte Soneson** (07:57:25) (in thread):
> All speakers in my session will give live talks, now confirmed.

**Federico Marini** (08:17:38):
> I’m there as well, if you want to join (keep in mind to keep mic & video off)

**Katharina Imkeller** (08:22:08):
> In order to go backstage while the session is running, one has to join and then raise hand?

**Laurent Gatto** (08:24:43):
> Won't join now for fear of disturbing. Just available in needed.

**Davide Risso** (08:25:35):
> Yeah, I think that's the role of backup chairs... just be online in case we need you!:slightly_smiling_face:

**Friederike Dündar** (08:26:31):
> is there any other way to join a session but via the backstage button?

**Federico Marini** (08:26:49):
> I think to join the backstage you should be*listed *as host/speaker

**Federico Marini** (08:27:04):
> the session is “auto-joined”

**Federico Marini** (08:27:18):
> at least, the plenaries just teleport you into that

**Kevin Rue-Albrecht** (08:27:29):
> i didn't autojoin the backstage, which is why i was a bit late

**Charlotte Soneson** (08:28:00):
> You also don’t autojoin the non-backstage (since this is the premium version which allows parallel sessions). You have to click to join a session, in the list of sessions

**Katharina Imkeller** (08:28:42):
> How can I make speaker come backstage while the session is running (in case someone is late)?

**Kevin Rue-Albrecht** (08:31:17):
> I think they'll just have to click the 'go basckstage' button

**Kevin Rue-Albrecht** (08:31:43):
> by default my video and audio are off whenever I join a session, so they should be able to enter discreetly

**Michael Love** (11:01:48):
> i left my video on as a friendly face for Sehyun (i've been doing this when i host/chair other zoom talks this year) but i don't know if for consistency across sessions maybe i will turn off video next time

**Davide Risso** (11:17:30):
> Are we doing all questions at the end or right after each talk for short talk sessions?

**Katharina Imkeller** (11:19:30) (in thread):
> After every single talk? What do you think?

**Davide Risso** (11:20:00) (in thread):
> Not sure... let's see how it works this time and we can re-adjust for the next session

**Katharina Imkeller** (11:20:32) (in thread):
> how long did you ask the speakers to present?

**Davide Risso** (11:20:47) (in thread):
> 8 minutes for short talks, 20 minutes for long talks

**Katharina Imkeller** (11:43:26):
> do I have to start the session to allow others to come backstage?

**Kevin Rue-Albrecht** (11:44:39) (in thread):
> with Charlotte we're doing questions at the end of each talk, keeping an eye on the time

**Kevin Rue-Albrecht** (11:45:02) (in thread):
> I think it's easier to check 10min per short talk than 8 per talk followed by again 2min for questions per talk

**Davide Risso** (11:45:06) (in thread):
> it's going well with this format

**Katharina Imkeller** (11:45:22) (in thread):
> ok, we'll do the same

**Davide Risso** (11:46:02):
> no, all the speakers will be able to go to the backstage independently

**Davide Risso** (11:46:22):
> but you will be the only one with the button "Start session"

**Federico Marini** (11:51:45):
> When can we share a link to our slides? Anytime?

**Katharina Imkeller** (11:52:25):
> anytime, but only when session is live

**Federico Marini** (11:52:54):
> Perfect, I’ll probably pre-type in the chat and click on enter when starting to speak:wink:

**Katharina Imkeller** (11:53:26):
> you can also send me the link and I post it while you speak. as you wish

**Friederike Dündar** (12:01:07):
> how do you all manage to have your photos shown? When I sign in, my photo is there, but as soon as I go to the EuroBioC airmeet, it's gone

**Gabriele Sales** (12:05:56):
> If you want to change your photo, you have to open your profile; click on edit; and finally upload your picture.
  - File (PNG): [Schermata 2020-12-14 alle 18.04.46.png](https://community-bioc.slack.com/files/U34P8RS3B/F01H85W002V/schermata_2020-12-14_alle_18.04.46.png)
  - File (PNG): [Schermata 2020-12-14 alle 18.04.51.png](https://community-bioc.slack.com/files/U34P8RS3B/F01HKC4K0PJ/schermata_2020-12-14_alle_18.04.51.png)
  - File (PNG): [Schermata 2020-12-14 alle 18.04.54.png](https://community-bioc.slack.com/files/U34P8RS3B/F01GNQPSSDU/schermata_2020-12-14_alle_18.04.54.png)

**Davide Risso** (12:10:03):
> I think that if you log out and log in again it may be there?

**Davide Risso** (12:10:35):
> but Johannes has been having the same issue and Airmeet support was not very helpful:slightly_smiling_face:

**Kevin Rue-Albrecht** (12:11:13):
> I remember that when I added my own picture, it didn't show until the next time I signed back in

**Friederike Dündar** (12:16:19):
> mh, I've signed in many, many times, but I'll hope for tomorrow:slightly_smiling_face:

**Gabriele Sales** (12:23:38):
> I’m going to write an email to Airmeet tech support over this. Would you mind sharing with me the email address you used for logging in?

**Mike Smith** (12:50:32):
> I have the same issue with the profile picture.  It's in my profile, but not seen anywhere else

**Gabriele Sales** (12:52:41):
> Hi@Mike Smith, I’ve just asked a fix for this to Airmeet. Will let you know if anything comes up.

**Davide Risso** (13:44:00):
> Ok,@Katharina Imkellerand I have figured that if the host goes to the "People" tab and add a person as a speaker to the session you can add as many as you want

**Davide Risso** (13:44:18):
> While if you use the raise hand feature you can only add one person at the time on stage

**Davide Risso** (13:44:30):
> this seems important for BOFs and workshops

**Katharina Imkeller** (13:46:03):
> Yes! Do not try to invite a second person with the raise hand function, because this kicks out the first invited person.

**Kevin Rue-Albrecht** (14:43:42) (in thread):
> as many speakers as you want? I thought there was an upper limit of 10 speakers per session?

**Davide Risso** (14:51:34) (in thread):
> It’s 16 I think...  although >10 is “not recommended “

**Davide Risso** (14:51:48) (in thread):
> But what I meant was >1:grimacing:

**Kevin Rue-Albrecht** (14:52:32) (in thread):
> haha good to know though, we had 30 participants in the github action BoF, with 5-6 interacting through Q&A and mic

**Kevin Rue-Albrecht** (14:53:01) (in thread):
> so 16 would probably cover a lot of BoF needs

**Friederike Dündar** (15:30:12):
> Is there a job posting section at the conference?

**Laurent Gatto** (16:25:08) (in thread):
> no, but there's a#jobschannel on slack


## 2020-12-15

**Levi Waldron** (08:15:24) (in thread):
> Same issue, I've uploaded a photo to my profile but it doesn't show ([levi.waldron@sph.cuny.edu](mailto:levi.waldron@sph.cuny.edu))

**Gabriele Sales** (08:23:03) (in thread):
> Just got in touch again with Airmeet. Apparently their support team lost my emails from yesterday…:open_mouth:

**Mike Smith** (10:26:16):
> In the Quantitative ChiP-seq workshop, none of us are assigned as a chair

**Kevin Rue-Albrecht** (10:28:11) (in thread):
> oh yeah the Host seems to be the 'EuroBioc2020' account

**Kevin Rue-Albrecht** (10:28:37) (in thread):
> let's see if we can change that:confused:

**Kevin Rue-Albrecht** (10:29:13) (in thread):
> looks like its done

**Davide Risso** (10:47:59) (in thread):
> yes, sorry I did it without checking slack

**Davide Risso** (12:19:31):
> <!here>I'm not sure what are your plans for the next hour or so but the poster hall is quite empty at the moment and it would be nice if you can check out the posters and interact with the presenters!

**Simone Bell** (13:05:43):
> I visited some posters now and I liked the setup very much. Authors say they also love it!

**Federico Marini** (13:49:57):
> It is super nice, lots of people did an excellent job in populating the booths

**Federico Marini** (13:50:03):
> perfect choice, got to say

**Laurent Gatto** (14:11:42):
> [https://twitter.com/lgatt0/status/1338921061409300491](https://twitter.com/lgatt0/status/1338921061409300491)
  - Attachment (twitter): [Attachment](https://twitter.com/lgatt0/status/1338921061409300491)
> I really enjoyed the #EuroBioc2020 poster session! [https://twitter.com/drisso1893/status/1338894478325800960](https://twitter.com/drisso1893/status/1338894478325800960)
  - Attachment (twitter): [Attachment](https://twitter.com/drisso1893/status/1338894478325800960)
> Join us in 5 minutes in the Arena for the #EuroBioc2020 poster session! Posters looking good! [https://pbs.twimg.com/media/EpS1X4PXYAElRjp.jpg](https://pbs.twimg.com/media/EpS1X4PXYAElRjp.jpg)

**Levi Waldron** (14:18:45):
> Only unfortunate thing is how few people attended the poster session, I wonder if it was not knowing or just less interest?

**Davide Risso** (14:21:07):
> In hindsight we should probably have scheduled it earlier in the afternoon

**Davide Risso** (14:21:28):
> i think people that wanted to follow both workshops needed a break in between

**Levi Waldron** (14:25:46):
> There were probably a lot more people who browsed and watched the videos without entering a table, too

**Michael Love** (14:45:16):
> I just had too many last-minute before-holidays meetings crammed in:disappointed:Sorry to have missed the session. Luckily can browse posters after the fact

**Laurent Gatto** (14:57:23):
> The end if the day was indeed quite hard, with the workshops and poster sessions. But I particularly enjoyed the poster session and workshops, despite a dodgy connection.


## 2020-12-16

**Simone Bell** (02:56:25):
> Morning all! We're missing a co-chair today at 17:30h. Any volunteers? Thanks.

**Levi Waldron** (03:27:11):
> I can do 17:30h

**Davide Risso** (05:12:15) (in thread):
> Great! I added you to the schedule!

**Levi Waldron** (11:19:53):
> As a session chair (Workshop: preciseTAD), should I see anything differently than I have before? I see that I am “organizer” and nothing seems different than other backstages I’ve been in…

**Charlotte Soneson** (11:21:15):
> It should say “Host” instead of “Organizer”

**Charlotte Soneson** (11:21:24):
> This may be linked to the two different accounts you have

**Charlotte Soneson** (11:22:00):
> Like yesterday - I assigned you as a speaker to Marcel’s workshop, but you were still an ‘Organizer’ and were thrown out once it started

**Levi Waldron** (11:22:15):
> OK Simone is here, she’s Host


## 2020-12-18

**Koen Van den Berge** (10:01:01):
> One of the speaakers in the upcoming session is backstage in the session but doesn’t seem to appear on the stage.

**Koen Van den Berge** (10:01:12):
> Oliver Crook

**Britta Velten** (10:02:03):
> problem solved, just appeared


## 2020-12-22

**Kozo Nishida** (00:24:46):
> @Kozo Nishida has joined the channel

**Mike Smith** (07:04:38):
> @Mike Smith has left the channel


## 2021-03-11

**Chris Vanderaa** (09:32:44):
> @Chris Vanderaa has left the channel


## 2021-04-28

**Michael Love** (12:25:56):
> @Michael Love has left the channel


## 2021-05-11

**Megha Lal** (16:44:55):
> @Megha Lal has joined the channel


## 2022-01-28

**Megha Lal** (11:12:35):
> @Megha Lal has left the channel


## 2022-07-27

**Levi Waldron** (12:29:29):
> archived the channel
