---
title: "#eurobioc2019"
---

## 2019-12-08

**Levi Waldron** (12:52:50):
> @Levi Waldron has joined the channel

**Levi Waldron** (12:52:52):
> set the channel description: EuroBioC2019 attendees

**Davide Risso** (12:55:07):
> @Davide Risso has joined the channel

**Martin Morgan** (12:55:08):
> @Martin Morgan has joined the channel

**Vince Carey** (12:55:08):
> @Vince Carey has joined the channel

**lievenClement** (12:55:08):
> @lievenClement has joined the channel

**lievenClement** (12:55:08):
> @lievenClement has joined the channel

**Laurent Gatto** (12:55:08):
> @Laurent Gatto has joined the channel

**Levi Waldron** (12:56:15):
> <!channel>,@Davide Rissoand I are meeting in the hotel lobby in 5 minutes to go find dinner…

**Charlotte Soneson** (17:26:55):
> @Charlotte Soneson has joined the channel


## 2019-12-09

**Federico Marini** (04:12:32):
> @Federico Marini has joined the channel

**Mireia Ramos-Rodríguez** (04:28:34):
> @Mireia Ramos-Rodríguez has joined the channel

**Olly Crook** (04:31:21):
> @Olly Crook has joined the channel

**Kevin Rue-Albrecht** (04:38:53):
> @Kevin Rue-Albrecht has joined the channel

**Robert Castelo** (11:57:18):
> @Robert Castelo has joined the channel

**Davide Risso** (15:33:56):
> @Laurent GattoLevi and I are lost... where is the bar that you mentioned?


## 2019-12-10

**Johannes Rainer** (10:49:58):
> @Johannes Rainer has joined the channel

**Nathalie Pochet** (10:57:20):
> @Nathalie Pochet has joined the channel

**Chong Tang** (10:58:46):
> @Chong Tang has joined the channel

**Katharina Hembach** (11:16:20):
> @Katharina Hembach has joined the channel

**Sebastian Gibb** (12:06:30):
> @Sebastian Gibb has joined the channel

**Almut** (12:15:47):
> @Almut has joined the channel

**Stephany Orjuela** (12:16:17):
> @Stephany Orjuela has joined the channel

**Robert Castelo** (13:38:07):
> Hi, three of us are at the lobby of Tangla to go for dinner. Anyone else is coming? Wasn't the appointment at 19:30?

**Tobias Kockmann** (16:22:29):
> @Tobias Kockmann has joined the channel


## 2019-12-11

**Kevin Rue-Albrecht** (04:14:09):
> … user/developers sessions in progress …
  - File (GIF): [Bioconductor.gif](https://community-bioc.slack.com/files/U34P8RS3B/FRJM8H069/bioconductor.gif)

**Jeroen Gilis** (04:20:36):
> @Jeroen Gilis has joined the channel

**Dario Righelli** (04:20:40):
> @Dario Righelli has joined the channel

**Mike Smith** (04:21:02):
> @Mike Smith has joined the channel

**Nathalie Pochet** (04:27:29):
> Can anyone tell me which rooms the sessions are? Thanks!

**Dario Righelli** (04:29:12):
> ***Experiment Hub***ToDo (sortof)
> * GTEx data  new package subgroup
> * Elisabetta’s data  scRNAseq subgroup
> * sideSeq to pmbc data package subgroup
> * patch for experiment hub subgroup
> * improve documentation
> * write functions for simplifying data creation/loading

**Dario Righelli** (04:29:43) (in thread):
> I’m sorry but I really don’t know where we are!:slightly_smiling_face:@Laurent Gatto

**Dario Righelli** (04:32:41) (in thread):
> If you come in front of the building where we where at the beginning someone will come for you

**Nathalie Pochet** (04:33:08) (in thread):
> I’m there now!

**Chong Tang** (04:34:40) (in thread):
> I'm here

**Nathalie Pochet** (04:34:58) (in thread):
> inside? outside?

**Chong Tang** (04:35:17) (in thread):
> Outside. Where we had presentations yesterday

**Nathalie Pochet** (04:35:54) (in thread):
> i’m outside downstairs

**Dania Machlab** (05:01:47):
> @Dania Machlab has joined the channel

**Chong Tang** (05:36:01):
> [https://renkulab.io](https://renkulab.io)

**Milan Malfait** (05:38:05):
> @Milan Malfait has joined the channel

**Elisabetta Mereu** (06:09:13):
> @Elisabetta Mereu has joined the channel

**Laurent Gatto** (08:52:45):
> Let's all reconvene in the pharmacy museau at 3.30pm for a final wrap-up. Rooms will still be available for those that want more.

**Christine Choirat** (12:08:52):
> @Christine Choirat has joined the channel

**Levi Waldron** (12:50:53):
> I'll get dinner in the Tanglia hotel in a bit, if anyone still here would like to join

**Dario Righelli** (13:35:28):
> I'm in the city center, I don't think I can join you! Have a good dinner:blush:


## 2020-03-09

**Levi Waldron** (19:13:43):
> archived the channel
