---
title: "#eurobioc-conference-everyone"
---

## 2023-09-12

**Simone Bell** (11:27:30):
> @Simone Bell has joined the channel


## 2023-09-14

**Simone Bell** (10:40:40):
> set the channel topic: EuroBioC2023 conference. This channel is for all participants, speakers and organisers.

**Simone Bell** (10:40:51):
> set the channel topic: EuroBioC2023 conference.

**Simone Bell** (10:40:56):
> set the channel description: This channel is for all participants, speakers and organisers.

**Charlotte Soneson** (11:36:17):
> @Charlotte Soneson has joined the channel

**Simone Bell** (11:37:27):
> this was easy. So, you just need to be on Slack.

**Simone Bell** (11:39:10):
> I will add all emails addresses to the channel and see who can join or not … and send an email to people letting them officially know and that’s it.

**Nils Eling** (11:43:11):
> @Nils Eling has joined the channel

**Brian Schilder** (11:44:02):
> @Brian Schilder has joined the channel

**Johannes Rainer** (11:50:50):
> @Johannes Rainer has joined the channel

**Jeroen Gilis** (11:50:50):
> @Jeroen Gilis has joined the channel

**SILVIA GIULIA GALFRE'** (11:50:50):
> @SILVIA GIULIA GALFRE' has joined the channel

**Nina Demeulemeester** (11:50:51):
> @Nina Demeulemeester has joined the channel

**Benjamin Haibe-Kains** (11:50:51):
> @Benjamin Haibe-Kains has joined the channel

**Rachel Queen** (11:50:51):
> @Rachel Queen has joined the channel

**Vandenbulcke Stijn** (11:50:51):
> @Vandenbulcke Stijn has joined the channel

**Robert Ivánek** (11:50:51):
> @Robert Ivánek has joined the channel

**Axelle Loriot** (11:50:51):
> @Axelle Loriot has joined the channel

**Ahmad Al Ajami** (11:50:51):
> @Ahmad Al Ajami has joined the channel

**lievenClement** (11:50:51):
> @lievenClement has joined the channel

**Federico Marini** (11:50:51):
> @Federico Marini has joined the channel

**Florian Geier** (11:50:51):
> @Florian Geier has joined the channel

**Annekathrin Ludt** (11:50:51):
> @Annekathrin Ludt has joined the channel

**Constantin Ahlmann-Eltze** (11:50:51):
> @Constantin Ahlmann-Eltze has joined the channel

**Hosna Baniadam** (11:50:52):
> @Hosna Baniadam has joined the channel

**Mike Smith** (11:50:52):
> @Mike Smith has joined the channel

**Janick** (11:50:52):
> @Janick has joined the channel

**Givanna Putri** (11:50:52):
> @Givanna Putri has joined the channel

**Lasse Myr** (11:50:52):
> @Lasse Myr has joined the channel

**Monica Valecha** (11:50:52):
> @Monica Valecha has joined the channel

**Maria Doyle** (11:50:52):
> @Maria Doyle has joined the channel

**Michael Stadler** (11:50:52):
> @Michael Stadler has joined the channel

**Michael Lynch** (11:50:52):
> @Michael Lynch has joined the channel

**Brian Schilder** (11:50:52):
> @Brian Schilder has joined the channel

**Aedin Culhane** (11:50:53):
> @Aedin Culhane has joined the channel

**Ahmad Alkhan** (11:50:53):
> @Ahmad Alkhan has joined the channel

**Jacques SERIZAY** (11:50:53):
> @Jacques SERIZAY has joined the channel

**Ivo Kwee** (11:50:53):
> @Ivo Kwee has joined the channel

**Anna Powell** (11:53:31):
> @Anna Powell has joined the channel

**Ilaria Billato** (11:56:32):
> @Ilaria Billato has joined the channel

**Daniela Corbetta** (12:00:39):
> @Daniela Corbetta has joined the channel

**Valentyna_Tararina** (12:01:16):
> @Valentyna_Tararina has joined the channel

**Stefania Pirrotta** (12:01:22):
> @Stefania Pirrotta has joined the channel

**Mariia** (12:02:32):
> @Mariia has joined the channel

**Anna** (12:03:42):
> @Anna has joined the channel

**Helena Crowell** (12:07:29):
> @Helena Crowell has joined the channel

**Marcel Ramos Pérez** (12:09:18):
> @Marcel Ramos Pérez has joined the channel

**Fabricio Almeida-Silva** (12:32:38):
> @Fabricio Almeida-Silva has joined the channel

**Yile** (12:44:09):
> @Yile has joined the channel

**Alexander Botzki** (12:58:44):
> @Alexander Botzki has joined the channel

**Davide Risso** (13:00:56):
> @Davide Risso has joined the channel

**Matthias Meyer-Bender** (14:07:15):
> @Matthias Meyer-Bender has joined the channel

**David Novak** (14:18:36):
> @David Novak has joined the channel

**Bárbara Zita Peters Couto** (16:02:18):
> @Bárbara Zita Peters Couto has joined the channel


## 2023-09-15

**Kerry** (01:36:06):
> @Kerry has joined the channel

**Almut** (02:36:39):
> @Almut has joined the channel

**Chris Vanderaa** (02:44:17):
> @Chris Vanderaa has joined the channel

**Marco Geigges** (02:51:45):
> @Marco Geigges has joined the channel

**Pablo** (02:58:18):
> @Pablo has joined the channel

**Dania Machlab** (03:27:45):
> @Dania Machlab has joined the channel

**Maryna Chepeleva** (03:36:26):
> @Maryna Chepeleva has joined the channel

**Dario Righelli** (03:57:16):
> @Dario Righelli has joined the channel

**Fiona Ross** (04:00:56):
> @Fiona Ross has joined the channel

**Philippe** (04:03:07):
> @Philippe has joined the channel

**Benjamin Rombaut** (04:05:42):
> @Benjamin Rombaut has joined the channel

**Celine Everaert** (04:10:08):
> @Celine Everaert has joined the channel

**Philippine Louail** (04:15:06):
> @Philippine Louail has joined the channel

**Lydia King** (04:15:41):
> @Lydia King has joined the channel

**Kerry** (04:16:41):
> Hi, If we have a poster pitch, do we also need to print it?

**Taras Lukashiv** (04:19:46):
> @Taras Lukashiv has joined the channel

**Andrea Vicini** (04:21:16):
> @Andrea Vicini has joined the channel

**Charlotte Soneson** (04:32:43) (in thread):
> The poster should still be printed - everyone will have the opportunity to make a poster pitch (1 slide, 1 minute) to advertise their poster.

**Alexandre Segers** (04:36:26):
> @Alexandre Segers has joined the channel

**Leo Lahti** (04:40:50):
> @Leo Lahti has joined the channel

**Kerry** (04:43:36) (in thread):
> Thanks for the clarification

**Cyril de Bodt** (06:47:41):
> @Cyril de Bodt has joined the channel

**Kerry** (07:10:58):
> Is the poster okay in portrait or landscape?

**Charlotte Soneson** (08:34:58) (in thread):
> Poster format is A0, portrait

**Kerry** (08:35:06) (in thread):
> Thanks!

**Wassim Gabriel** (09:13:44):
> @Wassim Gabriel has joined the channel

**Angelo Velle** (09:41:13):
> @Angelo Velle has joined the channel

**Louise Deconinck** (09:47:25):
> @Louise Deconinck has joined the channel

**Laurent** (10:03:27):
> @Laurent has joined the channel

**Laurent Gatto** (10:43:54):
> @Laurent Gatto has joined the channel


## 2023-09-16

**Tuomas Borman** (03:47:38):
> @Tuomas Borman has joined the channel

**Charlotte Soneson** (08:06:18):
> :wave:A few notes ahead of EuroBioC:
> 
> To all***poster presenters***: as mentioned, you are encouraged to present a (1 slide, 1 minute) poster pitch, just before your assigned poster session (see the[schedule](https://eurobioc2023.bioconductor.org/schedule/)). Please add your slide to the google slide deck (the link is in the email you received on September 6). If you don't want to do a poster pitch, please let us know/remove your slide from the deck.
> 
> To all***short talk presenters***: please upload your slides to the google drive folder (the link is in the email you received on September 6)***latest in the afternoon the day before your talk***- we need to have the time to move the slides to the room computer. Include your first and last name in the file name.
> 
> To all participants: most of the package demos have been added to our cloud workshop platform at[https://workshop.bioconductor.org/](https://workshop.bioconductor.org/). This means that for these demos, you can follow along in any live coding, without having to install or set up anything on your own computer. If you would like to do this, please create an account on the platform - once logged in you will find a tutorial video, and links to the included demos under the 'EUROBIOC2023' header in the left side bar.
> 
> The talk sessions will be live-streamed during the conference, the links will be available from the conference website. Demo sessions will be recorded and made available after the conference.
> 
> Before the conference starts, take a moment to look through the[Code of Conduct](https://eurobioc2023.bioconductor.org/code/). We're looking forward to seeing everyone next week in Ghent!

**Givanna Putri** (10:52:50) (in thread):
> ahh i’ve printed my poster in landscape. I hope this is ok. Apologies!


## 2023-09-17

**Hyeongseok Lim** (11:09:49):
> @Hyeongseok Lim has joined the channel


## 2023-09-18

**Ajda Pristavec** (02:35:58):
> @Ajda Pristavec has joined the channel

**Julie Devis** (04:01:55):
> @Julie Devis has joined the channel

**Ruth Seurinck** (05:29:13):
> @Ruth Seurinck has joined the channel

**Samuel Grégoire** (06:32:58):
> @Samuel Grégoire has joined the channel

**Sebastian Lobentanzer** (09:12:38):
> @Sebastian Lobentanzer has joined the channel

**Sebastian Lobentanzer** (09:23:12):
> @Sebastian Lobentanzer has joined the channel

**Kerry** (09:25:46):
> Do we have a poster number?

**Charlotte Soneson** (09:30:41) (in thread):
> No, no poster numbers. You are assigned to a session (see the schedule) where you should be at your poster.

**Maryna Chepeleva** (09:42:03) (in thread):
> @Charlotte Sonesonshould we hang on poster on the first day or only on the day of our session?

**Charlotte Soneson** (09:43:12) (in thread):
> I think it should be possible to keep the posters up for the whole conference.

**Maryna Chepeleva** (09:48:34) (in thread):
> ok, thank you!

**Daria Fijalkowska** (13:43:42):
> @Daria Fijalkowska has joined the channel

**Anna** (16:43:06):
> the workshops tomorrow start at 9, right?

**Maria Doyle** (17:07:15):
> Yes:thumbsup:

**Aedin Culhane** (17:08:32):
> @Maria.. please check your DM


## 2023-09-19

**Katharina Imkeller** (04:05:49):
> @Katharina Imkeller has joined the channel

**louisc** (04:36:03):
> @louisc has joined the channel

**Thomas Naake** (07:33:03):
> @Thomas Naake has joined the channel

**Thomas Naake** (07:36:55):
> @Thomas Naake has joined the channel

**Simone Bell** (09:15:19):
> Hi all, there are no sockets in the auditorium,where the plenary sessions take place. It might be a good idea to charge your laptops over night.

**Biancamaria Florenzi** (12:24:46):
> @Biancamaria Florenzi has joined the channel

**Jeroen Gilis** (12:35:01) (in thread):
> I can confirm this! You can set up the posters the first morning or in the conference breaks; we'll be around to help with that.

**Jeroen Gilis** (12:36:35) (in thread):
> @Givanna Putrithe poster boards are in portrait, but in theory it should be possible to reassemble them to landscape. I will have a look at it tomorrow morning.

**Richard Heery** (12:52:21):
> @Richard Heery has joined the channel

**Francesco Dossena** (14:46:41):
> @Francesco Dossena has joined the channel

**Simone Bell** (15:10:42):
> Dear short talk presenters: Please upload your slides to this[google folder](https://drive.google.com/drive/folders/1HGKQZrfTzXU0uS4o5qwICKlNthdHUeAG?usp=drive_link)and add your first and last name to the file name before midnight. We will display the slides from the room computer and you cannot present with your own laptop. Thank you!

**Roberto Albanese** (18:19:59):
> @Roberto Albanese has joined the channel


## 2023-09-20

**Laure Cougnaud** (03:20:19):
> @Laure Cougnaud has joined the channel

**Charlotte Soneson** (03:21:48):
> Form to sign up for a flashtalk (approximately 5 minutes) - first come, first served:[https://forms.gle/YscQzQFDCZAWYtFGA](https://forms.gle/YscQzQFDCZAWYtFGA)
  - Attachment (Google Docs): [EuroBioC2023 flashlight talk submission](https://forms.gle/YscQzQFDCZAWYtFGA)

**Franka Voigt** (03:31:11):
> @Franka Voigt has joined the channel

**Maria Doyle** (04:25:16):
> :loudspeaker:ICYMI:***EuroBioC2023 Social Media Challenge***!
> Remember the Social Media Challenge from the opening?:point_right:Get the full info:[https://genomic.social/@bioconductor/111091945998178236](https://genomic.social/@bioconductor/111091945998178236)Be part of the excitement!:boom:
  - Attachment (genomic.social): [Bioconductor (@bioconductor@genomic.social)](https://genomic.social/@bioconductor/111091945998178236)
> Attached: 1 image
> 
> ***EuroBioC2023 Social Media Competition***
> 
> Are you attending the EuroBioC2023 conference!? Then you should take part in our social media competition. 
> 
> Follow the steps below to be in with the chance to win an awesome prize at #EuroBioC2023!!

**Petr Smirnov** (05:41:26):
> @Petr Smirnov has joined the channel

**Erin** (06:02:43):
> @Erin has joined the channel

**Dario Righelli** (07:55:58):
> Sorry to ask, which is the link to the workshop platform?

**Charlotte Soneson** (07:56:31) (in thread):
> [https://workshop.bioconductor.org/](https://workshop.bioconductor.org/)

**Dario Righelli** (07:56:52) (in thread):
> thanks!

**Adrienne Unsworth** (08:07:43):
> @Adrienne Unsworth has joined the channel

**Mauro Masiero** (09:44:22):
> @Mauro Masiero has joined the channel

**Aakanksha Singh** (10:46:00):
> @Aakanksha Singh has joined the channel

**Giulio Benedetti** (10:47:04):
> @Giulio Benedetti has joined the channel

**Aedin Culhane** (11:47:35):
  - File (JPEG): [IMG_9905](https://community-bioc.slack.com/files/U34P8RS3B/F05TVEQ6CE4/img_9905.jpg)


## 2023-09-21

**Ahmad Al Ajami** (05:29:39):
> @Brian Schilder
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F05TD7R1WLU/image.png)

**Teresa** (10:31:01):
> @Teresa has joined the channel

**Koen Van den Berge** (10:40:35):
> @Koen Van den Berge has joined the channel

**Ahmad Alkhan** (12:49:44):
> @Alexander Botzki
  - File (JPEG): [IMG_0356](https://community-bioc.slack.com/files/U34P8RS3B/F05U29NRJE4/img_0356.jpg)


## 2023-09-22

**SILVIA GIULIA GALFRE'** (02:50:44):
  - File (JPEG): [IMG_20230922_084645.jpg](https://community-bioc.slack.com/files/U34P8RS3B/F05U5AUJXJL/img_20230922_084645.jpg)

**Simone Bell** (02:59:55):
> Please return your badge before you leave, so that we can use it again. Thanks very much!

**Donnacha Fitzgerald** (04:09:22):
> @Donnacha Fitzgerald has joined the channel

**Tümay** (04:09:46):
> @Tümay has joined the channel

**SILVIA GIULIA GALFRE'** (04:53:26):
  - File (JPEG): [IMG_20230922_105059.jpg](https://community-bioc.slack.com/files/U34P8RS3B/F05T2BQQ7LP/img_20230922_105059.jpg)

**Kerry** (05:26:38):
  - File (High Efficiency Image File): [IMG_3202.HEIC](https://community-bioc.slack.com/files/U34P8RS3B/F05T2G3BXGF/img_3202.heic)

**Donnacha Fitzgerald** (05:32:30):
> Last night we interviewed some historical figures about Bioconductor. Here’s what they had to say:[https://chat.openai.com/share/3911ad51-7e3d-4ed7-a299-38caa1a64500](https://chat.openai.com/share/3911ad51-7e3d-4ed7-a299-38caa1a64500)Inspiration for pitching Bioconductor to newcomers!:bulb:
  - Attachment (chat.openai.com): [ChatGPT](https://chat.openai.com/share/3911ad51-7e3d-4ed7-a299-38caa1a64500)

**Donnacha Fitzgerald** (05:39:14) (in thread):
> Credits to@Tümay,@Thomas Naake,@Matthias Meyer-Benderand others for suggesting interviewees!

**Sebastian Lobentanzer** (05:44:20) (in thread):
> Douglas Adams:
> ```
> Bioconductor, much like a baffling and enigmatic extraterrestrial phenomenon, is a wondrous creation of the scientific cosmos. It's as if the universe itself decided to play a grand cosmic joke on us mere mortals, gifting us with a repository of tools and resources for the analysis and exploration of biological data. It's like discovering a towel in the vast expanse of space, only to find that this towel is actually a toolkit for deciphering the secrets of life itself.
> 
> In the whimsical world of Douglas Adams, where improbable things happen with alarming regularity, Bioconductor would be a sentient, hyper-intelligent being that navigates the labyrinthine corridors of genomics, statistics, and computational biology with the ease of a hitchhiker thumbing a ride on a passing spaceship. It would be a digital babel fish, effortlessly translating the complex languages of DNA, RNA, and protein into comprehensible insights for scientists and researchers.
> 
> And just like the mysterious and absurd events in Adams' tales, Bioconductor invites us to embark on a journey through the bewildering universe of genomics, where the improbable becomes possible, and the ordinary becomes extraordinary. So, don't forget your towel, and don't panic—Bioconductor is here to guide you through the intricacies of the biological universe with a dose of humor and a touch of absurdity.
> ```

**Donnacha Fitzgerald** (06:01:36) (in thread):
> Wonderful - keep them coming!

**Charlotte Soneson** (06:03:38):
> Link to post-conference survey:[https://bit.ly/EuroBioc2023survey](https://bit.ly/EuroBioc2023survey). Please share your thoughts about the conference!
  - Attachment (Google Docs): [EuroBioC2023 - Post-conference survey](https://bit.ly/EuroBioc2023survey)
> Thank you for attending the European Bioconductor Conference 2023. The conference website is at [https://eurobioc2023.bioconductor.org](https://eurobioc2023.bioconductor.org). Files and videos will be available on the Bioconductor YouTube channel soon.


## 2023-09-23

**SILVIA GIULIA GALFRE'** (03:17:27) (in thread):
> Wonderful. I appreciate particularly the one like Napoleon:rolling_on_the_floor_laughing:

**Brian Schilder** (07:08:53) (in thread):
> hahaha, we're so gangsta@Ahmad Al Ajami


## 2023-09-26

**Simone Bell** (15:46:58):
> Please don’t forget to to fill the post-conference survey out and after that you can request a certificate of attendance by sending an email to info (at)[bioconductor.eu](http://bioconductor.eu). The certificates will be sent out in the second half of October. Thanks very much!


## 2023-10-09

**Aedin Culhane** (12:40:42):
> In case you missed it[https://elixir-europe.org/events/elixir-single-cell-omics-community-f2fhybrid-meeting-0](https://elixir-europe.org/events/elixir-single-cell-omics-community-f2fhybrid-meeting-0)
  - Attachment (ELIXIR): [ELIXIR Single Cell Omics Community F2F/hybrid meeting](https://elixir-europe.org/events/elixir-single-cell-omics-community-f2fhybrid-meeting-0)
> This year, we are combining the annual community gathering with the FAIR Data Management Workshop. The annual meeting is scheduled for October 18th and will be hosted at the EMBL-EBI Campus in

**Aedin Culhane** (12:43:39) (in thread):
> Love it especially the star wars “Born from the R language, Bioconductor is the ally we’ve been looking for. With over 1,900 interoperable packages, it can dissect any biological data, decode genomes, and more. It’s the Force of bioinformatics, made accessible to Rebels like us.”

**Kasper D. Hansen** (12:56:51):
> @Kasper D. Hansen has joined the channel

**Kasper D. Hansen** (13:00:30) (in thread):
> This is awesome

**Ludwig Geistlinger** (13:32:59):
> @Ludwig Geistlinger has joined the channel

**Peace Sandy** (14:39:12):
> @Peace Sandy has joined the channel

**Odigiri Great Alume** (15:17:11):
> @Odigiri Great Alume has joined the channel


## 2023-10-11

**Romane Libouban** (05:41:19):
> @Romane Libouban has joined the channel


## 2023-10-12

**Artur Sannikov** (09:40:07):
> @Artur Sannikov has joined the channel


## 2023-10-15

**Karthik Desingu** (23:49:29):
> @Karthik Desingu has joined the channel


## 2024-01-25

**Maria Doyle** (11:12:53):
> If you enjoyed last year’s conference and would like to win free registration for this year, see below.:star2:**EuroBioC2024 Sticker Contest Reminder**:star2:Hello everyone! Just a reminder about our sticker design contest for EuroBioC2024. It’s a great opportunity to showcase your creativity and potentially win a fantastic prize.:gift:Prize: Free registration for this year’s EuroBioC conference in Oxford, September 4-6th!:rocket:Deadline:***January 31st, 2024*******
> ****To submit your design, please visit:[https://forms.gle/ALx3UUAuqzcazGbeA](https://forms.gle/ALx3UUAuqzcazGbeA)Looking forward to seeing your amazing designs


## 2024-02-07

**Maria Doyle** (06:10:29):
> :mega:Abstract submission is open for #EuroBioC2024 conference in Oxford:flag-gb:Sep 4-6[https://eurobioc2024.bioconductor.org/](https://eurobioc2024.bioconductor.org/)!
> 
> Submit an abstract***by April 26***for
> * Short talk
> * Package demo
> * Poster
> * Contributed session
> :point_right:Submit here[https://openreview.net/group?id=bioconductor.org/EuroBioC/2024/Conference](https://openreview.net/group?id=bioconductor.org/EuroBioC/2024/Conference)
  - File (PNG): [EuroBioC2023 Abstracts open.png](https://community-bioc.slack.com/files/U34P8RS3B/F06HMCGQZM1/eurobioc2023_abstracts_open.png)


## 2024-02-09

**Kevin Rue-Albrecht** (08:34:15):
> @Kevin Rue-Albrecht has joined the channel

**Lena** (08:35:05):
> @Lena has joined the channel

**Maria Doyle** (09:36:04):
> set the channel topic: EuroBioC conference.


## 2024-02-21

**Florian Geier** (10:35:52):
> @Florian Geier has left the channel


## 2024-03-01

**Claire Rioualen** (09:20:15):
> @Claire Rioualen has joined the channel


## 2024-04-18

**Philipp Sergeev** (03:02:16):
> @Philipp Sergeev has joined the channel


## 2024-04-29

**Samuel Gunz** (09:35:03):
> @Samuel Gunz has joined the channel


## 2024-06-04

**Axel Klenk** (02:42:32):
> @Axel Klenk has joined the channel


## 2024-07-26

**Qiwen Octavia Huang** (19:48:35):
> @Qiwen Octavia Huang has joined the channel


## 2024-07-30

**Jacques SERIZAY** (06:57:24):
> Late to the party, can I register for virtual attendance to eurobioc2024? Or is it not hybrid? Thanks!

**Kevin Rue-Albrecht** (08:18:16) (in thread):
> Thanks for your message. It is not organised as a hybrid conference. We will do every effort to record as much as possible (for upload to the Bioconductor YouTube channel) and we will consider closer to the date whether live streaming on Youtube is workable without negatively affecting the in-person experience.

**Jacques SERIZAY** (08:19:28) (in thread):
> Got it, thanks! Next time then :)


## 2024-08-01

**Maria Doyle** (05:49:30):
> :rocket:***Join us for the EuroBioC2024 Carpentries Workshops!***:date:September 2-3, 2024:round_pushpin:Oxford, UK***Workshops:***
> 1. Intro to Genomic Data Analysis with R and Bioconductor (2 days)
> 2. Analysis & Interpretation of Bulk RNA-Seq Data using Bioconductor (2 days)
> 3. Intro to the Bioconductor Project (1 day on September 3rd)
> :mag:Who: Biologists, bioinformaticians, and developers. Check the application forms for prerequisites.:bulb:Why: Hands-on training, expert instructors, and fantastic networking opportunities:point_right:[Register here](https://eurobioc2024.bioconductor.org/registration/#carpentries-workshops)For more details, check out our posts on[Mastodon](https://genomic.social/@bioconductor/112767180909630454)and[LinkedIn](https://www.linkedin.com/feed/update/urn:li:share:7217099690029248512/).
> Please share with your networks!


## 2024-08-08

**Maria Doyle** (09:42:17):
> ️:zap:***EuroBioC2024 Flashtalks & Birds-of-a-Feather Sessions ***:bird:
> * Flashtalks: Submit a 5-min presentation! Check the[conference schedule](https://eurobioc2024.bioconductor.org/schedule/)for session date and time and[submit here](https://docs.google.com/forms/d/e/1FAIpQLScnfsQjOhe5_PMUYgPo_7GvTISMS5epLt4ShKtXhEWtks1dZw/viewform).
> 
> * Birds-of-a-Feather: Propose your interactive discussion sessions on GitHub by September 5.[See last year’s examples and more details here](https://eurobioc2024.bioconductor.org/submissions/).
> Join us in Oxford & share your ideas with theEuroBioC2024community!
> 
> Share on[Mastodon](https://genomic.social/@bioconductor/112926661960639056)and[LinkedIn](https://www.linkedin.com/posts/bioconductor_eurobioc2024-bioinformatics-rstats-activity-7227306440862945281-_wz4?utm_source=share&utm_medium=member_desktop).


## 2024-08-15

**Maria Doyle** (06:43:50):
> :sparkles:***EuroBioC Updates: Important Deadlines***:sparkles::alarm_clock:***Final Week to Register for EuroBioC 2024***Registration closes***Aug 21st***! Join us in Oxford for a week of bioinformatics, networking, and collaboration.[Register now](https://eurobioc2024.bioconductor.org/registration/):wrench:***Carpentries Workshops***Registration closes***Aug 23rd***. Enhance your skills with hands-on bioinformatics training.[Sign up](https://eurobioc2024.bioconductor.org/registration/):mega:***Host EuroBioC 2025***Applications open until***Aug 31st***! Bring EuroBioC to your city.[Apply here](https://docs.google.com/forms/d/e/1FAIpQLSeJ20Bkl7Fy-paaHo8x70Ll9_M1juwoGmZxulC7MRV7j-7j-Q/viewform)Feel free to share the[LinkedIn](https://www.linkedin.com/posts/bioconductor_eurobioc2024-bioconductor-bioconductorcommunity-activity-7229795764346994690-ByLh)or[Mastodon](https://genomic.social/@bioconductor/112965603239633267)post to help spread the word!

**Dominik Burri** (07:32:19):
> @Dominik Burri has joined the channel


## 2024-08-19

**Rema Gesaka** (09:41:13):
> @Rema Gesaka has joined the channel


## 2024-08-20

**Maria Doyle** (10:22:03):
> :hourglass_flowing_sand:**** Final Reminder: EuroBioC2024 in-person registration closes tomorrow!****Don’t miss out—[register here](https://eurobioc2024.bioconductor.org/registration/)
  - Attachment (eurobioc2024.bioconductor.org): [Registration](https://eurobioc2024.bioconductor.org/registration/)
> Registration


## 2024-08-21

**Ellis Patrick** (05:07:56):
> @Ellis Patrick has joined the channel


## 2024-08-27

**Lisa Breckels** (08:30:13):
> @Lisa Breckels has joined the channel


## 2024-09-04

**Aedin Culhane** (03:49:32):
> Location for euroBioc[https://maps.app.goo.gl/9mKfEjNv5wUraDYVA?g_st=ic](https://maps.app.goo.gl/9mKfEjNv5wUraDYVA?g_st=ic)
  - Attachment (google.com): [Department of Statistics · 5.0★(6) · Academic department](https://maps.app.goo.gl/9mKfEjNv5wUraDYVA?g_st=ic)
> 24-29 St Giles', Oxford OX1 3LB, United Kingdom

**Laura Symul** (04:18:43):
> @Laura Symul has joined the channel

**Maria Doyle** (04:41:59):
> FYI we are using a separate Slack for the EuroBioC2024 conference, so we can have more channels, DM me if registered for the conference and you need the link.

**rohitsatyam102** (06:06:57):
> @rohitsatyam102 has joined the channel


## 2024-09-05

**Aedin Culhane** (12:51:04):
> Tour[https://maps.app.goo.gl/3qZNiL61NL33uwq78](https://maps.app.goo.gl/3qZNiL61NL33uwq78)
  - Attachment (google.co.uk): [Oxford University Museum of Natural History to Covered Market](https://maps.app.goo.gl/3qZNiL61NL33uwq78)
> Find local businesses, view maps and get driving directions in Google Maps.


## 2024-09-07

**Maria Doyle** (06:16:23):
> :star2:***Save the date for EuroBioC2025***:star2::date:***Barcelona, September 17-19, 2025***Check out our posts on[LinkedIn](https://www.linkedin.com/posts/bioconductor_eurobioc2024-eurobioc2025-activity-7237888796564885505-hUW6)and[Mastodon](https://genomic.social/@bioconductor/113092011144543560)for more details and stay tuned for a recap of EuroBioC2024!
  - Attachment (linkedin.com): [Bioconductor on LinkedIn: #eurobioc2024 #eurobioc2025](https://www.linkedin.com/posts/bioconductor_eurobioc2024-eurobioc2025-activity-7237888796564885505-hUW6)
> :star2: Thank you to all our amazing sponsors, organisers, presenters, and attendees for making #EuroBioC2024 a success! Stay tuned for a recap blog post, and save…


## 2024-09-16

**Mike Morgan** (06:24:04):
> @Mike Morgan has joined the channel


## 2024-09-20

**Maria Doyle** (08:18:56):
> :writing_hand:New Bioconductor blog post on EuroBioC2024 conference recap. Check it out here:[https://blog.bioconductor.org/posts/2024-09-20-eurobioc2024-recap/](https://blog.bioconductor.org/posts/2024-09-20-eurobioc2024-recap/)
  - Attachment (Bioconductor community blog): [EuroBioC2024 conference recap – Bioconductor community blog](https://blog.bioconductor.org/posts/2024-09-20-eurobioc2024-recap/)
> Highlights from the 2024 Bioconductor European Conference in Oxford.

**Camille Guillermin** (09:29:49):
> @Camille Guillermin has joined the channel


## 2024-09-30

**Leo Lahti** (09:11:46):
> @Leo Lahti has joined the channel


## 2024-10-28

**Brian Schilder** (21:11:33):
> @Brian Schilder has left the channel


## 2024-11-21

**Tehniyat zahra** (05:08:12):
> @Tehniyat zahra has joined the channel


## 2025-02-20

**Maria Doyle** (04:22:24):
> :mega:**** EuroBioC2025: Abstract Submissions Open!****Join us in Barcelona, Spain:es:, Sep 17-19, 2025, for the European Bioconductor Conference! Submit your abstract for a short talk, workshop, or poster.:spiral_calendar_pad:***Abstract Deadline:***April 24, 2025:link:***Register/Submit***:[https://eurobioc2025.bioconductor.org/](https://eurobioc2025.bioconductor.org/)


## 2025-04-22

**Maria Doyle** (06:25:23):
> [https://community-bioc.slack.com/archives/C35G93GJH/p1745316430815909](https://community-bioc.slack.com/archives/C35G93GJH/p1745316430815909)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C35G93GJH/p1745316430815909)
> :hourglass_flowing_sand: Just a reminder — **EuroBioC2025 abstract submissions close on 24 April!**
> We’ll be in **Barcelona** :es: this September — a great opportunity to share your work and connect with others in the Bioconductor community.
> If you’re planning to submit (or encouraging someone else to), here’s the info:
>  :point_right: [https://eurobioc2025.bioconductor.org/pages/submissions.html](https://eurobioc2025.bioconductor.org/pages/submissions.html)
> We’ve shared the call on socials too — feel free to reshare if you’d like:
> •  [LinkedIn](https://www.linkedin.com/feed/update/urn:li:share:7320386024977702915/)
> •  <https://genomic.social/@bioconductor/114381028529404011|Mastodon>
> •  [Bluesky](https://bsky.app/profile/bioconductor.bsky.social/post/3lnfga2tcdb23)


## 2025-04-25

**Najla Abassi** (10:16:02):
> @Najla Abassi has joined the channel
