---
title: "#FC:F05URJ0P021:Welcome material"
format: gfm
---

## 2023-10-02

**USLACKBOT** (18:00:17):
> ***WaldronLab***has joined this channel by invitation from***community-bioc***.


## 2023-11-01

**Joan C. Chukwuemeka** (12:13:26):
> [https://www.ebi.ac.uk/efo/](https://www.ebi.ac.uk/efo/)
  - Attachment (ebi.ac.uk): [The Experimental Factor Ontology < EMBL-EBI](https://www.ebi.ac.uk/efo/)
> The Experimental Factor Ontology (EFO) provides a systematic description of many experimental variables available in EBI databases, and for projects such as the GWAS catalog. It combines parts of several biological ontologies, such as UBERON anatomy, ChEBI chemical compounds, and Cell Ontology. The scope of EFO is to support the annotation, analysis and visualization of data handled by many groups at the EBI and as the core ontology for Open Targets. We also add terms for external users when requested. If you are new to ontologies, there is a short introduction on the subject available and a blog post by James Malone on what ontologies are for.


## 2023-11-02

**USLACKBOT** (17:35:15):
> The goal is to pick the most accurate ontology for the condition. Sometimes, Since authors are not looking at the ontology, they actually don’t choose the most appropriate terminology for the condition they are studying sometimes


## 2025-02-14

**Svetlana Ugarcina Perovic** (15:44:10):
> [https://kunmiwrites.wordpress.com/2024/01/22/bugsigdb-101-a-beginners-guide-to-exploring-microbial-signatures/](https://kunmiwrites.wordpress.com/2024/01/22/bugsigdb-101-a-beginners-guide-to-exploring-microbial-signatures/)
  - Attachment (The everyday chronicles): [BugSigDB 101: A Beginner’s Guide to Exploring Microbial Signatures](https://kunmiwrites.wordpress.com/2024/01/22/bugsigdb-101-a-beginners-guide-to-exploring-microbial-signatures/)
> Image of the BugSigDB Homepage ( Welcome back! It’s been an interesting couple of weeks as an Outreachy intern at Bioconductor. I’ve been working on the Microbiome Study Curation projec…

**Svetlana Ugarcina Perovic** (15:44:27):
> [https://kunmiwrites.wordpress.com/2024/01/22/bugsigdb-101-a-beginners-guide-to-exploring-microbial-signatures/](https://kunmiwrites.wordpress.com/2024/01/22/bugsigdb-101-a-beginners-guide-to-exploring-microbial-signatures/)
  - Attachment (The everyday chronicles): [BugSigDB 101: A Beginner’s Guide to Exploring Microbial Signatures](https://kunmiwrites.wordpress.com/2024/01/22/bugsigdb-101-a-beginners-guide-to-exploring-microbial-signatures/)
> Image of the BugSigDB Homepage ( Welcome back! It’s been an interesting couple of weeks as an Outreachy intern at Bioconductor. I’ve been working on the Microbiome Study Curation projec…


## 2025-02-20

**Svetlana Ugarcina Perovic** (07:31:48):
> [https://www.youtube.com/playlist?list=PLhy2nHJciTEB1jE6WpoeG7vkdmvAfM7mR](https://www.youtube.com/playlist?list=PLhy2nHJciTEB1jE6WpoeG7vkdmvAfM7mR)
  - Attachment (YouTube): [Microbiome & Health | MOOC on iMooX.at](https://www.youtube.com/playlist?list=PLhy2nHJciTEB1jE6WpoeG7vkdmvAfM7mR)
> Share your videos with friends, family, and the world


## 2025-02-27

**Svetlana Ugarcina Perovic** (09:18:51):
> [https://blog.bioconductor.org/#category=Outreachy](https://blog.bioconductor.org/#category=Outreachy)
  - Attachment (blog.bioconductor.org): [Bioconductor community blog](https://blog.bioconductor.org/#category=Outreachy)
> A blog for the Bioconductor community!


## 2025-03-18

**Svetlana Ugarcina Perovic** (17:27:04):
> [https://github.com/waldronlab/BugSigDBcuration/issues/94](https://github.com/waldronlab/BugSigDBcuration/issues/94)

**Svetlana Ugarcina Perovic** (17:27:19):
> [https://github.com/waldronlab/BugSigDBcuration/issues/94](https://github.com/waldronlab/BugSigDBcuration/issues/94)


## 2025-03-20

**Svetlana Ugarcina Perovic** (11:48:14):
> [https://bugsigdb.org/Curation_Policy](https://bugsigdb.org/Curation_Policy)
  - Attachment (BugSigDB): [Curation Policy](https://bugsigdb.org/Curation_Policy)
> .
