---
title: "#funding"
format: gfm
---


## 2022-09-16

*08:15:55 - @Leo Lahti has joined the channel*
**Leo Lahti** (08:15:55):
> set the channel description: Funding opportunities

*08:16:10 - @Aedin Culhane has joined the channel*
*08:16:10 - @Laurent Gatto has joined the channel*
*08:16:10 - @Wolfgang Huber has joined the channel*

## 2022-09-26

*17:39:29 - @Maria Doyle has joined the channel*
*17:39:29 - @Kevin Rue-Albrecht has joined the channel*
*17:39:29 - @Charlotte Soneson has joined the channel*

## 2022-12-15

*09:38:32 - @Mercilena Benjamin has joined the channel*

## 2023-01-18

*13:09:52 - @José Basílio has joined the channel*

## 2023-01-21

*16:02:22 - @Hien has joined the channel*
*16:18:50 - @Hien has left the channel*

## 2023-03-15

*01:45:50 - @Amarinder Singh Thind has joined the channel*

## 2023-05-17

*12:11:04 - @Hassan Kehinde Ajulo has joined the channel*

## 2023-06-19

*05:10:39 - @Pierre-Paul Axisa has joined the channel*

## 2023-08-28

*15:02:59 - @Sean Davis has joined the channel*
**Sean Davis** (15:03:07):
> [https://www.nsf.gov/pubs/2023/nsf23143/nsf23143.jsp](https://www.nsf.gov/pubs/2023/nsf23143/nsf23143.jsp)Funding opportunity jointly offered by UKRI and US NSF.
> Proposals should develop informatics approaches and cyberinfrastructure resources to enable novel and more effective use of data in biological research. Proposals should address important current or emerging challenges faced by researchers, supporting generation of new knowledge from biological data.
> Proposals should clearly identify their relevance to one of two biological informatics focus areas, either:
> 1. Research to design novel or greatly improved research tools and methods or
> 2. The implementation of, scaling of, or major improvements to research tools, products, and services for biology applicable to a wide range of researchers.
> Proposals can be in any bioinformatics research area within the scope of both the NSF Directorate for Biological Sciences and BBSRC. Proposals should clearly describe their potential to advance and enable data driven research undertaken by biological research communities primarily supported by both NSF/BIO and BBSRC.
> Proposals must be aligned to NSF's Division of Biological Infrastructure informatics (Innovation) OR cyberinfrastructure (Capacity) programs, but NOT both. Principal investigators are advised to consult the appropriate program officers of both agencies to ensure that their portion of the project is compliant with the targeted program.

*15:04:21 - @Alex Mahmoud has joined the channel*
*15:05:10 - @Abdullah Al Nahid has joined the channel*
*15:05:57 - @Chenyue Lu has joined the channel*
*15:09:07 - @chilam has joined the channel*
*15:18:21 - @Lambda Moses has joined the channel*
*15:23:00 - @Lluís Revilla has joined the channel*
*15:44:56 - @Andres Wokaty has joined the channel*
*15:56:01 - @Ritika Giri has joined the channel*
*16:19:17 - @Kasper D. Hansen has joined the channel*
*16:20:44 - @Frederick Tan has joined the channel*
*16:35:43 - @Ashwini Shanmugam has joined the channel*
*16:36:58 - @Janani Ravi has joined the channel*
*16:40:41 - @Marcel Ramos Pérez has joined the channel*
*18:30:29 - @Boyi Guo has joined the channel*
*19:11:29 - @Mikhail Dozmorov has joined the channel*
*20:57:01 - @Tyrone Chen has joined the channel*
*21:41:09 - @Mikaila Chetty has joined the channel*
*23:21:21 - @Himel Mallick has joined the channel*

## 2023-08-29

*01:53:07 - @Beth Cimini has joined the channel*
*02:27:05 - @Valentina Lorenzi has joined the channel*
*08:45:38 - @Mike Morgan has joined the channel*
**Kevin Rue-Albrecht** (09:56:24) (in thread):
> I'll enquire to my Uni's grant team about what it would take for me to get involved.
> 
> I'd be keen to try my luck at this to fund further iSEE-related development, under "**The implementation of, scaling of, or major improvements to research tools, products, and services for biology applicable to a wide range of researchers.**"
> 
> Since, it's about allowing "**U.S. and UK researchers to submit a single collaborative proposal that will undergo a single review process**", I'm happy to chat with whoever else would like to work on this together

*10:27:36 - @Jared Andrews has joined the channel*
*11:22:27 - @Stevie Pederson has joined the channel*
*12:28:03 - @Mariela has joined the channel*
*12:51:46 - @Shashank has joined the channel*
*17:09:07 - @stefano mangiola has joined the channel*
**stefano mangiola** (17:20:34) (in thread):
> @Michael Lovehow about tidyomics development?

*17:20:43 - @Michael Love has joined the channel*
**Michael Love** (18:13:33) (in thread):
> I don’t usually go for microbiome related proposal

**Michael Love** (18:13:59) (in thread):
> but I would like to aim to CZI for tidyomics, as they seem willing to support broad impact OSS for genomics

*19:32:37 - @Andrés Arredondo Cruz has joined the channel*
*19:33:46 - @Shila Ghazanfar has joined the channel*

## 2023-08-30

*03:47:28 - @Dario Righelli has joined the channel*
**Kevin Rue-Albrecht** (04:23:42) (in thread):
> @Michael Lovehold on, do I misunderstand?Does it have to be microbiolome related? I understand this is only one of 4 possible axes

**Kevin Rue-Albrecht** (04:43:19) (in thread):
> because tidyomics is clearly also "**research tools [....] applicable to a wide range of researchers**"

**Kevin Rue-Albrecht** (04:45:55) (in thread):
> In any case, I actually wondered whether that call would be perfect for BioC as a single application would definitely tick that box, while focus could be given to a set of packages maintained by co-applicants (eg, tidyomics, iSEE, …).
> Might sound a bit patchwork-y, but I could see some bridges, for instance iSEE could benefit of tidy functionality if DataFrame became ggplot2 friendly ([https://community-bioc.slack.com/archives/C6KJHH0M9/p1690235172607369](https://community-bioc.slack.com/archives/C6KJHH0M9/p1690235172607369)). Would save us a bit of data wrangling code in the shiny app…
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C6KJHH0M9/p1690235172607369)
    > I wanted to ask the following - someone on this channel may have thought about this already:
    > 
    > -> the missing support for DataFrame in ggplot2:
    > 
    > • *ggplot2* eats `data.frame`s but it does not understand `S4vectors::DataFrame`
    > • multiple Bioconductor packages (incl. the SCE framework) are now using `DataFrame` instead of `data.frame` 
    > • hence, one must do `ggplot(as.data.frame(DF))` when `DF` is a `DataFrame` ; Also OSCA seems to do so: [https://github.com/OSCA-source/OSCA.advanced](https://github.com/OSCA-source/OSCA.advanced)
    > • but it would be handy if we could just call: `ggplot(DF)` (i.e. if *ggplot2* could support `DataFrame`)   
    > • problem: ggplot2 is not Bioconductor package, so it would be less straightforward to request adding support
    > Has someone thought about a solution to this (or aware of a solution)?

*07:35:41 - @irem Kahveci has joined the channel*
**Michael Love** (07:40:24) (in thread):
> @Kevin Rue-Albrechtyou’re right the bolded text in the NOI has:
> * ***Biological Informatics***
> * ***Understanding of Host-Microbe Interaction***
> * ***Synthetic Cells and Cellular Systems***
> * ***Synthetic Microbial Communities***
> so the first one would be a good bucket for lots of things

**Michael Love** (07:43:45) (in thread):
> I misread at first because i didn’t see that these bolded themes were “OR”

**Michael Love** (07:48:43) (in thread):
> “bottom-line estimates of funding to be requested from the NSF/BIO and UKRI/BBSRC. For NSF, bottom line estimates should include both direct and indirect costs”
> 
> my uni requires lead time to OK budgets, even provisional, and more for international contracts. this has 4 weeks lead time:tired_face:does anyone know what the funding range is?

**Kevin Rue-Albrecht** (09:05:39) (in thread):
> > my uni requires lead time to OK budgets,
> mine has internals deadline for the process too. They sent me (and my group leader) a checklist to return by 13th Sep, and asked to receive the draft application by 20th Sep for a funder's deadline of 27th.

**Kevin Rue-Albrecht** (09:07:10) (in thread):
> They also did a bit of extra homework for me and read the BBSRC page (UK-facing side of this) which states
> > ***Maximum award:***£2,000,000
> [https://www.ukri.org/opportunity/work-with-us-researchers-bbsrc-nsf-bio-lead-agency-2023/](https://www.ukri.org/opportunity/work-with-us-researchers-bbsrc-nsf-bio-lead-agency-2023/)(if that's the number you're asking for)
  - Attachment (ukri.org): [Work with US researchers: BBSRC-NSF/BIO lead agency 2023](https://www.ukri.org/opportunity/work-with-us-researchers-bbsrc-nsf-bio-lead-agency-2023/)
    > Collaborate with US researchers on a single joint proposal.

**Aedin Culhane** (12:12:52):
> Announced on the czi slack. I wonder if this might be a mechanism to use the new functionality in R described by JJ at bioc2023 and create a open publication framework for dynamic books, workflows and vignettes.
> 
> ICYMI the Astera Institute recently launched a new program funding a cohort of entrepreneurs-in-residence aiming to build innovative tools for scientific publication/dissemination. Initial awards up to $500K with a possibility of extended funding up to $2M. They also have an open RFI in parallel to the EiR program asking participants to “describe clear technological bottlenecks limiting innovation in life sciences publishing. What is blocking the ability to build advanced tools for open sharing and discussion of scientific information?” More details at:[https://astera.org/science-opportunities/](https://astera.org/science-opportunities/)

**Aedin Culhane** (12:40:06) (in thread):
> Ireland do a tripartite program with both NIH and NSF, grants are reviewed by US partners, and they will match funds to Republic and Northern Ireland partners.[https://www.sfi.ie/funding/funding-calls/us-ireland-rd-partnership/index.xml](https://www.sfi.ie/funding/funding-calls/us-ireland-rd-partnership/index.xml)
  - Attachment (Science Foundation Ireland): [US-Ireland R&D Partnership Programme](https://www.sfi.ie/funding/funding-calls/us-ireland-rd-partnership/index.xml)
    > A ‘single-proposal, single-review’ mechanism is facilitated by the National Science Foundation and National Institutes of Health who accept submissions from tri-jurisdictional (USA, NI and RoI) teams to a number of their existing funding programmes. [https://www.sfi.ie/funding/funding-calls/us-ireland-rd-partnership/](https://www.sfi.ie/funding/funding-calls/us-ireland-rd-partnership/)

**Aedin Culhane** (12:42:05) (in thread):
> There is also an Irish -SFI and UK EPSRC funding mechanism[https://www.sfi.ie/funding/funding-calls/epsrc-sfi-partnership/index.xml](https://www.sfi.ie/funding/funding-calls/epsrc-sfi-partnership/index.xml)
  - Attachment (Science Foundation Ireland): [EPSRC-SFI Joint Funding of Research](https://www.sfi.ie/funding/funding-calls/epsrc-sfi-partnership/index.xml)
    > EPSRC and Science Foundation Ireland (SFI) have entered an agreement to welcome, encourage and support research applications that cut across national boundaries involving collaborative teams led by researchers from the UK and Ireland. [https://www.sfi.ie/funding/funding-calls/epsrc-sfi-partnership/](https://www.sfi.ie/funding/funding-calls/epsrc-sfi-partnership/)

**Aedin Culhane** (12:43:44) (in thread):
> @Kevin Rue-AlbrechtThey also did a bit of extra homework for me and read the BBSRC page (UK-facing side of this) which states
> > ***Maximum award:***£2,000,000
> its not 2,000,000.  The 2M is the sum of the US and UK funding. BBSRC will fund 80% of the UK component of the funding.

**Kevin Rue-Albrecht** (13:36:06) (in thread):
> Well spotted. Ididn’tread the fine print

*16:23:39 - @Aaron Olschefski has joined the channel*

## 2023-08-31

*12:53:09 - @Stephanie Hicks has joined the channel*
**USLACKBOT** (12:54:13):
  - File (Email): [Fwd: Apply Now: Essential Open Source Software for Science (Cycle 6)](https://community-bioc.slack.com/files/U34P8RS3B/F05QDH2E6JZ/fwd__apply_now__essential_open_source_software_for_science__cycle_6_)

**Michael Love** (12:56:20):
> Request for Applications: Essential Open Source Software for Science
> Applications due October 17, 2023 by 5 p.m. Pacific Time

**Michael Love** (13:17:31) (in thread):
> “I would like to aim to CZI for tidyomics” woohoo, EOSS6 is open

**Kevin Rue-Albrecht** (13:43:19) (in thread):
> How much coordination is there usually between bioc applications to CZI ?

**Aedin Culhane** (13:46:50):
> [https://czi.co/OpenSourceSoftwareRFA](https://czi.co/OpenSourceSoftwareRFA)
  - Attachment (Chan Zuckerberg Initiative): [Essential Open Source Software for Science - Chan Zuckerberg Initiative](https://czi.co/OpenSourceSoftwareRFA)

**Aedin Culhane** (13:48:49):
> 2-step process. LOI due Oct 17th. Full application Nov 2nd.  There are 3 funding bodies, CZI, Wellcome Trust and Kavil Foundation, and applicants will be funded by one funder

**Aedin Culhane** (13:50:34) (in thread):
> Except for Vince and I co-ordinating in the previous EOSS 5, normally very little.  But I think it helped our applications because we made it clear in the application, that our work was complementary. Both got funding.

**Aedin Culhane** (13:52:12) (in thread):
> Indirects are limited to 15%, so@Michael Loveif institute won’t allow applications when indirects are too low. I was talking to vince and could consider using NumFocus. We are on boarded to NumFocus

**Michael Love** (13:52:29) (in thread):
> ~~~yes i think it would be detrimental to name all the applications with “Bioconductor”~~~it would be good to coordinate to make applications look distinct

**Michael Love** (13:53:06) (in thread):
> whereas we have had limma/edgeR funded, DESeq2 funded, etc.**in addition**to those coordinated by “core” members

**Aedin Culhane** (13:53:36) (in thread):
> @Michael Loveno I don’t think so, they  specifically state they will fund >1 applications to the same software and same people if the projects are distinct

**Michael Love** (13:54:03) (in thread):
> UNC was fine for me to submit even with limited indirects, I think the department does have to pay, but they are more happy to have the foundation money so they let it go

**Michael Love** (13:54:45) (in thread):
> “no I don’t think so, they specifically state they will fund >1 applications to the same software and same people if the projects are distinct”
> 
> oh sorry, I just meant, having lots of applications from Bioc members is good and we should make them look distinct

**Kevin Rue-Albrecht** (14:15:21) (in thread):
> Ok so kinda “together and complementary” or “separate and distinct”

*14:22:48 - @Jennifer Foltz has joined the channel*
*14:27:26 - @Edoardo Bertolini has joined the channel*

## 2023-09-01

*11:02:10 - @Vince Carey has joined the channel*

## 2023-09-03

**Kevin Rue-Albrecht** (12:19:19) (in thread):
> @Michael Love:@Charlotte Soneson‘s PR on DESeq2 made me wonder whether there’s any potential for DESeq2/iSEE synergy[https://github.com/thelovelab/DESeq2/pull/84](https://github.com/thelovelab/DESeq2/pull/84)
  - Attachment: [#84 Fix some typos in the vignette](https://github.com/thelovelab/DESeq2/pull/84)
    > This PR fixes a couple of typos in the `DESeq2` vignette.
    > 
    > The changes on line 1574 were made in response to the following warnings:
    > 
    > ```
    > ## Warning: The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
    > ## ℹ Please use the `fun` argument instead.
    > ## This warning is displayed once every 8 hours.
    > ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    > ## generated.
    > 
    > ## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
    > ## ℹ Please use `linewidth` instead.
    > ## This warning is displayed once every 8 hours.
    > ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    > ## generated.
    > ```
    > 
    > As a consequence (since I believe `linewidth` was introduced there), I added the requirement of `ggplot2` >=3.4.0 to the `Imports`. Happy to revert back if these were intentionally retained of course.
    > 
    > Finally, a note that [`iSEEde`](https://isee.github.io/iSEEde/) was just accepted into Bioconductor (and should be available soon), in case you would like to add something like this to the bullet point that mentions `iSEE` (cc [@kevinrue](https://github.com/kevinrue)) :slightly_smiling_face:
    > 
    > ```
    > The [iSEEde]([https://bioconductor.org/packages/iSEEde](https://bioconductor.org/packages/iSEEde)) package provides 
    > additional panels that facilitate the interactive visualisation of differential 
    > expression results in iSEE applications.
    > ```


## 2023-09-04

*05:43:36 - @Mike Smith has joined the channel*
*16:52:13 - @Anna Lewkowicz has joined the channel*

## 2023-09-06

**Aedin Culhane** (07:25:22):
> Should we co-ordinate CZI EOSS6 applications, so we have an “ecosystem” of applications to support different aspects of Bioc… I have created a google doc[https://docs.google.com/document/d/1wum-jkBfGk3LMGP8oLN3nSWB_7_vASx5CrC3GDlBEN0/edit?usp=sharing](https://docs.google.com/document/d/1wum-jkBfGk3LMGP8oLN3nSWB_7_vASx5CrC3GDlBEN0/edit?usp=sharing)if you want to share ideas.  We have successfully got EOSS funding before, so happy to share insights on what CZI look for. Also happy to organize a meeting of those interested, if people want@Michael Love@Kevin Rue-Albrecht@Sean Davis

**Aedin Culhane** (07:44:02):
> Just updated sharing on doc

**Michael Love** (07:57:52) (in thread):
> @stefano mangiolaand I are scoping out funding to support development and maintanence of tidyomics packages. We’re just getting started but we can share here as we progress. We aren’t planning to mention “Bioconductor” in the title, so it’s seen as a distinct application, but of course we will mention it in the text.
> 
> I’m also happy to share thoughts. Unfortunately I have little idea what they are looking for besides what they have online. I’ve submitted 4 and awarded 1 and they give zero feedback.

**Kevin Rue-Albrecht** (09:26:10) (in thread):
> Thanks. Definitely will attempt iSEE-verse. I see the hacktoberfest item in the doc. I wasn't thinking about funding in that direction (especially as I can't apply for it myself) but happy to be part of a discussion about it

*13:30:54 - @Ludwig Geistlinger has joined the channel*
**Vince Carey** (17:14:57) (in thread):
> I have been thinking about contacting our project officer at CZI to see how we would best structure a coordinated application.  I will do it and let you know what I hear back.


## 2023-09-07

*09:24:46 - @Sehyun Oh has joined the channel*
**Laurent Gatto** (15:56:59) (in thread):
> @Johannes Rainerand I have a meeting tomorrow to discuss the submission of an MS/proteomcis/metabolomics proposal. This would be my 3rd if I count well, and as many rejection, so not holding my breath.

**Michael Love** (16:12:50) (in thread):
> it’s hard without any feedback


## 2023-09-08

*05:31:21 - @Heather Turner has joined the channel*

## 2023-09-12

*09:03:20 - @Jiwoon Park has joined the channel*

## 2023-09-13

*07:23:43 - @Davide Risso has joined the channel*

## 2023-09-15

*04:54:42 - @Leo Lahti has joined the channel*

## 2023-10-11

*05:41:31 - @Romane Libouban has joined the channel*

## 2023-11-14

*14:55:13 - @Federico Marini has joined the channel*

## 2024-01-23

*00:14:29 - @Shruti Shah has joined the channel*

## 2024-03-15

*08:34:29 - @Peace Sandy has joined the channel*

## 2024-04-26

*09:37:54 - @Francesc Català-Moll has joined the channel*

## 2024-07-03

**Aedin Culhane** (05:01:07):
> Google Research Awards 100K[https://research.google/programs-and-events/google-academic-research-awards/](https://research.google/programs-and-events/google-academic-research-awards/)
  - Attachment (research.google): [Google Academic Research Awards – Google Research](https://research.google/programs-and-events/google-academic-research-awards/)
    > Google Academic Research Awards (GARA) recognizes and supports academic research in computing and technology that makes a positive difference in the world.


## 2024-07-23

*15:15:29 - @Tuulu has joined the channel*

## 2024-08-02

**Sean Davis** (12:53:37):
> [https://datascience.cancer.gov/news-events/news/funding-available-software-support-open-science](https://datascience.cancer.gov/news-events/news/funding-available-software-support-open-science)
  - Attachment (datascience.cancer.gov): [Funding Available for Software to Support Open Science | CBIIT](https://datascience.cancer.gov/news-events/news/funding-available-software-support-open-science)
    > NIH has a new funding opportunity to help you develop scientifically sound and sustainable software tools to advance cancer research.


## 2024-11-13

*15:26:18 - @Kylie Bemis has joined the channel*

## 2024-11-25

*16:16:46 - @rohitsatyam102 has joined the channel*

## 2025-02-06

*11:59:05 - @Liz Hare has joined the channel*

## 2025-02-13

*13:54:11 - @JP Flores has joined the channel*

## 2025-03-19

**Sean Davis** (14:11:26):
> [https://www.czbiohub.org/program-ssfcz-global-science-scholars/](https://www.czbiohub.org/program-ssfcz-global-science-scholars/)
  - Attachment (CZ Biohub): [Global Science Scholars Postdoctoral Fellowship Program SS-F](https://www.czbiohub.org/program-ssfcz-global-science-scholars/)
    > Apply for the new international postdoctoral fellowship program from the CZ Biohub Network and Stellar Science Foundation.


## 2025-03-31

*12:50:50 - @Joshua Hamilton has joined the channel*