---
title: "#gpus"
---

## 2024-09-16

**Andres Wokaty** (11:03:15):
> @Andres Wokaty has joined the channel

**Levi Waldron** (11:05:28):
> @Levi Waldron has joined the channel

**Vince Carey** (11:05:28):
> @Vince Carey has joined the channel

**Lori Shepherd** (11:05:28):
> @Lori Shepherd has joined the channel

**Marcel Ramos Pérez** (11:05:28):
> @Marcel Ramos Pérez has joined the channel

**Alex Mahmoud** (11:05:29):
> @Alex Mahmoud has joined the channel

**Davide Risso** (11:05:29):
> @Davide Risso has joined the channel

**Gabriele Sales** (11:05:29):
> @Gabriele Sales has joined the channel

**Andres Wokaty** (11:06:08):
> If there's a more appropriate name, feel free to suggest or rename.

**Marcel Ramos Pérez** (14:44:17):
> Here we have some examples of how GPU driver deps are handled :[https://rapids-singlecell.readthedocs.io/en/latest/Installation.html](https://rapids-singlecell.readthedocs.io/en/latest/Installation.html)


## 2024-09-17

**Vince Carey** (09:09:16):
> Here is transcript of chat entries from first call:
> ```
> 09:08:58 From Gabriele Sales To Everyone:^M[https://developer.nvidia.com/nsight-systems](https://developer.nvidia.com/nsight-systems)09:09:51 From Alexandru Mahmoud To Everyone:^M[https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/](https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/)09:14:12 From Davide Risso To Everyone:^M[https://github.com/billila/spca/tree/main](https://github.com/billila/spca/tree/main)09:14:41 From Davide Risso To Everyone:^M[https://github.com/billila/spca/blob/main/2_time/M10_time.py](https://github.com/billila/spca/blob/main/2_time/M10_time.py)09:22:53 From jen (they/them/theirs) To Everyone:^M[https://docs.google.com/document/d/1FVfgxGe8-eSViKwlWKvJrlxkPky-Rx4zGPFS7Ny7hrA/edit#heading=h.6kz8o1se9wa0](https://docs.google.com/document/d/1FVfgxGe8-eSViKwlWKvJrlxkPky-Rx4zGPFS7Ny7hrA/edit#heading=h.6kz8o1se9wa0)09:29:53 From jen (they/them/theirs) To Everyone:^M
>         is this biocontainers:[https://biocontainers.pro/](https://biocontainers.pro/)?
> 09:47:20 From Vincent Carey To Everyone:^M[https://bioconductor.org/packages/release/bioc/html/gpuMagic.html](https://bioconductor.org/packages/release/bioc/html/gpuMagic.html)
> ```
  - Attachment (NVIDIA Developer): [NVIDIA Nsight Systems](https://developer.nvidia.com/nsight-systems)
> Profile systems, analyze performance, and optimize platforms.
  - Attachment (The GitHub Blog): [GitHub Actions: GPU hosted runners are now generally available · GitHub Changelog](https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/)
> GitHub Actions: GPU hosted runners are now generally available


## 2024-10-08

**Lori Shepherd** (08:11:25):
> I plan on joining late to the meeting today.  I will join as soon as I can as I have overlapping this morning

**Vince Carey** (08:55:33):
> i will be somewhat late also

**Vince Carey** (09:13:47):
> [https://docs.google.com/document/d/1DdrZehrn1pD4D1P6gieEcGGyT3yDrmXt7ZcTtDNb9i0/edit](https://docs.google.com/document/d/1DdrZehrn1pD4D1P6gieEcGGyT3yDrmXt7ZcTtDNb9i0/edit)is the agenda
  - File (Google Docs): [CZI EOSS6 GPU](https://community-bioc.slack.com/files/U34P8RS3B/F07QWVC46TU/czi_eoss6_gpu)

**Vince Carey** (09:23:30):
> [https://github.com/scverse/rapids_singlecell](https://github.com/scverse/rapids_singlecell)


## 2024-10-14

**Michael Lynch** (09:18:32):
> @Michael Lynch has joined the channel


## 2024-11-10

**Shian Su** (19:48:36):
> @Shian Su has joined the channel

**Shian Su** (20:35:41):
> Heard Davide mention this initiative at BioCAsia, interested in keeping tabs on how it goes. Don't have the expertise to help out with code but have some thoughts to share.
> 
> Having seen Ilaria's benchmarking talk and some other talks at ABACBS/BioCAsia, my thoughts are that targeting GPU in general is still a very difficult problem, and the best value would come from speeding up key steps in popular workflows. Ideally there'd be cross-platform support for generic statistical computations, but that requires such rare expertise to develop and maintain that I don't think it's feasible (unless you already have someone in mind). I think as a starting point, providing GPU for the BiocSingular functions would be very valuable, I'm interested in what might be the best option between cu.ml, RAPIDS, cuBLAS and openACC.[https://github.com/ceslobfer/GPUmatrix](https://github.com/ceslobfer/GPUmatrix)seems to be a new entrant to the field that might be looking at. Also, I'm not entirely sure of how tensor cores being added to all our CPUs for AI will affect this, it's not clear to me whether that hardware is considered to be a part of the CPU, in which case all our matrix operations will magically speed up in the future with no intervention, or if it's considered to be a GPU where additional work is required to offload calculations onto them.


## 2024-11-11

**Shian Su** (18:10:47):
> [https://github.com/gfx-rs/wgpu](https://github.com/gfx-rs/wgpu)from Rust is also very interesting, I don't know what the state of R-Rust interface is at the moment.


## 2024-11-12

**Andres Wokaty** (09:08:26):
> @Levi Waldron@Alex MahmoudPlease use[https://meet.google.com/toh-kgxv-pho](https://meet.google.com/toh-kgxv-pho)for the meeting today.
  - Attachment (meet.google.com): [Meet](https://meet.google.com/toh-kgxv-pho)
> Real-time meetings by Google. Using your browser, share your video, desktop, and presentations with teammates and customers.

**Ilaria Billato** (09:09:39):
> @Ilaria Billato has joined the channel

**Alex Mahmoud** (10:02:06):
> Sorry I am at Anvil conference at CSHL, so I will be missing meetings until Thursday


## 2024-12-10

**Gabriele Sales** (07:12:57):
> Hi everyone, I wanted to let you know that I won't be able to join today's meeting. I need to attend the thesis discussion of one of my master's students, which unfortunately conflicts with our meeting time.

**Lori Shepherd** (07:15:57):
> I will also be a few minutes late as I have back to back meeting and the previous normally goes a little long.  I'll pop on as soon as I can.


## 2025-01-14

**Marcel Ramos Pérez** (09:05:08):
> Is there a meeting link for today?

**Andres Wokaty** (09:05:24):
> Was there no link?

**Andres Wokaty** (09:06:40):
> [https://us02web.zoom.us/j/83618883993?pwd=Ffp7w8kMQWatWT7YKAtn6RRp2NNl9u.1](https://us02web.zoom.us/j/83618883993?pwd=Ffp7w8kMQWatWT7YKAtn6RRp2NNl9u.1)

**Marcel Ramos Pérez** (09:08:38):
> Thanks!


## 2025-01-29

**Davide Risso** (05:39:23):
> Adding@Amin Zadenoorito this channel. Amin is joining my group and will work on the CZI GPU project

**Amin Zadenoori** (05:39:25):
> @Amin Zadenoori has joined the channel


## 2025-02-10

**Davide Risso** (10:45:13):
> Hi<!here>in preparation for tomorrow's meeting, please find a draft of the agenda here:[https://docs.google.com/document/d/1DdrZehrn1pD4D1P6gieEcGGyT3yDrmXt7ZcTtDNb9i0/edit?usp=sharing](https://docs.google.com/document/d/1DdrZehrn1pD4D1P6gieEcGGyT3yDrmXt7ZcTtDNb9i0/edit?usp=sharing)We hope to discuss, among other things, practical steps to start testing GPU-aware packages on the new server.


## 2025-02-11

**Hervé Pagès** (11:14:26):
> @Hervé Pagès has joined the channel

**Andres Wokaty** (11:27:53):
> At the GPU meeting today, we discussed the possibility of having something like a tag, such as a biocViews term, to find GPU capable packages. I don't know what's the process to add new terms and how can encourage maintainers to add this term for their packages? Because I think we might have packages with GPU support.

**Lori Shepherd** (11:29:40):
> I can help add the term. No way to enforce people to use it but if you find existing once added  you can email to ask to add it

**Vince Carey** (13:10:09):
> We should discuss the role of biocViews for this purpose.  Is it used for any other aspect of "requirement" or "optional capability" of a resource?  I think we should add a tag if it is relevant to the aims of biocViews but I'd like more discussion of whether this is so.


## 2025-02-13

**Lori Shepherd** (08:04:31):
> [https://bioconductor.org/packages/release/BiocViews.html#___Infrastructure](https://bioconductor.org/packages/release/BiocViews.html#___Infrastructure)we have some other infrastructure type views... I guess let me know what is decided after further discussion and just ping me if you want the new view created.


## 2025-03-10

**Davide Risso** (10:36:32):
> <!channel>our next scheduled meeting is tomorrow at 9am EST, which I believe is too early for Hervé on the West Coast. I think it would be good for Hervé to start attending these meetings (or at least to attend the next one) given the work he has done to test the RbowtieCuda package, which is very relevant to the role of our new GPU server. Any chance that we can reschedule to a more West-Coast-Friendly time?

**Davide Risso** (10:37:49):
> For instance, would you be available Wed 3/12 at 9am Pacific / 12noon Easter / 5pm Europe? (please react with:+1:or:thumbsdown:)

**Andres Wokaty** (13:50:34):
> I will cancel our meeting tomorrow so that we can try to reschedule for later this week or next week.

**Davide Risso** (15:54:42):
> Thanks@Andres Wokaty!@Hervé Pagèsany chance you can make our proposed meeting time (see above)?


## 2025-03-11

**Andres Wokaty** (14:07:09):
> Are there specs for the new gpu machine somewhere?


## 2025-03-17

**Hervé Pagès** (12:58:34) (in thread):
> Sorry for the late response. I was travelling with poor access to internet. 9am Pacific works for me in general except on Fridays. Also I think we have our biweekly Image Analysis meeting this week on Wednesday. Other than that, any day will do.

**Andres Wokaty** (13:18:07):
> I think rescheduling for tomorrow might be too short notice, so we can reschedule for possibly this Thursday 3/20 or likely next Tuesday 3/25 at 9am PT/ 12pm ET / 5pm Europe. If anyone has a preference, let me know by 3/18 9am ET and I'll send the invite and update subsequent meetings.

**Hervé Pagès** (13:54:04) (in thread):
> Thursday 3/20 or next Tuesday 3/25 both work for me, thanks!


## 2025-03-25

**Andres Wokaty** (12:04:29):
> Hi, we are meeting now:slightly_smiling_face:

**Simple Poll** (13:08:17):
> @Simple Poll has joined the channel

**Simple Poll** (13:08:17):
> @Simple Poll has joined the channel

**Simple Poll** (13:08:54):
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: actions]
> 
> [Unsupported block type: context]

**Andres Wokaty** (13:10:01):
> If you want more options, such as Friday or Tuesday, I can add. Whatever is picked, I will try to avoid other conflicts like the TAB meeting.


## 2025-03-27

**Davide Risso** (05:58:59):
> Just FYI for people in Europe, the European time will change next week so 5pm will be 6pm and 6pm will be 7pm


## 2025-04-17

**Juan Henao** (17:23:41):
> @Juan Henao has joined the channel
