---
title: "#gwas-data"
---

## 2021-01-23

**Vince Carey** (10:42:38):
> @Vince Carey has joined the channel

**Vince Carey** (10:42:38):
> set the channel description: Continues a discussion of data structures for GWAS-related data, especially summary statistics

**Malte Thodberg** (10:43:01):
> @Malte Thodberg has joined the channel

**Kasper D. Hansen** (10:43:01):
> @Kasper D. Hansen has joined the channel

**Kevin Blighe** (10:43:01):
> @Kevin Blighe has joined the channel

**RGentleman** (10:43:12):
> @RGentleman has joined the channel

**Qian Liu** (10:43:24):
> @Qian Liu has joined the channel

**Vince Carey** (10:45:46):
> [https://vjcitn.github.io/gwaslake/articles/gwaslake.html](https://vjcitn.github.io/gwaslake/articles/gwaslake.html)defines a container and starts a documentation effort to aid interested parties ... building the container with gwasglue proved problematic, and a few packages needed DESCRIPTION tweaked, and thus repos were forked.
  - Attachment (vjcitn.github.io): [gwaslake: exploring the MRC GWAS API and data/software ecosystem with Bioconductor](https://vjcitn.github.io/gwaslake/articles/gwaslake.html)
> gwaslake

**Yagoub Ali Ibrahim Adam** (14:54:29):
> @Yagoub Ali Ibrahim Adam has joined the channel

**Lambda Moses** (14:54:43):
> @Lambda Moses has joined the channel

**Sridhar N** (14:55:40):
> @Sridhar N has joined the channel

**FelixErnst** (19:32:54):
> @FelixErnst has joined the channel

**rohitsatyam102** (21:38:02):
> @rohitsatyam102 has joined the channel


## 2021-01-24

**Malte Thodberg** (03:54:58):
> Looks cool!
> Pretty interesting to see that their gwasglue and ieugwas packages don’t use any Bioconductor at all…

**Ludwig Geistlinger** (12:02:21):
> @Ludwig Geistlinger has joined the channel

**Frederick Tan** (14:57:09):
> @Frederick Tan has joined the channel

**Hector Climente** (17:19:21):
> @Hector Climente has joined the channel


## 2021-01-25

**Sean Davis** (12:37:09):
> @Sean Davis has joined the channel


## 2021-02-08

**Rene Welch** (11:26:40):
> @Rene Welch has joined the channel


## 2021-02-23

**Wynn Cheung** (10:32:40):
> @Wynn Cheung has joined the channel


## 2021-03-12

**Julia Romanowska** (14:51:24):
> @Julia Romanowska has joined the channel


## 2021-04-21

**Aishwarya Mandava** (13:55:58):
> @Aishwarya Mandava has joined the channel


## 2021-04-29

**Tembi F** (04:47:32):
> @Tembi F has joined the channel


## 2021-05-01

**Arjun Krishnan** (21:42:34):
> @Arjun Krishnan has joined the channel


## 2021-05-11

**Megha Lal** (16:45:00):
> @Megha Lal has joined the channel


## 2022-01-03

**Kurt Showmaker** (17:04:10):
> @Kurt Showmaker has joined the channel


## 2022-01-28

**Megha Lal** (11:12:49):
> @Megha Lal has left the channel


## 2022-02-01

**Lindsay Clark** (09:59:01):
> @Lindsay Clark has joined the channel


## 2022-05-05

**Aedin Culhane** (12:22:45):
> @Aedin Culhane has joined the channel


## 2022-05-10

**Daniel Adediran** (05:11:22):
> @Daniel Adediran has joined the channel


## 2022-10-10

**Mercilena Benjamin** (13:55:59):
> @Mercilena Benjamin has joined the channel


## 2022-10-28

**Brian Schilder** (08:31:02):
> @Brian Schilder has joined the channel


## 2022-11-06

**Sherine Khalafalla Saber** (11:20:46):
> @Sherine Khalafalla Saber has joined the channel


## 2022-12-11

**Vince Carey** (07:31:01):
> Anyone experienced with variant annotation by Nirvana?[https://illumina.github.io/NirvanaDocumentation/](https://illumina.github.io/NirvanaDocumentation/)
  - Attachment (illumina.github.io): [Introduction | Nirvana](https://illumina.github.io/NirvanaDocumentation/)
> Clinical-grade variant annotation


## 2022-12-12

**Kendall H. Burks** (17:58:27):
> @Kendall H. Burks has joined the channel


## 2023-01-03

**Alan Murphy** (10:33:52):
> @Alan Murphy has joined the channel


## 2023-01-21

**Hien** (16:02:33):
> @Hien has joined the channel


## 2023-01-26

**Hien** (23:20:46):
> @Hien has left the channel


## 2023-03-10

**Joaquin Reyna** (15:35:35):
> @Joaquin Reyna has joined the channel


## 2023-05-03

**Rebecca Butler** (16:16:11):
> @Rebecca Butler has joined the channel


## 2023-06-19

**Pierre-Paul Axisa** (05:10:47):
> @Pierre-Paul Axisa has joined the channel


## 2023-08-12

**Xiuwen Zheng** (22:19:22):
> @Xiuwen Zheng has joined the channel


## 2024-01-26

**Vince Carey** (05:44:50):
> VariantAnnotation (devel branch) now includes vep_by_region, which prepares a request to the ensembl REST API for variant effect prediction.  The perl-based API interfaces in ensemblVEP will no longer be maintained; the Bioconductor ensemblVEP package will be deprecated in 3.19.


## 2024-07-29

**JP Flores** (17:09:32):
> @JP Flores has joined the channel


## 2024-08-27

**Bharat Mishra** (11:36:52):
> @Bharat Mishra has joined the channel


## 2024-09-16

**Mike Morgan** (06:24:29):
> @Mike Morgan has joined the channel


## 2024-09-18

**Alan Murphy** (05:05:51):
> Hey All! I'm the creator of the[MungeSumstats](https://github.com/Al-Murphy/MungeSumstats)Bioconductor package which standardises and performs quality control of GWAS sumstats. We recently encountered an issue with mislabeled allele columns in a GWAS which I would like to get the communities opinions on? If you have 5 minutes, see this[Twitter post](https://x.com/Al_Murphy_/status/1834195362052997123)on it and the[related github issue](https://github.com/Al-Murphy/MungeSumstats/issues/193)


## 2025-03-18

**Nicolo** (15:00:54):
> @Nicolo has joined the channel
