---
title: "#hacktoberfest"
---

## 2023-01-20

**Maria Doyle** (08:11:34):
> @Maria Doyle has joined the channel

**Maria Doyle** (08:11:34):
> set the channel description: A channel for discussions of Bioconductor participation in Hacktoberfest

**Kozo Nishida** (08:11:44):
> @Kozo Nishida has joined the channel

**Kevin Rue-Albrecht** (08:11:44):
> @Kevin Rue-Albrecht has joined the channel


## 2023-01-21

**Hien** (16:02:35):
> @Hien has joined the channel


## 2023-07-05

**Sonali Kumari** (16:11:07):
> @Sonali Kumari has joined the channel


## 2023-08-08

**Kozo Nishida** (04:42:46):
> I found out it was already August...
> We need to plan for Hacktoberfest (in October).
> If anyone has any ideas for actions for Hacktoberfest, please let us know.[https://community-bioc.slack.com/archives/CEQD45CHK/p1691420966046599](https://community-bioc.slack.com/archives/CEQD45CHK/p1691420966046599)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CEQD45CHK/p1691420966046599)
> FYI stay tuned with the CAB for Hacktoberfest. We've been talking about organising a Bioconductor event this year. The open challenges would be a great headline for it!


## 2023-08-09

**Andres Wokaty** (15:16:08):
> @Andres Wokaty has joined the channel


## 2023-08-10

**Johannes Rainer** (16:22:30):
> @Johannes Rainer has joined the channel

**Johannes Rainer** (16:23:29):
> Just as info: I will definitely open one of my repos for hacktoberfest:slightly_smiling_face:

**Sonali Kumari** (16:34:46):
> Hello, I am sonali kumari, a 3rd-year undergraduate student from India. I am a current outreachy intern at Bioconductor, and my mentor is@Andres Wokaty. Feel free to contact me if you need any volunteers or help for Hactoberfest. I will be more than happy to help.

**Kevin Rue-Albrecht** (17:05:15) (in thread):
> Hi and thanks!
> As things stand, I may be the one who'll try to get Bioconductor registered with DigitalOcean as an organisation participating in Hacktoberfest this year.
> From there, we'll advertise to the community to get developers involved (opening their repositories for contributions) and contributors involved (opening PRs in October).
> Let me know if/how you'd like to help. I'll message here too when I identify things people can help with!


## 2023-08-11

**Leo Lahti** (05:43:50):
> @Leo Lahti has joined the channel


## 2023-08-16

**Zainab Ashimiyu-Abdusalam** (07:57:06):
> @Zainab Ashimiyu-Abdusalam has joined the channel


## 2023-08-21

**Charlotte Soneson** (13:48:12):
> @Charlotte Soneson has joined the channel


## 2023-08-24

**Tuomas Borman** (17:13:21):
> @Tuomas Borman has joined the channel

**Leo Lahti** (17:16:44):
> We are potentially interested to join Hactoberfest. I saw some more info somewhere, is there more info? We could consider arranging activities around microbiome.


## 2023-08-28

**Abdullah Al Nahid** (15:06:54):
> @Abdullah Al Nahid has joined the channel


## 2023-08-29

**Kevin Rue-Albrecht** (08:02:14) (in thread):
> April 2023 minutes of the CAB meeting[https://bioconductor.org/about/community-advisory-board/2023-04-13-minutes.pdf](https://bioconductor.org/about/community-advisory-board/2023-04-13-minutes.pdf)

**Kevin Rue-Albrecht** (08:02:58) (in thread):
> I've recently contacted our Hacktoberfest contact. I was recommended to wait until announcements at the start of September


## 2023-09-04

**Kevin Rue-Albrecht** (04:17:22):
> On my way to work, anyone wants to help me read instructions at[https://hacktoberfest.com](https://hacktoberfest.com)to figure out what to do to for Bioconductor to participate this year?I’llhave a closer read myself asap
  - Attachment (hacktoberfest.com): [Hacktoberfest 2023](https://hacktoberfest.com)
> Hacktoberfest: a month-long celebration of open-source projects, their maintainers, and the entire community of contributors.

**Charlotte Soneson** (04:38:31) (in thread):
> My take-aways:slightly_smiling_face:
> * Prepare repositories by adding labels and suitable issues ([https://hacktoberfest.com/participation/#maintainers](https://hacktoberfest.com/participation/#maintainers)) - to me it seemed like this is the only required action (and even without it, contributors could still ask for PRs to be labeled as`hacktoberfest-accepted`)
> * Potentially organize events ([https://hacktoberfest.com/events/#organizers](https://hacktoberfest.com/events/#organizers)), which I suppose would be more subproject-specific?

**Kevin Rue-Albrecht** (04:39:47) (in thread):
> So I guess the same as every year. Perhaps no need to tryhard a Bioconductor level event

**Kevin Rue-Albrecht** (04:40:15) (in thread):
> Of course there could be events related to Bioconductor repositories (eg website)


## 2023-09-06

**Leo Lahti** (07:03:07) (in thread):
> we can join as individual Bioc development projects, and perhaps use this to plan how to promote more coordinated community action for next year

**Kevin Rue-Albrecht** (07:18:57) (in thread):
> yup, in summary, what I meant is:
> * initialise a new quarto markdown website
> * invite Bioconductor developers maintaining a repository participating in hacktoberfest to add an entry/page in the website to give extra visibility to their project

**Kevin Rue-Albrecht** (07:20:24) (in thread):
> unless someone can point to an existing website with suitable space to create that sort of content


## 2023-09-13

**Vince Carey** (11:29:54):
> @Vince Carey has joined the channel


## 2023-09-14

**Taylor Reiter** (15:31:36):
> @Taylor Reiter has joined the channel

**Taylor Reiter** (15:41:31):
> Hi Bioconductor! We at[Arcadia Science](https://www.arcadiascience.com/)are hosting a[mini-hackathon](https://www.eventbrite.com/e/hacktoberfest-at-arcadia-science-tickets-713938869377)(in person) this October in celebration of Hacktoberfest & to give back to the bioinformatics open source community. In the lead up to this, we’re curating a set of repositories that are accepting PRs. While we’ll provide this document to our hacktoberfest participants, we’d like to share it with the broader bioinformatics open source community to better match skills/interests with software needs. Have bioconductor maintainers tagged issues/repos that are hacktoberfest accepted yet? I would love to add them/accept suggestions including them in[this google doc](https://docs.google.com/document/d/1EjyQOwPO-Zc4aKM_mTPEFo3K97Ox3lEk-DyZxlivyVU/edit?usp=sharing)!


## 2023-09-15

**Leo Lahti** (04:54:49):
> @Leo Lahti has joined the channel


## 2023-09-29

**Zainab Ashimiyu-Abdusalam** (12:05:54) (in thread):
> Can we share this out?


## 2023-10-02

**Maria Doyle** (09:02:47) (in thread):
> @Taylor Reiterapologies for the delayed response, it’s been busy here! Is it still possible for us to join the Hacktoberfest initiative? We’d like to encourage Bioconductor maintainers who are interested to add their repos to your document. We see great value in participating and hope it’s not too late to collaborate.
> 
> Thanks and looking forward to your reply!

**Taylor Reiter** (10:15:17) (in thread):
> Please@Zainab Ashimiyu-Abdusalam, we would love if you share this out!@Maria Doyleyes it is still possible to join Hacktoberfest, both for this document and more generally. The event lasts through the end of October, so there is still plenty of time. We would love to see Bioconductor maintainers participating!


## 2023-10-03

**Maria Doyle** (09:29:17) (in thread):
> @Taylor Reitercan you help with@Kozo Nishida’s question
> > I’d like to add my repository to their list.[https://github.com/kozo2/BiocYouTubeTimestamps](https://github.com/kozo2/BiocYouTubeTimestamps)However, most of the repositories in[the Google Doc ](https://docs.google.com/document/d/1EjyQOwPO-Zc4aKM_mTPEFo3K97Ox3lEk-DyZxlivyVU/edit?usp=sharing)seem to be under organizations. Is it okay to suggest additions to[the Google Doc ](https://docs.google.com/document/d/1EjyQOwPO-Zc4aKM_mTPEFo3K97Ox3lEk-DyZxlivyVU/edit?usp=sharing)while keeping my repository under my user account?

**Taylor Reiter** (20:06:28) (in thread):
> @Maria Doyle@Kozo NishidaYes it’s totally fine to add a repository to the google doc that is housed under a user account:slightly_smiling_face:


## 2023-10-17

**Muluh** (04:10:33):
> @Muluh has joined the channel


## 2024-07-23

**Tuulu** (15:18:23):
> @Tuulu has joined the channel


## 2024-08-27

**Bharat Mishra** (11:36:55):
> @Bharat Mishra has joined the channel
