---
title: "#hca-data-insights"
---

## 2021-10-24

**Martin Morgan** (09:32:26):
> @Martin Morgan has joined the channel

**Martin Morgan** (09:32:26):
> set the channel description: Human Cell Atlas ‘Data Insights’ proposal

**Stephanie Hicks** (09:33:41):
> @Stephanie Hicks has joined the channel

**Davide Risso** (09:33:41):
> @Davide Risso has joined the channel

**Laurent Gatto** (09:33:41):
> @Laurent Gatto has joined the channel

**Lukas Weber** (09:33:41):
> @Lukas Weber has joined the channel

**Matt Ritchie** (09:33:41):
> @Matt Ritchie has joined the channel

**Martin Morgan** (09:52:02):
> <!channel>Our next group meeting will be Wednesday November 10 at 8am Eastern to discuss[https://chanzuckerberg.com/rfa/single-cell-data-insights/](https://chanzuckerberg.com/rfa/single-cell-data-insights/). Please take a brief look at the RFA before-hand so that we can strategize about directions, timelines, participation, etc.
> 
> The agenda is at[https://docs.google.com/document/d/1okIX93rq7867YLxKMdLVoK6t5MNQvFUMa00Tlww8A6w/edit?usp=sharing](https://docs.google.com/document/d/1okIX93rq7867YLxKMdLVoK6t5MNQvFUMa00Tlww8A6w/edit?usp=sharing)HCA sc Data Insights proposal
> Wednesday, November 10 · 8:00 – 9:00am
> Google Meet joining info
> Video call link:[https://meet.google.com/ajz-jxgg-zzs](https://meet.google.com/ajz-jxgg-zzs)Or dial: ‪(US) +1 650-285-3089‬ PIN: ‪296 828 473‬#
> More phone numbers:[https://tel.meet/ajz-jxgg-zzs?pin=3514184645744](https://tel.meet/ajz-jxgg-zzs?pin=3514184645744)
  - Attachment (Chan Zuckerberg Initiative): [New Funding Opportunity for Single-Cell Computational Biology](https://chanzuckerberg.com/rfa/single-cell-data-insights/)
> Advancing tools and resources for analyzing single-cell biology datasets to gain greater insights into health and disease.
  - Attachment (meet.google.com): [Meet](https://meet.google.com/ajz-jxgg-zzs)
> Real-time meetings by Google. Using your browser, share your video, desktop, and presentations with teammates and customers.
  - Attachment (meet.google.com): [Meet](https://tel.meet/ajz-jxgg-zzs?pin=3514184645744)
> Real-time meetings by Google. Using your browser, share your video, desktop, and presentations with teammates and customers.

**Stephanie Hicks** (10:01:46):
> Thanks@Martin Morgan!


## 2021-10-25

**Kasper D. Hansen** (10:34:35):
> @Kasper D. Hansen has joined the channel

**Vince Carey** (11:28:18):
> @Vince Carey has joined the channel

**Charlotte Soneson** (11:29:33):
> @Charlotte Soneson has joined the channel

**Sean Davis** (13:28:02):
> @Sean Davis has joined the channel

**Frederick Tan** (16:16:25):
> @Frederick Tan has joined the channel

**Mike Smith** (18:59:25):
> @Mike Smith has joined the channel


## 2021-10-26

**Aedin Culhane** (01:30:48):
> @Aedin Culhane has joined the channel

**Mark Robinson** (02:28:33):
> @Mark Robinson has joined the channel

**Chris Vanderaa** (03:18:59):
> @Chris Vanderaa has joined the channel

**Koen Van den Berge** (04:28:16):
> @Koen Van den Berge has joined the channel

**Shila Ghazanfar** (05:02:19):
> @Shila Ghazanfar has joined the channel


## 2021-10-27

**Constantin Ahlmann-Eltze** (04:09:26):
> @Constantin Ahlmann-Eltze has joined the channel

**Martin Morgan** (07:55:44):
> <!here>I added the agenda for today’s meeting ([https://docs.google.com/document/d/1okIX93rq7867YLxKMdLVoK6t5MNQvFUMa00Tlww8A6w/edit?usp=sharing](https://docs.google.com/document/d/1okIX93rq7867YLxKMdLVoK6t5MNQvFUMa00Tlww8A6w/edit?usp=sharing)) to the invite pinned to this channel.

**Kasper D. Hansen** (08:57:53):
> I will set up a meeting for various aspects of data integration. The preliminary list of names are Stephanie, Shila, Laurent. We have a couple of different integration directions

**Kasper D. Hansen** (08:58:38):
> Let’s meet next Wednesday at 8am EST (same time as the meeting today), since that seems to fit peoples agenda and we’re already spanning 3 continents

**Kasper D. Hansen** (08:58:56):
> I’ll send a link shortly

**Mark Robinson** (09:03:00):
> (if I'm not mistaken .. note that for the Nov 1-5th week, there is only a 5h time difference b/w EST and CET)

**Aedin Culhane** (09:05:59):
> Yes@Mark Robinsonyour correct. 4 hours different to UK time, 5 hours to CEST

**Kasper D. Hansen** (09:06:37):
> arghh. Anyway, by specifying 8am EST I have protected myself from this!

**Aedin Culhane** (09:07:56):
> Does 8am EST/12noon GMT/1pm CET on Tues/Thurs work for cluster calling/signatures/gene set models.:heart:for Tues.:+1:for Thurs

**Davide Risso** (09:27:27):
> Are people interested in attending more than one of the discussion groups? I.e. should we try to avoid overlapping meeting?

**Kasper D. Hansen** (09:34:47):
> There are for sure people listed in multiple groups, so I think the answer to this is largely yes

**Kasper D. Hansen** (09:35:03):
> at least for the initial discussion

**Mark Robinson** (09:37:00):
> For the benchmarking focus group, and to avoid the other groups but still maintain the magic 3-continent-compatible time, I propose Mon 1st November 13.00 Zurich time. From the Google doc and this now-broad topic, I'm expecting (if available) minimally@Matt Ritchie@Davide Risso@Laurent Gatto@Stephanie Hicks@Harald Sager Voehringer@Shila Ghazanfar@Lukas Weber(others of course welcome) .. please give an indication if you can make it with:ok_hand:. Given the breadth, we will likely need to anyways subdivide.
  - File (PNG): [Screenshot 2021-10-27 at 15.35.44.png](https://community-bioc.slack.com/files/U34P8RS3B/F02JTG7CVPZ/screenshot_2021-10-27_at_15.35.44.png)

**Harald Sager Voehringer** (09:37:07):
> @Harald Sager Voehringer has joined the channel

**Mark Robinson** (09:40:50) (in thread):
> meeting will take place here:[https://uzh.zoom.us/j/65508609136?pwd=ZC8wTUhOeVk3d3N2U3JmV3J2RkhOQT09](https://uzh.zoom.us/j/65508609136?pwd=ZC8wTUhOeVk3d3N2U3JmV3J2RkhOQT09)

**Laurent Gatto** (10:28:24) (in thread):
> That clashes with a Bioc code of conduct call. Would it be possible to have it 1 hour later?

**Laurent Gatto** (10:29:35) (in thread):
> I'm unlikely to be able to join (it's bank holiday in Belgium) and will try to catch up.

**Mark Robinson** (10:33:02) (in thread):
> sorry about that@Laurent Gatto.. there will be a recording, in case that helps.

**Laurent Gatto** (10:33:23) (in thread):
> Great, thank you!

**Kasper D. Hansen** (10:34:44) (in thread):
> Ok with me.@Stephanie Hicks@Shila Ghazanfar? Laurent is suggesting 9am EST

**Davide Risso** (10:37:05) (in thread):
> It’s a holiday in italy as well, will catch up with the recording!

**Davide Risso** (10:41:48):
> For the data structure group, what about::one:1pm CET Tues 2 November:two:2pm CET Wed 3 November:three:2pm CET Fri 5 November
> 
> Please vote with the corresponding emoji

**Martin Morgan** (11:01:41):
> I’ve added a folder (czi-sc-data-insights-2021) with documents for each of the focus areas. Links are in the ‘Focus areas’ section of this morning’s agenda; I moved the Focus areas section to the top of the document for easy reference.
> 
> My hope is that notes from meetings / etc can be stored in this place so that communication / directions are relatively transparent. Feel free to add or structure things in whatever way works best for your groups, including adding subfolders etc for specific proposals as we move in that direction. Note that the links are quite permissive (edit for anyone with the link); this might be made more restrictive as ideas become more mature, mostly to protect content from accidental change (so restricting the shared link to ‘comment’, with specific individuals having ‘edit’ permissions).
> 
> Thanks everyone for your enthusiasm!

**Dario Righelli** (11:08:23):
> @Dario Righelli has joined the channel

**Gabriele Sales** (11:16:33):
> @Gabriele Sales has joined the channel

**Shila Ghazanfar** (11:19:18) (in thread):
> that works with me too, 9AM EST Wed 3rd Nov

**Laurent Gatto** (11:55:24) (in thread):
> Thank you!

**Mike Smith** (13:04:33) (in thread):
> AFAIK it's clock change day on 31st Oct, so this is CET, right?

**Davide Risso** (18:07:36) (in thread):
> Oh God.. I think you're right.. I never remember that S in CEST is Summer and not Standard like in EST!

**Davide Risso** (18:08:04) (in thread):
> Fixed now!


## 2021-10-28

**Laurent Gatto** (08:47:11) (in thread):
> I'm teaching at 2pm - I will try to start a bit later to join the beginning of the meeting.

**Davide Risso** (10:54:29) (in thread):
> Ok let’s go with 2pm on Friday 5/11. Will send a link closer to the date!


## 2021-10-29

**Aedin Culhane** (19:21:38):
> Nice review from Luke Zappia and Fabian Thesis on sc package.  Interesting to see so many R packages in github and not submitted to R or Bioconductor[https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02519-4](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02519-4)
  - Attachment (Genome Biology): [Over 1000 tools reveal trends in the single-cell RNA-seq analysis landscape - Genome Biology](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02519-4)
> Recent years have seen a revolution in single-cell RNA-sequencing (scRNA-seq) technologies, datasets, and analysis methods. Since 2016, the scRNA-tools database has cataloged software tools for analyzing scRNA-seq data. With the number of tools in the database passing 1000, we provide an update on the state of the project and the field. This data shows the evolution of the field and a change of focus from ordering cells on continuous trajectories to integrating multiple samples and making use of reference datasets. We also find that open science practices reward developers with increased recognition and help accelerate the field.

**Aedin Culhane** (19:22:23):
  - File (PNG): [Screen Shot 2021-10-30 at 12.20.20 AM.png](https://community-bioc.slack.com/files/U34P8RS3B/F02KM2424E6/screen_shot_2021-10-30_at_12.20.20_am.png)


## 2021-11-01

**Mark Robinson** (03:31:05):
> Hi all. I didn't get too many:ok_hand:for this "benchmarking focus" meeting (later today) and a couple that couldn't make it, so I'm thinking it's best to postpone ..:one:Tuesday/:two:Wednesday/:three:Thursday Nov 2nd/3rd/4th 13.00 CET could all work for me. Potential clash with@Aedin Culhane's and@Kasper D. Hansen's meeting.
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C02JX7P0WMS/p1635341820021700?thread_ts=1635341820021700&cid=C02JX7P0WMS)
> For the benchmarking focus group, and to avoid the other groups but still maintain the magic 3-continent-compatible time, I propose Mon 1st November 13.00 Zurich time. From the Google doc and this now-broad topic, I'm expecting (if available) minimally @Matt Ritchie @Davide Risso @Laurent Gatto @Stephanie Hicks @Harald Sager Voehringer @Shila Ghazanfar @Lukas Weber (others of course welcome) .. please give an indication if you can make it with :ok_hand:. Given the breadth, we will likely need to anyways subdivide.

**Mark Robinson** (03:34:00) (in thread):
> in any case, maybe best to start in the google doc that@Martin Morgansetup:[https://docs.google.com/document/d/1UhLn-gma6WnjiFx27Uzf3EmdV19K4m7wMWZIX2PX9PA/edit](https://docs.google.com/document/d/1UhLn-gma6WnjiFx27Uzf3EmdV19K4m7wMWZIX2PX9PA/edit)


## 2021-11-02

**Aedin Culhane** (06:06:18) (in thread):
> Any interest?????

**Aedin Culhane** (06:08:16):
> No one responded to my question on meeting times for signature models/annotation on PCA space …  Can I assume no one is interested?


## 2021-11-03

**Stephanie Hicks** (06:38:58):
> Hi everyone — I apologize for not responding to the polls above. Things got a little crazy the last week for me. I’ll reach out directly here in a bit to folks the get a sense of where things stand in the projects I listed my name for. Also, for anyone interested in the scalability one — will ping soon.

**Stephanie Hicks** (06:40:09) (in thread):
> Hi@Kasper D. Hansenet al — apologies but I can’t make the 9am meeting today. Is there anyway to record the meeting? Happy to follow up afterwards asynchronously?

**Mark Robinson** (06:49:29):
> Just to confirm. Benchmarking meeting is tomorrow (Thurs 4th) at 13.00 Zurich time (Baltimore 8.00, Melbourne 23.00, London 12.00). Zoom:[https://uzh.zoom.us/j/65508609136?pwd=ZC8wTUhOeVk3d3N2U3JmV3J2RkhOQT09](https://uzh.zoom.us/j/65508609136?pwd=ZC8wTUhOeVk3d3N2U3JmV3J2RkhOQT09)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C02JX7P0WMS/p1635751865039300?thread_ts=1635751865039300&cid=C02JX7P0WMS)
> Hi all. I didn't get too many :ok_hand: for this "benchmarking focus" meeting (later today) and a couple that couldn't make it, so I'm thinking it's best to postpone .. :one:Tuesday/:two:Wednesday/:three:Thursday Nov 2nd/3rd/4th 13.00 CET could all work for me. Potential clash with @Aedin Culhane's and @Kasper D. Hansen's meeting.

**Luke Zappia** (07:24:07):
> @Luke Zappia has joined the channel

**Shila Ghazanfar** (07:47:33) (in thread):
> hi all, i can meet at 9AM or happy to shift to anytime until 1PM if that’s helpful?@Kasper D. Hansen@Stephanie Hicks@Laurent Gattore recording I can send around a zoom link with recording (first time trying this feature out!)

**Kasper D. Hansen** (07:51:16) (in thread):
> I'm also free this morning

**Kasper D. Hansen** (07:54:20) (in thread):
> Kasper D Hansen is inviting you to a scheduled Zoom meeting.
> 
> Topic: HCA Bioc
> Time: Nov 3, 2021 09:00 AM Eastern Time (US and Canada)
> 
> Join Zoom Meeting[https://jhjhm.zoom.us/j/91531598722?pwd=VDBkanp4b1d1NDZkNGVTQ21Ub1U3dz09](https://jhjhm.zoom.us/j/91531598722?pwd=VDBkanp4b1d1NDZkNGVTQ21Ub1U3dz09)Meeting ID: 915 3159 8722
> Passcode: 139902
> One tap mobile
> +13017158592,,91531598722#,,,,*139902# US (Washington DC)[+16513728299,,91531598722#,,,,*139902#](tel:+16513728299,,91531598722#,,,,*139902#)US (Minnesota)
> 
> Dial by your location[+1 301 715 8592](tel:+1 301 715 8592)US (Washington DC)
>         +1 651 372 8299 US (Minnesota)
>         +1 786 635 1003 US (Miami)[+1 267 831 0333](tel:+1 267 831 0333)US (Philadelphia)[+1 312 626 6799](tel:+1 312 626 6799)US (Chicago)[+1 470 250 9358](tel:+1 470 250 9358)US (Atlanta)[+1 470 381 2552](tel:+1 470 381 2552)US (Atlanta)[+1 646 518 9805](tel:+1 646 518 9805)US (New York)[+1 646 558 8656](tel:+1 646 558 8656)US (New York)[+1 720 928 9299](tel:+1 720 928 9299)US (Denver)[+1 971 247 1195](tel:+1 971 247 1195)US (Portland)[+1 213 338 8477](tel:+1 213 338 8477)US (Los Angeles)[+1 253 215 8782](tel:+1 253 215 8782)US (Tacoma)[+1 346 248 7799](tel:+1 346 248 7799)US (Houston)[+1 602 753 0140](tel:+1 602 753 0140)US (Phoenix)[+1 669 219 2599](tel:+1 669 219 2599)US (San Jose)
>         +1 669 900 9128 US (San Jose)
> Meeting ID: 915 3159 8722
> Passcode: 139902
> Find your local number: https://jhjhm.zoom.us/u/acixA4k2Tb
> 
> Join by SIP[91531598722.139902@zoomcrc.com](mailto:91531598722.139902@zoomcrc.com)Join by H.323
> 162.255.37.11 (US West)
> 162.255.36.11 (US East)
> 115.114.131.7 (India Mumbai)
> 115.114.115.7 (India Hyderabad)
> 213.19.144.110 (Amsterdam Netherlands)
> 213.244.140.110 (Germany)
> 103.122.166.55 (Australia Sydney)
> 103.122.167.55 (Australia Melbourne)
> 64.211.144.160 (Brazil)
> 69.174.57.160 (Canada Toronto)
> 65.39.152.160 (Canada Vancouver)
> 207.226.132.110 (Japan Tokyo)
> 149.137.24.110 (Japan Osaka)
> Meeting ID:[915 3159 8722
> Passcode: 139902](tel:915 3159 8722
> Passcode: 139902)

**Kasper D. Hansen** (07:54:34) (in thread):
> Here is one for 9am.

**Kasper D. Hansen** (07:55:24) (in thread):
> But should we do later@Laurent Gatto,@Stephanie Hicks,@Shila Ghazanfar

**Laurent Gatto** (07:57:39) (in thread):
> in 1 hour works for me

**Kasper D. Hansen** (09:01:10):
> Data Integration zoom now: Kasper D Hansen is inviting you to a scheduled Zoom meeting.
> 
> Topic: HCA Bioc
> Time: Nov 3, 2021 09:00 AM Eastern Time (US and Canada)
> 
> Join Zoom Meeting[https://jhjhm.zoom.us/j/91531598722?pwd=VDBkanp4b1d1NDZkNGVTQ21Ub1U3dz09](https://jhjhm.zoom.us/j/91531598722?pwd=VDBkanp4b1d1NDZkNGVTQ21Ub1U3dz09)Meeting ID: 915 3159 8722
> Passcode: 139902
> One tap mobile[+13017158592](tel:+13017158592),,91531598722#,,,,*139902# US (Washington DC)[+16513728299](tel:+16513728299)[,,91531598722#,,,,*139902#](tel:+16513728299,,91531598722#,,,,*139902#)US (Minnesota)
> 
> Dial by your location
>         +1 301 715 8592 US (Washington DC)
>         +1 651 372 8299 US (Minnesota)
>         +1 786 635 1003 US (Miami)
>         +1 267 831 0333 US (Philadelphia)
>         +1 312 626 6799 US (Chicago)
>         +1 470 250 9358 US (Atlanta)
>         +1 470 381 2552 US (Atlanta)
>         +1 646 518 9805 US (New York)
>         +1 646 558 8656 US (New York)
>         +1 720 928 9299 US (Denver)
>         +1 971 247 1195 US (Portland)
>         +1 213 338 8477 US (Los Angeles)
>         +1 253 215 8782 US (Tacoma)
>         +1 346 248 7799 US (Houston)
>         +1 602 753 0140 US (Phoenix)
>         +1 669 219 2599 US (San Jose)
>         +1 669 900 9128 US (San Jose)
> Meeting ID: 915 3159 8722
> Passcode: 139902
> Find your local number:[https://jhjhm.zoom.us/u/acixA4k2Tb](https://jhjhm.zoom.us/u/acixA4k2Tb)Join by SIP[91531598722.139902@zoomcrc.com](mailto:91531598722.139902@zoomcrc.com)Join by H.323
> 162.255.37.11 (US West)
> 162.255.36.11 (US East)
> 115.114.131.7 (India Mumbai)
> 115.114.115.7 (India Hyderabad)
> 213.19.144.110 (Amsterdam Netherlands)
> 213.244.140.110 (Germany)
> 103.122.166.55 (Australia Sydney)
> 103.122.167.55 (Australia Melbourne)
> 64.211.144.160 (Brazil)
> 69.174.57.160 (Canada Toronto)
> 65.39.152.160 (Canada Vancouver)
> 207.226.132.110 (Japan Tokyo)
> 149.137.24.110 (Japan Osaka)
> Meeting ID: 915 3159 8722 Passcode: 139902


## 2021-11-05

**Mike Smith** (05:19:13) (in thread):
> I've been added to an 30 minute interview panel in our selected timeslot today, but I'll try to join once I'm finished there.

**Davide Risso** (05:29:44):
> A gentle reminder that the Standardized data structures group will meet today at 2pm CET / 9am EST / 1pm GMT.
> Here's a zoom link for the meeting:[https://unipd.zoom.us/j/82115430528](https://unipd.zoom.us/j/82115430528)

**Luke Zappia** (06:16:57) (in thread):
> @Davide RissoWould it be ok if I join in?

**Davide Risso** (06:42:57) (in thread):
> Of course!

**Davide Risso** (06:43:15) (in thread):
> It’s open to anyone who wants to contribute!

**Davide Risso** (06:43:47) (in thread):
> Moreover I already mention you in the notes as someone to potentially contact as a collaborator!:grin:


## 2021-11-06

**Stephanie Hicks** (23:36:44) (in thread):
> hi@Martin Morgan— just confirming. For the meeting on Wednesday, should we have a fleshed out draft of the proposal(s)?

**Stephanie Hicks** (23:38:16) (in thread):
> hi everyone — I’m sorry I missed out on the convo. Would it be OK if I still participate even if it’s async? I’m happy to edit google docs directly or support in anyway that I can.

**Stephanie Hicks** (23:40:01) (in thread):
> hi everyone — I’m sorry I missed out on the convo. Would it be OK if I still participate even if it’s async? I’m happy to edit google docs directly or support in anyway that I can.

**Stephanie Hicks** (23:42:06) (in thread):
> hi@Martin Morgan— would it be possible to make this change for the scalability doc? I’m starting to draft out the proposal and would appreciate it being in comment mode from here on out.

**Stephanie Hicks** (23:43:28) (in thread):
> hi@Mark RobinsonI’m sorry I missed out on the convo. Would it be OK if I still participate even if it’s async? I’m happy to edit google docs directly or support in anyway that I can.


## 2021-11-07

**Mark Robinson** (03:59:40) (in thread):
> hey@Stephanie Hicks.. yes, of course, async is no problem.@Lukas Weberwas on the call. But basically what we tried to do is nail down potential CZI applications and we came up with the 2 that you saw in the google doc (that@Martin Morgansetup) ([https://docs.google.com/document/d/1UhLn-gma6WnjiFx27Uzf3EmdV19K4m7wMWZIX2PX9PA/edit](https://docs.google.com/document/d/1UhLn-gma6WnjiFx27Uzf3EmdV19K4m7wMWZIX2PX9PA/edit)) .. several members are also tied to the other groups, and so nothing set in stone .. and I guess we will all meet on Wednesday (?) with the other groups and discuss how to proceed.

**Davide Risso** (04:01:10) (in thread):
> Hi Stephanie! Of course! Feel free to add your thoughts in the google doc! It’s a bit sparse atm but I plan to have a better write up before our next meeting with the larger group

**Stephanie Hicks** (06:11:21) (in thread):
> Ok thanks!

**Stephanie Hicks** (06:12:06) (in thread):
> Makes sense.

**Stephanie Hicks** (06:12:25) (in thread):
> I’ll add some thoughts directly in the doc.

**Stephanie Hicks** (06:12:44) (in thread):
> Thanks!


## 2021-11-08

**Paula Nieto García** (03:27:33):
> @Paula Nieto García has joined the channel

**Stephanie Hicks** (13:27:39):
> Starting a thread of the scalability proposal

**Stephanie Hicks** (13:30:23) (in thread):
> hi@Davide Risso@Mark Robinson@Kasper D. Hansen— the three you noted your interest in the HCA scalability proposal. If it’s OK with you all, I am going to try and do this async as much as possible. I would love to have other Co-PIs on this proposal so I’m reaching out to gauge your interest. I’ve started to draft the proposal and plan to put a bunch of ideas down in the next two days before we meet. If you have thoughts, I’m happy to take them in the document. I will reach out to my grants admin on Wednesday to start get the ball rolling with the admin stuff. It would be great to know whether or not this is something you (a) are interested in or (b) have the bandwidth for. Thanks!

**Vince Carey** (15:04:16) (in thread):
> @Stephanie Hicksis HDF5 a significant component of your scalability concept?  If so it may be useful to include a component for John Readey of the HDF5 group; I've had some interaction with him lately and he indicated interest.  Let me know if you would be interested in discussing further.

**Stephanie Hicks** (17:50:51) (in thread):
> hi@Vince Carey. The on-disk file formats are significant from the perspective of using them, but my goal is not to further develop them. I assume that’s where@Davide Risso’s proposal would focus on “data infrastructure”.

**Stephanie Hicks** (17:51:35) (in thread):
> My goal would be to propose methods that leverage these file formats. And from that perspective, yes, I will definitely point to John Readey’s work in this area and@Davide Risso’s proposal

**Vince Carey** (17:55:09) (in thread):
> BTW it is not on-disk HDF5 that is of primary interest, but instead the scalable data service HSDS which can do parallelized query resolution.  I'd rather not lead a project in that space as I already have active CZI commitments.

**Stephanie Hicks** (20:36:23) (in thread):
> ah ok, thanks!

**Stephanie Hicks** (23:31:50) (in thread):
> just following up on this. I’ve now got an abstract and a set of two deliverables. I’ll draft the work plan tomorrow.


## 2021-11-09

**Aedin Culhane** (02:11:43) (in thread):
> Slightly off topic but might be interesting r&d folks at NVIDA contacted me keen to do joint research. (They mentioned they did a gatk pipeline at the broad and have a genomics r&d group). They want to set up meeting. Anyone interested ?

**Aedin Culhane** (02:26:14):
> Is everything in Google folder. Trying to catch up. Had another grant  deadline that got in yesterday and missed a few days

**Davide Risso** (04:29:45):
> Hi all, I realized I have a conflict with tomorrow's meeting and will have to leave at 2:30pm my time to teach a class and will miss the second half of the meeting.

**Davide Risso** (04:31:11) (in thread):
> @Stephanie Hicksthe agenda now has a "Minutes" section in which I have filled in a bit of details on our discussion

**Davide Risso** (04:31:23) (in thread):
> feel free to add comments/questions to the doc

**Olly Crook** (07:01:31):
> @Olly Crook has joined the channel

**Stephanie Hicks** (07:33:40) (in thread):
> yep! At least that’s what I’ve been working off of:upside_down_face:

**Aedin Culhane** (09:09:23):
> Can spatial omics leverage existing spatial imaging  experiences. During the CZI EOSS meeting, I connected with guys from 3D slider…[https://www.slicer.org/](https://www.slicer.org/)Let me know if you think this could help
  - Attachment (3D Slicer): [3D Slicer image computing platform](https://www.slicer.org/)
> 3D Slicer is a free, open source and multi-platform software package widely used for medical, biomedical, and related imaging research.

**Kasper D. Hansen** (10:05:26):
> I will also be absent; I have an unavoidable child obligation

**Martin Morgan** (10:40:51):
> <!channel>Reminder for tomorrow’s 8am Eastern meeting, with call information in the pinned post[https://community-bioc.slack.com/archives/C02JX7P0WMS/p1635083522003200](https://community-bioc.slack.com/archives/C02JX7P0WMS/p1635083522003200). Also, the US ended daylight savings time (or did it begin…?) last weekend, so the local time may be different from two weeks ago…
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C02JX7P0WMS/p1635083522003200)
> <!channel> Our next group meeting will be Wednesday November 10 at 8am Eastern to discuss [https://chanzuckerberg.com/rfa/single-cell-data-insights/](https://chanzuckerberg.com/rfa/single-cell-data-insights/). Please take a brief look at the RFA before-hand so that we can strategize about directions, timelines, participation, etc.
> 
> The agenda is at [https://docs.google.com/document/d/1okIX93rq7867YLxKMdLVoK6t5MNQvFUMa00Tlww8A6w/edit?usp=sharing](https://docs.google.com/document/d/1okIX93rq7867YLxKMdLVoK6t5MNQvFUMa00Tlww8A6w/edit?usp=sharing)
> 
> HCA sc Data Insights proposal
> Wednesday, November 10 · 8:00 – 9:00am
> Google Meet joining info
> Video call link: [https://meet.google.com/ajz-jxgg-zzs](https://meet.google.com/ajz-jxgg-zzs)
> Or dial: ‪(US) [+1 650-285-3089](tel:+1650-285-3089)‬ PIN: ‪296 828 473‬#
> More phone numbers: [https://tel.meet/ajz-jxgg-zzs?pin=3514184645744](https://tel.meet/ajz-jxgg-zzs?pin=3514184645744)

**rohitsatyam102** (12:43:03):
> @rohitsatyam102 has joined the channel


## 2021-11-10

**Laurent Gatto** (08:31:40) (in thread):
> @Stephanie HicksIf there's any mention or need for proteomics/mass spec expertise, let me know and I would be happy to contribute.

**Gabriel Hoffman** (11:29:05):
> @Gabriel Hoffman has joined the channel


## 2021-11-11

**Shilpa Garg** (09:28:23):
> @Shilpa Garg has joined the channel


## 2021-11-12

**Shila Ghazanfar** (12:15:47) (in thread):
> hi@Stephanie Hicksi wonder if you’ve thought a bit more re splitting the scalability proposal into Book + scalable spatially-aware clustering, or rather keep as a single proposal?


## 2021-11-15

**Stephanie Hicks** (11:36:13) (in thread):
> @Laurent Gatto— thank you! Will do@Shila Ghazanfar— Apologies for my delayed response. Yes, I plan on separating the two proposals out this week. Are you still interested in collaborating on the scability one?

**Shila Ghazanfar** (11:39:52) (in thread):
> thanks@Stephanie Hicksyes i still am!

**Stephanie Hicks** (11:40:23) (in thread):
> ok, I’ll send you a DM tomorrow to coordinate?

**Shila Ghazanfar** (11:41:37) (in thread):
> yes that’d be great thanks!


## 2021-11-17

**Julia Wrobel** (04:59:14):
> @Julia Wrobel has joined the channel


## 2021-11-18

**Federico Marini** (05:07:55):
> @Federico Marini has joined the channel

**Federico Marini** (05:11:34):
> Joining late to this party, but happy to share a thought out loud -
> I thought this call would be a nice setting to try and establish iSEE as a real portal-like tool/component, with potential connection to other ongoing efforts, among which
> * “our” experimenthub, to browse right away cool datasets
> * the parallel that could come from the SFAIRA project
> Would fit quite nicely IMHO in the interoperability ideas that had been proposed. Is that something that tickles the interest enough?

**Federico Marini** (05:14:45):
> If someone from Fabian Theis’s group is already in here, it would be very useful I guess

**Luke Zappia** (09:29:35) (in thread):
> I’m happy to put you in contact with people.

**Federico Marini** (09:42:54) (in thread):
> Thanks Luke! I know the time is not so much, but probably it is worth a shot


## 2021-11-19

**Wes W** (08:35:13):
> @Wes W has joined the channel


## 2021-11-26

**Mikhael Manurung** (18:28:31):
> @Mikhael Manurung has joined the channel


## 2021-12-02

**Stephanie Hicks** (08:20:56):
> hi all, i just wanted to mention that in the abstract of my application, i’m putting this as the first sentence:
> > “Bioconductor is a widely used open source software community using the R programming language performing leading edge analysis and comprehension of high throughput genomic data.”
> If others would like to use it too, it might help us unify the apps. Happy to take edits on the sentence too.

**Olly Crook** (08:43:59) (in thread):
> Looks really good to me. Might be helpful to be more pedantic with compound adjectives "open-source", "leading-edge", "high-throughput". At first, I was unsure what an edge analysis was ...

**Stephanie Hicks** (12:30:25) (in thread):
> ooh thanks!

**Stephanie Hicks** (12:31:48):
> Could we start a thread to get a sense of how many other bioc apps there will be? I would love to try and coordinate with like adding a sentence above or in some other way. Feel free to leave a message in a thread below. For me, I’m aiming for two proposals.

**Shila Ghazanfar** (17:24:51) (in thread):
> Thanks Stephanie! I’m putting one in for spatial genomics data integration


## 2021-12-03

**Davide Risso** (01:17:34) (in thread):
> Hi Stephanie, I’m submitting one on benchmarking spatial transcriptomics. My aim is to have an abstract ready to share here by the end of the week. I think the obvious place to coordinate is the community statement? Can we come up with some common language for everyone to use? In addition to your opening sentence above which I think is great and I plan to use.

**Stephanie Hicks** (07:07:40) (in thread):
> Great idea@Davide Risso! Do you have a community statement drafted?

**Katharina Imkeller** (07:57:40):
> @Katharina Imkeller has joined the channel

**Davide Risso** (08:55:44) (in thread):
> Not yet...:sweat_smile:

**Katharina Imkeller** (10:03:49) (in thread):
> Hi Stephanie@Federico Mariniand myself will probably submit one. No community statement drafted yet:sweat_smile:

**Martin Morgan** (14:08:01) (in thread):
> In our first CZI / HCA collaboration of a handful of independent applications we had the following paragraph (I’ve updated the numbers to current values…)
> > The volume and rich complexity of the Human Cell Atlas requires sophisticated computational tools for integrative statistical analysis and comprehension.**Bioconductor**is the pre-eminent resource for this purpose.*Bioconductor *consists of 2803*R *‘packages’ for integrative analysis of sequencing, microarray, flow cytometry, and other genomic assays.*Bioconductor *is widely used (>840,000 distinct IP downloads annually) and highly respected (>52,000 PubMedCentral citations).**Bioconductor**has a broad developer community (>1100 maintainers), extensive documentation, active support, and mature software development practices.**Bioconductor**includes important single-cell analysis methods and already supports large datasets (e.g., 10x Genomics 1.3M neuron), although additional work is required in this area. Our*‘Statistical Analysis and Comprehension of the Human Cell Atlas with R / Bioconductor’ *collaboration aims to (1)***provide a coherent programmatic interface to the HCA***and to (2)***enable scalable interactive statistical analysis of single-cell data ***for*Bioconductor *users and developers.
> > 
> > This individual proposal aims to support our community by …


## 2021-12-04

**Stephanie Hicks** (06:40:23) (in thread):
> Oh thank you@Martin Morgan!


## 2021-12-05

**Stephanie Hicks** (09:53:58):
> OK, so if others want to do something similar, this is the first abstract sentence:
> > “Bioconductor is a widely used open-source software community using the R programming language performing leading-edge analysis and comprehension of high-throughput genomic data. With the recent advances of ….”
> This is the first part of the community statement:
> > “The volume and rich complexity of large-scale single-cell data atlases, such as the Human Cell Atlas, requires sophisticated computational tools and resources for reproducible and integrative computational analyses leading to greater insights in health and disease. Bioconductor is the pre-eminent resource for this purpose. Bioconductor consists of 2803 R ‘packages’ for integrative analysis of sequencing, microarray, flow cytometry, and other genomic assays. Bioconductor is widely used (>840,000 distinct IP downloads annually) and highly respected (>52,000 PubMedCentral citations). Bioconductor has a broad developer international community (>1100 maintainers), extensive documentation, active support, and mature software development practices. Furthermore, Biocondcutor is well-integrated with the Seurat and Python communities through tools to leverage Python packages (e.g. reticulate, basilisk) or to convert between data formats (e.g. sceasy, zellkonverter) used in large atlas-scale analyses, which can also be used directly used in interactive data visualization tools for single-cell data (e.g. cellxgene). While Bioconductor collaborative community support is large and well-established, we are committed to contributing to a growing community with collaboration and integration with other projects both within Bioconductor and across CZI Data Insights networks.
> 
> > This individual proposal aims to support these communities by…”

**Stephanie Hicks** (09:54:00):
> thoughts?


## 2021-12-07

**Aedin Culhane** (09:21:45):
> Hi

**Aedin Culhane** (09:26:52):
> Hi I need a co-supervisor for a PhD student who will be working on this project with me.  He just completed is a biomedical engineer who just completed a masters in mathematical modeling.  Would anyone like to volunteer to co-supervisor?  The time-commitment would be minimal, its really just to have a supervisor in case something happens to the supervisor, but we can make it what we want it to be?


## 2021-12-08

**Federico Marini** (11:18:13) (in thread):
> Hi Steph,
> I personally think it is an excellently crafted paragraph - also for the numbers of words used, which would leave a good third of space to the own proposal:slightly_smiling_face:

**Federico Marini** (11:19:07) (in thread):
> Do you want to add iSEE to the example of vis tools for sc dats close to cellxgene - that being already a component of the Bioc ecosystem? (yeah, biased viewpoint here, but hey:smile:)

**Stephanie Hicks** (11:51:51) (in thread):
> oh sure! that works

**Federico Marini** (15:41:29) (in thread):
> On a similar line - do we want/should we have a common DEI statement part as well?


## 2021-12-10

**Federico Marini** (08:40:04):
> A question on the datasets to be mentioned in the CZI proposal:
> Do datasets hosted on EGA count as open & freely available (as the call details specifically mentions)?

**Kasper D. Hansen** (09:10:49):
> I would say its borderline, but it would be weird if it doesn’t. Unless there is some crazy end user agreement.

**Federico Marini** (09:19:14):
> It is open*able* once one has the permission, let’s put it like this. Freely I think it only refers to the no fee needed to access it, right?

**Stephanie Hicks** (09:50:24):
> I would assume EGA is OK

**Davide Risso** (10:19:05):
> That would be my understanding too

**Davide Risso** (10:19:54):
> But I guess it wouldn’t hurt to ask a Program Officer

**Sean Davis** (13:38:09):
> My understanding as well.


## 2021-12-11

**Federico Marini** (06:55:59):
> Thanks everyone for chiming in - guess asking the officers is the safest way, but at least it confirmed my hunch (cc@Katharina Imkeller)


## 2021-12-18

**Ciro Ramírez-Suástegui** (11:33:58):
> @Ciro Ramírez-Suástegui has joined the channel


## 2022-01-03

**Kurt Showmaker** (17:04:14):
> @Kurt Showmaker has joined the channel


## 2022-01-19

**Elisabetta Mereu** (10:29:37):
> @Elisabetta Mereu has joined the channel


## 2022-03-21

**Pedro Sanchez** (05:01:25):
> @Pedro Sanchez has joined the channel


## 2022-06-23

**Stephanie Hicks** (21:09:06):
> the CZI Single-Cell Biology Data Insights Cycle 2 RFA was just announced[https://chanzuckerberg.com/rfa/single-cell-data-insights](https://chanzuckerberg.com/rfa/single-cell-data-insights). Due date is Aug 25
  - Attachment (Chan Zuckerberg Initiative): [New Funding Opportunity for Single-Cell Computational Biology](https://chanzuckerberg.com/rfa/single-cell-data-insights)
> Advancing tools and resources for analyzing single-cell biology datasets to gain greater insights into health and disease.


## 2022-07-07

**Federico Marini** (07:04:32):
> Hi@Stephanie Hicks- thanks for reviving a little the channel.
> I am thinking of putting together a submission for the cycle 2. This would be a focused project (the one with a lower budget).
> I thought to share this here to see
> * if there are others also interested for this round
> * whether we can find some synergies worth mentioning in the proposals
> If enough are interested, we can try to arrange a call where we pitch each other?

**Stephanie Hicks** (07:54:31):
> Thanks@Federico Marini! I plan to submit one (and I did the previous around too). Happy to work with folks here on synergies:smile:

**Federico Marini** (07:55:34):
> Sounds great!
> I would like to focus the work on the annotation process. As in “the boring labeling of cells”.

**Federico Marini** (07:56:23):
> Happy to share more details once I jot the main principles down:slightly_smiling_face:

**Wes W** (13:51:44):
> id be keen to collaborate@Federico Marini

**Federico Marini** (14:20:05):
> Let’s collect some interest here in the coming days and see what can be ideally done then:slightly_smiling_face:Glad to tickle the interest Wes!


## 2022-12-15

**Mercilena Benjamin** (09:38:38):
> @Mercilena Benjamin has joined the channel


## 2023-01-21

**Hien** (16:02:37):
> @Hien has joined the channel


## 2023-03-31

**Ilaria Billato** (08:57:03):
> @Ilaria Billato has joined the channel


## 2023-04-20

**Chris Vanderaa** (04:35:14):
> @Chris Vanderaa has left the channel


## 2023-05-24

**Gabriel Hoffman** (09:08:34):
> @Gabriel Hoffman has left the channel


## 2023-06-19

**Pierre-Paul Axisa** (05:10:56):
> @Pierre-Paul Axisa has joined the channel


## 2023-11-14

**Mark Robinson** (08:39:18):
> hi<!here>.. just wondering, there is another[Data Insights call from CZI](https://chanzuckerberg.com/rfa/single-cell-data-insights/)(due December 5th 2023!) and last time, there was some coordination here in terms of having similar text in the community statements, etc. Is anyone else planning an application for this round and is it worth coordinating?

**Mark Robinson** (08:45:24):
> With a colleague in CH, we were planning something like "end-to-end toolchains for single-cell long-read RNA-seq" (especially with the new PacBio Kinnex released) .. my colleague is an expert in the downstream analyses (e.g.,[functional impact](https://doi.org/10.1093/bioadv/vbad050)); I'm more at the discovery + quant + DE end. Maybe of interest to@Matt Ritchie; not sure who else is into this nowadays. But, my idea here is also to bridge R/Python universes, so not Bioc-specific.

**Mark Robinson** (08:45:51):
> If there is any coordination, please ping me.

**Stephanie Hicks** (10:39:39):
> I’mnot submitting anything this time.


## 2023-11-15

**Stephanie Hicks** (14:41:29):
> hey@Mark Robinson(and anyone else for is thinking about submitting to the Cycle 3) -- I'm at a CZI meeting and Jonah Cool gave a presentation yesterday noting how the "Single Cell Biology" program will be renamed to "CZI Cell Science" soon (unsure not sure when). But I'm attaching a picture of the topics they seem to be most interested in funding. Hope this helps!

**Stephanie Hicks** (14:41:56):
  - File (JPEG): [IMG_0392](https://community-bioc.slack.com/files/U34P8RS3B/F065UGRDS8M/img_0392.jpg)

**Stephanie Hicks** (14:43:35):
> in summary, CZI seems to be very keen on the idea of leveraging the existing cell atlases that they have been generating to extract new biology in new ways

**Mark Robinson** (16:12:16):
> Thanks@Stephanie Hicks.


## 2023-11-21

**Matt Ritchie** (20:33:56) (in thread):
> Sounds like a good idea@Mark Robinson. I am in the process of putting together an EOSSS application along similar lines that I can share with you that covers single-cell and bulk long-read analysis (joint with others from Australia and Singapore). I don’t imagine that will put a spanner in any of the works - I think having people working on this across schemes could be good (there’s plenty to do!)


## 2025-01-09

**Ammar Sabir Cheema** (11:38:19):
> @Ammar Sabir Cheema has joined the channel
