---
title: "#histopathology-image-analysis"
---

## 2025-01-28

**Levi Waldron** (13:23:27):
> @Levi Waldron has joined the channel

**Sehyun Oh** (13:23:34):
> @Sehyun Oh has joined the channel


## 2025-01-29

**Sean Davis** (17:11:08):
> @Sean Davis has joined the channel

**Hervé Pagès** (17:11:08):
> @Hervé Pagès has joined the channel

**Davide Risso** (17:11:08):
> @Davide Risso has joined the channel

**Vince Carey** (17:11:08):
> @Vince Carey has joined the channel

**Lucio Queiroz** (17:12:10):
> @Lucio Queiroz has joined the channel

**Marcel Ramos Pérez** (17:14:04):
> @Marcel Ramos Pérez has joined the channel

**Mohamed Omar** (17:16:20):
> @Mohamed Omar has joined the channel

**Sehyun Oh** (17:16:32):
> Our meeting notes/schedules/link are[HERE](https://docs.google.com/document/d/1AQzizrfpLc3D-S4LacMucMvZeRFBzf65fZ4k1bfizi4/edit?usp=sharing).


## 2025-02-04

**Charlotte Soneson** (00:13:19):
> @Charlotte Soneson has joined the channel

**Chenyue Lu** (01:53:01):
> @Chenyue Lu has joined the channel

**Phil Cheng** (02:46:24):
> @Phil Cheng has joined the channel

**Artür Manukyan** (03:11:27):
> @Artür Manukyan has joined the channel

**Stephanie Hicks** (05:06:01):
> @Stephanie Hicks has joined the channel

**Ilaria Billato** (07:22:07):
> @Ilaria Billato has joined the channel

**chiara romualdi** (07:48:56):
> @chiara romualdi has joined the channel

**Tyrone Lee** (12:22:48):
> @Tyrone Lee has joined the channel

**Ludwig Geistlinger** (13:47:50):
> @Ludwig Geistlinger has joined the channel

**Lukas Weber** (17:04:34):
> @Lukas Weber has joined the channel


## 2025-02-05

**Samuel Gunz** (01:30:14):
> @Samuel Gunz has joined the channel

**Himel Mallick** (02:22:55):
> @Himel Mallick has joined the channel

**Alik Huseynov** (14:05:57):
> @Alik Huseynov has joined the channel


## 2025-02-24

**Alan O'C** (07:13:33):
> @Alan O'C has joined the channel


## 2025-03-19

**Hervé Pagès** (01:01:01):
> Hi all, I'm not feeling well and won't be able to attend our meeting tomorrow. I'll catch up later with MeetGeek.


## 2025-04-15

**USLACKBOT** (15:53:09):
> ***eslam.abousamra32***from***WaldronLab***was added to this channel by***shbrief***. You can review their permissions in Channel Details. Happy collaborating!
