---
title: "#ibt2025-kushcentregroup1"
format: gfm
---

## 2025-04-13

**U08N34ENLGL** (22:04:59):
> @U08N34ENLGL has joined the channel


## 2025-04-14

**U08MXGQ0G6A** (18:54:25):
> @U08MXGQ0G6A has joined the channel

**USLACKBOT** (20:13:11):
> ***alkhansa.ahmed.00***from***Alkhansa***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08N34ENLGL** (20:41:15):
> Dear all,
> I would like to congratulate you once again on being selected as a participant in the AfriGen-D & H3ABioNet Introduction to Bioinformatics Training Course (IBT2025) at the Kush Centre for Genomics and Biomedical Informatics.
> My name is Faisal Mohamed Fadlelmola and I'm a Professor of Health Genomics, Bioinformatics, Information Technology and data science. I have been working as the Principal Investigator of the NIH H3ABioNet Sudan Node from July 2012 to June 2024. Since September 2021, I have been working as the Principal Investigator at the Data Science Initiative Africa Consortium, funded by the NIH representing Sudan.
> I received my first master’s degree in medical molecular biology from the University of Westminster in London, UK, and my second master’s degree in information technology from the University of Sunderland in Sunderland, UK. I also hold a PhD in Human Molecular Genetics and Bioinformatics from the Institute of Human Genetics at the University of Würzburg, Germany (2000-2003). I completed my postdoctoral training at the Centre for Translational and Applied Genomics (CTAG) at the British Columbia Cancer Centre (2004-2006), Vancouver, Canada. I also worked as a research associate at CTAG for two years (2007-2009).
> I was a founding member of the first medical school at the University of Botswana (2009-2011). I was Dean of the Faculty of Computer Science at Future University for almost a year (2011-2012) before being a Visiting Professor at the Asmara College of Health Science for almost two years (2012-2014).
> From July 2014 until the end of 2021, I worked as a collaborating professor with the Faculty of Science at the University of Khartoum, in addition to my work as the principal investigator of the H3ABioNet Sudan Node.
> In March 2022, we established the Kush Centre for Genomics and Biomedical Informatics within the Biotechnology Perspectives Organization (NGO) to maintain the momentum we have achieved through our training courses and work activities within the Sudan Node of the H3ABioNet consortium since July 2012.***Message from your local Kush Centre staff***Ms. Nihad Elsayed, my PhD candidate, will serve as the course coordinator for the Kush Centre class, and I will be the system administrator. I wish you every success and a truly rewarding learning experience that will enhance your skills, add value, and benefit your careers in genomics and bioinformatics for years to come. Your class teaching assistants will introduce themselves later. I encourage you to take full advantage of this complimentary opportunity.
> Regards
> Faisal Mohamed Fadlelmola, PhD, FBCS (UK), FIBMS (UK), CTDP (Canada)
> Professor of Health Genomics, Bioinformatics, Information Technology and Data Science
> Principal Investigator of USA NIH Data Science Initiative Africa Consortium @Sudan Node (September 2021-Present)
> Ex-Principal Investigator of USA NIH H3ABioNet Consortium @Sudan Node (July 2012-June 2024)
> Secretary General of African Society for Bioinformatics and Computational Biology (2020 – present)
> Member of International Society for Computational Biology (2015 – present)
> Director & Founder of the Kush Centre for Genomics & Biomedical Informatics,                                                                           CEO and Founder of Biotechnology Perspectives Organization                                                                                                  Khartoum, 11111, Sudan*                                                                                                                                                                                                       * Currently based in Vancouver, Canada, due to the ongoing war in Sudan.

**USLACKBOT** (21:17:24):
> ***ahmedwdabdon11***from***Ahmed Abdoun***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NHAVC5NV** (21:21:29):
> :wave:Hello, team! Thank for invention Prof fasial


## 2025-04-15

**USLACKBOT** (02:44:05):
> ***israaabdulrahman***from***israaabdulrahman@yahoo.com’s Workspace***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**USLACKBOT** (04:12:14):
> ***muatsimahmed***from***sudan_node@h3abionet_IBT2024***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U06VCDHPSAY** (04:12:14):
> @U06VCDHPSAY has joined the channel

**U08MXGVDG6S** (06:57:56):
> Hello everyone,  thanks for the add prof.

**USLACKBOT** (08:44:39):
> ***thwiiiban.m***from***sudan_node_h3abionet_agmt2023***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**USLACKBOT** (09:10:17):
> ***fatimaemad558***from***sudan_node@h3abionet_IBT2023***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U054R37BZMZ** (09:10:17):
> @U054R37BZMZ has joined the channel

**USLACKBOT** (23:34:00):
> ***abdulrahimsalih123***from***H3ABioNet Sudan Node***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U03P0CD5K0C** (23:35:09):
> hello to all we are glad to join you


## 2025-04-16

**USLACKBOT** (04:21:31):
> ***fatimayousif687***from***H3ABioNet, UofK Node***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U013FGV9V0A** (04:25:11):
> Hello everyone, thanks for inventions prof fasial

**USLACKBOT** (06:47:45):
> Buay James Hoth Reath made updates to a canvas tab:[canvas content]

**USLACKBOT** (14:25:44):
> ***nesreen.alsanousi***from***nesreen.alsanousi@gmail.com’s Workspace***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**USLACKBOT** (14:38:11):
> ***nesreen.alsanousi@gmail.com’s Workspace***has removed themselves from this channel.

**USLACKBOT** (14:47:01):
> ***mohamedahmed***from***Aims***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08N8QSRN22** (14:47:01):
> @U08N8QSRN22 has joined the channel

**U08N8QSRN22** (14:47:46):
> Hi all, can we make a WhatsApp group?

**U08N382REPP** (16:01:10):
> Hello everyone, thanks prof, Faisal for the invitation.

**U08N382REPP** (16:01:34):
> Excited to be here and looking forward to some great conversations with all of you.


## 2025-04-17

**USLACKBOT** (20:08:44):
> ***yousofm1989***from***IBT2025@kush_centre***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08P70LSG3A** (20:09:28):
> :wave:Hello, team!

**USLACKBOT** (23:48:47):
> ***yousratagelsirahmed***from***yoya***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NUQ666NM** (23:48:48):
> @U08NUQ666NM has joined the channel


## 2025-04-18

**USLACKBOT** (00:20:08):
> ***sumayahasan***from***UAEU***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08MS8EKN1M** (00:20:08):
> @U08MS8EKN1M has joined the channel

**USLACKBOT** (02:21:45):
> ***zahraabdelmagid***from***zahraabdelmagid@gmail.com’s workspace***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**USLACKBOT** (05:05:46):
> ***mmotalab707***from***Moha909***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**USLACKBOT** (05:15:59):
> ***thebioinformation***from***Waleed I. A.  Khalil***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NH5SDGG6** (05:33:23):
> :wave:Hello, team! Thanks for adding

**USLACKBOT** (06:57:56):
> ***moutavet***from***Moutavet***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NABN7Y76** (06:57:56):
> @U08NABN7Y76 has joined the channel

**USLACKBOT** (07:46:57):
> ***hibamusa2010***from***IBT2025@kush_centre***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08MYCR3H62** (07:46:57):
> @U08MYCR3H62 has joined the channel

**USLACKBOT** (09:18:53):
> ***hamdan.mohammed1843***from***CBSB_IBT_Course_2021_Class***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U028EURKAU8** (09:18:53):
> @U028EURKAU8 has joined the channel

**USLACKBOT** (13:27:03):
> ***hamza.313***from***hamza.313@hotmail.com’s workspace***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NC7F2UKH** (13:41:44):
> Hello everyone, it's a great pleasure to be with you all. Wish you the best at this course:pray:

**USLACKBOT** (20:50:49):
> ***nadirabuzeid***from***OlU***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NRU24TK7** (20:50:49):
> @U08NRU24TK7 has joined the channel


## 2025-04-21

**U08MXGWTCUW** (01:46:12) (in thread):
> This is my number.. +966 54 647 1961

**U08N34ENLGL** (11:50:33):
> Dear All,

**U08N34ENLGL** (11:50:37):
> IBT2025 Class at Kush Centre for Genomics & Biomedical Informatics, Sudan is inviting you to a scheduled Zoom meeting.
> Topic: IBT2025 Local Sessions with TAs @Kush Centre!
> Time: Apr 22, 2025 10:30 AM Khartoum
>        Every week on Tue, Thu, until Jul 15, 2025, 25 occurrence(s)
> Please download and import the following iCalendar (.ics) files to your calendar system.
> Weekly:[https://us02web.zoom.us/meeting/tZEudOGppzIuHtWs76dDqdLKjN2AVFNyTMQ5/ics?icsToken=DDNAzIo6BdMId5NIWQAALAAAACusoMN39e_uBy_mS20nqWtexSd-jQ9IZEWihUX6UPB0Q9bavCDnLvsrntyRF-Bs1Iy9r3ZuQVgKLy-YuzAwMDAwMQ&meetingMasterEventId=xiskJfBtRSaXKMbtNRw1JQ](https://us02web.zoom.us/meeting/tZEudOGppzIuHtWs76dDqdLKjN2AVFNyTMQ5/ics?icsToken=DDNAzIo6BdMId5NIWQAALAAAACusoMN39e_uBy_mS20nqWtexSd-jQ9IZEWihUX6UPB0Q9bavCDnLvsrntyRF-Bs1Iy9r3ZuQVgKLy-YuzAwMDAwMQ&meetingMasterEventId=xiskJfBtRSaXKMbtNRw1JQ)Join Zoom Meeting[https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1](https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1)Meeting ID: 853 3819 9441
> Passcode: 612203

**U08N34ENLGL** (19:55:25):
> 10:30am Khartoum time = 10:30am CAT (Central Africa Time).


## 2025-04-22

**U08N3821H8D** (05:46:33) (in thread):
> [+8613125828073](tel:+8613125828073)

**U08N3821H8D** (06:07:53) (in thread):
> [https://chat.whatsapp.com/CjBVWHGOGNPCGiwqSMGgcb](https://chat.whatsapp.com/CjBVWHGOGNPCGiwqSMGgcb)You can join the Whatsapp group
  - Attachment (WhatsApp.com): [IBT2025](https://chat.whatsapp.com/CjBVWHGOGNPCGiwqSMGgcb)
> WhatsApp Group Invite

**U08NUQ666NM** (06:13:25):
> I think our session will be from 1:50_2:30 pm in Khartoum time

**U08N37X4FRB** (06:19:45):
> In my email is say from 1:00_2:00 pm

**U08MXGQ0G6A** (06:49:21):
> Dear Participant,
> 
> Here are a few things to take note of:
> 1. The IBT session will be hosted twice a week as stipulated on the course schedule.
> * To access the schedule, click on******Resources******* > *******Documentation******
> 2. We have released the training materials you will need for sessions 1 and 2.
> * Day plan
> * Lecture slides
> * Lecture videos
> * Assignment (session 2 only)
> 3. For each session, this is what you are required to do:
> * Check the day plan. Navigate to******Resources******* *>******Day plan ****to obtain the day plan.
> * Watch videos designated for that session. Session videos have been made available on the******Lecture Videos******tab
> * To access lecture slides and additional materials, please navigate to******Resources. ****Click on the folder designated for that week or module.
> * All assignments***must***be submitted on the******Assignments******tab before the deadline.***We will not accept assignments submitted to our email. ***
> * After each session, there will be a Q&A session with the trainer.
> 
>   * Check the classroom sign-in schedule for the Q&A session, which can be found on******Resources******>******Documentation******
>   * To attend the Q&A session, please register on this link:[https://zoom.us/meeting/register/dfin2nU9RVqz2cevAD_sMg](https://zoom.us/meeting/register/dfin2nU9RVqz2cevAD_sMg).
>   * Q&A sessions will be******recorded******and made available on Vula.
>   * If a trainer is unable to attend a Q&A session, please paste your question on the******Discussion ****tab, and trainers will respond.
>   * If you have a technical or an admin-related query, please use the******Discussion ****tab.***We will not attend to queries sent to our email (*****unless you have issues with activating your Vula account******)****
> 4. Test/quiz/assessment
> * The participant orientation week will not have a test/quiz/assessment
> * Modules 1-6 will have a***compulsory ***test/quiz/assessment. To access the test/quiz/assessment, please click on the******Tests & Quizzes******tab
> We hope that you enjoy the course.
> Regards
> On behalf of the IBT core team

**U08N3831QCD** (07:57:53) (in thread):
> Me too, but if you look at the day plans or schedule you will see Sudan is listed with the countries starting at 13:50

**U08N3831QCD** (07:58:30) (in thread):
> I think since it is the same link for all of us we just have to look at our classroom and enter at the right time by ourselves!

**USLACKBOT** (08:11:30):
> ***huda.baharana***from***huda.baharana@gmail.com’s Workspace***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NABNAV6H** (08:11:30):
> @U08NABNAV6H has joined the channel

**U08N3831QCD** (08:17:43) (in thread):
> Here
  - File (JPEG): [Screenshot_20250422_141627.jpg](https://ibt2025kushcentre.slack.com/files/U34P8RS3B/F08P8TJPC0J/screenshot_20250422_141627.jpg)

**U08N37X4FRB** (08:36:26) (in thread):
> OK thanks

**USLACKBOT** (08:37:39):
> ***neem14a***from***community-bioc***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08NRU24TK7** (08:39:42):
> You are welcome


## 2025-04-23

**USLACKBOT** (05:41:26):
> ***rahma.elmahdi***from***AEGIS***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**U08PENJ4HV2** (05:41:27):
> @U08PENJ4HV2 has joined the channel

**Welcome message** (05:46:01):
> Hi, everyone! Please welcome<@U08PENJ4HV2>! Here’s a little bit about them, in their own words:
> * ***Role: ***Researcher
> * ***Pronouns: ***She/Her
> * ***Current project: ***
> phage immunoprecipitation sequencing for viral antibody detection.
> * ***Location: ***
> Copenhagen, Denmark
> * ***Bio: ***
> Medial doctor by training, epidemiologist by trade. Bioinformatics novice.
> * ***Fun fact: ***
> I practice yoga and meditation.

**USLACKBOT** (10:39:38):
> ***AEGIS***has removed themselves from this channel.

**USLACKBOT** (10:39:39):
> ***AEGIS***has removed themselves from this channel.

**USLACKBOT** (10:39:43):
> ***AEGIS***has removed themselves from this channel.

**USLACKBOT** (10:39:44):
> ***AEGIS***has removed themselves from this channel.

**USLACKBOT** (10:39:45):
> ***AEGIS***has removed themselves from this channel.

**USLACKBOT** (10:39:48):
> ***AEGIS***has removed themselves from this channel.


## 2025-04-24

**U08N3831QCD** (07:17:18):
> I have a question
> 
> What sessions are Obligatory?
> 
> We asked Sindi in the Q/A Session and she said it is not Mandatory!
> 
> Unless we have questions you can attend them!

**U08MXGQ0G6A** (11:06:28) (in thread):
> Hi<@U08N3831QCD>***If you would like to officially pass the course and obtain a letter of completion, you must:***
> * Attend all live sessions (in cases where it is impossible to do so you must inform the TAs for your classroom).
> * Submit 90% of practical assignments by the relevant hand-in dates (one practical assignment per contact session for Module 1-6, excluding consolidation sessions).
> * Submit assessments by the relevant hand-in dates and obtain a minimum grade of 60% overall for the assessments (one assessment per Module).

**U08N3831QCD** (11:22:57) (in thread):
> Thank you for your assistance and support, Dr. Fathi Ismael.
> 
> I would like to clarify whether you are referring to a Q&A session.
> 
> 
> During our meeting on Tuesday, Dr. Sindi mentioned that participation in this session is not mandatory unless there are specific questions.
> 
> 
> I also wanted to bring to your attention that we are currently experiencing prolonged electricity outages, which have persisted since yesterday. This situation may hinder my ability to fully engage in live sessions.
> 
> Please rest assured that I am committed to completing the assignments and assessments on time. 
> 
> I appreciate your understanding and am grateful for your clear communication.

**U08MXGQ0G6A** (12:12:35) (in thread):
> The Q/A Session is not mandatory, But it is very important to meet familiar trainers as well as the participants’ interaction with interesting topics in the sessions will explain a lot of information more clearly.
> We understand the situation in Sudan due to conflict, please try to attend the Q/A Session

**U08N3831QCD** (12:23:02) (in thread):
> I will do my best to attend!
> 
> 
> Thanks a lot, Dr. Fathi, I appreciate your support!

**U08MXGQ0G6A** (16:35:04) (in thread):
> Good luck<@U08N3831QCD>


## 2025-04-25

**U08NABN7Y76** (15:11:32):
> Dear all
> I am receiving messages from Sindi in email about assignment but when I log to my Vula account there is nothing there what would be the problem?????


## 2025-04-26

**U08NABN7Y76** (06:26:05):
> I am sorry I had a bad experience no body answer your queries and even a bad constructed site at vula is unsatisfactory and non professional and treat people as soldiers and not learner that why I am withdrawing from the course

**U08N382PGDT** (09:42:29):
> Hello, I would like to inquire about the attendance. Where can I attend from? Is it necessary to attend the Q&A session even if I don't have a question? And do we have a local class meeting or a specific meeting for our group?


## 2025-04-27

**U08MXGQ0G6A** (11:52:19) (in thread):
> In vula site, please navigate to***Assignments***tab and click on required***assignment to download.***After resolved the assignment you can**** Submit**it easy on***Assignments***tab.
> any queries related to the assignments or technical challenges, please use the**** Discussions forum**.

**U08MXGQ0G6A** (12:36:19) (in thread):
> Q/A Session is not mandatory, but it is very important to meet familiar trainers as well as the participants’ interaction with interesting topics in the sessions will explain a lot of information more clearly.***like to officially pass the course and obtain a letter of completion, you must:***Attending the local Session is obligatory (in cases where it is impossible to do so you must inform the TAs for your classroom).
> 
> Submit 90% of practical assignments by the relevant hand-in dates (one practical assignment per contact session for Module 1-6, excluding consolidation sessions).
> 
> Submit assessments by the relevant hand-in dates and obtain a minimum grade of 60% overall for the assessments (one assessment per Module).
> 
> The***IBT local Sessions with TAs***will be hosted twice a week from 10:30 a.m. to 14:30 Khartoum local time via  Zoom meeting on Tuesdays and Thursdays, until Jul on (******you can find the colander and link in Slack******)

**USLACKBOT** (17:04:37):
> ***khansaahamid573***from***Alkhansaa Hamid***was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!

**USLACKBOT** (23:38:25):
> ***sh.fadlalla***from****#ibt2025-kushcentregroup1**was added to this channel by***faisalfadl***. You can review their permissions in Channel details. Happy collaborating!


## 2025-04-28

**U08N8QSRN22** (05:30:04):
> Please regard this message. Where can I find the link???
> 
> The***IBT local Sessions with TAs***will be hosted twice a week from 10:30 a.m. to 14:30 Khartoum local time via  Zoom meeting on Tuesdays and Thursdays, until Jul on (******you can find the colander and link in Slack******)

**U08N8QSRN22** (05:35:23):
> Please, it's my first time seeing the following message for that. Could you please count my attendance from the upcoming week? Also, I can not find the iCalendar; I received the attached message.
> 
> IBT2025 Class at Kush Centre for Genomics & Biomedical Informatics, Sudan is inviting you to a scheduled Zoom meeting.
> Topic: IBT2025 Local Sessions with TAs @Kush Centre!
> Time: Apr 22, 2025 10:30 AM Khartoum
>        Every week on Tue, Thu, until Jul 15, 2025, 25 occurrence(s)
> Please download and import the following iCalendar (.ics) files to your calendar system.
> Weekly:[https://us02web.zoom.us/meeting/tZEudOGppzIuHtWs76dDqdLKjN2AVFNyTMQ5/ics?icsToken=DDNAzIo6BdMId5NIWQAALAAAACusoMN39e_uBy_mS20nqWtexSd-jQ9IZEWihUX6UPB0Q9bavCDnLvsrntyRF-Bs1Iy9r3ZuQVgKLy-YuzAwMDAwMQ&meetingMasterEventId=xiskJfBtRSaXKMbtNRw1JQ](https://us02web.zoom.us/meeting/tZEudOGppzIuHtWs76dDqdLKjN2AVFNyTMQ5/ics?icsToken=DDNAzIo6BdMId5NIWQAALAAAACusoMN39e_uBy_mS20nqWtexSd-jQ9IZEWihUX6UPB0Q9bavCDnLvsrntyRF-Bs1Iy9r3ZuQVgKLy-YuzAwMDAwMQ&meetingMasterEventId=xiskJfBtRSaXKMbtNRw1JQ)Join Zoom Meeting[https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1](https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1)Meeting ID: 853 3819 9441
> Passcode: 612203 (edited)
  - File (PNG): [image.png](https://aims-ycw9637.slack.com/files/U34P8RS3B/F08Q22N0WN7/image.png)

**U08N3831QCD** (08:25:32):
> ***Update on Current Circumstances***Dear Facilitators, 
> 
> I hope this message finds you well. I wanted to reach out to share some challenges we've been facing in al-Gezira state due to***ongoing electricity cuts***that have***persisted***for about four days now.
> 
> 
> These power outages have made it quite***difficult for us to manage our time effectively.***I've even attempted to charge my phone at the mosque, but there are many others in the same situation, which limits access. 
> 
> 
> Given these circumstances,***attending live sessions has become a significant challenge for me.***I am***committed to doing my best to stay engaged***and catch up on any missed content.
> 
> Thank you for your understanding, and I appreciate your support during this time.
> 
> Wishing you all the best!
> 
> 
> Kind regards,
> Abdelrahim Dafalla,

**U08N3831QCD** (08:27:48):
> I will try to do my best to complete the assignments and assessments on time!

**U08MXGWTCUW** (08:51:05) (in thread):
> Dear participants,
> 
> What each and everyone of you is experiencing might be challenging and overwhelming to some extent. Just know that we are all in this together doing our best for you to be part of this opportunity. So, try to reach out whenever you are having a trouble and DO NOT DROP OUT and as prof.Faisal always says "try to make the most out of this course" .

**U08MXGWTCUW** (08:51:13) (in thread):
> <@U08NABN7Y76>

**U08MXGWTCUW** (08:51:46) (in thread):
> <@U08N3831QCD>

**U08MXGWTCUW** (08:52:01) (in thread):
> @all

**U08N3831QCD** (10:09:47) (in thread):
> I appreciate your support!
> 
> 
> I will not drop out of the course since it is a great opportunity, and I have been accepted, so I will not waste it!
> 
> 
> I will do my best to complete all the assignments and assessments for sure!:+1:

**Tasneem Awad** (11:28:28) (in thread):
> "Hello, how can I attend the live-streamed lectures? I missed the first lecture. Is there a recording available?

**U08PGEJ1XAT** (14:16:34):
> :wave:Hello, team!
> I hope everyone  well, and am happy joining  this group. 
> I have same situation of abdelrahim , in north state  no electricity,and it's so difficult to attending live  but I will do my best to catch up. 
> 
> Regards 
> Shaza


## 2025-04-29

**U08N8QSRN22** (07:39:26) (in thread):
> Please, no one reply to me why?

**U08N8QSRN22** (07:40:27):
> Even I can not see the Calendar

**U08MXGQ0G6A** (10:54:33) (in thread):
> Every week on Tue, Thu, until Jul 15, 2025, 25 occurrence(s)
> Please download and import the following iCalendar (.ics) files to your calendar system.
> Weekly:[https://us02web.zoom.us/meeting/tZEudOGppzIuHtWs76dDqdLKjN2AVFNyTMQ5/ics?icsToken=DDNAzIo6BdMId5NIWQAALAAAACusoMN39e_uBy_mS20nqWtexSd-jQ9IZEWihUX6UPB0Q9bavCDnLvsrntyRF-Bs1Iy9r3ZuQVgKLy-YuzAwMDAwMQ&meetingMasterEventId=xiskJfBtRSaXKMbtNRw1JQ](https://us02web.zoom.us/meeting/tZEudOGppzIuHtWs76dDqdLKjN2AVFNyTMQ5/ics?icsToken=DDNAzIo6BdMId5NIWQAALAAAACusoMN39e_uBy_mS20nqWtexSd-jQ9IZEWihUX6UPB0Q9bavCDnLvsrntyRF-Bs1Iy9r3ZuQVgKLy-YuzAwMDAwMQ&meetingMasterEventId=xiskJfBtRSaXKMbtNRw1JQ)Join Zoom Meeting[https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1](https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1)Meeting ID: 853 3819 9441
> Passcode: 612203


## 2025-05-01

**U08MXGQ0G6A** (04:39:47):
> Please join to local session via link[https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1](https://us02web.zoom.us/j/85338199441?pwd=9sMbWfbrNNm6RLbgngHMhLHidqPDig.1)

**Welcome message** (06:51:36):
> Hi, everyone! Please welcome<@U08PZHJKBM0>! Here’s a little bit about them, in their own words:
> * ***Role: ***Participant
> * ***Pronouns: ***She
> * ***Current project: ***
> Medical Laboratory Technologist
> * ***Location: ***
> Khartoum, Sudan
> * ***Bio: ***
> I have a background in Medical Laboratory Sciences with specialization in Hisopathology and Cytology. I'm passionate about improving healthcare through diagnostics research.
> * ***Fun fact: ***
> I enjoy learning New languages.
