# Instructions

1. Download [convert.py](https://github.com/waldronlab/community-bioc-archive/blob/devel/convert.py) (written by Gemini 2.5 Pro (Experimental))
and place it in the same directory as the unzipped Slack export.

2. Convert Slack export to quarto files:


```bash
% python convert.py
# (note: path to Slack export directory must not contain spaces)
Enter the path to the main Slack export directory (default: '.'): 

Enter the directory to save Markdown files (default: 'quarto_export'):
```

3. Run (although `--no-execute` seems to be useless):

`quarto render --no-execute`

4. Push and enable GitHub Pages from docs/ directory

# Full list of channels

- [#accessible-vis](accessible-vis.qmd)
- [#alpha-missense](alpha-missense.qmd)
- [#annotation-roadmap](annotation-roadmap.qmd)
- [#anvil](anvil.qmd)
- [#arm-linux](arm-linux.qmd)
- [#artifactdb](artifactdb.qmd)
- [#beginners_and_schools](beginners_and_schools.qmd)
- [#bigdata-rep](bigdata-rep.qmd)
- [#bioc-builds](bioc-builds.qmd)
- [#bioc-conference-everyone](bioc-conference-everyone.qmd)
- [#bioc-conference-noncompeting](bioc-conference-noncompeting.qmd)
- [#bioc-conference-sponsorship](bioc-conference-sponsorship.qmd)
- [#bioc-conference-web](bioc-conference-web.qmd)
- [#bioc-connect](bioc-connect.qmd)
- [#bioc2018](bioc2018.qmd)
- [#bioc2018-workshops](bioc2018-workshops.qmd)
- [#bioc2019](bioc2019.qmd)
- [#bioc2020](bioc2020.qmd)
- [#bioc2020-bioconductor-100_introduction-to-bioconductor-annotation-resources](bioc2020-bioconductor-100_introduction-to-bioconductor-annotation-resources.qmd)
- [#bioc2020-bof-10sr](bioc2020-bof-10sr.qmd)
- [#bioc2020-workshops](bioc2020-workshops.qmd)
- [#bioc2021](bioc2021.qmd)
- [#bioc2022](bioc2022.qmd)
- [#bioc2024](bioc2024.qmd)
- [#bioc2u](bioc2u.qmd)
- [#bioc_africa](bioc_africa.qmd)
- [#bioc_git](bioc_git.qmd)
- [#biocasia](biocasia.qmd)
- [#biocasia2020](biocasia2020.qmd)
- [#biocasia2021](biocasia2021.qmd)
- [#biocasia2022](biocasia2022.qmd)
- [#biocasia2023](biocasia2023.qmd)
- [#biocbooks](biocbooks.qmd)
- [#biocchallenges](biocchallenges.qmd)
- [#bioccheck-a-thon](bioccheck-a-thon.qmd)
- [#biocclasses](biocclasses.qmd)
- [#biochubs](biochubs.qmd)
- [#biocpython](biocpython.qmd)
- [#biocverse](biocverse.qmd)
- [#biocwebsite](biocwebsite.qmd)
- [#biocworkshops](biocworkshops.qmd)
- [#bugsigdb](bugsigdb.qmd)
- [#calendar-events](calendar-events.qmd)
- [#cancer-related](cancer-related.qmd)
- [#cancerdata](cancerdata.qmd)
- [#carpentries](carpentries.qmd)
- [#cbioportal-data-r](cbioportal-data-r.qmd)
- [#channel-requests](channel-requests.qmd)
- [#clinical](clinical.qmd)
- [#cloud-github-actions-subgroup](cloud-github-actions-subgroup.qmd)
- [#cloud-working-group](cloud-working-group.qmd)
- [#community-advisory-board](community-advisory-board.qmd)
- [#containers](containers.qmd)
- [#cool-vis](cool-vis.qmd)
- [#covid19](covid19.qmd)
- [#cpp](cpp.qmd)
- [#csama2023](csama2023.qmd)
- [#cyto-spec-book](cyto-spec-book.qmd)
- [#database](database.qmd)
- [#delayed_array](delayed_array.qmd)
- [#developers-forum](developers-forum.qmd)
- [#developers-mentorship](developers-mentorship.qmd)
- [#diversebioc](diversebioc.qmd)
- [#documentation-translation](documentation-translation.qmd)
- [#easylift](easylift.qmd)
- [#easyplot](easyplot.qmd)
- [#edam-collaboration](edam-collaboration.qmd)
- [#education-and-training](education-and-training.qmd)
- [#elixir](elixir.qmd)
- [#eurobioc-conference-everyone](eurobioc-conference-everyone.qmd)
- [#eurobioc2019](eurobioc2019.qmd)
- [#eurobioc2020](eurobioc2020.qmd)
- [#eurobioc2020-chairs](eurobioc2020-chairs.qmd)
- [#eurobioc2020-isee-transcripts](eurobioc2020-isee-transcripts.qmd)
- [#events](events.qmd)
- [#FC:F05M79CU2HW:Canvas](FCF05M79CU2HWCanvas.qmd)
- [#FC:F05URJ0P021:Welcome material](FCF05URJ0P021Welcome_material.qmd)
- [#funding](funding.qmd)
- [#genai-bioc](genai-bioc.qmd)
- [#general](general.qmd)
- [#gitdevtest](gitdevtest.qmd)
- [#github-actions](github-actions.qmd)
- [#gpus](gpus.qmd)
- [#gseabase](gseabase.qmd)
- [#gwas-data](gwas-data.qmd)
- [#hacktoberfest](hacktoberfest.qmd)
- [#hash-multi-species](hash-multi-species.qmd)
- [#hca-data-insights](hca-data-insights.qmd)
- [#hca_clustering](hca_clustering.qmd)
- [#hca_rfa](hca_rfa.qmd)
- [#histopathology-image-analysis](histopathology-image-analysis.qmd)
- [#hubmapr](hubmapr.qmd)
- [#humble-brag](humble-brag.qmd)
- [#ibt2025-kushcentregroup1](ibt2025-kushcentregroup1.qmd)
- [#image-analysis](image-analysis.qmd)
- [#industry](industry.qmd)
- [#introductions](introductions.qmd)
- [#isee](isee.qmd)
- [#ismb-osca](ismb-osca.qmd)
- [#jobs](jobs.qmd)
- [#llms-for-bioc](llms-for-bioc.qmd)
- [#long-read-study-group](long-read-study-group.qmd)
- [#longread](longread.qmd)
- [#m](m.qmd)
- [#machine-learning](machine-learning.qmd)
- [#mae-discussion](mae-discussion.qmd)
- [#mae-updates](mae-updates.qmd)
- [#mass-spectrometry](mass-spectrometry.qmd)
- [#meetups](meetups.qmd)
- [#mentorship_program_microstasis](mentorship_program_microstasis.qmd)
- [#metabolomics](metabolomics.qmd)
- [#miaverse](miaverse.qmd)
- [#miaverse-admins](miaverse-admins.qmd)
- [#microbiome_experiment_bioc2021](microbiome_experiment_bioc2021.qmd)
- [#microbiome_metagenome](microbiome_metagenome.qmd)
- [#microsoft-azure-collaboration](microsoft-azure-collaboration.qmd)
- [#molevolvr](molevolvr.qmd)
- [#multiomics](multiomics.qmd)
- [#new_packages](new_packages.qmd)
- [#nullranges](nullranges.qmd)
- [#oma-developers](oma-developers.qmd)
- [#omicidx](omicidx.qmd)
- [#osca-book](osca-book.qmd)
- [#osca-book-club](osca-book-club.qmd)
- [#other-distros](other-distros.qmd)
- [#outreachy](outreachy.qmd)
- [#package-submission](package-submission.qmd)
- [#package_submissions](package_submissions.qmd)
- [#palmtree](palmtree.qmd)
- [#pangenome](pangenome.qmd)
- [#papersandpreprints](papersandpreprints.qmd)
- [#pharmacogenomics](pharmacogenomics.qmd)
- [#proteomics](proteomics.qmd)
- [#queer-bioc](queer-bioc.qmd)
- [#r-ladies](r-ladies.qmd)
- [#r7](r7.qmd)
- [#raggedexperiment](raggedexperiment.qmd)
- [#random](random.qmd)
- [#rcwl](rcwl.qmd)
- [#reproducibility](reproducibility.qmd)
- [#rhdf5client](rhdf5client.qmd)
- [#rowdatafix](rowdatafix.qmd)
- [#salmon2bioc](salmon2bioc.qmd)
- [#sc-batch-correction](sc-batch-correction.qmd)
- [#sc-repertoires](sc-repertoires.qmd)
- [#sc-signature](sc-signature.qmd)
- [#sc-velocity](sc-velocity.qmd)
- [#scalability](scalability.qmd)
- [#shiny](shiny.qmd)
- [#singlecell-queries](singlecell-queries.qmd)
- [#singlecellexperiment](singlecellexperiment.qmd)
- [#singularity](singularity.qmd)
- [#social-media](social-media.qmd)
- [#spatial](spatial.qmd)
- [#spatial-interoperability](spatial-interoperability.qmd)
- [#spatialdata-devel](spatialdata-devel.qmd)
- [#spatialexperiment](spatialexperiment.qmd)
- [#spatialexperiment-devel](spatialexperiment-devel.qmd)
- [#sticker_joy](sticker_joy.qmd)
- [#support-site](support-site.qmd)
- [#sweave2rmd](sweave2rmd.qmd)
- [#tab_polls](tab_polls.qmd)
- [#tech-advisory-board](tech-advisory-board.qmd)
- [#terra](terra.qmd)
- [#tess-integration](tess-integration.qmd)
- [#tidiness_in_bioc](tidiness_in_bioc.qmd)
- [#translation-fr](translation-fr.qmd)
- [#tree-like-se](tree-like-se.qmd)
- [#voyager](voyager.qmd)
- [#wasm](wasm.qmd)
- [#workflows](workflows.qmd)
- [#zarr](zarr.qmd)
