---
title: "#industry"
---

## 2022-08-11

**Nicole Ortogero** (21:49:27):
> @Nicole Ortogero has joined the channel


## 2022-08-19

**Snehal Wani** (10:07:10):
> @Snehal Wani has joined the channel


## 2022-09-15

**Xiuwen Zheng** (00:50:08):
> @Xiuwen Zheng has joined the channel

**Snehal Wani** (19:07:56):
> We are having meeting tonight! Very excited!!

**Nicole Ortogero** (19:23:44):
> Yes, cant wait to talk with everyone soon!


## 2022-09-16

**Aedin Culhane** (04:13:24):
> @Aedin Culhane has joined the channel

**Aedin Culhane** (04:14:20):
> @Laurent Gattospoke at EuroBioc about licensing. It's also of interest to@Nicole Ortogero… just connecting you

**Maria Doyle** (04:15:22):
> @Maria Doyle has joined the channel

**Laurent Gatto** (04:15:22):
> @Laurent Gatto has joined the channel

**Aaron Lun** (04:15:22):
> @Aaron Lun has joined the channel

**Michael Lawrence** (04:16:58):
> @Michael Lawrence has joined the channel

**Laurent Gatto** (04:18:24) (in thread):
> Thank you Aedin - I am by no means an expert, but happy to discuss.

**Aedin Culhane** (04:19:31):
> set the channel topic: Group for Bioconductor users and developers who work in industry or non academic settings. Aligned to industry working group

**Aedin Culhane** (04:19:33):
> set the channel description: Group for Bioconductor users and developers who work in industry or non academic settings. Aligned to industry working group

**Kozo Nishida** (04:40:52):
> @Kozo Nishida has joined the channel

**Koen Van den Berge** (04:42:00):
> @Koen Van den Berge has joined the channel

**Lluís Revilla** (05:42:43):
> @Lluís Revilla has joined the channel

**Sowmya Parthiban** (07:48:49):
> @Sowmya Parthiban has joined the channel

**Spencer Nystrom** (07:50:04):
> @Spencer Nystrom has joined the channel

**Dirk Eddelbuettel** (08:16:21):
> @Dirk Eddelbuettel has joined the channel

**Frederick Tan** (08:24:58):
> @Frederick Tan has joined the channel

**Vince Carey** (08:51:10):
> @Vince Carey has joined the channel

**Stephany Orjuela** (09:11:13):
> @Stephany Orjuela has joined the channel

**Gurpreet Kaur** (09:39:51):
> @Gurpreet Kaur has joined the channel

**Ali Quidwai** (10:25:21):
> @Ali Quidwai has joined the channel

**kipper fletez-brant** (11:58:35):
> @kipper fletez-brant has joined the channel

**Sean Davis** (12:09:07):
> @Sean Davis has joined the channel

**Nicole Ortogero** (12:23:46) (in thread):
> Hi@Laurent Gatto. We just had our first meeting yesterday, and this was one of the topics that was brought up for future discussion. If you are interested in joining the working group and helping with this topic, let me know and I'll add you to the members list.

**Laurent Gatto** (13:06:35) (in thread):
> Ni@Nicole Ortogero- I'm not sure if I have much to contribute with regard to the general industry topic, but happy to participate in licensing discussions.

**Nicole Ortogero** (13:07:39) (in thread):
> Ok I will let whomever takes this discussion topic on that you are interested in contributing. Thank you!

**Laurent Gatto** (13:07:59) (in thread):
> Thanks!

**Athena Chen** (13:10:54):
> @Athena Chen has joined the channel

**Steve Lianoglou** (15:26:57):
> @Steve Lianoglou has joined the channel

**Garth Kong** (16:42:26):
> @Garth Kong has joined the channel


## 2022-09-17

**Tyrone Chen** (01:31:09):
> @Tyrone Chen has joined the channel

**Valentina Lorenzi** (12:17:53):
> @Valentina Lorenzi has joined the channel

**ImranF** (12:35:26):
> @ImranF has joined the channel


## 2022-09-18

**Olly Crook** (12:26:12):
> @Olly Crook has joined the channel


## 2022-09-19

**Chris Vanderaa** (04:14:57):
> @Chris Vanderaa has joined the channel

**Nick** (04:29:32):
> @Nick has joined the channel

**Juan Moriano** (08:34:24):
> @Juan Moriano has joined the channel

**Wancen Mu** (10:33:25):
> @Wancen Mu has joined the channel

**Abhijeet Sonawane** (13:51:41):
> @Abhijeet Sonawane has joined the channel

**Raphael Gottardo** (14:47:25):
> @Raphael Gottardo has joined the channel

**Anna Quaglieri (she/her)** (23:51:25):
> @Anna Quaglieri (she/her) has joined the channel


## 2022-09-22

**Anne-Maud Ferreira** (15:04:35):
> @Anne-Maud Ferreira has joined the channel


## 2022-09-23

**Theresa Alexander** (10:52:47):
> @Theresa Alexander has joined the channel

**ChiaSin** (12:03:20):
> @ChiaSin has joined the channel

**Krithika Bhuvanesh** (14:16:31):
> @Krithika Bhuvanesh has joined the channel


## 2022-09-26

**Russ Bainer** (16:45:14):
> @Russ Bainer has joined the channel

**Ino de Bruijn** (17:44:24):
> @Ino de Bruijn has joined the channel


## 2022-09-27

**Jennifer Holmes** (16:09:32):
> @Jennifer Holmes has joined the channel


## 2022-09-29

**Mikie Phan** (07:54:03):
> @Mikie Phan has joined the channel


## 2022-10-15

**Aedin Culhane** (10:57:26):
> @Nicole OrtogeroHave you any update on the article/blog on software licences that you were writing. We are doing a review of the licences in Bioconductor.  Your info on licensing will be really useful. When is your next industry working group and I can present at it


## 2022-10-17

**Nicole Ortogero** (14:30:35):
> Hi@Aedin CulhaneWe haven't had a dedicated discussion on this topic yet. I will forward our next meeting (Thursday) invite to you. 
> Thanks,
> Nicole


## 2022-10-18

**Vince Carey** (06:29:51):
> One quick comment on licenses -- we have applied for membership in the NumFocus organization.  A condition for membership is that all software packages in the project are under OSI-approved licenses.

**Vince Carey** (06:30:20):
> OSI = Open Source Initiative[https://opensource.org/licenses](https://opensource.org/licenses)


## 2022-10-23

**Charlotte Soneson** (03:41:18):
> @Charlotte Soneson has joined the channel


## 2022-10-31

**Chenyue Lu** (10:04:56):
> @Chenyue Lu has joined the channel


## 2022-11-04

**Aedin Culhane** (06:31:58):
> @Nicole Ortogero@Charlotte SonesonCharlotte’s code that examines all of the licences in Bioconductor is at[https://csoneson.github.io/bioc_pkg_licenses/bioc_pkg_licenses.html](https://csoneson.github.io/bioc_pkg_licenses/bioc_pkg_licenses.html).   She also shared the following links that might be useful with the TAB. These maybe useful for the review article/blog that Dave is writing. (Is Dave Henderson on slack.. couldn’t find his id to @). Charlotte might be a great person to include in this project
> * OSI licenses:[https://opensource.org/licenses/alphabetical](https://opensource.org/licenses/alphabetical)
> * Another list of free software licenses:[https://www.gnu.org/licenses/license-list.html](https://www.gnu.org/licenses/license-list.html)
> * [Bioc pkgs with only 'file LICENSE'](https://docs.google.com/spreadsheets/d/11rvP8FvxmLHWgyQgcgBp3Y_LGre14mmzYFf1dDGWkuA/edit?usp=sharing)
> [FAQ on 'non-commercial use'](https://opensource.org/faq#commercial)

**Laurent Gatto** (07:20:00) (in thread):
> Here's an important extract from the contributions book:
> > Licenses restricting use, e.g., to academic or non-profit researchers, are not suitable for Bioconductor.

**Laurent Gatto** (07:21:18) (in thread):
> I also recently learnt about the`License_is_FOSS`and`License_restricts_use`fields in the DESCRIPTION file (see[https://cran.r-project.org/doc/manuals/R-exts.html#Licensing](https://cran.r-project.org/doc/manuals/R-exts.html#Licensing)).
  - Attachment (cran.r-project.org): [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#Licensing)
> Writing R Extensions


## 2022-11-06

**Aedin Culhane** (18:24:30):
> R in Pharma. Free online conference this week[https://hopin.com/events/r-pharma-2022/registration](https://hopin.com/events/r-pharma-2022/registration)
  - Attachment (hopin.com): [R/Pharma 2022](https://hopin.com/events/r-pharma-2022/registration)
> Get tickets to R/Pharma 2022 virtual conference, taking place Nov 8-10, 2022.


## 2022-11-21

**Aedin Culhane** (08:32:20) (in thread):
> @Charlotte Sonesonexpanded her licence report[https://csoneson.github.io/bioc_pkg_licenses/bioc_pkg_licenses.html](https://csoneson.github.io/bioc_pkg_licenses/bioc_pkg_licenses.html)

**Maria Doyle** (09:01:44):
> Webinar that may be of interest to this group[https://www.addevent.com/event/Kq14516694](https://www.addevent.com/event/Kq14516694)
  - Attachment (addevent.com): [R at AstraZeneca: upskilling our workforce through education, experience, and exposure](https://www.addevent.com/event/Kq14516694)
> Join us on November 29th at 12PM EST to hear Gabriella Rustici & Guillaume Desachy share their experience about the R journey AstraZeneca is currently on.The use of R continues to become more and more important at AstraZeneca. It is a true paradigm shift that we have embarked on! This shift has required upskilling our workforce to make them proficient R users. To do so, we are leveraging the 3Es of learning: education, experience and exposure. Learn more about their team's Data Science Educational Program and how the team at AstraZeneca has built their own strong community of R users - where learning takes place through experience and exposure.  Speaker bios:Gabriella is Data Science Learning Senior Director in Astrazeneca’s R&D Data Science & AI where she is responsible for developing a strategy for, and creating a centralised approach to, data science learning for R&D. Gabriella completed her PhD at the Wellcome Sanger Institute and previously run bioinformatics training programs at the University of Cambridge and the European Bioinformatics Institute, in the UK. She is passionate about designing, implementing and evaluating effective and scalable solutions to educate scientists and data science practitioners at all career stages.Guillaume is passionate about helping bring new medicines to patients by leveraging the power of statistics and precision medicine. Since October 2020, he has been doing so at AstraZeneca where he works as a Statistical Science [Director.In](http://Director.In) addition, since March 2022, he have been leading a team of 15 collaborators focusing on building the community of R users at AstraZeneca, called R @ AZ.


## 2022-12-07

**Thiago Britto-Borges** (09:30:02):
> @Thiago Britto-Borges has joined the channel


## 2022-12-14

**Lijia Yu** (19:40:58):
> @Lijia Yu has joined the channel


## 2022-12-15

**Nicole Ortogero** (22:34:45):
> @Aedin Culhanethe industry group reviewed the license notes from Charlotte. We agree that licenses with edits disallowing any commercial use are too restrictive, but we wondering if we could allow clauses that restrict sale or proceeds from products that include the package. I'm sure there are official wordings for this and we will look into that, but does this sound like an acceptable clause that can be made to a license?


## 2022-12-16

**Laurent Gatto** (00:49:09):
> I think any changes to Bioc package licensing terms should first get discussed and would need to officially approved by the advisory boards.

**Charlotte Soneson** (01:51:03) (in thread):
> Not a lawyer obviously, but my reading of the[OSI FAQ](https://opensource.org/faq#commercial)would be that also restricting sales would not be compliant:
> ```
> Can Open Source software be used for commercial purposes?
> Absolutely. All Open Source software can be used for commercial purpose; the Open Source Definition guarantees this. You can even sell Open Source software.
> 
> However, note that commercial is not the same as proprietary. If you receive software under an Open Source license, you can always use that software for commercial purposes, but that doesn't always mean you can place further restrictions on people who receive the software from you. In particular, copyleft-style Open Source licenses require that, in at least some cases, when you distribute the software, you must do so under the same license you received it under.
> 
> Can I restrict how people use an Open Source licensed program?
> No. The freedom to use the program for any purpose is part of the Open Source Definition. Open source licenses do not discriminate against fields of endeavor.
> ```


## 2022-12-20

**David Henderson** (14:27:02):
> @David Henderson has joined the channel


## 2022-12-26

**Aedin Culhane** (08:24:21) (in thread):
> @Maria Doyledo you know?


## 2023-01-04

**Domenick Braccia** (13:58:26):
> @Domenick Braccia has joined the channel


## 2023-01-16

**Thomas Sandmann** (23:35:50):
> @Thomas Sandmann has joined the channel


## 2023-01-21

**Hien** (16:02:48):
> @Hien has joined the channel


## 2023-02-01

**Chiaowen Joyce Hsiao** (16:30:41):
> @Chiaowen Joyce Hsiao has joined the channel


## 2023-02-02

**Yogesh Lakhotia** (02:24:23):
> @Yogesh Lakhotia has joined the channel


## 2023-02-22

**michaelkleymn** (01:48:38):
> @michaelkleymn has joined the channel


## 2023-02-28

**Ramin** (15:30:53):
> @Ramin has joined the channel


## 2023-05-16

**Nitesh Turaga** (17:24:22):
> @Nitesh Turaga has joined the channel

**Nitesh Turaga** (17:24:22):
> Hello!


## 2023-06-12

**Natasha** (10:51:30):
> @Natasha has joined the channel


## 2023-08-03

**Ritika Giri** (15:58:15):
> @Ritika Giri has joined the channel


## 2023-08-04

**Trisha Timpug** (09:35:37):
> @Trisha Timpug has joined the channel

**Andrew McDavid** (12:51:36):
> @Andrew McDavid has joined the channel

**Aedin Culhane** (13:46:36):
> @Ed Lauzierconnecting you to industry group

**Ed Lauzier** (13:46:41):
> @Ed Lauzier has joined the channel


## 2023-09-21

**Philippine Louail** (16:39:48):
> @Philippine Louail has joined the channel


## 2024-08-12

**Erick Navarro** (14:55:15):
> @Erick Navarro has joined the channel


## 2024-10-23

**Sounkou Mahamane Toure** (11:49:08):
> @Sounkou Mahamane Toure has joined the channel


## 2024-11-07

**Malvika Kharbanda** (22:10:47):
> @Malvika Kharbanda has joined the channel


## 2025-03-18

**Nicolo** (17:30:24):
> @Nicolo has joined the channel


## 2025-03-25

**Leo Lahti** (06:11:02):
> @Leo Lahti has joined the channel

**Tuomas Borman** (07:34:07):
> @Tuomas Borman has joined the channel
