---
title: "#ismb-osca"
format: gfm
---


## 2023-03-13

*13:55:26 - @Ludwig Geistlinger has joined the channel*
**Ludwig Geistlinger** (13:55:27):
> set the channel description: OSCA tutorial at the ISMB 2023

*13:56:12 - @Davide Risso has joined the channel*
*13:56:12 - @Vince Carey has joined the channel*
*13:56:12 - @Alex Mahmoud has joined the channel*
*13:56:12 - @Sean Davis has joined the channel*
*13:56:12 - @Marcel Ramos Pérez has joined the channel*
*13:56:12 - @Dario Righelli has joined the channel*
*13:56:12 - @Ilaria Billato has joined the channel*
**Ludwig Geistlinger** (14:00:21):
> Hi folks - we wanted to get started on planning the OSCA tutorial for the ISMB 2023. It would be good if we could all come together and discuss setup and divide responsibilities for the individual sessions among us. Davide and I were thinking to meet March 30, 9 AM - 10 AM EST (3 PM - 4 PM CET). Would this work or do folks have difficulties with this slot?

**Ludwig Geistlinger** (14:00:44):
> Here is the original proposal as submitted together with some annotations and action items:[https://docs.google.com/document/d/1xLiohdkqHHloNphFyyv2QvYIV99Fa-NljXAPbfiO0f0/edit?usp=sharing](https://docs.google.com/document/d/1xLiohdkqHHloNphFyyv2QvYIV99Fa-NljXAPbfiO0f0/edit?usp=sharing)

**Vince Carey** (17:02:48):
> Adding@Alex Mahmoudwho is handling[workshop.bioconductor.org](http://workshop.bioconductor.org)

**Alex Mahmoud** (17:42:30) (in thread):
> March 30th works for me


## 2023-03-14

**Dario Righelli** (04:40:16) (in thread):
> ok

**Ludwig Geistlinger** (12:44:35) (in thread):
> Great - how does this slot look for you@Marcel Ramos Pérez?

**Marcel Ramos Pérez** (12:45:08) (in thread):
> That works for me

**Ludwig Geistlinger** (13:36:44) (in thread):
> @Davide Risso- looks like the slot works for everyone and we can send out an invitation

**Ludwig Geistlinger** (16:20:33):
> @Sean DavisI have included you in the call, not sure whether you can make it, but we wanted to primarily understand whether we could maybe ask for a bit of help to also host the ISMB workshop on the orchestra platform

**Sean Davis** (16:46:26) (in thread):
> Happy to. The alternative is to use@Alex Mahmoud's galaxy-based system and I see he is also on the call.

**Ludwig Geistlinger** (17:05:54) (in thread):
> Great thank you, much appreciated! Yes the idea is to use Alex' system but maybe have the Orchestra one as a backup in case things break unexpectedly shortly before the conference ...


## 2023-03-16

*12:29:49 - @Stefania Pirrotta has joined the channel*

## 2023-03-30

**Ludwig Geistlinger** (10:25:20):
> Hi@Dario Righelliand@Davide Risso: thanks to@Marcel Ramos Pérezthe github repo is now here:[https://github.com/Bioconductor/ISMB.OSCA](https://github.com/Bioconductor/ISMB.OSCA)

**Ludwig Geistlinger** (10:26:03):
> The four of us can push to that repo ... Davide let us know if you would like to add additional contributors eg the github usernames of Ilaria and Stefania


## 2023-04-12

**Ludwig Geistlinger** (18:12:17):
> Hi@Dario Righelli@Marcel Ramos Pérez@Davide Risso: I have fleshed out the github repo a bit more by putting some info into`README`and`DESCRIPTION`. Also there are now placeholder vignettes for all six sessions in the`vignettes`subfolder, so everyone can start adding their contents to the corresponding vignettes. Also the`pkgdown`site is up under:[https://bioconductor.github.io/ISMB.OSCA/](https://bioconductor.github.io/ISMB.OSCA/)listing the placeholder vignettes in the`Vignettes`dropdown.


## 2023-04-13

**Dario Righelli** (03:24:57):
> Thanks@Ludwig GeistlingerI already started a vignette on the multisample section, I’ll merge the things after our meeting:slightly_smiling_face:

**Ilaria Billato** (09:53:29):
> @Marcel Ramos Pérezmy username on GitHub is billila, thanks

**Stefania Pirrotta** (09:53:55):
> @Marcel Ramos Pérezmy username is SPirrotta


## 2023-05-23

**Ludwig Geistlinger** (08:38:57):
> Hi@Davide Risso@Dario Righelli@Marcel Ramos Pérez- I have a conflict on Thursday at our usual time. Any chance we can move the meeting to either one hour earlier (8 AM US East Coast, 2 PM Italy) or one hour later (10 AM US East Coast, 4 PM Italy)?

**Dario Righelli** (08:40:17):
> no problem for me in both cases

**Davide Risso** (08:42:26):
> I have another meeting at 2pm our time, let me try to reschedule it and get back to you

**Davide Risso** (10:17:49):
> Ok, I was able to move my other meeting, 2pm works for me

**Ludwig Geistlinger** (10:30:01):
> Ok great going to move the meeting


## 2023-05-25

**Marcel Ramos Pérez** (18:01:13):
> It looks like`MouseGastrulationData`should be available in devel now[https://bioconductor.org/checkResults/devel/data-experiment-LATEST/MouseGastrulationData/](https://bioconductor.org/checkResults/devel/data-experiment-LATEST/MouseGastrulationData/)

**Ludwig Geistlinger** (19:10:29):
> Ok - great, rerunning the GHA now indeed finds the package


## 2023-06-08

**Ludwig Geistlinger** (09:00:58):
> Sorry I am in transit and will be a little bit delayed

**Davide Risso** (09:04:47):
> no worries

**Ludwig Geistlinger** (09:07:47):
> Alright coming online

**Marcel Ramos Pérez** (09:38:10):
> I've created the`billila-devel`branch. You can checkout with
> ```
> git checkout -b billila-devel origin/billila-devel
> ```
> (after doing a`git fetch --all`)


## 2023-06-10

**Ludwig Geistlinger** (05:29:18):
> Hi@Davide Risso- just a heads up that my slides are now up on your ISMB2023 slides gdrive folder


## 2023-06-22

**Davide Risso** (09:07:08):
> @Ludwig Geistlingerdo we have our meeting today? We're in your waiting room...

**Davide Risso** (09:07:35):
> If you can't make it no worries! I think we don't have much to discuss and could reschedule or simply skip this week's meeting

**Ludwig Geistlinger** (09:09:24):
> Sorry another meeting was running over, be right there

**Ludwig Geistlinger** (09:09:34):
> A quick check in will be good

**Marcel Ramos Pérez** (13:58:17):
> It looks like our steps in GHA update the website when pushing to a non-devel branch. I can go ahead and fix that. We may want to use stricter updating of the website by only updating it when there is a difference in the`DESCRIPTION`file, e.g., version bump***or***a change in the`.yml`file

**Ludwig Geistlinger** (14:02:44):
> Where would we configure that?

**Marcel Ramos Pérez** (14:03:35):
> I am doing it in the`basic_checks.yaml`

**Marcel Ramos Pérez** (14:03:53):
> I'll push shortly

**Marcel Ramos Pérez** (15:10:46):
> You can see the changes here:[https://github.com/Bioconductor/ISMB.OSCA/pull/13](https://github.com/Bioconductor/ISMB.OSCA/pull/13)


## 2023-06-29

**Ludwig Geistlinger** (05:35:01):
> @Dario Righelli@Marcel Ramos Pérez@Davide Risso: a little reminder for us to finalize contents on the repo, so that@Ilaria Billatoand@Stefania Pirrottacan test drive the materials over the course of next week.


## 2023-07-06

**Ludwig Geistlinger** (15:28:32):
> Hi@Dario Righelli@Marcel Ramos Pérez@Davide Rissothe github page and docker image has built successfully. Can you give it another quick check whether you want to add anything else and give me a quick thumbs up:+1:once you are ready and we can inform Alex to incorporate into Bioc workshops?

**Ludwig Geistlinger** (16:50:37):
> @Davide Rissoslides updated on the gdrive folder that you shared before


## 2023-07-07

**Dario Righelli** (03:37:31):
> Is it ok if I put a ToC in the vignette?
> I saw that there is no ToC in the others, but I think it could be useful

**Davide Risso** (07:17:52):
> Idon’thave a particular preference, butlet’sstay consistent.I.e. either all vignettes with or all without TOC

**Davide Risso** (08:12:06):
> Actually, I do see a table of content in each vignette (see screenshot below)
  - File (PNG): [Screen Shot 2023-07-07 at 14.11.51.png](https://community-bioc.slack.com/files/U34P8RS3B/F05FZPY65H9/screen_shot_2023-07-07_at_14.11.51.png)

**Davide Risso** (08:12:42):
> BTW I am fixing a couple of issues in my and Dario's vignettes (only text), I will push soon-ish to devel

**Dario Righelli** (10:07:50):
> I created a new branch to check if my new sampling on the cells builds… 500 was too small and brought to some inconsistencies in the results

**Ludwig Geistlinger** (12:35:00):
> @Davide Rissojust a heads-up that you need to bump the version number in the`DESCRIPTION`file if you want to trigger a new build ...

**Marcel Ramos Pérez** (15:22:19):
> Should I start submitting the workshop to[workshop-contributions](https://github.com/Bioconductor/workshop-contributions)?

**Davide Risso** (15:53:59):
> Perhaps we can wait until we merge the open PR?


## 2023-07-09

**Dario Righelli** (05:00:03):
> I just checked all the changes and the checks on the new PR, everything is ok, so I merged it into the devel.
> Sorry for the delay!


## 2023-07-10

**Davide Risso** (05:04:23):
> @Marcel Ramos PérezI think we are now ready to submit to workshop-contributions!

**Davide Risso** (09:54:47):
> FYI from the ISMB website:
> * [Tutorial IP4: Orchestrating Large-Scale Single-Cell Analysis with Bioconductor](https://www.iscb.org/ismbeccb2023-programme/tutorials#ip4)(SOLD OUT)
  - Attachment (iscb.org): [Tutorials](https://www.iscb.org/ismbeccb2023-programme/tutorials#ip4)
    > ISCB - International Society for Computational Biology

**Marcel Ramos Pérez** (17:27:50):
> [https://github.com/Bioconductor/workshop-contributions/issues/35](https://github.com/Bioconductor/workshop-contributions/issues/35):crossed_fingers:

**Marcel Ramos Pérez** (17:30:59) (in thread):
> FWIW, I wrote a little shiny app (using Dean Attali's[tutorial](https://deanattali.com/2015/06/14/mimicking-google-form-shiny/)) but currently a lot of it is manual. I will add more checks and automation for more general use:[https://github.com/LiNk-NY/BiocWorkshopSubmit](https://github.com/LiNk-NY/BiocWorkshopSubmit)

**Ludwig Geistlinger** (17:53:53):
> Nice! One thing that I wanted to understand is whether developments on the ISMB.OSCA repo can continue and will continuously be integrated? Or will the request build the current snapshot and we will need to open a new issue if we wanted to update the workshop on[https://workshop.bioconductor.org/](https://workshop.bioconductor.org/)?

**Ludwig Geistlinger** (17:55:15):
> (I assume the docker container being fairly stable going forward, but I could imagine some further polishing on the text, ie changes to the github page)

**Marcel Ramos Pérez** (18:30:48) (in thread):
> That's a good question. I'm not sure.@Alex Mahmoudshould know.

**Alex Mahmoud** (18:34:21) (in thread):
> We can use the latest tag on the container, and I can set the pull policy on the cluster to always pull latest image. Running instances will not update, but new launches would pull the newer image when the GHA passes and the container image rebuilds

**Ludwig Geistlinger** (18:39:40) (in thread):
> Ok great, let's do that


## 2023-07-11

**Marcel Ramos Pérez** (11:40:31):
> Our workshop is now live at[https://workshop.bioconductor.org/](https://workshop.bioconductor.org/)! Thanks@Alex Mahmoud

**Alex Mahmoud** (11:41:23):
> Np. What date is the workshop? (To know when I should scale up the cluster)

**Marcel Ramos Pérez** (11:42:29):
> July 23rd from 3 AM to 12 PM EDT

**Ludwig Geistlinger** (11:57:01):
> Cool! Thanks@Alex Mahmoud- any concerns with having 30-40 people concurrently trying to spin up the workshop?

**Alex Mahmoud** (11:57:51):
> Shouldn't be an issue. What is minimum RAM you'd think each needs?

**Ludwig Geistlinger** (11:58:30):
> We have worked on github runners with 4 GB, which was quite limiting. If we could get 8 GB or 16 GB we would be better off.

**Alex Mahmoud** (12:05:48):
> How about 4GB guaranteed, 10GB limit per person?

**Davide Risso** (12:24:49):
> I think that would work. As@Ludwig Geistlingersaid the vignettes are running with 4GB so having that guaranteed is good. The workshop is sold out so we should expect 30 people + at least one of us to be running the workshop at any given time

**Davide Risso** (12:25:31):
> And yes, thank you@Alex Mahmoudand@Marcel Ramos Pérezfor deploying the workshop!

**Davide Risso** (12:26:46):
> @Ilaria Billato@Stefania Pirrottacan you try this out to make sure everything works as expected?
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C04UE0D23K2/p1689090031898289)
    > Our workshop is now live at [https://workshop.bioconductor.org/](https://workshop.bioconductor.org/)! Thanks @Alex Mahmoud


## 2023-07-12

**Dario Righelli** (04:30:22):
> thanks everyone!


## 2023-07-13

**Ludwig Geistlinger** (15:25:48):
> Hi@Sean Davisour ISMB OSCA tutorial seems to work beautifully in the new[https://workshop.bioconductor.org/](https://workshop.bioconductor.org/)galaxy environment (Thanks a lot@Alex Mahmoud)! Just wondering whether we could maybe ask you to also include the tutorial on the orchestra platform? The repo is[here](https://github.com/Bioconductor/ISMB.OSCA)and the docker container is[here](http://ghcr.io/bioconductor/ismb.osca). Thanks!


## 2023-07-17

**Davide Risso** (08:55:08):
> Important info for our tutorial:
> > Sunday, July 23  9:00 – 18:00 CEST 
> Room: Salle Rhône 3B (Level 1)  
> 
> This in-person tutorial will be held at the[Centre de Congrès de Lyon](https://www.ccc-lyon.com/)located at: 50 Quai Charles de Gaulle. Lunch will be provided for this tutorial.
> You need to pick up your name badge at the conference registration desk prior to the tutorial. The registration desk is located in the Terreaux Hall, located on ground level. You can find registration desk hours and a map showing the access to the venue at:[https://www.iscb.org/ismbeccb2023-general-info/faq#registration](https://www.iscb.org/ismbeccb2023-general-info/faq#registration)
  - Attachment (ccc-lyon.com): [Centre Congrès de Lyon, organiser événementiel et conference - Organisation Congres en France](https://www.ccc-lyon.com/)
    > Centre de congrès de Lyon. Organisation de conventions, de congrès, de séminaires, de salons, de réunions à la Cité Internationale.
  - Attachment (iscb.org): [FAQ](https://www.iscb.org/ismbeccb2023-general-info/faq#registration)
    > ISCB - International Society for Computational Biology


## 2023-07-20

**Davide Risso** (08:50:20):
> <!here>are we meeting today? I'm running a bit late, but please start without me if we are indeed meeting

**Ludwig Geistlinger** (08:58:43):
> I think we have all the materials ready, but I think it will be good to just shortly clarify on the organization + see whether there are any questions with the setup

**Ludwig Geistlinger** (09:00:11):
> let's start 5 minutes after the full hour

**Ludwig Geistlinger** (09:09:38):
> @Dario Righelli@Marcel Ramos Pérezare you joining?

**Ludwig Geistlinger** (09:19:43):
> Meeting time on Sunday: 8 AM at the registration desk


## 2023-07-23

**Ludwig Geistlinger** (01:19:32):
> Bonjour mesdames et messieurs!:fr:

**Ludwig Geistlinger** (01:19:49):
> On my way to the conferencevenue

**Davide Risso** (01:39:06):
> Me too… but I needed a croissant stop!:wink:
  - File (JPEG): [IMG_3041](https://community-bioc.slack.com/files/U34P8RS3B/F05K0KPTCN4/img_3041.jpg)

**Ludwig Geistlinger** (01:55:54):
> Registered and Arrived in Salle Rhone 3B (Level 1)

**Ludwig Geistlinger** (02:32:16):
> Panel: Spatial Data Panel: Challenges, Lessons, Best Practices
> Room: Salle Rhone 2
> Format: Live from venue
> 
> Moderator(s): Alberto Riva
> Hua Li
> Meeta Mistry
> Jenny Drnevich, University of Illinois Urbana-Champaign, United States of America
> Ellis Patrick
> Ayushi Agrawal, The J. David Gladstone Institutes, United States of America
> 
>  Presentation Overview: Hide
> Panel topics may include:
>  - current challenges with spatial data
>  - platform pros and cons or experiences
>  - best practices or things that worked
>  - tools for data analysis, integration, visualization
>  - strategies for finding time/resources to spend on development of new approaches

**Ludwig Geistlinger** (02:33:28):
> Monday, July 24, 2:30-3 PM (have to double-check the time)

**Dario Righelli** (04:17:39):
  - File (JPEG): [IMG_1011](https://community-bioc.slack.com/files/U34P8RS3B/F05JPN6R857/img_1011.jpg)


## 2023-07-28

*15:57:47 - @Benjamin Yang has joined the channel*

## 2023-07-29

**Marcel Ramos Pérez** (09:57:47):
> BTW@Ludwig Geistlinger@Dario Righellihere is the`plotly::toWebGL`example which makes rendering many points in a browser much faster[https://mtmorgan.github.io/HCABiocTraining/articles/d-objects.html](https://mtmorgan.github.io/HCABiocTraining/articles/d-objects.html)

**Dario Righelli** (09:58:22) (in thread):
> nice, thanks marcel!

**Ludwig Geistlinger** (09:59:19) (in thread):
> Great thanks Marcel!

**Dario Righelli** (09:59:43) (in thread):
> everything ok with your flights guys?

**Ludwig Geistlinger** (10:01:06) (in thread):
> Yes I arrived yesterday night in Boston, had an hour delay in departing from Munich but otherwise fine. Sounded like Marcel had some more troubles. How about you?

**Dario Righelli** (10:01:52) (in thread):
> Everything went smooth for me, it was a direct flight with no delay

**Dario Righelli** (10:02:27) (in thread):
> An hour delay could be a lot on an oversea trip…:disappointed:

**Marcel Ramos Pérez** (10:05:05) (in thread):
> I had issues with delayed flights and US customs haha I had about a 19 hour travel time door to door but it was a great experience in France overall:smile:

**Dario Righelli** (10:06:50) (in thread):
> In the end I’m happy you are fine and at home guys!
> It was great to meet in person, work and chat of science (and not) with both of you!

**Dario Righelli** (10:07:08) (in thread):
> let’s do that at least once a year!:joy:

**Ludwig Geistlinger** (10:10:18) (in thread):
> Yesit’sbeen a great week!


## 2023-09-12

**Marcel Ramos Pérez** (11:09:13):
> We would like to test GPU capabilities on AnVIL and maybe even replicate the results from Ilaria's poster. Have you made your code public Ilaria?@Ilaria Billato@Davide Risso

**Davide Risso** (11:29:38):
> Not yet, I think. Butthere’sno reason weshouldn’t…I’m meeting with Ilaria tomorrow, we’ll get back shortly after


## 2023-09-13

**Marcel Ramos Pérez** (13:58:43):
> Thanks Davide! cc:@Vince Carey


## 2023-09-14

**Davide Risso** (10:48:32):
> @Vince Carey@Marcel Ramos Pérezhere’sthe link:[https://github.com/billila/spca](https://github.com/billila/spca)


## 2023-10-30

**Dario Righelli** (11:38:20):
> Hey everyone, I’m organizing a workshop on single cell data analysis in my own city (Napoli - IT) at a local conference and I’d like to adapt the code we used for the ISMB workshop.
> What do you think if I fork the workshop and adapt it on my github?
> Would it be a good idea to rename the bioconductor repo from`ISMB.OSCA`to a more generic name like`Bioc.OSCA.Workshop`?
> In case all of you agree, would it be possible to use the cloud to let 30 people use it to run the tutorial?
> Thanks in advice for any feedback on this!

**Ludwig Geistlinger** (11:41:52):
> Great idea to re-use and further spread the word! I can take care of the renaming, you might want to ping@Alex Mahmoudand@Vince Careyas to whether bioc cloud resources under the galaxy framework can be used.

**Marcel Ramos Pérez** (11:53:04):
> Hi Dario,@Dario Righellithat’s great! Once your fork has a working Docker / GH container via GHA, you can use the[Bioconductor/BiocWorkshopSubmit](https://github.com/bioconductor/biocworkshopsubmit)app to create a submission with the details. Let me know how it goes and feel free to open issues / questions at the repo if there are any. I will work on getting a`README.md`up

**Dario Righelli** (11:58:06):
> thanks !

**Marcel Ramos Pérez** (15:01:32) (in thread):
> The`README.md`is up now[https://github.com/Bioconductor/BiocWorkshopSubmit](https://github.com/Bioconductor/BiocWorkshopSubmit)

**Dario Righelli** (16:42:07) (in thread):
> nice, thanks again


## 2024-05-03

**Ludwig Geistlinger** (13:39:47):
> Hi<!channel>just a heads up that we are making good progress in translating our ISMB OSCA tutorial into a carpentries-compatible Bioc education module here:[https://ccb-hms.github.io/osca-workbench/](https://ccb-hms.github.io/osca-workbench/)

**Ludwig Geistlinger** (13:40:58):
> One question@Dario Righelli@Davide Risso: do you happen to have the solutions for the exercises spelled out eg in Rmarkdown files for your sessions, ie the intro lesson, the EDA lesson@Davide Risso, and the multi-sample lesson@Dario Righelli?

**Dario Righelli** (15:35:36) (in thread):
> Hi Ludwig, not really, it was meant more as a homework for the attendees to think about possible different approaches.
> Do you need them?

**Ludwig Geistlinger** (15:41:02) (in thread):
> It'll be great to collect them for having them readily available when giving the workshop again. Together with some folks here at CCB, I will be giving the workshop to the Department of Immunology here at HMS in the fall, and likely also for a paid private gig for physalia courses in Berlin. Maybe you and Davide can also benefit from that in case you plan to give the workshop again eg in Italy? We do not intend to include them in the carpentries module directly though, but rather have them in a private instructor-only github repo. Because otherwise most students will just immediately skip to the solutions instead of actually working on the exercises.

**Davide Risso** (15:49:47) (in thread):
> Sounds good. Idon’thave any solutions written down but I can work on it. I will likely reuse some of this for CSAMA in June btw

**Davide Risso** (15:50:14) (in thread):
> If you create the instructor-only repo, I’d be happy to contribute the solutions

**Davide Risso** (15:50:51) (in thread):
> Thanks for your effort! The carpentries course looks amazing!

**Dario Righelli** (15:51:31) (in thread):
> I can do the same:slightly_smiling_face:

**Ludwig Geistlinger** (15:52:37) (in thread):
> Sounds great, let me add you both to the instructor-only repo

**Ludwig Geistlinger** (15:56:10) (in thread):
> I added you both to the repo, you should have received an invitation from github. Also added you@Marcel Ramos Pérez, we do have the solutions for your session already though

**Dario Righelli** (15:56:34) (in thread):
> Thanks Ludwig!
