---
title: "#mae-updates"
format: gfm
---

## 2016-11-21

**Marcel Ramos Pérez** (15:22:12):
> @Marcel Ramos Pérez has joined the channel

**Marcel Ramos Pérez** (15:22:13):
> set the channel description: MultiAssayExperiment GitHub updates

**Marcel Ramos Pérez** (15:40:10):
> added an integration to this channel: [github](https://community-bioc.slack.com/services/B35C0QX8B)


## 2016-11-26

**Sean Davis** (22:23:43):
> @Sean Davis has joined the channel


## 2016-11-28

**Lucas Schiffer** (13:17:28):
> @Lucas Schiffer has joined the channel

**Levi Waldron** (13:17:28):
> @Levi Waldron has joined the channel

**Vince Carey** (13:17:36):
> @Vince Carey has joined the channel


## 2016-11-30

**Unknown User** (15:43:15):
**Unknown User** (15:53:29):
**Marcel Ramos Pérez** (15:54:34):
> <!channel>For those who are in the channel, you are able to mute the channel from the settings:gear:, if the updates are too noisy. Thanks.

**Unknown User** (17:08:09):
**Unknown User** (18:49:25):

## 2016-12-08

**Unknown User** (21:03:14):

## 2016-12-09

**Unknown User** (20:00:39):

## 2016-12-12

**Sean Davis** (09:29:46):
> [https://www.youtube.com/watch?v=ZAbaXAQpZPE](https://www.youtube.com/watch?v=ZAbaXAQpZPE)from@Levi Waldron.
  - Attachment (YouTube): [curatedMetagenomicData](https://www.youtube.com/watch?v=ZAbaXAQpZPE)


## 2016-12-19

**Unknown User** (23:39:32):

## 2016-12-22

**Unknown User** (13:56:52):
**Unknown User** (23:24:35):

## 2016-12-23

**Unknown User** (00:00:55):

## 2016-12-27

**Unknown User** (19:51:38):
**Unknown User** (20:42:26):

## 2016-12-28

**Unknown User** (15:35:59):
**Unknown User** (15:36:18):
**Unknown User** (16:00:07):

## 2016-12-29

**Unknown User** (18:45:51):
**Unknown User** (18:56:44):

## 2016-12-30

**Unknown User** (15:35:33):

## 2017-01-02

**Unknown User** (16:40:03):
**Unknown User** (23:19:58):

## 2017-01-03

**Unknown User** (18:53:11):

## 2017-01-13

**Unknown User** (20:11:59):
**Unknown User** (20:49:08):

## 2017-01-17

**Unknown User** (10:48:40):
**Unknown User** (11:00:47):
**Unknown User** (11:04:38):
**Unknown User** (11:52:05):
**Unknown User** (11:54:48):

## 2017-01-20

**Unknown User** (19:10:38):

## 2017-01-23

**Unknown User** (17:12:06):
**Unknown User** (17:12:32):
**Unknown User** (17:13:43):

## 2017-01-24

**Unknown User** (00:37:33):

## 2017-01-27

**Unknown User** (13:24:25):
**Unknown User** (15:09:14):
**Unknown User** (17:17:54):
**Unknown User** (20:29:12):

## 2017-01-30

**Unknown User** (12:32:44):
**Unknown User** (21:13:47):

## 2017-01-31

**Unknown User** (14:55:44):

## 2017-02-01

**Unknown User** (17:43:18):

## 2017-02-02

**Unknown User** (14:13:54):
**Unknown User** (20:26:45):

## 2017-02-03

**Unknown User** (18:39:02):

## 2017-02-06

**Unknown User** (16:45:23):
**Unknown User** (16:45:48):

## 2017-02-07

**Unknown User** (20:20:29):

## 2017-02-08

**Unknown User** (21:26:46):

## 2017-02-09

**Unknown User** (22:10:54):

## 2017-02-13

**Unknown User** (13:48:27):

## 2017-02-14

**Unknown User** (11:03:01):
**Unknown User** (11:03:38):

## 2017-02-24

**Unknown User** (11:20:09):

## 2017-02-27

**Unknown User** (14:45:10):
**Unknown User** (16:03:51):
**Unknown User** (19:26:42):
**Unknown User** (19:43:57):

## 2017-02-28

**Unknown User** (12:37:28):
**Unknown User** (12:59:29):
**Unknown User** (13:46:44):
**Unknown User** (14:05:09):
**Unknown User** (14:17:29):
**Unknown User** (16:01:23):
**Unknown User** (16:40:12):
**Unknown User** (21:30:01):
**Unknown User** (21:31:00):

## 2017-03-01

**Unknown User** (20:24:46):
**Unknown User** (20:52:12):
**Unknown User** (21:29:33):

## 2017-03-02

**Unknown User** (19:20:39):
**Unknown User** (19:35:32):
**Unknown User** (19:38:37):
**Unknown User** (19:47:30):

## 2017-03-06

**Unknown User** (16:03:53):

## 2017-03-09

**Unknown User** (15:48:36):
**Unknown User** (18:10:36):
**Unknown User** (18:26:59):

## 2017-03-10

**Unknown User** (13:48:28):
**Unknown User** (15:26:53):
**Unknown User** (20:59:17):
**Unknown User** (21:09:49):

## 2017-03-13

**Unknown User** (21:24:09):

## 2017-03-20

**Unknown User** (20:45:59):
**Unknown User** (20:56:08):
**Unknown User** (22:22:19):

## 2017-03-21

**Unknown User** (21:22:52):
**Unknown User** (21:23:58):

## 2017-03-22

**Unknown User** (20:28:57):
**Unknown User** (20:35:28):
**Unknown User** (20:40:47):
**Unknown User** (20:52:47):
**Unknown User** (20:53:05):

## 2017-03-23

**Unknown User** (13:43:50):
**Unknown User** (15:57:14):
**Unknown User** (19:03:33):

## 2017-03-24

**Unknown User** (20:13:47):
**Unknown User** (20:16:17):

## 2017-03-26

**Unknown User** (21:58:49):

## 2017-03-27

**Unknown User** (13:06:28):
**Unknown User** (13:08:42):
**Unknown User** (13:09:07):
**Unknown User** (13:19:14):
**Unknown User** (13:40:16):

## 2017-03-30

**Unknown User** (15:46:53):

## 2017-03-31

**Unknown User** (19:24:11):
**Unknown User** (19:44:58):

## 2017-04-05

**Unknown User** (21:27:56):
**Unknown User** (21:35:59):

## 2017-04-06

**Unknown User** (17:55:34):

## 2017-04-07

**Unknown User** (14:04:28):
**Unknown User** (15:53:27):
**Unknown User** (15:54:07):
**Unknown User** (15:54:34):

## 2017-04-10

**Unknown User** (19:18:46):

## 2017-04-11

**Unknown User** (20:37:44):

## 2017-04-13

**Unknown User** (17:36:39):

## 2017-04-19

**Unknown User** (16:50:42):
**Unknown User** (16:56:36):
**Unknown User** (16:57:08):
**Unknown User** (18:05:08):

## 2017-04-20

**Unknown User** (20:46:23):

## 2017-04-21

**Unknown User** (18:24:42):

## 2017-05-01

**Aedin Culhane** (12:09:32):
> @Aedin Culhane has joined the channel


## 2017-05-03

**Unknown User** (01:28:16):
**Unknown User** (02:06:34):
**Unknown User** (02:39:29):
**Unknown User** (02:41:36):
**Unknown User** (19:26:37):
**Unknown User** (20:43:36):
**Marcel Ramos Pérez** (20:46:59):
> @Marcel Ramos Pérez pinned a message to this channel.


## 2017-05-04

**Unknown User** (11:49:43):
**Unknown User** (20:02:34):
**Unknown User** (21:13:34):

## 2017-05-05

**Unknown User** (11:47:42):
**Unknown User** (11:48:01):
**Unknown User** (11:50:28):
**Unknown User** (16:05:18):

## 2017-05-10

**Unknown User** (20:48:14):

## 2017-05-15

**Unknown User** (14:13:53):
**Kasper D. Hansen** (17:23:19):
> @Kasper D. Hansen has joined the channel


## 2017-05-16

**Unknown User** (13:32:50):
**Marcel Ramos Pérez** (13:40:10):
> set the channel topic: Please see pinned item in channel.


## 2017-05-17

**Unknown User** (13:57:41):
**Unknown User** (21:05:39):
**Unknown User** (21:31:46):
**Unknown User** (21:51:52):

## 2017-05-19

**Unknown User** (19:41:34):

## 2017-05-22

**Unknown User** (01:52:17):

## 2017-05-25

**Unknown User** (19:20:47):

## 2017-05-26

**Unknown User** (19:32:08):
**Unknown User** (19:33:40):

## 2017-05-30

**Unknown User** (16:21:47):
**Unknown User** (16:22:17):

## 2017-06-06

**Unknown User** (17:33:30):
**Unknown User** (20:43:26):

## 2017-06-07

**Unknown User** (21:01:14):

## 2017-06-09

**Unknown User** (16:59:14):
**Unknown User** (16:59:46):
**Unknown User** (17:00:09):

## 2017-06-16

**Unknown User** (17:51:50):
**Unknown User** (18:15:40):

## 2017-06-22

**Unknown User** (16:17:47):

## 2017-07-21

**Unknown User** (17:56:57):

## 2017-07-31

**Lorena Pantano** (12:34:40):
> @Lorena Pantano has joined the channel


## 2017-08-17

**Levi Waldron** (10:58:06):
> @Marcel Ramos Pérezthoughts about the cheatsheet addition?
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C34PABUD7/p1500674217176448)
> [\[MultiAssayExperiment\]](https://github.com/waldronlab/MultiAssayExperiment) New branch "[cheatsheet](https://github.com/waldronlab/MultiAssayExperiment/tree/cheatsheet)" was pushed by lwaldron

**Unknown User** (13:29:09):

## 2017-08-18

**Unknown User** (12:48:18):
**Unknown User** (12:48:18):
**Unknown User** (14:52:10):
**Unknown User** (17:16:18):

## 2017-08-23

**Unknown User** (12:25:08):
**Unknown User** (14:43:15):
**Unknown User** (15:16:53):
**Unknown User** (16:15:23):
**Unknown User** (17:29:58):

## 2017-08-31

**Unknown User** (15:30:32):

## 2017-09-08

**Unknown User** (15:36:41):

## 2017-09-13

**Unknown User** (11:59:14):

## 2017-10-05

**Unknown User** (13:01:18):
**Unknown User** (14:52:24):
**Unknown User** (16:57:52):

## 2017-10-11

**Unknown User** (12:05:12):
**Unknown User** (13:16:36):
**Unknown User** (13:57:11):

## 2017-10-19

**Unknown User** (18:04:26):

## 2017-10-23

**Unknown User** (15:04:08):

## 2017-10-30

**Unknown User** (15:26:44):
**Unknown User** (16:45:46):
**Unknown User** (21:00:17):

## 2017-10-31

**Unknown User** (12:57:09):

## 2017-11-01

**Unknown User** (15:35:01):

## 2017-11-09

**Unknown User** (13:52:30):
**Unknown User** (16:52:14):
**Unknown User** (17:08:57):
**Unknown User** (17:55:57):

## 2017-11-10

**Unknown User** (19:57:29):
**Unknown User** (20:12:54):
**Unknown User** (20:13:54):

## 2017-11-13

**Unknown User** (15:01:24):

## 2017-11-16

**Unknown User** (01:11:34):
**Unknown User** (17:09:47):
**Unknown User** (17:15:24):
**Unknown User** (17:27:14):
**Unknown User** (17:49:44):
**Unknown User** (17:53:43):

## 2017-11-17

**Unknown User** (11:47:08):

## 2017-11-20

**Unknown User** (12:56:55):
**Unknown User** (13:04:50):
**Unknown User** (18:06:30):

## 2017-11-21

**Unknown User** (00:02:14):
**Unknown User** (20:09:50):
**Marcel Ramos Pérez** (20:12:59):
> disabled an integration in this channel: [gh-MultiAssayExperiment](https://community-bioc.slack.com/services/B35C0QX8B)

**Marcel Ramos Pérez** (20:13:02):
> removed an integration from this channel: [gh-MultiAssayExperiment](https://community-bioc.slack.com/services/B35C0QX8B)

**Marcel Ramos Pérez** (20:13:45):
> archived the channel
