---
title: "#mass-spectrometry"
format: gfm
---

## 2021-07-29

**Johannes Rainer** (02:04:52):
> @Johannes Rainer has joined the channel

**Johannes Rainer** (02:04:52):
> set the channel description: Mass spectrometry data representation and analysis with Bioconductor. See also dedicated #metabolomics and #proteomics channels for more specific questions.

**Charlotte Soneson** (08:21:29):
> @Charlotte Soneson has joined the channel


## 2021-08-03

**Laurent Gatto** (08:11:08):
> @Laurent Gatto has joined the channel


## 2021-08-04

**Chris Vanderaa** (11:46:31):
> @Chris Vanderaa has joined the channel


## 2021-08-05

**Robert M Flight** (10:33:36):
> @Robert M Flight has joined the channel

**Manojkumar Selvaraju** (17:59:41):
> @Manojkumar Selvaraju has joined the channel


## 2021-08-15

**KP** (01:40:09):
> @KP has joined the channel


## 2022-01-03

**Kurt Showmaker** (17:04:37):
> @Kurt Showmaker has joined the channel


## 2022-03-30

**Sergio Oller** (23:18:20):
> @Sergio Oller has joined the channel


## 2022-08-27

**Clara Pereira** (11:48:49):
> @Clara Pereira has joined the channel


## 2022-10-10

**Mercilena Benjamin** (13:56:14):
> @Mercilena Benjamin has joined the channel


## 2022-12-12

**Carlos José Ferreira da Silva** (18:57:24):
> @Carlos José Ferreira da Silva has joined the channel


## 2023-01-11

**Johannes Rainer** (09:39:57):
> Note: there is an open position in my team - if anybody here is seeking a PhD position in Computational MS and Metabolomics or knows somebody that does:[https://community-bioc.slack.com/archives/CMC6T5KJ8/p1673423299437419](https://community-bioc.slack.com/archives/CMC6T5KJ8/p1673423299437419)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CMC6T5KJ8/p1673423299437419)
> Open PhD position in my team as part of the HUMAN Marie Curie Actions doctoral network.
> 
> The project involves
> • development of methods for quality assessment, normalization and improvement of chromatographic LC-MS data
> • develop methods to enable reproducible annotation of untargeted metabolomics
> • integration of Python and web-based tools into reproducible R analysis workflows (based on the `Spectra` and other Bioconductor packages)
> • analysis and comparison of untargeted metabolomics data from different blood microsampling devices generated within the doctoral network
> For more details: [https://human-dn.eu/](https://human-dn.eu/)
> 
> To apply to the project: [https://human-dn.eu/dc7/](https://human-dn.eu/dc7/)


## 2023-03-16

**Roger Giné Bertomeu** (04:21:04):
> @Roger Giné Bertomeu has joined the channel


## 2023-07-04

**Shruti Shah** (06:19:44):
> @Shruti Shah has joined the channel


## 2023-07-10

**Helge Hecht** (22:40:23):
> @Helge Hecht has joined the channel

**Helge Hecht** (22:41:22):
> There will be a mass spectrometry BoF at the Galaxy Community Conference - meeting details are in the following document:[https://docs.google.com/document/d/1G_k4xtvaNkXkVOFiN22vahx_iryNeRaBj5JaeZuclmI/edit](https://docs.google.com/document/d/1G_k4xtvaNkXkVOFiN22vahx_iryNeRaBj5JaeZuclmI/edit)If you'd like to learn about the state of MS tools in Galaxy or would like to learn more about the activities this meeting is open for everyone to join and express their interest!


## 2023-09-13

**Christopher Chin** (17:03:59):
> @Christopher Chin has joined the channel


## 2023-09-21

**Philippine Louail** (16:39:21):
> @Philippine Louail has joined the channel


## 2024-03-11

**Melysssa Minto** (10:14:58):
> @Melysssa Minto has joined the channel


## 2024-07-23

**Tuulu** (15:21:38):
> @Tuulu has joined the channel


## 2024-08-14

**Kylie Bemis** (22:31:28):
> @Kylie Bemis has joined the channel


## 2024-10-10

**Larissa T Grizzo Thomassian** (20:42:16):
> @Larissa T Grizzo Thomassian has joined the channel


## 2025-03-18

**Nicolo** (17:30:49):
> @Nicolo has joined the channel
