---
title: "#meetups"
format: gfm
---


## 2018-02-26

*16:46:15 - @Davide Risso has joined the channel*
**Davide Risso** (16:46:16):
> set the channel description: Discuss R/Bioconductor meetups and share materials among groups

*16:47:03 - @Kevin Rue-Albrecht has joined the channel*
*16:47:40 - @Dario Righelli has joined the channel*
*17:01:51 - @Marcel Ramos Pérez has joined the channel*
*17:08:07 - @Levi Waldron has joined the channel*
**Levi Waldron** (17:08:45):
> Couple possible topics I can see to discuss here:

**Levi Waldron** (17:09:41):
> 1) sharing materials, resources, experiences on what makes for good / not so good meetups

**Levi Waldron** (17:14:15):
> 2) are organizers looking for some kind of "official" recognition or mention on[bioconductor.org](http://bioconductor.org)? Boston and NYC meetups are so far community efforts without any central organization or recognition, but it could be discussed.

*17:15:14 - @Leonardo Collado Torres has joined the channel*
**Leonardo Collado Torres** (17:16:03):
> Baltimore R meetup groups that I know of:[https://www.meetup.com/Bmore-UseR-Group/](https://www.meetup.com/Bmore-UseR-Group/)[https://www.meetup.com/rladies-baltimore/](https://www.meetup.com/rladies-baltimore/)(both kinda new)
  - Attachment (Meetup): [Bmore UseR Group (Baltimore, MD)](https://www.meetup.com/Bmore-UseR-Group/)
    > R is an open source programming language for statistical computing, data analysis, visualization, and is becoming more of a general purpose tool.Although it has many strengths, learning R has been a c
  - Attachment (Meetup): [R-Ladies Baltimore (Baltimore, MD)](https://www.meetup.com/rladies-baltimore/)
    > R-Ladies Baltimore welcomes members of all R proficiency levels, whether you're a new or aspiring R user, or an experienced R programmer interested in mentoring, networking & expert upskilling. Our no

**Levi Waldron** (17:16:23):
> 3) taking advantage of[meetup.com](http://meetup.com)'s three groups included per account (the account costs $, but you get three groups so some additional groups could piggy-back on already paid accounts)

**Davide Risso** (17:19:31):
> I think that what@Leonardo Collado Torresis alluding to is also worth discussing, i.e. Interactions with R meetup groups

**Davide Risso** (17:20:35):
> Especially in places where there are already well attended / established R meetups

**Davide Risso** (17:26:04):
> Also, from what I could sense, it’s not so much that people want official recognition (although that might be a nice incentive), but seek “permission” to use the Bioconductor brand / logo

**Davide Risso** (17:26:46):
> (that is of course based on my N=1 dataset)

**Levi Waldron** (17:31:24):
> [http://bioconductor.org/about/logo/](http://bioconductor.org/about/logo/)

**Levi Waldron** (17:33:23):
> (no permission is needed provided several conditions - that it is used in reference to Bioconductor, does not imply sponsorship or endorsement by Bioconductor and is not disparaging to Bioconductor, is used in its original color scheme and format and not stretched, cropped or distorted, and links where possible to[bioconductor.org](http://bioconductor.org))

**Levi Waldron** (17:34:18):
> sponsorship / endorsement would be different, we don't really have precedent for that

*17:42:16 - @Laurent Gatto has joined the channel*
*18:32:40 - @Martin Morgan has joined the channel*
**Martin Morgan** (18:36:42):
> The 'technical advisory board' has an opportunity to discuss this later this week; in the past there has been minor concern about the 'brand' being used in a way that doesn't reflect well on the project. I'm more of the opinion that, worst case, there is no such thing as bad press but actually almost always the press is good.

**Martin Morgan** (18:39:44):
> It would be natural to update the 'Events' at the bottom of[https://bioconductor.org](https://bioconductor.org)with meet-ups etc; maybe this would be facilitated by a meetup group or other mostly-automated approach. Also the Bioconductor twitter feed could be employed programmatically or at least as a best practice.

*19:04:54 - @Stephanie Hicks has joined the channel*
*21:56:43 - @Simina Boca has joined the channel*

## 2018-02-27

*01:00:11 - @Charlotte Soneson has joined the channel*
*06:18:37 - @Vince Carey has joined the channel*

## 2018-03-01

*12:33:03 - @Aedin Culhane has joined the channel*
**Aedin Culhane** (12:34:21):
> Maybe borrowing ideas from Rladies might be useful[https://github.com/rladies/starter-kit](https://github.com/rladies/starter-kit)
  - Attachment (GitHub): [rladies/starter-kit](https://github.com/rladies/starter-kit)
    > starter-kit - Guidelines for starting up a local R-Ladies chapter :purple_heart: :earth_africa:

**Stephanie Hicks** (12:35:49):
> I’m going through the process right now of starting an RLadies meet up group. Happy to answer questions if it’s helpful

**Aedin Culhane** (12:36:42):
> Thanks Stephaine, do you think its useful to have a "starter-kit".  Do you like this model. What should a Bioconductor starter kit contain ?

**Aedin Culhane** (12:39:18):
> Should the meetup groups use a "modified" Bioc logo.. (similar to R ladies)...

**Marcel Ramos Pérez** (12:59:02):
> Please see[https://www.bioconductor.org/about/logo/](https://www.bioconductor.org/about/logo/)

**Stephanie Hicks** (14:43:01):
> I thought the starter-kit was extremely helpful and I like the model. It made the process very streamlined. I know the meetup R-Ladies accounts are sponsored by an R-Consortium grant. There is a R-Ladies slack group for all organizers (or co-organizers) of the various chapters. Great place to discuss ideas for events. There is a #new_chapters channel for everyone to request a meetup account.

**Martin Morgan** (19:28:43):
> We did have a bit of a discussion about the use of the Bioconductor name and logo, and revised the statement at[https://bioconductor.org/about/logo/](https://bioconductor.org/about/logo/)to request that groups ask permission (which will usually be granted) before use. We also discussed things to be done to facilitate meetups and similar activities, and hopefully have some progress to report in the not too distant future.

*21:00:46 - @Lorena Pantano has joined the channel*

## 2018-03-02

**Aedin Culhane** (16:48:56):
> Thanks@Stephanie Hicks. I think its useful to have a "go-to" point for organizing the meetups.  Partly because of the cost-structure of meetups. Once membership is over 150 (which it is for our meetup in Boston and for Levi's in NY) then you have to upgrade the membership. The upgraded membership allows one to run 3 groups. So we are paying for 6 meetup groups, but currently only running 2.  At the board meeting, we also discussion the R-Consortium or a central funding model.  Perhaps we can organize a blue jeans call, to work out the good/bad/unnecessary of the starter-kit so we can adapt for bioc@Levi Waldron@Vince Carey

**Levi Waldron** (17:14:32):
> You've been doing it the longest Aedin, want to start by writing down a bit about your format and experiences? I think we should wait for some direction before publishing, but it doesn't hurt to start putting together some pieces.


## 2018-03-03

**Aedin Culhane** (12:09:48):
> Yes, I stated a google doc.[https://docs.google.com/document/d/1i0U9lEJK_-BPs92mAfb6iO-zCY3Q_p7l4Wzbh8ZQmnk/edit?usp=sharing](https://docs.google.com/document/d/1i0U9lEJK_-BPs92mAfb6iO-zCY3Q_p7l4Wzbh8ZQmnk/edit?usp=sharing)


## 2018-03-04

*06:02:08 - @Stian Lågstad has joined the channel*

## 2018-03-30

*07:51:48 - @Matt Ritchie has joined the channel*

## 2018-04-20

**Leonardo Collado Torres** (01:17:49):
> In case you know anyone in Latin American countries[https://twitter.com/fellgernon/status/987191790380945410](https://twitter.com/fellgernon/status/987191790380945410)
  - Attachment (twitter): [Attachment](https://twitter.com/fellgernon/status/987191790380945410)
    > Read about why I'm super excited about the "Latin American R/BioConductor Developers Workshop 2018" 7/30-8/03 [http://lcolladotor.github.io/2018/04/19/latin-american-r-bioconductor-developers-workshop-2018/#.Wtlu4NPwY0o](http://lcolladotor.github.io/2018/04/19/latin-american-r-bioconductor-developers-workshop-2018/#.Wtlu4NPwY0o) [@CDSBMexico](https://twitter.com/CDSBMexico) [@Bioconductor](https://twitter.com/Bioconductor) #rstats Help us spread the word [@LatinR2018](https://twitter.com/LatinR2018) [@RLadiesCDMX](https://twitter.com/RLadiesCDMX) [@RConsortium](https://twitter.com/RConsortium) [@rOpenSci](https://twitter.com/rOpenSci) [@ccg_unam](https://twitter.com/ccg_unam) [@lcgunam](https://twitter.com/lcgunam) [@Conabio](https://twitter.com/Conabio) [@LIIGH_UNAM](https://twitter.com/LIIGH_UNAM)! [https://pbs.twimg.com/media/DbM0T6OVMAA7Ltr.jpg](https://pbs.twimg.com/media/DbM0T6OVMAA7Ltr.jpg)


## 2018-04-24

*13:30:58 - @Ju Yeong Kim has joined the channel*

## 2018-05-03

*13:52:25 - @Loyal has joined the channel*

## 2018-05-18

**Aedin Culhane** (22:50:09):
> Should we do a BOI or short "something" at Bioc2018 regarding Bioc Meetups????

**Levi Waldron** (22:52:53):
> Maybe, or at least a call for interested organizers on developer day along with requests to let us know if they are coming to Boston or NYC and would be interested in participating?


## 2018-07-25

*13:04:06 - @Ezgi Karaesmen has joined the channel*
*13:05:19 - @Diya Das has joined the channel*
**Diya Das** (13:06:36):
> I'd be interested in organizing an SF Bay Area meetup?

**Aedin Culhane** (13:11:22):
> Cool Diya.

**Ezgi Karaesmen** (13:11:52):
> Hi! I’m an organizer of R-Ladies in Columbus OH, and would be interested setting up some BioC meetups!

**Aedin Culhane** (13:11:53):
> We can do a quick Birds of a Feather for meetups if people want.

**Aedin Culhane** (13:12:05):
> Great Ezgi

**Dario Righelli** (18:42:32):
> I’m interested in organizing the meetups in Naples-Italy

**Martin Morgan** (20:04:26):
> I'll add a lunchtime event tomorrow, Thursday, room 211;@Lori Shepherd(from the core team) will be there and@Aedin Culhanewill be there to facilitate.


## 2018-07-26

*11:16:07 - @Andrea Mcewan has joined the channel*
*12:55:35 - @Matthew Oldach has joined the channel*
**Matthew Oldach** (12:56:21):
> I'm interested in starting a #meetup in the Montreal area, anyone willing to help?

**Diya Das** (13:12:11):
> for a website:[https://github.com/academicpages/group-meeting](https://github.com/academicpages/group-meeting)
  - Attachment (GitHub): [academicpages/group-meeting](https://github.com/academicpages/group-meeting)
    > group-meeting - A Jekyll template (based on holman/left) for a group that has regularly scheduled meetings, one post per date. Genericized from thehackerwithin/template

**Davide Risso** (13:45:55):
> Another, R-friendly, option for the website:[https://github.com/rstudio/blogdown](https://github.com/rstudio/blogdown)
  - Attachment (GitHub): [rstudio/blogdown](https://github.com/rstudio/blogdown)
    > blogdown - Create Blogs and Websites with R Markdown

*14:01:13 - @Matthew McCall has joined the channel*
**Matthew McCall** (14:20:46):
> Thanks to all the presenters at lunch today. I really enjoyed hearing about how you structured your meet-ups.@Aedin CulhaneWould you be willing to share the slides from your presentation?

**Aedin Culhane** (14:37:53):
> The doc I showed today was[https://docs.google.com/document/d/1i0U9lEJK_-BPs92mAfb6iO-zCY3Q_p7l4Wzbh8ZQmnk/edit](https://docs.google.com/document/d/1i0U9lEJK_-BPs92mAfb6iO-zCY3Q_p7l4Wzbh8ZQmnk/edit)

*14:38:28 - @Lori Shepherd has joined the channel*
**Matthew McCall** (14:39:50):
> Thank you!

**Dario Righelli** (15:33:34):
> maybe it’s good to have an online “world map” representation of the meetups for each city… what do you think?

**Dario Righelli** (15:34:18):
> (i’m not offering myself to do it):stuck_out_tongue:

**Levi Waldron** (15:43:06):
> @Dario Righellido you mean like the R consortium’s map?[https://www.meetup.com/pro/r-user-groups](https://www.meetup.com/pro/r-user-groups)
  - Attachment (meetup.com): [R User Groups | Meetup Pro - Meetup](https://www.meetup.com/pro/r-user-groups)
    > R User Groups is on Meetup Pro with more than 27279 members across 47 Meetups worldwide. Meetup Pro is the professional tool for organizing and communicating a network of users, partners, contributors and members.

**Levi Waldron** (15:43:17):
> but Bioconductor-specific?

**Levi Waldron** (15:44:40):
> BTW I’ve been keeping a README.md with abstracts and links to materials from our meetups at[https://github.com/waldronlab/BiocNYC](https://github.com/waldronlab/BiocNYC). Would be happy to move this to a shared/combined site.
  - Attachment (GitHub): [waldronlab/BiocNYC](https://github.com/waldronlab/BiocNYC)
    > Materials presented at the BiocNYC meet-up

**Dario Righelli** (16:08:38):
> @Levi Waldronexactly. In such a way we’d be able of keeping track of all the groups worldwide and also coordination would be easier!
> If we have a dedicated site (or something similar) clicking on the city mark additional informations can be added (email/citymeetup/whatever)

**Dario Righelli** (16:10:42):
> maybe combining the blogdown linked by@Davide Rissowith leaflet htmlwidget ([https://www.htmlwidgets.org/showcase_leaflet.html](https://www.htmlwidgets.org/showcase_leaflet.html))


## 2018-07-27

**Levi Waldron** (09:00:17):
> I love the idea of having a page that lists all the Bioconductor groups around the world, collects materials from all of them, and has some information for people looking to start a new group where they are.

**Lori Shepherd** (09:26:45):
> I started a meetup under the Bioconductor organization too -[https://github.com/Bioconductor/meetups](https://github.com/Bioconductor/meetups)
  - Attachment (GitHub): [Bioconductor/meetups](https://github.com/Bioconductor/meetups)
    > meetups - Bioconductor repository for meetup groups

**Dario Righelli** (13:26:08):
> I made a first draft of a blog and map using the rblogdown and the leaflet widget[https://github.com/drighelli/BioCmeetups](https://github.com/drighelli/BioCmeetups)
  - Attachment (GitHub): [drighelli/BioCmeetups](https://github.com/drighelli/BioCmeetups)
    > Contribute to BioCmeetups development by creating an account on GitHub.

**Dario Righelli** (13:26:36):
> We have to understand how to setup some stuff, but it seems to work!

**Dario Righelli** (13:27:23):
> If it’s ok for you, I can try to make a pull request on the Bioconductor/meetups repo

*14:32:12 - @Angeline Yasodhara has joined the channel*
**Dario Righelli** (16:14:29):
> ok I just realized that I cannot pull requests on an empty repository ^^

**Davide Risso** (16:43:49):
> who has push access to the repository?@Levi Waldron@Lori Shepherd

**Davide Risso** (16:45:01):
> Perhaps you can add a small commit so that dario can add his pull request?

**Aedin Culhane** (19:31:40):
> Hi@Levi Waldron,@Lori Shepherd. Can you add a commit so I can make a pull request to add files?

**Dario Righelli** (20:05:55):
> @Davide RissoI added you to the repo as contributor… maybe you can add other people in order to easily commit the files


## 2018-07-29

**Levi Waldron** (12:02:29):
> @Davide Risso,@Dario Righelli,@Aedin CulhaneI’ve added you as contributors to the bioconductor/meetups repository

**Levi Waldron** (12:02:44):
> and added a minimal README.md file

**Levi Waldron** (14:01:23) (in thread):
> Hey@Matthew Oldachwhat kind of help do you need? Willing to help as I can from New York...

**Dario Righelli** (15:02:55):
> I’ll proceed with the pull request asap

**Dario Righelli** (15:48:19):
> made it! everyone is invited to contribute! ^^'


## 2018-07-30

**Levi Waldron** (18:03:10):
> How do we contribute? And should we be worried about this warning?
> ```
> We found a potential security vulnerability in one of your dependencies.
> A dependency defined in …/capsule/package-lock.json has known security vulnerabilities and should be updated.
> ```

**Davide Risso** (18:08:10):
> Yeah that sounds scary...

**Marcel Ramos Pérez** (18:22:52):
> can you add me as collaborator? I can look into the json lock file

**Levi Waldron** (18:23:50):
> done


## 2018-07-31

**Dario Righelli** (06:12:26):
> I really don't know why there is that message, I just ignored it for now...  ^^' 
> It's the first time I'm working with these packages!

**Dario Righelli** (07:11:39):
> anyway, this seems a good reference for the blogdown package

**Dario Righelli** (07:11:40):
> [https://bookdown.org/yihui/bookdown/](https://bookdown.org/yihui/bookdown/)
  - Attachment (bookdown.org): [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
    > A guide to authoring books with R Markdown, including how to generate figures and tables, and insert cross-references, citations, HTML widgets, and Shiny apps in R Markdown. The book can be exported to HTML, PDF, and e-books (e.g. EPUB). The book style is customizable. You can easily write and preview the book in RStudio IDE or other editors, and host the book wherever you want (e.g. [bookdown.org](http://bookdown.org)).

**Diya Das** (10:46:42):
> Re: the security vulnerability: I just committed to another GitHub pages site yesterday and got a similar message, so it seems to be something widespread

**Martin Morgan** (11:43:39) (in thread):
> following the security links in yellow lead to updating  "hoek ~> 4.2.1" at[https://github.com/Bioconductor/meetups/blob/master/themes/capsule/package-lock.json#L2775](https://github.com/Bioconductor/meetups/blob/master/themes/capsule/package-lock.json#L2775)but this likely requires updating other dependencies. It is probably better to fix this now (better still: get the upstream 'capsule' fixed by the pros by opening an issue on the upstream repository) rather than investing a lot of content development effort into something that you in the end are forced to discard.
  - Attachment (GitHub): [Bioconductor/meetups](https://github.com/Bioconductor/meetups/blob/master/themes/capsule/package-lock.json#L2775)
    > meetups - Bioconductor repository for meetup groups

*14:18:25 - @Frederick Tan has joined the channel*

## 2018-08-01

**Dario Righelli** (04:58:25) (in thread):
> in our particular case, the capsule theme is not used at the moment.
> So we can discard it... also because maybe in our case it's better to develop a specific theme.


## 2018-08-27

*06:49:45 - @Malte Thodberg has joined the channel*

## 2018-09-27

**Dario Righelli** (09:27:26):
> Hello everyone, I have a question about the meetup page/channel.
> How can I use the bioconductor subscription plan?
> Thanks!


## 2018-09-29

**Levi Waldron** (20:10:47):
> Sorry for the delay@Dario Righelli! Bioconductor doesn’t have a meetup pro plan, but the R Consortium does, which is what the Boston and NYC Bioconductor meetups are using:[https://www.r-consortium.org/projects/r-user-group-support-program](https://www.r-consortium.org/projects/r-user-group-support-program)
  - Attachment (R Consortium): [R User Group Support Program - R Consortium](https://www.r-consortium.org/projects/r-user-group-support-program)
    > Welcome to RC RUGS 2018, the R Consortium’s R User Group and Small Conference Support Program. We at the R Consortium fervently believe that nothing is more effective than face-to-face...

**Levi Waldron** (20:11:26):
> There is a form at the bottom of that page for signing up.


## 2018-10-01

**Dario Righelli** (04:49:52):
> thanks@Levi Waldron!

*04:50:29 - @Stian Lågstad has left the channel*
**Levi Waldron** (08:41:23):
> You're welcome!


## 2018-10-09

*13:56:47 - @BJ Stubbs has joined the channel*

## 2018-10-24

*15:45:06 - @Lauren Fitch has joined the channel*

## 2018-10-31

**Aedin Culhane** (12:57:59):
> Do we know if other cities set up bioconductor meetups after bioc2018?

**Stephanie Hicks** (12:58:20):
> I haven’t heard of anyone starting one

**Stephanie Hicks** (12:58:55):
> I thought about it for Baltimore, but I don’t think I can do both Rlades and Bioconductor meetups


## 2018-11-04

**Matthew McCall** (09:34:57):
> I've been trying to build up interest in Rochester. We hired a bunch of comp bio faculty last year and have another large search going, so I'm hopefully we'll reach sufficient interest soon.


## 2018-11-06

**Dario Righelli** (08:29:51):
> I'm starting with our meetups in Naples (IT)

**Dario Righelli** (08:29:51):
> [https://www.facebook.com/NapoliRBiocMeetup](https://www.facebook.com/NapoliRBiocMeetup)
  - Attachment (facebook.com): [Napoli R/Bioconductor Meetup](https://www.facebook.com/NapoliRBiocMeetup)
    > Napoli R/Bioconductor Meetup, Napoli. 55 likes · 31 talking about this. The Neapolitan community of R/Bioconductor.

**Dario Righelli** (08:30:13):
> Friday 16th we have our first event

**Dario Righelli** (08:30:25):
> [https://www.facebook.com/events/323449664905008/](https://www.facebook.com/events/323449664905008/)


## 2018-11-11

*03:41:07 - @Charlotte Soneson has left the channel*

## 2018-11-27

**Dario Righelli** (16:50:54):
> hey we just planned our second meetup ^^[https://www.facebook.com/events/305033257009758/](https://www.facebook.com/events/305033257009758/)

**Dario Righelli** (16:51:59):
> for the ones who are in Napoli (IT) on December 17th:stuck_out_tongue:

**Kevin Rue-Albrecht** (17:02:14):
> darn.. I'll only be in the region 27th Dec-3rd Jan:stuck_out_tongue_winking_eye:


## 2018-11-28

**Levi Waldron** (07:57:16):
> Nice@Dario Righelli! Love your Vesuvius logo…

**Dario Righelli** (08:38:06):
> thanks@Levi Waldron!!! I’m really proud of it, indeed! ^^
> I made the picture and edited the Bioconductor logo!:laughing:


## 2018-12-02

**Vince Carey** (09:26:01):
> :+1:


## 2018-12-06

*10:27:44 - @Stevie Pederson has joined the channel*

## 2018-12-13

*13:03:27 - @Michael Lawrence has joined the channel*
**Aedin Culhane** (14:09:00):
> @Dario Righellihow do you find FB for meeting organization?

**Aedin Culhane** (14:09:40):
> Like the stickers/gadgets!

*14:16:24 - @Nitesh Turaga has joined the channel*
**Dario Righelli** (14:39:54):
> @Aedin Culhanehere in Italy Facebook is really widespread, that’s why I use it very often for any kind of event organisation.
> Anyway, I find it really intuitive and easy!
> You can create a community around a “fan page” and create events from there!
> If you want to spend money, facebook offers you several way to do it! >.<
> You can sponsor events, posts or whatever you want!

**Dario Righelli** (14:42:05):
> For example, now Facebook offered me a 10€ to spend to sponsor a post!
> I already spent it, before that zuckerberg changed his mind about this gift!:stuck_out_tongue:

**Dario Righelli** (14:43:17):
> and if you want to sell tickets, it gives you the possibility to add this feature to an event…

**Martin Morgan** (14:51:15):
> Is there a master schedule of meetups? Should there be one (e.g., a[github.com/Bioconductor](http://github.com/Bioconductor)repository that takes pull requests and publishes at[bioconductor.github.io](http://bioconductor.github.io))?

**Dario Righelli** (15:27:07):
> @Martin Morganin general for all the meetups? or for each city?

**Martin Morgan** (15:31:04):
> for all meetups

**Martin Morgan** (15:31:15):
> (well, for all Bioc meetups ;)

**Dario Righelli** (15:35:01):
> mmm there should be something from@Levi Waldronmeetups, I think!

**Dario Righelli** (15:36:51):
> [https://github.com/Bioconductor/meetups](https://github.com/Bioconductor/meetups)I started a sort of website, when I was in Toronto… But didn’t had time to improve it…
  - Attachment (GitHub): [Bioconductor/meetups](https://github.com/Bioconductor/meetups)
    > Bioconductor repository for meetup groups. Contribute to Bioconductor/meetups development by creating an account on GitHub.

**Dario Righelli** (15:37:37):
> Maybe after christmas I can finish the website and we can think to create a section with all the meetups and related markdowns

**Levi Waldron** (16:02:16):
> Good idea! I could move over the NYC materials from[https://github.com/waldronlab/BiocNYC](https://github.com/waldronlab/BiocNYC)
  - Attachment (GitHub): [waldronlab/BiocNYC](https://github.com/waldronlab/BiocNYC)
    > Materials presented at the BiocNYC meet-up. Contribute to waldronlab/BiocNYC development by creating an account on GitHub.


## 2018-12-28

*12:46:02 - @Rene Welch has joined the channel*

## 2018-12-30

*14:39:33 - @Evan Biederstedt has joined the channel*

## 2019-01-10

*12:01:00 - @Avi Srivastava has joined the channel*

## 2019-03-17

*07:18:21 - @gamzeaydilek has joined the channel*

## 2019-04-10

*09:47:49 - @Sean Davis has joined the channel*

## 2019-04-15

*12:26:12 - @Jon Bråte has joined the channel*

## 2019-05-23

*11:31:01 - @dave_sevenbridges has joined the channel*

## 2019-06-23

*10:19:12 - @Krithika Venkataraman has joined the channel*
*22:09:46 - @Ameya Kulkarni has joined the channel*
*23:05:29 - @Matt Brauer has joined the channel*

## 2019-06-24

*23:42:23 - @Joanna Dragich has joined the channel*

## 2019-06-26

*13:28:25 - @Junhao Li has joined the channel*

## 2019-08-14

*11:50:08 - @kipper fletez-brant has joined the channel*

## 2019-10-04

*15:33:19 - @David Jenkins has joined the channel*
*16:06:54 - @Keith Connolly has joined the channel*
**Aedin Culhane** (16:24:01):
> The older message have gone.  If you want to set up a Bioconductor Meetups, we have 2 groups one in Boston and in NYC, and we'd love to help

**Aedin Culhane** (16:24:14):
> Boston[https://www.meetup.com/Boston-R-Bioconductor-for-genomics/](https://www.meetup.com/Boston-R-Bioconductor-for-genomics/)
  - Attachment (Meetup): [Boston R/Bioconductor for Genomics (Boston, MA)](https://www.meetup.com/Boston-R-Bioconductor-for-genomics/)
    > This group will meet regularly to discuss topics related to the application and development of R and Bioconductor workflows and packages for data analysis and visualization of genomics data.

**Aedin Culhane** (16:25:00):
> NYC is[https://www.meetup.com/BiocNYC/](https://www.meetup.com/BiocNYC/)
  - Attachment (Meetup): [New York City R/Bioconductor for Genomics (New York, NY)](https://www.meetup.com/BiocNYC/)
    > This group will meet regularly to discuss topics related to the application and development of R and Bioconductor workflows and packages for data analysis and visualization of genomics data. We post m

**Aedin Culhane** (16:25:06):
> There maybe others ???

**Aedin Culhane** (16:26:22):
> Both the Boston and NYC groups joined the R consortium meetup pro account. Which means that they pay the meetup fees.

**Aedin Culhane** (16:33:14):
> JJ Alaires' talk at the Boston Meetup (April 2019) is at[https://externalmediasite.partners.org/Mediasite/Play/67426149abe64801b5d2892c9a4d4a1a1d](https://externalmediasite.partners.org/Mediasite/Play/67426149abe64801b5d2892c9a4d4a1a1d)Skip to minute 11 for the start of it
  - Attachment (externalmediasite.partners.org): [Bioconductor Meet 04/04/19](https://externalmediasite.partners.org/Mediasite/Play/67426149abe64801b5d2892c9a4d4a1a1d)


## 2019-10-07

**Dario Righelli** (03:23:57):
> there is also the Napoli (Italy) group

**Dario Righelli** (03:24:21):
> [https://www.facebook.com/NapoliRBiocMeetup/?modal=admin_todo_tour](https://www.facebook.com/NapoliRBiocMeetup/?modal=admin_todo_tour)
  - Attachment (facebook.com): [Napoli R/Bioconductor Meetup](https://www.facebook.com/NapoliRBiocMeetup/?modal=admin_todo_tour)
    > Napoli R/Bioconductor Meetup, Napoli. 99 likes. The Neapolitan community of R/Bioconductor.

**Dario Righelli** (03:25:34):
> We had the R consortium vector level grant

**Dario Righelli** (03:26:19):
> But we're on Facebook, cause meetup is not really common to use here...

*10:25:17 - @Kelly Street has joined the channel*

## 2019-11-28

*07:18:41 - @Kevin Rue-Albrecht has left the channel*
*07:19:04 - @Kevin Rue-Albrecht has joined the channel*

## 2020-02-14

*04:47:59 - @Ines de Santiago has joined the channel*

## 2020-03-12

*16:00:50 - @Stephanie Hicks has left the channel*

## 2020-03-19

*12:30:59 - @Daniela Cassol has joined the channel*

## 2020-06-06

*19:57:31 - @Olagunju Abdulrahman has joined the channel*

## 2020-06-26

*15:56:56 - @Jenny Smith has joined the channel*

## 2020-07-29

*17:37:56 - @Riyue Sunny Bao has joined the channel*

## 2020-07-31

*12:48:43 - @Isha Goel has joined the channel*
*13:56:13 - @bogdan tanasa has joined the channel*

## 2020-08-05

*03:22:58 - @Hans-Rudolf Hotz has joined the channel*

## 2020-09-04

*08:24:35 - @Goutham Atla has joined the channel*

## 2020-09-16

*09:32:56 - @Nitesh Turaga has left the channel*

## 2020-10-11

*21:42:14 - @Kozo Nishida has joined the channel*

## 2020-11-19

*13:32:51 - @Martin Morgan has left the channel*

## 2020-12-01

*22:24:14 - @Kevin Stachelek has joined the channel*

## 2020-12-02

*05:43:24 - @Konstantinos Geles (Constantinos Yeles) has joined the channel*

## 2020-12-07

*21:19:39 - @Aoi Senju has joined the channel*

## 2020-12-12

*00:39:41 - @Huipeng Li has joined the channel*

## 2020-12-24

*16:38:07 - @Jose Marie Antonio Miñoza has joined the channel*

## 2021-01-22

*15:44:25 - @Annajiat Alim Rasel has joined the channel*

## 2021-02-12

*15:52:49 - @Janani Ravi has joined the channel*

## 2021-03-12

*14:51:36 - @Julia Romanowska has joined the channel*

## 2021-03-23

*23:05:27 - @Lambda Moses has joined the channel*

## 2021-04-28

*17:57:01 - @Mateusz Staniak has joined the channel*

## 2021-05-05

*09:55:25 - @Abel Torres Espin has joined the channel*

## 2021-05-11

*16:44:16 - @Megha Lal has joined the channel*

## 2021-05-25

*12:19:09 - @Quang Nguyen has joined the channel*

## 2021-06-04

*05:51:59 - @Flavio Lombardo has joined the channel*

## 2021-06-05

*17:21:39 - @KP has joined the channel*

## 2021-07-23

*15:53:14 - @Batool Almarzouq has joined the channel*

## 2021-08-05

*18:20:30 - @Robert M Flight has joined the channel*

## 2021-08-19

*11:33:34 - @Ava Hoffman (she/her) has joined the channel*

## 2021-09-01

*14:43:18 - @Katie Saund has joined the channel*

## 2021-09-06

*08:22:59 - @Eddie has joined the channel*
*09:09:12 - @Eddie has left the channel*

## 2021-09-16

*18:36:02 - @Henry Miller has joined the channel*

## 2021-09-25

*19:05:38 - @Mikey C has joined the channel*

## 2021-11-08

*03:28:34 - @Paula Nieto García has joined the channel*

## 2021-11-26

*06:46:37 - @Francesc Català has joined the channel*

## 2022-02-16

*04:37:48 - @Heather Turner has joined the channel*
**Heather Turner** (04:38:07):
> :fire:Collaboration Campfires
> 
> Join us at these informal collaborative events to find out about how you can contribute to R by helping with bug handling and/or translating messages from English to other languages.
> 
> February 22: Explore R’s Bug-tracking Process
> March 22: How to Help Review R Bug Reports
> April 26: Explore R’s Process for Localization (Translation)
> May 24: How to Contribute to a Translation Team
> 
> More info:[https://contributor.r-project.org/events/collaboration-campfires](https://contributor.r-project.org/events/collaboration-campfires)
  - Attachment (contributor.r-project.org): [Collaboration Campfires](https://contributor.r-project.org/events/collaboration-campfires)
    > Collaborative sessions for newcomers to learn more about contributing to R.

**Heather Turner** (04:38:29):
> Regarding translation, I have created a copy of the table on[https://developer.r-project.org/TranslationTeams.html](https://developer.r-project.org/TranslationTeams.html), which you can find here:[https://docs.google.com/spreadsheets/d/1sA_C4lYHgyl3v6B48vgeZx9d5TMsHK9ahinJqnpNhq4/edit#gid=0](https://docs.google.com/spreadsheets/d/1sA_C4lYHgyl3v6B48vgeZx9d5TMsHK9ahinJqnpNhq4/edit#gid=0)If people have updated information on any of the contacts/translation teams, can you add it to the sheet? Thanks!


## 2022-03-02

*09:57:06 - @Wes W has joined the channel*

## 2022-03-10

**Aedin Culhane** (19:35:44):
> We are looking for a Bioconductor person to take over running the Boston R/Bioconductor Meetup Group[https://www.meetup.com/Boston-R-Bioconductor-for-genomics/?_cookie-check=uZjYOIfAhBSrmM3o](https://www.meetup.com/Boston-R-Bioconductor-for-genomics/?_cookie-check=uZjYOIfAhBSrmM3o)
  - Attachment (Meetup): [Boston R/Bioconductor for Genomics (Boston, MA)](https://www.meetup.com/Boston-R-Bioconductor-for-genomics/?_cookie-check=uZjYOIfAhBSrmM3o)
    > This group will meet regularly to discuss topics related to the application and development of R and Bioconductor workflows and packages for data analysis and visualization of genomics data.


## 2022-03-15

*12:04:15 - @Jeanette Johnson has joined the channel*
*15:53:00 - @Lluís Revilla has joined the channel*

## 2022-03-22

**Heather Turner** (09:28:20):
> :fire:Happening in a couple of hours: the second session in the series of[#CollabCampfires](https://twitter.com/search?q=%23CollabCampfires)!:bug:In this session we will learn how to help review R bug reports[#RStats](https://twitter.com/search?q=%23RStats)[#OpenSource](https://twitter.com/search?q=%23OpenSource):timer_clock:Tuesday, March 22, 15:30 - 17:00 UTC
> 
> You can register via this link anytime in advance:[https://us02web.zoom.us/meeting/register/tZ0qf-uqqjovE9RqD6hvjAIigS9nQb69WGRf](https://us02web.zoom.us/meeting/register/tZ0qf-uqqjovE9RqD6hvjAIigS9nQb69WGRf)


## 2022-04-21

**Heather Turner** (15:34:25):
> :alarm_clock:The 3rd session of the[#CollabCampfires](https://twitter.com/search?q=%23CollabCampfires)series is coming up!:computer:We are moving on to a new topic: Exploring[#RStats](https://twitter.com/search?q=%23RStats)' process for localization (translation).:date:When? Tuesday, April 26, 15:30 - 17:00 UTC
> 
> You don't need to be proficient in a non-English language to participate. In this first session, we will be exploring the process of contributing translations and the current status of translations in the core R codebase.
> 
> To attend, register via the link on this page:[https://contributor.r-project.org/events/collaboration-campfires](https://contributor.r-project.org/events/collaboration-campfires)
  - Attachment (contributor.r-project.org): [Collaboration Campfires](https://contributor.r-project.org/events/collaboration-campfires)
    > Collaborative sessions for newcomers to learn more about contributing to R.

**Kozo Nishida** (21:48:26) (in thread):
> @Heather TurnerThank you for sharing this!
> This seems to be helpful in overcoming language barriers!


## 2022-05-19

**Heather Turner** (10:44:21):
> :tada:The final session of the Collaboration Campfire series is coming soon!:computer:Topic: How to Contribute to a Translation Team, including hands-on translation activities.:date:When? Tuesday, May 24, 15:30 - 17:00 UTC
> 
> You are welcome to join if you are only fluent in English: one of our examples will translate between standard and British English!
> 
> Zoom registration link on the event page:[https://contributor.r-project.org/events/collaboration-campfires](https://contributor.r-project.org/events/collaboration-campfires)
  - Attachment (contributor.r-project.org): [Collaboration Campfires](https://contributor.r-project.org/events/collaboration-campfires)
    > Collaborative sessions for newcomers to learn more about contributing to R.


## 2022-06-15

**Aedin Culhane** (07:15:30):
> @Heather Turner@Kozo NishidaI wonder if we could add some of these events to our calendar. Or if we can link out to relevant other calendars on our events pages


## 2022-06-20

**Kozo Nishida** (06:46:13) (in thread):
> I will ask them if their events can be added to Bioconductor's event calendar.


## 2022-07-07

*14:28:02 - @Clara Pereira has joined the channel*

## 2022-07-22

*14:46:32 - @Gary Sieling has joined the channel*

## 2022-07-28

*17:20:11 - @Mervin Fansler has joined the channel*

## 2022-08-05

**Heather Turner** (06:13:03) (in thread):
> @Aedin Culhaneand@Kozo Nishidasorry for missing this. You're welcome to link to[https://contributor.r-project.org/events/](https://contributor.r-project.org/events/)which should have any events coming up. That also gives Google calendar/ical  links allowing subscription to particular event series, but at the moment we only have R Contribution Working Group meetings planned, so not sure if you want to add all those - no harm I guess, if it's easy enough for you to do!

**Kozo Nishida** (06:50:47) (in thread):
> Thanks@Heather Turner.
> I will link[https://contributor.r-project.org/events/](https://contributor.r-project.org/events/)to the Bioconductor event calendar.
> I think I will only link to "Collaboration Campfires".
> I will plan a collaboration event between "R Contributor" and Bioconductor.
  - Attachment (contributor.r-project.org): [Event calendar](https://contributor.r-project.org/events/)
    > R Contributor Site - for people interested in contributing to R core development

**Heather Turner** (13:09:32) (in thread):
> That sounds great@Kozo Nishida. Maybe you can open an issue about the collaboration event as part of our Ideas Incubator that has just kicked off? See more details here:[https://github.com/r-devel/rcontribution/blob/main/ideas_incubator.md](https://github.com/r-devel/rcontribution/blob/main/ideas_incubator.md).


## 2022-09-27

*16:17:08 - @Jennifer Holmes has joined the channel*

## 2022-10-21

**Kozo Nishida** (18:00:28):
> [https://twitter.com/Bioconductor/status/1583578580012847104](https://twitter.com/Bioconductor/status/1583578580012847104)
  - Attachment (twitter): [Attachment](https://twitter.com/Bioconductor/status/1583578580012847104)
    > #hacktoberfest
    > We reschedule this meetup to next Wednesday in order to gather more attendees!
    > We would be happy if you could join us on the new date!
    > The [http://Meetup.com](http://Meetup.com) URL remains the same. You can also register at 
    > [https://www.meetup.com/boston-r-bioconductor-for-genomics/events/289261203/](https://www.meetup.com/boston-r-bioconductor-for-genomics/events/289261203/) 
    > as well as the following URL. [https://twitter.com/Bioconductor/status/1582117168816132096](https://twitter.com/Bioconductor/status/1582117168816132096)
  - Attachment (twitter): [Attachment](https://twitter.com/Bioconductor/status/1582117168816132096)
    > Join our meetup to learn how to create a post for Bioconductor community blog! :writing_hand:
    > You can be rewarded on [@hacktoberfest](https://twitter.com/hacktoberfest) if you make a blog post PR that's merged :tada:
    > :spiral_calendar_pad:Saturday 22 October 
    > :clock9: 3pm JST
    > :world_map: [https://www.meetup.com/bioconductor-community-in-asia/events/288949678/](https://www.meetup.com/bioconductor-community-in-asia/events/288949678/)
    > #hacktoberfest #rstats [@R_Contributors](https://twitter.com/R_Contributors) [@_R_Foundation](https://twitter.com/_R_Foundation)


## 2022-10-31

**Heather Turner** (13:18:12):
> Starting this week:sparkles:R Contributor Office Hours:sparkles:!
> 
> On the first Thursday of the month, join an Office Hour to
> - discuss how to get started contributing to R
> - get help/feedback on contributions you are working on
> - look at open bugs/work on translations together
> 
> Details:[https://contributor.r-project.org/events](https://contributor.r-project.org/events).
> 
> Note this is for contributor to the core R project vs Bioconductor, but hopefully of interest to some folk here!
  - Attachment (contributor.r-project.org): [Event calendar](https://contributor.r-project.org/events)
    > R Contributor Site - for people interested in contributing to R core development


## 2022-11-02

*11:45:18 - @Nitesh Turaga has joined the channel*

## 2022-12-12

*17:59:03 - @Lexi Bounds has joined the channel*

## 2022-12-13

*18:32:17 - @Xiangnan Xu has joined the channel*

## 2023-01-26

*16:49:19 - @Chenyue Lu has joined the channel*

## 2023-01-27

**Aedin Culhane** (12:22:12):
> Can the meetup admins add Bioc2023 to the meetup groups please

**Aedin Culhane** (12:22:32):
> [http://bioc2023.bioconductor.org](http://bioc2023.bioconductor.org)


## 2023-01-31

*09:10:29 - @Ahmad Al Ajami has joined the channel*

## 2023-02-22

*01:51:08 - @michaelkleymn has joined the channel*
**Heather Turner** (08:45:55):
> Announcing:sparkles:R Project Sprint 2023:sparkles::date:August 30 - September 1:office:University of Warwick, Coventry, UK
> 
> New & experienced contributors are encouraged to apply for a place, funding is available for travel.:dart:Deadline Friday 10 March.
> 
> Full details:[https://contributor.r-project.org/r-project-sprint-2023/](https://contributor.r-project.org/r-project-sprint-2023/)Feel free to get in touch with me if you have any questions.
  - Attachment (contributor.r-project.org): [R Project Sprint 2023](https://contributor.r-project.org/r-project-sprint-2023/)
    > A 3-day meeting of R developers to work collaboratively on R core development, hosted at the University of Warwick, August 30 – September 1


## 2023-02-28

*15:30:37 - @Ramin has joined the channel*

## 2023-03-02

**Aedin Culhane** (09:27:20):
> Meetup admins@Kozo Nishidacan you add Bioc2023 and EuroBioc to the meetup calendars.

**Kozo Nishida** (11:32:52) (in thread):
> I added the events to the Events Google calendar.
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F04S5MP601J/image.png)
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F04S5MQNWBW/image.png)


## 2023-03-09

**Heather Turner** (10:00:09):
> Reminder that the deadline for applications to participate in R Project Sprint 2023 is tomorrow (midnight UTC) :[https://contributor.r-project.org/r-project-sprint-2023/](https://contributor.r-project.org/r-project-sprint-2023/)


## 2023-03-28

**Konstantinos Geles (Constantinos Yeles)** (11:37:44):
> Hello! Are there any meetups in France? North-east?


## 2023-04-05

**Heather Turner** (03:09:55):
> :books:The R Contribution Working Group are organizing a book club for existing/aspiring R contributors that want to learn C or refresh their basic C programming skills. Aside from base R, it will also be relevant to people wanting to contribute to older packages that use R's C interface, which includes several Bioconductor packages (C++ is generally recommended for new packages and this club will not cover that).
> 
> It will run from May to August and our main reading will be[Modern C](https://gustedt.gitlabpages.inria.fr/modern-c/)by Jens Gustedt. All readings and exercises can be accessed for free. See the book club repo for full details:[https://github.com/r-devel/c-book-club/](https://github.com/r-devel/c-book-club/).

**Konstantinos Geles (Constantinos Yeles)** (04:00:28) (in thread):
> Hello@Heather TurnerI would like to ask you how many contributors are already in the group?
> Do you think that the meetings are going to take place during CET  or CST working hours?

**Heather Turner** (05:16:36) (in thread):
> Hard to say exactly - 14 people have responded to the poll about meeting times so far, but 27 have joined the book club channel on the R Contributors Slack. The times in the poll are 10:30 - 15:00 CET; 16:00-17:00 CET; 21:00-22:00 CET, so mostly in CET working hours, but we will go with the majority. As it says on the repo, we plan to record meetings and share on the R Contributors Slack for people that can't make it. If there is no good time (say less than 50% of poll respondents can attend the meeting), we may switch to an asynchronous format or possibly alternate between two times - it depends on the poll results.

**Heather Turner** (05:21:47) (in thread):
> Sorry times above are CEST.

**Konstantinos Geles (Constantinos Yeles)** (05:53:44) (in thread):
> Thanks I will join the slack then!


## 2023-05-15

**Heather Turner** (08:32:46):
> [R/Basel](https://user-regional-2023.gitlab.io/basel)A useR! affiliated regional event on Friday, July 21, 2023. Call for abstracts open until***Friday 26 May***.
> 
> Abstracts invited on:
> - R for presenting, communication and reporting
> - R communities
> - R “show n tell” (package showcase)
> - R for data science
> - Using R in regulatory interactions
> 
> There will also be an invited session on R in Clinical Trials, co-hosted with the Basel Biometrics Society).


## 2023-05-18

*05:53:49 - @Oluwafemi Oyedele has joined the channel*

## 2023-05-31

*14:15:28 - @Alyssa Obermayer has joined the channel*

## 2023-06-07

*18:29:58 - @Alyssa Obermayer has joined the channel*

## 2023-07-28

*13:47:46 - @Konstantinos Daniilidis has joined the channel*

## 2023-08-03

*15:58:32 - @Ritika Giri has joined the channel*

## 2023-08-04

*09:35:50 - @Trisha Timpug has joined the channel*
*10:48:42 - @Ray Su has joined the channel*

## 2023-09-15

*04:55:23 - @Leo Lahti has joined the channel*

## 2024-02-01

**Kevin Rue-Albrecht** (10:17:27):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F06GR1CJ09Y/image.png)

**Vince Carey** (13:03:37):
> @Levi Waldron@Marcel Ramos Pérezis this of interest?


## 2024-02-02

**Kevin Rue-Albrecht** (05:42:23):
> For the record, somehow I'm offered a button to "Become the organizer". I'm not sure if all members of the group have that option, but I'm not based in New York City (not even in the US), so that really wouldn't feel right:smile:


## 2024-02-07

**Kevin Rue-Albrecht** (07:33:53):
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F06J0HHJHMX/image.png)


## 2024-02-09

**Levi Waldron** (10:07:10) (in thread):
> Too many Slack channels. I haven't organized NYC Meetups for a while. If there is still time to "save" it I could check with alternative potential organizers.

**Levi Waldron** (10:08:47):
> @Vince Carey@Kevin Rue-AlbrechtToo many Slack channels. I haven't organized NYC Meetups for a while. If there is still time to "save" it I could be the organizer for long enough to check with alternative potential organizers.

**Kevin Rue-Albrecht** (10:32:07):
> Do you need me to forward you the email? If there is still time, you should be able to log in and be presented with the button to save it


## 2024-02-12

**Levi Waldron** (05:24:24):
> No that's OK, even as of last week we would have to coordinate with RUGS again to stay on their paid plan.


## 2024-02-28

**Heather Turner** (10:35:05):
> :loudspeaker:R Dev Day @ PLUS, Salzburg, Austria on Fri 12 July
> 
> Collaborative event for novice & experienced contributors to base R.
> 
> Places allocated by application, deadline Sun March 24, 2024.[https://contributor.r-project.org/r-dev-day-plus-2024](https://contributor.r-project.org/r-dev-day-plus-2024)
  - Attachment (contributor.r-project.org): [R Dev Day @ PLUS](https://contributor.r-project.org/r-dev-day-plus-2024)
    > A 1-day meeting of R developers to work collaboratively on R core development, hosted at Paris Lodron University of Salzburg, July 12, 2024.


## 2024-03-15

**Heather Turner** (06:31:03):
> :loudspeaker:**** R Dev Day @ Imperial, London, UK - Fri 26 Apr**Collaborative event for current/aspiring contributors to base R.
> 
> Free and open registration, until Sun 14 Apr:[https://pretix.eu/r-contributors/r-dev-day-imperial-2024/](https://pretix.eu/r-contributors/r-dev-day-imperial-2024/)Coffee & lunch thanks to Jumping Rivers and Imperial Central RSE Team.  Also 40% discount code for[#SatRdays](https://twitter.com/hashtag/SatRdays?src=hashtag_click)London the following day.


## 2024-03-22

**Heather Turner** (10:52:41):
> Reminder that the deadline for applications to this event is end of day Sunday March 24 (anywhere on earth)[https://community-bioc.slack.com/archives/C9EJJD6KT/p1709134505015969](https://community-bioc.slack.com/archives/C9EJJD6KT/p1709134505015969)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C9EJJD6KT/p1709134505015969)
    > :loudspeaker: R Dev Day @ PLUS, Salzburg, Austria on Fri 12 July
    > 
    > Collaborative event for novice & experienced contributors to base R.
    > 
    > Places allocated by application, deadline Sun March 24, 2024.
    > 
    > [https://contributor.r-project.org/r-dev-day-plus-2024](https://contributor.r-project.org/r-dev-day-plus-2024)


## 2024-04-04

*23:39:23 - @Tung Trinh has joined the channel*

## 2024-04-17

*23:15:32 - @rizoic has joined the channel*

## 2024-04-18

*03:02:29 - @Philipp Sergeev has joined the channel*

## 2024-05-15

*08:31:23 - @Sunil Nahata has joined the channel*

## 2024-07-02

*10:59:19 - @Diána Pejtsik has joined the channel*

## 2024-07-05

*12:29:13 - @Margherita has joined the channel*

## 2024-07-26

*19:52:24 - @Qiwen Octavia Huang has joined the channel*

## 2024-08-04

*14:58:30 - @sunnyday has joined the channel*

## 2024-08-19

*09:41:26 - @Rema Gesaka has joined the channel*

## 2024-09-20

*09:30:32 - @Camille Guillermin has joined the channel*

## 2024-10-28

**Heather Turner** (13:48:11):
> :loudspeaker:R Dev Day @ LatinR 2024:date:Dates: Mon 18 Nov and Tue 19 Nov, 5:30pm - 8pm (UTC-3):computer:Venue: Online:moneybag:Cost: free:eyes:More details and registration:[English](https://latinr.org/en/cronograma/r-dev-day/rdevday-en.html)|[Spanish](https://latinr.org/cronograma/r-dev-day/)|[Portuguese](https://latinr.org/pt/cronograma/r-dev-day/rdevday-pt.html), deadline Sat 16 Nov
> 
> R Dev Day @ LatinR 2024 is an open, collaborative event for people interested in contributing to the code, documentation and translations of base R, or to infrastructure that supports such contribution. Both new and experienced contributors are welcome!


## 2024-11-12

**Heather Turner** (06:43:05):
> Please register by this Saturday, 16 Nov, if you wish to participate in R Dev Day @ LatinR 2024:point_up_2:


## 2024-11-25

*16:17:50 - @rohitsatyam102 has joined the channel*

## 2025-03-18

*14:28:06 - @Andres Wokaty has joined the channel*

## 2025-03-19

**Heather Turner** (10:10:58):
> :loudspeaker:R Dev Day @ useR! 2025, Duke University, Durham, NC, USA:date:Mon 11 Aug 2025
> 
> Join this collaborative event for people to contribute to the code, documentation or translations in base R, or to infrastructure that supports such contribution. Both new and experienced contributors are welcome!
> 
> Free to attend - registration at useR! 2025 is not required. Places allocated by application to balance across experience levels.
> 
> Details:[https://user2025.r-project.org/additional/r-dev-day](https://user2025.r-project.org/additional/r-dev-day)Application deadline:***Tuesday, April 15***(midnight anywhere on earth)


## 2025-03-27

*05:42:41 - @Jacqueline Murphy has joined the channel*

## 2025-04-02

**Heather Turner** (08:49:05):
> :loudspeaker:R Dev Day @ RSECon25, Warwick University, UK:date:Friday 12 September 2025			
> 			
> Apply to attend this free event, to collaborate on contributions to base R.:sparkles:Travel funding available for participants from UK, Europe & Global South:sparkles:Deadline***Wednesday 23 April***:[https://warwick.ac.uk/statistics/news/r-dev-day-rsecon25](https://warwick.ac.uk/statistics/news/r-dev-day-rsecon25)


## 2025-04-17

*16:17:45 - @dhvani solanki has joined the channel*

## 2025-04-22

**Heather Turner** (10:51:45):
> Reminder that applications are closing soon for the R Dev Day @ RSECon25:point_up_2:
