---
title: "#metabolomics"
format: gfm
---


## 2020-03-23

*13:58:52 - @Kevin Blighe has joined the channel*
**Kevin Blighe** (13:58:52):
> set the channel description: discussion surrounding metabolomics analyses

*14:00:42 - @kipper fletez-brant has joined the channel*
*16:24:59 - @Laurent Gatto has joined the channel*

## 2020-03-26

*14:36:08 - @olga tsiouri has joined the channel*

## 2020-04-19

*11:20:07 - @Shubham Gupta has joined the channel*

## 2020-06-06

*19:57:33 - @Olagunju Abdulrahman has joined the channel*

## 2020-06-12

*09:48:54 - @Johannes Rainer has joined the channel*

## 2020-07-07

*02:56:57 - @Vivek Das has joined the channel*

## 2020-07-24

*07:47:26 - @Isha Goel has joined the channel*

## 2020-07-31

*03:16:05 - @Saulius Lukauskas has joined the channel*

## 2020-08-24

*16:43:35 - @Chris Fields has joined the channel*

## 2020-09-17

**Johannes Rainer** (10:55:48):
> Excuse me for mis-using this channel for a job-ad - but I'm looking for a postdoc with experience in R and interested in large scale metabolomics data analysis. If you are interested or know somebody that maybe is, here's the official job post:[bit.ly/35INbUa](http://bit.ly/35INbUa)

**Laurent Gatto** (15:13:57) (in thread):
> There's also the#jobschannel and a jobs posts on the support site.


## 2020-10-11

*21:43:29 - @Kozo Nishida has joined the channel*

## 2020-10-15

*19:42:28 - @Kevin Blighe has left the channel*

## 2020-10-28

*11:56:33 - @Gavin Rhys Lloyd has joined the channel*

## 2020-11-19

*08:30:01 - @Kevin Blighe has joined the channel*

## 2020-12-12

*00:39:38 - @Huipeng Li has joined the channel*

## 2020-12-14

*08:56:06 - @Thomas Naake has joined the channel*

## 2020-12-17

*11:12:55 - @James MacDonald has joined the channel*

## 2021-01-22

*15:44:33 - @Annajiat Alim Rasel has joined the channel*

## 2021-01-27

*03:53:25 - @Mirko Signorelli has joined the channel*
**Mirko Signorelli** (03:59:41):
> Hi all! I am analysing a dataset gathered in a multiomic experiment and comprising measurements of RNA transcripts, metabolites and lipids. I'm fairly new to metabolomics, and I am wondering if for metabolites (and lipids) there exist specific ontologies that are the equivalent of GO or KEGG.  Do you have suggestions?:pray:


## 2021-01-28

**Mirko Signorelli** (09:21:52) (in thread):
> Thanks! It does indeed allow to do enrichment analyses with the methods implemented in their webtool, but it does not seem possible to download a list of the pathways that they test with the corresponding metabolites - I would need that list to apply a different test (PCGSEA)


## 2021-02-01

**Johannes Rainer** (03:21:46) (in thread):
> I've never done that before, but quite some information about metabolites and pathways and links to genes is in KEGG. Also, it should in theory be possible to download stuff from HMDB (human metabolom database) that also provide annotations/ontologies.


## 2021-03-20

*01:57:43 - @watanabe_st has joined the channel*

## 2021-03-24

*10:20:32 - @Jan Stanstrup has joined the channel*
*12:19:52 - @Gonçalo Graça has joined the channel*

## 2021-05-11

*16:44:14 - @Megha Lal has joined the channel*

## 2021-07-23

*15:53:20 - @Batool Almarzouq has joined the channel*

## 2021-07-29

**Johannes Rainer** (02:54:08):
> Hi all! we're currently implementing**core functionality**for metabolomics analyses (chemical formula processing, adduct definition, isotope identification) in the [MetaboCoreUtils]([https://rformassspectrometry.github.io/MetaboCoreUtils](https://rformassspectrometry.github.io/MetaboCoreUtils)), utilities simplifying annotation of untargeted metabolomics data in [MetaboAnnotation]([https://rformassspectrometry.github.io/MetaboAnnotation](https://rformassspectrometry.github.io/MetaboAnnotation)) and with [CompoundDb]([https://euracbiomedicalresearch.github.io/CompoundDb/index.html](https://euracbiomedicalresearch.github.io/CompoundDb/index.html)) a package to create and use (metabolomics) annotation databases. Feedback (and eventually contributions) highly welcome!
  - Attachment (rformassspectrometry.github.io): [Core Utils for Metabolomics Data](https://rformassspectrometry.github.io/MetaboCoreUtils)
    > MetaboCoreUtils defines metabolomics-related core functionality provided as low-level functions to allow a data structure-independent usage across various R packages. This includes functions to calculate between ion (adduct) and compound mass-to-charge ratios and masses or functions to work with chemical formulas. The package provides also a set of adduct definitions and information on some commercially available internal standard mixes commonly used in MS experiments.
  - Attachment (rformassspectrometry.github.io): [Utilities for Annotation of Metabolomics Data](https://rformassspectrometry.github.io/MetaboAnnotation)
    > High level functions to assist in annotation of (metabolomics) data sets. These include functions to perform simple tentative annotations based on mass matching but also functions to consider m/z and retention times for annotation of LC-MS features given that respective reference values are available. In addition, the function provides high-level functions to simplify matching of LC-MS/MS spectra against spectral libraries and objects and functionality to represent and manage such matched data.
  - Attachment (euracbiomedicalresearch.github.io): [Creating and Using (Chemical) Compound Annotation Databases](https://euracbiomedicalresearch.github.io/CompoundDb/index.html)
    > CompoundDb provides functionality to create and use (chemical) compound annotation databases from a variety of different sources such as LipidMaps, HMDB, ChEBI.


## 2021-08-05

*10:33:48 - @Robert M Flight has joined the channel*

## 2021-09-28

*12:16:01 - @Steffen Neumann has joined the channel*
**Steffen Neumann** (12:16:50):
> Hi, application is open (deadline October 11th) for[https://www.denbi.de/training/1177-3rd-de-nbi-elixir-de-metarbolomics-hackathon](https://www.denbi.de/training/1177-3rd-de-nbi-elixir-de-metarbolomics-hackathon)Aim of the workshop is to improve the interoperability of packages (e.g. using common data structures and interfaces), combine efforts (use single implementation of common functions), create and demonstrate complex workflows by integrating existing tools, identify gaps in the metaRbolomics ecosystem that need to be covered. We will also have enough discussion time to ponder challenges of the future, taking metaRbolomics into the next decade.

**Steffen Neumann** (12:17:58):
> In case you haven't seen metaRbolomics yet,[https://www.mdpi.com/2218-1989/9/10/200](https://www.mdpi.com/2218-1989/9/10/200)and[https://youtu.be/LfmkZ1HmJnE](https://youtu.be/LfmkZ1HmJnE)


## 2021-11-26

**Steffen Neumann** (02:35:17):
> <!channel>:
> CompMS Workshops at @MetSoc conference 2022 in Barcelona, Spain
> 
> Dear CompMS community,
> One of the big events next year will be the annual conference of the International Metabolomics Society in Barcelona, Spain (June 19-23, 2020 see[https://metabolomics2022.org/](https://metabolomics2022.org/)).
> Recently, the call for workshop proposals went out (see[https://www.metabolomics2022.org/workshops](https://www.metabolomics2022.org/workshops)for the announcement), asking for workshop proposals by January 10th, 2022.
> As we had several coordinated proposals for workshops from the computational community in past years, and many of them got accepted, it would be great to repeat that success. This coordination might also avoid that the organising committee asks to join several proposals with overlapping content.
> The workshop submission system asks a number of questions, which I have collected in a google doc at[https://ogy.de/ehzi](https://ogy.de/ehzi)for self-organised coordination of our efforts that includes a copy of the submission form questions, so the actual submission will only be a copy&paste away.
> Yours,
> Steffen
  - Attachment (Google Docs): [CompMS activities at metabolomics2022](https://ogy.de/ehzi)
    > CompMS Activities 2022 The Workshop call is now out at [https://www.metabolomics2022.org/workshops](https://www.metabolomics2022.org/workshops) Workshops will take place on Sunday afternoon, June 19 and Monday morning, June 20.The deadline for submission of workshop proposals is January 10, 2022. Our previous CompMS activities at metabol...

**Steffen Neumann** (02:57:20) (in thread):
> Valencia of course. Apologies for mixing up !!


## 2021-11-29

**Johannes Rainer** (01:58:16) (in thread):
> Great idea to synchronize efforts! I could give a workshop on the`Spectra`and`MetaboAnnotation`packages.


## 2021-11-30

**Steffen Neumann** (04:00:55):
> Hi, while it has "Proteomics" in the name, the PSI is also working on standards useable in metabolomics (mzML, mzTab-M, ...) it would be great to have some attendands with Metabolomics / Metabolomics  background at that meeting:
> 
> Dear All
> We are currently trying to plan the 2022 Spring workshop on 11-13th May as a hybrid event, with those able to meet face-to-face doing so on the Wellcome Trust Campus, Hinxton, Cambs, UK. It would greatly help with the planning if you would be willing to spend 2 minutes answering a very short questionnaire, which will help us to gauge how many people are likely to attend in person, and what size rooms we need to book.
> Please fill in the Google form[here](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2F1uU0lwIpNRM1merasytDOq4jijm5FcdPwJFa61MdwNb8&data=04%7C01%7C%7C64529d09e08649ab23b108d9b3db6c2a%7C0934ee6c2a574efd80a9fc003defef4e%7C0%7C0%7C637738577826520279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=uTOK5iRPCzD1DphVtv0yDSn35DUfVr%2BgVoTzULgx%2BWk%3D&reserved=0)and save the date in your diaries.
> Many thanks
> Sandra


## 2021-12-14

*08:23:00 - @Megha Lal has left the channel*

## 2022-01-03

*17:05:52 - @Kurt Showmaker has joined the channel*

## 2022-03-21

*05:02:00 - @Pedro Sanchez has joined the channel*

## 2022-03-30

*23:18:35 - @Sergio Oller has joined the channel*

## 2022-07-27

*19:49:49 - @saskia has joined the channel*

## 2022-08-11

*17:15:32 - @Rene Welch has joined the channel*

## 2022-08-27

*11:48:42 - @Clara Pereira has joined the channel*

## 2022-10-10

*13:56:17 - @Mercilena Benjamin has joined the channel*

## 2022-10-12

**Steffen Neumann** (09:37:11):
> ***Subject:***CompMS Workshops at @MetSoc conference 2023 in Niagara Falls, Canada
> Dear CompMS community,
> It’s this time of the year again :-) One of the big events next year will be the annual conference of the International Metabolomics Society in Niagara Falls, Canada (June 18 - 22, 2023,[https://metabolomics2023.org/](https://metabolomics2023.org/)). Recently, the Call for pre-conference workshops went out at[https://www.metabolomics2023.org/workshops](https://www.metabolomics2023.org/workshops). Workshops will take place on Sunday afternoon, June 18 and Monday morning, June 19.
> The deadline for submission of workshop proposals is November 10, 2022.
> As we had several coordinated proposals for workshops from the computational community in past years, and many of them got accepted, it would be great to repeat that success. This coordination might also avoid that the Conference organising committee asks to join several proposals with overlapping content after the proposal submission.
> The workshop submission system asks a number of questions, which I have collected in a google doc at[https://ogy.de/oycb](https://ogy.de/oycb)for self-organised coordination of our efforts. The document includes a copy of the submission form questions, so the actual submission will only be a copy&paste away. Developing & Sharing your workshop here is not a requirement for submission, in fact conference organisers might not even be aware of it.
> I would also like to notice that there are several initiatives and mailing lists to which this mail got sent out to reach a broad audience in the CompMS community:
> * ELIXIR Metabolomics Community ([https://elixir-europe.org/communities/metabolomics](https://elixir-europe.org/communities/metabolomics))
> * The ICSB+HUPO+MetSoc CompMS collaboration ([https://CompMS.org/](https://CompMS.org/))
> * #metaRbolomics is a Twitter Hashtag & Slack Workspace dedicated to R stuff.
> If you are aware of other relevant channels to disseminate this call, please get back to me.
> Yours, Steffen
  - Attachment (Google Docs): [CompMS activities at metabolomics2023](https://ogy.de/oycb)
    > CompMS Activities 2023 The call for pre-conference workshops is now out at [https://www.metabolomics2023.org/workshops](https://www.metabolomics2023.org/workshops). Workshops will take place on Workshops will take place on Sunday afternoon, June 18 and Monday morning, June 19.The deadline for submission of workshop proposals is November ...


## 2022-11-10

*08:34:15 - @Roger Giné Bertomeu has joined the channel*

## 2022-12-12

*18:57:29 - @Carlos José Ferreira da Silva has joined the channel*

## 2022-12-13

*18:32:18 - @Xiangnan Xu has joined the channel*

## 2023-01-11

**Johannes Rainer** (09:40:52):
> Note: there is an open position in my team - if anybody here is seeking a PhD position in Computational MS and Metabolomics or knows somebody that does:[https://community-bioc.slack.com/archives/CMC6T5KJ8/p1673423299437419](https://community-bioc.slack.com/archives/CMC6T5KJ8/p1673423299437419)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CMC6T5KJ8/p1673423299437419)
    > Open PhD position in my team as part of the HUMAN Marie Curie Actions doctoral network.
    > 
    > The project involves
    > • development of methods for quality assessment, normalization and improvement of chromatographic LC-MS data
    > • develop methods to enable reproducible annotation of untargeted metabolomics
    > • integration of Python and web-based tools into reproducible R analysis workflows (based on the `Spectra` and other Bioconductor packages)
    > • analysis and comparison of untargeted metabolomics data from different blood microsampling devices generated within the doctoral network
    > For more details: [https://human-dn.eu/](https://human-dn.eu/)
    > 
    > To apply to the project: [https://human-dn.eu/dc7/](https://human-dn.eu/dc7/)

**Kozo Nishida** (13:26:28):
> Hi all,
> Does MsBackendRawFileReader only support rawrr (i.e. Thermo .raw files?)?
> Are Agilent or Bruker .D or Sciex .wiff files not supported yet?

**Laurent Gatto** (13:30:47) (in thread):
> ping@Christian Panse

**Kozo Nishida** (13:37:09) (in thread):
> If it's not implemented yet, I'm interested in adding raw file support to MsBackendRawFileReader using the DLLs included in the vendor's SDK (and mono). (I would like to imitate rawrr to do it.)

*13:42:53 - @Christian Panse has joined the channel*
**Laurent Gatto** (13:46:27) (in thread):
> I think it's only Thermo files, but I might be wrong. I always convert to mzML and am not aware of any real drawbacks in doing so (other than the conversion time and disk space, but these are irrelevant compare to other challenges).

**Christian Panse** (14:26:44) (in thread):
> @Kozo Nishidawouldn’t it make more sense to implement a backend for *.d files using[https://CRAN.R-project.org/package=opentimsr](https://CRAN.R-project.org/package=opentimsr)
  - Attachment (cran.r-project.org): [opentimsr: An Open-Source Loader for Bruker's timsTOF Data Files](https://CRAN.R-project.org/package=opentimsr)
    > A free, open-source package designed for handling .tdf data files produced by Bruker's 'timsTOF' mass spectrometers. Fast, free, crossplatform, with no reading through EULAs or messing with binary .dll files involved.

**Christian Panse** (14:29:33) (in thread):
> and call it, e.g., MsBackendWiff similar for Bruker and Agilent

**Christian Panse** (14:30:06) (in thread):
> better coordinate the naming with@Laurent Gattoand@Johannes Rainer

**Christian Panse** (14:31:08) (in thread):
> the name RawFileReader is derived from ThermoFisherScientific’s RawFileReader library

**Christian Panse** (14:37:38) (in thread):
> Also, as far as I remember, there was some effort in *.d file backend development in@Johannes Rainergroup

**Christian Panse** (14:39:30) (in thread):
> btw:@Laurent Gatto@Johannes Rainerlet me know if there is a mzXML file converter for *.d files

**Christian Panse** (14:42:49) (in thread):
> @Laurent Gatto@Johannes Rainertalking about the MsBackendRawFileReader I failed to make progress with that issue:[http://fgcz-ms.uzh.ch/~cpanse/talks/20211123-rawrrRcpp_MetaRbolimics2021.html](http://fgcz-ms.uzh.ch/~cpanse/talks/20211123-rawrrRcpp_MetaRbolimics2021.html)

**Kozo Nishida** (14:46:52) (in thread):
> @Christian PanseThank you for the information!@Laurent GattoBy the way, Is ProteoWizard often used for such conversions? (Or is any Bioconductor package used for the conversion?) > I always convert to mzML

**Christian Panse** (14:57:04) (in thread):
> @Kozo NishidaI use`docker run -t -v ${PWD}:${PWD} -w ${PWD} --rm chambm/pwiz-skyline-i-agree-to-the-vendor-licenses wine msconvert $(MSCONVERTOPT_DIA) $<`for running pwiz in docker

**Laurent Gatto** (15:20:31) (in thread):
> Yes,`msconvert`from Proteowizard (pwiz for short) is the standard. For Thermo files, there's[ThermoRawFileParser](https://github.com/compomics/ThermoRawFileParser)that uses mono and work on GNU/Linux.

**Christian Panse** (16:00:46) (in thread):
> I am not sure if ThermoRawFileParser is advanced enough to compete with pwiz. E.g., I did not get working mzML files for our FragPipeDIA|DDA workflow. Old story: mzML != mzML so better run pwiz in wine emulator (on GNU/Linux).

**Kozo Nishida** (21:17:49) (in thread):
> Thank you for information!
> Raw file handling is interesting for me and I might write a post about it on the Bioconductor community blog.


## 2023-01-12

**Johannes Rainer** (05:42:58) (in thread):
> Great@Kozo Nishida- and just to add also some information: we have our data as Sciex wiff files and usually convert them with proteowizard/docker (same as@Christian Panse). For Bruker TimsTOF we (actually Andrea who is now in@Laurent Gatto’s group) have started to implement a dedicated backend ([https://github.com/rformassspectrometry/MsBackendTimsTof/](https://github.com/rformassspectrometry/MsBackendTimsTof/)). To make life easier for developers I've now also started to write a tutorial how to write a`MsBackend`for`Spectra`([https://github.com/rformassspectrometry/Spectra/pull/265](https://github.com/rformassspectrometry/Spectra/pull/265)) - your feedback on that would also be great if you plan your own backend.
  - Attachment: [#265 Add first content to the MsBackend howto](https://github.com/rformassspectrometry/Spectra/pull/265)

**Johannes Rainer** (11:18:38) (in thread):
> Let me know if you need any more information! am always happy for contributions :)


## 2023-02-08

**Kozo Nishida** (08:48:27):
> Hi all,
> Does anyone know if there is a Bioconductor package that converts the MS-DIAL export text table to SummarizedExperiment?

**Laurent Gatto** (09:24:29):
> I have never used MS-DIAL outputs, but it it's a rather standard table, with some columns containing quantitative values, then`QFeatures::readSummarizedExperiment()`is a simple approach.

**Laurent Gatto** (09:24:57) (in thread):
> [https://rformassspectrometry.github.io/QFeatures/reference/readQFeatures.html](https://rformassspectrometry.github.io/QFeatures/reference/readQFeatures.html)
  - Attachment (rformassspectrometry.github.io): [QFeatures from tabular data — readQFeatures](https://rformassspectrometry.github.io/QFeatures/reference/readQFeatures.html)
    > Convert tabular data from a spreadsheet or a data.frame into a
    > QFeatures object.

**Kozo Nishida** (09:33:19) (in thread):
> Thank you. I will try`readQFeatures`.


## 2023-02-09

**Laurent Gatto** (01:24:45) (in thread):
> Note that there's`QFeatures::readSummarizedExperiment()`and`QFeatures::readQFeatures()`.

**Kozo Nishida** (22:49:25):
> @Laurent GattoDoes any package exist to retrieve (Quantitative) data (not raw data) from Metabolights / Metabolomics Workbench and read them as QFeatures objects?


## 2023-02-10

**Laurent Gatto** (00:15:59):
> Not that I know of.


## 2023-02-14

**Johannes Rainer** (02:45:23) (in thread):
> I never tried that, but if I'm not wrong[https://bioconductor.org/packages/release/bioc/html/Risa.html](https://bioconductor.org/packages/release/bioc/html/Risa.html)allows to import the metadata and data from metabolights?
  - Attachment (Bioconductor): [Risa](https://bioconductor.org/packages/release/bioc/html/Risa.html)
    > The Investigation / Study / Assay (ISA) tab-delimited format is a general purpose framework with which to collect and communicate complex metadata (i.e. sample characteristics, technologies used, type of measurements made) from experiments employing a combination of technologies, spanning from traditional approaches to high-throughput techniques. Risa allows to access metadata/data in ISA-Tab format and build Bioconductor data structures. Currently, data generated from microarray, flow cytometry and metabolomics-based (i.e. mass spectrometry) assays are supported. The package is extendable and efforts are undergoing to support metadata associated to proteomics assays.


## 2023-02-28

*16:53:52 - @Krithika Bhuvanesh has joined the channel*

## 2023-03-01

*12:13:19 - @jeremymchacón has joined the channel*

## 2023-05-04

**Kozo Nishida** (11:46:00):
> Hi all,
> Should msp file contributions be sent to AnnotationHub?
> Or should it be sent to MsDataHub?

**Laurent Gatto** (12:00:11):
> It depends on the file and its usage. I'm open.@Johannes Rainermight have an opinion?

**Kozo Nishida** (12:26:08):
> I would like to make that contribution by redistributing the msp files in this tweet[https://twitter.com/msdial_project/status/1561613568918712320](https://twitter.com/msdial_project/status/1561613568918712320).
> The license is CC-BY 4.0, so I can redistribute the msp files.[http://prime.psc.riken.jp/compms/licence/main.html](http://prime.psc.riken.jp/compms/licence/main.html)
  - Attachment (Twitter): [MS-DIAL on Twitter](https://twitter.com/msdial_project/status/1561613568918712320)
    > The publicly available/distributable msp files are uploaded on our website.
    > [https://t.co/7vC3n6tn3B](https://t.co/7vC3n6tn3B)
    > This should be a good 'start up kit' for using ms-dial program at this moment.
  - Attachment (prime.psc.riken.jp): [CompMS | Licence](http://prime.psc.riken.jp/compms/licence/main.html)
    > Computational mass spectrometry for metabolomics and lipidomics

**Kozo Nishida** (12:34:43):
> I am thinking of using`sp <- Spectra(THE_MSP_FILE, `****`source`****` = MsBackendMsp())`anyway.
> I have not yet thought of any usage beyond that.


## 2023-05-05

**Johannes Rainer** (04:04:18):
> If it's for annotation (e.g. is a reference library with fragment spectra) then I think it should go to`AnnotationHub`. Would be really great if that file also gets a version so that multiple version can be kept on AnnotationHub - to ensure reproducibility.
> 
> I did something similar with the MassBank releases - I'm converting their databases (MySQL dumps) into a`CompDb`SQLite database (for the`CompoundDb`package). These are added to AnnotationHub (there is the[AHMassBank](http://bioconductor.org/packages/release/bioc/html/AHMassBank.html)package that provides the metadata etc for that).
> 
> In your case it would even be easier because you would just have to reference the msp file and don't have to physically add the file to the AnnotationHub. What would be nice is if the AnnotationHub resource is loaded the data is provided to the user already as a`Spectra`object... but that's details:slightly_smiling_face:I would be really interested to also start using that resource, so it would be very nice to have that easily accessible to the user. Let me know if I can help with anything:slightly_smiling_face:
  - Attachment (Bioconductor): [AHMassBank](http://bioconductor.org/packages/release/bioc/html/AHMassBank.html)
    > Supplies AnnotationHub with MassBank metabolite/compound annotations bundled in CompDb SQLite databases. CompDb SQLite databases contain general compound annotation as well as fragment spectra representing fragmentation patterns of compounds' ions. MassBank data is retrieved from [https://massbank.eu/MassBank](https://massbank.eu/MassBank) and processed using helper functions from the CompoundDb Bioconductor package into redistributable SQLite databases.


## 2023-05-19

*11:14:50 - @Ajda Pristavec has joined the channel*

## 2023-05-29

**Kozo Nishida** (05:17:49):
> Hi all,
> I am interested in the workflow calculating spectra similarity scores.[https://rformassspectrometry.github.io/MsCoreUtils/reference/distance.html#ref-examples](https://rformassspectrometry.github.io/MsCoreUtils/reference/distance.html#ref-examples)shows the example, but
> the
> ```
> x <- matrix(c(1:5, 1:5), ncol = 2, dimnames = list(c(), c("mz", "intensity")))
> y <- matrix(c(1:5, 5:1), ncol = 2, dimnames = list(c(), c("mz", "intensity")))
> ```
> are not from a real data source.
> Does anyone have an idea for creating x / y from real Bioc data resources?
  - Attachment (rformassspectrometry.github.io): [Spectra Distance/Similarity Measurements — distance](https://rformassspectrometry.github.io/MsCoreUtils/reference/distance.html#ref-examples)
    > These functions provide different normalized similariy/distance measurements.

**Laurent Gatto** (06:29:56):
> You can use`Spectra`objects and the`compareSpectra()`function (that uses the MsCoreUtils distances) to compute distances. Some examples here:[https://rformassspectrometry.github.io/docs/sec-id.html#comparing-spectra](https://rformassspectrometry.github.io/docs/sec-id.html#comparing-spectra)
  - Attachment (rformassspectrometry.github.io): [Chapter 4 Identification data | R for Mass Spectrometry](https://rformassspectrometry.github.io/docs/sec-id.html#comparing-spectra)
    > Chapter 4 Identification data | R for Mass Spectrometry

**Laurent Gatto** (06:30:29):
> (example are for proteomics though, put is applicable to metabolomics data)


## 2023-05-30

**Kozo Nishida** (01:42:04):
> I would like to classify all HMDB IDs by the instrument on which they were measured.
> Any ideas that might be useful to do that?
> I'm sure CompoundDb would help that, but I'm not sure if data with instrument field for all HMDB IDs is distributed in Bioconductor.

**Laurent Gatto** (01:46:40) (in thread):
> @Johannes Raineris the go-to person for that

**Johannes Rainer** (02:21:36) (in thread):
> Yes, it should be possible to import the HMDB data with`CompoundDb`- I haven't tried for quite some time... if you run into problems feel also free to open an issue at the CompoundDb github repo. And yes, we're importing the instrument info from HMDB. My issue with HMDB is a bit that it lacks quite some crucial data in their downloadable files (e.g. the precursor m/z). And we're not re-distributing HMDB on Bioconductor - in contrast, you can get MassBank data from`AnnotationHub`.

**Johannes Rainer** (02:22:54) (in thread):
> Maybe also have a look at[https://github.com/jorainer/SpectraTutorials](https://github.com/jorainer/SpectraTutorials)that shows examples for spectra similarity calculations of experimental spectra against MassBank spectra

**Kozo Nishida** (02:29:01) (in thread):
> @Johannes RainerThanks for the information!
> I will try to make my own hmdb CompoundDb.
> But the hmdb_metabolites.xml (with all the information) is very large (6.04 GB).
> Is there a function in CompoundDb to read this (large) xml?

**Johannes Rainer** (02:38:42) (in thread):
> actually,`CompoundDb`requires you to install the compound information from the SDF file from HMDB ("structures" file) - for the spectra data you need to download the spectra xml file archive (which seems to be huge now). that archive contains one xml file per spectrum. See[https://rformassspectrometry.github.io/CompoundDb/articles/create-compounddb.html#compdb-from-hmdb-data](https://rformassspectrometry.github.io/CompoundDb/articles/create-compounddb.html#compdb-from-hmdb-data)for more information on creating the HMDB CompDb...
  - Attachment (rformassspectrometry.github.io): [Creating CompoundDb annotation resources](https://rformassspectrometry.github.io/CompoundDb/articles/create-compounddb.html#compdb-from-hmdb-data)
    > CompoundDb

**Johannes Rainer** (02:50:46) (in thread):
> Note: I did create a`CompDb`for HMDB in 2021:[https://github.com/jorainer/MetaboAnnotationTutorials/releases/tag/2021-11-02](https://github.com/jorainer/MetaboAnnotationTutorials/releases/tag/2021-11-02)- maybe you can use that until you managed to create a CompDb on the newest version

**Kozo Nishida** (05:17:38) (in thread):
> Thank you@Johannes Rainer.
> Thanks to your[https://github.com/jorainer/MetaboAnnotationTutorials/releases/tag/2021-11-02](https://github.com/jorainer/MetaboAnnotationTutorials/releases/tag/2021-11-02),
> Now I can see the ID to intrument[_type] associations
> ```
> library(CompoundDb)
> cdb <- CompDb("CompDb.Hsapiens.HMDB.5.0.sqlite")
> compounds(cdb, columns = c("compound_id", "instrument_type", "instrument"))
> ```
> 
> ```
> compound_id                                   instrument_type
> 1   HMDB0000001                                       Quattro_QQQ
> 2   HMDB0000002                                              <NA>
> 3   HMDB0000002                             EI-B (HITACHI RMU-6L)
> 4   HMDB0000002                             EI-B (HITACHI RMU-6M)
> 5   HMDB0000002                               CI-B (HITACHI M-80)
> ```
> But what I wanted to know was not the `instrument[_type]' information. (sorry I was wrong.)
> I wanted to know if it was experimentally detected or not, and the following seems to be what I want.
> I understand that`compound_id`with`FALSE`in the`predicted`column is experimentally detected.
> (If I am wrong about that, I would appreciate it if you could let me know.)
> ```
> > a=compounds(cdb, columns = c("compound_id", "predicted"))
> > a
>     compound_id predicted
> 1   HMDB0000001     FALSE
> 2   HMDB0000002     FALSE
> 3   HMDB0000005     FALSE
> 4   HMDB0000008     FALSE
> 5   HMDB0000010     FALSE
> 6   HMDB0000011     FALSE
> 7   HMDB0000012     FALSE
> 8   HMDB0000014     FALSE
> 9   HMDB0000015     FALSE
> 10  HMDB0000016     FALSE
> 11  HMDB0000017     FALSE
> 12  HMDB0000019     FALSE
> 13  HMDB0000020     FALSE
> 14  HMDB0000021     FALSE
> 15  HMDB0000022     FALSE
> 16  HMDB0000023     FALSE
> 17  HMDB0000024        NA
> ```
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F05A1FEQN74/image.png)

**Johannes Rainer** (06:18:39) (in thread):
> Ah, I see. I created this database***only***with experimental MS/MS spectra (I imported that "experimental_msms_spectra" xml file from HMDB. Then, I would suggest you extract the data as a`Spectra`:
> ```
> sps <- Spectra(cdb)
> ```

**Johannes Rainer** (06:19:51) (in thread):
> You have then access to all variables in the database:`sps$predicted`gives you information whether spectra are predicted (none of them are),`sps$compound_id`would return you the compound ID of the spectrum. Use`spectraVariables(sps)`to list all available information/columns from the database.

**Johannes Rainer** (06:20:31) (in thread):
> I'm still trying to download the full HMDB spectra data... let's then see if I'll be able to import that into a`CompDb`...

**Johannes Rainer** (06:21:02) (in thread):
> that database would then also contain the predicted spectra - if you would be interested in them (I usually ignore them...)


## 2023-05-31

**Johannes Rainer** (07:30:40) (in thread):
> Note: I created now also a`CompDb`from the HMDB data including the predicted spectra (in case you want/need that). It has 24805 experimental and 455954 predicted spectra.


## 2023-06-15

*22:12:04 - @Indrik Wijaya has joined the channel*

## 2023-06-16

*04:54:45 - @Leo Lahti has joined the channel*
*04:56:12 - @Artur Sannikov has joined the channel*
*04:56:13 - @Tuomas Borman has joined the channel*

## 2023-06-20

*23:52:46 - @Sudarshan has joined the channel*

## 2023-07-04

*06:20:02 - @Shruti Shah has joined the channel*

## 2023-07-10

*22:40:27 - @Helge Hecht has joined the channel*

## 2023-07-13

**Kozo Nishida** (04:29:56):
> I would like to know if there is a package that does some kind of machine learning for`Spectra`object.
> If you have any ideas on how to find that, please let me know.


## 2023-07-28

*15:57:54 - @Benjamin Yang has joined the channel*

## 2023-08-01

**Johannes Rainer** (09:22:57) (in thread):
> I'm not aware of any such package. for what purpose would you like to use ML on a`Spectra`?


## 2023-08-04

*10:05:17 - @Ray Su has joined the channel*

## 2023-08-08

**Kozo Nishida** (02:46:45) (in thread):
> I would like to predict the annotation of unknown (== not annotated from the library)`Spectra`by ML (by similarity of known and unknown`Spectra`).


## 2023-08-10

**Johannes Rainer** (03:14:17) (in thread):
> that sounds great! I'm not aware of anybody having implemented that for`Spectra`- please let me know if you need help/contributions (or to eventually cross-check your code for potential optimization based on internals of`Spectra`) etc. that would be also very interesting for me:slightly_smiling_face:


## 2023-09-03

*09:51:52 - @Lea Seep has joined the channel*

## 2023-09-06

**Steffen Neumann** (06:36:21):
> Hi,
> I was going through the list of to-be-deprecated BioC packages[https://support.bioconductor.org/p/9152979/](https://support.bioconductor.org/p/9152979/)that might've been of interest in case someone wants to support current maintainers:[https://www.bioconductor.org/packages/release/bioc/html/mbOmic.html](https://www.bioconductor.org/packages/release/bioc/html/mbOmic.html)mbOmic: Integrative analysis of the microbiome and metabolome[https://www.bioconductor.org/packages/release/bioc/html/Metab.html](https://www.bioconductor.org/packages/release/bioc/html/Metab.html)Metab: An R Package for a High-Throughput Analysis of Metabolomics Data Generated by GC-MS.[https://www.bioconductor.org/packages/release/bioc/html/MSstatsSampleSize.html](https://www.bioconductor.org/packages/release/bioc/html/MSstatsSampleSize.html)Simulation tool for optimal design of high-dimensional MS-based proteomics experiment[https://www.bioconductor.org/packages/release/bioc/html/OmicsLonDA.html](https://www.bioconductor.org/packages/release/bioc/html/OmicsLonDA.html)OmicsLonDA: Omics Longitudinal Differential Analysis
> 
> I might've missed others, in that case please mention here.
> 
> Yours, Steffen


## 2023-09-13

*17:04:00 - @Christopher Chin has joined the channel*

## 2023-09-15

*04:55:28 - @Leo Lahti has joined the channel*

## 2023-09-22

*03:54:09 - @Philippine Louail has joined the channel*

## 2023-11-14

*09:23:43 - @Pablo has joined the channel*

## 2023-12-01

**Kozo Nishida** (07:59:22):
> Hi all,
> I found[https://www.metabolomics2024.org/](https://www.metabolomics2024.org/)is up and running. I heard that last year there was an informal event "Bioinformatics hub", where several members of this community gathered. Is there anything we can prepare to come together again for this year's conference ? (I live in Japan, the hosting country, so I thought I'd ask about this.)


## 2024-01-09

**Kozo Nishida** (11:28:48):
> Hi all,
> does anyone know if there's a collection of suitable parameter sets for different instruments when doing peak picking with xcms in Bioconductor?
> 
> As a beginner, I'm not sure what kind of parameter settings are preferable for each instrument(, so I asked the above).

**Roger Giné Bertomeu** (11:54:17) (in thread):
> Hi@Kozo Nishida, I think XCMS online ([https://xcmsonline.scripps.edu](https://xcmsonline.scripps.edu))  has some parameter sets for different instrumental configurations which you could use/copy as a starting point for your analysis
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F06D3L2RU82/image.png)
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F06CX1CSXC6/image.png)

**Roger Giné Bertomeu** (11:55:16) (in thread):
> I'm not aware if anyone has collected these parameter sets for XCMS elsewhere

**Kozo Nishida** (12:16:28) (in thread):
> Hi@Roger Giné BertomeuThank you for the information.
> Indeed, xcms online seems to be the best option.
> I'll consider compiling this information to make it easily accessible from local xcms.
> If it works out, I'll share it with the community.:pray:


## 2024-01-10

**Johannes Rainer** (05:04:35) (in thread):
> I'm not particularly fond of these pre-defined parameter sets of xcms online...   I try to estimate the parameters based on the data measured (see[here](https://jorainer.github.io/xcmsTutorials/)for examples how that can be done). Basically, the most important parameter for***centWave***in`xcms`is the`peakwidth`, and that depends on the LC setup. The second important one is`ppm`- but it's way less important. The only thing one should be careful is to not use too large values of`ppm`(in the range of thousands). I generally use`ppm = 40`for our QTOF data. All other parameters are way less important and the defaults are more or less OK. Also, I generally use`integrate = 2`since the default`integrate = 1`assumes the detected peaks to be symmetric - so, for our data it always cuts off the tail.
  - Attachment (jorainer.github.io): [Exploring and Analyzing LC-MS data with Spectra and xcms](https://jorainer.github.io/xcmsTutorials/)
    > This resource contains examples and tutorials for the analysis of
    >  LC-MS data using the **MsExperiment**, **Spectra** and **xcms** packages.
    >  Various examples show data handling, representation, visualization
    >  and analysis of LC-MS data with these packages. A special emphasis
    >  is given on the definition of various data set-specific parameters
    >  for analysis algorithms of the **xcms** package.

**Kozo Nishida** (06:27:58) (in thread):
> @Johannes RainerThank you for sharing that article.
> It's a great resource.
> I will learn from it and try to provide some feedback.

**Johannes Rainer** (09:46:20) (in thread):
> Let me know if there is something unclear or you need more information/explanation. Also, contributions/PR to this workshop are highly welcome.


## 2024-03-10

*19:58:20 - @Cherishma Subhasa has joined the channel*

## 2024-03-11

*10:15:02 - @Melysssa Minto has joined the channel*

## 2024-03-12

**Kozo Nishida** (02:21:56):
> Hi all,
> Is there a function in the Biodoncudtor package for calculating Bonanza spectrum similarity scores?
> If not, I would like to contribute to some package  by adding that function. (perhaps MsCoreUtils?)

**Laurent Gatto** (03:17:25):
> Not that I'm aware of. And yes,`MsCoreUtils`has a couple of spectra similarity measures, and that would be a good place to add it, as it would then be available for`Spectra`objects.

**Kozo Nishida** (04:22:56):
> Thank you for the information.
> So I'd like to send a PR to`MsCoreUtils`.
> However I have a concern about the R code.
> I plan to write the R code that mimics`Spectral_Similarity_Algorithms.r`in the attached image.
> But the`Spectral_Similarity_Algorithms.r`does not have license information, and there is a copyright comment written as follows.
> ```
> #########################################
> # This script is to do the spectral comparison using four algorithms (Dot product, Bonanza, HSS and GNPS).
> # Shipei Xing, Aug 19, 2020
> # Copyright @ The University of British Columbia
> #########################################
> ```
> If you have any advice regarding this licensing concern, please let me know.
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F06P26QPP8A/image.png)

**Kozo Nishida** (04:33:54):
> Anyway, I will send the PR first rather than worrying about it:sweat_smile:

**Laurent Gatto** (17:03:48):
> That chunk defines copyright holder (the researcher's employer, which is the case in many/most universities, I believe), which is different from the licencing terms. It would be good to check what the terms are if the code is to be copied. Without licence, we are technically now allowed to re-use it in another software. Might be worth contacting the author.


## 2024-03-13

**Kozo Nishida** (06:26:05) (in thread):
> Understood.
> I will contact the author first.


## 2024-03-18

**Kozo Nishida** (08:47:25):
> @Steffen NeumannHave you ever tried to convert MassBank format to mzSpecLib / mzPAF ?
> (I'm in HUPO-PSI Kyoto.)

**Steffen Neumann** (08:47:59) (in thread):
> Hi, no, we didn't give it a shot yet.

**Kozo Nishida** (08:57:01):
> Proteomics people seem to use PSI CV (Controlled Vocabularies)[https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_0000000?lang=en](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_0000000?lang=en)in their standardized format.
> Is it okay to assume that we (#metabolomics) also should use PSI CV in the spectral library metadata?
  - Attachment (ebi.ac.uk): [Ontology Lookup Service (OLS)](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_0000000?lang=en)
    > OLS is a repository for biomedical ontologies that aims to provide a single point of access to the latest ontology versions

**Kozo Nishida** (10:02:53) (in thread):
> The author has allowed me to copy the bonanza function code.
> I submitted an issue for it.[https://github.com/rformassspectrometry/MsCoreUtils/issues/124](https://github.com/rformassspectrometry/MsCoreUtils/issues/124)By the way, I welcome anyone who can submit a PR before I can.


## 2024-04-28

*08:33:33 - @Danielle Callan has joined the channel*

## 2024-05-22

*05:04:39 - @Vilhelm Suksi has joined the channel*
**Vilhelm Suksi** (05:17:07):
> Hi!
> 
> Thanks for your encouraging words@Johannes Rainer. Transitioning right away from the mailing list to this great resource. I agree that keeping the object as generic as possible has its advantages, especially if there was a consensus or guideline for how parameters are set up for extracting necessary data from the object. As it stands, it seems that there is a variety of approaches. For example, some packages require 'colData' columns with specific names. Thus, in absence of a consensus or guideline regarding function parameters for extracting the necessary data, the slots may be included for convenience and support for the existing following of the notame package.
> 
> As I see it, the main contribution of the notame package is in it drawing on a consensus in the literature, which makes it attractive for new practitioners of untargeted LC-MS. With the SummarizedExperiment-support in xcms and the MetaboAnnotation package a full SummarizedExperiment workflow can be achieved, which is approachable to new users. Perhaps at some point it may be worth demonstrating this in a workflow package?

**Johannes Rainer** (05:33:19):
> Hey@Vilhelm Suksi, great to see you here!
> 
> Regarding the slots vs "standard" column names in`colData`- to be as generic and flexible as possible we use parameters such as`mzColname = "mz"`and`rtColname = "rtmed"`in our functions in`MetaboAnnotation`to allow the user to choose which column from e.g. the`SummarizedExperiment`'s`colData`contains the relevant information. We thus don't put constraints on the input object and make it easier to integrate/load data e.g. different software (that all use a different nomenclature).
> 
> Totally agree on the workflow/tutorial showing how to combine packages efficiently. For different aspects of metabolomics data analysis we have currently two tutorial resources:[https://jorainer.github.io/xcmsTutorials/](https://jorainer.github.io/xcmsTutorials/)and[https://jorainer.github.io/SpectraTutorials/](https://jorainer.github.io/SpectraTutorials/)and my PhD student@Philippine Louailis currently working on a complete end-to-end analysis workflow/tutorial. Inclusion of notame or separate workflows but with examples of integration of other packages would be nice options here.
  - Attachment (jorainer.github.io): [Exploring and Analyzing LC-MS data with Spectra and xcms](https://jorainer.github.io/xcmsTutorials/)
    > This resource contains examples and tutorials for the analysis of LC-MS data using the **MsExperiment**, **Spectra** and **xcms** packages. Various examples show data handling, representation, visualization and analysis of LC-MS data with these packages. A special emphasis is given on the definition of various data set-specific parameters for analysis algorithms of the **xcms** package.
  - Attachment (jorainer.github.io): [Mass Spectrometry Data Analysis with Spectra](https://jorainer.github.io/SpectraTutorials/)
    > These workshops and tutorials provide use cases and examples for mass spectrometry data handling and analysis using the Spectra Bioconductor package and how these can be included into other R-based analyis workflows.

**Gavin Rhys Lloyd** (06:06:19):
> Hi@Vilhelm Suksi, welcome! Sorry to jump in but I have been following your thread with interest. We had similar recommendations from reviewers for[PMP](https://bioconductor.org/packages/release//bioc/html/pmp.html)and[structToolbox](https://bioconductor.org/packages/release//bioc/html/structToolbox.html), which share some functionality with notame.
> 
> For PMP we just allow the user to use SummarisedExperiment as input to the functions; it is fairly easy to extract the required data.frame(s) where we need it in this package.
> 
> For structToolbox we were advised to extend SummarisedExperiment to DatasetExperiment, and in the package we include an`as_DatasetExperiment`function to convert from a SummarisedExperiment to a DatasetExperiment. This way the user can input SummarisedExperiment and functions/methods can convert as needed. We dont force any columns to be present in the data object itself. Instead the data processing objects have slots where the user explicitly names the relevant column to use and if the column is required for the method we dont include a default, so that the user is forced to specify it in order to use the method.
> 
> In another package (not released yet, but soon!) we have some methods that require e.g. mz and rt columns and some that dont, so we extended DatasetExperiment to e.g. LCMSExperiment and provide slots in the extended dataset object where the user can name the column containing mz and rt values, and methods can then find them when they need them. Methods that require these slots then use S4 dispatch to ensure they only work with LCMSExperiment and throw an error for DatasetExperiment, while other methods that dont need mz and rt can accept DatasetExperiment or LCMSExperiment since one inherits from the other.
> 
> If you wanted to include some integration of notame with e.g. struct/structToolbox then I am happy to help with this.
> 
> Likewise@Johannes Rainerif you wanted to include PMP and/or structToolbox in your examples of integration with other packages, or to improve integration between our packages and yours, then I would be happy to discuss this and how it might work.

**Leo Lahti** (07:37:39):
> @Vilhelm Suksiperhaps would be good to invite Retu here, too?

**Leo Lahti** (07:42:18):
> We have used TreeSummarizedExperiment in microbiome research, that derives from SingleCellExperiment and it has some advantages: 1) reducedDim slot allows one to store ordinations of the data (like from PCA, PCoA) which are sometimes slow to compute for large data sets; 2) altExps for data versions with different numbers of features (e.g. different metabolomic platforms for the same samples, or aggregated feature sets); 3) metadata slot for additional information. These can be rather useful and many tools are readily available to take advantage of them. I am just wondering whether we should use TreeSummarizedExperiment as the basis for Notame for this reason. TreeSE is a SE, so this would not exclude the possibility of using any of the available SE machinery.

**Johannes Rainer** (09:20:02):
> hm, good point@Leo Lahti, I've never looked into the`TreeSummarizedExperiment`, I see the point for possibility of aggregated feature sets, but wanted to use the`QFeatures`object/package instead for that (i.e. to keep both the original LC-MS features in one assay and the compounded information, if isotopes, adducts of the same compound are aggregated in a separate) - that object keeps track of how the features were aggregated.
> IMHO I would suggest to use the simplest-possible object for general data exchange between packages - which would boil down to the`SummarizedExperiment`. Extending that support (through more complicated objects) would then be relatively easy and could be done later.

**Leo Lahti** (14:23:43):
> Yep.`SummarizedExperiment`is not just the simplest but also the most widely used (out of the above options) afaik (somewhere around top-15 / 2200 Bioc pkgs when I last checked).

**Leo Lahti** (14:27:37):
> I am not that much into metabolomics but the options seem to cover`SummarizedExperiment`,`TreeSummarizedExperiment`,`DatasetExperiment`,`LCMSExperiment`,`QFeatures`, and perhaps something else.

**Vilhelm Suksi** (16:17:15):
> Hi@Gavin Rhys Lloyd, and thanks for your input! The struct/structToolbox  data processing  objects with functionality-dependent slots are interesting but the motivation behind this is not obvious. Is it to more easily automate an assessment of the variability of results depending on the values of the parameters?  I  believe integration with notame  is not in the immediate future, but this will definitely be kept in the back of my mind. In the meanwhile, it will be interesting to see how the further extended LCMSExperiment in the upcoming package translates to  user experience!


## 2024-05-23

**Johannes Rainer** (03:18:22):
> As mentioned above,@Philippine Louailis working currently on a complete end-to-end untargeted metabolomics workflow within R/Bioconductor (from raw data files to significant, annotated features). I'm super busy at present but will come back to you@Vilhelm Suksiand@Gavin Rhys Lloydfor feedback (or contribution) from you on this workflow. That would also be a nice example to test how the packages can be currently integrated or how we could adapt to improve integration.

*05:08:48 - @Retu Haikonen has joined the channel*

## 2024-08-07

*01:59:39 - @Anton Ribbenstedt has joined the channel*

## 2024-08-21

*08:57:21 - @Laura Symul has joined the channel*

## 2024-09-01

*06:47:49 - @Ifra has joined the channel*

## 2024-09-02

**Kozo Nishida** (12:28:45):
> Is there any way to convert a`Spectra`object into a`MSnbase`object of class`Spectrum`or`Spectrum2`?
> (Sorry if I have misunderstood something!)

**Laurent Gatto** (15:09:41):
> No that I can think of. If you have an mzML file, it would be easier to load it into a Specta object. If not, you should be able export the MSnbase data into an mzML, and then create the Spectra object.@Johannes Rainer- can you think of another way?

**Kozo Nishida** (21:19:38):
> Thanks for your reply, Laurent.
> By the way, I would like to create a`MSnbase`object of class`Spectrum`or`Spectrum2`from an msp file.
> Is there a function in`MSnbase`that reads an msp file and creates the object of class`Spectrum`or`Spectrum2`?
> (I don't know the MSnbase::read_msp?, so) I used`MsBackendMsp`(and create the`Spectra`object).
> I ask the above because the software I want to use requires an`Spectrum`or`Spectrum2`input, not an`Spectra`.


## 2024-09-04

**Johannes Rainer** (04:10:21):
> @Kozo Nishida, no we don't have functionality yet to convert from`Spectra`to a`list`of`Spectrum`objects - I could give that however a shot to implement if it's something you will definitely require. That might also help if you want to change in the long term to switch all software to use`Spectra`instead of`MSnbase`

**Johannes Rainer** (09:16:27):
> Looking through the`MSnbase`code I found a function`extractSpectraData`that allows to convert from a`MSnbase::MSpectra`to a`Spectra::Spectra`object - but that's the wrong direction ;)


## 2024-09-05

**Kozo Nishida** (14:04:25):
> Thanks@Johannes Rainer,
> > no we don't have functionality yet to convert from`Spectra`to a`list`of`Spectrum`objects
> Thanks for the info. I see.
> > I could give that however a shot to implement if it's something you will definitely require.
> Sorry, Actually now I created the S4 class (for the package I need to use) myself without using the`MSnbase``Spectrum`or`Spectrum2`.
> Therefore, it is no longer something I definitely require.:bow:
> > That might also help if you want to change in the long term to switch all software to use`Spectra`instead of`MSnbase`
> I agree with that.
> If making that compatibility would be a contribution, let me help in some way.
> > Looking through the`MSnbase`code I found a function`extractSpectraData`that allows to convert from a`MSnbase::MSpectra`to a`Spectra::Spectra`object - but that's the wrong direction:wink:
> That's certainly the opposite direction:wink:Should we send a PR for function called like`MSnbase::createSpectrum1(SpectraObject)``MSnbase::createSpectrum2(SpectraObject)`?


## 2024-09-11

**Johannes Rainer** (02:04:11) (in thread):
> Hi Kozo! sorry for my late reply. Actually, a contribution/PR would be nice, but I had already a look at how that could be done - using some internal code in MSnbase we have (in detail: creating a`list`of`Spectrum`objects directly in C - which is much faster than using`new`etc in R).

**Johannes Rainer** (02:08:24) (in thread):
> I have a PR for Spectra ([https://github.com/rformassspectrometry/Spectra/pull/329](https://github.com/rformassspectrometry/Spectra/pull/329)) with that code - but I might add the functionality to MSnbase instead (to avoid Spectra being dependent on "older" packages)
  - Attachment: [#329 feat: add a function to coerce from Spectra to MSnbase::MSpectra](https://github.com/rformassspectrometry/Spectra/pull/329)
    > • Add backward compatibility: support changing from a `Spectra` object to a `MSnbase::MSpectra` object using the `as()` method.
    > • Add unit tests conditional to the installation of the *MSnbase* package.


## 2024-09-16

*13:22:06 - @Pedro Baldoni has joined the channel*

## 2024-10-21

*19:05:34 - @Zahraa W Alsafwani has joined the channel*

## 2024-10-22

**Kozo Nishida** (17:30:10):
> How do you(Bioconductor community) typically save annotated feature tables (for metabolomics), and in what file formats?


## 2024-10-25

**Johannes Rainer** (05:06:56):
> honestly - for now as tab delimited text files. For the R object to**represent**that data we try to use/stick to the`SummarizedExperiment`. But we're working also on supporting standardized file formats, such as mzTab-M. Development is currently happening in[https://github.com/rformassspectrometry/MsIO](https://github.com/rformassspectrometry/MsIO). feedback/suggestions/contributions welcome. having said that, I would also love to have some data exchange format with MS-DIAL:slightly_smiling_face:


## 2024-10-30

**Steffen Neumann** (07:51:23):
> A few people are currently trying to improve the adoption of mzTab-M. E.g. , with output from MS-Dial and upcoming output in mzMine. xcms always had a hidden minimalistic mzTab-M output as well. On the consumer side, I think MetaboAnalyst(R) does read mzTab-M. ELIXIR-DE is contemplating an mzTab-M interoperability workshop to test/improve the readers and writers.
> An R package by@Nils Hoffmannis at[https://github.com/lifs-tools/rmzTab-m/](https://github.com/lifs-tools/rmzTab-m/)


## 2024-11-01

**Kozo Nishida** (03:19:02) (in thread):
> > honestly - for now as tab delimited text files. For the R object to**represent**that data we try to use/stick to the`SummarizedExperiment`.
> Thank you for the information.
> By the way, it seems that there is no culture of sharing the`SummarizedExperiment`objects in the metabolomics community. Could this be because the columns for features and samples in the`SummarizedExperiment`objects are not in a standardized ?

**Kozo Nishida** (03:45:47) (in thread):
> > But we're working also on supporting standardized file formats, such as mzTab-M. Development is currently happening in[https://github.com/rformassspectrometry/MsIO](https://github.com/rformassspectrometry/MsIO).
> feedback/suggestions/contributions welcome.
> I couldn’t find how to create an`MsExperiment`object from the previously mentioned`SummarizedExperiment`. Is there any documentation on this?

**Kozo Nishida** (03:49:17) (in thread):
> > having said that, I would also love to have some data exchange format with MS-DIAL:slightly_smiling_face:
> The feature table exported by MS-DIAL is in a text file format, but its content is exactly the same as the`SummarizedExperiment`.
> Therefore, for me to contribute to MsIO, I need to know an example of converting SummarizedExperiment to MsExperiment.


## 2024-11-04

**Johannes Rainer** (02:09:20) (in thread):
> regarding the lack of sharing`SummarizedExperiment`in the metabolomics community - I also don't know why that's happening. I guess mostly because developers are used to their own data structures and want to stick with them. I actually found the`SummarizedExperiment`great because it does NOT have a rigid/hard-coded format for feature and sample columns.
> 
> For`MsIO`, we don't have a way to get from a`SummarizedExperiment`to a`MsExperiment`. The analysis workflow is`MsExperiment`->`XcmsExperiment`(which extends`MsExperiment`) ->`SummarizedExperiment`(with the preprocessing results). So, for interoperability, it would be great if MS-DIAL results could be imported/loaded as a`SummarizedExperiment`. Ideally, if available, with feature (`rowData`) columns`"mz"`,`"rt"`. that would be the minimum required information to proceed.
> 
> If you have more information, such as MS/MS spectra etc (linked to features) then indeed you would need an`MsExperiment`- with the`SummarizedExperiment`stored in the`@qdata`slot and the MS/MS spectra in the`@spectra`slot.


## 2024-11-06

**Kozo Nishida** (22:32:00) (in thread):
> Jo, thank you for your reply.
> Thanks to you, I now understand what`MsExperiment`is and how I can contribute to`MsIO`.


## 2024-11-13

**Steffen Neumann** (09:58:35):
> Hi, for some time I get the warnings
> ```
> Warning: multiple methods tables found for 'filterFeatures'
>   Warning: multiple methods tables found for 'filterMzRange'
> ```
> when loading xcms

**Steffen Neumann** (09:59:21) (in thread):
> Is that just my local installation, or do we need to fix something in the NAMESPACES across some packages ?

**Steffen Neumann** (10:04:06) (in thread):
> I find them in
> ```
> Spectra/NAMESPACE:exportMethods(filterMzRange)
> xcms/NAMESPACE:exportMethods("filterMzRange")
> ```
> => Does that need fixing ? If so how ?

**Gavin Rhys Lloyd** (10:20:13) (in thread):
> I installed xcms this morning and I dont get these warnings when loading the package (Bioc 3.20, R 4.4.2)

**Steffen Neumann** (10:23:45) (in thread):
> Sounds like my local installation then. Maybe we need some versioned depends that avoid/prevent my combination of packages


## 2024-11-15

**Laurent Gatto** (13:42:38) (in thread):
> I think we should move this method to ProtGenerics.@Johannes Rainer- what do you think?


## 2024-11-18

**Johannes Rainer** (01:31:55) (in thread):
> `filterFeatures`and`filterMzRange`both are already in`ProtGenerics`- and in xcms we are also importing them from ProtGenerics - at least in the version I have locally, which we might still need to merge into the main branch


## 2025-03-18

*17:30:40 - @Nicolo has joined the channel*

## 2025-04-01

**Johannes Rainer** (06:00:15):
> Resource of reproducible workflows (playbooks?) metabolomics data analysis. By@Philippine Louailand contributors.[https://rformassspectrometry.github.io/Metabonaut/](https://rformassspectrometry.github.io/Metabonaut/)
  - Attachment (rformassspectrometry.github.io): [Exploring and Analyzing LC-MS Data](https://rformassspectrometry.github.io/Metabonaut/)
    > This resource hosts tutorials and end-to-end workflows describing how to analyze LC-MS/MS data, from raw files to annotation, using Bioconductor packages.

**Gavin Rhys Lloyd** (06:25:09) (in thread):
> This looks very nice, great job!
> 
> If you are interested I could help you to use structToolbox ([link to vignette](https://computational-metabolomics.github.io/structToolbox/articles/data_analysis_omics_using_the_structtoolbox.html#partial-least-squares-pls-analysis-of-a-untargeted-lc-ms-based-clinical-metabolomics-dataset-)) for the multivariate (and univariate if you liked) section(s). Happy to make extra wrappers for missing steps/charts (e.g. I dont have one for limma... yet).
> 
> Or I could add a pull request to add structToolbox as an alternative example; it might depend if your plan is to showcase workflows using different tools, or not

**Johannes Rainer** (06:53:31) (in thread):
> hey! that's great! ideally a PR with a separate vignette:blush:- loading the data after preprocessing. we can also discuss through github issues at Metabonaut


## 2025-04-02

**Pablo** (05:54:18) (in thread):
> I have been referring to Metabonaut a lot since it's launch! Great job@Philippine Louailand others :)

**Kozo Nishida** (13:07:37):
> Does anyone know if there's a function that returns a SummarizedExperiment of a study in MetaboLights, like the following metabolomicsWorkbenchR do_query function?
> ```
> SE = do_query(
>     context = 'study',
>     input_item = 'study_id',
>     input_value = 'ST000001',
>     output_item = 'SummarizedExperiment' # or 'DatasetExperiment'
> )
> ```

**Gavin Rhys Lloyd** (13:27:48) (in thread):
> MetaboLights is mostly raw data. SummarizedExperiment is better suited to peak tables obtained after processing the raw data.
> You could try something like[https://rformassspectrometry.github.io/MsBackendMetaboLights/](https://rformassspectrometry.github.io/MsBackendMetaboLights/)combined with the xcms package to process the data into a peak table (I think xcms can output the peak table as a SummarisedExperiment).

**Gavin Rhys Lloyd** (13:30:18) (in thread):
> also there is a nice example of this in the Metabonaut repo posted recently:[https://rformassspectrometry.github.io/Metabonaut/articles/a-end-to-end-untargeted-metabolomics.html](https://rformassspectrometry.github.io/Metabonaut/articles/a-end-to-end-untargeted-metabolomics.html)


## 2025-04-03

**Kozo Nishida** (00:35:41) (in thread):
> Thank you for your reply, Gavin.
> Sorry, I didn’t explain myself clearly.
> I wasn’t referring to the raw data in MetaboLights, but rather to the ISA-TAB file format—specifically the files starting with**s_**or**m_**.
> I wanted to ask whether there is already functionality to create a`SummarizedExperiment`from those files.
> It doesn’t seem like that functionality is included in examples MsBackendMetaboLights or Metabonaut either.

**Kozo Nishida** (00:37:52) (in thread):
> And if it turns out that this functionality doesn’t exist anywhere in Bioconductor, I wanted to ask this community where it might make the most sense to add it.

**Kozo Nishida** (00:48:55) (in thread):
> Much of what I want to do is already implemented in[https://github.com/tidymass/massdataset/tree/main/R](https://github.com/tidymass/massdataset/tree/main/R), but it doesn’t support database-backed approaches.
> The massdataset package is in**tidymass**framework, and it is different from Bioconductor.
> I’d like to discuss what kind of approach would be best for the community as a whole (for reading ISA-TABs in MetaboLights).

**Tuomas Borman** (11:14:52) (in thread):
> Hi!
> 
> As part of a larger project, we developed a method for retrieving data tables from MetaboLights. The primary goal of the HoloFoodR package is to fetch data from the HoloFood database. However, for certain data types, the HoloFood database points to MetaboLights, so we created methods to retrieve those data tables.
> 
> Initially, we didn't plan to make the MetaboLights retrieval method directly accessible to users, but rather keep it as internal function. However, today I made it available and did some testing to ensure it works also for data outside this HoloFood project.
> 
> Here is reference page:[https://ebi-metagenomics.github.io/HoloFoodR/reference/getMetaboLights.html](https://ebi-metagenomics.github.io/HoloFoodR/reference/getMetaboLights.html)You can retrieve data specified by study identifier
> ```
> # The latest changes are not yet in Bioc
> remotes::install_github("EBI-Metagenomics/HoloFoodR")
> library(HoloFoodR)
> 
> # Get data as list
> res <- getMetaboLights("MTBLS11993")
> # Get data as SE
> se <- getMetaboLights("MTBLS3540", output = "SE")
> ```
> Is this what you are looking for?
  - Attachment (ebi-metagenomics.github.io): [Get metabolomic data from MetaboLights database — getMetaboLights](https://ebi-metagenomics.github.io/HoloFoodR/reference/getMetaboLights.html)
    > Get metabolomic data from MetaboLights database

**Kozo Nishida** (11:31:19) (in thread):
> Hi! Thank you for your reply!
> Yes that is what I'm looking for! (I think that's very likely.)[https://github.com/EBI-Metagenomics/HoloFoodR/blob/devel/R/getMetaboLights.R#L280](https://github.com/EBI-Metagenomics/HoloFoodR/blob/devel/R/getMetaboLights.R#L280)Unfortunately, I encountered the following error in my environment.
> ```
> > res <- getMetaboLights("MTBLS4381")
> curl::curl_parse_url(url, baseurl = base_url, decode = FALSE) でエラー: 
>   Failed to parse URL: Bad scheme
> ```
> But I’ll ask about it on GitHub Issues instead.[https://github.com/EBI-Metagenomics/HoloFoodR/issues](https://github.com/EBI-Metagenomics/HoloFoodR/issues)Thanks again for your reply—I really appreciate it!

**Tuomas Borman** (11:39:59) (in thread):
> Thanks, I will check it ASAP

**Tuomas Borman** (12:03:44) (in thread):
> I was able to replicate the issue. I had older version of httr2 package. I will fix this today

**Tuomas Borman** (13:04:40) (in thread):
> Not the nicest start, but now the issue is fixed:[https://github.com/EBI-Metagenomics/HoloFoodR/pull/41](https://github.com/EBI-Metagenomics/HoloFoodR/pull/41)Behavior of`httr2::url_parser()`was changed and I had not noticed that.
> 
> Thanks for letting me know@Kozo NishidaPlease tell if you still encounter in problems or have feature requests.

**Leo Lahti** (16:43:17) (in thread):
> Cool! HoloFoodR might not be the most logical place to find the metabolights functionality, so perhaps we could in the longer run consider other, metabolomics oriented packages as a home for it. Just a thought.


## 2025-04-04

**Kozo Nishida** (08:05:58) (in thread):
> Thanks@Tuomas Borman! Now the`getMetaboLights`works fine!
> I have a feature request/question .
> I added it to[https://github.com/EBI-Metagenomics/HoloFoodR/issues/42](https://github.com/EBI-Metagenomics/HoloFoodR/issues/42)
  - Attachment: [#42 When there are multiple maf.tsv files in one MTBLS study](https://github.com/EBI-Metagenomics/HoloFoodR/issues/42)
    > Is there a way to determine from which row the data in rowData comes from a different maf.tsv file when there are multiple maf.tsv files included in one study?
    > 
    > For example [https://www.ebi.ac.uk/metabolights/editor/MTBLS12138/files](https://www.ebi.ac.uk/metabolights/editor/MTBLS12138/files) has the following two maf.tsv files.
    > 
    > • m_MTBLS12138_LC-MS_negative_reverse-phase_metabolite_profiling_v2_maf.tsv (263 rows)
    > • m_MTBLS12138_LC-MS_positive_reverse-phase_metabolite_profiling_v2_maf.tsv (495 rows)
    > 
    > And the SummarizedExperiment object rowData has 758 (==263+495) rows.
    > 
    > ```
    > > res <- getMetaboLights("MTBLS12138", output = "SE")
    > > dim(rowData(res))
    > [1] 758  21
    > 
    > ```
    > 
    > I’m fine with the behavior where the data from the two maf.tsv files are stored in a single SummarizedExperiment object.  
    > However, I wasn’t able to figure out how to determine which rows originated from the positive or negative mode maf.tsv file.  
    > Is there a way to do that?

**Kozo Nishida** (08:08:45) (in thread):
> I agree with Leo. If Tuomas is okay with it, I’d be happy to see the functionality of the`getMetabolites`function contributed to one of the RforMassSpectrometry packages.

**Tuomas Borman** (08:16:13) (in thread):
> I also agree, it would be great if the function were easier to find so more people could benefit from it


## 2025-04-06

**Leo Lahti** (09:52:42) (in thread):
> @Vilhelm Suksiis this something you could have a look at, at least tentatively?

**Vilhelm Suksi** (16:38:31) (in thread):
> Sure, I'll check in with Tuomas as well as consider a suitable package and possible overlap.


## 2025-04-07

**Johannes Rainer** (03:57:58) (in thread):
> Agree with@Leo Lahtion the comment above that such function should be in a maybe more obvious location. We have in the[MsBackendMetaboLights](https://github.com/RforMassSpectrometry/MsBackendMetaboLights)package some utility code already for MetaboLights - PR would be welcome:slightly_smiling_face:- or alternatively the (still under development)[MsIO](https://github.com/RforMassSpectrometry/MsIO)package - where we have currently code to load the raw data + experiment + sample annotations from MetaboLights - as a`MsExperiment`object. We use that in the Metabonaut resource above.
> 
> The`MsExperiment`can be loaded from MetaboLights with
> ```
> mse <- readMsExperiment(MsExperiment(), MetaboLightsParam("MTBLS93"))
> ```
> So, maybe a new
> ```
> se <- readMsExperiment(SummarizedExperiment(), MetaboLightsParam("MTBL93"))
> ```
> would be nice to have?

**Kozo Nishida** (04:07:42) (in thread):
> In case`se <- readMsExperiment(SummarizedExperiment(), MetaboLightsParam("MTBL93"))`, would changes to[https://github.com/rformassspectrometry/MsExperiment/blob/main/R/MsExperiment-functions.R#L391](https://github.com/rformassspectrometry/MsExperiment/blob/main/R/MsExperiment-functions.R#L391)be necessary?
> Or would changes be needed somewhere else?
> I'd appreciate it if you could give me a rough idea of which lines might require code additions/changes.

**Johannes Rainer** (04:13:28) (in thread):
> ideally, it should be in a new R/SummarizedExperiment.R file in[https://github.com/RforMassSpectrometry/MsIO](https://github.com/RforMassSpectrometry/MsIO)- something similar to the code we have for`MsExperiment`in[https://github.com/rformassspectrometry/MsIO/blob/main/R/MsExperiment.R#L214-L295](https://github.com/rformassspectrometry/MsIO/blob/main/R/MsExperiment.R#L214-L295)

**Leo Lahti** (05:55:54) (in thread):
> I am not familiar with MsExperiment but would be good to have support for SummarizedExperiment or TreeSummarizedExperiment , unless there is a strong reason to have MS specific container. I will perhaps need to read more about it too.@Vilhelm Suksiyou can also stay up-to-date on this and we talk later.


## 2025-04-18

*04:43:02 - @Juan Henao has joined the channel*

## 2025-04-23

**Steffen Neumann** (07:10:16):
> Hi<!channel>, if you plan submitting a poster abstract to the Metabolomics conference in Prague, note the (somewhat vague) announcement:[https://www.metabolomics2025.org/abstract-submissions](https://www.metabolomics2025.org/abstract-submissions)Poster Abstract deadline IMPORTANT UPDATE as of April 21
> NOTICE: Due to the high volume of submissions, we will likely need to close poster submission early, as we're quickly approaching capacity for poster presentations. If you're planning to submit please do so as soon as possible to ensure your work is considered. Once we have reached the capacity limit, we will close the submission portal, very likely before May 15.
  - Attachment (Abstract Submissions): [Abstract Submissions - Metabolomics 2025](https://www.metabolomics2025.org/abstract-submissions)
    > Discover groundbreaking metabolomics research at Metabolomics 2025 in Prague.
