---
title: "#microbiome_experiment_bioc2021"
format: gfm
---


## 2021-03-04

*04:54:57 - @Leo Lahti has joined the channel*
**Leo Lahti** (04:54:58):
> set the channel description: Planning channel for Bioc2021

*04:56:06 - @FelixErnst has joined the channel*
*04:56:06 - @Sudarshan has joined the channel*
*04:56:06 - @Domenick Braccia has joined the channel*
*04:56:06 - @Ruizhu HUANG has joined the channel*
**Leo Lahti** (04:56:31):
> Hi all - we were talking about Bioc2021 submission (DL March 9; event in Aug 4-6)

**Leo Lahti** (04:56:31):
> [https://bioc2021.bioconductor.org/](https://bioc2021.bioconductor.org/)
  - Attachment (bioc2021.bioconductor.org): [BioC2021](https://bioc2021.bioconductor.org/)
    > Site template made by devcows using hugo

**Leo Lahti** (04:56:53):
> I have drafted an abstract in google doc

**Leo Lahti** (04:56:54):
> [https://docs.google.com/document/d/1U-amBggNl8ZGubbcBUS2KpERjvKuMVyk3MW2xXXhODk/edit#](https://docs.google.com/document/d/1U-amBggNl8ZGubbcBUS2KpERjvKuMVyk3MW2xXXhODk/edit#)
  - File (Google Docs): [Bioc2021 TSE](https://community-bioc.slack.com/files/U34P8RS3B/F01QB59EU7N/bioc2021_tse)

**Leo Lahti** (04:57:49):
> I did not Hector Bravo from this Bioc slack but we could add him here. Otherwise we are all here, from EuroBioc2020 abstract.

**Leo Lahti** (04:58:06):
> We could also add Tuomas Borman on the author list as he has contributed substantially. I did not add him in this thread yet.

**Leo Lahti** (05:00:06):
> We will need to decide whether a short talk (+ poster?) is enough, or if we also like to arrange BoF or long workshop. I am preparing some training material for courses before that, we could consider having a generic BoF session to briefly discuss the recent developments with the community, or a longer workshop to provide some proper demonstrations (and training?).

**Leo Lahti** (05:00:43):
> Separate abstracts needed for talk&poster and BoF/workshop. I can take care of the practicalities once we agree about the plan.

**Leo Lahti** (05:02:18):
> Oh yes, "package demo" is also a possible presentation format besides BoF/workshop.

**FelixErnst** (09:00:14):
> I am not sure, that I will be able to attend Bioc2021. So everything I could bring to the table is about preperation and feedback

**Leo Lahti** (09:03:36):
> Ok good to know.

**Leo Lahti** (09:03:48):
> I think we should have a short talk (or pkg demo) at least.

*13:04:04 - @Tuomas Borman has joined the channel*

## 2021-03-05

**Leo Lahti** (02:10:30):
> We have DL on March 9 (3-4 days from now). Perhaps I should email those of us who have not reacted. To confirm their participation. I guess it is ok to submit if we do not hear back from them since the author list is the same as in December (plus Tuomas), based on the same stuff.

**Leo Lahti** (14:41:47):
> .. any comments on BoF/workshop? I understand Felix may like to drop out from that discussion if he cannot join Bioc anyway.

**Leo Lahti** (14:42:37):
> I have mixed feelings since it is more work & arrangements and added value difficult to quantify. On the other hand it could be a good opportunity to receive more specific feedback and/or help people getting started with the new stuff.


## 2021-03-06

**Sudarshan** (02:42:13):
> I also think it's much work at this stage :(

**Sudarshan** (02:43:13):
> I will check the abstract today

**Leo Lahti** (05:38:05):
> yeah it is a bit risky to have workshop since things are stlll being set up

**Leo Lahti** (05:38:18):
> BoF or Package demo could work however. We already had one BoF.

**FelixErnst** (07:21:48) (in thread):
> But not a lot has changed since then and I am not sure how much will change until August. I am not sure about it

**Leo Lahti** (07:35:48) (in thread):
> Yep we dont know yet.

**Leo Lahti** (07:36:37) (in thread):
> It is a bit different audience, though.


## 2021-03-07

**Leo Lahti** (03:48:41):
> Ok let's have a short talk + poster then. Unless I get extra energy later today. I am planning to write an email today to all co-authors to ensure that everyone is aware of this plan.

**Ruizhu HUANG** (11:13:52):
> Hi all,
> I am afraid I can’t attend the Bioc2021 either, but would be happy to give feedbacks.

**Leo Lahti** (11:44:17):
> ok great!

**Leo Lahti** (14:31:53):
> Ok I sent email to all co-authors. Hopefully it came through.

**Leo Lahti** (14:32:15):
> @Ruizhu HUANGyour email i apparently got wrong

**Leo Lahti** (14:32:28):
> -- but you know about this abstract already.

**Ruizhu HUANG** (14:34:53):
> Thanks! Yes, I can see the abstract in google doc. My email is :[fionarhuang@gmail.com](mailto:fionarhuang@gmail.com)or[Ruizhu.Huang@cardio-care.ch](mailto:Ruizhu.Huang@cardio-care.ch).

**Leo Lahti** (14:37:39):
> great!

**Ruizhu HUANG** (14:40:30) (in thread):
> Thanks, I have got the email!

**Leo Lahti** (14:48:54) (in thread):
> !


## 2021-03-09

**Leo Lahti** (04:40:11):
> You all should have received submission confirmation now.

**Sudarshan** (05:14:34):
> I have not received it yet

**Leo Lahti** (06:21:28):
> oh

**FelixErnst** (06:21:44) (in thread):
> spam folder?

**Leo Lahti** (06:22:16):
> I used the rivm email. Have you checked spam folder

**Sudarshan** (06:24:55):
> Not in spam/junk folder :(

**Sudarshan** (06:25:24):
> [sudarshan.shetty@rivm.nl](mailto:sudarshan.shetty@rivm.nl)

**Leo Lahti** (06:41:44):
> now?

**Sudarshan** (06:55:55):
> Yes thanks!!


## 2021-03-20

*01:57:45 - @watanabe_st has joined the channel*

## 2021-05-06

*10:38:29 - @Pratheepa Jeganathan has joined the channel*

## 2021-05-11

*16:45:12 - @Megha Lal has joined the channel*

## 2021-05-22

*16:00:33 - @Moritz E. Beber has joined the channel*

## 2021-08-03

**Leo Lahti** (16:47:10):
> Levi's good initiative made me wondering if we should also reserve a table for free chat dedicated to miaverse / TreeSE frameworks on microbiome data science[https://docs.google.com/forms/d/e/1FAIpQLSdIrll5358cH4l7VqUyCq0fU4UBcoXU-DzVChpEtKHvU7AGuw/viewform](https://docs.google.com/forms/d/e/1FAIpQLSdIrll5358cH4l7VqUyCq0fU4UBcoXU-DzVChpEtKHvU7AGuw/viewform)

**Leo Lahti** (16:47:38):
> slightly late but somehow I only came to think about this now


## 2021-08-06

*14:57:24 - @Mercedeh Javanbakht Movassagh has joined the channel*

## 2022-01-28

*11:13:40 - @Megha Lal has left the channel*

## 2022-05-20

*09:06:52 - @Michal has joined the channel*

## 2022-07-31

*04:16:36 - @Arda Keles has joined the channel*

## 2024-01-23

*00:16:20 - @Shruti Shah has joined the channel*

## 2024-05-14

**Lori Shepherd** (10:19:54):
> archived the channel
