---
title: "#multiomics"
---

## 2018-05-19

**Aedin Culhane** (13:32:51):
> @Aedin Culhane has joined the channel


## 2018-06-25

**Elana Fertig** (16:06:35):
> @Elana Fertig has joined the channel

**Alex Hopkins** (18:44:52):
> @Alex Hopkins has joined the channel


## 2018-07-25

**Kasper D. Hansen** (09:06:25):
> @Kasper D. Hansen has joined the channel

**Kasper D. Hansen** (09:08:31):
> Candidate for archive


## 2018-09-24

**Kim-Anh Lê Cao** (21:50:07):
> @Kim-Anh Lê Cao has joined the channel


## 2018-10-04

**Levi Waldron** (13:00:04):
> @Levi Waldron has joined the channel


## 2018-12-21

**Laurent Gatto** (12:03:55):
> @Laurent Gatto has joined the channel


## 2019-01-17

**Lluís Revilla** (07:24:54):
> @Lluís Revilla has joined the channel


## 2019-03-22

**Davide Risso** (11:33:35):
> @Davide Risso has joined the channel


## 2019-03-26

**Dror Berel** (15:02:46):
> @Dror Berel has joined the channel


## 2019-04-17

**Craig** (22:50:43):
> @Craig has joined the channel


## 2019-04-23

**darlanminussi** (12:55:25):
> @darlanminussi has joined the channel


## 2019-05-08

**Ming Tang** (13:50:48):
> @Ming Tang has joined the channel


## 2019-05-21

**Almut** (06:38:15):
> @Almut has joined the channel


## 2019-05-30

**FeiZhao** (18:55:39):
> @FeiZhao has joined the channel


## 2019-06-23

**Krithika Venkataraman** (10:19:27):
> @Krithika Venkataraman has joined the channel


## 2019-06-26

**Junhao Li** (13:28:38):
> @Junhao Li has joined the channel


## 2019-07-12

**Rene Welch** (12:35:55):
> @Rene Welch has joined the channel


## 2019-08-02

**Leo Lahti** (14:32:33):
> @Leo Lahti has joined the channel


## 2019-08-03

**Mikhael Manurung** (13:54:56):
> @Mikhael Manurung has joined the channel


## 2019-08-14

**kipper fletez-brant** (11:50:23):
> @kipper fletez-brant has joined the channel


## 2019-10-04

**Lauren Hsu** (09:17:35):
> @Lauren Hsu has joined the channel


## 2019-10-05

**John Hutchinson** (12:07:02):
> @John Hutchinson has joined the channel


## 2019-10-07

**Kelly Street** (10:25:01):
> @Kelly Street has joined the channel

**Juan Monroy-Nieto** (15:32:54):
> @Juan Monroy-Nieto has joined the channel


## 2019-10-14

**Kathy Sivils** (15:38:26):
> @Kathy Sivils has joined the channel


## 2019-11-04

**Izaskun Mallona** (08:20:57):
> @Izaskun Mallona has joined the channel


## 2019-11-18

**Siyuan Ma** (11:45:32):
> @Siyuan Ma has joined the channel


## 2019-11-25

**Stephanie Hicks** (13:10:37):
> @Stephanie Hicks has joined the channel


## 2019-12-10

**Ludwig Geistlinger** (11:25:34):
> @Ludwig Geistlinger has joined the channel


## 2019-12-17

**Jean Yang** (02:40:22):
> @Jean Yang has joined the channel


## 2020-01-08

**Stephanie Hicks** (12:09:02):
> @Stephanie Hicks has left the channel


## 2020-02-14

**Ines de Santiago** (04:47:07):
> @Ines de Santiago has joined the channel


## 2020-03-25

**Dario Righelli** (09:29:29):
> @Dario Righelli has joined the channel


## 2020-03-27

**ceclaurent** (06:10:36):
> @ceclaurent has joined the channel


## 2020-04-22

**Marcel Ramos Pérez** (09:25:07):
> @Marcel Ramos Pérez has joined the channel

**Marcel Ramos Pérez** (09:43:56):
> archived the channel
