---
title: "#oma-developers"
---

## 2022-04-13

**Leo Lahti** (12:56:13):
> @Leo Lahti has joined the channel

**Leo Lahti** (12:56:13):
> set the channel description: Orchestrating Microbiome Analysis online book development channel

**Himel Mallick** (12:56:40):
> @Himel Mallick has joined the channel

**Sudarshan** (12:56:40):
> @Sudarshan has joined the channel

**Tuomas Borman** (12:56:40):
> @Tuomas Borman has joined the channel

**Giulio Benedetti** (12:56:40):
> @Giulio Benedetti has joined the channel

**FelixErnst** (12:56:40):
> @FelixErnst has joined the channel


## 2022-05-16

**Pedro Sanchez** (07:03:52):
> @Pedro Sanchez has joined the channel


## 2022-05-20

**Michal** (09:06:55):
> @Michal has joined the channel


## 2022-10-27

**Leo Lahti** (05:31:48):
> Bioconductor, supported by the Chan Zuckerberg Initiative's EOSS program, has joined The Carpentries as a member organization to ensure excellence in instruction and to develop infrastructure to create and maintain high-quality, pedagogically-sound training with support for local languages.
> 
> Please apply in the form below if you are interested in becoming one of our 30 certified Carpentries instructors and contributing to the efforts of the Bioconductor teaching community!
> 
> Apply here:[https://forms.gle/TY5FdFckNosJB5x38](https://forms.gle/TY5FdFckNosJB5x38)


## 2022-12-19

**watanabe_st** (20:28:48):
> @watanabe_st has joined the channel


## 2023-01-28

**Leo Lahti** (10:19:25):
> Getting support from this source for the development on the TreeSummarizedExperiment-based R ecosystem?[https://twitter.com/Bioconductor/status/1616427968347181058](https://twitter.com/Bioconductor/status/1616427968347181058)
  - Attachment (twitter): [Attachment](https://twitter.com/Bioconductor/status/1616427968347181058)
> :mega:Bioconductor plans to participate in the [@outreachy](https://twitter.com/outreachy) Mar-Aug 2023 internship cycle. We’re seeking Outreachy interns who would like to work on a Bioconductor project and mentors to propose projects.
> 
> Feb 6 - deadline to apply to be an intern 
> Feb 24 - deadline to submit projects


## 2024-05-14

**Lori Shepherd** (13:13:10):
> archived the channel
