---
title: "#osca-book-club"
---

## 2023-07-03

**U077GTL5S** (21:09:10):
> @U077GTL5S has joined the channel

**U077GTL5S** (21:52:48):
> M1 Mac installation - if you have trouble with installing Bioconductor packages, please check that you have Xcode and GNU Fortran compiler installed as per these instructions:[https://mac.r-project.org/tools/](https://mac.r-project.org/tools/)


## 2023-07-04

**UEF2C8J1K** (00:23:38):
> @UEF2C8J1K has joined the channel

**U1X955E9L** (00:31:11):
> @U1X955E9L has joined the channel

**USLACKBOT** (09:09:22):
> ***community-bioc***has joined this channel by invitation from***Monash Bioinformatics Platform***.

**akurut evelyn** (09:09:22):
> @akurut evelyn has joined the channel


## 2023-07-14

**U03J4HZR83D** (02:08:11):
> @U03J4HZR83D has joined the channel


## 2023-07-16

**U02596KDSKG** (18:37:17):
> @U02596KDSKG has joined the channel


## 2023-07-18

**U077GTL5S** (00:08:07):
> Hey folks, we’re starting our book club tomorrow!***Session 1: 2023-07-19******Time: 2.30pm***Chapters:[Getting scRNAseq Datasets](http://bioconductor.org/books/3.17/OSCA.intro/getting-scrna-seq-datasets.html),[the SingleCellExperiment Class](http://bioconductor.org/books/3.17/OSCA.intro/the-singlecellexperiment-class.html),[Analysis Overview](http://bioconductor.org/books/3.17/OSCA.intro/analysis-overview.html)We’re kicking off the book club with the first sub-book from OSCA - Introductions. We will be skipping the first 2 chapters and focusing on loading single cell data into R and the SingleCellExperiment class. If we have the time, we’ll also delve into the Analysis overview chapter.
  - Attachment (bioconductor.org): [Chapter 3 Getting scRNA-seq datasets | Introduction to Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.17/OSCA.intro/getting-scrna-seq-datasets.html)
> Chapter 3 Getting scRNA-seq datasets | Introduction to Single-Cell Analysis with Bioconductor
  - Attachment (bioconductor.org): [Chapter 4 The SingleCellExperiment class | Introduction to Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.17/OSCA.intro/the-singlecellexperiment-class.html)
> Chapter 4 The SingleCellExperiment class | Introduction to Single-Cell Analysis with Bioconductor
  - Attachment (bioconductor.org): [Chapter 5 Analysis overview | Introduction to Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.17/OSCA.intro/analysis-overview.html)
> Chapter 5 Analysis overview | Introduction to Single-Cell Analysis with Bioconductor


## 2023-07-19

**U04CP3TU7** (01:31:35):
> @U04CP3TU7 has joined the channel

**U04CZ95DE** (01:32:18):
> @U04CZ95DE has joined the channel

**U018JNZQF5G** (01:32:54):
> @U018JNZQF5G has joined the channel


## 2023-07-28

**Benjamin Yang** (15:58:14):
> @Benjamin Yang has joined the channel


## 2023-08-01

**U077GTL5S** (18:29:28):
> Hey folks, we have book club today!***Session 2: 2023-08-02******Time: 2.30pm AEST***Chapters: the[SingleCellExperiment Class](http://bioconductor.org/books/3.17/OSCA.intro/the-singlecellexperiment-class.html),[Analysis Overview](http://bioconductor.org/books/3.17/OSCA.intro/analysis-overview.html#quick-start-simple)We’re finishing off the Introductions book today. We will continue from where we left off with the SingleCellExperiment class and go through the analysis overview. If we have the time, we’ll start the Basics book and begin the[Quality Control chapter](http://bioconductor.org/books/3.17/OSCA.basic/quality-control.html)
  - Attachment (bioconductor.org): [Chapter 4 The SingleCellExperiment class | Introduction to Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.17/OSCA.intro/the-singlecellexperiment-class.html)
> Chapter 4 The SingleCellExperiment class | Introduction to Single-Cell Analysis with Bioconductor
  - Attachment (bioconductor.org): [Chapter 5 Analysis overview | Introduction to Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.17/OSCA.intro/analysis-overview.html#quick-start-simple)
> Chapter 5 Analysis overview | Introduction to Single-Cell Analysis with Bioconductor
  - Attachment (bioconductor.org): [Chapter 1 Quality Control | Basics of Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.17/OSCA.basic/quality-control.html)
> Chapter 1 Quality Control | Basics of Single-Cell Analysis with Bioconductor

**U1X955E9L** (19:44:29):
> @U1X955E9L has left the channel


## 2023-08-02

**U03S8NHSP47** (01:48:00):
> @U03S8NHSP47 has joined the channel


## 2023-08-15

**U077GTL5S** (22:20:47):
> Just a reminder, we have book club today!***Session 3: 2023-08-02******Time: 2.30pm AEST******Location: room 204, level 2, 19 Innovation Walk or join us on ***[zoom](https://monash.us12.list-manage.com/track/click?u=85d4a2121c4d9c77802612bc0&id=9be06738f3&e=580b18f096)Chapters:[Quality Control](http://bioconductor.org/books/3.17/OSCA.basic/quality-control.html)We’re starting the Basics book today and dig into the quality control metrics we look at with single cell data.
  - Attachment (Zoom Video): [Join our Cloud HD Video Meeting](https://monash.us12.list-manage.com/track/click?u=85d4a2121c4d9c77802612bc0&amp;id=9be06738f3&amp;e=580b18f096)
> Zoom is the leader in modern enterprise video communications, with an easy, reliable cloud platform for video and audio conferencing, chat, and webinars across mobile, desktop, and room systems. Zoom Rooms is the original software-based conference room solution used around the world in board, conference, huddle, and training rooms, as well as executive offices and classrooms. Founded in 2011, Zoom helps businesses and organizations bring their teams together in a frictionless environment to get more done. Zoom is a publicly traded company headquartered in San Jose, CA.
  - Attachment (bioconductor.org): [Chapter 1 Quality Control | Basics of Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.17/OSCA.basic/quality-control.html)
> Chapter 1 Quality Control | Basics of Single-Cell Analysis with Bioconductor


## 2023-09-06

**U077GTL5S** (01:05:14):
> [https://www.nature.com/articles/nmeth.4292/figures/1](https://www.nature.com/articles/nmeth.4292/figures/1)
  - File (PNG): [image.png](https://monashbioinformatics.slack.com/files/U34P8RS3B/F05R6AV057W/image.png)


## 2023-10-08

**Maximilian** (16:02:27):
> @Maximilian has joined the channel


## 2024-02-27

**UC8GHQQHJ** (21:05:56):
> @UC8GHQQHJ has joined the channel

**UC8GHQQHJ** (21:21:06):
> Hi Everyone. I hope you are excited to restart bookclub today. Just some notes previous to the session.
> 
> - We are working today on Clustering ([https://bioconductor.org/books/3.18/OSCA.basic/clustering.html](https://bioconductor.org/books/3.18/OSCA.basic/clustering.html))
> - Please try to set up your code using the code here from 3.1-3.6 ([https://bioconductor.org/books/3.18/OSCA.workflows/unfiltered-human-pbmcs-10x-genomics.html#unfiltered-human-pbmcs-10x-genomics](https://bioconductor.org/books/3.18/OSCA.workflows/unfiltered-human-pbmcs-10x-genomics.html#unfiltered-human-pbmcs-10x-genomics))
> - you may face some error because of some updates in packages like dbplyr and matrix
> 
> If your error looks like:`Error in `collect()`:`` ! Failed to collect lazy table.``Caused by error in `db_collect()`:`` ! Arguments in `...` must be used.``✖ Problematic argument:`` • ..1 = Inf``ℹ Did you misspell an argument name?`You need to downgrade dbplyr: run`devtools::install_version("dbplyr", version = "2.3.4")`and***restart your Rstudio***If your error looks like this:`Error in function 'as_cholmod_sparse' not provided by package 'Matrix' `You need to downgrade Matrix: run`remotes::install_version("Matrix", version = "1.6-1.1") `and***restart your Rstudio***
  - Attachment (bioconductor.org): [Chapter 5 Clustering | Basics of Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/3.18/OSCA.basic/clustering.html)
> Chapter 5 Clustering | Basics of Single-Cell Analysis with Bioconductor
  - Attachment (bioconductor.org): [Chapter 3 Unfiltered human PBMCs (10X Genomics) | Single-Cell Analysis Workflows with Bioconductor](https://bioconductor.org/books/3.18/OSCA.workflows/unfiltered-human-pbmcs-10x-genomics.html#unfiltered-human-pbmcs-10x-genomics)
> Chapter 3 Unfiltered human PBMCs (10X Genomics) | Single-Cell Analysis Workflows with Bioconductor

**UC8GHQQHJ** (23:18:36):
> ```
> colLabels(sce.pbmc) <-clust.num
> plotReducedDim(sce.pbmc, "TSNE", colour_by="label")
> 
> cluster1<-subset(sce.pbmc, , label=="1")
> cluster2<-subset(sce.pbmc, , label=="2")
> 
> p1<-plotExpression(cluster1, top.pbmc[1:20])
> p2<-plotExpression(cluster2, top.pbmc[1:20])
> gridExtra::grid.arrange(p1,p2)
> ```

**UC8GHQQHJ** (23:51:39):
> Why TSNE is not my preferred method (This paper was around since 2018 but it looks like it only got publish last year:thinking_face:)[https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011288](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011288)
  - Attachment (journals.plos.org): [The specious art of single-cell genomics](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011288)
> Dimensionality reduction is standard practice for filtering noise and identifying relevant features in large-scale data analyses. In biology, single-cell genomics studies typically begin with reduction to 2 or 3 dimensions to produce “all-in-one” visuals of the data that are amenable to the human eye, and these are subsequently used for qualitative and quantitative exploratory analysis. However, there is little theoretical support for this practice, and we show that extreme dimension reduction, from hundreds or thousands of dimensions to 2, inevitably induces significant distortion of high-dimensional datasets. We therefore examine the practical implications of low-dimensional embedding of single-cell data and find that extensive distortions and inconsistent practices make such embeddings counter-productive for exploratory, biological analyses. In lieu of this, we discuss alternative approaches for conducting targeted embedding and feature exploration to enable hypothesis-driven biological discovery.

**UC8GHQQHJ** (23:53:10):
> This is<@U04CZ95DE>packages for visualisation of high dimensional data:[https://github.com/pfh/langevitour](https://github.com/pfh/langevitour)


## 2024-02-28

**U04CZ95DE** (00:28:08):
> Interestingly the default scran "walktrap" clustering algorithm is hierarchical (similar to hclust). You can ask for as many clusters as you like without recomputing the clustering:
> ```
> nn.clust.info <- clusterCells(sce.pbmc, use.dimred="PCA", full=TRUE)
> nn.clust.info$objects$communities
> colLabels(sce.pbmc) <- 
>     igraph::cut_at(nn.clust.info$objects$communities, 9) |>
>     factor()
> plotReducedDim(sce.pbmc, "UMAP", colour_by="label")
> ```

**U04CZ95DE** (00:32:29) (in thread):
> You don't need UMAP. With this you can look at the 50 dimension PCA directly :-P
> 
> If you want a 3D or 4D UMAP, that's fine too. :-)


## 2024-03-26

**U04CP3TU7** (23:47:00):
> [https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03183-0#Tab1](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03183-0#Tab1)
  - Attachment (BioMed Central): [A comparison of marker gene selection methods for single-cell RNA sequencing data - Genome Biology](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03183-0#Tab1)
> Background The development of single-cell RNA sequencing (scRNA-seq) has enabled scientists to catalog and probe the transcriptional heterogeneity of individual cells in unprecedented detail. A common step in the analysis of scRNA-seq data is the selection of so-called marker genes, most commonly to enable annotation of the biological cell types present in the sample. In this paper, we benchmark 59 computational methods for selecting marker genes in scRNA-seq data. Results We compare the performance of the methods using 14 real scRNA-seq datasets and over 170 additional simulated datasets. Methods are compared on their ability to recover simulated and expert-annotated marker genes, the predictive performance and characteristics of the gene sets they select, their memory usage and speed, and their implementation quality. In addition, various case studies are used to scrutinize the most commonly used methods, highlighting issues and inconsistencies. Conclusions Overall, we present a comprehensive evaluation of methods for selecting marker genes in scRNA-seq data. Our results highlight the efficacy of simple methods, especially the Wilcoxon rank-sum test, Student’s t-test, and logistic regression.


## 2024-03-27

**U077GTL5S** (01:06:07):
> ```
> The concept of the marker gene is closely related to that of the differentially expressed (DE) gene, but the two concepts are not synonymous. Strictly, marker gene selection is a subset of the identification of DE genes, but effective and useful marker genes have specific characteristics that are not shared by all DE genes. Broadly, we define a marker gene as a gene that can be used to distinguish between sub-populations of cells. Good marker genes typically exhibit a large difference in expression between cell types and, canonically, are strongly up-regulated in a cell type of interest, exhibiting high expression in that cell type and no or low expression in other cell types. Thus, a marker gene is a narrower, more specific concept than that of a DE gene, which is context dependent. In the analysis of scRNA-seq data, the term DE gene does not have a unique meaning as it refers generally to a gene that shows a statistically significant difference in expression in a specific comparison. DE genes can therefore refer to genes found in a comparison between cells in different clusters in the same sample or in the same cluster between different samples, or to a comparison between arbitrary groups of cells. When DE methods are used to identify marker genes a decision has to be made about how to map the idea (and desirable characteristics) of marker genes to a concrete between-groups comparison
> ...
> As such, marker gene selection used for distinguishing between sub-populations of cells is conceptually and practically a distinctly different task from the more general challenge of identification of all genes with statistically significant differences in expression in a given comparison context, with no consideration for whether or not detected DE genes are useful for distinguishing a given group of cells from others.
> ```
> This!!!! This passage gets at what I was struggling to articulate at the start of the book club - marker gene selection isn’t exactly the same thing as DEG but the Seurat pbmc tutorial (and most tutorials in general tbh) treats it as if it is.


## 2024-05-08

**U04CP3TU7** (01:02:01):
> [https://www.youtube.com/watch?v=XtjZRZFzUVw](https://www.youtube.com/watch?v=XtjZRZFzUVw)
  - Attachment (YouTube): [Single-cell gene set activity with AUCell](https://www.youtube.com/watch?v=XtjZRZFzUVw)

**UC8GHQQHJ** (01:12:16):
> Cell type from pathways machine learning[https://academic.oup.com/bib/article/25/1/bbad449/7461884](https://academic.oup.com/bib/article/25/1/bbad449/7461884)

**UC8GHQQHJ** (01:12:45):
> Cell type using pathways:[https://www.nature.com/articles/s42003-023-05634-z](https://www.nature.com/articles/s42003-023-05634-z)
  - Attachment (Nature): [scPML: pathway-based multi-view learning for cell type annotation from single-cell RNA-seq data](https://www.nature.com/articles/s42003-023-05634-z)
> Communications Biology - scPML is a pathway-based multi-view learning model that outperforms alternative approaches in cell type annotation and detecting unknown cell types across diverse species,...

**U03S8NHSP47** (01:29:47):
> challenges in current deep learning approaches faced within scRNA-seq data[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10025684/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10025684/)
  - Attachment (PubMed Central (PMC)): [Application of Deep Learning on Single-cell RNA Sequencing Data Analysis: A Review](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10025684/)
> Single-cell RNA sequencing (scRNA-seq) has become a routinely used technique to quantify the gene expression profile of thousands of single cells simultaneously. Analysis of scRNA-seq data plays an important role in the study of cell states and phenotypes, ...


## 2024-11-21

**U04CZ95DE** (22:03:10):
> @U04CZ95DE has left the channel


## 2024-12-18

**Michael Totty** (15:03:40):
> @Michael Totty has joined the channel
