---
title: "#pangenome"
format: gfm
---


## 2024-07-25

*13:49:02 - @Lori Shepherd has joined the channel*
*13:49:20 - @Hervé Pagès has joined the channel*
*13:49:53 - @Pascal Belleau has joined the channel*
*13:49:54 - @Tim Triche has joined the channel*
**Lori Shepherd** (13:50:23):
> set the channel description: Discuss pangenome-related activities in Bioconductor

**Lori Shepherd** (13:50:31):
> set the channel topic: Discuss pangenome-related activities in Bioconductor

*14:11:42 - @Pascal Belleau has joined the channel*
**Pascal Belleau** (16:01:44):
> Welcome to Pangenome channel
> 
> As a starting point, the pangenome management in Bioconductor, at my knowledge, is at the beginning and it would be useful to try define the first small aims of the groups.


## 2024-07-26

**Pascal Belleau** (15:46:58):
> Minigraph-cactus :[https://www.nature.com/articles/s41587-023-01793-w](https://www.nature.com/articles/s41587-023-01793-w)
  - Attachment (Nature): [Pangenome graph construction from genome alignments with Minigraph-Cactus](https://www.nature.com/articles/s41587-023-01793-w)
    > Nature Biotechnology - Constructing genome graphs directly from genome assemblies overcomes single-reference bias.

*16:31:05 - @Astrid Deschenes has joined the channel*
*17:16:46 - @Vince Carey has joined the channel*

## 2024-07-28

**Tim Triche** (13:38:27):
> The big contrast is pggb versus minigraph-cactus versus paragraph

**Tim Triche** (13:40:20):
> I will rope in my people and Erik so that we can lay out the pluses and minuses.Heng Li and Ben Langmead have both been working on faster aligners to locally linearized graphs, but assembly is a matter of speed vs reference-bias-free (I.e. whether it matters which assembly you start with in building the graph)

*13:41:14 - @Lauren Harmon has joined the channel*
*13:41:14 - @Peter(Yizhou) Huang has joined the channel*
**Tim Triche** (13:41:37):
> Looks like I need to invite Erik and Heng to community-BioC slack

**Tim Triche** (13:42:34):
> Arang Rhie and Adam Phillipy at NIH also have a ton of practical experience with this.Karen Miga and Angela Brooks at UCSC as well


## 2024-08-03

**Pascal Belleau** (12:22:13):
> I am adding the link to the pggb paper.[https://www.biorxiv.org/content/10.1101/2023.04.05.535718v1](https://www.biorxiv.org/content/10.1101/2023.04.05.535718v1)
  - Attachment (bioRxiv): [Building pangenome graphs](https://www.biorxiv.org/content/10.1101/2023.04.05.535718v1)
    > Pangenome graphs can represent all variation between multiple genomes, but existing methods for constructing them are biased due to reference-guided approaches. In response, we have developed PanGenome Graph Builder (PGGB), a reference-free pipeline for constructing unbi-ased pangenome graphs. PGGB uses all-to-all whole-genome alignments and learned graph embeddings to build and iteratively refine a model in which we can identify variation, measure conservation, detect recombination events, and infer phylogenetic relationships.
    > 
    > ### Competing Interest Statement
    > 
    > Author J.H. is employed by Computomics GmbH.


## 2024-11-15

*09:00:30 - @Stevie Pederson has joined the channel*

## 2024-11-25

*16:18:55 - @rohitsatyam102 has joined the channel*