---
title: "#pharmacogenomics"
format: gfm
---

## 2017-09-01

**Sean Davis** (10:48:47):
> @Sean Davis has joined the channel

**Sean Davis** (10:48:47):
> set the channel description: Discuss pharmacogenomics approaches, with a focus on machine learning, drug response and target prediction, and repositioning

**Sean Davis** (10:51:49):
> Amazing package:[https://bioconductor.org/packages/ChemmineR](https://bioconductor.org/packages/ChemmineR)
  - Attachment (Bioconductor): [ChemmineR](https://bioconductor.org/packages/ChemmineR)
> ChemmineR is a cheminformatics package for analyzing drug-like small molecule data in R. Its latest version contains functions for efficient processing of large numbers of molecules, physicochemical/structural property predictions, structural similarity searching, classification and clustering of compound libraries with a wide spectrum of algorithms. In addition, it offers visualization functions for compound clustering results and chemical structures.

**Sean Davis** (10:53:36):
> And another:[https://bioconductor.org/packages/PharmacoGx](https://bioconductor.org/packages/PharmacoGx)
  - Attachment (Bioconductor): [PharmacoGx](https://bioconductor.org/packages/PharmacoGx)
> Contains a set of functions to perform large-scale analysis of pharmacogenomic data.

**Martin Morgan** (11:15:16):
> @Martin Morgan has joined the channel

**Thomas Girke** (12:36:57):
> @Thomas Girke has joined the channel

**Thomas Girke** (12:58:24):
> Thanks for the invitation. I also invited Kevin Horan in my group who is always a great resource.

**Sean Davis** (12:59:00):
> Thanks for coming,@Thomas Girke.

**Benjamin Haibe-Kains** (12:59:11):
> @Benjamin Haibe-Kains has joined the channel


## 2017-09-05

**Benjamin Haibe-Kains** (09:11:45):
> If you are wondering whether a cell line and/or a drug have been already tested in a published pharmacogenomic dataset, check out***PharmacoDB***:[http://pharmacodb.pmgenomics.ca/](http://pharmacodb.pmgenomics.ca/)
  - Attachment (pharmacodb.pmgenomics.ca): [PharmacoDB](http://pharmacodb.pmgenomics.ca/)
> Efficiently mine multiple large-scale pharmacogenomic datasets.

**Benjamin Haibe-Kains** (09:12:34):
> Still under development but hopefully providing an easy way to mine***PharmacoGx***Feedback is more than welcome!:[https://github.com/bhklab/PharmacoDB/issues](https://github.com/bhklab/PharmacoDB/issues)
  - Attachment (GitHub): [bhklab/PharmacoDB](https://github.com/bhklab/PharmacoDB/issues)
> PharmacoDB - Search across publicly available datasets to find instances where a drug or cell line of interest has been profiled.

**Sean Davis** (09:17:58):
> Great,@Benjamin Haibe-Kains.[https://twitter.com/seandavis12/status/905057195800358912](https://twitter.com/seandavis12/status/905057195800358912)
  - Attachment (twitter): [Attachment](https://twitter.com/seandavis12/status/905057195800358912)
> Thanks [@bhaibeka](https://twitter.com/bhaibeka) for pointing out PharmacoDB, DB of #pharmacogenomic datasets and expts: 
> [http://pharmacodb.pmgenomics.ca/](http://pharmacodb.pmgenomics.ca/)
> & [https://github.com/bhklab/PharmacoDB/issues](https://github.com/bhklab/PharmacoDB/issues) [https://pbs.twimg.com/media/DI9ouAvXgAEh9Ut.jpg](https://pbs.twimg.com/media/DI9ouAvXgAEh9Ut.jpg)

**Benjamin Haibe-Kains** (10:50:07):
> Cool:slightly_smiling_face:

**Sean Davis** (14:33:46):
> Another dataset that might interest this group:[https://wiki.nci.nih.gov/display/NCIDTPdata/NCI-ALMANAC](https://wiki.nci.nih.gov/display/NCIDTPdata/NCI-ALMANAC)and[https://www.ncbi.nlm.nih.gov/pubmed/28446463](https://www.ncbi.nlm.nih.gov/pubmed/28446463)To date, over 100 small-molecule oncology drugs have been approved by the FDA. Because of the inherent heterogeneity of tumors, these small molecules are often administered in combination to prevent emergence of resistant cell subpopulations. Therefore, new combination strategies to overcome drug resistance in patients with advanced cancer are needed. In this study, we performed a systematic evaluation of the therapeutic activity of over 5,000 pairs of FDA-approved cancer drugs against a panel of 60 well-characterized human tumor cell lines (NCI-60) to uncover combinations with greater than additive growth-inhibitory activity. Screening results were compiled into a database, termed the NCI-ALMANAC (A Large Matrix of Anti-Neoplastic Agent Combinations), publicly available at[https://dtp.cancer.gov/ncialmanac](https://dtp.cancer.gov/ncialmanac)Subsequent in vivo experiments in mouse xenograft models of human cancer confirmed combinations with greater than single-agent efficacy. Concomitant detection of mechanistic biomarkers for these combinations in vivo supported the initiation of two phase I clinical trials at the NCI to evaluate clofarabine with bortezomib and nilotinib with paclitaxel in patients with advanced cancer. Consequently, the hypothesis-generating NCI-ALMANAC web-based resource has demonstrated value in identifying promising combinations of approved drugs with potent anticancer activity for further mechanistic study and translation to clinical trials.

**Benjamin Haibe-Kains** (15:25:45):
> We are working on it. We are extending PharmacoGx to handle drug combinations. Hopefully ready with NCI-ALMANAC early next***year***

**Sean Davis** (15:51:21):
> Awesome! I like the#pharmacogenomicschannel already!

**Benjamin Haibe-Kains** (15:57:39):
> Sorry, instead of early next week, I meant early next***year***. Sometimes, my dreams take over:slightly_smiling_face:

**Sean Davis** (16:56:19):
> That works, also. That dataset is pretty complicated.

**Keegan Korthauer** (17:21:50):
> @Keegan Korthauer has joined the channel

**Vince Carey** (19:17:47):
> @Vince Carey has joined the channel


## 2017-09-07

**Benjamin Haibe-Kains** (11:00:13):
> @Benjamin Haibe-Kainsuploaded a file:[projects-pharmacogx-future_psets \[BHK Lab Wiki\].pdf](https://community-bioc.slack.com/files/bhaibeka/F6ZPDJ2R3/projects-pharmacogx-future_psets__bhk_lab_wiki_.pdf)and commented: List of datasets we would lov love integrate in PharmacoGx (if we had an army of bright students). You may find some studies of interest
  - File (PDF): [projects-pharmacogx-future_psets [BHK Lab Wiki].pdf](https://community-bioc.slack.com/files/U34P8RS3B/F6ZPDJ2R3/projects-pharmacogx-future_psets__bhk_lab_wiki_.pdf)

**Sean Davis** (11:22:44):
> Wow,@Benjamin Haibe-Kains, that looks like a little bit of work planned!

**Sean Davis** (11:24:44):
> Do you have a “workflow” that you use for creating psets, or is it the usual “munge-check-remunge-repeat”?

**Benjamin Haibe-Kains** (11:34:08):
> A bit of both
> -->[https://bioconductor.org/packages/release/bioc/vignettes/PharmacoGx/inst/doc/CreatingPharmacoSet.pdf](https://bioconductor.org/packages/release/bioc/vignettes/PharmacoGx/inst/doc/CreatingPharmacoSet.pdf)


## 2017-09-20

**Ludwig Geistlinger** (12:43:16):
> @Ludwig Geistlinger has joined the channel


## 2017-09-24

**hcorrada** (20:01:01):
> @hcorrada has joined the channel


## 2017-10-18

**Sean Davis** (10:09:33):
> [http://genome.cshlp.org/content/27/10/1743](http://genome.cshlp.org/content/27/10/1743)presented at #ASHG2017
  - Attachment (genome.cshlp.org): [Discovering novel pharmacogenomic biomarkers by imputing drug response in cancer patients from large genomics studies](http://genome.cshlp.org/content/27/10/1743)
> An international, peer-reviewed genome sciences journal featuring outstanding original research that offers novel insights into the biology of all organisms

**Benjamin Haibe-Kains** (13:37:24):
> We have analyzed this paper in our journal club series: the overall idea is very interesting but the authors make a very strong assumption. They assume that the gene expression-based predictors they built using an old version of GDSC are relevant to predict therapy response in patients. There is a bunch of labs, including mine, trying to demonstrate that this is feasible (and we are unsuccessful so far), so it is not reasonable to make such an assumption (the Genome Biology 2014 paper from the same authors provide only anecdotal evidence that it might work). Actually, I can show their models do not predict drug response in independent in vitro datasets (genome research does not accept critiques so I gave up but it is easy to show). If you cannot predict in vitro, why would it work in vivo? In conclusion, their assumption is badly violated and jeopardize the vast majority of their findings. It might work for a few drugs like lapatinib, but you did not need their approach to “discover” that ERBB2 amplification is associated with lapatinib response in patients … I might have missed something, so I would be happy if anyone proves me wrong!

**Benjamin Haibe-Kains** (14:01:13):
> Our manuscript on PharmacoDB has been published:[http://bit.ly/2yy7tgD](http://bit.ly/2yy7tgD)

**Sean Davis** (14:06:51):
> We had the same limited experience with the nci60 data. In the talk, they gave a few examples of true positives in the sense that they showed that gene inactivation by mutation in some samples was predicted to be "responsive" to a known targeting drug. In my experience, these are low-hanging fruits, but still....

**Sean Davis** (14:07:22):
> Congrats on the paper. I'll tweet it out later!

**Benjamin Haibe-Kains** (14:07:48):
> I think that is the main issue with this paper. A few low-hanging fruits or positive controls, does***not***justify their approach

**Sean Davis** (14:08:27):
> Totally agree.

**Benjamin Haibe-Kains** (14:09:37):
> Re: PharmacoDB: we have to fix the feedback and the batch query pages but it shoudl be done today. Feedback welcome


## 2017-10-19

**Sean Davis** (11:25:09):
> Another pub to read:[http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005599](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005599)
  - Attachment (journals.plos.org): [Systematic, network-based characterization of therapeutic target inhibitors](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005599)
> Author summary Most transcription factors are considered “undruggable” in conventional drug discovery. However, a large number of them are discovered to be key tumor dependencies. Thus, targeting these difficult targets has been a challenge for cancer drug discovery. Here, we introduce a novel method, OncoLead, that applies biological networks to identify candidate inhibitors that either directly or in-directly block the activities of these targets. This approach is confirmed by known target-inhibitor interactions in public databases. Furthermore, we predicted new inhibitors for MYC and STAT3, which are validated by in vitro assays.


## 2017-10-27

**Nicholas Clark** (11:42:24):
> @Nicholas Clark has joined the channel


## 2017-11-04

**Sean Davis** (06:15:27):
> [https://www.nature.com/articles/s41467-017-01383-w](https://www.nature.com/articles/s41467-017-01383-w)
  - Attachment (Nature Communications): [Common and cell-type specific responses to anti-cancer drugs revealed](https://www.nature.com/articles/s41467-017-01383-w)
> Understanding why some tumor cells respond to therapy and others do not is essential for advancing precision cancer care. Here, the authors perform large-scale transcriptomic profiling of breast cance

**Sean Davis** (06:17:36):
> [http://www.lincsproject.org/LINCS/data/overview](http://www.lincsproject.org/LINCS/data/overview)


## 2017-11-09

**Parham Solaimani** (11:34:28):
> @Parham Solaimani has joined the channel


## 2017-11-28

**Simina Boca** (14:27:31):
> @Simina Boca has joined the channel


## 2017-12-15

**Lori Shepherd** (08:05:17):
> @Lori Shepherd has joined the channel


## 2017-12-27

**Marcel Ramos Pérez** (14:16:51):
> @Marcel Ramos Pérez has joined the channel


## 2018-02-14

**Sean Davis** (08:33:09):
> Results from the AstraZeneca DREAM Challenge:[https://www.biorxiv.org/content/early/2018/02/13/200451](https://www.biorxiv.org/content/early/2018/02/13/200451)
  - Attachment (bioRxiv): [A cancer pharmacogenomic screen powering crowd-sourced advancement of drug combination prediction](https://www.biorxiv.org/content/early/2018/02/13/200451)
> The effectiveness of most cancer targeted therapies is short lived since tumors evolve and develop resistance. Combinations of drugs offer the potential to overcome resistance, however the number of possible combinations is vast necessitating data-driven approaches to find optimal treatments tailored to a patient's tumor. AstraZeneca carried out 11,576 experiments on 910 drug combinations across 85 cancer cell lines, recapitulating in vivo response profiles. These data, the largest openly available screen, were hosted by DREAM alongside deep molecular characterization from the Sanger Institute for a Challenge to computationally predict synergistic drug pairs and associated biomarkers. 160 teams participated to provide the most comprehensive methodological development and subsequent benchmarking to date. Winning methods incorporated prior knowledge of putative drug target interactions. For >60% of drug combinations synergy was reproducibly predicted with an accuracy matching biological replicate experiments, however 20% of drug combinations were poorly predicted by all methods. Genomic rationale for synergy predictions were identified, including antagonism unique to combined PIK3CB/D inhibition with the ADAM17 inhibitor where synergy is seen with other PI3K pathway inhibitors. All data, methods and code are freely available as a resource to the community.


## 2018-03-27

**Jayaram Kancherla** (08:39:26):
> @Jayaram Kancherla has joined the channel


## 2018-04-18

**Aedin Culhane** (18:56:21):
> @Aedin Culhane has joined the channel


## 2018-06-26

**Elana Fertig** (08:37:35):
> @Elana Fertig has joined the channel


## 2018-07-25

**Petr Smirnov** (15:12:08):
> @Petr Smirnov has joined the channel

**Petr Smirnov** (15:14:06):
> I made some example code public for the “long sql table” like object here:[https://github.com/bhklab/longArray](https://github.com/bhklab/longArray)
  - Attachment (GitHub): [bhklab/longArray](https://github.com/bhklab/longArray)
> longArray Example

**Petr Smirnov** (16:01:54):
> @Levi Waldron

**Derek Nedveck** (16:02:02):
> @Derek Nedveck has joined the channel

**Levi Waldron** (16:02:59):
> @Levi Waldron has joined the channel

**Lucas Schiffer** (16:03:16):
> @Lucas Schiffer has joined the channel

**Sehyun Oh** (16:03:21):
> @Sehyun Oh has joined the channel

**solomon shorser** (16:08:12):
> @solomon shorser has joined the channel

**Eric Milliman** (18:35:17):
> @Eric Milliman has joined the channel


## 2018-07-28

**Vince Carey** (08:06:29):
> [https://github.com/vjcitn/longArray/tree/vince](https://github.com/vjcitn/longArray/tree/vince)reorganizes longArray as a package pharmGxComb, and includes a vignette speculating about use cases
  - Attachment (GitHub): [vjcitn/longArray](https://github.com/vjcitn/longArray/tree/vince)
> longArray Example


## 2018-07-29

**Levi Waldron** (12:06:20):
> @Sean Davisyou’re really catching on to the enhanced messaging!


## 2018-07-30

**Samuela Pollack** (13:49:06):
> @Samuela Pollack has joined the channel

**Aedin Culhane** (16:43:52):
> @Sean Daviswhat is a fast parrot supposed to represent????

**Marcel Ramos Pérez** (16:48:04):
> My guess is excitement:grin:

**Petr Smirnov** (16:51:24):
> :fast_parrot:

**Sean Davis** (21:36:56):
> @Aedin Culhane, the fast parrot is really beyond words to express. However,@Marcel Ramos Pérezhas clearly gotten the sense of the message with his teethy smile.


## 2018-07-31

**Levi Waldron** (01:25:35):
> I’ve lost track of whether fiesta parrots or fast parrots are related to pharmacogenomics or we’ve gotten off-topic. But they’re two different parrots.

**Aedin Culhane** (15:30:23):
> We need a dancing fast bioconductor symbol


## 2018-09-07

**Sean Davis** (08:14:10):
> [https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-018-0189-6](https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-018-0189-6)
  - Attachment (Journal of Biomedical Semantics): [Using predicate and provenance information from a knowledge graph for drug efficacy screening](https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-018-0189-6)
> Biomedical knowledge graphs have become important tools to computationally analyse the comprehensive body of biomedical knowledge. They represent knowledge as subject-predicate-object triples, in which the predicate indicates the relationship between subject and object. A triple can also contain provenance information, which consists of references to the sources of the triple (e.g. scientific publications or database entries). Knowledge graphs have been used to classify drug-disease pairs for drug efficacy screening, but existing computational methods have often ignored predicate and provenance information. Using this information, we aimed to develop a supervised machine learning classifier and determine the added value of predicate and provenance information for drug efficacy screening. To ensure the biological plausibility of our method we performed our research on the protein level, where drugs are represented by their drug target proteins, and diseases by their disease proteins. Using random forests with repeated 10-fold cross-validation, our method achieved an area under the&nbsp;ROC curve (AUC) of 78.1% and 74.3% for two reference sets. We benchmarked against a state-of-the-art knowledge-graph technique that does not use predicate and provenance information, obtaining AUCs of 65.6% and 64.6%, respectively. Classifiers that only used predicate information performed superior to classifiers that only used provenance information, but using both performed best. We conclude that both predicate and provenance information provide added value for drug efficacy screening.

**Sean Davis** (08:15:04):
> Datasets available at github:[https://github.com/Wytz/Drug_efficacy](https://github.com/Wytz/Drug_efficacy)
  - Attachment (GitHub): [Wytz/Drug_efficacy](https://github.com/Wytz/Drug_efficacy)
> Using predicate and provenance information from a knowledge graph for drug efficacy screening - Wytz/Drug_efficacy


## 2018-12-14

**Rena Yang** (12:45:15):
> @Rena Yang has joined the channel


## 2019-03-28

**bioinfodirtyjobs** (06:52:02):
> @bioinfodirtyjobs has joined the channel


## 2019-04-17

**Craig** (22:50:57):
> @Craig has joined the channel


## 2019-04-23

**Craig** (01:59:29):
> Hey folks - new to the group here, hoping to learn more about what goes into the pharmacogenomics process:slightly_smiling_face:


## 2019-05-01

**Samuela Pollack** (09:19:40):
> @Samuela Pollack has left the channel


## 2019-06-19

**ZainabAlTaie** (13:49:34):
> @ZainabAlTaie has joined the channel


## 2019-06-20

**Marko Zecevic** (19:39:29):
> @Marko Zecevic has joined the channel


## 2019-06-23

**Ameya Kulkarni** (22:09:16):
> @Ameya Kulkarni has joined the channel


## 2019-06-24

**Komal Rathi** (09:23:46):
> @Komal Rathi has joined the channel


## 2019-07-23

**Sehyun Oh** (19:09:24):
> @Sehyun Oh has left the channel


## 2019-08-14

**kipper fletez-brant** (11:50:38):
> @kipper fletez-brant has joined the channel


## 2019-12-03

**Lori Shepherd** (16:41:30):
> @Lori Shepherd has left the channel


## 2019-12-04

**Jonathan Carroll** (17:41:24):
> @Jonathan Carroll has joined the channel


## 2020-02-14

**Ines de Santiago** (04:47:24):
> @Ines de Santiago has joined the channel


## 2020-06-06

**Olagunju Abdulrahman** (19:57:42):
> @Olagunju Abdulrahman has joined the channel


## 2020-07-24

**Isha Goel** (07:46:49):
> @Isha Goel has joined the channel


## 2020-07-29

**Arshi Arora** (15:43:41):
> @Arshi Arora has joined the channel

**Riyue Sunny Bao** (17:38:10):
> @Riyue Sunny Bao has joined the channel


## 2020-07-31

**Saulius Lukauskas** (03:16:33):
> @Saulius Lukauskas has joined the channel


## 2020-08-05

**shr19818** (13:45:50):
> @shr19818 has joined the channel


## 2020-09-04

**Goutham Atla** (08:24:40):
> @Goutham Atla has joined the channel


## 2020-10-17

**Kevin Blighe** (08:24:47):
> @Kevin Blighe has joined the channel


## 2020-12-02

**Konstantinos Geles (Constantinos Yeles)** (05:43:48):
> @Konstantinos Geles (Constantinos Yeles) has joined the channel


## 2020-12-04

**Arvind Mer** (12:46:05):
> @Arvind Mer has joined the channel


## 2020-12-07

**Aoi Senju** (21:19:48):
> @Aoi Senju has joined the channel


## 2020-12-12

**Huipeng Li** (00:39:01):
> @Huipeng Li has joined the channel


## 2020-12-16

**Thomas Naake** (15:09:07):
> @Thomas Naake has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:45:08):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-24

**Kyle Alford** (11:40:53):
> @Kyle Alford has joined the channel


## 2021-03-20

**watanabe_st** (01:58:04):
> @watanabe_st has joined the channel


## 2021-04-28

**Mahmoud Ahmed** (08:06:21):
> @Mahmoud Ahmed has joined the channel


## 2021-04-29

**Ludwig Geistlinger** (14:19:43):
> @Ludwig Geistlinger has left the channel


## 2021-05-11

**Megha Lal** (16:45:25):
> @Megha Lal has joined the channel


## 2021-06-04

**Flavio Lombardo** (05:52:16):
> @Flavio Lombardo has joined the channel


## 2021-07-23

**Batool Almarzouq** (15:53:52):
> @Batool Almarzouq has joined the channel


## 2021-09-06

**Eddie** (08:23:14):
> @Eddie has joined the channel

**Eddie** (09:09:48):
> @Eddie has left the channel


## 2021-09-07

**Andrew Jaffe** (14:51:37):
> @Andrew Jaffe has joined the channel


## 2021-09-25

**Mikey C** (19:05:51):
> @Mikey C has joined the channel


## 2022-01-03

**Kurt Showmaker** (17:05:03):
> @Kurt Showmaker has joined the channel


## 2022-01-28

**Megha Lal** (11:14:09):
> @Megha Lal has left the channel


## 2022-02-10

**Susanna** (03:45:53):
> @Susanna has joined the channel


## 2022-02-23

**Paulina Paiz** (10:45:57):
> @Paulina Paiz has joined the channel


## 2022-03-21

**Pedro Sanchez** (05:02:23):
> @Pedro Sanchez has joined the channel


## 2022-05-18

**Vince Carey** (06:24:59):
> @Vince Carey has left the channel


## 2022-07-22

**Gary Sieling** (14:47:18):
> @Gary Sieling has joined the channel


## 2022-07-28

**Krithika Bhuvanesh** (13:52:56):
> @Krithika Bhuvanesh has joined the channel


## 2022-12-12

**Carlos José Ferreira da Silva** (18:57:43):
> @Carlos José Ferreira da Silva has joined the channel


## 2023-02-01

**Chiaowen Joyce Hsiao** (16:39:23):
> @Chiaowen Joyce Hsiao has joined the channel


## 2023-02-22

**Indrik Wijaya** (04:40:38):
> @Indrik Wijaya has joined the channel

**Indrik Wijaya** (04:41:01):
> @Indrik Wijaya has left the channel


## 2023-02-28

**Krithika Bhuvanesh** (16:54:09):
> @Krithika Bhuvanesh has joined the channel


## 2023-05-31

**Krithika Bhuvanesh** (14:52:29):
> @Krithika Bhuvanesh has left the channel


## 2023-07-28

**Konstantinos Daniilidis** (13:48:04):
> @Konstantinos Daniilidis has joined the channel

**Benjamin Yang** (15:58:26):
> @Benjamin Yang has joined the channel


## 2023-11-21

**Konstantinos Geles (Constantinos Yeles)** (05:39:21):
> @Konstantinos Geles (Constantinos Yeles) has left the channel


## 2024-03-09

**Cherishma Subhasa** (20:37:56):
> @Cherishma Subhasa has joined the channel


## 2024-03-26

**Sara m.morsy** (16:10:45):
> @Sara m.morsy has joined the channel


## 2024-05-14

**Lori Shepherd** (10:46:46):
> archived the channel
