---
title: "#queer-bioc"
---

## 2022-07-21

**Andres Wokaty** (13:00:00):
> @Andres Wokaty has joined the channel

**Andres Wokaty** (13:46:42):
> Anyone is interested in meeting at BioC2022?:slightly_smiling_face:

**Daniel Adediran** (14:11:15):
> @Daniel Adediran has joined the channel

**Alex Mahmoud** (14:14:17):
> @Alex Mahmoud has joined the channel

**Dan Bunis** (18:46:37):
> @Dan Bunis has joined the channel

**Peter Hickey** (18:48:11):
> @Peter Hickey has joined the channel

**Spencer Nystrom** (19:54:30):
> @Spencer Nystrom has joined the channel

**Madelyn Carlson** (21:59:49):
> @Madelyn Carlson has joined the channel


## 2022-07-22

**Assa** (01:04:03):
> @Assa has joined the channel

**Claire Rioualen** (16:01:24):
> @Claire Rioualen has joined the channel

**Claire Rioualen** (16:01:44) (in thread):
> I’ll be there!:blush:


## 2022-07-25

**Paul Villafuerte** (20:01:04):
> @Paul Villafuerte has joined the channel


## 2022-07-26

**Jamshaid Ahmad** (20:40:04):
> @Jamshaid Ahmad has joined the channel


## 2022-07-27

**Andres Wokaty** (18:12:58) (in thread):
> Any interest in meeting up for lunch tomorrow?


## 2022-07-28

**Alex Mahmoud** (11:24:55) (in thread):
> I'd do it!:slightly_smiling_face:


## 2022-07-29

**Claire Rioualen** (12:11:07) (in thread):
> Hi! How about today?

**Andres Wokaty** (12:41:09) (in thread):
> Sure. Sounds good. If we're having lunch at the same place as the previous days, maybe we can meet there.

**Claire Rioualen** (12:54:16) (in thread):
> I don't know how you guys look btw:sweat_smile:but if you spot me dont hesitate to introduce yourselves

**Alex Mahmoud** (14:04:01) (in thread):
> It us
  - File (JPEG): [image.jpg](https://community-bioc.slack.com/files/U34P8RS3B/F03RM589DTM/image.jpg)

**Andres Wokaty** (16:03:53) (in thread):
> It was great meeting everyone for lunch! Thanks for making the conference memorable. I hope we can do this at future conferences:unicorn_face::person_doing_cartwheel::smile_cat:


## 2022-08-12

**Vince Carey** (11:58:52):
> @Vince Carey has joined the channel

**Vince Carey** (11:59:05):
> [https://viterbischool.usc.edu/news/2022/08/busting-anti-queer-bias-in-text-prediction/](https://viterbischool.usc.edu/news/2022/08/busting-anti-queer-bias-in-text-prediction/)
  - Attachment (USC Viterbi | School of Engineering): [Busting Anti-Queer Bias in Text Prediction - USC Viterbi | School of Engineering](https://viterbischool.usc.edu/news/2022/08/busting-anti-queer-bias-in-text-prediction/)
> New research at USC demonstrates how to train a popular language model to remove homophobic, anti-queer bias


## 2022-08-26

**Connor Higgins** (21:05:12):
> @Connor Higgins has joined the channel


## 2023-02-09

**Wes W** (22:04:06):
> @Wes W has joined the channel


## 2024-08-12

**Erick Navarro** (14:55:29):
> @Erick Navarro has joined the channel


## 2024-08-14

**Kylie Bemis** (22:31:51):
> @Kylie Bemis has joined the channel


## 2024-08-21

**Laura Symul** (08:57:53):
> @Laura Symul has joined the channel


## 2024-11-25

**rohitsatyam102** (16:18:06):
> @rohitsatyam102 has joined the channel
