---
title: "#r-ladies"
---

## 2022-07-28

**Aedin Culhane** (16:23:21):
> @Aedin Culhane has joined the channel

**Aedin Culhane** (16:23:21):
> set the channel description: Channel for R-Ladies

**Daniela Cassol** (16:24:37):
> @Daniela Cassol has joined the channel

**Lori Shepherd** (16:24:40):
> @Lori Shepherd has joined the channel

**Charlotte Soneson** (16:24:40):
> @Charlotte Soneson has joined the channel

**Heather Turner** (16:24:40):
> @Heather Turner has joined the channel

**Lou Woodley** (16:24:40):
> @Lou Woodley has joined the channel

**Susan Holmes** (16:24:40):
> @Susan Holmes has joined the channel

**Erica Feick** (16:24:40):
> @Erica Feick has joined the channel

**Jenny Drnevich** (16:24:40):
> @Jenny Drnevich has joined the channel

**saskia** (16:24:40):
> @saskia has joined the channel

**Aedin Culhane** (16:25:18):
> set the channel description: Channel for Bioconductor users and developers who are R-Ladies.


## 2022-07-29

**Leo Lahti** (16:34:50):
> @Leo Lahti has joined the channel

**Leo Lahti** (16:35:24):
> @Leo Lahti has left the channel

**Jill Lundell** (16:37:46):
> @Jill Lundell has joined the channel

**Stephanie Hicks** (16:47:48):
> @Stephanie Hicks has joined the channel

**Stephanie Hicks** (16:48:11):
> AHH I love that this is here now!!:purple_heart::rladies:

**Stephanie Hicks** (16:51:19):
> Thank you to@Daniela Cassol(and any others!) for leading the R-Ladies Bioc Hub!

**Stephanie Hicks** (16:51:41):
> @Daniela Cassol-- feel free to sign me up for supporting you (and any others!) in this.

**Mercedeh Javanbakht Movassagh** (16:52:50):
> @Mercedeh Javanbakht Movassagh has joined the channel

**Sean Davis** (16:58:13):
> @Sean Davis has joined the channel

**Madelyn Carlson** (16:58:20):
> @Madelyn Carlson has joined the channel

**Joselyn Chávez** (16:58:31):
> @Joselyn Chávez has joined the channel

**Frederick Tan** (16:58:49):
> @Frederick Tan has joined the channel

**Nicole Ortogero** (17:04:14):
> @Nicole Ortogero has joined the channel

**Wes W** (17:04:35):
> @Wes W has joined the channel

**Janani Ravi** (17:11:44):
> @Janani Ravi has joined the channel

**Kary Oetjen** (17:28:34):
> @Kary Oetjen has joined the channel

**Kayla Interdonato** (17:43:36):
> @Kayla Interdonato has joined the channel

**Alyssa Columbus** (17:53:46):
> @Alyssa Columbus has joined the channel

**Lindsay Hayes** (18:21:47):
> @Lindsay Hayes has joined the channel

**Louise Huuki** (19:15:44):
> @Louise Huuki has joined the channel

**Thai Nguyen** (19:56:02):
> @Thai Nguyen has joined the channel

**Kelly Street** (19:56:40):
> @Kelly Street has joined the channel

**Kristyna Kupkova** (20:07:03):
> @Kristyna Kupkova has joined the channel

**Claire Rioualen** (20:12:32):
> @Claire Rioualen has joined the channel

**Lauren Fitch** (20:14:09):
> @Lauren Fitch has joined the channel

**Margaret Turner** (20:46:53):
> @Margaret Turner has joined the channel

**Alex Mahmoud** (20:46:53):
> @Alex Mahmoud has joined the channel

**Andres Wokaty** (20:46:53):
> @Andres Wokaty has joined the channel


## 2022-07-30

**Afrooz Razi** (01:16:17):
> @Afrooz Razi has joined the channel

**Valentina Lorenzi** (02:41:06):
> @Valentina Lorenzi has joined the channel

**Sara Fonseca Costa** (03:19:36):
> @Sara Fonseca Costa has joined the channel

**SILVIA GIULIA GALFRE'** (08:37:14):
> @SILVIA GIULIA GALFRE' has joined the channel

**Liz Ing-Simmons** (10:04:38):
> @Liz Ing-Simmons has joined the channel

**Brenda Pardo** (12:36:13):
> @Brenda Pardo has joined the channel

**Helena L. Crowell** (14:13:52):
> @Helena L. Crowell has joined the channel

**Arshi Arora** (17:38:49):
> @Arshi Arora has joined the channel

**Krithika Bhuvanesh** (22:53:21):
> @Krithika Bhuvanesh has joined the channel


## 2022-07-31

**Ariel Hippen** (13:36:28):
> @Ariel Hippen has joined the channel


## 2022-08-01

**Lea Seep** (04:41:16):
> @Lea Seep has joined the channel

**Mireia Ramos-Rodríguez** (05:35:15):
> @Mireia Ramos-Rodríguez has joined the channel


## 2022-08-02

**Himel Mallick** (14:41:11):
> @Himel Mallick has joined the channel

**Katharina Bosch** (15:25:38):
> @Katharina Bosch has joined the channel


## 2022-08-04

**Maria Doyle** (08:58:40):
> @Maria Doyle has joined the channel

**rebecca jaszczak** (10:59:44):
> @rebecca jaszczak has joined the channel


## 2022-08-05

**Heather Turner** (06:13:59):
> Nice to see this initiative!


## 2022-08-18

**Filip Stachura** (04:20:42):
> @Filip Stachura has joined the channel


## 2022-11-23

**ashish tp53** (01:07:22):
> @ashish tp53 has joined the channel


## 2022-11-30

**Calandra Grima** (23:45:27):
> @Calandra Grima has joined the channel


## 2022-12-15

**Mercilena Benjamin** (09:39:11):
> @Mercilena Benjamin has joined the channel


## 2023-01-10

**Atuhurira Kirabo Kakopo** (10:52:17):
> @Atuhurira Kirabo Kakopo has joined the channel


## 2023-01-21

**Hien** (16:04:10):
> @Hien has joined the channel


## 2023-01-24

**Janani Ravi** (14:08:04) (in thread):
> Hi Heather, good to see you on this slack space as well. Should we set up a call to discuss some initial logistics with a few folks from here, or I would be happy to give you a quick run-through before bringing in others? Let me know which would work best.


## 2023-03-02

**Levi Waldron** (12:26:52):
> @Levi Waldron has joined the channel

**Janani Ravi** (12:31:43):
> @Levi Waldron, please let me know if there’s a better channel to start this conversation.
> 
> Following up from the recent cab/tab meeting: could/shall we host a booth/birds-of-a-feather mini session/alternate format for BioC+R-Ladies folks? We have been talking with R-Ladies leadership to start an`R-Ladies BioC Remote`chapter. This could get the ball rolling. Thoughts?


## 2023-03-07

**Levi Waldron** (10:46:27) (in thread):
> Thanks for bringing up this idea@Janani Ravi, and sorry for the delay! I’ll mention this in today’s conference planning meeting then will figure out the best place to continue the conversation with the local organizers and for the virtual platform.


## 2023-03-08

**Laurent Gatto** (09:23:26):
> @Laurent Gatto has joined the channel

**Laurent Gatto** (09:27:00):
> Apologies for cross-posting - I posted this in the#diversebiocchannel initially and then was pointed here. As a comment to@Janani Ravimessage, I think the following the also relevant:
> > Today, I read this article "[The retention problem: Women are going into tech but are also being driven out](https://theconversation.com/the-retention-problem-women-are-going-into-tech-but-are-also-being-driven-out-200625)", that specifically mentions open source projects. Among the suggestions they have to have more welcoming project, several have been put in place by Bioconductor. There is also mention of spaces that are mainly but not exclusively for women and cite Fedora Women or Debian Women. I know that several people in the project are also involved in or interact with R-ladies. But I was wondering of a Bioconductor equivalent to the above would be welcome?
  - Attachment (The Conversation): [The retention problem: Women are going into tech but are also being driven out](https://theconversation.com/the-retention-problem-women-are-going-into-tech-but-are-also-being-driven-out-200625)
> Women are severely underrepresented in tech. Strength in numbers – communities for women and women mentoring women – can counter tech’s sexist culture and help retain women in the field.

**Jenny Drnevich** (09:41:13):
> I found this line mind-blowing:
> "Seventy percent of all the software that supports technology infrastructure is open source, which makes open-source software integral to the future of the tech workforce. Yet women[make up only 9.8%](https://doi.org/10.1145/3510460)of the people who contribute to open-source software projects."
> Any idea what Bioconductor's contributor break down by gender is?

**Jenny Drnevich** (09:41:31):
> I feel like we must be higher than the average!

**Janani Ravi** (09:45:03) (in thread):
> Yup, this is unfortunately very true indeed!! that’s why we were working with R-Ladies and women+ data science! Retention is a major problem, often not spoken of!! We should see if there’s anything we can contribute via this space.

**Namusisi Sharon** (09:58:53):
> @Namusisi Sharon has joined the channel

**Janani Ravi** (13:56:00) (in thread):
> Yeah, 10% seems remarkably low!@Lori Shepherd@Aedin Culhane@Maria Doyle, any easy way to pull these data/stats?


## 2023-03-09

**Maria Doyle** (10:49:51) (in thread):
> I might be wrong but I don't think gender of contributors is captured anywhere by Bioconductor

**Lori Shepherd** (13:07:49) (in thread):
> no we have no way to tell.  We only have names in description files really -- and emails on mailing lists

**Janani Ravi** (14:10:53) (in thread):
> understandable — maybe we have these data for all the events?

**Jenny Drnevich** (14:14:21) (in thread):
> @Erica FeickDo you have gender breakdown (from asking about pronouns) for BioC2022 attendees?


## 2023-03-10

**Erica Feick** (07:04:36) (in thread):
> yep, let me see if I can pull that today…

**Edel Aron** (15:29:57):
> @Edel Aron has joined the channel


## 2023-03-11

**Charlotte Soneson** (05:08:59) (in thread):
> There was a discussion about this in the#diversebiocchannel a few years ago. FWIW, without being an expert here, and with**big**caveats that I feel make the precise numbers somewhat meaningless, including (1) databases assuming that gender is binary and can be inferred from the reported name, (2) name databases being incomplete and coverage being very geographically biased, (3) not all maintainers actually providing a name (e.g. just initials, 'Bioconductor Package Maintainer' :[https://community-bioc.slack.com/archives/CL21357E2/p1561885679036800](https://community-bioc.slack.com/archives/CL21357E2/p1561885679036800)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/CL21357E2/p1561885679036800)
> [https://community-bioc.slack.com/archives/CL21357E2/p1561755991011300](https://community-bioc.slack.com/archives/CL21357E2/p1561755991011300) FWIW, I tried this approach some time ago, and I found it quite difficult to get reliable results in an automated way, especially without additional information (for example, many names are typically male in some countries and typically female in other). The `gender` and `genderizeR` packages implement several “methods” (underlying data sets), but there didn’t seem to be enough geographic diversity in any of them, and there were lots of names that were not assigned (including, of course, all the maintainers only providing initials), or that I could identify as misassigned by manual inspection. As an example though, these are the results I would get with two of the methods that seemed to do “best” (numbers represent unique maintainers, not packages):
> ```          genderize
> kantrowitz female male <NA>
>     either     16   69    0
>     female    111    8    0
>     male        1  456    0
>     <NA>      113  223  167```

**Charlotte Soneson** (05:10:02) (in thread):
> Maybe more representative - the self-reported presenter pronouns for the BioC2022 submissions:
  - File (PNG): [Screenshot 2023-03-11 at 11.05.23.png](https://community-bioc.slack.com/files/U34P8RS3B/F04TK8Y97NG/screenshot_2023-03-11_at_11.05.23.png)


## 2023-03-13

**Erica Feick** (12:25:15) (in thread):
> So it turns out we only asked pronouns on Open Review, not eh registration form. so if what could easily be identified from the registration list for bioc22, we had 91 female, 127 males and 204 unknown.

**Erica Feick** (12:25:36) (in thread):
> We are asking for pronouns this year on the reg form, but it is an optional question.

**Janani Ravi** (13:22:37) (in thread):
> thanks, Erica & Charlotte!


## 2023-03-22

**Keerthana** (08:07:30):
> @Keerthana has joined the channel


## 2023-03-29

**Janani Ravi** (19:53:58):
> Hi all, we will meet on Wed,***Apr 5, 2023***at***9a MT/11a ET/3p UTC***.
> Zoom details:
> > [https://ucdenver.zoom.us/j/94194166689?pwd=MmJ3dksvcmVDOFlMcVlDaHZkbTFGZz09](https://ucdenver.zoom.us/j/94194166689?pwd=MmJ3dksvcmVDOFlMcVlDaHZkbTFGZz09)Meeting ID: 941 9416 6689
> > Passcode: rlel2023
> :writing_hand:[Agenda](https://docs.google.com/document/d/1krToeCohUrPGxQrcrk5kXqRKe6jjA-D3lT8jMEzIin0/edit#)
> > Partnership between BioC / R-Ladies / Remote to start a new chapter/hub, can we start with BioC 2023 satellite events, BoF, etc.

**Stephanie Hicks** (19:57:14):
> Hey! Quick question.April 5th or 7th? Thecalendarinvite says 7th I think.Thanks@Janani Ravi!

**Janani Ravi** (23:47:11) (in thread):
> Good catch.Fixed it!!


## 2023-03-30

**Janani Ravi** (11:53:52) (in thread):
> It is Apr 5 as per the poll!:neutral_face:Fixed the invite too.


## 2023-04-18

**Janani Ravi** (12:40:43):
> Hi everyone<!here>,
> I wanted to briefly follow up on our[Apr 5 call](https://docs.google.com/document/d/1krToeCohUrPGxQrcrk5kXqRKe6jjA-D3lT8jMEzIin0/edit#heading=h.g3aec2orzxlv)w/ R-Ladies/remote leadership.
> > ***BioC2023 + R-Ladies | satellite events***We can host BioC satellite events as watch parties w/ additional local talks/professional networking/BoF events. These can be co-hosted with local R-Ladies meetup groups or maybe RUGs, although R-Ladies are centralized and have dedicated branding/followers — easy to reach out to and work with them.
> > Are any local attendees interested in hosting BoF/lunch for BioC R-Ladies? That’s perfectly fine — we can go for it!***Kick-off partnership with a blog post***We don’t yet know what to officially call our R-Ladies + BioC partnership, but we can start by announcing it to the world with a blog post/tweet/mastodon/pigeon post!***Joint events | R-Ladies + BioC***Also, we can begin hosting R-Ladies**XYZ**(local chapter) (or R-Ladies Remote) + BioC joint events right away using the local unit’s meetup audience. These can be remote/hybrid events for maximal impact — maybe the host can pick their local chapter to host, and other chapters can advertise too. Again, based on how this takes off, we can figure out next steps for our partnership. For these, we can use their meetup, zoom, calendly, YouTube, etc.***Partnership name/type***R-Ladies has never done anything like this before — so they are open to this collaboration/partnership but aren’t sure if having a remote chapter/unit for BioC is the best way to go (at least not yet)! They need to set precedence in case carpentries, rOpenSci, miR, and other R communities want this R-Ladies + X chapter too.
> > 
> > Qs? comments?


## 2023-05-03

**Rebecca Butler** (16:11:28):
> @Rebecca Butler has joined the channel


## 2023-05-31

**Alyssa Obermayer** (14:16:00):
> @Alyssa Obermayer has joined the channel


## 2023-06-07

**Kayla Jackson** (13:53:06):
> @Kayla Jackson has joined the channel

**Alyssa Obermayer** (18:30:18):
> @Alyssa Obermayer has joined the channel


## 2023-06-14

**Aedin Culhane** (21:14:15) (in thread):
> Thanks for working on this. What was the outcome?


## 2023-07-04

**Shruti Shah** (06:20:39):
> @Shruti Shah has joined the channel


## 2023-07-05

**Sonali Kumari** (16:14:10):
> @Sonali Kumari has joined the channel


## 2023-07-13

**Janani Ravi** (17:28:29):
> Hi all, anything to add to this[PR](https://github.com/Bioconductor/BiocWorkingGroups/pull/33)on the proposed new BioC + R-Ladies working group?

**Yingxin Lin** (18:16:31):
> @Yingxin Lin has joined the channel

**Sowmya Parthiban** (19:38:15):
> @Sowmya Parthiban has joined the channel


## 2023-07-15

**irem Kahveci** (18:40:10):
> @irem Kahveci has joined the channel


## 2023-07-17

**Selin Jessa** (12:31:12):
> @Selin Jessa has joined the channel


## 2023-07-19

**Heather Turner** (11:04:56) (in thread):
> Looks good to me!


## 2023-07-20

**Jenea Adams** (13:19:01):
> @Jenea Adams has joined the channel


## 2023-07-28

**Konstantinos Daniilidis** (13:47:15):
> @Konstantinos Daniilidis has joined the channel


## 2023-07-31

**Chenyue Lu** (17:50:55):
> @Chenyue Lu has joined the channel


## 2023-08-03

**Ritika Giri** (15:59:01):
> @Ritika Giri has joined the channel


## 2023-08-04

**Trisha Timpug** (09:36:06):
> @Trisha Timpug has joined the channel


## 2023-09-04

**Anna Lewkowicz** (16:54:37):
> @Anna Lewkowicz has joined the channel


## 2023-09-15

**Aakanksha Singh** (01:54:07):
> @Aakanksha Singh has joined the channel

**Leo Lahti** (04:56:09):
> @Leo Lahti has joined the channel


## 2023-09-18

**Beatriz Calvo Serra** (05:37:57):
> @Beatriz Calvo Serra has joined the channel


## 2023-11-16

**Sue McClatchy** (10:00:01):
> @Sue McClatchy has joined the channel


## 2023-12-01

**Julia Philipp** (05:09:59):
> @Julia Philipp has joined the channel


## 2023-12-27

**Cindy Reichel** (14:39:27):
> @Cindy Reichel has joined the channel


## 2024-03-11

**Melysssa Minto** (10:12:26):
> @Melysssa Minto has joined the channel


## 2024-03-27

**Jovana Maksimovic** (00:40:03):
> @Jovana Maksimovic has joined the channel


## 2024-04-13

**Ankitha Ramaiyer** (20:48:16):
> @Ankitha Ramaiyer has joined the channel


## 2024-04-25

**Mercedes Guerrero** (05:02:43):
> @Mercedes Guerrero has joined the channel


## 2024-06-09

**Janani Ravi** (21:52:35):
> Hi all, based on a recent conversation with R-Ladies leadership (Shannon Pilegi, Yanina Belini-Saibene), we decided to proceed with a potential R-Ladies BioC partnership in the following manner:
> * draft a blog post to announce | include ‘invitation to participate’ by highlighting how both BioC and R-Ladies communities mutually benefit from this interaction/partnership?
> * reach out to R-Ladies chapters to host satellite events for BioC | reach out to<#G01KMRQP3C7>to see how this would work
> * in the future, R-Ladies could add BioC events to their calendar, offer abstract pre-review, and other options to help R-Ladies participation at BioC events | could start with Euro-BioC or BioC-Asia right away!
> * host an R-Ladies dinner this and in future BioCs by announcing on our#eventsor other channels ahead of time (and on R-Ladies for bioconductor enthusiasts).
> Please let me know how you’d like to work with me on these and if you have any questions/suggestions. Looking forward to getting this partnership going! Thanks!


## 2024-06-10

**Harshitha** (09:36:00):
> @Harshitha has joined the channel


## 2024-06-14

**Harshitha** (11:00:33):
> Hi everyone! This is Harshitha and I am a biologist turned bioinformatician so my programming skills aren't the best. I analyse a wide range of omics data and am looking into practising R, especially working with Bioconductor. Are there any resources I can look into or tips to improve my skills? I appreciate any help. Thank you!

**Joselyn Chávez** (13:14:57) (in thread):
> Hi@Harshithasomething that usually helps me is looking and reproducing the vignettes of Bioconductor packages of my interest. You can access them directly from the Bioconductor website or by running in R browseVignettes(<package name>) e.g. browseVignettes(“Biostrings”)


## 2024-06-17

**Jenny Drnevich** (09:38:09) (in thread):
> Hi@Harshithawe are literally writing a paper about this right now and hope to submit by the end of the summer. Besides each package's vignettes, I'd recommend working through the 3 Carpentries-style workshops we have developed:[https://bioconductor.org/help/education-training/](https://bioconductor.org/help/education-training/). The first, bioc-intro, is a general introduction to R. The second, bioc-rnaseq, is intermediate and focused on analysis of RNA-Seq data. The third, bioc-project, is an introduction to Bioconductor specifically, it's history, the website layout, how to find packages you need, and some of the common S4 data structures used acrossed Bioc packages.
  - Attachment (bioconductor.org): [Bioconductor](https://bioconductor.org/help/education-training/)
> The Bioconductor project aims to develop and share open source software for precise and repeatable analysis of biological data. We foster an inclusive and collaborative community of developers and data scientists.


## 2024-07-05

**Margherita** (12:28:55):
> @Margherita has joined the channel


## 2024-07-11

**Hothri Moka** (07:20:13):
> @Hothri Moka has joined the channel


## 2024-07-12

**Janani Ravi** (17:14:07):
> R-Ladies+ @ BioC 2024?
> 
> Let's[meet](https://www.meetup.com/rladies-east-lansing/events/302185529)!:raised_hands:
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C35G93GJH/p1720818746340839?thread_ts=1720704602.291879&cid=C35G93GJH)
> Cross-posting w/ #r-ladies #events #bioc-conference-everyone
> 
> We're getting together later this month for a `Bioconductor + R-Ladies` meetup at Grand Rapids, MI! If you are an R-Ladies member/ally & are a computational biologist/bioinformatics developer/user, this could be for you!
> :point_right::skin-tone-3: RSVP [here on Meetup](https://www.meetup.com/rladies-east-lansing/events/302185529) :parrotconga:
> 
> :writing_hand::skin-tone-3: As a reminder, virtual registration for BioC is still open: [https://www.bioc2024.bioconductor.org/registration](https://www.bioc2024.bioconductor.org/registration) (especially affordable for trainees @ `$10`)
> Schedule: [https://www.bioc2024.bioconductor.org/schedule](https://www.bioc2024.bioconductor.org/schedule)
> 
> See you soon! :raised_hands::skin-tone-3:
> [*Please DM me if you have any questions!*]


## 2024-07-21

**Janani Ravi** (09:44:57):
> :tada:
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C35G93GJH/p1721552833388169)
> :writing_hand: New blog post announcing Bioconductor and R-Ladies collaboration. Check it out [here](https://blog.bioconductor.org/posts/2024-07-20-rladies-bioconductor-collaboration/).

**Lambda Moses** (10:47:45):
> @Lambda Moses has joined the channel

**Izabela Mamede** (13:50:39):
> @Izabela Mamede has joined the channel


## 2024-07-24

**Laura Symul** (05:34:28):
> @Laura Symul has joined the channel


## 2024-07-31

**Zahraa W Alsafwani** (17:18:55):
> @Zahraa W Alsafwani has joined the channel


## 2024-08-14

**Kylie Bemis** (22:32:03):
> @Kylie Bemis has joined the channel


## 2024-08-19

**Rema Gesaka** (09:41:15):
> @Rema Gesaka has joined the channel


## 2024-10-01

**Caroline Schreiber** (04:10:18):
> @Caroline Schreiber has joined the channel


## 2024-10-02

**Eva Hamrud** (19:07:33):
> @Eva Hamrud has joined the channel


## 2024-10-16

**Zelal Özgür Durmuş** (03:50:05):
> @Zelal Özgür Durmuş has joined the channel


## 2024-11-07

**Malvika Kharbanda** (22:11:20):
> @Malvika Kharbanda has joined the channel


## 2024-12-29

**Aleru Divine** (17:29:20):
> @Aleru Divine has joined the channel


## 2025-01-14

**neslihan oztas** (10:35:35):
> @neslihan oztas has joined the channel


## 2025-02-06

**Liz Hare** (12:00:54):
> @Liz Hare has joined the channel


## 2025-02-13

**Jasmine Daly** (17:23:53):
> @Jasmine Daly has joined the channel


## 2025-03-03

**Mildred Anashie** (11:49:56):
> @Mildred Anashie has joined the channel
