---
title: "#rcwl"
format: gfm
---


## 2020-07-29

*14:21:03 - @Qian Liu has joined the channel*
**Qian Liu** (14:21:04):
> set the channel description: The Bioconductor toolset for usage and development of reproducible bioinformatics pipelines in CWL. This is intended to be a community efforts and we welcome collaborations and contributions from the community. Look forward to working with you!

*15:42:05 - @Qiang Hu has joined the channel*
*18:00:52 - @Leonardo Collado Torres has joined the channel*
*18:00:59 - @Nick Eagles has joined the channel*
*18:01:18 - @Randall Johnson has joined the channel*
**Leonardo Collado Torres** (18:04:34):
> Hi! Nick@Nick Eagleshas been working at LIBD on a`nextflow`based pipeline, and while it's probably too far now to pivot to`Rcwl`, I'm just curious if you plan some "pipeline import/conversion" scripts or guides from`nextflow`,`snakemake`, etc to`Rcwl`or if there are other tools out there that can get you halfway there.
> 
> Also Nick, maybe you can mention to them some of the complicated dependency graph issues you encountered. I think one is for example, you have a pipeline that is step a) align, b) quantify gene counts. But what if you want to have multiple options for the aligner. Then you either have to make multiple nextflow[main.nf](http://main.nf)scripts (right Nick?) or have people manually tweak things.
> 
> Thanks again for your workshop presentation!

**Qiang Hu** (18:14:54):
> Hi@Leonardo Collado Torres, great suggestion. Actually, the snakemake and WDL provide tools to convert its scripts to CWL. I don't know whether there is a similar tool for nextflow. We have function`readCWL`to load CWL pipelines to Rcwl object.

**Qiang Hu** (18:20:30):
> We have helper functions to customize the`Rcwl`pipelines easily, so we don't have to modify any configuration file manually. For example, we want to change a default argument for one tool in a heavy pipeline. We can change it like`argument(heavyPipeline, "workflow1/worflow2/tool") <- '--abc'`, then the heavyPipeline is ready to use.

**Leonardo Collado Torres** (18:32:23):
> awesome, thanks for the info Qiang!


## 2020-07-30

**Nick Eagles** (07:40:34) (in thread):
> In nextflow you would likely make one process in[main.nf](http://main.nf)for each aligner and use if statements or the`when`declaration. Then a command-line option would specify the aligner to use. It's fairly easy for the user to choose an aligner from there, but managing input and output channels with conditional execution can get somewhat complicated (and maybe`Rcwl`does it more elegantly)

**Nick Eagles** (07:46:54) (in thread):
> In general I think nextflow's channel management is pretty difficult at first (understanding operations like`toList()`,`flatten()`, etc)

*08:51:11 - @CristinaChe has joined the channel*
*08:59:08 - @Hyun-Hwan Jeong has joined the channel*
*09:12:36 - @Nick Owen has joined the channel*
**Qiang Hu** (10:12:30) (in thread):
> Thanks for sharing your experience with nf.`Rcwl`has a simple way to manage inputs for parallel computing, e.g. a list for a list of samples per input parameter.

*11:59:17 - @Yuri Kotliarov has joined the channel*

## 2020-07-31

*13:56:48 - @bogdan tanasa has joined the channel*

## 2020-08-13

**Qiang Hu** (13:46:52):
> A request from the workshop is implemented to the`requirements`function. It is much easier to manage the container in any step.
> For example, the`bwaMRecal`combines multiple workflows (bwaAlign, markdup, BaseRecal). We can change the`bwa`version under the`bwaAlign`workflow.
> ```
> > cwlInstall("pl_bwaMRecal")
> > requirements(bwaMRecal, "bwaAlign/bwa") <- list(requireDocker("biocontainers/bwa:v0.7.17_cv1"))
> > requirements(bwaMRecal, "bwaAlign/bwa")[[1]]
>  $class
>  [1] "DockerRequirement"
> 
>  $dockerPull
>  [1] "biocontainers/bwa:v0.7.17_cv1"
> ```


## 2020-10-11

*21:42:36 - @Kozo Nishida has joined the channel*

## 2020-10-23

*13:29:18 - @Daniela Cassol has joined the channel*

## 2020-12-12

*00:38:55 - @Huipeng Li has joined the channel*

## 2021-01-22

*15:45:14 - @Annajiat Alim Rasel has joined the channel*

## 2021-04-12

**Kozo Nishida** (04:52:07):
> Hi@Qian LiuI tried[https://liubuntu.github.io/Bioc2020RCWL/articles/Bioc2020RCWL.html](https://liubuntu.github.io/Bioc2020RCWL/articles/Bioc2020RCWL.html)with
> ```
> docker pull liubuntu/bioc2020rcwl:latest
> docker run -e PASSWORD=bioconductor -p 8787:8787 -v $(pwd):/home/rstudio/outdir -d --privileged liubuntu/bioc2020rcwl
> ```
> and got the following error:
> ```
> > library(Rcwl)
> > library(RcwlPipelines)
> Loading required package: BiocFileCache
> Loading required package: dbplyr
> > atls <- cwlUpdate()  ## sync the tools/pipelines
> Update scripts...
> trying URL '[https://github.com/hubentu/RcwlRecipes/archive/master.zip](https://github.com/hubentu/RcwlRecipes/archive/master.zip)'
> downloaded 316 KB
> 
> Error in cwlProcess(baseCommand = "table_annovar.pl", requirements = list(req1,  : 
>   could not find function "cwlProcess"
> ```
> Is the cwlProcess function gone now?
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F01TW6S3WKX/image.png)

**Kozo Nishida** (11:58:50):
> And the I got the "could not find function "cwlProcess" Error" with the Hello World example too.
> If there is something that I should do, please let me know.
> ```
> > library(Rcwl)
> > inputs <- InputParamList(
> +     InputParam(id = "sth")
> + )
> > echo <- cwlProcess(baseCommand = "echo", inputs)
> Error in cwlProcess(baseCommand = "echo", inputs) : 
>   could not find function "cwlProcess"
> > echo$sth <- "Hello World!"
> Error in echo$sth <- "Hello World!" : object 'echo' not found
> > res <- runCWL(echo)
> Error in inputs(cwl) : object 'echo' not found
> ```

**Qian Liu** (12:12:44):
> Hi@Kozo Nishida, thank you for raising up this question. This docker image was for Bioc2020 workshop. We have made some significant update to the packages recently, especially due to the manuscript submission to Bioinformatics (which was already accepted and the advance version is available here:[https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btab208/6194565](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btab208/6194565)).

**Qian Liu** (12:13:59):
> The`cwlProcess`is actually a new function which was renamed from`cwlParam.`

**Qian Liu** (12:22:22):
> ```
> The error can be fixed by specifying the version 1.6 for now: atls <- cwlUpdate(branch="rcwl1.6")
> ```

**Qian Liu** (12:22:46):
> After the new release in the end of April, all the new features/functions/recipes will be available in the new release.

**Kozo Nishida** (12:24:55):
> Thank you for the information! I understand.

**Qian Liu** (12:25:00):
> If you are interested, you can also run the new workshop material we have prepared for the RLadies-Tunis in March, which includes a real example for scRNA-seq pre-processing.[https://github.com/rworkflow/Rcwl_scRNAseq](https://github.com/rworkflow/Rcwl_scRNAseq)


## 2021-05-11

*16:45:30 - @Megha Lal has joined the channel*

## 2021-06-04

*08:57:02 - @Izaskun Mallona has joined the channel*

## 2022-01-28

*11:14:19 - @Megha Lal has left the channel*

## 2022-12-23

*09:35:13 - @Nicholas Cooley has joined the channel*

## 2023-08-03

*10:51:51 - @Jill Lundell has joined the channel*
*15:59:14 - @Ritika Giri has joined the channel*

## 2023-08-04

*10:49:40 - @Ray Su has joined the channel*

## 2024-05-14

**Lori Shepherd** (10:26:10):
> archived the channel
