---
title: "#reproducibility"
format: gfm
---

## 2020-07-21

**Kevin Rue-Albrecht** (10:08:41):
> @Kevin Rue-Albrecht has joined the channel

**Kevin Rue-Albrecht** (10:08:41):
> set the channel description: Solutions for reproducible workflows and environments

**Charlie George** (10:12:30):
> @Charlie George has joined the channel


## 2020-07-31

**Erick Cuevas** (12:03:32):
> @Erick Cuevas has joined the channel

**Lambda Moses** (12:05:18):
> @Lambda Moses has joined the channel

**Daniela Cassol** (12:05:27):
> @Daniela Cassol has joined the channel

**Charlotte Soneson** (12:15:55):
> @Charlotte Soneson has joined the channel

**Paula Beati** (12:19:46):
> @Paula Beati has joined the channel

**Qian Liu** (12:21:05):
> @Qian Liu has joined the channel

**Qiang Hu** (12:21:44):
> @Qiang Hu has joined the channel

**Zuzanna Nowicka** (12:54:22):
> @Zuzanna Nowicka has joined the channel

**Vivek Das** (12:58:53):
> @Vivek Das has joined the channel

**Charlie George** (13:00:14):
> Thanks for joining the discussion

**Charlie George** (13:01:09):
> @Sara Keeblewould you mind mentioning why airflow is your chosen choice, what does it do well and have you used others that didn't come up to scratch?

**Sara Keeble** (13:01:15):
> @Sara Keeble has joined the channel

**Charlie George** (13:08:26):
> Here is the link to the google doc feel free to add your thoughts, the more the merrier and there is no such thins as a 'stupid opinion' thanks[https://docs.google.com/document/d/1ok2H9HVoa8c-m-VcwdQM0ccOuMTmESKCzaaWHb6trwE/edit#](https://docs.google.com/document/d/1ok2H9HVoa8c-m-VcwdQM0ccOuMTmESKCzaaWHb6trwE/edit#)

**Sara Keeble** (13:23:13):
> Hi@Charlie George, I actually wasn't the one who chose airflow for our team, so I can't offer much in the way of comparisons. However, I've been happy with the performance relative to Luigi, which is what we were using before airflow. The main pipeline we've developed in airflow is complex and has to be run frequently, so the most important features for us are the ability to 1) handle tasks with many dependency relationships, and 2) little hands-on management time. The previous iteration of the pipeline in Luigi required a lot of babysitting and manual restarting. Of course, some of the burden of managing babysitting time falls on writing good idempotent tasks. The final thing that's important for us is integration with Jenkins, which is what we use for automated regression testing. Overall, I think it works really well for production-level code.

**Nathan Sheffield** (16:10:34):
> @Nathan Sheffield has joined the channel

**Lori Shepherd** (16:11:53):
> @Lori Shepherd has joined the channel


## 2020-08-05

**shr19818** (13:47:37):
> @shr19818 has joined the channel

**Charlotte Soneson** (17:08:32):
> [https://www.biorxiv.org/content/10.1101/2020.08.04.236208v1](https://www.biorxiv.org/content/10.1101/2020.08.04.236208v1)


## 2020-08-06

**Laurent Gatto** (13:01:34):
> @Laurent Gatto has joined the channel


## 2020-09-25

**Anna Liza Kretzschmar** (22:55:48):
> @Anna Liza Kretzschmar has joined the channel


## 2020-10-11

**Kozo Nishida** (21:42:38):
> @Kozo Nishida has joined the channel


## 2020-10-14

**Nathan Sheffield** (08:35:09):
> hey all, I posted a preprint last week describing PEP, which helps with standardizing the descriptions of samples that you would then put into a workflow. check it out if interested:[https://www.biorxiv.org/content/10.1101/2020.10.08.331322v1.full](https://www.biorxiv.org/content/10.1101/2020.10.08.331322v1.full)

**Kevin Rue-Albrecht** (18:02:38):
> that sounds awesome! on my list to read, thanks!

**Kevin Rue-Albrecht** (18:03:27):
> i gotta say, my first reaction was "what's that gotta do with PEP8":wink:


## 2020-10-23

**Rebecca Howard** (08:18:25):
> @Rebecca Howard has joined the channel


## 2020-10-30

**Nathan Sheffield** (15:28:15):
> yeah, seems like the space of acronyms is getting kind of crowded these days. I hoped it was a distant enough concept that it wouldn't confuse too many people...


## 2020-11-02

**Johannes Rainer** (10:02:17):
> @Johannes Rainer has joined the channel


## 2020-11-11

**Joshua Shapiro** (09:09:27):
> @Joshua Shapiro has joined the channel


## 2020-11-12

**Philippe Boileau** (15:09:04):
> @Philippe Boileau has joined the channel


## 2020-11-30

**Roy Storey** (04:56:03):
> @Roy Storey has joined the channel


## 2020-12-02

**Konstantinos Geles (Constantinos Yeles)** (05:43:53):
> @Konstantinos Geles (Constantinos Yeles) has joined the channel


## 2020-12-12

**Huipeng Li** (00:38:50):
> @Huipeng Li has joined the channel


## 2020-12-14

**Nick Owen** (13:21:32):
> @Nick Owen has joined the channel


## 2020-12-17

**Manojkumar Selvaraju** (11:10:08):
> @Manojkumar Selvaraju has joined the channel


## 2021-01-01

**Bernd** (14:06:18):
> @Bernd has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:45:15):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-02

**Sanchit Saini** (17:16:59):
> @Sanchit Saini has joined the channel


## 2021-02-12

**Janani Ravi** (15:53:06):
> @Janani Ravi has joined the channel


## 2021-03-12

**Julia Romanowska** (14:51:49):
> @Julia Romanowska has joined the channel


## 2021-03-20

**watanabe_st** (01:58:17):
> @watanabe_st has joined the channel


## 2021-04-12

**Naohisa Goto** (00:28:47):
> @Naohisa Goto has joined the channel


## 2021-04-28

**Mahmoud Ahmed** (08:06:30):
> @Mahmoud Ahmed has joined the channel


## 2021-05-01

**Arjun Krishnan** (21:43:57):
> @Arjun Krishnan has joined the channel


## 2021-05-11

**Megha Lal** (16:45:31):
> @Megha Lal has joined the channel


## 2021-05-28

**Izaskun Mallona** (10:16:03):
> @Izaskun Mallona has joined the channel


## 2021-06-05

**KP** (17:22:07):
> @KP has joined the channel


## 2021-07-19

**Leo Lahti** (17:02:18):
> @Leo Lahti has joined the channel


## 2021-07-23

**Batool Almarzouq** (15:53:56):
> @Batool Almarzouq has joined the channel


## 2021-07-30

**Tom Sinden** (04:19:35):
> @Tom Sinden has joined the channel


## 2021-09-25

**Haichao Wang** (07:20:42):
> @Haichao Wang has joined the channel


## 2021-11-08

**Paula Nieto García** (03:29:17):
> @Paula Nieto García has joined the channel


## 2021-11-24

**Helge Hecht** (13:16:26):
> @Helge Hecht has joined the channel


## 2022-01-28

**Megha Lal** (11:14:21):
> @Megha Lal has left the channel


## 2022-05-03

**Ray Su** (06:56:23):
> @Ray Su has joined the channel


## 2022-07-04

**Andrew J. Rech** (19:46:00):
> @Andrew J. Rech has joined the channel


## 2022-07-22

**Gary Sieling** (14:49:04):
> @Gary Sieling has joined the channel


## 2022-07-28

**Krithika Bhuvanesh** (13:53:01):
> @Krithika Bhuvanesh has joined the channel

**Mervin Fansler** (17:20:41):
> @Mervin Fansler has joined the channel


## 2022-08-11

**Rene Welch** (17:15:58):
> @Rene Welch has joined the channel


## 2022-08-15

**Michael Kaufman** (13:15:25):
> @Michael Kaufman has joined the channel


## 2022-09-04

**Gurpreet Kaur** (15:02:03):
> @Gurpreet Kaur has joined the channel


## 2022-09-27

**Jennifer Holmes** (16:17:22):
> @Jennifer Holmes has joined the channel


## 2022-12-13

**Lea Seep** (08:58:13):
> @Lea Seep has joined the channel


## 2022-12-23

**Pierre Gestraud** (08:42:16):
> @Pierre Gestraud has joined the channel


## 2023-01-21

**Hien** (16:04:17):
> @Hien has joined the channel


## 2023-02-28

**Krithika Bhuvanesh** (16:54:14):
> @Krithika Bhuvanesh has joined the channel


## 2023-03-16

**Roger Giné Bertomeu** (04:21:25):
> @Roger Giné Bertomeu has joined the channel


## 2023-05-03

**Rebecca Butler** (16:17:02):
> @Rebecca Butler has joined the channel


## 2023-05-11

**Krithika Bhuvanesh** (16:29:48):
> @Krithika Bhuvanesh has left the channel


## 2023-05-25

**Jacob Krol** (17:14:03):
> @Jacob Krol has joined the channel


## 2023-07-13

**Brian Schilder** (07:02:50):
> @Brian Schilder has joined the channel


## 2023-07-28

**Konstantinos Daniilidis** (13:47:55):
> @Konstantinos Daniilidis has joined the channel

**Benjamin Yang** (15:58:33):
> @Benjamin Yang has joined the channel


## 2023-08-03

**Jill Lundell** (10:51:54):
> @Jill Lundell has joined the channel

**Ritika Giri** (15:59:16):
> @Ritika Giri has joined the channel

**Abiud Cantu** (17:16:34):
> @Abiud Cantu has joined the channel


## 2023-08-07

**Jiaji George Chen** (11:22:18):
> @Jiaji George Chen has joined the channel


## 2023-08-20

**Jacques SERIZAY** (10:39:23):
> @Jacques SERIZAY has joined the channel


## 2023-09-15

**Leo Lahti** (04:56:19):
> @Leo Lahti has joined the channel


## 2024-03-21

**Francesc Català-Moll** (02:20:46):
> @Francesc Català-Moll has joined the channel


## 2024-03-22

**Stevie Pederson** (02:13:27):
> @Stevie Pederson has joined the channel


## 2024-03-27

**abhich** (05:46:31):
> @abhich has joined the channel


## 2024-05-14

**Lori Shepherd** (10:47:29):
> archived the channel
