---
title: "#singularity"
format: gfm
---


## 2024-07-26

*10:46:43 - @Maria Doyle has joined the channel*
*10:46:50 - @Alex Mahmoud has joined the channel*
**Maria Doyle** (10:47:02):
> set the channel description: Channel to discuss singularity developments/containers

*12:41:04 - @Charlotte Soneson has joined the channel*
*12:41:59 - @Michael Lynch has joined the channel*

## 2024-10-02

*19:07:51 - @Eva Hamrud has joined the channel*

## 2025-01-09

*11:40:53 - @Ammar Sabir Cheema has joined the channel*

## 2025-04-01

**Alex Mahmoud** (14:01:50):
> Hi all! I got some time/energy this week, and re-started the effort to build (and automate building of) our containers as singularity containers as well. If you have an environment to test, especially restricted HPC type envs where docker is not available, I would appreciate any testing you might be able to do, so I get as many data points as possible as I refine the image and build stack!
> ```
> apptainer remote add --no-login SylabsCloud cloud.sycloud.io
> apptainer remote use SylabsCloud
> singularity pull --arch amd64[library://almahmoud/almahmoud/bioconductor:3.20](library://almahmoud/almahmoud/bioconductor:3.20)
> ```


## 2025-04-03

*12:28:47 - @Kasper D. Hansen has joined the channel*
**Kasper D. Hansen** (12:29:14):
> Shouldn't this be rolled into#containers


## 2025-04-06

**Alex Mahmoud** (23:49:57):
> I think that's a good idea long term, but might be useful to have a smaller dedicated channel while developing, to not have apptainer/singularity conversations get diluted/lost. However I don't have  strong feelings either way tbh so happy to defer to others
