---
title: "#support-site"
format: gfm
---

## 2019-08-30

**Martin Morgan** (09:59:01):
> @Martin Morgan has joined the channel

**Martin Morgan** (09:59:02):
> set the channel description: Bug reports and feature requests for updated support site

**Michael Love** (09:59:02):
> @Michael Love has joined the channel

**Mike Smith** (09:59:02):
> @Mike Smith has joined the channel

**Aaron Lun** (09:59:02):
> @Aaron Lun has joined the channel

**Gordon Smyth** (09:59:02):
> @Gordon Smyth has joined the channel

**James MacDonald** (09:59:02):
> @James MacDonald has joined the channel

**Martin Morgan** (10:01:16):
> The Biostars people (Istvan Albert and especially Natay Aberra) are spearheading an update to the 'back end' of the support site. The current iteration, based on a snapshot of the support site from a month or so ago, is at[http://supportupgrade.bioconductor.org/](http://supportupgrade.bioconductor.org/). Please take a look and report issues / feature requests here! Please avoid more public mention of the site, to avoid confusion with users...

**Natay Aberra** (10:02:50):
> @Natay Aberra has joined the channel

**Istvan Albert** (10:02:50):
> @Istvan Albert has joined the channel

**Natay Aberra** (10:41:17):
> Thanks for starting this slack@Martin Morgan, I will keep you guys updated on our progress!

**Mike Smith** (15:02:05):
> Thanks, great to know there's updates in the pipeline. One thing I immediately see on mobile is that the menu continues right out of frame.
  - File (JPEG): [Screenshot_20190830-160937_Chrome.jpg](https://community-bioc.slack.com/files/U34P8RS3B/FMW80SHMK/screenshot_20190830-160937_chrome.jpg)

**Aaron Lun** (15:56:10):
> Oh man, the search is so much better now. a.k.a. it’s actually usable.

**Michael Love** (16:19:18):
> :point_up:this is huge!

**Lori Shepherd** (20:42:59):
> @Lori Shepherd has joined the channel

**Kayla Interdonato** (20:43:00):
> @Kayla Interdonato has joined the channel

**Natay Aberra** (22:31:14):
> @Mike Smithmobile compatibility is being worked on next, it will be straightened out with the next update to the site.


## 2019-09-03

**Charlotte Soneson** (14:30:45):
> @Charlotte Soneson has joined the channel


## 2019-09-06

**Martin Morgan** (17:30:56):
> The current support site has a facebook and twitter post icon beside 'follow by email' at the bottom right of new posts, but the update does not

**Natay Aberra** (22:45:24):
> We will add those buttons to the site with the next update to the site. I have pushed an update so the tags dropdown works and shows the 800 most used tags as choices, the markdown preview is also fixed and I will add the`prettify`package so syntax highlighting works the same as it currently does, mobile compatibility has been fixed as well but we plan on reworking it more to tone down the styling.  Let me know what you  guys think.

**Natay Aberra** (23:03:33):
> To the people wanting to know what some of the new features :
> 
> 1. Inplace editing - creating/editing posts no longer redirects you to a new page.
> 
> 2. @<users> - Mention a user in posts using their handler and the user will get a message notifying them.
> 
> 3. reCAPTCHA- New users get a recaptcha field added to every form, this has greatly reduced spam on our beta test site.
> 
> 4. search bar - Better sorted and more informative search results, granted the styling will change .
> 
> 5. moderators moving posts - Moderators can move any comment to be an answer and vice versa
> 
> We still have some ways to go but have made progress in the past few months.
> Check out the new features and let us know of any issues or feedbacks.

**Aaron Lun** (23:05:09):
> 5 is also great. Common bugbear of mine.


## 2019-09-07

**Martin Morgan** (02:53:27):
> Yeah 5 is neat -- actually completely flexible -- move to a child of any post on page.

**Martin Morgan** (03:15:51):
> I'll mention two other things that sometimes seem to happen, and that have something to do with language, I think, on the 'Ask a question' page
> 
> People sometimes post what I would call a 'Question' under the 'Tutorial' type, I think because they are looking for some tutoring to answer their problem; actually looking under Tutorial on the test web site shows that most of the entries here are really questions that haven't been moderated to be Question; this is different from the Biostars site. Is there some other term that should be used, or maybe text that could appear when one choose to ask a Question vs. Tutorial vs. ..., or ...?
> 
> Another interesting phenomenon from earlier this year was a post where the person entered their job title in the 'Title' field. I asked them to update their question to have a more informative title and they provided finer resolution on their job classification. StackOverflow has a prompt 'What's your programming question? Be specific.'; maybe this type of solution could be used to address both the Question vs. Tutorial problem, and provide guidance to what is expected.
> 
> Hmm, maybe the 'body' could also contain prompts, like 'Enter the text of your question here. Use the icons above to format your post. Be sure to include a reproducible example. Conclude your post with the output of the`sessionInfo()`command.'
> 
> And along the same theme, perhaps the Tags text could be updated to 'Include the name of any Bioconductor package used', which is text already present on the original site

**Kevin Blighe** (03:19:18):
> @Kevin Blighe has joined the channel

**Natay Aberra** (09:52:01):
> That would be a fix@Kevin Blighebut I think@Martin Morganwants to prevent the problem from happening and lighten the burden on moderators. We will add a specific help text to appear when one chooses a type, much like StackOverflow. We could also change the phrasing to 'Share a tutorial', 'Ask a question', 'Post a job', ..etc. Neither of these will be foolproof and moderation might be necessary. We will also add a prompt for the body as well and make the Tags dropdown read from a text file specified in the settings. For the prompts, I will create the basic templates and show@Lori Shepherdhow to customize the templates to fit the support site better. I will let you guys know once these changes have been added.


## 2019-09-25

**Martin Morgan** (07:55:13):
> Handles. With regard to the 'handle' on the new site, people seem to sometimes tag current questions like[https://support.bioconductor.org/p/121979/#124958](https://support.bioconductor.org/p/121979/#124958)where they use`@Martin`, presumably going for my user name hoping for autocompletion. Maybe that (automatic handle based on profile 'Name:') is a better way to implement handles? Of course the auto-completion seems to be quite important for this to be useful...

**Martin Morgan** (07:57:29):
> Maybe an easy tweak is to update the name displayed in the browser tab, currently 'Biostar Forum' previously the name of the page (e.g., 'Latest Post', or the question title) but maybe consistently 'Bioconductor Support Forum'.

**Natay Aberra** (15:21:59):
> @Martin Morgan, we could add an autocompletion for the handles granted that features would take month+ to correctly implement and test but I do agree the autocompletion is important especially with handles. I added a change so that handles for new users are generated using the profile 'Name:' and the user id, for example 'Martin-1'. We can not rely solely on that name since that is not a unique attribute. Users without names are given 'user-' prefix instead of a name. We will also change handles for already existing users so they have 'Name:'  instead of 'user-' prefix. I have not pushed these changes yet because we have our hands full with another project, but I plan to by the end of this week.
> 
> Can you elaborate more on the easy tweak you suggested?

**Martin Morgan** (15:26:20):
  - File (PNG): [Screen Shot 2019-09-25 at 3.25.46 PM.png](https://community-bioc.slack.com/files/U34P8RS3B/FNRALCQN9/screen_shot_2019-09-25_at_3.25.46_pm.png)

**Martin Morgan** (15:28:41):
> the first two tabs are on the old site, the next two on the new site. The first of each group is the 'home page', the second is a particular question. My original suggestion was to have 'Bioconductor Support Forum' for all tabs; a revised approach is 'Bioconductor Support Forum' for the first tab in each group, and the post title for the second tab (so tabs on questions behave the way they do on the current support site)

**Natay Aberra** (15:31:37):
> Thanks for clarifying. We will make all tabs say 'Bioconductor Support Forum'


## 2019-09-29

**Martin Morgan** (09:39:11):
> I believe standard GUI design has 'Cancel' and 'Save' buttons or similar in the lower right, in that order, whereas here they are, e.g., 'Submit' 'Cancel' in the lower left of, e.g., 'Add comment' (I didn't look at other scenarios, but obviously these should be consistent....)

**Lori Shepherd** (19:42:07):
> It has been reported. We are hoping the upgrade will fix this issue.


## 2019-09-30

**Natay Aberra** (14:42:39):
> @Martin Morganwe shall fix the buttons to be consistent


## 2019-10-16

**Lori Shepherd** (07:18:23):
> I believe this was a specific design intention to click on the logo and go to the[bioconductor.org](http://bioconductor.org)website -  but perhaps a home page link -

**Lori Shepherd** (07:22:13):
> @Natay Aberranote for us to try more markdown specials to make sure they all appear.[https://github.com/Bioconductor/support.bioconductor.org/issues/73](https://github.com/Bioconductor/support.bioconductor.org/issues/73)


## 2019-10-19

**Aaron Lun** (13:39:49):
> Insofar as feedback is still going: I don't do this often, but image uploads on GitHub Issues have been amazing.

**Aaron Lun** (13:40:28):
> No need to point to a separate site or URL, you just drag-and-drop the image into the text box, the website (somehow!) uploads it and gives you a markdown chunk pointing to the image on Github's servers.

**Aaron Lun** (13:41:14):
> Now, the drag-and-drop magic is probably unnecessary, but it would be cool to upload images directly to the support site server without having to go through the song and dance of an external site (over which we have no control, so some posts will not make sense once the external server goes down).


## 2019-11-02

**Natay Aberra** (12:32:06):
> @Lori Shepherd, we will add a test to ensure the markdown special characters are rendered correctly.@Aaron LunCool feature! I added it to the wishlist, we will see how easy/practical it is to implement.

**Aaron Lun** (12:33:37):
> Thanks. As I said, the drag and drop is some insane magic but is probably just window dressing; the real killer feature is the fact that you can upload it directly.


## 2020-01-17

**Vince Carey** (16:20:42):
> @Vince Carey has joined the channel


## 2020-01-25

**Aaron Lun** (20:30:00):
> What is the timeline for this? I'm not getting notifications because I can't edit my profile to watch tags on some of my packages (or, in fact, the system is not even acknowledging my tags) so I'm missing a whole bunch of questions.


## 2020-01-27

**Lori Shepherd** (08:34:43):
> We have weekly check-ins -  The last biostars update we had estimated their rollout last fri -  I'll see if that happened -  Bioconductor would shoot for 2-3 weeks after that

**Natay Aberra** (13:37:13):
> Hey, just a heads up we plan on rolling out this week. We upgraded to Django 3 for improved security, amongst other things, and want to make sure all is well before releasing.

**Aaron Lun** (15:45:21):
> :konata:


## 2020-05-06

**Aaron Lun** (04:47:59):
> So. Is this happening, or what?

**Lori Shepherd** (08:31:49):
> it is happening.  Biostars is in there beta phase and plan to officially roll out beginning of june and we will follow a week or two behind them

**Lori Shepherd** (08:32:30):
> we are continuing to play around and add or fix features on the testing site that is still up if you wanted to take a fresh look

**Lori Shepherd** (08:33:10):
> [http://supportupgrade.bioconductor.org/](http://supportupgrade.bioconductor.org/)


## 2020-06-05

**Aaron Lun** (03:37:23):
> Wow, it really does seem like all the google links to the support site have been wiped out. What on earth happened?

**Aaron Lun** (11:15:50):
> I was looking for specific posts and I could only get to the upgraded support site.

**Lori Shepherd** (11:21:33):
> @Martin Morganand I are investigating

**Lori Shepherd** (11:22:15):
> We had some crawler spam issues in the past and might have blocked google in the process of blocking those.  Its under investigation

**Aaron Lun** (11:22:47):
> Okay. To be more specific, if I do something like, “Bioconductor support site scran aaron lun”, I don’t get any support site entries.


## 2020-07-08

**Devika Agarwal** (07:19:52):
> @Devika Agarwal has joined the channel


## 2020-08-19

**Aaron Lun** (20:15:14):
> oh

**Aaron Lun** (20:15:15):
> great.


## 2020-09-30

**Lori Shepherd** (11:23:04):
> We have a new testing site,  we plan on rolling out the major changes within the next two weeks -- we would appreciate everyone going on the testing site, playing around and reporting any further issues .  The testing site is at  34.224.95.209     Please report issues/concerns as an issue on the github repository[https://github.com/Bioconductor/SupportUpgrade/issues](https://github.com/Bioconductor/SupportUpgrade/issues)You should be able to log in with your current email and password that you use on the current site.   Social logins are currently unavailable but will be active soon


## 2020-10-11

**Kozo Nishida** (21:43:05):
> @Kozo Nishida has joined the channel


## 2020-10-13

**Lori Shepherd** (09:35:03):
> We think we are still about a week away from the support site upgrade rollout.  We would appreciate any additional feedback for the testing site before we officially launch.  Please access the testing site at[http://supportupgrade.bioconductor.org/](http://supportupgrade.bioconductor.org/)Please report any bugs or enhancements by opening an issue at[https://github.com/Bioconductor/SupportUpgrade/issues](https://github.com/Bioconductor/SupportUpgrade/issues)

**Michael Love** (09:42:13) (in thread):
> sorting search results by date:thumbsup:(and showing the date)

**Lori Shepherd** (09:42:54) (in thread):
> yes search functionality of the upgrade site is actually functioning which is a huge plus

**Michael Love** (09:43:40) (in thread):
> great work

**Michael Love** (09:43:49) (in thread):
> i'll try to test more in coming days

**Lori Shepherd** (09:57:19) (in thread):
> @Natay Aberrahas been putting a lot of hours in fixing things!  props to him!


## 2020-10-14

**Lori Shepherd** (08:14:18):
> I believe this was disabled when we had an attack last summer -- I can update it as a admin -- but I think its still disabled because there was a vulnerability associated with it


## 2020-10-15

**Martin Morgan** (07:24:01):
> @Natay Aberra(thanks for the work!)@Lori Shepherd[http://supportupgrade.bioconductor.org/](http://supportupgrade.bioconductor.org/)has a 500 server error now

**Lori Shepherd** (07:31:50):
> @Natay Aberranot sure if its for eveyone?  FWIW:  I can reproduce the 500 error on firefox but not on chrome

**Natay Aberra** (08:21:18):
> I can not reproduce it on my chrome or Firefox, but I am investigating the logs and will keep you guys updated.

**Natay Aberra** (10:05:51):
> The secret key was not being hardcoded so every server restart meant a new secret key was being assigned; this secret key is used to create the session key, which is then used to access the session cache.
> Now it is hardcoded, but I think some browsers would still need to clear their caches of the old stale data.@Martin Morgan@Lori Shepherdyou can clear your cache to see the working site.


## 2020-10-17

**Kevin Blighe** (08:25:40):
> @Kevin Blighe has joined the channel


## 2020-10-22

**Lori Shepherd** (09:40:16):
> The support site update will be happening today in roughtly 30 min.  The support site will be temporarily unavailable until the update is complete.  We will make an announcement on the support site and on the bioc-devel mailing list when it is okay to start posting.  Thank you for your patience and understanding.

**Lori Shepherd** (13:09:39):
> support site is back up and able to post.  Please post issues, bugs, concerns to[github.com/Bioconductor/support.bioconductor.org/issues](http://github.com/Bioconductor/support.bioconductor.org/issues)

**Christopher Eeles** (13:45:48):
> @Christopher Eeles has joined the channel


## 2020-10-23

**James MacDonald** (10:14:47):
> @Lori ShepherdI used to get emails for all posts, and now I get none. Is there a way, other than putting 500 terms in 'Watched Tags' to retrieve the old behavior?

**Lori Shepherd** (10:15:50):
> @Hervé Pagèsopened an issue for this as well[https://github.com/Bioconductor/support.bioconductor.org/issues/23](https://github.com/Bioconductor/support.bioconductor.org/issues/23)that@Natay Aberraand I will look into


## 2020-10-30

**Kevin Rue-Albrecht** (07:28:12):
> @Kevin Rue-Albrecht has joined the channel

**Kevin Rue-Albrecht** (07:30:48):
> Hi there!
> I wanted to post an announcement for EuroBioc2020 on the support website, and I get the blocked with the message
> > At least one package from[this list](http://bioconductor.org/packages/devel/BiocViews.html#___Software)is required.
> I guess I can put`Biobase`, but 1) that's not really accurate, 2) i already haev 5 other tags
> Note that i've selected "Announce News", which IMHO should not be forced to tag a package.
> Thoughts? How shall I get around the issue in the meantime?

**Alan O'C** (07:35:20):
> @Alan O'C has joined the channel

**Lori Shepherd** (07:36:14):
> I added some generics to get around this issue like Bioconductor and  some others -- let me check the file again to make sure

**Kevin Rue-Albrecht** (07:37:10):
> in that case, can you check if 'eurobioc' is one of those generics, or if you an add it please?

**Kevin Rue-Albrecht** (07:38:28):
> i love you reuse of "generics" in this case:smile:

**Lori Shepherd** (07:43:55):
> We have a  Workshop and Conference tag that should get you through and be more generic --

**Lori Shepherd** (07:44:20):
> then you can still add free form text tags like eurobio -

**Kevin Rue-Albrecht** (07:49:25):
> i should have said: here's what I had
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F01DVHF3752/image.png)

**Lori Shepherd** (07:50:37):
> I just regenerated the list -- I'll go and make case insensitive but can you try caps  Conference Worksop

**Lori Shepherd** (07:52:23):
> I also just added lower case start for conference workshop and bioconductor

**Lori Shepherd** (08:09:22) (in thread):
> does it work now?

**Kevin Rue-Albrecht** (08:10:06) (in thread):
> tags are ok, but I still have an independent issue about non ASCII characters in the post

**Kevin Rue-Albrecht** (08:10:50) (in thread):
> nvm, I copied from GDocs, and '...' got collapsed into a non ASCII single character

**Kevin Rue-Albrecht** (08:10:54) (in thread):
> all good now

**Kevin Rue-Albrecht** (08:11:08) (in thread):
> [https://support.bioconductor.org/p/p132509/](https://support.bioconductor.org/p/p132509/)

**Lori Shepherd** (08:11:15) (in thread):
> yes the issue is still open and we are looking into the ascii issue


## 2020-10-31

**Lluís Revilla** (06:35:24):
> @Lluís Revilla has joined the channel


## 2020-11-01

**Aaron Lun** (22:19:35):
> I suspect I'm not getting emails when posts are created with my "Watched tags", despite the website saying that I should get an email. Does this have some kind of interaction with the "Notifactions" being set to "local messages"?


## 2020-11-02

**Kevin Blighe** (06:05:44):
> I neither receive them

**Lori Shepherd** (07:23:09):
> could you please open an issue if you haven't already on[github.com/bioconductor/support.bioconductor.org/issues](http://github.com/bioconductor/support.bioconductor.org/issues)

**Martin Morgan** (09:00:24):
> I think the 'local messages' mean that the notifications go to the 'messages' link in the top left of the screen; change notifications to 'email' if you want email.


## 2020-11-04

**rohitsatyam102** (12:00:53):
> @rohitsatyam102 has joined the channel


## 2020-11-10

**Kevin Rue-Albrecht** (11:19:48):
> Hi all - Not sure if one of my own settings is wrong or if it's the support site that's behaving weird.
> I've been getting email notifications about this thread[https://support.bioconductor.org/p/p132778/#p132795](https://support.bioconductor.org/p/p132778/#p132795)The email says
> > Activity on a tag you are watching on[support.bioconductor.org](http://support.bioconductor.org)
> But my profile page only says I'm watching:`tvtb`,`iseeu`,`goexpress`,`isee`While the post is tagged with`R`and`EBImage`Did I miss anything?

**Aaron Lun** (11:20:29):
> at least you get emails for other people’s messages.

**Aaron Lun** (11:20:34):
> I only get emails… for my own messages!

**Kevin Blighe** (11:21:25):
> I got those for EBImage too - not sure why

**Kevin Blighe** (11:21:45):
> May have to fill out an Issue on GitHub

**Lori Shepherd** (11:22:12) (in thread):
> Its already been reported and an open issue

**Lori Shepherd** (11:22:28) (in thread):
> its already an open issue

**Kevin Rue-Albrecht** (11:32:55) (in thread):
> oh yeah i can see it, sorry !


## 2020-11-12

**Kevin Blighe** (05:36:18):
> Support site is down (10:36AM UK):[https://support.bioconductor.org/](https://support.bioconductor.org/)

**rohitsatyam102** (05:47:00):
> Yes it is

**rohitsatyam102** (05:47:14):
> IST(4:16)

**Kevin Blighe** (06:04:11):
> Now back

**Lori Shepherd** (06:06:52):
> Sorry for the inconvenience -- we will investigate what happened


## 2020-11-19

**Kevin Blighe** (08:30:56):
> @Kevin Blighe has joined the channel


## 2020-12-12

**Huipeng Li** (00:38:06):
> @Huipeng Li has joined the channel


## 2021-01-07

**Lori Shepherd** (08:31:54):
> it would be good to open an issue on the github page rather than reaching out directly.  then we can track the issue

**Lori Shepherd** (08:32:10):
> [http://github.com/bioconductor/support.bioconductor.org/issues](http://github.com/bioconductor/support.bioconductor.org/issues)


## 2021-01-20

**Luke Zappia** (03:43:40):
> @Luke Zappia has joined the channel

**Luke Zappia** (03:43:41):
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C35G93GJH/p1611130947026100?thread_ts=1611130947026100&cid=C35G93GJH)
> None of the buttons (“Add comment”, “Add answer” etc.) seem to be working for me on the support site. Possibly I’m doing something wrong but I’ve tried Chrome/Safari/incognito without any luck. If I inspect the page I see a bunch of `jQuery reference not found` errors. Anyone else having issues or is it just me?

**Luke Zappia** (03:44:55) (in thread):
> Happy to open an issue instead if that’s better (only just found out about the GitHub repo).

**Lori Shepherd** (06:36:13) (in thread):
> Thank! Looking into it.

**Sean Davis** (07:40:51):
> @Sean Davis has joined the channel


## 2021-01-22

**Annajiat Alim Rasel** (15:46:29):
> @Annajiat Alim Rasel has joined the channel


## 2021-02-06

**Aaron Lun** (04:58:43):
> Wooaoh. Depending on whether I have "add answer" open or closed, I get different syntax highlighting. Here's open:
  - File (PNG): [Screenshot from 2021-02-06 01-57-25.png](https://community-bioc.slack.com/files/U34P8RS3B/F01ME97B66Q/screenshot_from_2021-02-06_01-57-25.png)

**Aaron Lun** (04:59:00):
> And here's closed:
  - File (PNG): [Screenshot from 2021-02-06 01-57-41.png](https://community-bioc.slack.com/files/U34P8RS3B/F01M51TNH61/screenshot_from_2021-02-06_01-57-41.png)

**Aaron Lun** (05:00:10):
> This is only partially caused by my browser's dark mode. Even without dark mode enabled, typing causes the highlighting to flicker between the two variants above.


## 2021-02-09

**Lluís Revilla** (06:50:52):
> Lately I don't see/receive notifications on the site (people replying to me mainly). Am I the only one?

**Lori Shepherd** (13:44:55):
> On the support site or being emailed to you?

**Lluís Revilla** (15:12:43):
> On the support site, but I restarted the computer and now they do appear


## 2021-03-01

**USLACKBOT** (10:29:18):
> This message was deleted.

**Alan O'C** (11:11:01) (in thread):
> I must say I was curious how adding a comma would make the difference

**James MacDonald** (12:38:32) (in thread):
> Adding a missing comma will make an incorrectly formed R command work. For example
> ```
> uh <- c("this will not work" "because the comma is missing")
> ```
> I am personally mystified as to how the 'offending' post is offensive, inasmuch as it is not dissimilar to telling a child not to touch a hot stove. But ymmv.[https://support.bioconductor.org/p/123265/#9135130](https://support.bioconductor.org/p/123265/#9135130)

**Alan O'C** (12:38:58) (in thread):
> Ah I see, I was thinking in bash not R

**Alan O'C** (12:42:12) (in thread):
> I think telling a child to not touch a hot stove is inoffensive but sarcastically telling a child to touch a hot stove (which is how I parse the description) is pretty offensive. Then again I'm not a parent so ymmv

**James MacDonald** (12:52:59) (in thread):
> Are you saying you found the post itself offensive? And sarcastic?

**Alan O'C** (13:05:05) (in thread):
> The answer is not visible; I don't find anything worthy of comment about the post. I think that
> > a malicious code snippet requiring only addition of a comma in order to recursively delete the user’s home directory
> is something usually done sarcastically, yes


## 2021-03-03

**Kevin Rue-Albrecht** (05:56:31) (in thread):
> the answer (or rather comment) was deleted, but it's still somewhat indexed for search and shows this
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F01QPLYRZ5W/image.png)

**Kevin Rue-Albrecht** (05:58:41) (in thread):
> Without going into any detail, I remember that particular post, as I had mixed feelings on the educative aspect of telling what not to do, and the risk of novice/naive/non-native speaker users running the 'malicious' code.

**Kevin Rue-Albrecht** (05:59:09) (in thread):
> Though is code malicious when it comes with a warning label on the tin "I am malicious, don't run me" ?

**Alan O'C** (05:59:52) (in thread):
> I'm so confused as to why that was actually posted on that question

**Kevin Rue-Albrecht** (06:00:25) (in thread):
> At the bottom of the question, the OP writes
> > This is the code that i'm using which i borrowed from a tutorial online:

**Kevin Rue-Albrecht** (06:00:59) (in thread):
> The comment posted back went to illustrate the dangers of running 'random' code from the web

**Kevin Rue-Albrecht** (06:01:22) (in thread):
> taking the 'delete your own home directory' scenario as an example

**Alan O'C** (06:03:23) (in thread):
> Okay that makes some sense, although those among us who haven't copy-pasted a random bash snippet from stackoverflow in a moment of frustration raise your hand

**Kevin Rue-Albrecht** (06:05:31) (in thread):
> The point was valid, but not an answer to the original question.
> I'd argue that this is exactly what 'comments' as for (in contrast to 'answers'), but there may also have been issues as to how the comment was phrased, which I can't claim to remember precisely

**Alan O'C** (10:13:42) (in thread):
> Interesting. Seems like "mocking" may be a harsh judgement but obviously I'm imputing a lot without the ability to read it


## 2021-03-16

**Luke Zappia** (07:33:06):
> Not sure if this is happening elsewhere but just got this spam on a support site question[https://support.bioconductor.org/p/9135516/#9135590](https://support.bioconductor.org/p/9135516/#9135590)

**Lori Shepherd** (07:42:21):
> Thanks for reporting.  We have marked that user as a spammer and the post should be removed.


## 2021-03-18

**James MacDonald** (17:47:39):
> Why does ~~~struckthrough~~~ end up being <del>struckthrough</del> (and not even the HTML version but the actual text <del>struckthrough</del>) when it's valid markdown?

**James MacDonald** (17:48:21):
> As an example:[https://support.bioconductor.org/p/9135684/#9135736](https://support.bioconductor.org/p/9135684/#9135736)

**Lori Shepherd** (20:43:03):
> Thanks for reporting.... We will look into


## 2021-03-25

**Lluís Revilla** (06:46:16):
> I'm finding lots of search results with uninformative tags (tag1, tag2) while the question have good tags:
  - File (PNG): [Screenshot from 2021-03-25 11-42-51.png](https://community-bioc.slack.com/files/U34P8RS3B/F01RYRH8HGF/screenshot_from_2021-03-25_11-42-51.png)

**Lluís Revilla** (06:49:41):
> Is it possible to search just within a tag? Like on Stack Overflow using [limma]

**rohitsatyam102** (09:18:13):
> I can't tag people on bioconductor posts because`@`won't work.
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F01RZAGUPUP/image.png)

**Mike Smith** (09:21:47):
> To help the developers keep track of things, you can open issues at[https://github.com/Bioconductor/support.bioconductor.org/issues](https://github.com/Bioconductor/support.bioconductor.org/issues)

**Mike Smith** (09:25:47):
> set the channel topic: You can report issues at [https://github.com/Bioconductor/support.bioconductor.org/issues](https://github.com/Bioconductor/support.bioconductor.org/issues)

**Lori Shepherd** (09:27:33):
> Thanks for reporting but yes if you can open issues on GitHub so we don't lose track of them that is preferred


## 2021-03-26

**rohitsatyam102** (00:02:51) (in thread):
> Okay. Will do that. Thought this was a minor one.


## 2021-04-10

**rohitsatyam102** (14:13:55):
> Where do we post for improvement in the documentation like typo's correction or code improvement??

**USLACKBOT** (14:56:21):
> This message was deleted.


## 2021-04-12

**rohitsatyam102** (02:48:33) (in thread):
> Package documentation it was!!

**rohitsatyam102** (02:49:27) (in thread):
> Is there a specific channel for that? Please point me to it!!

**Lluís Revilla** (06:02:40) (in thread):
> You can look at the landing page of the package if there is any place to submit these issues (look for BugReport) or you can send an email to the maintainer of the package.


## 2021-05-11

**Megha Lal** (16:46:03):
> @Megha Lal has joined the channel


## 2021-06-19

**Kozo Nishida** (03:02:15):
> (This is just an idea...)
> Is it possible to cross-post from[https://support.bioconductor.org/](https://support.bioconductor.org/)to Slack(here)?
> I heard that such integration feature is useful in the a forum app (called Discourse).


## 2021-08-18

**Kevin Blighe** (06:32:25):
> Getting an error on the website. Ill message Istvan directly about it
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F02BKCV45NF/image.png)

**Lori Shepherd** (07:09:23):
> I will investigate this asap

**Lori Shepherd** (10:00:04):
> The support site is back up and running

**Lori Shepherd** (10:00:51) (in thread):
> Please don't message Istvan directly. While the biostars help and maintain a lot of the backend, the support site isnt fully maintained by biostars.


## 2021-08-19

**Michael Love** (12:33:38):
> Has anyone else noticed not getting email notifications for tagged posts? I can’t say for sure but i’ve seen posts that didn’t come through my email over the past few weeks I’d say
> 
> I know sometimes it can happen if they edit their post to add tags (right?) but i think it’s happened more often than that would explain

**Lori Shepherd** (12:45:19):
> Thanks for reporting we will check the functionality.


## 2021-08-21

**Mike Smith** (13:07:57):
> I never get emails or support site messages about posts with the biomaRt tag, but I do for some of my other followed tags. I've never worked out what's going on with that.

**Kevin Blighe** (13:21:22):
> It has never worked consistently on Biostars, either.


## 2021-08-23

**Michael Love** (06:50:16):
> I can confirm that I’m not receiving any emails currently for DESeq2 posts. Last one was about 10 days ago but there have been more since then.

**Lori Shepherd** (07:46:32) (in thread):
> Thanks. I'll open an issue on the github so we don't loose track of the report.  We will investigate further.

**Michael Love** (08:14:05) (in thread):
> thanks, sorry i'll post these as issues in the future

**Lori Shepherd** (08:15:28) (in thread):
> no problem. good to have discussion here and point out potential issues. I just don't want to loose track once we decide to investigate something


## 2021-09-04

**Kevin Blighe** (11:02:46):
> Hi, Charles seems to be addressing the site admins here:[https://support.bioconductor.org/p/9139395/](https://support.bioconductor.org/p/9139395/)

**Lori Shepherd** (14:14:05) (in thread):
> Thanks. We saw it. We were waiting to respond because we don't have the capabilities now but looking at an update to fix.  We'll respond when we know more this week


## 2021-11-15

**Lori Shepherd** (07:10:02):
> has renamed the channel from "support-site-update" to "support-site"

**Lluís Revilla** (07:12:23):
> Hi, moving here my question:
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C34NC134G/p1636974023018600)
> Hi all, I want to change the password for my user on [support.bioconductor.org](http://support.bioconductor.org) but I couldn't find a way. Did I miss some documentation or this is not possible?

**Marc Elosua** (08:32:12):
> @Marc Elosua has joined the channel

**Sean Davis** (11:11:47) (in thread):
> I believe you can just logout and then click "forgot password" on the login page to reset your password.

**Sean Davis** (11:12:25) (in thread):
> I don't think there is a way to "edit password", but I could be wrong.

**Lluís Revilla** (11:39:42) (in thread):
> Thanks! I will use that if there isn't anything else

**Peter Hickey** (17:31:38):
> @Peter Hickey has joined the channel


## 2021-11-24

**Laurent Gatto** (11:32:24):
> @Laurent Gatto has joined the channel


## 2021-12-07

**emanuela iovino** (04:10:31):
> @emanuela iovino has joined the channel


## 2021-12-14

**Megha Lal** (08:23:46):
> @Megha Lal has left the channel


## 2022-03-22

**Lluís Revilla** (11:08:31):
> @Lluís Revilla has left the channel


## 2022-04-15

**Nicole Ortogero** (15:28:45):
> @Nicole Ortogero has joined the channel


## 2022-06-30

**rohitsatyam102** (07:52:41):
> I am unable to install org.Pf.eg.db package in R 4.2, BiocManager 1.30 . Is there a tar ball available somewhere that can be used??

**Lori Shepherd** (08:07:23):
> org.Pf.plasmo.db was removed in 3.15 but older versions are found on the older landing pages:[http://bioconductor.org/packages/3.14/data/annotation/html/org.Pf.plasmo.db.html](http://bioconductor.org/packages/3.14/data/annotation/html/org.Pf.plasmo.db.html)

**rohitsatyam102** (10:29:09) (in thread):
> Thanks Lori. Got the tar file at the bottom of this page.


## 2022-09-16

**Maria Doyle** (12:18:18):
> @Maria Doyle has joined the channel


## 2022-11-03

**Haichao Wang** (12:59:32):
> @Haichao Wang has joined the channel


## 2022-12-06

**Jenny Drnevich** (09:01:39):
> @Jenny Drnevich has joined the channel

**Jenny Drnevich** (09:03:10):
> Any idea if this is/could become a problem for our support site?[https://meta.stackoverflow.com/questions/421831/temporary-policy-chatgpt-is-banned](https://meta.stackoverflow.com/questions/421831/temporary-policy-chatgpt-is-banned)
  - Attachment (Meta Stack Overflow): [Temporary policy: ChatGPT is banned](https://meta.stackoverflow.com/questions/421831/temporary-policy-chatgpt-is-banned)
> Use of ChatGPT generated text for content on Stack Overflow is temporarily banned.
> This is a temporary policy intended to slow down the influx of answers and other content created with ChatGPT. Wha...

**Kevin Rue-Albrecht** (09:27:08):
> I remember *some* occurences of spam-type messages in the support site, but my impression was that it was pretty rare. Do we have statistics on that?

**Kevin Rue-Albrecht** (09:27:29):
> I gotta say that it's a pretty thing to play with ^^
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F04EBBBAESD/image.png)

**Kevin Rue-Albrecht** (09:29:30) (in thread):
> (small mistake by the AI though: it's installing version 3.16 or BiocVersion not BiocManager, but that's pretty tricky for the AI to figure out without going into a pretty deep thorough analysis of the code in`BiocManager::install`)

**Jenny Drnevich** (09:49:13) (in thread):
> That was quite amazing

**Jenny Drnevich** (09:50:19) (in thread):
> The problem cited by Stack Overflow is that the responses sound so plausible that it takes an expert to show where it is wrong.

**Kevin Rue-Albrecht** (09:51:30) (in thread):
> indeed, I didn't mean it, but my screenshot and comment actually illustrate that perfectly: I almost missed the mistake about the 3.16 as I glossed over the response

**Alan O'C** (09:52:58) (in thread):
> Yes it also writes in a very assertive tone, even if its facts or logic are completely wrong. Hopefully it's not an issue on bioc support because the answers often parse as vaguely correct unless you really pay attention

**Kevin Rue-Albrecht** (10:15:23) (in thread):
> I know there's a ton of information all over the place for the AI to learn, but in this case... just ... wow ...
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F04DYUMSDEF/image.png)
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F04DYUQJW7M/image.png)
  - File (PNG): [image.png](https://community-bioc.slack.com/files/U34P8RS3B/F04ENP650N4/image.png)

**Kevin Rue-Albrecht** (10:21:09) (in thread):
> I missed a bit. After the first screenshot, I asked a second question: "How do I install Bioconductor?"


## 2023-04-18

**Chris Fields** (12:10:06):
> @Chris Fields has joined the channel

**Chris Fields** (12:13:59):
> Hi all,@Jenny Drnevichpointed me here (thx Jenny!).

**Chris Fields** (12:15:29):
> I’m a member on the Open Bioinformatics Foundation board, and had a few questions re: the Bioconductor support site (using the biostars webapp).  Was it terribly difficult to set up?  And how much effort is needed to maintain it?  We’ve long been looking into ways to step away from old mailman mail lists for the bio* projects (Bioperl, Biopython, Bioruby, etc), but would like something that isn’t going to be difficult to maintain.

**Chris Fields** (12:16:24):
> We’re pretty much all volunteer at the moment for what it’s worth


## 2023-04-21

**Vince Carey** (16:36:44):
> @Lori Shepherd^^


## 2023-04-24

**Lori Shepherd** (12:41:37):
> I took over after the adaption had already taken place so I can't speak on the initial set up but biostars has the idea of themes where if you use their base code you could make changes based on your needs to override the default -- this allows easier maintenance as far as keeping base code the same so you have the ability to pull/merge any updates/patches/etc that biostars implements along the way.@Natay Aberraanything else you would want to add?

**Natay Aberra** (12:57:29):
> Initial setup is notdifficultbutdoesrequiressomeknowledgewithnetworkinterfaces andpython. Biostars comes with a lot boilerplate tools ( database backups, async workers, high code coverage, easydeployments ) that make maintenance really easyand doesn’t require much except the occasional certs update. Let me know ifyou’dlike morecontext/info, canhelpgetyousetup as well if needed.
>  note:Iamdefinitelybiasedtowardsbiostars :)


## 2023-04-25

**Chris Fields** (12:31:55):
> Awesome, thanks@Lori Shepherd@Natay Aberra!  I’ll mention this to the OBF Board; this seems like a good option!


## 2023-04-26

**Chris Fields** (12:20:26):
> @Lori Shepherdone additional question: how did you manage email imports?  Is it pretty straightforward?

**Lori Shepherd** (12:21:36):
> what do you mean by email imports?

**Chris Fields** (12:23:21):
> It looks like old emails have been imported in somehow, for example (from Mike Love):[https://support.bioconductor.org/p/51957/](https://support.bioconductor.org/p/51957/)

**Chris Fields** (12:24:41):
> But maybe I’m mis-reading that?

**Lori Shepherd** (12:29:50):
> ah from an old mailing list. I'm not exactly sure how that was handle as I did not set it up initially but only took over maintenance.  Maybe@Natay Aberrahas some thoughts?

**Chris Fields** (12:31:17):
> Thx!  Might not be a huge issue for us to be honest, as most of the mail lists have been publicly archived elsewhere. But if it can be done, it might be worth looking into for us

**Natay Aberra** (15:08:41):
> These posts are olderoneswe copied over during initial setup. There iscurrentlyno way to consume emails. We use to allow users reply to emails and that wastranscribedas ananswerbut found noonereally used it

**Chris Fields** (16:23:17):
> @Natay Aberrathx.  I guess my question is**how**the initial emails were copied in (e.g. was an import script involved)?

**Natay Aberra** (16:24:14):
> Yup, an import script


## 2023-05-10

**Martin Morgan** (12:38:31):
> @Robert Castelo[mentions very significant spam](https://community-bioc.slack.com/archives/C010R4JC2TB/p1683709361746479)on the support site. I wonder if there's an online course or something going on now? There seem to be a[large number of 'new' users](https://support.bioconductor.org/user/list/)over the past couple of days (mostly well-behaved!), maybe they are being encouraged to 'sign up' and there are a few bad actors. (there's an API endpoint[https://support.bioconductor.org/api/stats/date/2023/05/09/](https://support.bioconductor.org/api/stats/date/2023/05/09/)that returns #new users per day)
  - Attachment: [Attachment](https://community-bioc.slack.com/archives/C010R4JC2TB/p1683709361746479)
> Hi, I'm subscribed to every post at the Bioc support site and in the last two days I'm getting massive amounts of SPAM at a scale that I'd say they must be produced by some sort of robot. Is there anything we can do to avoid or minimize this problem?

**Robert Castelo** (12:42:44):
> @Robert Castelo has joined the channel

**Robert Castelo** (12:46:17):
> In any case, those few bad actors are able to submit many messages at once, which to me suggests some kind of automated spam generator. If all would come from the same IP address, one could try to block that IP? just an idea, I'm not an expert in spam filtering.

**Martin Morgan** (16:57:37):
> For what it's worth the spammers seem to have emails from two domains and names like
> > bojey42141@satering.comgiyeman682@onitopia.comcirado2974@xunleu.com
> as a moderator I've taken to monitoring the 'Users' list[https://support.bioconductor.org/user/list/](https://support.bioconductor.org/user/list/)and 'ban'ing these users as soon as they show up, even before they post. Hopefully not discouraging too many new bioinformaticians...

**Lori Shepherd** (17:07:04):
> ThanksMartin. We'll look into seeing if there is a way to block those domains.  We are looking into updates tonight that hopefully also will help


## 2023-05-11

**Robert Castelo** (04:48:39):
> Thanks, this morning I had 299 messages, posted between May 10th, 20:59 CEST and May 11th 10:44 CEST.


## 2023-05-12

**Robert Castelo** (03:14:27):
> Hi, this morning I found no spam from the Bioc support site in my email, thanks@Lori Shepherdand@Martin Morganfor your efforts to quickly address this problem:raised_hands:

**Lori Shepherd** (06:26:13):
> @Natay Aberrais instrumental in updates and quick fixes. 
> Just a word of caution. We did do a roll out yesterday but we still have new account creation temporarily suspended. I plan on reopening this morning. If we see a large uptick again we will have to do more work. Just letting you know so if something happens you aren't too disheartened. Please keep us posted tho on if you start to see more

**Robert Castelo** (13:00:19):
> Ok, I'll let you know if I start getting spam again, and kudos to@Natay Aberrafor fighting this battle!!


## 2023-06-13

**Peter Hickey** (18:17:42):
> When editing this post ([https://support.bioconductor.org/p/9152727/](https://support.bioconductor.org/p/9152727/)), I had to add a package tag to be able to submit my edit even though the original post didn't require one (apologies to the***SpatialExperiment***authors). Is this something that is easily fixed?


## 2023-11-13

**Lori Shepherd** (08:47:21):
> You should be able to Bioconductor instead of a package


## 2024-04-16

**Lluís Revilla** (16:27:29):
> @Lluís Revilla has joined the channel

**Lluís Revilla** (16:35:01):
> I recently activated receiving email notifications from[support.bioconductor.org](http://support.bioconductor.org)for the tags I follow to avoid missing a question tagged with my package. I have set up weekly "Digest Preferences" but I have the notifications setting as local messages. However, I received an email from[noreply@bioconductor.org](mailto:noreply@bioconductor.org)to several emails (not in BCC) with links to several questions none of which are related to my tags. I have in "My Tags"`BioCor`, and in watched tags`BioCor`and`biocor`. In addition the post are linked without the full url: The title of the question was correct but the link was like "[http://p/9157660/](http://p/9157660/)", missing the base url of[support.bioconductor.org](http://support.bioconductor.org)which makes it harder to find the right post. I think these post are merged from all accounts as I didn't find any question related to my tags. Is there a way to improve this and receive only notifications from my tags without sending them to other people?

**Lori Shepherd** (17:25:28):
> We'll look into it. Thank you for the report


## 2024-04-19

**Frederick Tan** (09:44:20):
> @Frederick Tan has joined the channel


## 2024-04-28

**Lluís Revilla** (05:08:10):
> Is there any update on the email notification issue? I expected that changing the emails from CC to BCC would be easy/fast but today I received another email with the same problems...

**Lori Shepherd** (18:50:56):
> We have been focused on the release that occurs this week. We will look into after.  It might be helpful to open an issue for it too on the GitHub repo[https://github.com/Bioconductor/support.bioconductor.org/issues](https://github.com/Bioconductor/support.bioconductor.org/issues)


## 2024-04-29

**Lori Shepherd** (06:59:43) (in thread):
> FWIW   The changing of cc to bcc was noted before and I had made notes of where I think the change should be but didn't get around to testing as I was also waiting to see if biostars wanted to make this change on their end but never heard back.  We can proceed with testing and hopefully making the change.  Not sure if the broken urls have been reported yet or if that is new.

**Lluís Revilla** (10:56:20) (in thread):
> In my opinion avoiding exposing other emails should be a priority, keep in mind the GDPR law in Europe. You can patch the support site there and the send a PR to their repository.

**Lori Shepherd** (11:14:54) (in thread):
> it is a priority now that I realize the digest haven't been disabled.  I originally thought this was the case while we investigated.  but please also keep in mind the core team is small and there is limited personal and limited time in the day.  We deal with issues as best we can.

**Lluís Revilla** (11:16:12) (in thread):
> I know the team is small. Thanks!


## 2024-05-22

**Jenny Drnevich** (14:11:58):
> Hi! I am trying to post on the support site about trouble we are having installing a package on our cluster. I'm including the error message output but the support site won't let me post it. It just goes back to the submit page and the text box is in red. I think it might be prohibited characters? UPDATE: Same issue here ([https://support.bioconductor.org/p/117436/](https://support.bioconductor.org/p/117436/)) addressed by@Lori Shepherd8 weeks ago. I've tagged a package and[https://pages.cs.wisc.edu/~markm/ascii.html](https://pages.cs.wisc.edu/~markm/ascii.html)didn't find any non-ASCII characters but it still won't let me submit.  Here's the output I wanted to post:
> ```
> ```r
> In file included from /home/apps/software/cURL/7.53.1-IGB-gcc-8.2.0/include/curl/curl.h:2523,
>                  from ucsc/net.c:7:
> ucsc/net.c: In function 'header_get_last_modified':
> ucsc/net.c:16:47: error: 'CURLINFO_FILETIME_T' undeclared (first use in this function); did you mean 'CURLINFO_FILETIME'?
>      CURLcode status = curl_easy_getinfo(curl, CURLINFO_FILETIME_T, &last_modified);
>                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/apps/software/cURL/7.53.1-IGB-gcc-8.2.0/include/curl/typecheck-gcc.h:113:14: note: in definition of macro 'curl_easy_getinfo'
>    *_typeof_*(info) _curl_info = info;                                        \
>               ^~~~~~
> ucsc/net.c:16:47: note: each undeclared identifier is reported only once for each function it appears in
>      CURLcode status = curl_easy_getinfo(curl, CURLINFO_FILETIME_T, &last_modified);
>                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/apps/software/cURL/7.53.1-IGB-gcc-8.2.0/include/curl/typecheck-gcc.h:113:14: note: in definition of macro 'curl_easy_getinfo'
>    *_typeof_*(info) _curl_info = info;                                        \
>               ^~~~~~
> ucsc/net.c: In function 'header_get_content_length':
> ucsc/net.c:33:47: error: 'CURLINFO_CONTENT_LENGTH_DOWNLOAD_T' undeclared (first use in this function); did you mean 'CURLINFO_CONTENT_LENGTH_DOWNLOAD'?
>      CURLcode status = curl_easy_getinfo(curl, CURLINFO_CONTENT_LENGTH_DOWNLOAD_T,
>                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/apps/software/cURL/7.53.1-IGB-gcc-8.2.0/include/curl/typecheck-gcc.h:113:14: note: in definition of macro 'curl_easy_getinfo'
>    *_typeof_*(info) _curl_info = info;                                        \
>               ^~~~~~
> make: ***** [/home/apps/software/R/4.4.0-IGB-gcc-8.2.0/lib64/R/etc/Makeconf:195: ucsc/net.o] Error 1ERROR: compilation failed for package 'rtracklayer'
> * removing '/home/a-m/drnevich/R/x86_64-pc-linux-gnu-library/4.4/rtracklayer'
> Installation paths not writeable, unable to update packages
>   path: /home/apps/software/R/4.4.0-IGB-gcc-8.2.0/lib64/R/library
>   packages:
>     broom, cachem, DelayedArray, dqrng, farver, fastmap, gbRd, ggiraph,
>     KernSmooth, openssl, ragg, rmarkdown, segmented, Seurat, SparseArray,
>     systemfonts, vegan, VGAM, xfun
> Warning message:
> In install.packages(...) :
>   installation of package 'rtracklayer' had non-zero exit status
> ```


## 2024-06-05

**Arnab Mukherjee** (03:06:13):
> @Arnab Mukherjee has joined the channel


## 2024-09-26

**Tram Nguyen** (14:54:22):
> @Tram Nguyen has joined the channel


## 2024-10-01

**Marcel Ramos Pérez** (12:43:19):
> @Marcel Ramos Pérez has joined the channel

**Aidan Lakshman** (12:50:47):
> @Aidan Lakshman has joined the channel


## 2024-10-02

**Matteo Tiberti** (01:47:34):
> @Matteo Tiberti has joined the channel

**Eva Hamrud** (19:07:57):
> @Eva Hamrud has joined the channel


## 2024-10-15

**Aidan Lakshman** (07:08:45):
> Seems like another spam comment here:[https://support.bioconductor.org/p/9160175/#9160183](https://support.bioconductor.org/p/9160175/#9160183)ChatGPT response with a suspicious link

**Lori Shepherd** (07:13:39):
> thank you.  marked as spam and removed


## 2024-10-22

**Liyang Fei** (00:09:42):
> @Liyang Fei has joined the channel


## 2025-01-31

**Axel Klenk** (10:03:24):
> @Axel Klenk has joined the channel

**Axel Klenk** (10:05:32):
> Hi all, I have two questions on the support site.

**Axel Klenk** (10:17:04):
> 1. I have just answered this user question[https://support.bioconductor.org/p/9161200/](https://support.bioconductor.org/p/9161200/)and found it useful to have an immediate preview of the markdown rendering below (rather than having to switch back and forth between markdown source and final result).  However, the rendering of, e.g., three backquotes for codeblocks was not as expected, i.e., as elsewhere, and worse, the result after posting my reply looked completely different from the preview.  Is there an issue with the preview feature or am I missing something?
> 2. I'm usually ordering the LATEST questions view by UPDATE.  Since yesterday I see this question[https://support.bioconductor.org/p/9160570/](https://support.bioconductor.org/p/9160570/)among the top 10 results, although its last update was nine weeks ago?

**Lori Shepherd** (10:20:05):
> 1. It looks like you have spaces between each backtick which will cause the final rendering not to be correct.  Inline code can be a single backtick instead of the three  or remove the spaces in btween the three.   I'm not entirely sure why the preview decided to display the way it did
> 2. There was as spam reply post that was deleted on the older post. unfortunately it retains that info for the ordering

**Axel Klenk** (10:21:29):
> Thanks, Lori.  Will try to do better with my next reply.:slightly_smiling_face:

**Lori Shepherd** (10:21:58) (in thread):
> no worries.  its odd that the preview displayed differently but hopefully that tip will help in the future


## 2025-02-06

**Liz Hare** (12:01:38):
> @Liz Hare has joined the channel


## 2025-02-12

**Robert Castelo** (11:09:36):
> Hi, in the digest preferences of my support site profile I have selected "Email for every new thread (mailing list mode)", however, I have not received any email from the support site since January 30th. Does somebody has the same issue? Any hint what might be going wrong? (I've checked my Spam folder, and they are not there either)

**Marcel Ramos Pérez** (13:08:17) (in thread):
> Thanks for bringing this up. I signed up for a daily digest and I also haven't received any emails. CC@Lori Shepherd

**Lori Shepherd** (15:07:04) (in thread):
> I can look into it. We made some adjustments to try and fix the exposed emails in digest and appears to have broken sending.


## 2025-04-30

**Dario Righelli** (11:55:10):
> @Dario Righelli has joined the channel

**Dario Righelli** (11:56:44):
> Hi, I’m trying to recover the password of the user on the support site, but I’m not receiving any email.
> I also tried to signup again, and it says that the email is already in use.
> Is there any issue on that or it just takes a while?
> Thanks for any reply!

**Lori Shepherd** (12:07:00) (in thread):
> we'll look into it.  also please check spam folder as well
