---
title: "#tab_polls"
format: gfm
---

## 2020-10-01

**Vince Carey** (11:20:27):
> @Vince Carey has joined the channel

**Vince Carey** (11:20:27):
> set the channel description: polling for TAB discussion

**Simple Poll** (11:25:03):
> @Simple Poll has joined the channel

**Unknown User** (11:28:37):
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: section]
> 
> [Unsupported block type: context]

**Levi Waldron** (11:31:38):
> @Levi Waldron has joined the channel

**Charlotte Soneson** (11:31:38):
> @Charlotte Soneson has joined the channel

**Aedin Culhane** (14:32:55):
> @Aedin Culhane has joined the channel


## 2020-10-02

**Laurent Gatto** (17:39:44):
> @Laurent Gatto has joined the channel


## 2020-12-12

**Huipeng Li** (00:38:04):
> @Huipeng Li has joined the channel


## 2021-05-11

**Megha Lal** (16:46:04):
> @Megha Lal has joined the channel


## 2022-01-28

**Megha Lal** (11:12:57):
> @Megha Lal has left the channel


## 2024-05-14

**Lori Shepherd** (10:12:30):
> archived the channel
