---
title: "#translation-fr"
format: gfm
---


## 2024-08-19

*09:07:31 - @Maria Doyle has joined the channel*
*09:09:03 - @Laurent Gatto has joined the channel*
*09:09:03 - @Marie HIDJO has joined the channel*
*09:09:03 - @Susan Holmes has joined the channel*
*09:09:04 - @Laura Symul has joined the channel*
**Maria Doyle** (09:10:00):
> set the channel description: A channel for French Translation of Bioconductor documentation.
> Some info on [https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#multilingual](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#multilingual)


## 2024-10-25

*08:01:12 - @Benjamin Story has joined the channel*

## 2025-03-31

**Laurent Gatto** (08:22:02):
> Hi@Kozo Nishida- some people at my institution will get together to work on the French translation of the Bioconductor carpentries lessons in April. I guess participants will need a crowdin account? Do they need to get an invitation to work on the lessons?

*09:20:26 - @Kozo Nishida has joined the channel*
**Kozo Nishida** (14:40:49) (in thread):
> Yes, participants will need a Crowdin account. However, they don't need an invitation — they should be able to create an account on their own and start contributing.[https://bioconductor.crowdin.com/](https://bioconductor.crowdin.com/)
  - Attachment (bioconductor.crowdin.com): [Crowdin Enterprise](https://bioconductor.crowdin.com/)
    > Use Crowdin Enterprise for localization of your projects. Register now and join the global translation community.

**Laurent Gatto** (15:17:48) (in thread):
> Thanks!
